CONTAINER CKdoodle
{
	NAME		CKDOODLE;
	INCLUDE CKbase;

	GROUP ID_CKEY_PROPERTIES
	{
		GROUP
		{
			COLUMNS 2;
			BITMAPBUTTON CK_DOODLE_PREVIEW { FIT_H; }
			BUTTON			 CK_DOODLE_CHOOSE	{ }
		}

		LINK CK_DOODLE_IMAGE  { ACCEPT { 1022211; } HIDDEN; }

		STRING CK_DOODLE_TITLE { }
		STRING CK_DOODLE_BODY { OPEN; CUSTOMGUI MULTISTRING; }

		DEFAULT 1;

	}
}
