CONTAINER obevel
{
  NAME obevel;
	INCLUDE Obase;
	
	GROUP O_BEVEL_GROUP_OPTION
	{
		DEFAULT 1;
		
		LONG O_BEVEL_MODE_COMPONENT_TYPE
		{
			CYCLE
			{
				O_BEVEL_MODE_COMPONENT_TYPE_POINT;
				O_BEVEL_MODE_COMPONENT_TYPE_EDGE;
				O_BEVEL_MODE_COMPONENT_TYPE_POLYGON;
			}
		}
		
		SEPARATOR{LINE;}
		
		GROUP
		{
			COLUMNS 2;

			BUTTON O_BEVEL_RESTRICTION_ADD { FIT_H; SCALE_H; }
			BUTTON O_BEVEL_RESTRICTION_REMOVE { FIT_H; SCALE_H; }
		}

		GROUP O_BEVEL_RESTRICTION_GROUP
		{
			STRING O_BEVEL_RESTRICTION_START {  }
		}

		SEPARATOR{LINE;}

		BOOL O_BEVEL_MODE_SELECTION_ANGLE_USE {};
		REAL O_BEVEL_MODE_SELECTION_ANGLE_VAL { MIN 0; UNIT DEGREE; MINSLIDER 0; MAXSLIDER 180;CUSTOMGUI REALSLIDER; }
		
		SEPARATOR{LINE;} 

		LONG O_BEVEL_MASTER_MODE
		{
			CYCLE
			{
				O_BEVEL_MASTER_MODE_CHAMFER;
				O_BEVEL_MASTER_MODE_SOLID;
			}
		}
		
		LONG O_BEVEL_OFFSET_MODE
		{
			CYCLE
			{
				O_BEVEL_OFFSET_MODE_FIXED;
				O_BEVEL_OFFSET_MODE_RADIAL;
				O_BEVEL_OFFSET_MODE_PROPORTIONAL;
			}
		}
		
		REAL O_BEVEL_RADIUS { UNIT METER; MINSLIDER -100; MAXSLIDER 100; CUSTOMGUI REALSLIDER; }
		REAL O_BEVEL_SUB		{ MIN 0; MINSLIDER 0; MAXSLIDER 20; CUSTOMGUI REALSLIDER; }
		REAL O_BEVEL_DEPTH	{ UNIT PERCENT; MINSLIDER -100; MAXSLIDER 100; CUSTOMGUI REALSLIDER; }
		REAL O_BEVEL_SHAPING_EXTR { UNIT METER; MINSLIDER -100; MAXSLIDER 100; CUSTOMGUI REALSLIDER; }
		BOOL O_BEVEL_LIMIT	{};
	}
	
	GROUP O_BEVEL_GROUP_POLYGON
	{
		DEFAULT 1;
		REAL O_BEVEL_EXTRUSION	{ UNIT METER; MINSLIDER -100; MAXSLIDER 100; CUSTOMGUI REALSLIDER; }
		REAL O_BEVEL_POLY_ANGLE { MIN 0; UNIT DEGREE; MINSLIDER 0; MAXSLIDER 180; CUSTOMGUI REALSLIDER; }
		BOOL O_BEVEL_GROUP	{};
	}

	GROUP O_BEVEL_GROUP_SHAPING
	{
		DEFAULT 1;
		LONG O_BEVEL_SHAPING_MODE
		{
			CYCLE
			{
				O_BEVEL_SHAPING_MODE_ROUND;
				O_BEVEL_SHAPING_MODE_USER;
				O_BEVEL_SHAPING_MODE_PROFILE;
			}
		}
		
		REAL O_BEVEL_SHAPING_TENSION { UNIT PERCENT; MINSLIDER -100; MAXSLIDER 100; CUSTOMGUI REALSLIDER; }
		
		SPLINE O_BEVEL_SHAPING_SPLINE { SHOWGRID_H; SHOWGRID_V; EDIT_H; EDIT_V; }
		
		LINK O_BEVEL_SHAPING_SPLINE_LINK 
		{
			ACCEPT { Ospline; }
		}
		
		LONG O_BEVEL_SHAPING_SPLINE_PLANE
		{
			CYCLE
			{
				O_BEVEL_SHAPING_SPLINE_PLANE_XY;
				O_BEVEL_SHAPING_SPLINE_PLANE_XZ;
				O_BEVEL_SHAPING_SPLINE_PLANE_ZY;
			}
		}
		
		BOOL O_BEVEL_SHAPING_SYMMETRY {};
		BOOL O_BEVELL_SHAPING_CONSTANT {};
	}
	
	GROUP O_BEVEL_GROUP_TOPOLOGY
	{
		DEFAULT 1;
		LONG O_BEVEL_MITERING
		{
			CYCLE
			{
				O_BEVEL_MITERING_DEFAULT;
				O_BEVEL_MITERING_UNIFORM;
				O_BEVEL_MITERING_RADIAL;
				O_BEVEL_MITERING_PATCH;
			}
		}
		
		LONG O_BEVEL_CORNER_ENDING
		{
			CYCLE
			{
				O_BEVEL_CORNER_ENDING_DEFAULT;
				O_BEVEL_CORNER_ENDING_EXTEND;
				O_BEVEL_CORNER_ENDING_INSET;
			}
		}
		
		LONG O_BEVEL_PROUNDING_TYPE
		{
			CYCLE
			{
				O_BEVEL_PROUNDING_TYPE_FLAT;
				O_BEVEL_PROUNDING_TYPE_FULL;
				O_BEVEL_PROUNDING_TYPE_CONVEX;
			}
		}
		
		BOOL O_BEVEL_CORNER_NGON {};
		BOOL O_BEVEL_ROUNDING_NGON {};
		BOOL O_BEVEL_SELECTION_PHONG_BREAK {};
		BOOL O_BEVEL_SELECTION_PHONG_BREAK_M {};
	}
}
		
