CONTAINER Omeasure
{
  NAME Omeasure;

	INCLUDE Obase;
	INCLUDE ToolMeasure;

	HIDE MDATA_MEASURE_SELECTION;
	HIDE MDATA_MEASURE_NEW;
	HIDE MDATA_MEASURE_DELETE;
	HIDE MDATA_MEASURE_CREATEOBJECT;

	HIDE MDATA_COMMANDGROUP;
}
