CONTAINER Tinteraction
{
	NAME		Tinteraction;

	INCLUDE Tbase;

	GROUP		Obaselist
	{
		BOOL		INTERACTIONTAG_ENABLE { ANIM OFF; }
	}

	GROUP		ID_TAGPROPERTIES
	{
		GROUP
		{
			GROUP
			{
				COLUMNS 2;
				FIT_H;

				BOOL		INTERACTIONTAG_TWEAKABLE { ANIM OFF; SCALE_H; }
				BOOL		INTERACTIONTAG_SELECT { ANIM OFF; SCALE_H; }

				LONG		INTERACTIONTAG_SELECTEDTWEAKMODE 
				{
					ANIM OFF; 
					SCALE_H;
					CYCLE
					{
						INTERACTIONTAG_SELECTEDTWEAKMODE_INVOKE;
						INTERACTIONTAG_SELECTEDTWEAKMODE_DISABLE;
						INTERACTIONTAG_SELECTEDTWEAKMODE_ALWAYS;
					} 
				}
				BOOL		INTERACTIONTAG_DISABLEMOVE { ANIM OFF; SCALE_H; }
			}
			SEPARATOR INTERACTIONTAG_GROUP_DISPLAY { }
			GROUP
			{
				COLUMNS 2;
				FIT_H;

				BOOL		INTERACTIONTAG_HIGHLIGHT { ANIM OFF; SCALE_H; }
				BOOL		INTERACTIONTAG_HIDE_MOUSE { ANIM OFF; SCALE_H; }
				BOOL		INTERACTIONTAG_HIDE_OBJECT { ANIM OFF; SCALE_H; }
			}
		}
	}
	
	GROUP		INTERACTIONTAG_GROUP_SCRIPTING
	{
		DEFAULT 0;
		FIT_H;

		GROUP
		{
			FIT_H;
			SEPARATOR { LINE; }
			LONG INTERACTIONTAG_SCRIPT_LANGUAGE 
			{
				ANIM OFF; 
				SCALE_H; 
				CYCLE
				{
					INTERACTIONTAG_SCRIPT_LANGUAGE_NONE;
					INTERACTIONTAG_SCRIPT_LANGUAGE_PYTHON;
					INTERACTIONTAG_SCRIPT_LANGUAGE_COFFEE;
				}
			}
		}

		GROUP INTERACTIONTAG_GROUP_SCRIPT
		{
			FIT_H;

			STRING		INTERACTIONTAG_SCRIPT_PY { ANIM OFF; PYTHON; CUSTOMGUI MULTISTRING; SCALE_V; SCALE_H; }
STRING		INTERACTIONTAG_SCRIPT_COF { ANIM OFF; CUSTOMGUI MULTISTRING; READONLY; SCALE_V; SCALE_H; }
			BUTTON		INTERACTIONTAG_EDIT_SCRIPT { ANIM OFF; }
		}
	}

	GROUP		INTERACTIONTAG_GROUP_OUTPUT
	{
		DEFAULT 0;
		BOOL		INTERACTIONTAG_USERIGHTMOUSE { ANIM OFF; }
		BOOL		INTERACTIONTAG_OBJECT_SELECTED { ANIM OFF; }
		BOOL		INTERACTIONTAG_OBJECT_HIGHLIGHTED { ANIM OFF; }
		SEPARATOR { LINE; }
		BOOL		INTERACTIONTAG_OBJECT_TWEAKED { ANIM OFF; }
		SEPARATOR { LINE; }
		LONG		INTERACTIONTAG_MOUSE_BUTTON
		{ 
			ANIM OFF;
			CYCLE
			{
				INTERACTIONTAG_MOUSE_BUTTON_UP;
				INTERACTIONTAG_MOUSE_BUTTON_LEFT;
				INTERACTIONTAG_MOUSE_BUTTON_RIGHT;
			}
		}
		LONG		INTERACTIONTAG_XMOUSE { ANIM OFF; }
		LONG		INTERACTIONTAG_YMOUSE { ANIM OFF; }
		REAL		INTERACTIONTAG_MOUSE_PRESSURE { ANIM OFF; UNIT PERCENT; MIN 0; MINSLIDER 0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		REAL		INTERACTIONTAG_MOUSE_TILT { ANIM OFF; UNIT PERCENT; MIN 0; MINSLIDER 0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		REAL		INTERACTIONTAG_MOUSE_ANGLE { ANIM OFF; UNIT DEGREE; }
		REAL		INTERACTIONTAG_MOUSE_WHEEL { ANIM OFF; }
		SEPARATOR { LINE; }
		LONG		INTERACTIONTAG_XPIXELS { ANIM OFF; }
		LONG		INTERACTIONTAG_YPIXELS { ANIM OFF; }
		REAL		INTERACTIONTAG_MOUSE_TRAVEL { ANIM OFF; }
		VECTOR		INTERACTIONTAG_WORLD_DELTA { ANIM OFF; }
	}

	GROUP		INTERACTIONTAG_GROUP_POLYINFO
	{
		DEFAULT 0;
		BOOL		INTERACTIONTAG_USEPOLYINFO { ANIM OFF; }
		BOOL		INTERACTIONTAG_LIVEPOLYINFO { ANIM OFF; }
		SEPARATOR { LINE; }
		BOOL		INTERACTIONTAG_POLYINFO_HIT { ANIM OFF; }
		VECTOR		INTERACTIONTAG_POLYINFO_HITPOINT { ANIM OFF; }
		LONG		INTERACTIONTAG_POLYINFO_POLYGON { MAX 1000000000; ANIM OFF; }
		LONG		INTERACTIONTAG_POLYINFO_EDGE { MAX 1000000000; ANIM OFF; }
		LONG		INTERACTIONTAG_POLYINFO_POINT { MAX 1000000000; ANIM OFF; }
		LINK		INTERACTIONTAG_POLYINFO_SELECTIONTAG { ANIM OFF; }
		LONG		INTERACTIONTAG_POLYINFO_SELECTIONTAGINDEX { ANIM OFF; }
	}
			
	GROUP		INTERACTIONTAG_GROUP_PROXY
	{
		DEFAULT 0;
		LINK		INTERACTIONTAG_PROXY_OBJECT { ANIM OFF; ACCEPT { Obase; } }
		BOOL		INTERACTIONTAG_HIGHLIGHT_PROXY { ANIM OFF; }
		BOOL		INTERACTIONTAG_SELECT_PROXY { ANIM OFF; }
		BOOL		INTERACTIONTAG_TWEAK_PROXY { ANIM OFF; }
		SEPARATOR INTERACTIONTAG_GROUP_DYNAMICPROXY { } 
		BOOL		INTERACTIONTAG_POLYINFO_USETAGPROXY { ANIM OFF; }
		LINK		INTERACTIONTAG_POLYINFO_TAGPROXY { ANIM OFF; HIDDEN; }
	}
}
