CONTAINER ToolModelingAxis
{
	NAME ToolModelingAxis;

	GROUP MDATA_AXIS_GROUP
	{
		GROUP
		{
			COLUMNS 2;

			LONG MDATA_AXIS_MODE { CYCLE { MDATA_AXIS_MODE_WORLD; MDATA_AXIS_MODE_OBJECT; MDATA_AXIS_MODE_SELECTED; MDATA_AXIS_MODE_ROOT; MDATA_AXIS_MODE_PARENT; MDATA_AXIS_MODE_BOUNDS; MDATA_AXIS_MODE_POINTS; MDATA_AXIS_MODE_CAMERA; MDATA_AXIS_MODE_FREE; } }
			LONG MDATA_AXIS_ROT
			{
				CYCLE
				{
					MDATA_AXIS_ROT_AXIS;
					MDATA_AXIS_ROT_WORLD;
					MDATA_AXIS_ROT_OBJECT;
					MDATA_AXIS_ROT_ROOT;
					MDATA_AXIS_ROT_PARENT;
					MDATA_AXIS_ROT_NORMALS;
					MDATA_AXIS_ROT_CAMERA;
				}
			}
			BOOL MDATA_AXIS_FREE { }
			BOOL MDATA_AXIS_NORMAL_PSR { }
		}

		LINK MDATA_AXIS_OBJECT_LINK	{ ACCEPT { Obase;} }

		REAL MDATA_AXIS_BOUNDS_X { UNIT PERCENT; MIN -100.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		REAL MDATA_AXIS_BOUNDS_Y { UNIT PERCENT; MIN -100.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		REAL MDATA_AXIS_BOUNDS_Z { UNIT PERCENT; MIN -100.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		
		BOOL MDATA_AXIS_DIRTY { HIDDEN; }

//		GROUP
//		{
//			LAYOUTGROUP; COLUMNS 2;
//
//			GROUP { VECTOR MDATA_AXIS_USER_POS { UNIT METER;  CUSTOMGUI SUBDESCRIPTION; } }
//			GROUP { VECTOR MDATA_AXIS_USER_ROTATION { UNIT DEGREE; CUSTOMGUI SUBDESCRIPTION; } }
//
//			GROUP
//			{ 
//				LONG MDATA_AXIS_USER
//				{
//					CYCLE
//					{
//						MDATA_AXIS_USER_WORLD;
//						MDATA_AXIS_USER_OBJECT;
//						MDATA_AXIS_USER_CAMERA;
//					}
//				}
//			}
//			GROUP { BOOL MDATA_AXIS_USER_LOCK { } }
		}
			
		GROUP MDATA_OBJECTAXIS_GROUP
		{
			GROUP
			{
				COLUMNS 2;
				BOOL MDATA_AXIS_LOCALMANIPULATION { }
				BOOL MDATA_AXIS_GIMBALROTATION { }
			}
		}	
	
	}
}
 
