CONTAINER toolpolypen
{
	NAME toolpolypen;
	INCLUDE ToolBase;
	HIDE MDATA_COMMANDGROUP;
	GROUP MDATA_MAINGROUP
	{
		LONG MDATA_POLYPEN_DRAWMODE
		{
			CYCLE
			{
				MDATA_POLYPEN_DRAWMODE_POINTS;
				MDATA_POLYPEN_DRAWMODE_EDGES;
				MDATA_POLYPEN_DRAWMODE_POLYGONS;
			}
		}

		SEPARATOR { LINE; }

		BOOL MDATA_POLYPEN_QUADSTRIP { }
		BOOL MDATA_POLYPEN_AUTOWELD { }
		BOOL MDATA_POLYPEN_REPROJECT { }
		BOOL MDATA_POLYPEN_CREATEEDGEEXTRUED { }
		BOOL MDATA_POLYPEN_CREATENGONS { }
		
		SEPARATOR { LINE; }

		BOOL MDATA_POLYPEN_HALFCIRCLE { }
		REAL MDATA_POLYPEN_ARCANGLE { MIN 0; MAX 180; UNIT DEGREE; MINSLIDER 0; MAXSLIDER 180; CUSTOMGUI REALSLIDER; }
		LONG MDATA_POLYPEN_ARCSUBDIVISION { MIN 0; MAX 500; MINSLIDER 0; MAXSLIDER 50; CUSTOMGUI LONGSLIDER; }

		SEPARATOR { LINE; }

		REAL MDATA_POLYPEN_POLYPAINTSIZE { UNIT METER; MIN 0.001;  MINSLIDER 0.001; MAXSLIDER 200; CUSTOMGUI REALSLIDER;}
		
		SEPARATOR { LINE; }
		
		LONG MDATA_POLYPEN_EXCLUSIVEMODE
		{
			CYCLE
			{
				MDATA_POLYPEN_EXCLUSIVEMODE_POINTEDGEPOLYS;
				MDATA_POLYPEN_EXCLUSIVEMODE_POINT;
				MDATA_POLYPEN_EXCLUSIVEMODE_EDGE;
				MDATA_POLYPEN_EXCLUSIVEMODE_POLY;
				MDATA_POLYPEN_EXCLUSIVEMODE_USEMODE;
			}
		}
	}
}
