CONTAINER ToolArrange
{
  NAME ToolArrange;
	INCLUDE ToolBase;

  GROUP MDATA_MAINGROUP
  {
		GROUP
		{
			LONG MDATA_ARRANGE_MODE { ALIGN_LEFT; CYCLE { MDATA_ARRANGE_MODE_SELECTMODE; MDATA_ARRANGE_MODE_LINEAR; MDATA_ARRANGE_MODE_CIRCLE; MDATA_ARRANGE_MODE_ALONGSPLINE; } }

			BOOL MDATA_ARRANGE_LINEAR_PERSTEP { }
			BOOL MDATA_ARRANGE_CIRCLE_PERSTEP { }
			BOOL MDATA_ARRANGE_SPLINE_PERSTEP { }
		}

		GROUP ID_GROUP_POSITION
		{
			DEFAULT 1;
			GROUP
			{
				COLUMNS 4;
				BOOL MDATA_ARRANGE_LINEAR_USE_MOVE { }
				BOOL MDATA_ARRANGE_CIRCLE_USE_MOVE { }
				BOOL MDATA_ARRANGE_SPLINE_USE_MOVE { }

				BOOL MDATA_ARRANGE_LINEAR_USE_MOVE_X { }
				BOOL MDATA_ARRANGE_CIRCLE_USE_MOVE_X { }
				BOOL MDATA_ARRANGE_SPLINE_USE_MOVE_X { }

				BOOL MDATA_ARRANGE_LINEAR_USE_MOVE_Y { }
				BOOL MDATA_ARRANGE_CIRCLE_USE_MOVE_Y { }
				BOOL MDATA_ARRANGE_SPLINE_USE_MOVE_Y { }

				BOOL MDATA_ARRANGE_LINEAR_USE_MOVE_Z { }
				BOOL MDATA_ARRANGE_CIRCLE_USE_MOVE_Z { }
				BOOL MDATA_ARRANGE_SPLINE_USE_MOVE_Z { }
			}

			LINK MDATA_ARRANGE_SPLINE_LINK { ACCEPT { Obase; } }
			REAL MDATA_ARRANGE_SPLINE_STARTPOS { UNIT PERCENT; }
			REAL MDATA_ARRANGE_SPLINE_ENDPOS { UNIT PERCENT; }

			REAL MDATA_ARRANGE_CIRCLE_RADIUS { UNIT METER; }
			REAL MDATA_ARRANGE_CIRCLE_START { UNIT DEGREE; }
			REAL MDATA_ARRANGE_CIRCLE_END   { UNIT DEGREE; }

			VECTOR MDATA_ARRANGE_LINEAR_MOVE { UNIT METER; }
			VECTOR MDATA_ARRANGE_CIRCLE_MOVE { UNIT METER; }
		}

		GROUP ID_GROUP_SCALE
		{
			DEFAULT 1;

			BOOL MDATA_ARRANGE_LINEAR_USE_SCALE { }
			BOOL MDATA_ARRANGE_CIRCLE_USE_SCALE { }
			BOOL MDATA_ARRANGE_SPLINE_USE_SCALE { }

			VECTOR MDATA_ARRANGE_LINEAR_SCALE { UNIT PERCENT; }
			VECTOR MDATA_ARRANGE_CIRCLE_SCALE { UNIT PERCENT; }
			VECTOR MDATA_ARRANGE_SPLINE_SCALE { UNIT PERCENT; }
		}

		GROUP ID_GROUP_ROTATION
		{
			DEFAULT 1;

			BOOL MDATA_ARRANGE_LINEAR_USE_ROTATION { }
			BOOL MDATA_ARRANGE_CIRCLE_USE_ROTATION { }
			BOOL MDATA_ARRANGE_SPLINE_USE_ROTATION { }

			BOOL MDATA_ARRANGE_CIRCLE_ALIGNTANGENTIAL { }

			LINK MDATA_ARRANGE_SPLINE_RAIL { ACCEPT { Obase; } }
			LONG MDATA_ARRANGE_SPLINE_ALIGNTANGENTIAL
			{
				ALIGN_LEFT;
				CYCLE
				{
					MDATA_ARRANGE_SPLINE_ALIGNTANGENTIAL_X;
					MDATA_ARRANGE_SPLINE_ALIGNTANGENTIAL_XN;
					MDATA_ARRANGE_SPLINE_ALIGNTANGENTIAL_Y;
					MDATA_ARRANGE_SPLINE_ALIGNTANGENTIAL_YN;
					MDATA_ARRANGE_SPLINE_ALIGNTANGENTIAL_Z;
					MDATA_ARRANGE_SPLINE_ALIGNTANGENTIAL_ZN;
				}
			}
			REAL MDATA_ARRANGE_SPLINE_FLIP { UNIT DEGREE; }

			VECTOR MDATA_ARRANGE_LINEAR_ROTATION { UNIT DEGREE; }
			VECTOR MDATA_ARRANGE_CIRCLE_ROTATION { UNIT DEGREE; }
			VECTOR MDATA_ARRANGE_SPLINE_ROTATION { UNIT DEGREE; }
		}
  }

	GROUP MDATA_COMMANDGROUP
	{
		SHOW MDATA_APPLY;
	}
}
