CONTAINER ToolKnifePath
{
	NAME ToolKnifePath;
	INCLUDE ToolBase;
	HIDE MDATA_COMMANDGROUP;

	GROUP MDATA_MAINGROUP
	{
		DEFAULT 1;
		LONG MDATA_KNIFEPATH_MODE
		{
			CYCLE
			{
				MDATA_KNIFEPATH_MODE_LOOP;
				MDATA_KNIFEPATH_MODE_PATH;
			}
		}

		LONG MDATA_KNIFEPATH_OFFSET_MODE
		{
			CYCLE
			{
				MDATA_KNIFEPATH_OFFSET_MODE_PROPORTIONAL;
				MDATA_KNIFEPATH_OFFSET_MODE_EDGEDISTANCE;
			}
		}

		REAL MDATA_KNIFEPATH_OFFSET { UNIT PERCENT; MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER; }
		REAL MDATA_KNIFEPATH_DISTANCE { UNIT METER; MIN 0; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER; }	
		LONG MDATA_KNIFEPATH_CUT_NUMBER { MIN 1; }

		SEPARATOR { LINE; }

		BOOL MDATA_KNIFEPATH_SELECTED { }
		BOOL MDATA_KNIFEPATH_SELECT_CUT { }
		BOOL MDATA_KNIFEPATH_CUTPOLYS { }

	}
	GROUP MDATA_KNIFEPATH_INTERACTION_GROUP
	{
		DEFAULT 1;
		BOOL MDATA_KNIFEPATH_INTERACTION_STORE_LAYOUT { }
		BOOL MDATA_KNIFEPATH_INTERACTION_BIDIRECTIONAL { }
		BOOL MDATA_KNIFEPATH_INTERACTION_SYMETRY { }
		BOOL MDATA_KNIFEPATH_INTERACTION_DIRECTION { }
		BOOL MDATA_KNIFEPATH_INTERACTION_STOP_AT_NGON { }
		BOOL MDATA_KNIFEPATH_INTERACTION_STOP_AT_POLE { }

		SEPARATOR { LINE; }

		GROUP
		{
			COLUMNS 2;
			BOOL MDATA_KNIFEPATH_QUANTIZE_EDGE_SUB { }
			LONG MDATA_KNIFEPATH_QUANTIZE_EDGE_SUB_NUMBER { MIN 1; }
			BOOL MDATA_KNIFEPATH_LIMITED_RANGE { }
			LONG MDATA_KNIFEPATH_RANGE_NUMBER { MIN 1; }
		}
	}
	GROUP MDATA_KNIFEPATH_SHAPING_GROUP
	{
		DEFAULT 1;
		BOOL MDATA_KNIFEPATH_PRESERVE_CURVATURE{ }
		REAL MDATA_KNIFEPATH_PRESERVE_CURVATURE_TENSION { MIN -5; MAX 5; STEP 0.1;  MINSLIDER -5; MAXSLIDER 5; CUSTOMGUI REALSLIDER; }
		BOOL MDATA_KNIFEPATH_SPLINE_USE { }
		REAL MDATA_KNIFEPATH_SPLINE_EXTRUSION { UNIT METER;  MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER; }
		SPLINE MDATA_KNIFEPATH_SPLINE { SHOWGRID_H; SHOWGRID_V; EDIT_H; EDIT_V; }

	}
}
