CONTAINER ToolExtrude
{
  NAME ToolExtrude;
	INCLUDE ToolBase;

  GROUP MDATA_MAINGROUP
  {
		REAL MDATA_EXTRUDE_OFFSET { UNIT METER; MINSLIDER -100; MAXSLIDER 100; CUSTOMGUI REALSLIDER; STEP 1; }
		REAL MDATA_EXTRUDE_VARIANCE { UNIT PERCENT;  MIN 0; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER; STEP 1; }
		REAL MDATA_EXTRUDE_SUBDIVISION { MIN 0; MINSLIDER 0; MAXSLIDER 10; CUSTOMGUI REALSLIDER; STEP 1;}
		BOOL MDATA_EXTRUDE_CREATENGONS { }
		BOOL MDATA_EXTRUDE_PRESERVEGROUPS { }
		GROUP MDATA_EXTRUDE_POLYGON_GROUP
	  {
			DEFAULT 1;
			BOOL MDATA_EXTRUDE_CREATECAPS { }
			REAL MDATA_EXTRUDE_ANGLE { UNIT DEGREE; MIN 0; MAX 180; MINSLIDER 0; MAXSLIDER 180; CUSTOMGUI REALSLIDER; STEP 1;}
		}

		GROUP MDATA_EXTRUDE_EDGE_GROUP
	  {
			DEFAULT 1;
			REAL MDATA_EXTRUDE_EDGEANGLE { UNIT DEGREE; MINSLIDER -180; MAXSLIDER 180; CUSTOMGUI REALSLIDER; STEP 1; }
			BOOL MDATA_EXTRUDE_EDGESNAP { }
			REAL MDATA_EXTRUDE_EDGESNAPVALUE { UNIT DEGREE; MIN 0; MAX 180; MINSLIDER 0; MAXSLIDER 180; CUSTOMGUI REALSLIDER; STEP 1; }
		}

	  GROUP MDATA_EXTRUDE_POINT_GROUP
	  {			
			DEFAULT 1;
			REAL MDATA_EXTRUDE_BEVEL { UNIT METER; MINSLIDER -100; MAXSLIDER 100; CUSTOMGUI REALSLIDER; STEP 0.1; }
			REAL MDATA_EXTRUDE_BEVEL_VARIANCE { UNIT PERCENT;  MIN 0; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER; STEP 1; }
		}
	}
}
