CONTAINER ToolSplineArc
{
	NAME		ToolSplineArc;
	INCLUDE ToolBase;

	GROUP MDATA_MAINGROUP
	{
		DEFAULT 1;

		VECTOR MDATA_SPLINEARC_MIDPOINT		{ UNIT METER; ANIM OFF; SCALE_H; }
		VECTOR MDATA_SPLINEARC_ENDPOINT		{ UNIT METER; ANIM OFF; SCALE_H; }
		VECTOR MDATA_SPLINEARC_FIRSTPOINT	{ UNIT METER; ANIM OFF; SCALE_H; }

		SEPARATOR { LINE; }

		VECTOR MDATA_SPLINEARC_CENTER		{ UNIT METER; ANIM OFF; SCALE_H; }
		REAL	 MDATA_SPLINEARC_RADIUS			{ UNIT METER; MIN 0.0; ANIM OFF; }
		REAL	 MDATA_SPLINEARC_ANGLE			{ ANIM OFF; UNIT DEGREE; MIN -360.0; MAX 360.0; CUSTOMGUI REALSLIDER; }

		LONG MDATA_SPLINEARC_POINTINDEX1 { MIN 0; HIDDEN; ANIM OFF; }
		LONG MDATA_SPLINEARC_POINTINDEX2 { MIN 0; HIDDEN; ANIM OFF; }
		LINK MDATA_SPLINEARC_OBJECT1 { HIDDEN; ANIM OFF; }
		LINK MDATA_SPLINEARC_OBJECT2 { HIDDEN; ANIM OFF; }
	}
}
