CONTAINER ToolKnifeLine
{
	NAME ToolKnifeLine;
	INCLUDE ToolBase;
	HIDE MDATA_COMMANDGROUP;

	GROUP MDATA_MAINGROUP
	{
		COLUMNS 1;
		GROUP
		{
			BOOL MDATA_KNIFELINE_VISIBLE_ONLY { }

			LONG MDATA_KNIFELINE_SPLIT_MODE
			{
				CYCLE
				{
					MDATA_KNIFELINE_SPLIT_MODE_NOSPLIT;
					MDATA_KNIFELINE_SPLIT_MODE_SPLIT;
					MDATA_KNIFELINE_SPLIT_MODE_REGION_A;
					MDATA_KNIFELINE_SPLIT_MODE_REGION_B;
				}
			}

			BOOL MDATA_KNIFELINE_SINGLE { }
			BOOL MDATA_KNIFELINE_INFINITE { }

			SEPARATOR { LINE; }

			BOOL MDATA_KNIFELINE_SELECTED { }
			BOOL MDATA_KNIFELINE_SELECT_CUT { }
			BOOL MDATA_KNIFELINE_CUTPOLYS	{	}
			BOOL MDATA_KNIFELINE_NGON_CURVATURE { }
			BOOL MDATA_KNIFELINE_AUTOSNAP { }

			SEPARATOR { LINE; }


			BOOL MDATA_KNIFELINE_ANGLE_CONSTRAINT{ }
			REAL MDATA_KNIFELINE_ANGLE_CONSTRAINT_VALUE { UNIT DEGREE; MIN 0.1; MAX 180; STEP 0.1; MINSLIDER 0.1; MAXSLIDER 180; CUSTOMGUI REALSLIDER; }

			SEPARATOR { LINE; }
			BOOL MDATA_KNIFELINE_REALTIME { }
		}
	}
}
