CONTAINER ToolSplinePen
{
	NAME		ToolSplinePen;
	INCLUDE ToolBase;

	HIDE MDATA_COMMANDGROUP;

	GROUP MDATA_MAINGROUP
	{
		LONG MDATA_SPLINEPEN_MODE
		{
			CYCLE
			{
				MDATA_SPLINEPEN_MODE_LINEAR;
				MDATA_SPLINEPEN_MODE_CUBIC;
				MDATA_SPLINEPEN_MODE_AKIMA;
				MDATA_SPLINEPEN_MODE_BSPLINE;
				MDATA_SPLINEPEN_MODE_BEZIER;
			}
			ANIM OFF;
		}

		BOOL MDATA_SPLINEPEN_TANGENT_MODE { ANIM OFF; }
		BOOL MDATA_SPLINEPEN_LOCK_ROTATION { ANIM OFF; }
		BOOL MDATA_SPLINEPEN_LOCK_SCALE	{ ANIM OFF; }
		BOOL MDATA_SPLINEPEN_CREATE_SPLINES { ANIM OFF; }
	}
}
