CONTAINER ToolEdgeCut
{
  NAME ToolEdgeCut;
	INCLUDE ToolBase;

  GROUP MDATA_MAINGROUP
  {
		GROUP
		{
			REAL MDATA_EDGECUT_OFFSET { UNIT PERCENT; MIN 0.0; MAX 100.0; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 1.0; CUSTOMGUI REALSLIDER; }
			REAL MDATA_EDGECUT_SCALE  { UNIT PERCENT; MIN 0.0; MINEX; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 1.0; CUSTOMGUI REALSLIDER; }
			REAL MDATA_EDGECUT_SUBDIV { MIN 1; MAX 100; MINSLIDER 1; MAXSLIDER 10; CUSTOMGUI REALSLIDER; STEP 1;}
			BOOL MDATA_EDGECUT_CREATENGONS { }
			LONG MDATA_EDGECUT_NGONMODE
			{
				CYCLE
				{
					MDATA_EDGECUT_NGONMODE_NONE;
					MDATA_EDGECUT_NGONMODE_ALL;
					MDATA_EDGECUT_NGONMODE_CORNER;
				}
			}
		}
	}
}
