CONTAINER ToolExtrudeInner
{
  NAME ToolExtrudeInner;
	INCLUDE ToolBase;

  GROUP MDATA_MAINGROUP
  {
		REAL MDATA_EXTRUDEINNER_OFFSET { UNIT METER; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER; STEP 1;}
		REAL MDATA_EXTRUDEINNER_VARIANCE { UNIT PERCENT;  MIN 0; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER; STEP 1;}
		REAL MDATA_EXTRUDEINNER_SUBDIVISION { MIN 1; MINSLIDER 1; MAXSLIDER 10; CUSTOMGUI REALSLIDER; STEP 1;}
		BOOL MDATA_EXTRUDEINNER_CREATENGONS { }
		BOOL MDATA_EXTRUDEINNER_PRESERVEGROUPS {}
		REAL MDATA_EXTRUDEINNER_ANGLE { UNIT DEGREE; MIN 0; MAX 180; MINSLIDER 0; MAXSLIDER 180; CUSTOMGUI REALSLIDER; STEP 1; }
		STATICTEXT { JOINEND; }
	}
}
