CONTAINER ToolStitchAndSew
{
	NAME ToolStitchAndSew;
	INCLUDE ToolBase;

	HIDE MDATA_COMMANDGROUP;

	GROUP MDATA_MAINGROUP
	{
		BOOL MDATA_STITCHANDSEW_NGONS { ANIM OFF;}
		BOOL MDATA_STITCHANDSEW_VISIBLE { ANIM OFF;}
	}
}
