CONTAINER ToolSoftSelection
{
	NAME ToolSoftSelection;

	GROUP MDATA_SOFTSELECTION
	{
		DEFAULT 1;

		GROUP
		{
			COLUMNS 3;

			BOOL MDATA_SOFT_ENABLE { }
			BOOL MDATA_SOFT_PREVIEW { }
			STATICTEXT { NEWLINE; }

			BOOL MDATA_SOFT_SURFACE { }
			BOOL MDATA_SOFT_RUBBER { }
			BOOL MDATA_SOFT_RESTRICT { }
		}

		GROUP
		{
			COLUMNS 2;
			LONG MDATA_SOFT_FALLOFF { CYCLE { MDATA_SOFT_FALLOFF_LINEAR; MDATA_SOFT_FALLOFF_DOME; MDATA_SOFT_FALLOFF_BELL; MDATA_SOFT_FALLOFF_CIRCLE; MDATA_SOFT_FALLOFF_NEEDLE; MDATA_SOFT_FALLOFF_VMAP; MDATA_SOFT_FALLOFF_SPLINE; } }
			LONG MDATA_SOFT_MODE { CYCLE { MDATA_SOFT_MODE_GROUPS; MDATA_SOFT_MODE_CENTER; MDATA_SOFT_MODE_ALL; } }
		}

		REAL MDATA_SOFT_RADIUS { UNIT METER; MIN 0.0; MAXSLIDER 1000; CUSTOMGUI REALSLIDER; }
		REAL MDATA_SOFT_STRENGTH { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		REAL MDATA_SOFT_WIDTH { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		GROUP
		{
			SPLINE MDATA_SOFT_SPLINE { SHOWGRID_H; SHOWGRID_V; EDIT_H; EDIT_V; }
		}
	}
}
