CONTAINER ToolMeasure
{
  NAME ToolMeasure;
	INCLUDE ToolBase;

	HIDE MDATA_COMMANDGROUP;

  GROUP MDATA_MAINGROUP
  {
		LONG MDATA_MEASURE_SELECTION { CYCLE {  } }
		BOOL MDATA_MEASURE_VISIBLE { }

		GROUP
		{
			COLUMNS 2;
			
			BUTTON MDATA_MEASURE_NEW { }
			BUTTON MDATA_MEASURE_DELETE { }
			BUTTON MDATA_MEASURE_CREATEOBJECT { }
			STATICTEXT { DUMMY; }
		}

		SEPARATOR { LINE; }

		GROUP
		{
			COLUMNS 3;
			
			BOOL MDATA_MEASURE_3RD_POINT { }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINEND; }

			BOOL MDATA_MEASURE_SHOWDIST1 { }
			REAL MDATA_MEASURE_DIST1 { UNIT METER; }
			BOOL MDATA_MEASURE_DIR1 { }

			BOOL MDATA_MEASURE_SHOWDIST2 { HIDDEN; }
			REAL MDATA_MEASURE_DIST2 { UNIT METER; HIDDEN; }
			BOOL MDATA_MEASURE_DIR2 { HIDDEN; }

			BOOL MDATA_MEASURE_SHOWANGLE { HIDDEN; }
			REAL MDATA_MEASURE_ANGLE { UNIT DEGREE; HIDDEN; }
			BOOL MDATA_MEASURE_FIXROT { HIDDEN; }
		}

		SEPARATOR MDATA_MEASUREGROUP_COLORS { }

		COLOR MDATA_MEASURE_COLORP { }
		COLOR MDATA_MEASURE_COLOR1 { }
		COLOR MDATA_MEASURE_COLOR2 { HIDDEN; }

		SEPARATOR MDATA_MEASUREGROUP_P1 { }

		LINK MDATA_MEASURE_PNT1_LINK { ACCEPT { Obase; } }
		LONG MDATA_MEASURE_PNT1_MODE { CYCLE { MDATA_MEASURE_PNT_MODE_FREE; MDATA_MEASURE_PNT_MODE_POINT; MDATA_MEASURE_PNT_MODE_EDGE; MDATA_MEASURE_PNT_MODE_POLY; } }
		LONG MDATA_MEASURE_PNT1_IDX  { }
		VECTOR MDATA_MEASURE_PNT1_VECTOR { UNIT METER; }

		SEPARATOR MDATA_MEASUREGROUP_P2 { }

		LINK MDATA_MEASURE_PNT2_LINK { ACCEPT { Obase; } }
		LONG MDATA_MEASURE_PNT2_MODE { CYCLE { MDATA_MEASURE_PNT_MODE_FREE; MDATA_MEASURE_PNT_MODE_POINT; MDATA_MEASURE_PNT_MODE_EDGE; MDATA_MEASURE_PNT_MODE_POLY; } }
		LONG MDATA_MEASURE_PNT2_IDX  { }
		VECTOR MDATA_MEASURE_PNT2_VECTOR { UNIT METER; }

		SEPARATOR MDATA_MEASUREGROUP_P3 { }

		LINK MDATA_MEASURE_PNT3_LINK { ACCEPT { Obase; } HIDDEN; }
		LONG MDATA_MEASURE_PNT3_MODE { CYCLE { MDATA_MEASURE_PNT_MODE_FREE; MDATA_MEASURE_PNT_MODE_POINT; MDATA_MEASURE_PNT_MODE_EDGE; MDATA_MEASURE_PNT_MODE_POLY; } HIDDEN; }
		LONG MDATA_MEASURE_PNT3_IDX  { HIDDEN; }
		VECTOR MDATA_MEASURE_PNT3_VECTOR { UNIT METER; HIDDEN; }
  }
	GROUP MDATA_COMMANDGROUP
	{
		SHOW MDATA_APPLY;
	}
}
