CONTAINER ToolRandomize
{
  NAME ToolRandomize;
	INCLUDE ToolBase;

  GROUP MDATA_MAINGROUP
  {
		GROUP
		{
			VECTOR MDATA_RANDOMIZE_MOVE { UNIT METER; }
			VECTOR MDATA_RANDOMIZE_SCALE { UNIT PERCENT; }
			VECTOR MDATA_RANDOMIZE_ROTATE { UNIT DEGREE; }
			LONG MDATA_RANDOMIZE_SEED { MIN 0; }
		}
  }
	GROUP MDATA_COMMANDGROUP
	{
		SHOW MDATA_APPLY;
	}
}
