CONTAINER ToolMagnet
{
	NAME ToolMagnet;
	INCLUDE ToolBase;

	HIDE MDATA_COMMANDGROUP;
	
	GROUP MDATA_MAINGROUP
	{
		REAL MDATA_MAGNET_FALLOFF_STRENGTH  { UNIT PERCENT; MAXSLIDER 100.0; MINSLIDER 0.0; STEP 1.0; CUSTOMGUI REALSLIDER; }
		REAL MDATA_MAGNET_FALLOFF_RADIUS  { UNIT METER; MIN 0.0; MAXSLIDER 100.0; MINSLIDER 0.0; STEP 0.1; CUSTOMGUI REALSLIDER; }
	
		LONG MDATA_MAGNET_EFFECTMODE
		{
			ALIGN_LEFT;
			CYCLE
			{
				MDATA_MAGNET_MODE_SMEAR;
				MDATA_MAGNET_MODE_PULL;
				MDATA_MAGNET_MODE_SURFACE;
				MDATA_MAGNET_MODE_NORMAL;
				MDATA_MAGNET_MODE_SPREAD;
				MDATA_MAGNET_MODE_SPIN;
				MDATA_MAGNET_MODE_TWIST;
				MDATA_MAGNET_MODE_VORTEX;
				MDATA_MAGNET_MODE_SMOOTH;
			}
		}

		BOOL MDATA_MAGNET_MOVEONLYVISIBLE {}
		BOOL MDATA_MAGNET_CONNECTED { }
		BOOL MDATA_MAGNET_PREVIEW { }
		BOOL MDATA_MAGNET_NEAREST { }
		BOOL MDATA_MAGNET_VISIBLEONLY { }
		
		GROUP MDATA_MAGNET_RESTRICTION_GROUP
		{
			LONG MDATA_MAGNET_RESTRICT
			{
				ALIGN_LEFT;
				CYCLE
				{
					MDATA_MAGNET_RESTRICT_WORLD;
					MDATA_MAGNET_RESTRICT_OBJECT;
					MDATA_MAGNET_RESTRICT_CAMERA;
				}
			}
			REAL MDATA_MAGNET_RESTRICT_X  { UNIT PERCENT; MAXSLIDER 100.0; MINSLIDER 0.0; STEP 1.0; CUSTOMGUI REALSLIDER; }
			REAL MDATA_MAGNET_RESTRICT_Y  { UNIT PERCENT; MAXSLIDER 100.0; MINSLIDER 0.0; STEP 1.0; CUSTOMGUI REALSLIDER; }
			REAL MDATA_MAGNET_RESTRICT_Z  { UNIT PERCENT; MAXSLIDER 100.0; MINSLIDER 0.0; STEP 1.0; CUSTOMGUI REALSLIDER; }
		}
	}

	GROUP MDATA_MAGNET_FALLOFF_GROUP
	{
		DEFAULT 1;
		LONG MDATA_MAGNET_MODE
		{
			ALIGN_LEFT;
			CYCLE
			{
				MDATA_MAGNET_MODE_CONSTANT;
				MDATA_MAGNET_MODE_LINEAR;
				MDATA_MAGNET_MODE_DOME;
				MDATA_MAGNET_MODE_BELL;
				MDATA_MAGNET_MODE_CIRCLE;
				MDATA_MAGNET_MODE_NEEDLE;
				MDATA_MAGNET_MODE_USER;
			}
		}
		REAL MDATA_MAGNET_FALLOFF_WIDTH  { UNIT PERCENT;  MIN 0.0; MAXSLIDER 100.0; MINSLIDER 0.0; STEP 1.0; CUSTOMGUI REALSLIDER;}
		SPLINE MDATA_MAGNET_FALLOFF { }
	}
}
