CONTAINER ToolSplineSmooth
{
	NAME		ToolSplineSmooth;
	INCLUDE ToolBase;

	HIDE MDATA_COMMANDGROUP;

	GROUP MDATA_MAINGROUP
	{
		REAL MDATA_SPLINESMOOTH_RADIUS { MIN 0.0; MAXSLIDER 100.0; STEP 1.0; CUSTOMGUI REALSLIDER; ANIM OFF; }
		REAL MDATA_SPLINESMOOTH_STRENGTH { UNIT PERCENT; MIN 0.0; MAX 100.0; STEP 1.0; CUSTOMGUI REALSLIDER; ANIM OFF; }

		SEPARATOR { LINE; }

		GROUP
		{
			COLUMNS 2;
			SCALE_H;
			BOOL MDATA_SPLINESMOOTH_SMOOTH_ON { ANIM OFF; }
			REAL MDATA_SPLINESMOOTH_SMOOTH { UNIT PERCENT; MIN 0.0; MAX 100.0; STEP 1.0; CUSTOMGUI REALSLIDER; SCALE_H; ANIM OFF; }
			BOOL MDATA_SPLINESMOOTH_FLATTEN_ON { ANIM OFF; }
			REAL MDATA_SPLINESMOOTH_FLATTEN { UNIT PERCENT; MIN 0.0; MAX 100.0; STEP 1.0; CUSTOMGUI REALSLIDER; SCALE_H; ANIM OFF; }
			BOOL MDATA_SPLINESMOOTH_RANDOM_ON { ANIM OFF; }
			REAL MDATA_SPLINESMOOTH_RANDOM { UNIT PERCENT; MIN 0.0; MAX 100.0; STEP 1.0; CUSTOMGUI REALSLIDER; SCALE_H; ANIM OFF; }
			BOOL MDATA_SPLINESMOOTH_PULL_ON { ANIM OFF; }
			REAL MDATA_SPLINESMOOTH_PULL { UNIT PERCENT; MIN 0.0; MAX 100.0; STEP 1.0; CUSTOMGUI REALSLIDER; SCALE_H; ANIM OFF; }
			BOOL MDATA_SPLINESMOOTH_SPIRAL_ON { ANIM OFF; }
			REAL MDATA_SPLINESMOOTH_SPIRAL { UNIT PERCENT; MIN -100.0; MAX 100.0; STEP 1.0; CUSTOMGUI REALSLIDER; SCALE_H; ANIM OFF; }
			BOOL MDATA_SPLINESMOOTH_INFLATE_ON { ANIM OFF; }
			REAL MDATA_SPLINESMOOTH_INFLATE { UNIT PERCENT; MIN -100.0; MAX 100.0; STEP 1.0; CUSTOMGUI REALSLIDER; SCALE_H; ANIM OFF; }
			BOOL MDATA_SPLINESMOOTH_PROJECT_ON { ANIM OFF; }
			REAL MDATA_SPLINESMOOTH_PROJECT { UNIT PERCENT; MIN -100.0; MAX 100.0; STEP 1.0; CUSTOMGUI REALSLIDER; SCALE_H; ANIM OFF; }
		}
	}
}
