CONTAINER ToolClone
{
  NAME ToolClone;
	INCLUDE ToolBase;

  GROUP MDATA_MAINGROUP
  {
		LONG MDATA_CLONE_CNT { MIN 1; MAX 1000; }
		REAL MDATA_CLONE_OFFSET	{ UNIT METER; }
		REAL MDATA_CLONE_HOLES { UNIT PERCENT; MIN 0; MAX 100; CUSTOMGUI REALSLIDER; MINSLIDER 0; MAXSLIDER 100; }
		REAL MDATA_CLONE_SCALE { UNIT PERCENT; MIN 0; MAX 100; CUSTOMGUI REALSLIDER; MINSLIDER 0; MAXSLIDER 100; }
		LONG MDATA_CLONE_AXIS
		{
			CYCLE
			{
				MDATA_CLONE_AXIS_X;
				MDATA_CLONE_AXIS_Y;
				MDATA_CLONE_AXIS_Z;
			}
		}
		REAL MDATA_CLONE_ROTATION { UNIT DEGREE; }
		VECTOR MDATA_CLONE_LOCALMOVE { UNIT METER; } 
		VECTOR MDATA_CLONE_LOCALSCALE { UNIT PERCENT; MIN 0; MAX 100; }
		VECTOR MDATA_CLONE_LOCALROTATE { UNIT DEGREE; }
		BOOL MDATA_CLONE_KEEPFORM { }
  }
}
