CONTAINER ToolIron
{
	NAME ToolIron;
	INCLUDE ToolBase;

	GROUP MDATA_MAINGROUP
	{
		REAL MDATA_IRON_PERCENT { UNIT PERCENT; MIN -100.0; MAX 100.0; MAXSLIDER 100.0; MINSLIDER -100.0; CUSTOMGUI REALSLIDER; }
		REAL MDATA_IRON_ANGLE { UNIT DEGREE; MIN 0.0; MAX 180.0; MAXSLIDER 180.0; MINSLIDER 0.0; CUSTOMGUI REALSLIDER; }
		BOOL MDATA_IRON_PRESERVEBOUNDARY { NAME MDATA_IRON_PRESERVEBOUNDARY; }
	}
}
