CONTAINER ToolSmoothShift
{
  NAME ToolSmoothShift;
	INCLUDE ToolBase;

  GROUP MDATA_MAINGROUP
  {
		REAL MDATA_SMOOTHSHIFT_OFFSET { UNIT METER; MINSLIDER -100; MAXSLIDER 100; CUSTOMGUI REALSLIDER; STEP 1; }
		REAL MDATA_SMOOTHSHIFT_VARIANCE { UNIT PERCENT;  MIN 0; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER; STEP 1; }
		REAL MDATA_SMOOTHSHIFT_SUBDIVISION { MIN 1; MINSLIDER 1; MAXSLIDER 10; CUSTOMGUI REALSLIDER; STEP 1;}
		BOOL MDATA_SMOOTHSHIFT_CREATENGONS { }
		BOOL MDATA_SMOOTHSHIFT_PRESERVEGROUPS { }
		REAL MDATA_SMOOTHSHIFT_ANGLE { UNIT DEGREE; MIN 0; MAX 180; MINSLIDER 0; MAXSLIDER 180; CUSTOMGUI REALSLIDER; STEP 1;}
  }
}
