CONTAINER ToolBrush
{
	NAME ToolBrush;
	INCLUDE ToolBase;

	HIDE MDATA_COMMANDGROUP;

	GROUP MDATA_MAINGROUP
	{
		REAL MDATA_BRUSH_FALLOFF_STRENGTH  { UNIT PERCENT; MAXSLIDER 100.0; MINSLIDER 0.0; STEP 1.0; CUSTOMGUI REALSLIDER; }
		REAL MDATA_BRUSH_FALLOFF_RADIUS  { UNIT METER; MIN 0.0; MAXSLIDER 100.0; MINSLIDER 0.0; STEP 0.1; CUSTOMGUI REALSLIDER; }

		LONG MDATA_BRUSH_MODE
		{
			ALIGN_LEFT;
			CYCLE
			{
				MDATA_BRUSH_MODE_SMEAR;
				MDATA_BRUSH_MODE_PULL;
				MDATA_BRUSH_MODE_SURFACE;
				MDATA_BRUSH_MODE_NORMAL;
				MDATA_BRUSH_MODE_SPREAD;
				MDATA_BRUSH_MODE_SPIN;
				MDATA_BRUSH_MODE_TWIST;
				MDATA_BRUSH_MODE_VORTEX;
				MDATA_BRUSH_MODE_SMOOTH;
				-1;
				MDATA_BRUSH_MODE_PAINT;
				MDATA_BRUSH_MODE_BLUR;
				MDATA_BRUSH_MODE_BLEED;
				MDATA_BRUSH_MODE_INTENSITY;
			}
		}
		BOOL MDATA_BRUSH_UPDATENORMALS { }
		BOOL MDATA_BRUSH_VISIBLEONLY { }
		BOOL MDATA_BRUSH_CONNECTED { }
		BOOL MDATA_BRUSH_PREVIEW { }

		GROUP MDATA_BRUSH_RESTRICTION_GROUP
		{
			LONG MDATA_BRUSH_RESTRICTION_SPACE
			{
				ALIGN_LEFT;
				CYCLE
				{
					MDATA_BRUSH_RESTRICTION_SPACE_WORLD;
					MDATA_BRUSH_RESTRICTION_SPACE_OBJECT;
				}
			}
			REAL MDATA_BRUSH_RESTRICTION_X  { UNIT PERCENT; MAXSLIDER 100.0; MINSLIDER 0.0; STEP 1.0; CUSTOMGUI REALSLIDER; }
			REAL MDATA_BRUSH_RESTRICTION_Y  { UNIT PERCENT; MAXSLIDER 100.0; MINSLIDER 0.0; STEP 1.0; CUSTOMGUI REALSLIDER; }
			REAL MDATA_BRUSH_RESTRICTION_Z  { UNIT PERCENT; MAXSLIDER 100.0; MINSLIDER 0.0; STEP 1.0; CUSTOMGUI REALSLIDER; }
		}
	}

	GROUP MDATA_BRUSH_FALLOFFGROUP
	{
		DEFAULT 1;
		LONG MDATA_BRUSH_FALLOFF_MODE
		{
			ALIGN_LEFT;
			CYCLE
			{
				MDATA_BRUSH_MODE_CONSTANT;
				MDATA_BRUSH_MODE_LINEAR;
				MDATA_BRUSH_MODE_DOME;
				MDATA_BRUSH_MODE_BELL;
				MDATA_BRUSH_MODE_CIRCLE;
				MDATA_BRUSH_MODE_NEEDLE;
				MDATA_BRUSH_MODE_USER;
			}
		}
		REAL MDATA_BRUSH_FALLOFF_WIDTH  { UNIT PERCENT;  MIN 0.0; MAXSLIDER 100.0; MINSLIDER 0.0; STEP 1.0; CUSTOMGUI REALSLIDER;}
		SPLINE MDATA_BRUSH_FALLOFF { }
	}
}
