CONTAINER ToolClosehole
{
	NAME ToolCloseHole;
	INCLUDE ToolBase;

	HIDE MDATA_COMMANDGROUP;

	GROUP MDATA_MAINGROUP
	{
		BOOL MDATA_CLOSEHOLE_TRI { ANIM OFF;}
		LONG MDATA_CLOSEHOLE_POLYTYPE
		{
			CYCLE
			{
				MDATA_CLOSEHOLE_POLYTYPE_NGON;
				MDATA_CLOSEHOLE_POLYTYPE_TRIANGLE;
				MDATA_CLOSEHOLE_POLYTYPE_QUADS;
			}
		}
		BOOL MDATA_CLOSEHOLE_SELECTNEWPOLY { ANIM OFF; }
		BOOL MDATA_CLOSEHOLE_SELECTOUTLINE { ANIM OFF; }
		BOOL MDATA_CLOSEHOLE_BREAKOUTLINE { ANIM OFF; }
	}
}
