CONTAINER ToolSplineProject
{
	NAME		ToolSplineProject;
	INCLUDE ToolBase;

	GROUP MDATA_MAINGROUP
	{
		LONG MDATA_SPLINE_PROJECT_MODE
		{
			CYCLE
			{
				MDATA_SPLINE_PROJECT_MODE_VIEW;
				MDATA_SPLINE_PROJECT_MODE_XY;
				MDATA_SPLINE_PROJECT_MODE_ZY;
				MDATA_SPLINE_PROJECT_MODE_XZ;
				MDATA_SPLINE_PROJECT_MODE_X_AXIS;
				MDATA_SPLINE_PROJECT_MODE_Y_AXIS;
				MDATA_SPLINE_PROJECT_MODE_Z_AXIS;
				MDATA_SPLINE_PROJECT_MODE_SPHERICAL;
			}
		}
	}
}
