CONTAINER ToolKnifePlane
{
	NAME ToolKnifePlane;
	INCLUDE ToolBase;
	HIDE MDATA_COMMANDGROUP;

	GROUP MDATA_MAINGROUP
	{
			COLUMNS 3;
			LONG MDATA_KNIFEPLANE_MODE
			{
				ALIGN_LEFT;
				CYCLE
				{
					MDATA_KNIFEPLANE_MODE_ALL;
					MDATA_KNIFEPLANE_MODE_SPLIT;
					MDATA_KNIFEPLANE_MODE_REGION_A;
					MDATA_KNIFEPLANE_MODE_REGION_B;
				}
			}
			STATICTEXT { }
			STATICTEXT { }

			LONG MDATA_KNIFEPLANE_PLANE_MODE
			{
				ALIGN_LEFT;
				CYCLE
				{
					MDATA_KNIFEPLANE_PLANE_MODE_FREE;
					MDATA_KNIFEPLANE_PLANE_MODE_LOCAL;
					MDATA_KNIFEPLANE_PLANE_MODE_WORLD;
					MDATA_KNIFEPLANE_PLANE_MODE_CAMERA;
				}
			}
			STATICTEXT { }
			STATICTEXT { }

			LONG MDATA_KNIFEPLANE_PLANE
			{
				ALIGN_LEFT;
				CYCLE
				{
					MDATA_KNIFEPLANE_PLANE_XY;
					MDATA_KNIFEPLANE_PLANE_YZ;
					MDATA_KNIFEPLANE_PLANE_XZ;
				}
			}
			STATICTEXT { }
			STATICTEXT { }


			VECTOR MDATA_KNIFEPLANE_PIVOT_POSITION { UNIT METER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }
			VECTOR MDATA_KNIFEPLANE_PIVOT_ROTATION { UNIT DEGREE; }
			LONG MDATA_KNIFEPLANE_PLANE_PRESET
			{
				ALIGN_LEFT;
				CYCLE
				{
					MDATA_KNIFEPLANE_PLANE_PRESET_X;
					MDATA_KNIFEPLANE_PLANE_PRESET_X2;
					MDATA_KNIFEPLANE_PLANE_PRESET_Y;
					MDATA_KNIFEPLANE_PLANE_PRESET_Y2;
					MDATA_KNIFEPLANE_PLANE_PRESET_Z;
					MDATA_KNIFEPLANE_PLANE_PRESET_Z2;
					MDATA_KNIFEPLANE_PLANE_PRESET_CUSTOM;
				}
			}
			STATICTEXT { }

			REAL MDATA_KNIFEPLANE_OFFSET { UNIT METER; MINSLIDER -100; MAXSLIDER 100; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }
			LONG MDATA_KNIFEPLANE_CONUT { MIN 1; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }
			REAL MDATA_KNIFEPLANE_DIST	{ UNIT METER; MINSLIDER -100; MAXSLIDER 100; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			SEPARATOR { LINE; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			BOOL MDATA_KNIFEPLANE_SELECTED { }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			BOOL MDATA_KNIFEPLANE_SELECT_CUT { }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			BOOL MDATA_KNIFEPLANE_CUTPOLYS { }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			BOOL MDATA_KNIFEPLANE_NGON_CURVATURE { }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			BOOL MDATA_KNIFEPLANE_AUTOSNAP { }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			BOOL MDATA_KNIFEPLANE_REGULARSLICE {	}
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			SEPARATOR { LINE; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			BOOL MDATA_KNIFEPLANE_ANGLE_CONSTRAINT{ }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			REAL MDATA_KNIFEPLANE_ANGLE_CONSTRAINT_VALUE { UNIT DEGREE; MIN 0.1; MAX 180; STEP 0.1; MINSLIDER 0.1; MAXSLIDER 180; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			SEPARATOR { LINE; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }
			BOOL MDATA_KNIFEPLANE_REALTIME { }
	}
}
