CONTAINER ToolLoopSelection
{
	NAME ToolLoopSelection;
	INCLUDE ToolBase;

	GROUP MDATA_MAINGROUP
	{
		BOOL MDATA_LOOP_SEL_STOP_AT_SELECTIONS { }
		BOOL MDATA_LOOP_SEL_STOP_AT_NON_QUADS { }
		BOOL MDATA_LOOP_SEL_STOP_AT_POLES { }
	}
	HIDE MDATA_COMMANDGROUP;
}
