CONTAINER xbeveltool
{
  NAME xbeveltool;

	GROUP MDATA_BEVEL_GROUP_OPTION
	{
		DEFAULT 1;
		LONG MDATA_BEVEL_MASTER_MODE
		{
			CYCLE
			{
				MDATA_BEVEL_MASTER_MODE_CHAMFER;
				MDATA_BEVEL_MASTER_MODE_SOLID;	
			}
		}
		
		LONG MDATA_BEVEL_OFFSET_MODE
		{
			CYCLE
			{
				MDATA_BEVEL_OFFSET_MODE_FIXED;
				MDATA_BEVEL_OFFSET_MODE_RADIAL;
				MDATA_BEVEL_OFFSET_MODE_PROPORTIONAL;
			}
		}
		
		REAL MDATA_BEVEL_RADIUS { UNIT METER; MINSLIDER -100; MAXSLIDER 100; CUSTOMGUI REALSLIDER; }
		REAL MDATA_BEVEL_SUB		{ MIN 0; MINSLIDER 0; MAXSLIDER 20; CUSTOMGUI REALSLIDER; }
		REAL MDATA_BEVEL_DEPTH	{ UNIT PERCENT; MINSLIDER -100; MAXSLIDER 100; CUSTOMGUI REALSLIDER; }
		REAL MDATA_BEVEL_SHAPING_EXTR { UNIT METER; MINSLIDER -100; MAXSLIDER 100; CUSTOMGUI REALSLIDER; }
		BOOL MDATA_BEVEL_LIMIT	{};
	}
	
	GROUP MDATA_BEVEL_GROUP_POLYGON
	{
		DEFAULT 1;
		REAL MDATA_BEVEL_EXTRUSION	{ UNIT METER; MINSLIDER -100; MAXSLIDER 100; CUSTOMGUI REALSLIDER; }
		REAL MDATA_BEVEL_POLY_ANGLE { MIN 0; UNIT DEGREE; MINSLIDER 0; MAXSLIDER 180; CUSTOMGUI REALSLIDER; }
		BOOL MDATA_BEVEL_GROUP	{};
	}

	GROUP MDATA_BEVEL_GROUP_SHAPING
	{
		DEFAULT 1;
		LONG MDATA_BEVEL_SHAPING_MODE
		{
			CYCLE
			{
				MDATA_BEVEL_SHAPING_MODE_ROUND;
				MDATA_BEVEL_SHAPING_MODE_USER;
				MDATA_BEVEL_SHAPING_MODE_PROFILE;
			}
		}
		
		REAL MDATA_BEVEL_SHAPING_TENSION { UNIT PERCENT; MINSLIDER -100; MAXSLIDER 100; CUSTOMGUI REALSLIDER; }
		
		SPLINE MDATA_BEVEL_SHAPING_SPLINE { SHOWGRID_H; SHOWGRID_V; EDIT_H; EDIT_V; }
		
		LINK MDATA_BEVEL_SHAPING_SPLINE_LINK 
		{
			ACCEPT { Ospline; }
		}
		
		LONG MDATA_BEVEL_SHAPING_SPLINE_PLANE
		{
			CYCLE
			{
				MDATA_BEVEL_SHAPING_SPLINE_PLANE_XY;
				MDATA_BEVEL_SHAPING_SPLINE_PLANE_XZ;
				MDATA_BEVEL_SHAPING_SPLINE_PLANE_ZY;
			}
		}
		
		BOOL MDATA_BEVEL_SHAPING_SYMMETRY {};
		BOOL MDATA_BEVELL_SHAPING_CONSTANT {};
	}
	
	GROUP MDATA_BEVEL_GROUP_TOPOLOGY
	{
		DEFAULT 1;
		LONG MDATA_BEVEL_MITERING
		{
			CYCLE
			{
				MDATA_BEVEL_MITERING_DEFAULT;
				MDATA_BEVEL_MITERING_UNIFORM;
				MDATA_BEVEL_MITERING_RADIAL;
				MDATA_BEVEL_MITERING_PATCH;
			}
		}
		
		LONG MDATA_BEVEL_CORNER_ENDING
		{
			CYCLE
			{
				MDATA_BEVEL_CORNER_ENDING_DEFAULT;
				MDATA_BEVEL_CORNER_ENDING_EXTEND;
				MDATA_BEVEL_CORNER_ENDING_INSET;
			}
		}
		
		LONG MDATA_BEVEL_PROUNDING_TYPE
		{
			CYCLE
			{
				MDATA_BEVEL_PROUNDING_TYPE_FLAT;
				MDATA_BEVEL_PROUNDING_TYPE_FULL;
				MDATA_BEVEL_PROUNDING_TYPE_CONVEX;
			}
		}
		
		BOOL MDATA_BEVEL_CORNER_NGON {};
		BOOL MDATA_BEVEL_ROUNDING_NGON {};
		BOOL MDATA_BEVEL_SELECTION_PHONG_BREAK {};
		BOOL MDATA_BEVEL_SELECTION_PHONG_BREAK_M {};
	}
	
	
	INCLUDE ToolBase;
}
		
