CONTAINER xslidetool
{
  NAME xslidetool;
	INCLUDE ToolBase;

  GROUP MDATA_MAINGROUP
  {
			REAL MDTA_SLIDE_OFFSET { UNIT METER; MINSLIDER -100; MAXSLIDER 100; CUSTOMGUI REALSLIDER; }
			REAL MDTA_SLIDE_SHIFT { UNIT METER; MINSLIDER -100; MAXSLIDER 100; CUSTOMGUI REALSLIDER; }
			LONG MDTA_SLIDE_OFFSET_MODE
			{
				CYCLE
				{
				MDTA_SLIDE_OFFSET_MODE_FIXED;
				MDTA_SLIDE_OFFSET_MODE_PROPORTIONAL;
				}
			}
			BOOL MDTA_SLIDE_OFFSET_LIMIT{};
			BOOL MDTA_SLIDE_CURVATURE{};
			BOOL MDTA_SLIDE_CLONE{};
			BOOL MDTA_SLIDE_TEMP_CLONE { HIDDEN; }
		}
}