// C4D-DialogResource

DIALOG DLG_PM_NEWBITMAP
{
  NAME TITLE;

  COLORFIELD IDC_PM_BGCOLOR { SCALE_H; SCALE_V; ALIGN_BOTTOM; SIZE 500,0; NOBRIGHTNESS; BODYPAINT; }

  DLGGROUP { OK;CANCEL;HELP; ALIGN_BOTTOM; }
}
