// C4D-DialogResource
DIALOG DLG_PVRMPREFS
{
  NAME IDS_PVRMPREF_TITLE; CENTER_V; SCALE_H; 
  
  GROUP IDC_PREFS_GR_GENERAL
  {
	  ALIGN_TOP; ALIGN_LEFT; 
	  BORDERSIZE 0, 0, 0, 0; 
	  COLUMNS 1;
	  SPACE 4, 4;
  	GROUP 
	{
		ALIGN_TOP; SCALE_H; 
		BORDERSIZE 0, 0, 0, 0; 
		COLUMNS 1;
		SPACE 4, 4;
	    
	    GROUP 
		{
		  ALIGN_TOP; ALIGN_LEFT; 
		  BORDERSIZE 0, 0, 0, 0; 
		  COLUMNS 1;
		  SPACE 4, 4;
		  STATICTEXT { NAME IDS_PVPREFS_NAMETEXT;}
		 }
		GROUP 
		{
		  ALIGN_TOP; ALIGN_LEFT; 
		  BORDERSIZE 0, 0, 0, 0; 
		  COLUMNS 3;
		  SPACE 4, 4;
		  STATICTEXT { NAME IDS_PVPREFS_MEMORY;}
		  EDITNUMBERARROWS IDC_PVPREFS_MEMORY { ALIGN_LEFT; SIZE 50,0;}
		  STATICTEXT { NAME IDS_PVPREFS_MEMORY2;}
		}
		GROUP 
		{
		  ALIGN_TOP; ALIGN_LEFT; 
		  BORDERSIZE 0, 0, 0, 0; 
		  COLUMNS 5;
		  SPACE 4, 4;
		  STATICTEXT { NAME IDS_PVPREFS_HD;}
		  EDITNUMBERARROWS IDC_PVPREFS_HD { ALIGN_LEFT; SIZE 50,0;}
		  STATICTEXT { NAME IDS_PVPREFS_HD2;}
		  CHECKBOX IDC_PVPREFS_HDUNLIMITED { NAME IDS_PVPREFS_HDUNLIMITED; CENTER_V; FIT_H;  }
		}
		GROUP 
		{
		  ALIGN_TOP; ALIGN_LEFT; 
		  BORDERSIZE 0, 0, 0, 0; 
		  COLUMNS 3;
		  SPACE 4, 4;
		  STATICTEXT { NAME IDS_PVPREFS_HDFOLDER;}
		  FILENAME IDC_PVPREFS_HDFOLDER { SCALE_H; SIZE 400,0; DIRECTORY; }
		 }
		CHECKBOX IDC_PVPREFS_DRAWBUCKETS { NAME IDS_PVPREFS_DRAWBUCKET; CENTER_V; FIT_H;  }
	}
 	GROUP
 	{
 		ALIGN_TOP; SCALE_H; 
 		BORDERSIZE 0, 0, 0, 0; 
 		COLUMNS 1;
 		SPACE 4, 4;
 		
 		CHECKBOX IDC_RMPREFS_LOGFILE { NAME IDS_RMPREFS_LOGFILE; CENTER_V; FIT_H;  }
 	}
  }
}
