DIALOG DLG_DILUTIONER
{
  NAME TITLE;
	SCALE_H; SCALE_V;
		
	GROUP
	{
		ROWS 2;
		BORDERSIZE 4,4,4,4;
		SCALE_H; SCALE_V;

		STATICTEXT { NAME TREDUCTION;  } EDITSLIDER IDC_DELU_REDUCTION { SCALE_H; }
		STATICTEXT { NAME TREDUCTION2;  } EDITSLIDER IDC_DELU_REDUCTION2 { SCALE_H; }

	}
}
