// C4D-DialogResource
DIALOG IDC_DELETEFRAME
{
  NAME IDS_DIALOG; CENTER_V; CENTER_H; 
  
  GROUP 
  {
    ALIGN_TOP; ALIGN_LEFT; 
    BORDERSIZE 0, 0, 0, 0; 
    COLUMNS 2;
    SPACE 4, 4;
    
    STATICTEXT IDC_DEL_FRAMETEXT { NAME IDS_TIME; CENTER_V; ALIGN_LEFT; }
    EDITNUMBERARROWS IDC_DEL_FRAME { CENTER_V; CENTER_H; SIZE 70, 0; }
  }
  DLGGROUP { OK; CANCEL; }
}