// C4D-DialogResource
DIALOG IDC_PREVIEW
{
  NAME IDS_PREVIEW; CENTER_V; CENTER_H; 
  
  GROUP IDC_PW_GROUP
  {
    SCALE_V; SCALE_H; 
    BORDERSIZE 0, 0, 0, 0; 
    COLUMNS 2;
    SPACE 4, 4;
    
    STATICTEXT IDC_PW_STATIC { NAME IDS_FROM; CENTER_V; ALIGN_LEFT; }
    EDITNUMBERARROWS IDC_PW_FROM { CENTER_V; CENTER_H; SIZE 70, 0; }
    STATICTEXT IDC_STATIC { NAME IDS_TO; CENTER_V; ALIGN_LEFT; }
    EDITNUMBERARROWS IDC_PW_TO { CENTER_V; CENTER_H; SIZE 70, 0; }
  }
}