// C4D-DialogResource
DIALOG IDC_SELECTION
{
  NAME IDS_DIALOG; CENTER_V; CENTER_H; 
  
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC; ALIGN_TOP; ALIGN_LEFT; 
    BORDERSTYLE BORDER_NONE; BORDERSIZE 4, 4, 4, 4; 
    COLUMNS 1;
    SPACE 4, 4;
    
    GROUP IDC_SS_GROUP
    {
      ALIGN_TOP; ALIGN_LEFT; 
      BORDERSIZE 4, 4, 4, 4; 
      COLUMNS 2;
      SPACE 4, 4;
      
      STATICTEXT IDC_SS_TEXTFROM { NAME IDS_FROM; CENTER_V; ALIGN_LEFT; }
      EDITNUMBERARROWS IDC_SS_FROM
      { CENTER_V; CENTER_H; SIZE 70, 0; }
      STATICTEXT IDC_SS_TOTEXT { NAME IDS_TO; CENTER_V; ALIGN_LEFT; }
      EDITNUMBERARROWS IDC_SS_TO
      { CENTER_V; CENTER_H; SIZE 70, 0; }
    }
    CHECKBOX IDC_SS_SELECTED { NAME IDS_CHECK; ALIGN_TOP; ALIGN_LEFT;  }
  }
}