// C4D-DialogResource
DIALOG IDD_RENAMELAYER
{
  NAME IDS_DIALOG; CENTER_V; CENTER_H; 
  
  GROUP IDC_STATIC
  {
    COLUMNS 1;
    GROUP IDC_STATIC
    {
      ALIGN_TOP; ALIGN_LEFT; 
      BORDERSIZE 5, 0, 0, 0; 
      COLUMNS 1;
      SPACE 4, 4;
      
      STATICTEXT IDC_RENAME_ORG { NAME IDS_STATIC_NAME; CENTER_V; ALIGN_LEFT; }
      EDITTEXT IDC_RENAME_NEW { CENTER_V; CENTER_H; SIZE 180, 0; }
    }
  }
 
  DLGGROUP { OK; CANCEL; }
}