// C4D-DialogResource
DIALOG IDD_MOTIONSETTINGS
{
  NAME IDS_DIALOG; CENTER_V; CENTER_H; 
  
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC2; ALIGN_TOP; ALIGN_LEFT; 
    BORDERSTYLE BORDER_NONE; BORDERSIZE 5, 5, 5, 5; 
    COLUMNS 1;
    SPACE 5, 5;
    
    GROUP IDC_STATIC
    {
      NAME IDS_STATIC1; ALIGN_TOP; ALIGN_LEFT; 
      BORDERSTYLE BORDER_GROUP_IN; BORDERSIZE 5, 5, 5, 5; 
      ROWS 2;
      SPACE 5, 5;
      
      CHECKBOX IDC_MTSET_FROM { NAME IDS_CHECK; ALIGN_TOP; ALIGN_LEFT;  }
      CHECKBOX IDC_MTSET_LOOPTIME { NAME IDS_CHECK1; ALIGN_TOP; ALIGN_LEFT;  }
      CHECKBOX IDC_MTSET_TO { NAME IDS_CHECK2; ALIGN_TOP; ALIGN_LEFT;  }
      CHECKBOX IDC_MTSET_TRIM { NAME IDS_CHECK3; ALIGN_TOP; ALIGN_LEFT;  }
    }
    RADIOGROUP IDC_MTSETRADIO
    {
		GROUP IDC_STATIC
        {
          NAME IDS_STATIC; ALIGN_TOP; ALIGN_LEFT; 
          BORDERSTYLE BORDER_GROUP_IN; BORDERSIZE 5, 5, 5, 5; 
          ROWS 1;
          SPACE 5, 5;
          
          RADIOGADGET IDC_MTSET_SOURCE { NAME IDS_RADIO1; ALIGN_TOP; ALIGN_LEFT;  }
          RADIOGADGET IDC_MTSET_CLIPNAME { NAME IDS_RADIO; ALIGN_TOP; ALIGN_LEFT;  }
          RADIOGADGET IDC_MTSET_NONAME { NAME IDS_RADIO2; ALIGN_TOP; ALIGN_LEFT;  }
        }
    }
    //CHECKBOX IDC_MTSET_LOOPCOUNT { NAME IDS_CHECK4; ALIGN_TOP; ALIGN_LEFT;  }
    CHECKBOX IDC_MTSET_UNTRIMMED { NAME IDS_CHECK8; ALIGN_TOP; ALIGN_LEFT;  }
    CHECKBOX IDC_MTSET_SCALE { NAME IDS_CHECK5; ALIGN_TOP; ALIGN_LEFT;  }
    CHECKBOX IDC_MTSET_FCLAYER { NAME IDS_CHECK6; ALIGN_TOP; ALIGN_LEFT;  }
    CHECKBOX IDC_MTSET_PICTURE { NAME IDS_CHECK7; ALIGN_TOP; ALIGN_LEFT;  }
  }
}
