// C4D-DialogResource
DIALOG IDD_CREATECLIP
{
  NAME IDS_DIALOG; CENTER_V; CENTER_H; 
  
  GROUP IDC_STATIC
  {
    COLUMNS 1;
    GROUP IDC_STATIC
    {
      ALIGN_TOP; ALIGN_LEFT; 
      BORDERSIZE 5, 0, 0, 0; 
      COLUMNS 2;
      SPACE 4, 4;
      
      STATICTEXT IDC_STATIC { NAME IDS_STATIC; CENTER_V; ALIGN_LEFT; }
      EDITTEXT IDC_CCLIP_NAME { CENTER_V; CENTER_H; SIZE 180, 0; }
    }
    CHECKBOX IDC_CCLIP_CREATESOURCE { NAME IDS_CHECK; ALIGN_TOP; ALIGN_LEFT;  }
    GROUP IDC_STATIC
    {
      ALIGN_TOP; ALIGN_LEFT; 
      BORDERSIZE 0, 0, 0, 0; 
      COLUMNS 4;
      SPACE 4, 4;
      
      STATICTEXT IDC_STATIC { NAME IDS_STATIC4; CENTER_V; ALIGN_LEFT; }
      EDITNUMBERARROWS IDC_CCLIP_FROM1
      { CENTER_V; CENTER_H; SIZE 70, 0; }
      STATICTEXT IDC_STATIC { NAME IDS_STATIC5; CENTER_V; ALIGN_LEFT; }
      EDITNUMBERARROWS IDC_CCLIP_TO1
      { CENTER_V; CENTER_H; SIZE 70, 0; }
    }
  }
 
  DLGGROUP { OK; CANCEL; }
}