DIALOG IDD_EULERFILTER
{
	NAME TITLE;
	SCALE_H; SCALE_V;
		
	GROUP
	{
		ALIGN_TOP; ALIGN_LEFT; 
		BORDERSIZE 5, 0, 0, 0; 
		COLUMNS 4;
		SPACE 4, 4;
    
		STATICTEXT { NAME FROM; CENTER_V; ALIGN_LEFT; }
		EDITNUMBERARROWS IDC_EULERFILTER_FROM
		{ CENTER_V; CENTER_H; SIZE 70, 0; }
		STATICTEXT { NAME TO; CENTER_V; ALIGN_LEFT; }
		EDITNUMBERARROWS IDC_EULERFILTER_TO
		{ CENTER_V; CENTER_H; SIZE 70, 0; }
	}

	GROUP
	{
		COLUMNS 1;
		BORDERSIZE 4,4,4,4;
		SCALE_H; SCALE_V;

		CHECKBOX IDC_SYNCHRONIZEROTATION { NAME SYNCHROT; }
		CHECKBOX IDC_MINIMIZEGIMBAL { NAME MINGIMBAL; }	
		CHECKBOX IDC_ADJUSTTANGENT { NAME ADJTANGENT; }	
	}

	DLGGROUP { OK; CANCEL; }
}
