// C4D-DialogResource
DIALOG IDD_PVCACHE
{
  NAME IDS_DIALOG; CENTER_V; CENTER_H; 
  
  GROUP 
  {
    COLUMNS 1;
    
    STATICTEXT IDC_PVCACHE_STR { NAME IDS_PVCACHE_STR; CENTER_V; ALIGN_LEFT; }
    
     RADIOGROUP IDC_PVCACHE_GROUP
	  {
		GROUP
		{
		  COLUMNS 1;
	  
		  RADIOGADGET IDC_PVCACHE_CLEAR { NAME IDS_PVCACHE_CLEAR ; }
		  RADIOGADGET IDC_PVCACHE_IGNORE { NAME IDS_PVCACHE_IGNORE; }
		  //RADIOGADGET IDC_PVCAHCE_CHANGE { NAME IDS_PVCAHCE_CHANGE; }
		}
	  }
  }
  DLGGROUP { OK; CANCEL; }
}