// C4D-DialogResource
DIALOG IDD_ADDFROMTO
{
  NAME IDS_DIALOG; CENTER_V; CENTER_H; 
  
  GROUP IDC_ADDGROUP
  {
    ALIGN_TOP; ALIGN_LEFT; 
    BORDERSTYLE BORDER_NONE; BORDERSIZE 0, 0, 0, 0; 
    COLUMNS 2;
    
    STATICTEXT IDC_ADD_TEXT1 { NAME IDS_TEXT1; CENTER_V; ALIGN_LEFT; }
    EDITNUMBERARROWS IDC_ADD_FROM
    { CENTER_V; CENTER_H; SIZE 70, 0; }
    STATICTEXT IDC_ADD_TEXT2 { NAME IDS_TEXT2; CENTER_V; ALIGN_LEFT; }
    EDITNUMBERARROWS IDC_ADD_COUNT
    { CENTER_V; CENTER_H; SIZE 70, 0; }
  }
	DLGGROUP { OK; CANCEL; }
}