// C4D-DialogResource
DIALOG IDD_BAKE
{
  NAME IDS_DIALOG; CENTER_V; CENTER_H; 
  
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC1; ALIGN_TOP; ALIGN_LEFT; 
    BORDERSIZE 5, 0, 0, 0; 
    COLUMNS 6;
    SPACE 4, 4;
    
	STATICTEXT IDC_STATIC { NAME IDS_STATIC4; CENTER_V; ALIGN_LEFT; }
    EDITNUMBERARROWS IDC_BAKE_FROM
    { CENTER_V; CENTER_H; SIZE 70, 0; }
    STATICTEXT IDC_STATIC { NAME IDS_STATIC5; CENTER_V; ALIGN_LEFT; }
    EDITNUMBERARROWS IDC_BAKE_TO
    { CENTER_V; CENTER_H; SIZE 70, 0; }
  }
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC8; ALIGN_TOP; ALIGN_LEFT; 
    BORDERSIZE 5, 0, 0, 4; 
    COLUMNS 1;
    SPACE 4, 4;
    
    CHECKBOX IDC_BAKE_EXPRESSION { NAME IDS_CHECK14; ALIGN_TOP; ALIGN_LEFT;  }
		CHECKBOX IDC_BAKE_CREATECOPY { NAME IDS_CHECK13; ALIGN_TOP; ALIGN_LEFT;  }
		CHECKBOX IDC_BAKE_REMOVETAGS { NAME IDS_CHECK17; ALIGN_TOP; ALIGN_LEFT; }
    CHECKBOX IDC_BAKE_CLEANTRACKS { NAME IDS_CHECK15; ALIGN_TOP; ALIGN_LEFT;  }
  }
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC11; SCALE_V; SCALE_H; 
    BORDERSTYLE BORDER_GROUP_TOP; BORDERSIZE 4, 4, 4, 4; 
    COLUMNS 2;
    
    GROUP IDC_STATIC
    {
      NAME IDS_STATIC7; ALIGN_TOP; ALIGN_LEFT; 
      BORDERSIZE 10, 0, 10, 10; 
      COLUMNS 1;
      SPACE 5, 5;
      
	  CHECKBOX IDC_BAKE_ALL { NAME IDS_CHECK16; ALIGN_TOP; ALIGN_LEFT;  }
      CHECKBOX IDC_BAKE_POSITION { NAME IDS_CHECK1; ALIGN_TOP; ALIGN_LEFT;  }
      CHECKBOX IDC_BAKE_SCALE { NAME IDS_CHECK3; ALIGN_TOP; ALIGN_LEFT;  }
      CHECKBOX IDC_BAKE_ROTATION { NAME IDS_CHECK2; ALIGN_TOP; ALIGN_LEFT;  }
      CHECKBOX IDC_BAKE_PLA { NAME IDS_CHECK12; ALIGN_TOP; ALIGN_LEFT;  }
      CHECKBOX IDC_BAKE_PARAMETER { NAME IDS_CHECK4; ALIGN_TOP; ALIGN_LEFT;  }
	  
    }
  }
  DLGGROUP { OK; CANCEL; }
}
