// C4D-DialogResource
DIALOG IDD_VIEWMARKER
{
  NAME IDS_DIALOG; CENTER_V; CENTER_H; 
  
  GROUP IDC_STATIC
  {
    ALIGN_TOP; ALIGN_LEFT; 
    BORDERSIZE 0, 0, 0, 0; 
    COLUMNS 2;
    SPACE 4, 4;
    
    STATICTEXT IDC_VIEWMARKER_TEXT { NAME IDS_VIEWMARKERTEXT; CENTER_V; ALIGN_LEFT; }
    EDITTEXT IDC_VIEWMARKER_FIELD { CENTER_V; CENTER_H; SIZE 70, 0; }
    STATICTEXT IDC_VIEWMARKER_FOUND { NAME IDS_VIEWMARKERTEXT2; CENTER_V; ALIGN_LEFT; }
  }
  
  DLGGROUP { OK; CANCEL; }
}