// C4D-DialogResource
DIALOG IDD_SPLINE
{
  NAME IDS_DIALOG; CENTER_V; CENTER_H; 
  
  GROUP IDC_SP_GROUP1
  {
    ALIGN_TOP; ALIGN_LEFT; 
    BORDERSIZE 0, 0, 0, 0; 
    COLUMNS 2;
    SPACE 4, 4;
    
    STATICTEXT IDC_NAME { NAME IDS_TEXT; CENTER_V; ALIGN_LEFT; }
    EDITTEXT IDC_SPLINE_TEXT
    { CENTER_V; CENTER_H; SIZE 200, 0; }
    STATICTEXT IDC_SPLINE_FOUND { NAME IDS_TEXT2; CENTER_V; ALIGN_LEFT; }
  }
  
  DLGGROUP { OK; CANCEL; }
}