// C4D-DialogResource
DIALOG IDD_PVSAVE
{
  NAME IDS_DIALOG;
  
  GROUP
  {
		SCALE_V; SCALE_H; 
    BORDERSTYLE BORDER_NONE; BORDERSIZE 3, 3, 3, 3; 
    COLUMNS 1;
    
    //Image,Sequence etc.
    GROUP
    {
      SCALE_V; SCALE_H; 
      BORDERSTYLE BORDER_NONE; BORDERSIZE 0, 0, 0, 0; 
      COLUMNS 3;
      
      STATICTEXT IDC_PVSAVE_ST1 { NAME IDS_STATIC1; CENTER_V; ALIGN_LEFT; }
      COMBOBOX IDC_PVSAVE_OPEN
      {
        ALIGN_TOP; FIT_H; 
        CHILDS
        {
        }
      }
			STATICTEXT { ALIGN_LEFT; }
      
      STATICTEXT IDC_PVSAVE_ST4 { NAME IDS_STATIC8; CENTER_V; ALIGN_LEFT; }
			COMBOBOX IDC_PVSAVE_TYPE
      {
          ALIGN_TOP; FIT_H; 
          CHILDS
          {
          }
      }
			BUTTON IDC_PVSAVE_OPTIONS { NAME IDS_STATIC9; }
      
      STATICTEXT IDC_PVSAVE_ST5 { NAME IDS_STATIC10; CENTER_V; ALIGN_LEFT; }
      COMBOBOX IDC_PVSAVE_DEPTH
      {
        ALIGN_TOP; FIT_H; 
        CHILDS
        {
				}
      }
			STATICTEXT { ALIGN_LEFT; }

      STATICTEXT IDC_PVSAVE_ST6 { NAME IDS_STATIC11; CENTER_V; ALIGN_LEFT; }
      COMBOBOX IDC_PVSAVE_NAMETYPE
      {
        ALIGN_TOP; FIT_H; 
        CHILDS
        {
					0,IDS_PVSAVE_NAMETYPE_0;
					1,IDS_PVSAVE_NAMETYPE_1;
					2,IDS_PVSAVE_NAMETYPE_2;
					3,IDS_PVSAVE_NAMETYPE_3;
					4,IDS_PVSAVE_NAMETYPE_4;
					5,IDS_PVSAVE_NAMETYPE_5;
					6,IDS_PVSAVE_NAMETYPE_6;
        }
      }
			STATICTEXT { ALIGN_LEFT; }

      STATICTEXT IDC_PVSAVE_ST12 { NAME IDS_STATIC27; CENTER_V; ALIGN_LEFT; }
			COMBOBOX IDC_PVSAVE_STEREO 
			{
				ALIGN_TOP; FIT_H; 
				CHILDS
				{
				}
			}
			EDITNUMBERARROWS IDC_PVSAVE_STEREO_CHANNEL { CENTER_V; ALIGN_LEFT;  SIZE 70, 0; }
    }

		SEPARATOR { SCALE_H; }

		//from to
		GROUP
		{
			SCALE_V; SCALE_H;
			COLUMNS 4;
	  
			STATICTEXT IDC_PVSAVE_ST2 { NAME IDS_STATIC2; CENTER_V; ALIGN_LEFT; }
			EDITNUMBERARROWS IDC_PVSAVE_FROM { CENTER_V; ALIGN_LEFT;  SIZE 70, 0; }
			STATICTEXT IDC_PVSAVE_ST3 { NAME IDS_STATIC5; CENTER_V; ALIGN_LEFT; }
			EDITNUMBERARROWS IDC_PVSAVE_TO { CENTER_V; ALIGN_LEFT;  SIZE 70, 0; }
			STATICTEXT IDC_PVSAVE_ST7 { NAME IDS_STATIC16; CENTER_V; ALIGN_LEFT; }
			EDITNUMBERARROWS IDC_PVSAVE_FPS { CENTER_V; ALIGN_LEFT;  SIZE 70, 0; }
			STATICTEXT IDC_PVSAVE_ST8 { NAME IDS_STATIC17; CENTER_V; ALIGN_LEFT; }
			EDITNUMBERARROWS IDC_PVSAVE_RESOLUTION { CENTER_V; ALIGN_LEFT; SIZE 70, 0; }
	 
		}
		SEPARATOR { SCALE_H; }
		GROUP
		{
				 SCALE_V; SCALE_H; 
			COLUMNS 2;
			CHECKBOX IDC_PVSAVE_LAYER {NAME IDS_STATIC12; CENTER_V;ALIGN_LEFT; }
			CHECKBOX IDC_PVSAVE_ALPHA {NAME IDS_STATIC13; CENTER_V; ALIGN_LEFT; }
			CHECKBOX IDC_PVSAVE_SOUND {NAME IDS_STATIC14; CENTER_V; ALIGN_LEFT; }
		//CHECKBOX IDC_PVSAVE_SINGLEFILE {NAME IDS_STATIC19; CENTER_V; ALIGN_LEFT;}
		}

		GROUP
		{
			SCALE_V; SCALE_H; 
			BORDERSTYLE BORDER_GROUP_IN; BORDERSIZE 2, 2, 2, 2; 
			COLUMNS 1;
		
			NAME IDS_STATIC26;

			GROUP
			{
				SCALE_V; SCALE_H; 
				COLUMNS 2;
				CHECKBOX IDC_PVSAVE_ABCOMAPRE {NAME IDS_STATIC25; CENTER_V; ALIGN_LEFT;}
				CHECKBOX IDC_PVSAVE_FILTER {NAME IDS_STATIC15; CENTER_V; ALIGN_LEFT;}
			}	
			SEPARATOR { SCALE_H; }
			GROUP
			{
				SCALE_V; SCALE_H; 
				COLUMNS 1;
		  
				CHECKBOX IDC_PVSAVE_RESCALE {NAME IDS_STATIC21; CENTER_V; ALIGN_LEFT;}
				CHECKBOX IDC_PVSAVE_SCALEPROP {NAME IDS_STATIC24; CENTER_V; ALIGN_LEFT;}
				GROUP
				{
					ALIGN_TOP; ALIGN_LEFT; 
					BORDERSTYLE BORDER_NONE; BORDERSIZE 0, 0, 0, 0; 
					COLUMNS 3;
					
					STATICTEXT IDC_PVSAVE_ST10 { NAME IDS_STATIC22; CENTER_V; ALIGN_LEFT; }
					EDITNUMBERARROWS IDC_PVSAVE_WIDTH { CENTER_V; CENTER_H; SIZE 70, 0; }
					EDITNUMBERARROWS IDC_PVSAVE_HEIGHT { CENTER_V; CENTER_H; SIZE 70, 0; }

					STATICTEXT { NAME IDS_ASPECTRATIO; CENTER_V; ALIGN_LEFT; }
					EDITNUMBERARROWS IDC_PVSAVE_ASPECTRATIO { CENTER_V; CENTER_H; SIZE 70, 0;}
					STATICTEXT {}

					STATICTEXT IDC_PVSAVE_ST10 { NAME IDS_STATIC22a; CENTER_V; ALIGN_LEFT; }
					EDITNUMBERARROWS IDC_PVSAVE_DISPLAY_WIDTH { CENTER_V; CENTER_H; SIZE 70, 0; }
					EDITNUMBERARROWS IDC_PVSAVE_DISPLAY_HEIGHT { CENTER_V; CENTER_H; SIZE 70, 0; }
				}
 			  MULTILINEEDIT IDC_PVSAVE_WARNING { SCALE_V; SCALE_H; SIZE 70, 80; READONLY; }
			}
		}
		GROUP
		{
			COLUMNS 1;
			BUTTON IDC_PVSAVE_RESETRENDER { NAME IDS_STATIC18; }
		}
	}
  DLGGROUP { OK; CANCEL; }
}
