// C4D-DialogResource
DIALOG IDD_CYCLE
{
  NAME IDS_DIALOG; CENTER_V; CENTER_H; 
  
  GROUP IDC_CYCLE_GR1
  {
    ALIGN_TOP; ALIGN_LEFT; 
    BORDERSIZE 0, 0, 0, 0; 
    COLUMNS 2;
    SPACE 4, 4;
    
    STATICTEXT IDC_CYLCE_TXT1 { NAME IDS_TEXT1; CENTER_V; ALIGN_LEFT; }
    EDITNUMBERARROWS IDC_CYCLE_COUNT { CENTER_V; CENTER_H; SIZE 70, 0; }

		STATICTEXT IDC_CYLCE_TXT2 { NAME IDS_TEXT2; CENTER_V; ALIGN_LEFT; }
    CHECKBOX	 IDC_CYCLE_OFFSET { CENTER_V; CENTER_H; }
  }
  
  DLGGROUP { OK; CANCEL; }
}