CONTAINER CKmorph
{
	NAME CKmorph;
	INCLUDE CKbase;

	GROUP ID_CKEY_PROPERTIES
	{
		LINK	CID_MORPHKEY_LINK { ACCEPT { Obase; } HIDE_ICON; }
		REAL	CID_MORPHKEY_BIAS  { UNIT PERCENT; MIN -100.0; MAX 100.0;  }
		BOOL	CID_MORPHKEY_CUBIC {  }

		DEFAULT	1;
	}
}
