CONTAINER CKsound
{
	NAME CKsound;
	INCLUDE CKbase;

	GROUP ID_CKEY_PROPERTIES
	{
		REAL CID_SOUNDKEY_VOLUME  { UNIT PERCENT; MIN 0.0; STEP 5.0; }
		REAL CID_SOUNDKEY_BALANCE	{ UNIT PERCENT; MIN -100.0; MAX 100.0; STEP 5.0; }
		DEFAULT	1;
	}
}
