CONTAINER MT_LAYER
{
	NAME MT_LAYER;
	INCLUDE Obaselist;

	GROUP Obaselist
	{
		//HIDE ID_LAYER_LINK;

		GROUP
		{
			REAL	ID_MT_LAYER_VALUE {UNIT PERCENT;}

			LONG ID_MT_LAYER_MODE
			{
				ANIM OFF;
				CYCLE
				{
					ID_MT_LAYER_MODE_MIX;
					ID_MT_LAYER_MODE_ADD;
					ID_MT_LAYER_MODE_REP;
				}
			}
			GROUP
			{
				COLUMNS 1;
				BOOL	ID_MT_LAYER_MUTE   {ANIM OFF;}
				BOOL	ID_MT_LAYER_SOLO   {ANIM OFF;}
				BOOL	ID_MT_LAYER_PASSTHROUGH {ANIM OFF;}
				BOOL	ID_MT_LAYER_ACTIVE		{ANIM OFF;}
				BOOL	ID_MT_LAYER_QUATERNION	{ANIM OFF;}
			}
		}

		SEPARATOR { LINE; }


	}

}
