CONTAINER Prefstimeline
{
	NAME Prefstimeline;
	GROUP PREF_TL_MAIN_GROUP
	{
	
		DEFAULT 1;
		COLUMNS 2;

		SEPARATOR PREF_TL_AMGROUP {}
		STATICTEXT {JOINENDSCALE;}

		BOOL PREF_TL_KEYFRAMEDOTS {ANIM OFF; }
		STATICTEXT {JOINENDSCALE;}

		BOOL PREF_TL_DOTSKILLTRACKS {ANIM OFF; }
		STATICTEXT {JOINENDSCALE;}
		
		SEPARATOR PREF_TL_DISPLAYGROUP {}
		STATICTEXT {JOINENDSCALE;}
		BOOL PREF_TL_INDICATOR {ANIM OFF;}
		STATICTEXT{}
		BOOL PREF_TL_INTERACTIVE {ANIM OFF;}
		STATICTEXT{}
		BOOL PREF_TL_HIGHLIGHT {ANIM OFF;}
		STATICTEXT{}
		LONG PREF_TL_TRACKCOL
		{
			ANIM OFF;
			CYCLE
			{
				PREF_TL_TRACKCOL_COL;
				PREF_TL_TRACKCOL_PSR;
				PREF_TL_TRACKCOL_NO;

			}
		}
		STATICTEXT{}
		SEPARATOR PREF_TL_LINKGROUP {}
		STATICTEXT {JOINENDSCALE;}	
		BOOL PREF_TL_LINKKEYFCSELECTION {ANIM OFF;}
		STATICTEXT{}
		BOOL PREF_TL_LINKOMSELECTONLY {ANIM OFF;}
		STATICTEXT{}
		BOOL PREF_TL_LINKOMSELECTONLYBUTTAGS {ANIM OFF;}
		STATICTEXT{}

		
		SEPARATOR PREF_TL_OBJECTGROUP {}
		STATICTEXT {JOINENDSCALE;}	
		BOOL PREF_TL_SHOWBRANCHES {ANIM OFF;}
		STATICTEXT{}
		BOOL PREF_TL_SHOWVECTOR {ANIM OFF;}
		STATICTEXT{}
		BOOL PREF_TL_FCLISTVIEW_HIERARCHICAL {ANIM OFF;}
		STATICTEXT{}	
		BOOL PREF_TL_FCLISTVIEW {ANIM OFF;}
		STATICTEXT{}			
		SEPARATOR PREF_TL_KEYGROUP {}
		STATICTEXT {JOINENDSCALE;}	
		BOOL PREF_TL_SUMMARY {ANIM OFF;}
		STATICTEXT{}
		BOOL PREF_TL_TRACKSTARTEND {ANIM OFF;}
		STATICTEXT{}
		BOOL PREF_TL_DOPESHEET {ANIM OFF;}
		STATICTEXT{}
		BOOL PREF_TL_KEYSYMBOLS {ANIM OFF;}
		STATICTEXT{}
		BOOL PREF_TL_LAYERCOL {ANIM OFF;}
		STATICTEXT{}
		LONG PREF_TL_KEYWIDTHVALUE {ANIM OFF; MIN 1; MAX 100;}
		STATICTEXT{}
		
		SEPARATOR PREF_TL_FCGROUP {}
		STATICTEXT {JOINENDSCALE;}	
		
		REAL PREF_TL_RMREDUCTION {ANIM OFF; UNIT PERCENT; MIN 0.0; MAX 100.0;}
		STATICTEXT{}
		
		SEPARATOR PREF_TL_MOTIONGROUP {}
		STATICTEXT {JOINENDSCALE;}	
		
		BASETIME PREF_TL_MOTION {ANIM OFF; MIN 0;}
		STATICTEXT{}
	}
}
