CONTAINER TakeBase
{
	NAME TakeBase;
	INCLUDE Obaselist;
	GROUP Obaselist
	{
		HIDE ID_LAYER_LINK;

		SEPARATOR { LINE; }
		
		BOOL TAKEBASE_CHECK		{ HIDDEN; }
		LONG TAKEBASE_INDEX		{ HIDDEN; }
		LINK TAKEBASE_CAMERA	{ HIDDEN; }
		LINK TAKEBASE_RDATA		{ HIDDEN; }
		IN_EXCLUDE TAKEBASE_OVERRIDES 
		{
			HIDDEN;
			NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 1;
		}
		LONG TAKEBASE_CAMERA_COMBO
		{
			ANIM OFF;
			CYCLE { }
		}
		LONG TAKEBASE_RDATA_COMBO
		{
			ANIM OFF;
			CYCLE {  }
		}
		
		SEPARATOR { LINE; }

		STRING TAKEBASE_NOTES
		{
			ANIM OFF; CUSTOMGUI MULTISTRING; WORDWRAP; SCALE_V;
		}
	}
}
