CONTAINER TLMarker
{
	NAME TLMarker;
	INCLUDE Obaselist;

	GROUP Obaselist
	{
		BASETIME	TLMARKER_TIME {ANIM OFF;}
		BASETIME	TLMARKER_LENGTH {ANIM OFF; MIN 0;}
		COLOR		TLMARKER_COLOR {ANIM OFF;}
		SEPARATOR { }
		BOOL		TLMARKER_TASK {ANIM OFF;}
		BOOL		TLMARKER_DONE {ANIM OFF;}
		SEPARATOR { }
		GROUP
		{
			BOOL 		TLMARKER_EXPORT_ANIMATION_TAKE {ANIM OFF;}
		}
		SEPARATOR { }
		STRING		TLMARKER_TEXT {CUSTOMGUI MULTISTRING; ANIM OFF; SCALE_V; WORDWRAP;}
	}
}
