CONTAINER TLWorld
{
	NAME TLWorld;
	

	GROUP TLWORLD_GROUP
	{
		DEFAULT	1;
		COLUMNS 2;

		BOOL TLWORLD_OVERDUB	{ANIM OFF;}
		STATICTEXT { }

		LONG TLWORLD_INTER	{ANIM OFF; CYCLE { TLWORLD_INTER_SP; TLWORLD_INTER_LI; TLWORLD_INTER_ST; } } 	
		STATICTEXT { }

		LONG TLWORLD_QUATINTER	{ANIM OFF; CYCLE { TLWORLD_QUATINTER_LINEAR; TLWORLD_QUATINTER_CUBIC; } }  // TLWORLD_QUATINTER_SPLINE removed
		STATICTEXT { }


		SEPARATOR { LINE; } STATICTEXT { JOINENDSCALE; }
		BOOL TLWORLD_LOCKT		{ ANIM OFF; }
		BOOL TLWORLD_BREAKDOWN	{ ANIM OFF; }

		BOOL TLWORLD_LOCKV	{ANIM OFF;}
		BOOL TLWORLD_BREAKDOWNCOLOR{ ANIM OFF; }


		SEPARATOR { LINE; } STATICTEXT { JOINENDSCALE; }
		LONG TLWORLD_PRESET    
		{
			ALIGN_LEFT; ANIM OFF; PARENTCOLLAPSE;
			CYCLE { TLWORLD_PRESET_CLASSICAUTO; TLWORLD_PRESET_NEWAUTO; TLWORLD_PRESET_NEWAUTOWEIGHTED; TLWORLD_PRESET__CUSTOM; } 
		}
		STATICTEXT { }

		// included in Preset Collapse
		BOOL TLWORLD_AUTO  { ANIM OFF; PARENTCOLLAPSE TLWORLD_PRESET;}
		LONG TLWORLD_AUTOTYPE   { ANIM OFF; PARENTCOLLAPSE TLWORLD_PRESET; CYCLE { TLWORLD_AUTOTYPE_CLASSIC; TLWORLD_AUTOTYPE_FIXEDSLOPE; } }
		
		BOOL TLWORLD_CLAMP { ANIM OFF; PARENTCOLLAPSE TLWORLD_PRESET;}
		BOOL TLWORLD_REMOVEOVERSHOOT { ANIM OFF; PARENTCOLLAPSE TLWORLD_PRESET;}

		BOOL TLWORLD_WEIGHTEDTANGENT { ANIM OFF; PARENTCOLLAPSE TLWORLD_PRESET;}
		BOOL TLWORLD_AUTOWEIGHT { ANIM OFF; PARENTCOLLAPSE TLWORLD_PRESET;}

	
		SEPARATOR { LINE; } STATICTEXT { JOINENDSCALE; }
		BOOL TLWORLD_LOCKTA  {ANIM OFF;}
		BOOL TLWORLD_LOCKTL  {ANIM OFF;}
		
		BOOL TLWORLD_BREAK  {ANIM OFF;}
		BOOL TLWORLD_KEEPVISUALANGLE  {ANIM OFF;}
	}
}
