CONTAINER ToDoTag
{
	NAME ToDoTag;
	INCLUDE Obaselist;

	GROUP Obaselist
	{
		SCALE_V;
		SHOW 		ID_BASELIST_ICON_SETTINGS_GROUP;
		BOOL		TODOTAG_DONE { ANIM OFF; }
		STRING	TODOTAG_TEXT { CUSTOMGUI MULTISTRING; ANIM OFF; SCALE_V; }
	}
}
