CONTAINER vpmagicbulletlooks
{
	NAME vpmagicbulletlooks;
	INCLUDE VPbase;

	GROUP ID_VIDEOPOSTPROPERTIES
	{
		COLUMNS 1;
		
		BUTTON VP_MAGICBULLETLOOKS_LOOKSBUILDER {}
		STATICTEXT VP_MAGICBULLETLOOKS_LOOKNAME {}
		BITMAPBUTTON VP_MAGICBULLETLOOKS_PREVIEWAFTER {BORDER; NO_FADING; }
		REAL VP_MAGICBULLETLOOKS_STRENGTH { UNIT PERCENT; STEP 1; MIN 0; MAX 100; CUSTOMGUI REALSLIDER; }
		BOOL VP_MAGICBULLETLOOKS_SAVEPREVIEW { ANIM OFF; }
		
		STATICTEXT { JOINENDSCALE; }
	}
}
