CONTAINER vpnormalpass
{
	NAME vpnormalpass;
	INCLUDE VPbase;

	GROUP ID_VIDEOPOSTPROPERTIES
	{
		COLUMNS 2;

		LONG					VP_NORMALPASS_SPACE
		{
			CYCLE
			{
				VP_NORMALPASS_SPACE_WORLD;
				VP_NORMALPASS_SPACE_CAMERA;
				VP_NORMALPASS_SPACE_OBJECT;
			}
		}
		STATICTEXT														{  }

		LONG					VP_NORMALPASS_FLIP
		{
			CYCLE
			{
				VP_NORMALPASS_FLIP_RGB;
				VP_NORMALPASS_FLIP_RBG;
				VP_NORMALPASS_FLIP_GBR;
				VP_NORMALPASS_FLIP_GRB;
				VP_NORMALPASS_FLIP_BGR;
				VP_NORMALPASS_FLIP_BRG;
			}
		}
		STATICTEXT														{  }

		BOOL					VP_NORMALPASS_INVERTZ	{  }
		STATICTEXT		{  }

		SEPARATOR															{  }
		STATICTEXT														{ JOINENDSCALE; }

		GROUP
		{
			STATICTEXT		VP_NORMALPASS_INFO	{  }
		}
		STATICTEXT														{ JOINENDSCALE; }
	}
}
