CONTAINER VPtext
{
	NAME VPtext;
	INCLUDE VPbase;

	GROUP ID_VIDEOPOSTPROPERTIES
	{
		BOOL	VP_TEXT_RENDER_OUTPUT_RENDER	{HIDDEN;}
		BOOL	VP_TEXT_RENDER_OUTPUT_VIDEOPOST	{HIDDEN;}	
		BOOL	VP_TEXT_RENDER_OUTPUT_MULTIPASS	{HIDDEN;}
		
		GROUP VP_TEXT_GRP_DISPLAY
		{
		
			DEFAULT 1;
			GROUP VP_TEXT_GRP_TEXT
			{
				STRING	VP_TEXT_STRING		{	CUSTOMGUI MULTISTRING; }
				GROUP 
				{
					COLUMNS 2;
					REAL	VP_TEXT_U		{	UNIT PERCENT;	MIN 0.0;	MAX 100.0;	STEP 0.1;	}
					REAL	VP_TEXT_V		{	UNIT PERCENT;	MIN 0.0;	MAX 100.0;	STEP 0.1;	}
				}
				LONG	VP_TEXT_TAB_SIZE	{	MIN 0;	MAX 16;}
				LONG	VP_TEXT_ALIGN
				{	
					CYCLE
					{
						VP_TEXT_ALIGN_LEFT;
						VP_TEXT_ALIGN_CENTER;
						VP_TEXT_ALIGN_RIGHT;
					}
				}

			}
			
			
			GROUP	VP_TEXT_GRP_INFO
			{
				LONG VP_TEXT_INFO_ALIGN
				{
					CYCLE
						{
						VP_TEXT_INFO_ALIGN_TOP;
						VP_TEXT_INFO_ALIGN_BOTTOM;
						}
				}
				SEPARATOR	{LINE;}
				GROUP
				{
					COLUMNS 2;
						
					BOOL	VP_TEXT_INFO_OBJECTCOUNT	{}
					BOOL	VP_TEXT_INFO_LIGHTCOUNT		{}	
					
					BOOL	VP_TEXT_INFO_POLYGONCOUNT	{}
					BOOL	VP_TEXT_INFO_VERTEXCOUNT	{}
					
					BOOL	VP_TEXT_INFO_SCENETIME		{}
				}
			}


			GROUP VP_TEXT_GRP_SETTINGS
			{
				GROUP	VP_TEXT_GRP_PEN
				{
					DEFAULT 1;
					COLOR	VP_TEXT_PEN			{}
					REAL	VP_TEXT_PEN_OPACITY	{UNIT PERCENT;	MIN 0.0;	MAX 100.0;	STEP 0.1;}
				}
		
				GROUP	VP_TEXT_GRP_PAPER
				{
					DEFAULT 1;
					COLOR	VP_TEXT_PAPER				{}
					REAL	VP_TEXT_PAPER_OPACITY		{UNIT PERCENT;	MIN 0.0;	MAX 100.0;	STEP 0.1;}
					LONG	VP_TEXT_PAPER_BORDER		{MIN 0;	MAX 100;}
					LONG	VP_TEXT_PAPER_ROUNDING		{MIN 0;	MAX 100;}
					BOOL	VP_TEXT_PAPER_DRAW_BORDER	{}
				}
			}
	

		
		}

		
		GROUP	VP_TEXT_GRP_WATERMARK
		{
			TEXTURE VP_TEXT_WATERMARK		{}
			REAL	VP_TEXT_WATERMARK_OPACITY	{	UNIT PERCENT;	MIN 0.0;	MAX 100.0;	STEP 0.1;	}

			REAL	VP_TEXT_WATERMARK_SCALE		{	UNIT PERCENT;	MIN 0.0;	MAX 100.0;	STEP 0.1;}
				
			LONG	VP_TEXT_WATERMARK_V_ALIGN	
			{
				CYCLE
				{
					VP_TEXT_WATERMARK_TOP;
					VP_TEXT_WATERMARK_VCENTER;
					VP_TEXT_WATERMARK_BOTTOM;
				}
			}
			LONG VP_TEXT_WATERMARK_H_ALIGN	
			{
				CYCLE
				{
					VP_TEXT_WATERMARK_LEFT;
					VP_TEXT_WATERMARK_HCENTER;
					VP_TEXT_WATERMARK_RIGHT;
				}
			}

			
		}
		
	}
}
