CONTAINER vpwatermark
{
	NAME vpwatermark;
	INCLUDE VPbase;

	GROUP ID_VIDEOPOSTPROPERTIES
	{
		//GROUP VP_WATERMARK_PREVIEW
		//{
		//	DEFAULT 1;

		//	BITMAPBUTTON	VP_WATERMARK_PREVIEW_IMAGE		{ ANIM OFF; }
		//}

		GROUP VP_WATERMARK_TEXT
		{
			DEFAULT 1;
			COLUMNS 3;
			
			GROUP
			{
				COLUMNS 3;

				BOOL					VP_WATERMARK_TEXT_ENABLE					{  }
				BOOL					VP_WATERMARK_TEXT_DYNAMICLAYOUT		{  }
				BOOL					VP_WATERMARK_TEXT_SHOWLABELS			{  }
			}
			STATICTEXT		{ JOINENDSCALE; }
			STATICTEXT		{ JOINENDSCALE; }

			SEPARATOR																				{ LINE; }
			STATICTEXT		{ JOINENDSCALE; }
			STATICTEXT		{ JOINENDSCALE; }

			BOOL					VP_WATERMARK_TEXT_TIMECODE				{  }
			BOOL					VP_WATERMARK_TEXT_RENDERTIME			{  }
			STATICTEXT		{  }

			BOOL					VP_WATERMARK_TEXT_ACTIVECAMERA		{  }
			BOOL					VP_WATERMARK_TEXT_DATE						{  }
			STATICTEXT		{  }

			BOOL					VP_WATERMARK_TEXT_SCENENAME				{  }
			BOOL					VP_WATERMARK_TEXT_POLYCOUNT				{  }
			STATICTEXT		{  }

			BOOL					VP_WATERMARK_TEXT_C4DVERSION			{  }
			BOOL					VP_WATERMARK_TEXT_MACHINEINFO			{  }
			STATICTEXT		{  }

      BOOL          VP_WATERMARK_TEXT_TAKE            {  }
      STATICTEXT		{  }
      STATICTEXT		{  }

			BOOL					VP_WATERMARK_TEXT_CUSTOM					{  }
			STATICTEXT		{  }
			STATICTEXT		{  }

			GROUP
			{
				COLUMNS 3;
				STRING				VP_WATERMARK_TEXT_CUSTOM_TEXT			{  }
				STATICTEXT		{ JOINENDSCALE; }
				POPUP					VP_WATERMARK_TEXT_CUSTOM_TEXT_PH	{  }
			}
			STATICTEXT		{ JOINENDSCALE; }
			STATICTEXT		{ JOINENDSCALE; }

			REAL					VP_WATERMARK_TEXT_BG_OPACITY			{ UNIT PERCENT; MIN 0.0; MAX 100.0; STEP 1.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT		{ JOINENDSCALE; }
			STATICTEXT		{ JOINENDSCALE; }
	
			LONG					VP_WATERMARK_TEXT_POS_Y						{ CYCLE { VP_WATERMARK_POS_TOP; VP_WATERMARK_POS_BOTTOM; } }
			STATICTEXT		{ JOINENDSCALE; }
			STATICTEXT		{  }

			FONT					VP_WATERMARK_TEXT_FONT						{ SCALE_H; FONTCHOOSER_ENABLE_SIZE; OPEN; }
			STATICTEXT		{ JOINENDSCALE; }
			STATICTEXT		{  }
			
			COLOR					VP_WATERMARK_TEXT_COLOR						{  }
			STATICTEXT		{ JOINENDSCALE; }
			STATICTEXT		{ JOINENDSCALE; }
			
			COLOR					VP_WATERMARK_TEXT_BG_COLOR				{  }
			STATICTEXT		{ JOINENDSCALE; }
			STATICTEXT		{ JOINENDSCALE; }
		}

		GROUP	VP_WATERMARK_IMG
		{
			DEFAULT 1;
			COLUMNS 3;

			BOOL					VP_WATERMARK_IMG_ENABLE				{  }
			STATICTEXT		{  }
			STATICTEXT		{  }

			SEPARATOR																				{ LINE; }
			STATICTEXT		{ JOINENDSCALE; }
			STATICTEXT		{ JOINENDSCALE; }

			FILENAME			VP_WATERMARK_IMG_FILENAME			{ ANIM OFF; }
			STATICTEXT		{ JOINENDSCALE; }
			STATICTEXT		{ JOINENDSCALE; }

			REAL					VP_WATERMARK_IMG_OPACITY			{ UNIT PERCENT; MIN 0.0; MAX 100.0; STEP 1.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT		{ JOINENDSCALE; }
			STATICTEXT		{ JOINENDSCALE; }

			LONG					VP_WATERMARK_IMG_BLENDMODE		{ CYCLE {
																											VP_IMG_BLENDMODE_NORMAL;
																											VP_IMG_BLENDMODE_LIGHTEN;
																											VP_IMG_BLENDMODE_DARKEN;
																											VP_IMG_BLENDMODE_MULTIPLY;
																											VP_IMG_BLENDMODE_ADD;
																											VP_IMG_BLENDMODE_OVERLAY;
																											VP_IMG_BLENDMODE_COLORDODGE;
																											VP_IMG_BLENDMODE_COLORBURN;
																											VP_IMG_BLENDMODE_LINEARDODGE;
																											VP_IMG_BLENDMODE_LINEARBURN;
																											VP_IMG_BLENDMODE_COLOR;
																											VP_IMG_BLENDMODE_COLOR_INV;
																									} }
			STATICTEXT		{ JOINENDSCALE; }
			STATICTEXT		{  }

			LONG					VP_WATERMARK_IMG_POS_X				{ CYCLE { VP_WATERMARK_POS_LEFT; VP_WATERMARK_POS_CENTER; VP_WATERMARK_POS_RIGHT; } }
			STATICTEXT		{ JOINENDSCALE; }
			STATICTEXT		{  }
			LONG					VP_WATERMARK_IMG_POS_Y				{ CYCLE { VP_WATERMARK_POS_TOP; VP_WATERMARK_POS_CENTER; VP_WATERMARK_POS_BOTTOM; } }
			STATICTEXT		{ JOINENDSCALE; }
			STATICTEXT		{  }
			LONG					VP_WATERMARK_IMG_MARGIN				{ MIN 0; }
			STATICTEXT		{  }
			STATICTEXT		{  }

			REAL					VP_WATERMARK_IMG_SCALE				{ UNIT PERCENT; MIN 0.1; MAX 1000.0; STEP 1.0; }
			STATICTEXT		{  }
			STATICTEXT		{  }
			BOOL					VP_WATERMARK_IMG_SCALE_ASPECT	{  }
			STATICTEXT		{  }
			STATICTEXT		{  }
			BOOL					VP_WATERMARK_IMG_SCALE_KEEPSIZE	{  }
			STATICTEXT		{  }
			STATICTEXT		{  }
		}

		//GROUP VP_WATERMARK_ADVANCED
		//{
		//	BOOL					VP_WATERMARK_ADVANCED_ADDMULTIPASS	{  }
		//	BOOL					VP_WATERMARK_ADVANCED_RENDERHUD			{  }
		//}
	}
}
