CONTAINER F3dsimport
{
	NAME F3dsimport;
	INCLUDE Fbase;

	GROUP F3DSIMPORTFILTER_GROUP
	{
		DEFAULT 1;
		UNITSCALE F3DSIMPORTFILTER_SCALE { }
		BOOL F3DSIMPORTFILTER_RENAMETEXTURES {DEFAULT 0; }
		STRING F3DSIMPORTFILTER_TEXTURESUFFIX	{ }
	}
}
