CONTAINER Faiimport
{
	NAME Faiimport;
	INCLUDE Fbase;

	GROUP AIIMPORTFILTER_GROUP
	{
		UNITSCALE AIIMPORTFILTER_SCALE	{ }
		BOOL AIIMPORTFILTER_CONNECTSPLINES { DEFAULT 1;}
		BOOL AIIMPORTFILTER_GROUPSPLINES { DEFAULT 1;}
	}
}
