CONTAINER Fbox
{
	NAME		Fbox;
	INCLUDE Ofield;

	GROUP ID_FIELDPROPERTIES
	{
		VECTOR FIELD_BOX_SIZE { MINSLIDER 0.0; MIN 0.0; UNIT METER; CUSTOMGUI SUBDESCRIPTION; }
		BOOL FIELD_BOX_CLIPPED { }
	}
}
