CONTAINER Fcapsule
{
	NAME		Fcapsule;
	INCLUDE Ofield;

	GROUP ID_FIELDPROPERTIES
	{
		REAL FIELD_CAPSULE_TOP { MINSLIDER 0.0; MIN 0.0; UNIT METER; MAXSLIDER 500.0; CUSTOMGUI REALSLIDER; }
		REAL FIELD_CAPSULE_BOTTOM { MINSLIDER 0.0; MIN 0.0; UNIT METER; MAXSLIDER 500.0; CUSTOMGUI REALSLIDER; }
		REAL FIELD_CAPSULE_HEIGHT { MINSLIDER 0.0; MIN 0.0; UNIT METER; MAXSLIDER 500.0; CUSTOMGUI REALSLIDER; }
		LONG FIELD_CAPSULE_DIRECTION
		{
			CYCLE
			{
				FIELD_CAPSULE_DIRECTION_XP;
				FIELD_CAPSULE_DIRECTION_XN;
				FIELD_CAPSULE_DIRECTION_YP;
				FIELD_CAPSULE_DIRECTION_YN;
				FIELD_CAPSULE_DIRECTION_ZP;
				FIELD_CAPSULE_DIRECTION_ZN;
			}
		}
		BOOL FIELD_CAPSULE_CLIP {}
	}
}
