CONTAINER Fcone
{
	NAME		Fcone;
	INCLUDE Ofield;

	GROUP ID_FIELDPROPERTIES
	{
		REAL FIELD_CONE_HEIGHT { MINSLIDER 0.0; MIN 0.0; UNIT METER; MAXSLIDER 500.0; CUSTOMGUI REALSLIDER; }
		REAL FIELD_CONE_RADIUS { MINSLIDER 0.0; MIN 0.0; UNIT METER; MAXSLIDER 500.0; CUSTOMGUI REALSLIDER; }
		LONG FIELD_CONE_DIRECTION
		{
			CYCLE
			{
				FIELD_CONE_DIRECTION_XP;
				FIELD_CONE_DIRECTION_XN;
				FIELD_CONE_DIRECTION_YP;
				FIELD_CONE_DIRECTION_YN;
				FIELD_CONE_DIRECTION_ZP;
				FIELD_CONE_DIRECTION_ZN;
			}
		}
		BOOL FIELD_CONE_CLIP { }
	}
}
