CONTAINER Fcylinder
{
	NAME Fcylinder;
	INCLUDE Ofield;

	GROUP ID_FIELDPROPERTIES
	{
		REAL FIELD_CYLINDER_HEIGHT { MIN 0.0; MAXSLIDER 500.0; CUSTOMGUI REALSLIDER; UNIT METER; }
		REAL FIELD_CYLINDER_RADIUS { MIN 0.0; MAXSLIDER 500.0; CUSTOMGUI REALSLIDER; UNIT METER; }
		LONG FIELD_CYLINDER_DIRECTION
		{
			CYCLE
			{
				FIELD_CYLINDER_DIRECTION_XP;
				FIELD_CYLINDER_DIRECTION_XN;
				FIELD_CYLINDER_DIRECTION_YP;
				FIELD_CYLINDER_DIRECTION_YN;
				FIELD_CYLINDER_DIRECTION_ZP;
				FIELD_CYLINDER_DIRECTION_ZN;
			}
		}
		BOOL FIELD_CYLINDER_CLIP { }
	}
}
