CONTAINER Fd3dexport
{
	NAME Fd3dexport;
	INCLUDE Fbase;

	GROUP D3DEXPORTFILTER_GROUP
	{
		DEFAULT 1;
		COLUMNS 2;
		UNITSCALE D3DEXPORTFILTER_SCALE	{ }
		STATICTEXT {}
  		BOOL D3DEXPORTFILTER_FORMAT { DEFAULT 1;}
		STATICTEXT {}
		BOOL D3DEXPORTFILTER_TEMPLATES {DEFAULT 1; }
		STATICTEXT {}
  		BOOL D3DEXPORTFILTER_TEXTURES {DEFAULT 1; }
  		STATICTEXT {}
  		BOOL D3DEXPORTFILTER_NORMALS {DEFAULT 1; }
  		STATICTEXT {}
  		BOOL D3DEXPORTFILTER_SAVEMESH {DEFAULT 1; }
  		STATICTEXT {}
		BOOL D3DEXPORTFILTER_CONVERTTEXTURENAME	{DEFAULT 1; }
		STATICTEXT {}
		STRING D3DEXPORTFILTER_TEXTURESUFFIX { }
		STATICTEXT {}
	}
}
