CONTAINER Fdxfimport
{
	NAME Fdxfimport;
	INCLUDE Fbase;

	GROUP DXFIMPORTFILTER_GROUP
	{
		DEFAULT 1;
		COLUMNS 2;
		
		UNITSCALE DXFIMPORTFILTER_SCALE	{ }
		STATICTEXT {}
		LONG DXFIMPORTFILTER_CIRCLESEGMENTS	{ MIN 12; MAX 500; DEFAULT 72;}
		STATICTEXT {}
		
		LONG DXFIMPORTFILTER_LAYER { CYCLE { DXFIMPORTFILTER_LAYER_NONE; DXFIMPORTFILTER_LAYER_BYLAYER; DXFIMPORTFILTER_LAYER_BYCOLOR; } DEFAULT DXFIMPORTFILTER_LAYER_BYCOLOR; }
		STATICTEXT {}
		BOOL DXFIMPORTFILTER_FROZEN	{ DEFAULT 0; }
		STATICTEXT {}
		
		BOOL DXFIMPORTFILTER_ELEMENTS2D	{DEFAULT 0;  }
		STATICTEXT {}
		
		BOOL DXFIMPORTFILTER_ALIGN { DEFAULT 1;}
		STATICTEXT {}
		
		BOOL DXFIMPORTFILTER_TRIANGULATE { DEFAULT 1;}
		STATICTEXT {}
	}
}
