CONTAINER Flinear
{
	NAME		Flinear;
	INCLUDE Ofield;

	GROUP ID_FIELDPROPERTIES
	{
		REAL LINEAR_SIZE { MINSLIDER 0.0; MIN 0.0; UNIT METER; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		LONG LINEAR_DIRECTION
		{
			CYCLE
			{
				LINEAR_DIRECTION_XP;
				LINEAR_DIRECTION_XN;
				LINEAR_DIRECTION_YP;
				LINEAR_DIRECTION_YN;
				LINEAR_DIRECTION_ZP;
				LINEAR_DIRECTION_ZN;
			}
		}
		BOOL LINEAR_CLIP {}
	}
}
