CONTAINER Fsphere
{
	NAME		Fsphere;
	INCLUDE Ofield;

	GROUP ID_FIELDPROPERTIES
	{
		REAL SPHERICAL_SIZE { MIN 0.0; UNIT METER; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		BOOL SPHERICAL_CLIP { }
	}
}
