CONTAINER Ftorus
{
	NAME		Ftorus;
	INCLUDE Ofield;

	GROUP ID_FIELDPROPERTIES
	{
		REAL FIELD_TORUS_RADIUS { MINSLIDER 0.0; MIN 0.0; UNIT METER; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		REAL FIELD_TORUS_THICKNESS { MINSLIDER 0.0; MIN 0.0; UNIT METER; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		LONG FIELD_TORUS_DIRECTION
		{
			CYCLE
			{
				FIELD_TORUS_DIRECTION_XP;
				FIELD_TORUS_DIRECTION_YP;
				FIELD_TORUS_DIRECTION_ZP;
			}
		}
		BOOL FIELD_TORUS_CLIP {}
	}
}
