CONTAINER Fvrml2import
{
	NAME Fvrml2import;
	INCLUDE Fbase;

	GROUP VRML2IMPORTFILTER_GROUP
	{
		COLUMNS 2;
		DEFAULT 1;
		
		UNITSCALE VRML2IMPORTFILTER_SCALE	{ }
		STATICTEXT {}
		
		BOOL VRML2IMPORTFILTER_OPTIMIZE	{ DEFAULT 1;}
		STATICTEXT {}
		
		BOOL VRML2IMPORTFILTER_OPTIMIZESTRUCTURE	{DEFAULT 1; }
		STATICTEXT {}
		
		BOOL VRML2IMPORTFILTER_USENORMALS { DEFAULT 1;	}
		STATICTEXT {}
	}
}
