CONTAINER Oatomarray
{
	NAME Oatomarray;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL ATOMARRAYOBJECT_CRAD { UNIT METER; MIN 0.01; STEP 0.01; }
		REAL ATOMARRAYOBJECT_SRAD { UNIT METER; MIN 0.01; STEP 0.01; }
		LONG ATOMARRAYOBJECT_SUB	{ MIN 3; MAX 1000; }
		BOOL ATOMARRAYOBJECT_SINGLE	{ }
	}
}
