CONTAINER Oattractor
{
	NAME Oattractor;
	INCLUDE Oparticlebase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL ATTRACTOROBJECT_STRENGTH { STEP 0.01; }
		REAL ATTRACTOROBJECT_SPEEDLIMIT { MIN 0.0; UNIT METER; }
		//VECTOR ATTRACTOROBJECT_SIZE { MIN 0.0; UNIT METER; }
		LONG PARTICLEBASE_MODE {CYCLE {PARTICLEBASE_MODE_ACCELERATION; PARTICLEBASE_MODE_FORCE;} }
	}
}
