CONTAINER Obaseeffector
{
	NAME		Obaseeffector;
	INCLUDE Obase;

	GROUP	ID_MG_BASEEFFECTOR_GROUPEFFECTOR
	{
		DEFAULT 1;

		REAL ID_MG_BASEEFFECTOR_STRENGTH
		{
			MINSLIDER 0.0;
			MAXSLIDER 100.0;
			UNIT			PERCENT;
			CUSTOMGUI REALSLIDER;
		}
		STRING ID_MG_BASEEFFECTOR_SELECTION
		{
		}
		GROUP ID_MG_BASEEFFECTOR_GROUPMINMAX
		{
			DEFAULT 0;
			REAL ID_MG_BASEEFFECTOR_MAXSTRENGTH
			{
				MINSLIDER -100.0;
				MAXSLIDER 100.0;
				UNIT			PERCENT;
				CUSTOMGUI REALSLIDER;
			}
			REAL ID_MG_BASEEFFECTOR_MINSTRENGTH
			{
				MINSLIDER -100.0;
				MAXSLIDER 100.0;
				UNIT			PERCENT;
				CUSTOMGUI REALSLIDER;
			}
		}
		SEPARATOR
		{
			LINE;
		}
	}
	GROUP ID_MG_BASEEFFECTOR_GROUPPARAMETER
	{
		GROUP ID_MG_BASEEFFECTOR_GROUPTRANSFORM
		{
			DEFAULT 1;

			GROUP
			{
				COLUMNS 2;

				LONG ID_MG_BASEEFFECTOR_TRANSFORMMODE
				{
					CYCLE
					{
						ID_MG_BASEEFFECTOR_TRANSFORMMODE_RELATIVE;
						ID_MG_BASEEFFECTOR_TRANSFORMMODE_ABSOLUTE;
						ID_MG_BASEEFFECTOR_TRANSFORMMODE_REMAP;
					}
				}
				LONG ID_MG_BASEEFFECTOR_SPACEMODE
				{
					CYCLE
					{
						ID_MG_BASEEFFECTOR_SPACEMODE_NODE;
						ID_MG_BASEEFFECTOR_SPACEMODE_EFFECTOR;
						ID_MG_BASEEFFECTOR_SPACEMODE_OBJECT;
					}
				}
			}
			GROUP
			{
				COLUMNS 3;
				LAYOUTGROUP;

				GROUP
				{
					BOOL	 ID_MG_BASEEFFECTOR_POSITION_ACTIVE { }
					VECTOR ID_MG_BASEEFFECTOR_POSITION
					{
						UNIT			METER;
						CUSTOMGUI SUBDESCRIPTION;
					}
				}
				GROUP
				{
					BOOL ID_MG_BASEEFFECTOR_SCALE_ACTIVE { }
					REAL ID_MG_BASEEFFECTOR_USCALE
					{
						STEP 0.01;
					}
					VECTOR ID_MG_BASEEFFECTOR_SCALE
					{
						STEP 0.01;
						CUSTOMGUI SUBDESCRIPTION;
					}
					BOOL ID_MG_BASEEFFECTOR_UNIFORMSCALE { }
					BOOL ID_MG_BASEEFFECTOR_POSITIVESCALE { }
				}
				GROUP
				{
					BOOL	 ID_MG_BASEEFFECTOR_ROTATE_ACTIVE { }
					VECTOR ID_MG_BASEEFFECTOR_ROTATION
					{
						UNIT			DEGREE;
						CUSTOMGUI SUBDESCRIPTION;
					}
				}
			}
		}
		GROUP ID_MG_BASEEFFECTOR_GROUPCOLOR
		{
			DEFAULT 1;

			GROUP
			{
				COLUMNS 2;
				LONG ID_MG_BASEEFFECTOR_COLOR_MODE
				{
					CYCLE
					{
						ID_MG_BASEEFFECTOR_COLOR_MODE_OFF;
						ID_MG_BASEEFFECTOR_COLOR_MODE_EFFECTOR;
						ID_MG_BASEEFFECTOR_COLOR_MODE_COLOR;
						ID_MG_BASEEFFECTOR_COLOR_MODE_FIELD;
					}
				}
				BOOL ID_MG_BASEEFFECTOR_COLOR_ALPHA { }
			}
			COLOR ID_MG_BASEEFFECTOR_COLOR
			{
				OPEN;
			}
			LONG ID_MG_BASEEFFECTOR_COLOR_BLEND
			{
				CYCLE
				{
					ID_MG_BASEEFFECTOR_COLOR_BLEND_DEFAULT;
					ID_MG_BASEEFFECTOR_COLOR_BLEND_ADD;
					ID_MG_BASEEFFECTOR_COLOR_BLEND_SUB;
					ID_MG_BASEEFFECTOR_COLOR_BLEND_MUL;
					ID_MG_BASEEFFECTOR_COLOR_BLEND_DIV;
				}
			}
		}
		GROUP ID_MG_BASEEFFECTOR_GROUPOTHER
		{
			COLUMNS 1;
			DEFAULT 1;

			BOOL ID_MG_BASEEFFECTOR_OTHERALPHA {}

			REAL ID_MG_BASEEFFECTOR_WEIGHT
			{
				MINSLIDER 0.0;
				MAXSLIDER 100.0;
				UNIT			PERCENT;
				CUSTOMGUI REALSLIDER;
			}
			REAL ID_MG_BASEEFFECTOR_U
			{
				MINSLIDER 0.0;
				MAXSLIDER 100.0;
				UNIT			PERCENT;
				CUSTOMGUI REALSLIDER;
			}
			REAL ID_MG_BASEEFFECTOR_V
			{
				MINSLIDER 0.0;
				MAXSLIDER 100.0;
				UNIT			PERCENT;
				CUSTOMGUI REALSLIDER;
			}
			REAL ID_MG_BASEEFFECTOR_CLONE
			{
				MINSLIDER 0.0;
				MAXSLIDER 100.0;
				UNIT			PERCENT;
				CUSTOMGUI REALSLIDER;
			}
			GROUP
			{
				COLUMNS 2;
				BASETIME ID_MG_BASEEFFECTOR_TIME { }
				BOOL		 ID_MG_BASEEFFECTOR_VISIBILITY { }
			}
		}
	}
	INCLUDE Oedeformer_panel;
}
