	CONTAINER Obasedeform
{
	NAME Obasedeform;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		COLUMNS 2;
		VECTOR DEFORMOBJECT_SIZE	{ HIDDEN; UNIT METER; MIN 0.0; }
		STATICTEXT { JOINEND; }
		LONG   DEFORMOBJECT_ALIGNMENT 	{ ANIM OFF; HIDDEN; CYCLE { DEFORMOBJECT_ALIGNMENT_AUTO; DEFORMOBJECT_ALIGNMENT_POSITIVE_X; DEFORMOBJECT_ALIGNMENT_NEGATIVE_X; DEFORMOBJECT_ALIGNMENT_POSITIVE_Y; DEFORMOBJECT_ALIGNMENT_NEGATIVE_Y; DEFORMOBJECT_ALIGNMENT_POSITIVE_Z; DEFORMOBJECT_ALIGNMENT_NEGATIVE_Z; } }
		BUTTON	DEFORMOBJECT_FITTOPARENT{ HIDDEN; }
		LONG   DEFORMOBJECT_MODE	{ HIDDEN; CYCLE { DEFORMOBJECT_MODE_LIMIT; DEFORMOBJECT_MODE_BOX; DEFORMOBJECT_MODE_UNLIMITED; } }
		STATICTEXT { JOINEND; }
		REAL   DEFORMOBJECT_STRENGTH 	{ HIDDEN; UNIT PERCENT; }
		STATICTEXT { JOINEND; }
		REAL   DEFORMOBJECT_ANGLE 	{ HIDDEN; UNIT DEGREE; CUSTOMGUI REALSLIDER; STEP 1; MINSLIDER 0; MAXSLIDER 360; DEFAULT 0; }
		STATICTEXT { JOINEND; }
		REAL   DEFORMOBJECT_CURVATURE 	{ HIDDEN; MIN 0.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; STEP 1; MINSLIDER 0; MAXSLIDER 100; DEFAULT 0; }
		STATICTEXT { JOINEND; }
		BOOL   DEFORMOBJECT_FILLET 	{ HIDDEN; }
		STATICTEXT { JOINEND; }
	}
}
