CONTAINER Obulge
{
	NAME Obulge;
	INCLUDE Obasedeform;

	SHOW DEFORMOBJECT_SIZE;
	SHOW DEFORMOBJECT_ALIGNMENT;
	SHOW DEFORMOBJECT_FITTOPARENT;
	SHOW DEFORMOBJECT_MODE;
	SHOW DEFORMOBJECT_CURVATURE;
	SHOW DEFORMOBJECT_STRENGTH;
	SHOW DEFORMOBJECT_FILLET;
	GROUP ID_OBJECTPROPERTIES
	{
		REAL BULGEOBJECT_STRENGTH	{ UNIT PERCENT; CUSTOMGUI REALSLIDER; STEP 1; MINSLIDER -100; MAXSLIDER 100; DEFAULT 0; }
	}
}
