CONTAINER Ocone
{
	NAME Ocone;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL PRIM_CONE_TRAD       { UNIT METER; MIN 0.0; }
		REAL PRIM_CONE_BRAD				{ UNIT METER; MIN 0.0; }
		REAL PRIM_CONE_HEIGHT			{ UNIT METER; MIN 0.0; }
		LONG PRIM_CONE_HSUB				{ MIN 1; MAX 1000; }
		LONG PRIM_CONE_SEG				{ MIN 3; MAX 1000; }

		INCLUDE Oprimitiveaxis;

		BUTTON PRIM_CONE_SWITCH_TO_UPDATED { } // To update legacy primitives to the new version
	}

	GROUP ID_CONECAPS
	{
		BOOL PRIM_CONE_CAPS {};

		LONG PRIM_CONE_CSUB				{ MIN 1; MAX 1000; }
		LONG PRIM_CONE_FSUB				{ MIN 1; MAX 1000; }

		GROUP
		{
			COLUMNS 2;

			BOOL PRIM_CONE_TOPFILLET {};
			BOOL PRIM_CONE_BOTFILLET {};

			REAL PRIM_CONE_TOPFILLET_RADIUS { PARENTID PRIM_CONE_TOPFILLET; UNIT METER; MIN 0.0; }
			REAL PRIM_CONE_BOTFILLET_RADIUS { PARENTID PRIM_CONE_BOTFILLET; UNIT METER; MIN 0.0; }

			REAL PRIM_CONE_TOPFILLET_HEIGHT { PARENTID PRIM_CONE_TOPFILLET; UNIT METER; MIN 0.0; }
			REAL PRIM_CONE_BOTFILLET_HEIGHT { PARENTID PRIM_CONE_BOTFILLET; UNIT METER; MIN 0.0; }
		}
	}
	INCLUDE Oprimitiveslice;
}
