CONTAINER Ocube
{
	NAME Ocube;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		GROUP
		{
			LAYOUTGROUP; COLUMNS 2;
			GROUP
			{
				VECTOR	PRIM_CUBE_LEN    { MIN 0 0 0; UNIT METER; CUSTOMGUI SUBDESCRIPTION; }
			}
			GROUP
			{
				LONG    PRIM_CUBE_SUBX   { MIN 1; MAX 1000; }
				LONG    PRIM_CUBE_SUBY   { MIN 1; MAX 1000; }
				LONG    PRIM_CUBE_SUBZ   { MIN 1; MAX 1000; }
			}
		}
		SEPARATOR { }
		BOOL		PRIM_CUBE_SEP    { }

		BOOL		PRIM_CUBE_DOFILLET { }
		REAL    PRIM_CUBE_FRAD	 { PARENTID PRIM_CUBE_DOFILLET; MIN 0; UNIT METER; }
		LONG    PRIM_CUBE_SUBF   { PARENTID PRIM_CUBE_DOFILLET; MIN 1; MAX 1000; }
	}
}
