CONTAINER Ocylinder
{
	NAME Ocylinder;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL PRIM_CYLINDER_RADIUS { UNIT METER; MIN 0.0; }
		REAL PRIM_CYLINDER_HEIGHT { UNIT METER; MIN 0.0; }
		LONG PRIM_CYLINDER_HSUB	  { MIN 1; MAX 1000; }
		LONG PRIM_CYLINDER_SEG	  { MIN 3; MAX 1000; }

		INCLUDE Oprimitiveaxis;

		BUTTON PRIM_CYLINDER_SWITCH_TO_UPDATED { } // To update legacy primitives to the new version
	}

	GROUP ID_CYLINDERCAPS
	{
		BOOL PRIM_CYLINDER_CAPS {}
		LONG PRIM_CYLINDER_CSUB { PARENTID PRIM_CYLINDER_FILLET; MIN 1; MAX 1000; }
		SEPARATOR { }
		BOOL PRIM_CYLINDER_FILLET {}
		LONG PRIM_CYLINDER_FSUB { PARENTID PRIM_CYLINDER_FILLET; MIN 1; MAX 1000; }
		REAL PRIM_CYLINDER_FILLETRADIUS { PARENTID PRIM_CYLINDER_FILLET; UNIT METER; MIN 0.0; }
	}

	INCLUDE Oprimitiveslice;
}
