CONTAINER Odestructor
{
	NAME Odestructor;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL DESTRUCTOROBJECT_RANDOM { UNIT PERCENT; MIN 0.0; MAX 100.0; }
		VECTOR DESTRUCTOROBJECT_SIZE { MIN 0.0; UNIT METER; }
	}
}
