CONTAINER Odisc
{
	NAME Odisc;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL PRIM_DISC_IRAD { UNIT METER; MIN 0.0; }
		REAL PRIM_DISC_ORAD { UNIT METER; MIN 0.0; }
		LONG PRIM_DISC_CSUB { MIN 1; MAX 1000; }
		LONG PRIM_DISC_SEG  { MIN 3; MAX 1000; }
	}
	INCLUDE Oprimitiveaxis;
	INCLUDE Oprimitiveslice;

	HIDE PRIM_REGULAR;
	HIDE PRIM_REGULARWIDTH;
}
