CONTAINER Oedeformer_panel
{
	NAME	Oedeformer_panel;

	GROUP ID_MG_EFFECTORDEFORMER_GROUP
	{
		LONG	ID_MG_EFFECTORDEFORMER_MODE
		{
			CYCLE
			{
				ID_MG_EFFECTORDEFORMER_MODE_OFF;
				ID_MG_EFFECTORDEFORMER_MODE_OBJECT;
				ID_MG_EFFECTORDEFORMER_MODE_POINT;
				ID_MG_EFFECTORDEFORMER_MODE_POLYGON;
			}
		}
	}
}
