CONTAINER Oenvironment
{
	NAME Oenvironment;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		COLOR ENVIRONMENT_AMBIENT {}
		REAL  ENVIRONMENT_AMBIENTSTRENGTH { UNIT PERCENT; MIN 0.0; MAX 100.0; }
		SEPARATOR { }
		BOOL  ENVIRONMENT_FOGENABLE {}
		COLOR ENVIRONMENT_FOG { PARENTID ENVIRONMENT_FOGENABLE; }
		REAL  ENVIRONMENT_FOGSTRENGTH { PARENTID ENVIRONMENT_FOGENABLE; UNIT PERCENT; MIN 0.0; MAX 100.0; }
		REAL  ENVIRONMENT_FOGDISTANCE { PARENTID ENVIRONMENT_FOGENABLE; MIN 0.0; UNIT METER; }
		BOOL  ENVIRONMENT_AFFECTBACKGROUND { PARENTID ENVIRONMENT_FOGENABLE; }
	}
}