CONTAINER Ofalloff_standard
{
	NAME	Ofalloff_standard;
	INCLUDE Ofalloff_panel;

	GROUP FALLOFF_GROUPFALLOFF
	{
		REAL	FALLOFF_STRENGTH
		{
			UNIT	PERCENT;
			MINSLIDER 0;
			MAXSLIDER 100;
			CUSTOMGUI REALSLIDER;
		}
		VECTOR	FALLOFF_SIZE { UNIT METER; }
		REAL	FALLOFF_SCALE
		{
			MINSLIDER 0.0;
			MAXSLIDER 100.0;
			UNIT			PERCENT;
			CUSTOMGUI REALSLIDER;
		}

		VECTOR FALLOFF_SHAPE_OFFSET { UNIT METER; }
		LONG FALLOFF_SHAPE_AXIS { CYCLE { FALLOFF_SHAPE_AXIS_XP; FALLOFF_SHAPE_AXIS_XN; FALLOFF_SHAPE_AXIS_YP; FALLOFF_SHAPE_AXIS_YN; FALLOFF_SHAPE_AXIS_ZP; FALLOFF_SHAPE_AXIS_ZN; } }

		REAL FALLOFF_SHAPE_SLICE { UNIT DEGREE; MIN 0.0; MAX 360.0; }
		REAL FALLOFF_SHAPE_TORUS_RADIUS { UNIT PERCENT; MIN 0.0; MAX 100.0; MINEX; }

		GROUP FALLOFF_SETTINGS
		{
		}
		SEPARATOR
		{
			LINE;
		}
		GROUP FALLOFF_GENERAL
		{
			GROUP
			{
				COLUMNS 2;
				BOOL FALLOFF_FUNCTION_SPHERICAL {}
				REAL FALLOFF_FUNCTION_RADIUS { UNIT METER; MIN 0.0; MINEX; }
			}

			REAL	FALLOFF_FALLOFF
			{
				MIN 0.0;
				MAX 100.0;
				UNIT			PERCENT;
				CUSTOMGUI REALSLIDER;
			}

			LONG FALLOFF_FUNCTION
			{
				CYCLE
				{
					FALLOFF_FUNCTION_LIN;
					FALLOFF_FUNCTION_SPLINE;
					FALLOFF_FUNCTION_INV;
					FALLOFF_FUNCTION_INVS;
					FALLOFF_FUNCTION_INVC;
					FALLOFF_FUNCTION_STEP;
				}
			}

			BOOL	FALLOFF_CLAMPED {}

			SPLINE	FALLOFF_SPLINE
			{
				SHOWGRID_H;
				SHOWGRID_V;
				EDIT_H;
				EDIT_V;
				X_MIN 0.0;
				X_MAX 1.0;
				Y_MIN 0.0;
				Y_MAX 1.0;
				X_STEPS 0.01;
				Y_STEPS 0.01;
			}
			REAL	FALLOFF_ANIM_SPEED
			{
				UNIT	PERCENT;
				MIN -100;
				MAX 100.0;
				CUSTOMGUI REALSLIDER;
			}
		}
	}
}
