CONTAINER Ofieldforce
{
	NAME Ofieldforce;
	INCLUDE Oparticlebase;

	GROUP ID_OBJECTPROPERTIES
	{
		LONG ID_FIELDFORCE_MODE 
		{
			CYCLE
			{
				ID_FIELDFORCE_MODE_ADD;
				ID_FIELDFORCE_MODE_ABSOLUTE;
				ID_FIELDFORCE_MODE_DIRECTION;
			}
		}
		REAL ID_FIELDFORCE_STRENGTH	 	{ STEP 1.0; }
		BOOL ID_FIELDFORCE_CONSIDER_MASS { NAME ID_FIELDFORCE_CONSIDER_MASS; }
		FIELDLIST ID_FIELDFORCE_FIELDLIST {	ANIM ON; NEWLINE; NOVALUE; NOCOLOR; NOROTATION; }

	}
	
	GROUP	ID_FIELDFORCE_DISPLAY_TAB
	{
		BOOL ID_FIELDFORCE_DISPLAY { NAME ID_FIELDFORCE_DISPLAY; }
		VECTOR ID_FIELDFORCE_BOX_SIZE	{ MIN 0.0; STEP 0.1; UNIT METER; }
		REAL ID_FIELDFORCE_DENSITY { CUSTOMGUI REALSLIDER; MIN 1.0; MAX 100.0; MAXSLIDER 100.0; STEP 1.0; UNIT PERCENT;}
		BOOL ID_FIELDFORCE_DISPLAY_LENGTH { NAME ID_FIELDFORCE_DISPLAY_LENGTH; PARENTCOLLAPSE; }
		LONG ID_FIELDFORCE_VECTOR_MODE
		{
			PARENTCOLLAPSE ID_FIELDFORCE_DISPLAY_LENGTH;
			CYCLE
			{
				ID_FIELDFORCE_VECTOR_MODE_LINES;
				ID_FIELDFORCE_VECTOR_MODE_COLOR;		
			}
			SCALE_H;
		}
		REAL ID_FIELDFORCE_SCALE_LENGTH_DISPLAY { PARENTCOLLAPSE ID_FIELDFORCE_DISPLAY_LENGTH; MIN 0.001; STEP 0.01; }
	}
}
