CONTAINER Ofigure
{
	NAME Ofigure;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL PRIM_FIGURE_HEIGHT { UNIT METER; MIN 0.0; }
		LONG PRIM_FIGURE_SUB    { MIN 4; MAX 1000; }
		BOOL PRIM_FIGURE_LEGACY_AXIS_MODE { ANIM OFF; }
		BUTTON PRIM_FIGURE_SWITCH_TO_UPDATED { } // To update legacy primitives to the new version
	}
}
