CONTAINER Oformula
{
	NAME Oformula;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		VECTOR FORMULAOBJECT_SIZE   { UNIT METER; MIN 0.0; }
		LONG   FORMULAOBJECT_EFFECT { CYCLE { FOEFFECT_MANUAL; FOEFFECT_SPHERICAL;FOEFFECT_CYLINDRICAL;FOEFFECT_XRADIAL;FOEFFECT_YRADIAL;FOEFFECT_ZRADIAL; } }
		STRING FORMULAOBJECT_DLT		{ }
		STRING FORMULAOBJECT_FX			{ }
		STRING FORMULAOBJECT_FY			{ }
		STRING FORMULAOBJECT_FZ			{ }
		SEPARATOR		{ LINE; }
		BUTTON	FORMULAOBJECT_FITTOPARENT	{  }
	}
}
