CONTAINER Ofractal
{
	NAME Ofractal;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		VECTOR  PRIM_FRACTAL_LEN 					{ MIN 0; UNIT METER; }
		LONG    PRIM_FRACTAL_SUBW 				{ MIN 4; MAX 1000; }
		LONG    PRIM_FRACTAL_SUBH 				{ MIN 4; MAX 1000; }
		REAL    PRIM_FRACTAL_ROUGH 				{ MIN 0; MAX 100; UNIT PERCENT; }
		REAL    PRIM_FRACTAL_FINE  				{ MIN 0; MAX 100; UNIT PERCENT; }
		REAL    PRIM_FRACTAL_SCALE 				{ MIN 0; MAX 10; STEP 0.01; }
		REAL    PRIM_FRACTAL_BLEVEL 			{ MIN 0; MAX 100; UNIT PERCENT; }
		REAL    PRIM_FRACTAL_TLEVEL 			{ MIN 0; MAX 100; UNIT PERCENT; }
		INCLUDE Oprimitiveaxis;
		BOOL    PRIM_FRACTAL_MULTIFRACTAL {	}
		LONG		PRIM_FRACTAL_SEED					{ }
		BOOL    PRIM_FRACTAL_BORDERS   		{ }
		BOOL    PRIM_FRACTAL_SPHERICAL 		{ }

		BUTTON PRIM_FRACTAL_SWITCH_TO_UPDATED { } // R21 - To update legacy primitives to the new elevation behavior.
	}
}
