CONTAINER Ofriction
{
	NAME Ofriction;
	INCLUDE Oparticlebase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL FRICTIONOBJECT_STRENGTH { STEP 0.01; }
		REAL FRICTIONOBJECT_ANGULAR_STRENGTH { STEP 0.01; }
		//VECTOR FRICTIONOBJECT_SIZE { UNIT METER; MIN 0.0; }
		LONG PARTICLEBASE_MODE {CYCLE {PARTICLEBASE_MODE_ACCELERATION; PARTICLEBASE_MODE_FORCE;} }
	}
}
