CONTAINER Ogravitation
{
	NAME Ogravitation;
	INCLUDE Oparticlebase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL GRAVITATIONOBJECT_STRENGTH	{ STEP 0.01; UNIT METER; }
		// VECTOR GRAVITATIONOBJECT_SIZE	{ UNIT METER; MIN 0.0; }
		LONG PARTICLEBASE_MODE {CYCLE {PARTICLEBASE_MODE_ACCELERATION; PARTICLEBASE_MODE_FORCE; PARTICLEBASE_MODE_AERODYNAMICS;} }
	}
}
