CONTAINER Oinstance
{
	NAME Oinstance;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		LINK INSTANCEOBJECT_LINK 
		{
			ACCEPT
			{
				Obase;
			}
		}
		LONG INSTANCEOBJECT_RENDERINSTANCE_MODE
		{
			CYCLE
			{
				INSTANCEOBJECT_RENDERINSTANCE_MODE_NONE;
				INSTANCEOBJECT_RENDERINSTANCE_MODE_SINGLEINSTANCE;
				INSTANCEOBJECT_RENDERINSTANCE_MODE_MULTIINSTANCE;
			}
		}
		
		LINK INSTANCEOBJECT_MULTIPOSITIONINPUT 
		{
			ACCEPT 
			{
				1018545;	// ID_MOTIONGENERATOR
				1001381;	// TP GROUP
				5109;			// Oparticle
				5156; 		// Opoint
				5100;			// Opolygon
			}
		}
		LONG INSTANCEOBJECT_DRAW_MODE
		{
			CYCLE
			{
				INSTANCEOBJECT_DRAW_MODE_NONE;
				INSTANCEOBJECT_DRAW_MODE_POINTS;
				INSTANCEOBJECT_DRAW_MODE_CUBE;
				INSTANCEOBJECT_DRAW_MODE_BBOX;
				INSTANCEOBJECT_DRAW_MODE_FULL;
			}
			ANIM ON;
		}
	}
}
