CONTAINER Olod
{
	NAME Olod;
	INCLUDE Obase;
	GROUP ID_OBJECTPROPERTIES
	{
		COLUMNS 2;
		LONG LOD_MODE
		{
			CYCLE
			{
				LOD_MODE_CHILD;
				LOD_MODE_MANUAL_GROUPS;
				LOD_MODE_SIMPLIFY;
			}
		}
		STATICTEXT { JOINENDSCALE; }

		LONG LOD_CRITERIA
		{
			CYCLE
			{
				LOD_CRITERIA_MANUAL;
				LOD_CRITERIA_MANUAL_SLIDER;
				LOD_CRITERIA_SCREEN_H;
				LOD_CRITERIA_SCREEN_V;
				LOD_CRITERIA_SCREEN_SURFACE;
				LOD_CRITERIA_CAMERA_DIST;
				LOD_CRITERIA_GLOBAL;
			}
		}
		STATICTEXT { JOINENDSCALE; }

		REAL LOD_CAMERA_MINDIST { UNIT METER; MIN 0; }
		REAL LOD_CAMERA_MAXDIST { UNIT METER; MIN 0; }

		LONG LOD_CURRENT_LEVEL
		{
			CYCLE
			{
			}
		}

		STATICTEXT { JOINENDSCALE; }
		LONG LOD_LEVEL_COUNT_DYN {	MIN 1; }
		STATICTEXT { JOINENDSCALE; }
		RANGE LOD_BAR {  }
		STATICTEXT { JOINENDSCALE; }
	}

	GROUP LOD_OPTIONS_GROUP
	{
		BOOL LOD_PROGRESIVE	{	}
		BOOL LOD_SHOW_UNASSIGNED { }
		SEPARATOR { LINE; }
		BOOL LOD_VIEWPORT_ONLY	{	}
		REAL LOD_RENDER_INCREMENT { UNIT PERCENT; MIN 0; MAX 100; }
		SEPARATOR { LINE; }
		BOOL LOD_CAMERA_CLIP {	}
		REAL LOD_CAMERA_CLIP_SAFEDISTANCE { UNIT METER; MIN 0; }
		REAL LOD_CAMERA_CLIP_SAFESPHERE { UNIT METER; MIN 0; }
		BOOL LOD_CAMERA_CLIP_AFFECTRENDER	{	}
		SEPARATOR { LINE; }
		BOOL LOD_POLYGONIZE {	}
	}
}
