CONTAINER Omelt
{
	NAME Omelt;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL MELTOBJECT_STRENGTH   { MIN 0.0; MAX 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; STEP 1; MINSLIDER 0; MAXSLIDER 100; DEFAULT 25; }
		REAL MELTOBJECT_RADIUS     { MIN 0.0; UNIT METER; }
		REAL MELTOBJECT_VERTRANDOM { MIN 0.0; MAX 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; STEP 1; MINSLIDER 0; MAXSLIDER 100; DEFAULT 100; }
		REAL MELTOBJECT_RADRANDOM  { MIN 0.0; MAX 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; STEP 1; MINSLIDER 0; MAXSLIDER 100; DEFAULT 100; }
		REAL MELTOBJECT_SIZE       { MIN 100.0; MAX 1000.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; STEP 1; MINSLIDER 100; MAXSLIDER 1000; DEFAULT 400; }
		REAL MELTOBJECT_NOISESCALE { MIN 0.1; MAX 10000.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; STEP 1; MINSLIDER 1; MAXSLIDER 100; DEFAULT 10; }
	}
}
