CONTAINER onoisefalloff
{
	NAME	onoisefalloff;
	INCLUDE Ofalloff_standard;

	HIDE FALLOFF_SIZE;
	HIDE FALLOFF_SCALE;
	
	GROUP FALLOFF_GROUPFALLOFF
	{
		GROUP FALLOFF_SETTINGS
		{
			SEPARATOR
			{
				LINE;
			}
			
			LONG ID_NOISEFALLOFF_NOISE_TYPE
			{
				CYCLE 
				{
						ID_NOISEFALLOFF_NOISE_TYPE_BOX;
						ID_NOISEFALLOFF_NOISE_TYPE_BLISTEREDTURBULENCE;
						ID_NOISEFALLOFF_NOISE_TYPE_BUYA;
						ID_NOISEFALLOFF_NOISE_TYPE_CELL;
						ID_NOISEFALLOFF_NOISE_TYPE_CRANAL;
						ID_NOISEFALLOFF_NOISE_TYPE_DENTS;
						ID_NOISEFALLOFF_NOISE_TYPE_DISPLACEDTURBULENCE;
						ID_NOISEFALLOFF_NOISE_TYPE_ELECTRIC;
						ID_NOISEFALLOFF_NOISE_TYPE_FBM;
						ID_NOISEFALLOFF_NOISE_TYPE_GASEOUS;
						ID_NOISEFALLOFF_NOISE_TYPE_HAMA;
						ID_NOISEFALLOFF_NOISE_TYPE_LUKA;
						ID_NOISEFALLOFF_NOISE_TYPE_MODNOISE;
						ID_NOISEFALLOFF_NOISE_TYPE_NAKI;
						ID_NOISEFALLOFF_NOISE_TYPE_NUTOUS;
						ID_NOISEFALLOFF_NOISE_TYPE_OBER;
						ID_NOISEFALLOFF_NOISE_TYPE_PEZO;
						ID_NOISEFALLOFF_NOISE_TYPE_POXO;
						ID_NOISEFALLOFF_NOISE_TYPE_SEMA;
						ID_NOISEFALLOFF_NOISE_TYPE_STUPL;
						ID_NOISEFALLOFF_NOISE_TYPE_TURBULENCE;
						ID_NOISEFALLOFF_NOISE_TYPE_VLNOISE;
						ID_NOISEFALLOFF_NOISE_TYPE_WAVYTURBULENCE;
						ID_NOISEFALLOFF_NOISE_TYPE_CELLVORONOI;
						ID_NOISEFALLOFF_NOISE_TYPE_DISPLACEDVORONOI;
						ID_NOISEFALLOFF_NOISE_TYPE_VORONOI1;
						ID_NOISEFALLOFF_NOISE_TYPE_VORONOI2;
						ID_NOISEFALLOFF_NOISE_TYPE_VORONOI3;
						ID_NOISEFALLOFF_NOISE_TYPE_ZADA;
						ID_NOISEFALLOFF_NOISE_TYPE_PERLIN;
						ID_NOISEFALLOFF_NOISE_TYPE_RIDGEDMULTIFRACTAL;
				}
				SCALE_H;
			}
			
			LONG ID_NOISEFALLOFF_NOISE_SEED { MIN 0;}
			REAL ID_NOISEFALLOFF_SCALE_GLOBAL {UNIT PERCENT; MIN 0.01; STEP 1.0;}
			VECTOR  ID_NOISEFALLOFF_SCALE_LOCAL 
			{
				UNIT PERCENT;
				MIN 0.01;
				STEP 1.0;
			}
			REAL ID_NOISEFALLOFF_NOISE_ANIMATIONSPEED {MIN 0.0; STEP 0.1;}
			REAL ID_NOISEFALLOFF_NOISE_LOW_CLIP { UNIT PERCENT; MIN 0.0; MAX 100.0; MAXSLIDER 100.0; STEP 1.0; CUSTOMGUI REALSLIDER;}
			REAL ID_NOISEFALLOFF_NOISE_HIGH_CLIP { UNIT PERCENT; MIN 0.0; MAX 100.0; MAXSLIDER 100.0; STEP 1.0; CUSTOMGUI REALSLIDER;}
			
			GROUP ID_NOISEFALLOFF_VIEWPLANES_GROUP
			{
				DEFAULT 1;
				GROUP
				{
					LAYOUTGROUP; COLUMNS 3;
					GROUP {BOOL ID_NOISEFALLOFF_VIEWPLANES_ACTIVEX {NAME ID_NOISEFALLOFF_VIEWPLANES_ACTIVEX;}}
					GROUP {BOOL ID_NOISEFALLOFF_VIEWPLANES_ACTIVEY {NAME ID_NOISEFALLOFF_VIEWPLANES_ACTIVEY;}}
					GROUP {BOOL ID_NOISEFALLOFF_VIEWPLANES_ACTIVEZ {NAME ID_NOISEFALLOFF_VIEWPLANES_ACTIVEZ;}}
				}
				VECTOR  ID_NOISEFALLOFF_VIEWPLANES 
				{
					UNIT METER;
					STEP 0.1;
				}
				LONG ID_NOISEFALLOFF_VIEWDENSITY{MIN 0; MAX 500; STEP 1; SCALE_H;}
			}
		}
	}
}
