CONTAINER Oplane
{
	NAME Oplane;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL PRIM_PLANE_WIDTH  { UNIT METER; MIN 0.0; }
		REAL PRIM_PLANE_HEIGHT { UNIT METER; MIN 0.0; }
		LONG PRIM_PLANE_SUBW   { MIN 1; MAX 1000; }
		LONG PRIM_PLANE_SUBH   { MIN 1; MAX 1000; }
	}
	INCLUDE Oprimitiveaxis;
}
