CONTAINER Opolyreduction
{
	NAME Opolyreduction;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL POLYREDUCTIONOBJECT_STRENGTH 	{ MIN 0.0; MAX 100.0; UNIT PERCENT; }
		LONG POLYREDUCTIONOBJECT_MESHFACTOR { MIN 0; MAX 20000; }
		BOOL POLYREDUCTIONOBJECT_COPLANAR	  { }
		BOOL POLYREDUCTIONOBJECT_BOUNDARY  	{ }
		BOOL POLYREDUCTIONOBJECT_QUALITY   	{ }
	}
}
