CONTAINER Oprimitiveslice
{
	INCLUDE Obase;
	GROUP ID_SLICE
	{
		BOOL PRIM_SLICE        { }
		REAL PRIM_SLICEFROM    { PARENTID PRIM_SLICE; UNIT DEGREE; }
		REAL PRIM_SLICETO      { PARENTID PRIM_SLICE; UNIT DEGREE; }
		SEPARATOR { }
		BOOL PRIM_REGULAR      { }
		REAL PRIM_REGULARWIDTH { PARENTID PRIM_REGULAR; MIN 0.01; STEP 0.1; UNIT METER; }
	}
}
