CONTAINER Oremesh
{
	NAME Oremesh;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		LONG ID_REMESH_POLYGONTYPE
		{
			CYCLE
			{
				ID_REMESH_POLYGONTYPE_QUADRANGLES;
				ID_REMESH_POLYGONTYPE_TRIANGLES;
			}
		}

		LONG ID_REMESH_POLYGONTARGET_MODE
		{
			CYCLE
			{
				ID_REMESH_POLYGONTARGET_MODE_ABSOLUTE;
				ID_REMESH_POLYGONTARGET_MODE_MESHDENSITY;
			}
		}
		REAL ID_REMESH_POLYGONSCALE { UNIT PERCENT; MIN 1; MINSLIDER 1; MAX 10000.0; MAXSLIDER 500.0; STEP 1; CUSTOMGUI REALSLIDER;}
		LONG ID_REMESH_POLYGONTARGET { MIN 1; MAX 5000000; }

		BOOL ID_REMESH_KEEPOUTLINE { }
		BOOL ID_REMESH_CREASES { }
		REAL ID_REMESH_EDGEANGLE { UNIT DEGREE; MIN 0.0; MINSLIDER 0.0; MAX 180; MAXSLIDER 180; CUSTOMGUI REALSLIDER; }
		LONG ID_REMESH_SMOOTHITERATIONS { MIN 0; MAX 100; }
		BOOL ID_REMESH_QUADONLY {}
		IN_EXCLUDE ID_REMESH_GUIDE_SPLINES
		{
			NUM_FLAGS 1;
			INIT_STATE 1;
			IMAGE_01_ON 300000131;
			IMAGE_01_OFF 300000130;
			ACCEPT 
			{
				Ospline;
			}
		}
	}
}
