CONTAINER Oselection
{
	NAME Oselection;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		SCALE_V;
		BUTTON SELECTIONOBJECT_RESTORE { }
 	  IN_EXCLUDE SELECTIONOBJECT_LIST { SCALE_V; NUM_FLAGS 1; INIT_STATE 0; IMAGE_01_ON 1009316; IMAGE_01_OFF 1009320; ACCEPT { Obase; Mbase; Tbase; } }
	}
}