CONTAINER Osplinestar
{
	NAME Osplinestar;
	INCLUDE Obase;
	
	GROUP ID_OBJECTPROPERTIES
	{
		REAL PRIM_STAR_IRAD { UNIT METER; MIN 0.0; }
		REAL PRIM_STAR_ORAD	{ UNIT METER; MIN 0.0; }
		REAL PRIM_STAR_TWIST { UNIT PERCENT; MIN -100; MAX 100; }
		LONG PRIM_STAR_POINTS { MIN 3; MAX 1000000; }
	}
	INCLUDE Osplineprimitive;
}
