CONTAINER Osplineprofile
{
	NAME Osplineprofile;
	INCLUDE Obase;
	
	GROUP ID_OBJECTPROPERTIES
	{
		LONG PRIM_PROFILE_TYPE
		{
			CYCLE
			{
				PRIM_PROFILE_TYPE_H;
				PRIM_PROFILE_TYPE_L;
				PRIM_PROFILE_TYPE_T;
				PRIM_PROFILE_TYPE_U;
				PRIM_PROFILE_TYPE_Z;
			}
		}
		REAL PRIM_PROFILE_A { UNIT METER; MIN 0.0; }
		REAL PRIM_PROFILE_B { UNIT METER; MIN 0.0; }
		REAL PRIM_PROFILE_S { UNIT METER; MIN 0.0; }
		REAL PRIM_PROFILE_T { UNIT METER; MIN 0.0; }
	}
	INCLUDE Osplineprimitive;
}
