CONTAINER Osplinecycloid
{
	NAME Osplinecycloid;
	INCLUDE Obase;
	
	GROUP ID_OBJECTPROPERTIES
	{
		LONG PRIM_CYCLOID_TYPE
		{
			CYCLE
			{
				PRIM_CYCLOID_TYPE_CYCLOID;
				PRIM_CYCLOID_TYPE_EPICYCLOID;
				PRIM_CYCLOID_TYPE_HYPOCYCLOID;
			}
		}
		REAL PRIM_CYCLOID_RADIUS { UNIT METER; MIN 0.0; }
		REAL PRIM_CYCLOID_R			 { UNIT METER; MIN 0.0; }
		REAL PRIM_CYCLOID_A      { UNIT METER; MIN 0.0; }
		REAL PRIM_CYCLOID_START	 { UNIT DEGREE; }
		REAL PRIM_CYCLOID_END		 { UNIT DEGREE; }
	}
	INCLUDE Osplineprimitive;
}
