CONTAINER Osplinecissoid
{
	NAME Osplinecissoid;
	INCLUDE Obase;
	
	GROUP ID_OBJECTPROPERTIES
	{
		LONG PRIM_CISSOID_TYPE { CYCLE { PRIM_CISSOID_TYPE_CISSOID; PRIM_CISSOID_TYPE_LEMNISCATE; PRIM_CISSOID_TYPE_STROPHOID; } }
		REAL PRIM_CISSOID_WIDTH { UNIT METER; MIN 0.0; }
		REAL PRIM_CISSOID_TENSION { MIN 1.5; MAX 100; }
		//LONG PRIM_CISSOID_SUB { MIN 3; }
	}
	INCLUDE Osplineprimitive;
}
