CONTAINER Osplinearc
{
	NAME Osplinearc;
	INCLUDE Obase;
	
	GROUP ID_OBJECTPROPERTIES
	{
		LONG PRIM_ARC_TYPE
		{
			CYCLE
			{
				PRIM_ARC_TYPE_ARC;
				PRIM_ARC_TYPE_SECTOR;
				PRIM_ARC_TYPE_SEGMENT;
				PRIM_ARC_TYPE_RING;
			}
		}
		REAL PRIM_ARC_RADIUS { UNIT METER; MIN 0.0; }
		REAL PRIM_ARC_INNER	 { UNIT METER; MIN 0.0; }
		REAL PRIM_ARC_START	 { UNIT DEGREE; MIN -360.0; MAX 360.0; }
		REAL PRIM_ARC_END    { UNIT DEGREE; MIN -360.0; MAX 360.0; }
	}
	INCLUDE Osplineprimitive;
}
