CONTAINER Osplinetext
{
	NAME Osplinetext;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		GROUP
		{
			STRING PRIM_TEXT_TEXT		{ CUSTOMGUI MULTISTRING; }
		}
		SEPARATOR { LINE; }
		FONT PRIM_TEXT_FONT		{ OPEN; }
		LONG PRIM_TEXT_ALIGN { CYCLE { PRIM_TEXT_ALIGN_LEFT;PRIM_TEXT_ALIGN_MIDDLE;PRIM_TEXT_ALIGN_RIGHT;}}
		REAL PRIM_TEXT_HEIGHT		{ UNIT METER; }
		REAL PRIM_TEXT_HSPACING { UNIT METER; }
		REAL PRIM_TEXT_VSPACING { UNIT METER; }
		BOOL PRIM_TEXT_SEPARATE	{ }
		SEPARATOR { LINE; }
		KERNING PRIM_TEXT_KERNING	{  }
		SEPARATOR { LINE; }
	}
	
	INCLUDE Osplineprimitive;
}
