CONTAINER Osplineformula
{
	NAME Osplineformula;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		STRING PRIM_FORMULA_X			{ }
		STRING PRIM_FORMULA_Y			{ }
		STRING PRIM_FORMULA_Z			{ }

		REAL PRIM_FORMULA_TMIN		{ }
		REAL PRIM_FORMULA_TMAX		{ }
		LONG PRIM_FORMULA_SAMPLES	{ MIN 2; }
		BOOL PRIM_FORMULA_CUBIC		{}
	}
	INCLUDE Osplineprimitive;
}
