CONTAINER Osplinehelix
{
	NAME Osplinehelix;
	INCLUDE Obase;
	
	GROUP ID_OBJECTPROPERTIES
	{
		REAL PRIM_HELIX_RADIUS1 { MIN 0.0; UNIT METER; }
		REAL PRIM_HELIX_START { UNIT DEGREE; }
		REAL PRIM_HELIX_RADIUS2 { MIN 0.0;UNIT METER; }
		REAL PRIM_HELIX_END   { UNIT DEGREE; }
		REAL PRIM_HELIX_RADIALBIAS { UNIT PERCENT; MIN 0.0; MAX 100.0; }
		REAL PRIM_HELIX_HEIGHT { UNIT METER; MIN 0.0; }
		REAL PRIM_HELIX_HEIGHTBIAS{ UNIT PERCENT; MIN 0.0; MAX 100.0; }
		LONG PRIM_HELIX_SUB { MIN 3; }
	}
	INCLUDE Osplineprimitive;
}
