CONTAINER Osplinecontour
{
	NAME Osplinecontour;
	INCLUDE Obase;
	
	GROUP ID_OBJECTPROPERTIES
	{
		TEXTURE PRIM_CONTOUR_TEXTURE { }
		REAL PRIM_CONTOUR_WIDTH { UNIT METER; MIN 0.0; }
		REAL PRIM_CONTOUR_TOLERANCE { UNIT METER; MIN 0.0; } 
	}
	INCLUDE Osplineprimitive;
}
