CONTAINER Osplinenside
{
	NAME Osplinenside;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL PRIM_NSIDE_RADIUS { UNIT METER; MIN 0.0; }
		LONG PRIM_NSIDE_SIDES  { MIN 2; }
		BOOL PRIM_NSIDE_ROUNDING {}
		REAL PRIM_NSIDE_RRADIUS { PARENTID PRIM_NSIDE_ROUNDING; UNIT METER; MIN 0.0; }
	}
	INCLUDE Osplineprimitive;
}
