CONTAINER Osplinerectangle
{
	NAME Osplinerectangle;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL PRIM_RECTANGLE_WIDTH { UNIT METER; MIN 0.0; }
		REAL PRIM_RECTANGLE_HEIGHT { UNIT METER; MIN 0.0; }
		BOOL PRIM_RECTANGLE_ROUNDING {}
		REAL PRIM_RECTANGLE_RADIUS { PARENTID PRIM_RECTANGLE_ROUNDING; UNIT METER; MIN 0.0; }
	}
	INCLUDE Osplineprimitive;
}
