CONTAINER Ospline4side
{
	NAME Ospline4side;
	INCLUDE Obase;
	
	GROUP ID_OBJECTPROPERTIES
	{
		LONG PRIM_4SIDE_TYPE { CYCLE { PRIM_4SIDE_TYPE_DIAMOND;PRIM_4SIDE_TYPE_KITE;PRIM_4SIDE_TYPE_PARALLELOGRAM;PRIM_4SIDE_TYPE_TRAPEZIUM; } }
		REAL PRIM_4SIDE_A { UNIT METER; MIN 0.0; }
		REAL PRIM_4SIDE_B { UNIT METER; MIN 0.0; }
		REAL PRIM_4SIDE_ANGLE { UNIT DEGREE; MIN -90; MAX 90; }
	}
	INCLUDE Osplineprimitive;
}
