CONTAINER Otaper
{
	NAME Otaper;
	INCLUDE Obasedeform;

	SHOW DEFORMOBJECT_SIZE;
	SHOW DEFORMOBJECT_ALIGNMENT;
	SHOW DEFORMOBJECT_FITTOPARENT;
	SHOW DEFORMOBJECT_MODE;
	SHOW DEFORMOBJECT_STRENGTH;
	SHOW DEFORMOBJECT_CURVATURE;
	SHOW DEFORMOBJECT_FILLET;
	GROUP ID_OBJECTPROPERTIES
	{
		REAL TAPEROBJECT_STRENGTH 	{ UNIT PERCENT; CUSTOMGUI REALSLIDER; STEP 1; MINSLIDER -100; MAXSLIDER 100; DEFAULT 0; }
		REAL TAPEROBJECT_CURVATURE	{ UNIT PERCENT; CUSTOMGUI REALSLIDER; STEP 1; MINSLIDER 0; MAXSLIDER 300; DEFAULT 100; }
	}
}
