CONTAINER Oturbulence
{
	NAME Oturbulence;
	INCLUDE Oparticlebase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL TURBULENCEOBJECT_STRENGTH { STEP 0.01; MIN 0.0; UNIT METER; }
		//VECTOR TURBULENCEOBJECT_SIZE { UNIT METER; MIN 0.0;}
		REAL TURBULENCEOBJECT_SCALE { MIN 0.0; STEP 0.01; MAXSLIDER 1000.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
		REAL TURBULENCEOBJECT_FREQUENCY { MINSLIDER 0.0; STEP 0.01; MAXSLIDER 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
		LONG PARTICLEBASE_MODE {CYCLE {PARTICLEBASE_MODE_ACCELERATION; PARTICLEBASE_MODE_FORCE; PARTICLEBASE_MODE_AERODYNAMICS;} }
	}
}
