CONTAINER Owind
{
	NAME Owind;
	INCLUDE Oparticlebase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL WINDOBJECT_STRENGTH { MIN 0.0; STEP 0.01; UNIT METER; }
		//VECTOR WINDOBJECT_SIZE { MIN 0.0; UNIT METER; }
		REAL WINDOBJECT_TURBULENCE { MINSLIDER 0.0; MAXSLIDER 100.0; STEP 0.01; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
		REAL WINDOBJECT_TURBULENCE_SCALE { MIN 0.0; STEP 0.01; MAXSLIDER 1000.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
		REAL WINDOBJECT_TURBULENCE_FREQUENCY { MINSLIDER 0.0; STEP 0.01; MAXSLIDER 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
		LONG PARTICLEBASE_MODE {CYCLE {PARTICLEBASE_MODE_ACCELERATION; PARTICLEBASE_MODE_FORCE; PARTICLEBASE_MODE_AERODYNAMICS;} }
	}
}
