CONTAINER Owinddeform
{
	NAME Owinddeform;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL WINDDEFORMOBJECT_AMPLITUDE  { UNIT METER; MIN 0.0; }
		REAL WINDDEFORMOBJECT_SIZE       { UNIT METER; MIN 0.0; }
		REAL WINDDEFORMOBJECT_FREQUENCY	 { MIN 0.0; STEP 0.01; CUSTOMGUI REALSLIDER; STEP 0.01; MINSLIDER 0; MAXSLIDER 10; DEFAULT 1; }
		REAL WINDDEFORMOBJECT_TURBULENCE { MIN 0.0; MAX 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; STEP 1; MINSLIDER 0; MAXSLIDER 100; DEFAULT 50; }
		REAL WINDDEFORMOBJECT_FX         { MIN 0.0; STEP 0.01; CUSTOMGUI REALSLIDER; STEP 0.01; MINSLIDER 0; MAXSLIDER 5; DEFAULT 1; }
		REAL WINDDEFORMOBJECT_FY	 { MIN 0.0; STEP 0.01; CUSTOMGUI REALSLIDER; STEP 0.01; MINSLIDER 0; MAXSLIDER 5; DEFAULT 1; }
		BOOL WINDDEFORMOBJECT_FLAG			 {}
	}
}
