CONTAINER Taligntospline
{
	NAME Taligntospline;
	INCLUDE Texpression;

	GROUP ID_TAGPROPERTIES
	{
		LINK 	ALIGNTOSPLINETAG_LINK	{ ACCEPT { Obase; } }
		LINK 	ALIGNTOSPLINETAG_RAIL	{ ACCEPT { Obase; } }
		BOOL	ALIGNTOSPLINETAG_TANGENTIAL { }
		
		REAL  ALIGNTOSPLINETAG_POSITION { UNIT PERCENT; CUSTOMGUI REALSLIDER; MINSLIDER 0.0;  MAXSLIDER 100.0; }
		LONG  ALIGNTOSPLINETAG_SEGMENT { MIN 0; }
		LONG	ALIGNTOSPLINETAG_AXIS	{ CYCLE { ALIGNTOSPLINETAG_AXIS_X; ALIGNTOSPLINETAG_AXIS_Y; ALIGNTOSPLINETAG_AXIS_Z; } }
	}
}
