CONTAINER Tannotation
{
  NAME Tannotation;
  INCLUDE Tbase;

  GROUP ANNOTATIONTAG_GROUPSETTINGS
  {
		DEFAULT 1; SCALE_V;
    STRING ANNOTATIONTAG_TEXT						{ ANIM OFF; CUSTOMGUI MULTISTRING; SCALE_V; }
    STRING ANNOTATIONTAG_URL						{ ANIM OFF; }
    STRING ANNOTATIONTAG_URL_INFO				{ ANIM OFF; }
		BUTTON ANNOTATIONTAG_URL_GO					{ }
  }

  GROUP ANNOTATIONTAG_GROUPDISPLAY
  {
		DEFAULT 1;
    GROUP
    {
      COLOR ANNOTATIONTAG_COLOR					{ ANIM OFF; }
		}

    GROUP
    {
      COLUMNS 2;
			BOOL ANNOTATIONTAG_COLORFROMLAYER	{ ANIM OFF; } STATICTEXT { JOINEND; }
			SEPARATOR													{ LINE; }    STATICTEXT { JOINENDSCALE; }
      BOOL ANNOTATIONTAG_VIEWPORT_SHOW	{ ANIM OFF; }
      BOOL ANNOTATIONTAG_VIEWPORT_ALL		{ ANIM OFF; }
			BOOL ANNOTATIONTAG_SCALEFLAG			{ ANIM OFF; }
      BOOL ANNOTATIONTAG_FOLD						{ ANIM OFF; }
      BOOL ANNOTATIONTAG_EXPORT					{ ANIM OFF; }
    }
    
    SEPARATOR														{ LINE; }
    
    GROUP
    {
      COLUMNS 3;
      BUTTON ANNOTATIONTAG_SHOW_ALL			{ }
      BUTTON ANNOTATIONTAG_HIDE_ALL			{ }
      BUTTON ANNOTATIONTAG_HIDE_OTHERS	{ }
    }
  }
}
