CONTAINER Tsunexpression
{
	NAME Tsunexpression;
	INCLUDE Texpression;

	GROUP ID_TAGPROPERTIES
	{
		DATETIME SUNEXPRESSIONTAG_DATETIME { NOW_BUTTON; ANIM MIX; }
		BOOL SUNEXPRESSIONTAG_INTERPOLATE_TIME { ANIM OFF; }
		BOOL SUNEXPRESSIONTAG_INTERPOLATE_DATE { ANIM OFF; }
		
		REAL SUNEXPRESSIONTAG_LATITUDE { UNIT DEGREE; CUSTOMGUI LONG_LAT; MIN -90; MAX 90; }
		REAL SUNEXPRESSIONTAG_LONGITUDE { UNIT DEGREE; CUSTOMGUI LONG_LAT; MIN -180; MAX 180; LONGITUDE; }
		REAL SUNEXPRESSIONTAG_DISTANCE { UNIT METER; MIN 0.0; }
		
		BOOL SUNEXPRESSIONTAG_SETLIGHTCOLOR	{ }
	}
}
