CONTAINER Tvibrate
{
	NAME Tvibrate;
	INCLUDE Texpression;

	GROUP ID_TAGPROPERTIES
	{
		BOOL		VIBRATEEXPRESSION_REGULAR { }
		BOOL		VIBRATEEXPRESSION_RELATIVE { }
		REAL		VIBRATEEXPRESSION_SEED { }
		SEPARATOR { LINE; }

		BOOL 		VIBRATEEXPRESSION_POS_ENABLE { }
		VECTOR 	VIBRATEEXPRESSION_POS_AMPLITUDE { PARENTID VIBRATEEXPRESSION_POS_ENABLE; UNIT METER; }
		REAL 		VIBRATEEXPRESSION_POS_FREQUENCY { PARENTID VIBRATEEXPRESSION_POS_ENABLE; MIN 0.0; STEP 0.01; }
		SEPARATOR { LINE; }

		BOOL 		VIBRATEEXPRESSION_SCL_ENABLE { }
		BOOL		VIBRATEEXPRESSION_SCL_UNIFORM { PARENTID VIBRATEEXPRESSION_SCL_ENABLE; }
		VECTOR 	VIBRATEEXPRESSION_SCL_AMPLITUDE { PARENTID VIBRATEEXPRESSION_SCL_ENABLE; MIN 0.01; STEP 0.01; }
		REAL 		VIBRATEEXPRESSION_SCL_FREQUENCY { PARENTID VIBRATEEXPRESSION_SCL_ENABLE; MIN 0.0; STEP 0.01; }
		SEPARATOR { LINE; }

		BOOL 		VIBRATEEXPRESSION_ROT_ENABLE { }
		VECTOR 	VIBRATEEXPRESSION_ROT_AMPLITUDE { PARENTID VIBRATEEXPRESSION_ROT_ENABLE; UNIT DEGREE; }
		REAL 		VIBRATEEXPRESSION_ROT_FREQUENCY { PARENTID VIBRATEEXPRESSION_ROT_ENABLE; MIN 0.0; STEP 0.01; }
	}
}
