// C4D-DialogResource
DIALOG IDC_REMESH_DIALOG
{
  NAME	DialogRemesher;

 	GROUP
	{
		COLUMNS 1;
		BORDERSIZE 8,8,8,8;
		SCALE_H;
		GROUP
		{
			COLUMNS 2;
			SCALE_H;
			STATICTEXT { ALIGN_LEFT; NAME IDS_REMESH_POLYGONTARGET; }
			EDITNUMBERARROWS IDC_REMESH_POLYGONTARGET	{ ALIGN_LEFT; SIZE 70, 0; }
		}
		CHECKBOX IDC_REMESH_KEEPOUTLINE { NAME IDS_REMESH_KEEPOUTLINE;}
	}

  DLGGROUP { OK; CANCEL; }
}