// C4D-DialogResource
DIALOG IDD_MODELING_UVUNWRAP
{
  NAME T1; CENTER_V; CENTER_H;

  CHECKBOX IDC_UVUNWRAP_POLYGON { NAME T2; }
  CHECKBOX IDC_UVUNWRAP_PIN { NAME T3; }
  CHECKBOX IDC_UVUNWRAP_REALIGN { NAME T4; }

  STATICTEXT  { CENTER_V; FIT_H; }
  DLGGROUP { OK; CANCEL; HELP; }
}