// C4D-DialogResource
DIALOG IDD_MODELING_UVWELDRELAX
{
  NAME T1; CENTER_V; CENTER_H;

  CHECKBOX IDC_UVWELDRELAX_POLYGON { NAME T4; }
  CHECKBOX IDC_UVWELDRELAX_PIN { NAME T2; }
  CHECKBOX IDC_UVWELDRELAX_REALIGN { NAME T3; }

  STATICTEXT  { CENTER_V; FIT_H; }
  DLGGROUP { OK; CANCEL; HELP; }
}