CONTAINER CacheTool
{
	NAME CacheTool;
	INCLUDE ToolBase;

	HIDE MDATA_COMMANDGROUP;

	GROUP MDATA_MAINGROUP
	{
		GROUP
		{
			COLUMNS 2;

			LONG CACHE_TOOL_MODE
			{
				ALIGN_LEFT;
				CYCLE
				{
					CACHE_TOOL_MODE_SMEAR;
					CACHE_TOOL_MODE_SMOOTH;
				}
			}

			LONG CACHE_TOOL_SHOW_RADIUS  { MIN 1; }

			LONG CACHE_TOOL_FALLOFF_RADIUS  { MIN 0; }
			REAL CACHE_TOOL_FALLOFF_STRENGTH  { UNIT PERCENT; }

			LONG CACHE_TOOL_FALLOFF_MODE
			{
				ALIGN_LEFT;
				CYCLE
				{
					CACHE_TOOL_MODE_CONSTANT;
					CACHE_TOOL_MODE_LINEAR;
					CACHE_TOOL_MODE_DOME;
					CACHE_TOOL_MODE_BELL;
					CACHE_TOOL_MODE_CIRCLE;
					CACHE_TOOL_MODE_NEEDLE;
					CACHE_TOOL_MODE_USER;
				}
			}

			REAL CACHE_TOOL_FALLOFF_WIDTH  { UNIT PERCENT;  MIN 0.0; }
		}

		GROUP
		{
			SPLINE CACHE_TOOL_FALLOFF
			{
				SHOWGRID_H;
				SHOWGRID_V;

				MINSIZE_H 120;
				MINSIZE_V 90;

				EDIT_H;
				EDIT_V;
			}
		}
	}
}
