CONTAINER ClothTag
{
	NAME Tsbd;
	INCLUDE Tbase;

	GROUP Obaselist
	{
	  PRIORITY CLOTH_SIMULATION_PRIORITY { ANIM OFF; NOCAMERA; }
	  BOOL CLOTH_USE { ANIM OFF; }
	}

	GROUP ID_TAGPROPERTIES
	{

		GROUP
		{
			COLUMNS 3;

			BOOL CLOTH_AUTOTIME { ANIM OFF; }

			BASETIME CLOTH_START { ANIM OFF; }
			BASETIME CLOTH_STOP  { ANIM OFF; }
		}

		SEPARATOR { LINE; }

		GROUP
		{
			COLUMNS 2;

			LONG CLOTH_ITERATIONS {MIN 1; } STATICTEXT { JOINENDSCALE; }

			REAL CLOTH_STRUCT_F   {UNIT PERCENT; MIN 0.0; MAX 100.0; } LINK CLOTH_STRUCT_F_MAP  { ACCEPT { 5682; } }
			REAL CLOTH_FLEXION_F  {UNIT PERCENT; MIN 0.0; MAX 100.0; }   LINK CLOTH_FLEXION_F_MAP { ACCEPT { 5682; } }
			REAL CLOTH_RUBBER_F   {UNIT PERCENT; MIN 0.0; MAX 100.0; }   LINK CLOTH_RUBBER_F_MAP  { ACCEPT { 5682; } }

			SEPARATOR { LINE; } STATICTEXT { JOINENDSCALE; }

			REAL CLOTH_BOUNCE { UNIT PERCENT; MIN 0.0; }            LINK CLOTH_BOUNCE_MAP    { ACCEPT { 5682; } }
			REAL CLOTH_STICKI { UNIT PERCENT; MIN 0.0; MAX 100.0; } LINK CLOTH_STICKI_MAP    { ACCEPT { 5682; } }

			SEPARATOR { LINE; } STATICTEXT { JOINENDSCALE; }

			REAL CLOTH_MASS      { MIN 0.1; STEP 0.1; }    LINK CLOTH_MASS_MAP     { ACCEPT { 5682; } }
			REAL CLOTH_SHRINK_F  {UNIT PERCENT; MIN 1.0; } LINK CLOTH_SHRINK_F_MAP { ACCEPT { 5682; } }
			REAL CLOTH_TEAR_F    {UNIT PERCENT; MIN 1.0; } LINK CLOTH_TEAR_F_MAP   { ACCEPT { 5682; } }
			BOOL CLOTH_TEAR      { } STATICTEXT { JOINENDSCALE; }
		}



		DEFAULT 1;
	}


	GROUP CLOTH_GROUP_FORCES
	{
		REAL CLOTH_GRAVITY { STEP 0.1; }
		REAL CLOTH_DRAG      { UNIT PERCENT; MIN 0.0; MAX 100.0; }

		SEPARATOR { LINE; }

		VECTOR CLOTH_WIND_DIR     { UNIT METER; CUSTOMGUI SUBDESCRIPTION; STEP 0.1; }
		REAL   CLOTH_WIND_F       { MIN 0.0; STEP 0.1; }
		REAL   CLOTH_WIND_TURB_F  { MIN 0.0; }
		REAL   CLOTH_WIND_TURB_S  { MIN 0.0; }
		REAL   CLOTH_WIND_DRAG    {UNIT PERCENT; MIN 0.0; MAX 100.0; }
		REAL   CLOTH_WIND_IMPACT  {UNIT PERCENT; MIN 0.0; MAX 100.0; }
		REAL   CLOTH_WIND_LIFT    {UNIT PERCENT; MIN 0.0; MAX 100.0; }
		REAL   CLOTH_WIND_SPEED   { STEP 0.1; }

		SEPARATOR { LINE; }

		BOOL CLOTH_SREP { }

		REAL CLOTH_SREP_D { UNIT METER;MIN 0.0; }
		REAL CLOTH_SREP_F { MIN 0.0; }
		REAL CLOTH_SREP_B {  }



		DEFAULT 0;

	}


	GROUP CLOTH_GROUP_DRESSING
	{
		BOOL CLOTH_DRESSMODE { ANIM OFF; }
		SEPARATOR { LINE; }


		GROUP
		{
			COLUMNS 3;

			BUTTON CLOTH_DO_RELAXING {}
			LONG CLOTH_RELAX_STEPS { MIN 1; ANIM OFF;}
			STATICTEXT { DUMMY; }

			SEPARATOR {  }
			STATICTEXT { JOINENDSCALE; }
			STATICTEXT { JOINENDSCALE; }

			BUTTON CLOTH_DO_DRESSING {}
			LONG CLOTH_DRESS_STEPS { MIN 1; ANIM OFF;}
			REAL   CLOTH_SEAMS_DIST { MIN 0.0; UNIT METER; ANIM OFF;}
		}

		SEPARATOR { LINE; }

		GROUP
		{
			COLUMNS 5;

			STATICTEXT CLOTH_TEXT_INIT { NOTEXT; }
			BUTTON CLOTH_SETINIT {}
			STATICTEXT { DUMMY; }
			BUTTON CLOTH_SHOWINIT{}
			STATICTEXT { DUMMY; }

			STATICTEXT CLOTH_TEXT_DRESS { NOTEXT; }
			BUTTON CLOTH_SETDINIT {}
			STATICTEXT { DUMMY; }
			BUTTON CLOTH_SHOWDINIT {}
			STATICTEXT { DUMMY; }

			SEPARATOR { LINE; }
			STATICTEXT { JOINENDSCALE; }
			STATICTEXT { JOINENDSCALE; }
			STATICTEXT { JOINENDSCALE; }
			STATICTEXT { JOINENDSCALE; }

			STATICTEXT CLOTH_TEXT_FIX { NOTEXT; }
			BUTTON CLOTH_SETMASS {}
			BUTTON CLOTH_CLEARMASS {}
			BUTTON CLOTH_SHOWMASS {}
			BOOL CLOTH_DRAWMASS{ }

			SEPARATOR { LINE; }
			STATICTEXT { JOINENDSCALE; }
			STATICTEXT { JOINENDSCALE; }
			STATICTEXT { JOINENDSCALE; }
			STATICTEXT { JOINENDSCALE; }

			STATICTEXT CLOTH_TEXT_SEAM { NOTEXT; }
			BUTTON CLOTH_SETSEAMS {}
			BUTTON CLOTH_CLEARSEAM {}
			BUTTON CLOTH_SHOWSEAMS {}
			STATICTEXT { DUMMY; }

			SEPARATOR { LINE; }
			STATICTEXT { JOINENDSCALE; }
			STATICTEXT { JOINENDSCALE; }
			STATICTEXT { JOINENDSCALE; }
			STATICTEXT { JOINENDSCALE; }
		}
	}

	GROUP CLOTH_GROUP_EFFECTS
	{
		BOOL CLOTH_BAKE { }

		SEPARATOR { LINE; }

		GROUP
		{
			COLUMNS 2;

			BASETIME CLOTH_CACHE_START { ANIM OFF; } STATICTEXT { JOINENDSCALE; }

			BUTTON CLOTH_DO_CALCULATE {  FIT_H; }
			STATICTEXT CLOTH_CACHE_INFO1 { SCALE_H; }

			BUTTON CLOTH_DELCACHE { FIT_H; }
			STATICTEXT CLOTH_CACHE_INFO2 { SCALE_H; }

			BUTTON CLOTH_CACHE_FRAME {  FIT_H; }
			STATICTEXT { DUMMY; SCALE_H; }

			SEPARATOR { } STATICTEXT { JOINENDSCALE; }

			BUTTON CLOTH_CACHE_LOAD {  FIT_H; }
			STATICTEXT { DUMMY; SCALE_H; }

			BUTTON CLOTH_CACHE_SAVE {  FIT_H; }
			STATICTEXT { DUMMY; SCALE_H; }

		}
	}

	GROUP CLOTH_GROUP_EXPERT
	{
		SCALE_V;

		GROUP
		{
			COLUMNS 2;

			LONG CLOTH_SUBDIV { MIN 1; MAX 100; }
			STATICTEXT { JOINEND; }

			BOOL CLOTH_SELF { }
			STATICTEXT { JOINEND; }

			BOOL CLOTH_GIA {}
			STATICTEXT { JOINEND; }

			BOOL CLOTH_POINTS {}
			REAL CLOTH_P_EPS  { MIN 0.0; UNIT METER;}

			BOOL CLOTH_EDGES {}
			REAL CLOTH_K_EPS  { MIN 0.0; UNIT METER;}

			BOOL CLOTH_POLYS {}
			REAL CLOTH_V_EPS  { MIN 0.0; UNIT METER;}
		}
	 	
		SEPARATOR { LINE; }

	 	IN_EXCLUDE  CLOTH_INCLUDE
	 	{
	 		SCALE_V;	ACCEPT { Obase; };
	 	}

		DEFAULT 0;
	}
}