CONTAINER CNurbsObject
{
	NAME Tcnurbs;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
	  GROUP
	  {
			COLUMNS 2;
		  LONG CNURBS_SUB  { MIN 0; MAX 7; }
			STATICTEXT {}

			REAL CNURBS_FAK  { UNIT PERCENT; MIN 0.0; MAX 100.0; }
			BOOL CNURBS_LIMIT  { }
	  
			REAL CNURBS_DOUBLE  { UNIT METER; }
			BOOL CNURBS_PARALLEL { }
		}
	}
}
