CONTAINER ColliderTag
{
	NAME Trbd;
	INCLUDE Tbase;

	GROUP ID_TAGPROPERTIES
	{
		BOOL COLLIDER_USE {}

		GROUP
		{
			REAL COLLIDER_BOUNCE { UNIT PERCENT; MIN 0.0; }
			REAL COLLIDER_STICKI { UNIT PERCENT; MIN 0.0; MAX 100.0; }
		}

		SEPARATOR { LINE; }

		GROUP
		{
			COLUMNS 5;

			STATICTEXT COLLIDER_TEXT_EXCL {}
			BUTTON COLLIDER_SET_EXCL {}
			BUTTON COLLIDER_CLEAR_EXCL {}
			BUTTON COLLIDER_SHOW_EXCL {}
			BOOL COLLIDER_DRAW_EXCL {}
		}
	}
}
