CONTAINER Obodycapture
{
	NAME Obodycapture;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{	
		FILENAME BODYCAPTURE_FILENAME { ANIM OFF; }
			
		SEPARATOR { LINE; }
		
		GROUP
		{
			COLUMNS 2;
			LINK BODYCAPTURE_BODY_LINK {  ANIM OFF; ACCEPT { Onull; } }
			BUTTON BODYCAPTURE_BODY_ADD { }
		}

		SEPARATOR { LINE; }
		
		GROUP
		{
			COLUMNS 2;
			LONG BODYCAPTURE_POSE
			{
				ANIM OFF;
				CYCLE
				{
					BODYCAPTURE_POSE_CAPTURE;
					BODYCAPTURE_POSE_T;
				}
			}
		
			BOOL BODYCAPTURE_LOCKED { ANIM OFF; }
		}
		
		SEPARATOR { LINE; }

		BUTTON BODYCAPTURE_SETTIMELINE { }
		
		SEPARATOR { LINE; }
		
		GROUP 
		{
			COLUMNS 2;
			BUTTON BODYCAPTURE_SETNEUTRALFRAME { }
			BUTTON BODYCAPTURE_CLEARNEUTRALFRAME { }
		}
						
		SEPARATOR { LINE; }

		LONG BODYCAPTURE_STARTFRAME { ANIM OFF; MIN 0;}
		LONG BODYCAPTURE_RANGELENGTH { ANIM OFF; MIN 0;}
		//BOOL BODYCAPTURE_LOOP {ANIM OFF;}
		
		SEPARATOR { LINE; }

		BOOL BODYCAPTURE_ROTATION { ANIM OFF; }
		BOOL BODYCAPTURE_OFFSET { ANIM OFF; }
						
		SEPARATOR { LINE; }
			
		GROUP
		{
			COLUMNS 2;
			LINK BODYCAPTURE_CAMERA {  ANIM OFF; ACCEPT { Ocamera; } }
			BUTTON BODYCAPTURE_ADDCAMERA { }
		}
		
		SEPARATOR { LINE; }
		
		LONG BODYCAPTURE_ORIENTATION
		{
			ANIM OFF;
			CYCLE
			{
				BODYCAPTURE_ORIENTATION_Z_POS;
				BODYCAPTURE_ORIENTATION_Z_NEG;
			}
		}
				
		SEPARATOR { LINE; }
		BUTTON BODYCAPTURE_BAKE { }
		//BUTTON BODYCAPTURE_CREATEMOTIONCLIP { }
								
		SEPARATOR { LINE; }

		GROUP 
		{
			COLUMNS 1;
			STATICTEXT BODYCAPTURE_UID { }	
		}
	}
		
		GROUP BODYCAPTURE_MATRICES
		{
			GROUP BODYCAPTURE_MATRIX_BODY_GROUP
			{
				DEFAULT 1;
				LAYOUTGROUP; COLUMNS 2; 
				GROUP
				{
					VECTOR BODYCAPTURE_MATRIX_BODY_POSITION { UNIT METER;  CUSTOMGUI SUBDESCRIPTION; ANIM OFF;}
				}
				GROUP
				{
					VECTOR BODYCAPTURE_MATRIX_BODY_ROTATION { UNIT DEGREE; CUSTOMGUI SUBDESCRIPTION; ANIM OFF;}
				}
			}
			
			GROUP BODYCAPTURE_MATRIX_CAMERA_GROUP
			{
				DEFAULT 1;
				LAYOUTGROUP; COLUMNS 2; 
				GROUP
				{
					VECTOR BODYCAPTURE_MATRIX_CAMERA_POSITION { UNIT METER;  CUSTOMGUI SUBDESCRIPTION; ANIM OFF;}
				}
				GROUP
				{
					VECTOR BODYCAPTURE_MATRIX_CAMERA_ROTATION { UNIT DEGREE; CUSTOMGUI SUBDESCRIPTION; ANIM OFF;}	
				}
			}
			
			GROUP BODYCAPTURE_MATRIX_NEUTRALFRAME_GROUP
			{
				DEFAULT 1;
				LAYOUTGROUP; COLUMNS 2; 
				GROUP
				{
					VECTOR BODYCAPTURE_MATRIX_NEUTRALFRAME_POSITION { UNIT METER;  CUSTOMGUI SUBDESCRIPTION; ANIM OFF;}
				}
				GROUP
				{
					VECTOR BODYCAPTURE_MATRIX_NEUTRALFRAME_ROTATION { UNIT DEGREE; CUSTOMGUI SUBDESCRIPTION; ANIM OFF;}	
				}
			}
		}
	}
}
