CONTAINER Ofacecapture
{
	NAME Ofacecapture;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{	
		FILENAME FACECAPTURE_FILENAME { ANIM OFF; }
		//STATICTEXT FACECAPTURE_FRAMECOUNT { }
		//BUTTON FACECAPTURE_RELOAD { }
			
		SEPARATOR { LINE; }
		
		GROUP
		{
			COLUMNS 2;
			LINK FACECAPTURE_FACEMESH_LINK {  ANIM OFF; ACCEPT { Opolygon; } }
			BUTTON FACECAPTURE_FACEMESH_ADD { }
		}
		BUTTON FACECAPTURE_FACEMESH_QUADMESH { }
	
		SEPARATOR { LINE; }

		BUTTON FACECAPTURE_SETTIMELINE { }
		
		SEPARATOR { LINE; }
		
		GROUP 
		{
			COLUMNS 2;
			BUTTON FACECAPTURE_SETNEUTRALFRAME { }
			BUTTON FACECAPTURE_CLEARNEUTRALFRAME { }
		}
		
		SEPARATOR { LINE; }
		
		GROUP
		{
			COLUMNS 2;
			BUTTON FACECAPTURE_ADDSOUND { }
			BUTTON FACECAPTURE_SOUNDTOGGLE { }
		}
		
		SEPARATOR { LINE; }
		
		GROUP 
		{
			COLUMNS 1;
			BUTTON FACECAPTURE_ADDEYES { }
		}
		
		SEPARATOR { LINE; }
		
		//LONG FACECAPTURE_LOSTFRAME
		//{
		//	ANIM OFF;
		//	CYCLE
		//	{
		//		FACECAPTURE_LOSTFRAME_HOLD;
		//		//FACECAPTURE_LOSTFRAME_BLEND;
		//		FACECAPTURE_LOSTFRAME_HIDE;
		//	}
		//}
		
		SEPARATOR { LINE; }

		BOOL FACECAPTURE_USESINGLETEXTURE { ANIM OFF; }
		LONG FACECAPTURE_FRAMETEXTURE { ANIM OFF; MIN 0; }
		BUTTON FACECAPTURE_SETDEFAULTUVS { }
		
		SEPARATOR { LINE; }

		LONG FACECAPTURE_STARTFRAME { ANIM OFF; }
		//LONG FACECAPTURE_RANGESTART { ANIM OFF; MIN 0;}
		LONG FACECAPTURE_RANGELENGTH { ANIM OFF; MIN 0;}
		//BOOL FACECAPTURE_LOOP { ANIM OFF; }
		
		SEPARATOR { LINE; }

		BOOL FACECAPTURE_ROTATION { ANIM OFF; }
		BOOL FACECAPTURE_OFFSET { ANIM OFF; }
						
		SEPARATOR { LINE; }
			
		GROUP
		{
			COLUMNS 2;
			LINK FACECAPTURE_CAMERA {  ANIM OFF; ACCEPT { Ocamera; } }
			BUTTON FACECAPTURE_ADDCAMERA { }
		}
		
		SEPARATOR { LINE; }
		
		LONG FACECAPTURE_ORIENTATION
		{
			ANIM OFF;
			CYCLE
			{
				FACECAPTURE_ORIENTATION_Z_POS;
				FACECAPTURE_ORIENTATION_Z_NEG;
			}
		}
		
		SEPARATOR { LINE; }
		
		GROUP
		{
			COLUMNS 2;
			BUTTON FACECAPTURE_CACHEOPENGL { }
			BUTTON FACECAPTURE_CACHECANCEL { }
		}
		
		SEPARATOR { LINE; }
		
		BUTTON FACECAPTURE_COPYFILESTOPROJECT { }
		
		SEPARATOR { LINE; }
		
		BUTTON FACECAPTURE_CREATEPOSTMORPH { }
		
		SEPARATOR { LINE; }
		
		GROUP 
		{
			COLUMNS 1;
			STATICTEXT FACECAPTURE_UID { }	
		}
	}
	
	GROUP FACECAPTURE_BLENDSHAPES
	{
		BOOL FACECAPTURE_FLIP_LEFTRIGHT { ANIM OFF;}
		GROUP FACECAPTURE_BLENDSHAPE_LEFTEYE
		{
			DEFAULT 1;
			REAL FACECAPTURE_BLENDSHAPE_LEFTEYE_BLINK { MIN 0; MAX 100; UNIT PERCENT; ANIM OFF;}
			REAL FACECAPTURE_BLENDSHAPE_LEFTEYE_LOOKDOWN {MIN 0; MAX 100; UNIT PERCENT;  ANIM OFF;}
			REAL FACECAPTURE_BLENDSHAPE_LEFTEYE_LOOKIN {MIN 0; MAX 100; UNIT PERCENT;  ANIM OFF;}
			REAL FACECAPTURE_BLENDSHAPE_LEFTEYE_LOOKOUT { MIN 0; MAX 100; UNIT PERCENT;ANIM OFF; }
			REAL FACECAPTURE_BLENDSHAPE_LEFTEYE_LOOKUP { MIN 0; MAX 100; UNIT PERCENT; ANIM OFF;}
			REAL FACECAPTURE_BLENDSHAPE_LEFTEYE_SQUINT { MIN 0; MAX 100; UNIT PERCENT;ANIM OFF; }
			REAL FACECAPTURE_BLENDSHAPE_LEFTEYE_WIDE { MIN 0; MAX 100; UNIT PERCENT;  ANIM OFF;}
		}
			
		GROUP FACECAPTURE_BLENDSHAPE_RIGHTEYE
		{
			DEFAULT 1;
			REAL FACECAPTURE_BLENDSHAPE_RIGHTEYE_BLINK {MIN 0; MAX 100; UNIT PERCENT; ANIM OFF; }
			REAL FACECAPTURE_BLENDSHAPE_RIGHTEYE_LOOKDOWN { MIN 0; MAX 100; UNIT PERCENT;ANIM OFF; }
			REAL FACECAPTURE_BLENDSHAPE_RIGHTEYE_LOOKIN {MIN 0; MAX 100; UNIT PERCENT;  ANIM OFF;}
			REAL FACECAPTURE_BLENDSHAPE_RIGHTEYE_LOOKOUT { MIN 0; MAX 100; UNIT PERCENT; ANIM OFF;}
			REAL FACECAPTURE_BLENDSHAPE_RIGHTEYE_LOOKUP { MIN 0; MAX 100; UNIT PERCENT;ANIM OFF; }
			REAL FACECAPTURE_BLENDSHAPE_RIGHTEYE_SQUINT {MIN 0; MAX 100; UNIT PERCENT; ANIM OFF; }
			REAL FACECAPTURE_BLENDSHAPE_RIGHTEYE_WIDE{ MIN 0; MAX 100; UNIT PERCENT;ANIM OFF; }
		}
		
		GROUP FACECAPTURE_BLENDSHAPE_JAW
		{
			DEFAULT 1;
			REAL FACECAPTURE_BLENDSHAPE_JAW_FORWARD{MIN 0; MAX 100; UNIT PERCENT; ANIM OFF; }
			REAL FACECAPTURE_BLENDSHAPE_JAW_LEFT{ MIN 0; MAX 100; UNIT PERCENT;ANIM OFF; }
			REAL FACECAPTURE_BLENDSHAPE_JAW_RIGHT{ MIN 0; MAX 100; UNIT PERCENT; ANIM OFF;}
			REAL FACECAPTURE_BLENDSHAPE_JAW_OPEN{ MIN 0; MAX 100; UNIT PERCENT; ANIM OFF;}
		}
		
		GROUP FACECAPTURE_BLENDSHAPE_MOUTH
		{
			DEFAULT 1;
			REAL FACECAPTURE_BLENDSHAPE_MOUTH_CLOSE {MIN 0; MAX 100; UNIT PERCENT;  ANIM OFF;}
			REAL FACECAPTURE_BLENDSHAPE_MOUTH_FUNNEL {MIN 0; MAX 100; UNIT PERCENT;  ANIM OFF;}
			REAL FACECAPTURE_BLENDSHAPE_MOUTH_PUCKER { MIN 0; MAX 100; UNIT PERCENT;ANIM OFF; }
			REAL FACECAPTURE_BLENDSHAPE_MOUTH_LEFT {MIN 0; MAX 100; UNIT PERCENT; ANIM OFF; }
			REAL FACECAPTURE_BLENDSHAPE_MOUTH_RIGHT { MIN 0; MAX 100; UNIT PERCENT; ANIM OFF;}
			REAL FACECAPTURE_BLENDSHAPE_MOUTH_SMILELEFT {MIN 0; MAX 100; UNIT PERCENT; ANIM OFF; }
			REAL FACECAPTURE_BLENDSHAPE_MOUTH_SMILERIGHT { MIN 0; MAX 100; UNIT PERCENT; ANIM OFF;}
			REAL FACECAPTURE_BLENDSHAPE_MOUTH_FROWNLEFT {MIN 0; MAX 100; UNIT PERCENT; ANIM OFF; }
			REAL FACECAPTURE_BLENDSHAPE_MOUTH_FROWNRIGHT { MIN 0; MAX 100; UNIT PERCENT;ANIM OFF; }
			REAL FACECAPTURE_BLENDSHAPE_MOUTH_DIMPLELEFT {MIN 0; MAX 100; UNIT PERCENT; ANIM OFF;}
			REAL FACECAPTURE_BLENDSHAPE_MOUTH_DIMPLERIGHT { MIN 0; MAX 100; UNIT PERCENT; ANIM OFF;}
			REAL FACECAPTURE_BLENDSHAPE_MOUTH_STRETCHLEFT { MIN 0; MAX 100; UNIT PERCENT; ANIM OFF;}
			REAL FACECAPTURE_BLENDSHAPE_MOUTH_STRETCHRIGHT {MIN 0; MAX 100; UNIT PERCENT;  ANIM OFF;}
			REAL FACECAPTURE_BLENDSHAPE_MOUTH_ROLLLOWER { MIN 0; MAX 100; UNIT PERCENT;ANIM OFF; }
			REAL FACECAPTURE_BLENDSHAPE_MOUTH_ROLLUPPER {MIN 0; MAX 100; UNIT PERCENT;  ANIM OFF;}
			REAL FACECAPTURE_BLENDSHAPE_MOUTH_SHRUGLOWER { MIN 0; MAX 100; UNIT PERCENT; ANIM OFF;}
			REAL FACECAPTURE_BLENDSHAPE_MOUTH_SHRUGUPPER { MIN 0; MAX 100; UNIT PERCENT; ANIM OFF;}
			REAL FACECAPTURE_BLENDSHAPE_MOUTH_PRESSLEFT { MIN 0; MAX 100; UNIT PERCENT;ANIM OFF; }
			REAL FACECAPTURE_BLENDSHAPE_MOUTH_PRESSRIGHT { MIN 0; MAX 100; UNIT PERCENT; ANIM OFF;}
			REAL FACECAPTURE_BLENDSHAPE_MOUTH_LOWERDOWNLEFT { MIN 0; MAX 100; UNIT PERCENT;ANIM OFF; }
			REAL FACECAPTURE_BLENDSHAPE_MOUTH_LOWERDOWNRIGHT { MIN 0; MAX 100; UNIT PERCENT;ANIM OFF; }
			REAL FACECAPTURE_BLENDSHAPE_MOUTH_UPPERUPLEFT {MIN 0; MAX 100; UNIT PERCENT; ANIM OFF; }
			REAL FACECAPTURE_BLENDSHAPE_MOUTH_UPPERUPRIGHT { MIN 0; MAX 100; UNIT PERCENT;ANIM OFF; }
		}
		
		GROUP FACECAPTURE_BLENDSHAPE_BROW
		{
			DEFAULT 1;
			REAL FACECAPTURE_BLENDSHAPE_BROW_DOWNLEFT { MIN 0; MAX 100; UNIT PERCENT;ANIM OFF; }
			REAL FACECAPTURE_BLENDSHAPE_BROW_DOWNRIGHT { MIN 0; MAX 100; UNIT PERCENT;ANIM OFF; }
			REAL FACECAPTURE_BLENDSHAPE_BROW_INNERUP { MIN 0; MAX 100; UNIT PERCENT;ANIM OFF; }
			REAL FACECAPTURE_BLENDSHAPE_BROW_OUTERUPLEFT { MIN 0; MAX 100; UNIT PERCENT;ANIM OFF; }
			REAL FACECAPTURE_BLENDSHAPE_BROW_OUTERUPRIGHT {MIN 0; MAX 100; UNIT PERCENT;ANIM OFF;  }
		}
		
		GROUP FACECAPTURE_BLENDSHAPE_CHEEK
		{
			DEFAULT 1;
			REAL FACECAPTURE_BLENDSHAPE_CHEEK_PUFF { MIN 0; MAX 100; UNIT PERCENT; ANIM OFF;}
			REAL FACECAPTURE_BLENDSHAPE_CHEEK_SQUINTLEFT { MIN 0; MAX 100; UNIT PERCENT;ANIM OFF; }
			REAL FACECAPTURE_BLENDSHAPE_CHEEK_SQUINTRIGHT { MIN 0; MAX 100; UNIT PERCENT;ANIM OFF; }	
		}
		
		GROUP FACECAPTURE_BLENDSHAPE_NOSE
		{
			DEFAULT 1;
			REAL FACECAPTURE_BLENDSHAPE_NOSE_SNEERLEFT {MIN 0; MAX 100; UNIT PERCENT; ANIM OFF; }
			REAL FACECAPTURE_BLENDSHAPE_NOSE_SNEERRIGHT {MIN 0; MAX 100; UNIT PERCENT;ANIM OFF;  }
		}
        GROUP FACECAPTURE_BLENDSHAPE_TONGUE
        {
            DEFAULT 1;
            REAL FACECAPTURE_BLENDSHAPE_TONGUE_OUT {MIN 0; MAX 100; UNIT PERCENT;ANIM OFF;  }
        }
	}
	
	GROUP FACECAPTURE_EXTRADATA
	{
		GROUP FACECAPTURE_EYETRACKING
		{
			GROUP FACECAPTURE_EYETRACKING_LEFTEYE
			{
				DEFAULT 1;
				LAYOUTGROUP; COLUMNS 2; 
				GROUP
				{
					VECTOR FACECAPTURE_EYETRACKING_LEFTEYE_POSITION { UNIT METER;  CUSTOMGUI SUBDESCRIPTION; ANIM OFF;}
				}
				GROUP
				{
					VECTOR FACECAPTURE_EYETRACKING_LEFTEYE_ROTATION { UNIT DEGREE; CUSTOMGUI SUBDESCRIPTION; ANIM OFF;}
				}
			}
			GROUP FACECAPTURE_EYETRACKING_RIGHTEYE
			{
				DEFAULT 1;
				LAYOUTGROUP; COLUMNS 2; 
				GROUP
				{
					VECTOR FACECAPTURE_EYETRACKING_RIGHTEYE_POSITION { UNIT METER;  CUSTOMGUI SUBDESCRIPTION; ANIM OFF;}
				}
				GROUP
				{
					VECTOR FACECAPTURE_EYETRACKING_RIGHTEYE_ROTATION { UNIT DEGREE; CUSTOMGUI SUBDESCRIPTION; ANIM OFF;}	
				}
			}
		   VECTOR FACECAPTURE_EYETRACKING_LOOKATPOINT {ANIM OFF; }
		}

		GROUP FACECAPTURE_LIGHT
		{
			VECTOR FACECAPTURE_LIGHT_DIRECTION { ANIM OFF; }
			REAL FACECAPTURE_LIGHT_INTENSITY { ANIM OFF; }
		}
		
		GROUP FACECAPTURE_MATRICES
		{
			GROUP FACECAPTURE_MATRIX_FACE_GROUP
			{
				DEFAULT 1;
				LAYOUTGROUP; COLUMNS 2; 
				GROUP
				{
					VECTOR FACECAPTURE_MATRIX_FACE_POSITION { UNIT METER;  CUSTOMGUI SUBDESCRIPTION; ANIM OFF;}
				}
				GROUP
				{
					VECTOR FACECAPTURE_MATRIX_FACE_ROTATION { UNIT DEGREE; CUSTOMGUI SUBDESCRIPTION; ANIM OFF;}
				}
			}
			
			GROUP FACECAPTURE_MATRIX_CAMERA_GROUP
			{
				DEFAULT 1;
				LAYOUTGROUP; COLUMNS 2; 
				GROUP
				{
					VECTOR FACECAPTURE_MATRIX_CAMERA_POSITION { UNIT METER;  CUSTOMGUI SUBDESCRIPTION; ANIM OFF;}
				}
				GROUP
				{
					VECTOR FACECAPTURE_MATRIX_CAMERA_ROTATION { UNIT DEGREE; CUSTOMGUI SUBDESCRIPTION; ANIM OFF;}	
				}
			}
			
			GROUP FACECAPTURE_MATRIX_NEUTRALFRAME_GROUP
			{
				DEFAULT 1;
				LAYOUTGROUP; COLUMNS 2; 
				GROUP
				{
					VECTOR FACECAPTURE_MATRIX_NEUTRALFRAME_POSITION { UNIT METER;  CUSTOMGUI SUBDESCRIPTION; ANIM OFF;}
				}
				GROUP
				{
					VECTOR FACECAPTURE_MATRIX_NEUTRALFRAME_ROTATION { UNIT DEGREE; CUSTOMGUI SUBDESCRIPTION; ANIM OFF;}	
				}
			}
		}
	}
	
	//GROUP FACECAPTURE_CALIBRATE_GROUP
	//{
	//	FILENAME FACECAPTURE_CALIBRATE_NEUTRAL { ANIM OFF; }
	//	FILENAME FACECAPTURE_CALIBRATE_MOVEMENT { ANIM OFF; }		
	//	BUTTON FACECAPTURE_CALIBRATE { }
	//}	
}
