CONTAINER Tfacepose
{
	NAME Tfacepose;
	INCLUDE Tbase;

	GROUP ID_TAGPROPERTIES
	{
		SCALE_H;
		LINK TFACEPOSE_CAPTURE {  ANIM OFF; ACCEPT { 1040464; } }
		LINK TFACEPOSE_EXPRESSO {  ANIM OFF; ACCEPT { 1001149; } }
		LINK TFACEPOSE_POSEMORPH { ANIM OFF; ACCEPT { 1024237; } }
		
		//SEPARATOR { LINE; }
		//BUTTON TFACEPOSE_ADD_PSR_XPRESSO { }
		
		SEPARATOR { LINE; }
		
		BUTTON TFACEPOSE_CREATEALL { }

		SEPARATOR { LINE; }
		
		FILENAME TFACEPOSE_CALIBRATE_CAPTURE {  ANIM OFF; }
		BUTTON TFACEPOSE_CALIBRATE { }	
		
		SEPARATOR { LINE; }
		
		GROUP 
		{
			COLUMNS 3;
			BUTTON TFACEPOSE_BAKE_BLENDSHAPES { }
			BUTTON TFACEPOSE_BAKE_FACE_PSR { }
			BUTTON TFACEPOSE_BAKE_EYES_PSR { }
			BUTTON TFACEPOSE_BAKE_SOUND { }
			BUTTON TFACEPOSE_BAKE_ALL { }
		}
	}
	
	GROUP TFACEPOSE_BLENDSHAPES
	{
		DEFAULT 1;	
		GROUP TFACEPOSE_BLENDSHAPE_LEFTEYE
		{
			DEFAULT 1;
			COLUMNS 2;
			BUTTON TFACEPOSE_BLENDSHAPE_LEFTEYE_BLINK { }
			BUTTON TFACEPOSE_BLENDSHAPE_LEFTEYE_LOOKDOWN { }
			BUTTON TFACEPOSE_BLENDSHAPE_LEFTEYE_LOOKIN { }
			BUTTON TFACEPOSE_BLENDSHAPE_LEFTEYE_LOOKOUT { }
			BUTTON TFACEPOSE_BLENDSHAPE_LEFTEYE_LOOKUP { }
			BUTTON TFACEPOSE_BLENDSHAPE_LEFTEYE_SQUINT { }
			BUTTON TFACEPOSE_BLENDSHAPE_LEFTEYE_WIDE { }
		}
			
		GROUP TFACEPOSE_BLENDSHAPE_RIGHTEYE
		{
			DEFAULT 1;
			COLUMNS 2;
			BUTTON TFACEPOSE_BLENDSHAPE_RIGHTEYE_BLINK { }
			BUTTON TFACEPOSE_BLENDSHAPE_RIGHTEYE_LOOKDOWN {  }
			BUTTON TFACEPOSE_BLENDSHAPE_RIGHTEYE_LOOKIN {}
			BUTTON TFACEPOSE_BLENDSHAPE_RIGHTEYE_LOOKOUT {}
			BUTTON TFACEPOSE_BLENDSHAPE_RIGHTEYE_LOOKUP {}
			BUTTON TFACEPOSE_BLENDSHAPE_RIGHTEYE_SQUINT {}
			BUTTON TFACEPOSE_BLENDSHAPE_RIGHTEYE_WIDE{ }
		}
		
		GROUP TFACEPOSE_BLENDSHAPE_JAW
		{
			DEFAULT 1;
			COLUMNS 2;
			BUTTON TFACEPOSE_BLENDSHAPE_JAW_FORWARD{ }
			BUTTON TFACEPOSE_BLENDSHAPE_JAW_LEFT{  }
			BUTTON TFACEPOSE_BLENDSHAPE_JAW_RIGHT{}
			BUTTON TFACEPOSE_BLENDSHAPE_JAW_OPEN{ }
		}
		
		GROUP TFACEPOSE_BLENDSHAPE_MOUTH
		{
			DEFAULT 1;
			COLUMNS 2;
			BUTTON TFACEPOSE_BLENDSHAPE_MOUTH_LEFT {  }
			BUTTON TFACEPOSE_BLENDSHAPE_MOUTH_RIGHT {  }
			BUTTON TFACEPOSE_BLENDSHAPE_MOUTH_SMILELEFT {  }
			BUTTON TFACEPOSE_BLENDSHAPE_MOUTH_SMILERIGHT {  }
			BUTTON TFACEPOSE_BLENDSHAPE_MOUTH_FROWNLEFT {  }
			BUTTON TFACEPOSE_BLENDSHAPE_MOUTH_FROWNRIGHT {  }
			BUTTON TFACEPOSE_BLENDSHAPE_MOUTH_DIMPLELEFT { }
			BUTTON TFACEPOSE_BLENDSHAPE_MOUTH_DIMPLERIGHT {  }
			BUTTON TFACEPOSE_BLENDSHAPE_MOUTH_STRETCHLEFT {  }
			BUTTON TFACEPOSE_BLENDSHAPE_MOUTH_STRETCHRIGHT { }
			BUTTON TFACEPOSE_BLENDSHAPE_MOUTH_ROLLLOWER {  }
			BUTTON TFACEPOSE_BLENDSHAPE_MOUTH_ROLLUPPER { }
			BUTTON TFACEPOSE_BLENDSHAPE_MOUTH_SHRUGLOWER {  }
			BUTTON TFACEPOSE_BLENDSHAPE_MOUTH_SHRUGUPPER {  }
			BUTTON TFACEPOSE_BLENDSHAPE_MOUTH_PRESSLEFT {  }
			BUTTON TFACEPOSE_BLENDSHAPE_MOUTH_PRESSRIGHT {  }
			BUTTON TFACEPOSE_BLENDSHAPE_MOUTH_LOWERDOWNLEFT {  }
			BUTTON TFACEPOSE_BLENDSHAPE_MOUTH_LOWERDOWNRIGHT {  }
			BUTTON TFACEPOSE_BLENDSHAPE_MOUTH_UPPERUPLEFT {  }
			BUTTON TFACEPOSE_BLENDSHAPE_MOUTH_UPPERUPRIGHT {  }
			BUTTON TFACEPOSE_BLENDSHAPE_MOUTH_CLOSE { }
			BUTTON TFACEPOSE_BLENDSHAPE_MOUTH_FUNNEL { }
			BUTTON TFACEPOSE_BLENDSHAPE_MOUTH_PUCKER {  }
		}
		
		GROUP TFACEPOSE_BLENDSHAPE_BROW
		{
			DEFAULT 1;
			COLUMNS 2;
			BUTTON TFACEPOSE_BLENDSHAPE_BROW_DOWNLEFT {  }
			BUTTON TFACEPOSE_BLENDSHAPE_BROW_DOWNRIGHT {  }
			BUTTON TFACEPOSE_BLENDSHAPE_BROW_OUTERUPLEFT {  }
			BUTTON TFACEPOSE_BLENDSHAPE_BROW_OUTERUPRIGHT {  }
			BUTTON TFACEPOSE_BLENDSHAPE_BROW_INNERUP {  }
		}
		
		GROUP TFACEPOSE_BLENDSHAPE_CHEEK
		{
			DEFAULT 1;
			COLUMNS 2;
			BUTTON TFACEPOSE_BLENDSHAPE_CHEEK_SQUINTLEFT {  }
			BUTTON TFACEPOSE_BLENDSHAPE_CHEEK_SQUINTRIGHT {  }	
			BUTTON TFACEPOSE_BLENDSHAPE_CHEEK_PUFF {  }
		}
		
		GROUP TFACEPOSE_BLENDSHAPE_NOSE
		{
			DEFAULT 1;
			COLUMNS 2;
			BUTTON TFACEPOSE_BLENDSHAPE_NOSE_SNEERLEFT {  }
			BUTTON TFACEPOSE_BLENDSHAPE_NOSE_SNEERRIGHT {  }
		}

        GROUP TFACEPOSE_BLENDSHAPE_TONGUE
        {
            DEFAULT 1;
            COLUMNS 2;
            BUTTON TFACEPOSE_BLENDSHAPE_TONGUE_OUT {  }
        }
	}
}
