CONTAINER COMPOSITING3DTAG
{
	NAME COMPOSITING3DTAG;
	INCLUDE Tbase;
	GROUP ID_TAGPROPERTIES
	{
		//LINK COMP3DTAG_MOGRAPH { FIT_H; ANIM OFF;}
		BOOL	COMP3DTAG_CHILDREN	{ ANIM OFF;}
		BOOL	COMP3DTAG_CACHE		{ ANIM OFF;}
		LONG COMP3DTAG_MIDPOINT
		{
			ANIM OFF;
			FIT_H;
			
			CYCLE
			{
				COMP3DTAG_MIDTL;
				COMP3DTAG_MIDTR;
				COMP3DTAG_MIDCTR;
				COMP3DTAG_MIDBL;
				COMP3DTAG_MIDBR;
			}
		}
		BOOL COMP3DTAG_SOLID		{ANIM OFF;}
		LONG COMP3DTAG_SIZEX {ANIM OFF;  MIN 1; MAX 50000;}
		LONG COMP3DTAG_SIZEY {ANIM OFF;  MIN 1; MAX 50000;}
		COLOR COMP3DTAG_COLOR {ANIM OFF;}
		//LONG COMP3DTAG_ORIENTATION
		//{
		//	ANIM OFF;
		//	FIT_H;
			
		//	CYCLE
		//	{
		//		COMP3DTAG_PX;
		//		COMP3DTAG_MX;
		//		COMP3DTAG_PY;
		//		COMP3DTAG_MY;
		//		COMP3DTAG_PZ;
		//		COMP3DTAG_MZ;
		//	}
		//}
	}
}
