#ifndef C4D_SYMBOLS_H__
#define C4D_SYMBOLS_H__

enum
{
	IDS_NBP_ROOT = 10000,
	IDS_NBP_OBJECT,
	IDS_NBP_TAG,
	IDS_MATERIALTAG,
	IDS_SHADER_NBM,
	IDS_MULTIPLE_VALUES,
	IDS_TEXTUREUI,
	IDS_BSDF_LAYER_UNCONNECTED,
	IDS_PREVIEWIMAGE_DEFAULT,
	IDS_PREVIEWIMAGE_SMALL,
	IDS_PREVIEWIMAGE_MEDIUM,
	IDS_PREVIEWIMAGE_LARGE,
	IDS_PREVIEWIMAGE_HUGE,
	IDS_BSDFLAYERS_ADDLAYER,
	IDS_BSDFLAYERS_REMOVELAYER,
	IDS_BSDFLAYERS_COPY,
	IDS_BSDFLAYERS_PASTE,

	IDS_MATPREVIEW_DEFAULT,
	IDS_MATPREVIEW_FLAT2D,
	IDS_MATPREVIEW_SPHERE,
	IDS_MATPREVIEW_CUBE,
	IDS_MATPREVIEW_ROUND_CUBE,
	IDS_MATPREVIEW_PLANE,
	IDS_MATPREVIEW_CYLINDER,
	IDS_MATPREVIEW_TORUS,
	IDS_MATPREVIEW_PLANE_BACK,
	IDS_MATPREVIEW_2TORUS,
	IDS_MATPREVIEW_KNOT,
	IDS_MATPREVIEW_MULTIPLE_OBJECTS,
	IDS_MATPREVIEW_CANDLE,
	IDS_MATPREVIEW_CLOTH,
	IDS_MATPREVIEW_GEM,
	IDS_MATPREVIEW_OBJECTANIM,
	IDS_MATPREVIEW_OBJECT,

	IDS_PREVIEW_HUD,
	IDS_PICCOPY,
	IDS_COPYERROR,

	IDS_TEXTUREUI_RESOLUTION,
	IDS_TEXTUREUI_ALPHAS,
	IDS_TEXTUREUI_LAYERS,
	IDS_TEXTUREUI_COLORPROFILE,
	IDS_TEXTUREUI_ASPECT,
	IDS_TEXTUREUI_DPI,
	IDS_TEXTUREUI_NAME,
	IDS_TEXTUREUI_DURATION,
	IDS_TEXTUREUI_FPS,
	IDS_TEXTUREUI_ERROR,
	IDS_TEXTUREUI_CALCULATINGINFO,
	IDS_TEXTUREUI_URLNOTFOUND,
	IDS_TEXTUREUI_CHOOSEFILE,
	IDS_TEXTUREUI_YES,
	IDS_TEXTUREUI_NO,
	IDS_TEXTUREUI_CHOOSEIMAGETOLOAD,

	IDS_PREVIEW_NODE,
	IDS_PREVIEW_MATERIAL,

	IDS_AOV_ID_LABEL,
	IDS_AOVLAYERS_ADD_TO_RENDERSETTINGS,

	// End of symbol definition
	_DUMMY_ELEMENT_
};

#endif // C4D_SYMBOLS_H__
