#ifndef C4D_SYMBOLS_H__
#define C4D_SYMBOLS_H__

enum
{
	// string table definitions
	IDC_APPLY = 1000,

	IDS_DUMMY1 = 10000,

	IDS_MENU_ABOUT_HELP,
	IDS_MENU_ABOUT,

	DLG_ACTOR_RECORD,
		IDC_ACTOR_RECORD_POSITION,
		IDC_ACTOR_RECORD_SCALE,
		IDC_ACTOR_RECORD_ROTATION,
		IDC_ACTOR_RECORD_PLA,
		IDC_ACTOR_RECORD_HIERARCHY,

		IDC_ACTOR_RECORD_LAYER,
		IDC_ACTOR_RECORD_FROM,
		IDC_ACTOR_RECORD_TO,
		IDC_ACTOR_RECORD_START,
		IDC_ACTOR_RECORD_STOP,

		IDC_ACTOR_RECORD_MODE,
		IDC_ACTOR_RECORD_REWIND,

		IDC_ACTOR_RECORD_USESEQUENCE,
		IDC_ACTOR_RECORD_RANGE,
		IDC_ACTOR_RECORD_ATIME,

		IDS_RECORD_OMANAGER,
		IDS_RECORD_TMANAGER,
		IDC_ACTOR_RECORD_SINGLE,


	MAIN_GROUP,
		IDC_SEL_DEL,
		IDC_SEL_NUM,
		IDC_SEL_NAME,


//	DLG_POSE,
//		IDC_POSE_STRENGTH,
		IDS_PYNTHESIZER,
		DELME_IDS_RECORD,
		DELME_IDS_POSEANIM,

	DLG_BONE_TOOL,
		IDC_BT_ADDBONE,
		IDC_BT_ADDCHILD,
		IDC_BT_SPLITBONE,
		IDC_BT_ADDNULL,

	DLG_P2P,
		IDC_P2P_TREE,
		IDC_P2P_ADDLIB,
		IDC_P2P_REMOVE,
		IDC_P2P_NAME,
		IDC_P2P_TEST,
		IDC_P2P_RECORD,
		IDC_P2P_EDIT,
		IDC_P2P_SYNC,
		P2P_RDATA_NAME,
		IDC_P2P_GEOMETRY,

	DLG_TRIGGER,
		IDC_TRI_REDRAW,
		IDC_TRI_TIME,

	DLG_DILUTIONER,
		IDC_DELU_REDUCTION,
		IDC_DELU_BOOST,

	IDS_MOMIX,

	IDS_ABOUT,
	IDS_CAPPUCINO,
	IDS_EFFECTOR_TIP,
	IDS_EFFECTOR_ROOT,
	IDS_TARGET_TIP,
	IDS_TARGET_ROOT,
	IDS_USESOFTIK,
	IDS_ADDANCHOR,
	IDS_ADDROOTGOAL,
	IDS_ADDTIPGOAL,
	IDS_SETUPIKCHAIN,
	IDS_SETCHAINRESTPOSITION,
	IDS_SETCHAINRESTROTATION,
	IDS_AUTOREDRAW,
	IDS_SOFTIK,
	IDS_MOTION,
	IDS_MOTION1,
	IDS_MOTION2,
	IDS_MOMIXOBJECT,
	IDS_LIB,
	IDS_POSE,
	IDS_COPY,
	IDS_P2PLIBRARY,
	IDS_P2PMANAGER,
	IDS_EMPTY,
	IDS_BONETOOL,
	IDS_BONETOOLHELP,
	IDS_CLAUDEBONET,
	IDS_KEYREDUCER,
	IDS_TIMETOOL,
	IDS_TIMETOOLHELP,
	IDS_STEP,
	IDS_TIMEWARP,
	IDS_ADDUPVECTOR,
	IDS_MENU_PALETTE,
	IDS_MENU_PALETTE_HELP,
	IDS_UPV,
	IDS_REMOVED_CB_TAGS,
	// Dialog definitions of dlg_claudebonet start here
	DLG_CLAUDEBONET,
	IDC_ONLYVISIBLE,
	IDC_DISPLAYALLBONES,
	IDC_PAINTABSOLUTE,
	IDC_FORCE_SHADING,
	IDC_SET_REFERNCE_BTN,
	IDC_PAINTSTRENGTH,
	IDC_SETPAINT,
	IDC_PAINTRADIUS,
	IDC_REMOVEPAINT1,
	IDC_REMOVEPAINT2,
	IDC_REMOVEPAINT3,
	IDC_TIDYUP_BTN,
	// Dialog definitions of dlg_claudebonet end here

	// Dialog definitions of IDC_SET_REFERENCE_DIALOG start here
	IDC_SET_REFERENCE_DIALOG,
	IDC_REFERENCE_BONE_LIST,
	// Dialog definitions of IDC_SET_REFERENCE_DIALOG end here
	IDS_NO_REFERNCE,
	IDS_PYN_ENABLED,
	IDS_PYN_VALUE,
	IDS_PYN_LINK,

	DLG_MOTRIB,
		IDC_MOTRIB_TREE,
		IDC_MOTRIB_PX,
		IDC_MOTRIB_PY,
		IDC_MOTRIB_PZ,

		IDC_MOTRIB_RX,
		IDC_MOTRIB_RY,
		IDC_MOTRIB_RZ,
	IDS_MOTRIBMANAGER,

	IDS_MOTION_SEQ,
	IDS_MOBLEND_TREE,
	IDS_MOTRANS_SEQ,
	IDS_MOBLEND_SETUP,
	IDS_MOBLEND_GHOST,

	IDS_RETARGET,

	IDS_PMIX_ENABLED,
	IDS_PMIX_VALUE,
	IDS_PMIX_LINK,
	IDS_NPOSEMIXER,

	IDS_QUATERNION,

	IDS_PMIX_RECORD_L,
	IDS_PMIX_RECORD_S,

	IDS_SPERRE,
	IDS_HLP_BONETOOL,
	IDS_HLP_CB,
// BONE MIRROR
	IDS_BMDLG_TITLE,
	IDS_BMDLG_PLANE,
	IDS_BMDLG_PLANE_YZ,
	IDS_BMDLG_PLANE_XZ,
	IDS_BMDLG_PLANE_XY,
	IDS_BMDLG_ORIGIN,
	IDS_BMDLG_SELECTED,
	IDS_BMDLG_TOPMOST,
	IDS_BMDLG_WORLD,
	IDS_BMDLG_AUTOCENTRE,
	IDS_BMDLG_SEARCH,
	IDS_BMDLG_SUFFIX,
	IDS_BMDLG_PREFIX,
	IDS_BMDLG_REPLACE,
	IDS_BMDLG_WITH,
	IDS_BMDLG_CLONETAGS,
	IDS_BMDLG_CLONEANIM,
	IDS_BMDLG_MIRRORCHILDS,
	IDS_BMDLG_MIRRORCONST,
	IDS_BMDLG_MIRRORINF,
	IDS_BMDLG_MIRROR,
	IDS_BMDLG_PARENT,
	IDS_BMDLG_DEF_PREFIX,
	IDS_BMDLG_DEF_SUFFIX,
	IDS_BMDLG_BONEMIRROR,
	IDS_BMDLG_BONEMIRROR_HELP,

	IDC_BT_ADDBONEN,
	IDC_BT_ADDCHILDN,
	IDC_BT_FIX,
	IDC_BT_RESET,
	IDS_BT_CHECKOUTSUB,

	IDS_MOCCASUBMENU,
	IDS_MOCCACONVERSION,

	IDS_ANIM_P2P,

	// Character Definition, keeps enum in the same pack 
	IDS_CHARACTERDEF,
	IDS_BODYPART_SKELETON,
	IDS_BODYPART_CONTROLLERS,

	IDS_BODYPART_TORSO_NAME,
	IDS_BODYPART_LEFTARM_NAME,
	IDS_BODYPART_RIGHTARM_NAME,
	IDS_BODYPART_LEFTHAND_NAME,
	IDS_BODYPART_RIGHTHAND_NAME,
	IDS_BODYPART_LEFTLEG_NAME,
	IDS_BODYPART_RIGHTLEG_NAME,
	IDS_BODYPART_LEFTFOOT_NAME,
	IDS_BODYPART_RIGHTFOOT_NAME,
		// Torso
	IDS_BODYPART_TORSO_HIPS_NAME,
	IDS_BODYPART_TORSO_SPINE_NAME,
	IDS_BODYPART_TORSO_NECK_NAME,
	IDS_BODYPART_TORSO_HEAD_NAME,
	// Arm
	IDS_BODYPART_ARM_CLAVICLE_NAME,
	IDS_BODYPART_ARM_BICEP_NAME,
	IDS_BODYPART_ARM_FOREARM_NAME,
	IDS_BODYPART_ARM_HAND_NAME,
	// Leg
	IDS_BODYPART_LEG_THIGH_NAME,
	IDS_BODYPART_LEG_SHIN_NAME,
	IDS_BODYPART_LEG_FOOT_NAME,
	// Hand
	IDS_BODYPART_HAND_PALM_NAME,
	IDS_BODYPART_HAND_THUMB_NAME,
	IDS_BODYPART_HAND_INDEX_NAME,
	IDS_BODYPART_HAND_MIDDLE_NAME,
	IDS_BODYPART_HAND_RING_NAME,
	IDS_BODYPART_HAND_LITLLE_NAME,
	IDS_BODYPART_NEWPARTNAME,
	//------------------------------------------------ End of Character Definition Strings

	IDS_CHARACTERSOLVER,
		IDS_TOOLBODYPART_NAME,
		IDS_TOOLBODYPART_HELP,

	IDS_CHARACTERDEFINITION_PRESET,
		IDS_BROWSERPRESET_PRESETEXISTS,
		IDD_NEW_PRESET_DIALOG,
		IDC_NEW_PRESET_NAME_EDIT,
		IDC_NEW_PRESET_AUTHOR_EDIT,
		IDC_NEW_PRESET_INFO_EDIT,

	IDS_TOOLCHARACTERDEF_NAME,
	IDS_TOOLCHARACTERDEF_HELP,
	IDS_TOOLCHARACTERDEF_COLUMN1_NAME,
	IDS_TOOLCHARACTERDEF_COLUMN2_NAME,
	IDS_TOOLCHARACTERDEF_COLUMN3_NAME,
	IDS_TOOLCHARACTERDEF_REFERENCECOMPLETE,
	IDS_TOOLCHARACTERDEF_REFERENCEPARTIAL,
	IDS_TOOLCHARACTERDEF_REFERENCEMISSING,
	IDS_TOOLCHARACTERDEF_STATUS_EXTRACT,

	IDS_SOLVERTAG_COMPONENTMATCH,
	IDS_SOLVERTAG_OBJECTMATCH,
	IDS_SOLVERTAG_STATUS_SOURCE,
	IDS_SOLVERTAG_STATUS_SOURCEREF,
	IDS_SOLVERTAG_STATUS_SOURCESKEL,
	IDS_SOLVERTAG_STATUS_TARGET,
	IDS_SOLVERTAG_STATUS_TARGETREF,
	IDS_SOLVERTAG_STATUS_TARGETSKEL,


// End of symbol definition
	_DUMMY_ELEMENT_
};

#endif // C4D_SYMBOLS_H__
