#ifndef C4D_SYMBOLS_H__
#define C4D_SYMBOLS_H__

enum // hier die unregistrierten IDs
{
	IDS_STR = 10000,

	IDS_OM_ID_DIALOG,
	IDH_OM_ID_DIALOG,
	IDS_VOM_DIALOG,

	IDS_NEUTRON_HOOK,
	IDS_NEUTRON_OBJECT,
	IDS_NEUTRON_LEGACY_CONVERSION,

	IDS_SCENE_NODE_EDITOR,
	IDH_SCENE_NODE_EDITOR,

	_DUMMY_END_STRINGS
};

#endif // C4D_SYMBOLS_H__

