CONTAINER Tdriver
{
	NAME Tdriver;
	INCLUDE Texpression;

	GROUP ID_TAGPROPERTIES
	{
		LONG DRIVERTAG_DRIVERPARAMETER
		{
			CYCLE
			{
				DRIVERTAG_SOURCEMODE_OFF;
			}
		}
		
		SEPARATOR { LINE; }
		
		GROUP DRIVERTAG_GROUPDRIVER
		{			
			GROUP
			{
				COLUMNS 3;
				LONG DRIVERTAG_DRIVERVECTORMODE
				{
					CYCLE
					{
						DRIVERTAG_DRIVERVECTORMODEX;
						DRIVERTAG_DRIVERVECTORMODEY;
						DRIVERTAG_DRIVERVECTORMODEZ;
					}
					FIT_H;
					ANIM OFF;
				}
				REAL DRIVERTAG_DRIVERVECTORMIN { ANIM OFF; }
				REAL DRIVERTAG_DRIVERVECTORMAX { ANIM OFF; }
			}
			GROUP
			{
				COLUMNS 2;
				LONG DRIVERTAG_DRIVERGRIDX { MIN 1; MAX 25; ANIM OFF; }
				LONG DRIVERTAG_DRIVERGRIDY { MIN 1; MAX 25; ANIM OFF; }
			}
			DRIVERGRID DRIVERTAG_DRIVERGRID { CUSTOMGUI DRIVERCONTROLLER; COLUMNS 3; ROWS 3;}
						
			BOOL DRIVERTAG_CLAMP { }
			
			SEPARATOR { LINE; }
			GROUP
			{
				COLUMNS 2;
				LINK DRIVERTAG_DRIVENOBJECT { }
				LONG DRIVERTAG_MODE
				{
					CYCLE
					{
						DRIVERTAG_MODE_SINGLES;
						DRIVERTAG_MODE_RELATIVES;
					}
				}
			}
			
			SEPARATOR { LINE; }
			
			GROUP DRIVERTAG_GROUPDRIVING
			{
				LONG DRIVERTAG_DRIVENPARAMETER
				{
					CYCLE
					{
						DRIVERTAG_TARGETMODE_OFF;
					}
					ANIM OFF;
					FIT_H;
					SCALE_H;
				}
				GROUP
				{
					COLUMNS 3;
					BOOL DRIVERTAG_DRIVERMIX { ANIM OFF; FIT_H; SCALE_H; }
					BOOL DRIVERTAG_DRIVERRELATIVE { ANIM OFF; FIT_H; SCALE_H;}
					LONG DRIVERTAG_ABSMODE
					{
						CYCLE
						{
							DRIVERTAG_ABSMODE_NORMAL;
							DRIVERTAG_ABSMODE_ADD;
							DRIVERTAG_ABSMODE_MULTIPLY;
						}
					}
				}
				REAL DRIVERTAG_DRIVERMIN { UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; ANIM OFF; FIT_H; SCALE_H; }
				REAL DRIVERTAG_DRIVERMAX { UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; ANIM OFF; FIT_H; SCALE_H; }
			}
			GROUP DRIVERTAG_GROUPRELATIVE
			{
				COLUMNS 3;
			}
		}
	}
}
