CONTAINER vstag
{
	NAME vstag;
	INCLUDE Tbase;

	GROUP ID_VS_TAG_SETTINGS
	{
		DEFAULT	0;
	
		STRING ID_VS_TAG_NAME {}
		
		TEXTURE ID_VS_TAG_IMAGE { }
	
		SEPARATOR{LINE;}

		GROUP 
		{
			COLUMNS 2;
			LONG ID_VS_TAG_ASPECT
			{
				CYCLE
				{
					ID_VS_TAG_ASPECT_11;
					ID_VS_TAG_ASPECT_43;
					ID_VS_TAG_ASPECT_34;
					ID_VS_TAG_ASPECT_169;
				}
			}
			LONG ID_VS_BASE_SIZE {ANIM OFF;MIN 150;MAX 640;}
		}
	}


	GROUP ID_VS_TAG_DYNAMIC_HOTSPOTS
	{
		GROUP
		{
			COLUMNS 3;
			
			GROUP
			{
				BOOL ID_VS_TAG_LOCK	{ANIM OFF;}
				GROUP
				{
					COLUMNS 2;
					BUTTON ID_VS_TAG_HOTSPOT_ADD {}
					BUTTON ID_VS_TAG_HOTSPOT_REMOVE {}
				}
			}
		}

		GROUP 
		{
			COLUMNS 1;
			DEFAULT	1;
			BITMAPBUTTON	ID_VS_TAG_DYNAMIC_BUTTON	{FIT_H;BUTTON;ANIM OFF;}
			LINK	ID_VS_TAG_DYNAMIC_LINK				{ANIM OFF;}
			LONG	ID_VS_TAG_DYNAMIC_COMMAND			{FIT_H;ANIM OFF;MIN 0;}	
			STRING	ID_VS_TAG_DYNAMIC_NAME				{ANIM OFF;}
			LONG ID_VS_TAG_DYNAMIC_ACTION
			{	
				ANIM OFF;
				CYCLE
				{
					ID_VS_TAG_ACTION_NONE;
					//ID_VS_TAG_ACTION_AXIS;
					ID_VS_TAG_ACTION_MOVE;
					ID_VS_TAG_ACTION_SCALE;
					ID_VS_TAG_ACTION_ROTATE;
					ID_VS_TAG_ACTION_SPECIAL;	
				}
			}
		}
	}


	HIDE ID_VS_TAG_DYNAMIC_NAME;
	HIDE ID_VS_TAG_DYNAMIC_LINK;
	HIDE ID_VS_TAG_DYNAMIC_BUTTON;
	HIDE ID_VS_TAG_DYNAMIC_ACTION;
	HIDE ID_VS_TAG_DYNAMIC_COMMAND;
}


