CONTAINER Tcharacterdef
{
	NAME Tcharacterdef;
	INCLUDE Tbase;

	GROUP CD_BODYPART_GROUP
	{
		COLUMNS 2;
		BUTTON CD_SETREFERENCEPOSE	{ SCALE_H; }
		BUTTON CD_GOTOREFERENCEPOSE	{ SCALE_H; }
		BUTTON CD_OPENMANAGER		{ SCALE_H; }
		BUTTON CD_CREATESOLVER		{ SCALE_H; }
	}
}

