CONTAINER Tcharactersolver
{
	NAME Tcharactersolver;
	INCLUDE Texpression;
	GROUP ID_TAGPROPERTIES
	{
		LINK CS_SOURCE_CHARACTER 
			{ 
				ANIM OFF; 
				ACCEPT { 1054858;} // CHARACTERDEFINITION_TAG_ID
			}
		LINK CS_TARGET_CHARACTER 
			{ 
				ANIM OFF; 
				ACCEPT { 1054858;} // CHARACTERDEFINITION_TAG_ID
			}
			BUTTON CS_GOTORESTPOSE {}

		GROUP CS_SOLVERRESULT_GROUP
		{
			COLUMNS 1;
			STATICTEXT CS_COMPONENTMATCH_RESULT {}
			STATICTEXT CS_OBJECTMATCH_RESULT {}
			STATICTEXT CS_ERROR_RESULT {}
		}
	}
}

