CONTAINER Toolcharacterdef
{
	NAME Toolcharacterdef;

	GROUP TCD_UPPERCOMMANDS_GROUP
	{
		COLUMNS 2;
		BUTTON TCD_EXTRACTRESTPOSE	{ SCALE_H; }
		BUTTON TCD_APPLYRESTPOSE	{ SCALE_H; }
		BUTTON TCD_EXTRACTSKELETON	{ SCALE_H; }
		STATICTEXT	{ SCALE_H; }
	}

	GROUP TCD_TREE_GROUP
	{
		DEFAULT 1;
		COLUMNS 1;
		SCALE_V;
		ITEMTREE TCD_TREE
		{
			HEADERS;
			SCALE_H;
			SCALE_V;
			NEWLINE;
			DRAGDROP;
			COLUMNS 3;
		}
	}

	GROUP TCD_LOWERCOMMANDS_GROUP
	{
		COLUMNS 2;
		BUTTON TCD_ADDBODYPART		{ SCALE_H; }
		BUTTON TCD_REMOVEBODYPART	{ SCALE_H; }
		BUTTON TCD_LOADPRESET		{ SCALE_H; }
		BUTTON TCD_SAVEPRESET		{ SCALE_H; }
	}
}

