CONTAINER Toolbodypart
{
	NAME Toolbodypart;

	GROUP TBP_CHARACTERDEFINITION_ATTRIBUTES_GROUP
	{
		COLUMNS 1;
		SCALE_H; SCALE_V;

		GROUP
		{
			SCALE_H; SCALE_V;
			GROUP
			{
				STATICTEXT TBP_PART_JOINTS_NAME { SCALE_H; }
			}
			IN_EXCLUDE TBP_PART_JOINTS { SCALE_H; SCALE_V; }
		}

		GROUP
		{
			SCALE_H; SCALE_V;
			GROUP
			{
				STATICTEXT TBP_PART_CONTROLS_NAME { HIDDEN; }
			}
			IN_EXCLUDE TBP_PART_CONTROLS { SCALE_V; SCALE_H; HIDDEN; }
		}


		GROUP
		{
			SCALE_H; SCALE_V;
			GROUP
			{
				STATICTEXT TBP_PART_INCLUDESTRING_NAME {}
			}
			STRING TBP_PART_INCLUDESTRING { CUSTOMGUI MULTISTRING; SCALE_H; SCALE_V; }
		}

		GROUP
		{
			SCALE_H; SCALE_V;
			GROUP
			{
				STATICTEXT TBP_PART_EXCLUDESTRING_NAME {}
			}
			STRING TBP_PART_EXCLUDESTRING { CUSTOMGUI MULTISTRING; SCALE_H; SCALE_V; }
		}

		GROUP
		{
			SCALE_H;
			GROUP
			{
				STATICTEXT TBP_PART_IDENTIFIER_NAME {}
			}
			STRING TBP_PART_IDENTIFIER {}
		}
	}
}

