// Menudefinition for EDITOR_BP
MENU M_EDITOR_USER1
{
  SUBMENU IDS_EDITOR_FILE
  {
    PLUGIN_CMD_200000204; // Quit and Sign Out
    IDM_BEENDEN;
  }
  SUBMENU IDS_LAYOUT
  {
    IDM_CM_NEWPALETTE;
    IDM_CM_GROUPWINDOW;
    IDM_LOADPALETTE;
    IDM_CM_CUSTOMIZE;
    IDM_LOCK_LAYOUT;
    SEPARATOR;
    IDM_LOADLAYOUT;
    IDM_SAVELAYOUT;
    IDM_SAVELAYOUTAS;
    SEPARATOR;
    PLUGIN_CMD_300000186;
    M_COFFEEMANAGER_MENUMANAGER;
    SEPARATOR;
    SUBMENU IDS_MENU_LAYOUTS
    {
      IDM_DEFAULT_LAYOUTS;
    }
    SUBMENU IDS_MENU_MENUS
    {
      IDM_MAINMENU_C4D;
      IDM_MAINMENU_BP;
      IDM_MAINMENU_USER1;
      IDM_MAINMENU_USER2;
      IDM_MAINMENU_USER3;
      IDM_MAINMENU_USER4;
      IDM_MAINMENU_USER5;
    }
  }
  SUBMENU IDS_EDITOR_ABOUT
  {
    IDM_MAXONDOCS;
    PLUGIN_CMD_1025120;
    IDM_MAXONSUPPORT;
    IDM_MAXONTUTORIALS;
    PLUGIN_CMD_1050249; // QuickStart
    SEPARATOR;
    PLUGIN_CMD_450000220;
    PLUGIN_CMD_450000229;
    SEPARATOR;
    PLUGIN_CMD_200000208;
    IDM_PERSONALIZE; // License Manager
    PLUGIN_CMD_1051496; // Sign Out
    SEPARATOR;
    PLUGIN_CMD_200000264; // C4D Licenses.html
    IDM_UEBER;
    SEPARATOR;
    PLUGIN_CMD_300001038;
  }
}
MENU M_EDITOR_USER2
{
	SUBMENU IDS_EDITOR_FILE
	{
    PLUGIN_CMD_200000204; // Quit and Sign Out
		IDM_BEENDEN;
	}
	SUBMENU IDS_LAYOUT
	{
		IDM_CM_NEWPALETTE;
		IDM_CM_GROUPWINDOW;
		IDM_LOADPALETTE;
		IDM_CM_CUSTOMIZE;
		IDM_LOCK_LAYOUT;
		SEPARATOR;
		IDM_LOADLAYOUT;
		IDM_SAVELAYOUT;
		IDM_SAVELAYOUTAS;
		SEPARATOR;
		PLUGIN_CMD_300000186;
		M_COFFEEMANAGER_MENUMANAGER;
		SEPARATOR;
		SUBMENU IDS_MENU_LAYOUTS
		{
			IDM_DEFAULT_LAYOUTS;
		}
		SUBMENU IDS_MENU_MENUS
		{
			IDM_MAINMENU_C4D;
			IDM_MAINMENU_BP;
			IDM_MAINMENU_USER1;
			IDM_MAINMENU_USER2;
			IDM_MAINMENU_USER3;
			IDM_MAINMENU_USER4;
			IDM_MAINMENU_USER5;
		}
	}
  SUBMENU IDS_EDITOR_ABOUT
  {
    IDM_MAXONDOCS;
    PLUGIN_CMD_1025120;
    IDM_MAXONSUPPORT;
    IDM_MAXONTUTORIALS;
    PLUGIN_CMD_1050249; // QuickStart
    SEPARATOR;
    PLUGIN_CMD_450000220;
    PLUGIN_CMD_450000229;
    SEPARATOR;
    PLUGIN_CMD_200000208;
    IDM_PERSONALIZE; // License Manager
    PLUGIN_CMD_1051496; // Sign Out
    SEPARATOR;
    PLUGIN_CMD_200000264; // C4D Licenses.html
    IDM_UEBER;
    SEPARATOR;
    PLUGIN_CMD_300001038;
  }
}
MENU M_EDITOR_USER3
{
	SUBMENU IDS_EDITOR_FILE
	{
    PLUGIN_CMD_200000204; // Quit and Sign Out
		IDM_BEENDEN;
	}
	SUBMENU IDS_LAYOUT
	{
		IDM_CM_NEWPALETTE;
		IDM_CM_GROUPWINDOW;
		IDM_LOADPALETTE;
		IDM_CM_CUSTOMIZE;
		IDM_LOCK_LAYOUT;
		SEPARATOR;
		IDM_LOADLAYOUT;
		IDM_SAVELAYOUT;
		IDM_SAVELAYOUTAS;
		SEPARATOR;
		PLUGIN_CMD_300000186;
		M_COFFEEMANAGER_MENUMANAGER;
		SEPARATOR;
		SUBMENU IDS_MENU_LAYOUTS
		{
			IDM_DEFAULT_LAYOUTS;
		}
		SUBMENU IDS_MENU_MENUS
		{
			IDM_MAINMENU_C4D;
			IDM_MAINMENU_BP;
			IDM_MAINMENU_USER1;
			IDM_MAINMENU_USER2;
			IDM_MAINMENU_USER3;
			IDM_MAINMENU_USER4;
			IDM_MAINMENU_USER5;
		}
	}
  SUBMENU IDS_EDITOR_ABOUT
  {
    IDM_MAXONDOCS;
    PLUGIN_CMD_1025120;
    IDM_MAXONSUPPORT;
    IDM_MAXONTUTORIALS;
    PLUGIN_CMD_1050249; // QuickStart
    SEPARATOR;
    PLUGIN_CMD_450000220;
    PLUGIN_CMD_450000229;
    SEPARATOR;
    PLUGIN_CMD_200000208;
    IDM_PERSONALIZE; // License Manager
    PLUGIN_CMD_1051496; // Sign Out
    SEPARATOR;
    PLUGIN_CMD_200000264; // C4D Licenses.html
    IDM_UEBER;
    SEPARATOR;
    PLUGIN_CMD_300001038;
  }
}
MENU M_EDITOR_USER4
{
	SUBMENU IDS_EDITOR_FILE
	{
    PLUGIN_CMD_200000204; // Quit and Sign Out
		IDM_BEENDEN;
	}
	SUBMENU IDS_LAYOUT
	{
		IDM_CM_NEWPALETTE;
		IDM_CM_GROUPWINDOW;
		IDM_LOADPALETTE;
		IDM_CM_CUSTOMIZE;
		IDM_LOCK_LAYOUT;
		SEPARATOR;
		IDM_LOADLAYOUT;
		IDM_SAVELAYOUT;
		IDM_SAVELAYOUTAS;
		SEPARATOR;
		PLUGIN_CMD_300000186;
		M_COFFEEMANAGER_MENUMANAGER;
		SEPARATOR;
		SUBMENU IDS_MENU_LAYOUTS
		{
			IDM_DEFAULT_LAYOUTS;
		}
		SUBMENU IDS_MENU_MENUS
		{
			IDM_MAINMENU_C4D;
			IDM_MAINMENU_BP;
			IDM_MAINMENU_USER1;
			IDM_MAINMENU_USER2;
			IDM_MAINMENU_USER3;
			IDM_MAINMENU_USER4;
			IDM_MAINMENU_USER5;
		}
	}
  SUBMENU IDS_EDITOR_ABOUT
  {
    IDM_MAXONDOCS;
    PLUGIN_CMD_1025120;
    IDM_MAXONSUPPORT;
    IDM_MAXONTUTORIALS;
    PLUGIN_CMD_1050249; // QuickStart
    SEPARATOR;
    PLUGIN_CMD_450000220;
    PLUGIN_CMD_450000229;
    SEPARATOR;
    PLUGIN_CMD_200000208;
    IDM_PERSONALIZE; // License Manager
    PLUGIN_CMD_1051496; // Sign Out
    SEPARATOR;
    PLUGIN_CMD_200000264; // C4D Licenses.html
    IDM_UEBER;
    SEPARATOR;
    PLUGIN_CMD_300001038;
  }
}
MENU M_EDITOR_USER5
{
	SUBMENU IDS_EDITOR_FILE
	{
    PLUGIN_CMD_200000204; // Quit and Sign Out
		IDM_BEENDEN;
	}
	SUBMENU IDS_LAYOUT
	{
		IDM_CM_NEWPALETTE;
		IDM_CM_GROUPWINDOW;
		IDM_LOADPALETTE;
		IDM_CM_CUSTOMIZE;
		IDM_LOCK_LAYOUT;
		SEPARATOR;
		IDM_LOADLAYOUT;
		IDM_SAVELAYOUT;
		IDM_SAVELAYOUTAS;
		SEPARATOR;
		PLUGIN_CMD_300000186;
		M_COFFEEMANAGER_MENUMANAGER;
		SEPARATOR;
		SUBMENU IDS_MENU_LAYOUTS
		{
			IDM_DEFAULT_LAYOUTS;
		}
		SUBMENU IDS_MENU_MENUS
		{
			IDM_MAINMENU_C4D;
			IDM_MAINMENU_BP;
			IDM_MAINMENU_USER1;
			IDM_MAINMENU_USER2;
			IDM_MAINMENU_USER3;
			IDM_MAINMENU_USER4;
			IDM_MAINMENU_USER5;
		}
	}
  SUBMENU IDS_EDITOR_ABOUT
  {
    IDM_MAXONDOCS;
    PLUGIN_CMD_1025120;
    IDM_MAXONSUPPORT;
    IDM_MAXONTUTORIALS;
    PLUGIN_CMD_1050249; // QuickStart
    SEPARATOR;
    PLUGIN_CMD_450000220;
    PLUGIN_CMD_450000229;
    SEPARATOR;
    PLUGIN_CMD_200000208;
    IDM_PERSONALIZE; // License Manager
    PLUGIN_CMD_1051496; // Sign Out
    SEPARATOR;
    PLUGIN_CMD_200000264; // C4D Licenses.html
    IDM_UEBER;
    SEPARATOR;
    PLUGIN_CMD_300001038;
  }
}
