// C4D Menu Resource

MENU M_BRUSHPRESETS
{
  SUBMENU IDS_PAINT_FILE
  {
	  IDP_BRUSH_NEWLIB;
	  IDP_BRUSH_NEWFOLDER;
		IDP_BRUSH_IMPORT;
    SEPARATOR;
		IDP_BRUSH_SAVE;
		IDP_BRUSH_SAVEAS;
		IDP_BRUSH_EXPORTSELECTION;
  }
  SUBMENU IDS_PAINT_BRUSH_GROUP
  {
    IDP_BRUSH_GROUPS;
  }
  SUBMENU IDS_PAINT_BRUSH_VIEW
  {
    IDP_BRUSH_ASLIST;
    IDP_BRUSH_ASICON;
    SEPARATOR;
    IDP_BRUSH_SMALLICONS;
    IDP_BRUSH_MEDIUMICONS;
    IDP_BRUSH_LARGEICONS;
  }
}
