// C4D Menu Resource

MENU M_CONSOLE
{
  SUBMENU IDS_CONSOLE_ADVANCED
  {
    IDM_CLEARCONSOLE;
    SEPARATOR;
    PLUGIN_CMD_1040017; // logger settings
    PLUGIN_CMD_1001083; // command line
    IDM_CM_CLOSEWINDOW;
  }
}
