// C4D Menu Resource

MENU M_EDITOR_BP
{
	SUBMENU IDS_EDITOR_FILE
	{
		IDM_NEU;
		IDM_OEFFNE;
		IDM_HINZULADEN;
		IDM_REVERTFILE;
		SEPARATOR;
		IDM_CLOSESCENE;
		IDM_CLOSEALL;
		SEPARATOR;
		IDM_SPEICHERN;
		IDM_S_C4D5;
		IDM_SAVEINCREMENTAL;
		SEPARATOR;
		IDM_SAVEALL;
		IDM_MAKEPROJECT;
		PLUGIN_CMD_100004765;
		PLUGIN_CMD_100004841;
		SEPARATOR;
		IDP_TEXTURE_NEW;
		IDP_TEXTURE_OPEN;
		IDP_TEXTURE_MERGE;
		IDP_TEXTURE_REVERT;
		IDP_TEXTURE_CLOSE;
		IDP_CLOSEALLTEXTURES;
		SEPARATOR;
		IDP_TEXTURE_SAVE;
		IDP_TEXTURE_SAVEAS;
		IDP_TEXTURE_SAVECOPYAS;
		IDP_SAVEALLTEXTURES;
		SEPARATOR;
		PLUGIN_CMD_1000581;
		SEPARATOR;
		SUBMENU IDS_EDITOR_EXPORT
		{
			IDM_FILTER3D;
		}
		SUBMENU IDS_RECENT
		{
			IDM_RECENTFILES;
		}
		SEPARATOR;
		PLUGIN_CMD_200000204; // Quit and Sign Out
		IDM_BEENDEN;
	}
	SUBMENU IDS_EDITOR_EDIT
	{
		IDM_UNDO;
		IDM_REDO;
		IDP_UNDOPAINTER;
		SEPARATOR;
		IDM_CUT;
		IDM_COPY;
		IDP_COPY_MERGED;
		IDM_PASTE;
		IDP_PASTEINTO_SELECTION;
		IDM_DELETE;
		IDP_PAINT_FILLBITMAP;
		SEPARATOR;
		IDP_PAINT_DEFINEBRUSH;
		IDP_PAINT_DEFINECOLORSET;
		IDP_PAINT_DEFINEWALLPAPER;
		SEPARATOR;
		IDP_PAINT_TILEU;
		IDP_PAINT_TILEV;
		IDP_PREVIEW_MULTI;
		IDP_DISPLAYSINGLECHANNEL;
		SEPARATOR;
		IDM_DOC_PREFS;
		PLUGIN_CMD_1000474;
	}
	SUBMENU IDS_BPMENU_SELECTPOLYS
	{
		SUBMENU IDS_SELECTIONFILTER
		{
			IDM_SELECTIONFILTER;
		}
		SEPARATOR;
		PLUGIN_CMD_1011192;
		PLUGIN_CMD_1011180;
		PLUGIN_CMD_1011179;
		PLUGIN_CMD_1011178;
		PLUGIN_CMD_1012129;
		PLUGIN_CMD_1019730;
		PLUGIN_CMD_1053469; // Mirror Selection
		SEPARATOR;
		IDM_SEL_ALL;
		IDM_SEL_NONE;
		IDM_SEL_INVERT;
		SEPARATOR;
		IDM_SEL_CONNECTED;
		IDM_SEL_GROW;
		IDM_SEL_SHRINK;
		SEPARATOR;
		IDM_HIDESEL;
		IDM_HIDEUNSEL;
		IDM_UNHIDE;
		IDM_HIDEINVERT;
		SEPARATOR;
		PLUGIN_CMD_1011181;
		IDM_GENERATESELECTION;
		PLUGIN_CMD_431000169;
		IDM_SETVERTEX_FROM_SELECTION;
		SEPARATOR;
		PLUGIN_CMD_200000083;
		PLUGIN_CMD_200000084;
		PLUGIN_CMD_200000085;
		PLUGIN_CMD_200000086;
	}
	SUBMENU IDS_BPMENU_IMAGE
	{
		IDP_PAINT_SCALE;
		IDP_PAINT_CANVAS;
		IDP_PAINT_CROP;
		IDP_PAINT_ROTATE;
		IDP_PAINT_FLIPX;
		IDP_PAINT_FLIPY;
		SEPARATOR;
		IDP_CONVERTTOGRAY;
		IDP_CONVERTTORGB;
		SEPARATOR;
		IDP_CONVERTTO_UCHAR;
		IDP_CONVERTTO_UWORD;
		IDP_CONVERTTO_FLOAT;
		SEPARATOR;
		IDP_PAINT_ASSIGNPROFILE;
		IDP_PAINT_CONVERTTOPROFILE;
		SEPARATOR;
		IDP_BITMAPINFO;
	}
	SUBMENU IDS_BPMENU_LAYER
	{
		IDP_NEWLAYER;
		IDP_NEWLAYERSET;
		IDP_DUPLICATELAYER;
		IDP_CHANNEL_DELETE;
		SEPARATOR;
		IDP_MERGEDOWN;
		IDP_MERGELINKED;
		IDP_CHANNEL_FLATTEN_VISIBLE;
		IDP_CHANNEL_FLATTEN;
		SEPARATOR;
		IDP_CHANNEL_ADDLAYERMASK;
		IDP_LAYERMASKADDSELECTION;
		IDP_LAYERMASKSUBSELECTION;
		SEPARATOR;
		IDP_UVEDIT_FILLFACES;
		IDP_UVEDIT_OUTLINEFACES;
		IDP_UVEDIT_CREATEUVLAYER;
		SEPARATOR;
		IDP_NEWALPHACHANNEL;
	}
	SUBMENU IDS_BPMENU_SELECT
	{
		IDP_PAINT_SELECTALL;
		IDP_PAINT_DESELECTALL;
		IDP_PAINT_INVERSESELECTION;
		SEPARATOR;
		IDP_TOOL_SELECTCIRCLE;
		IDP_TOOL_SELECTRECT;
		IDP_TOOL_SELECTPOLYLINES;
		IDP_TOOL_SELECTFREEHAND;
		SEPARATOR;
		IDP_TOOL_MAGICWAND;
		IDP_TOOL_SELECTCOLORRANGE;
		SEPARATOR;
		IDP_FEATHER;
		IDP_GROWSELECTION;
		IDP_SHRINKSELECTION;
		SEPARATOR;
		IDP_SELECTIONFROMLAYER;
		IDP_SELECTIONFROMLAYERADD;
		IDP_SELECTIONFROMLAYERSUB;
		IDP_PAINT_CREATEMASKFROMSELECTION;
		SEPARATOR;
		IDP_PAINT_HIDEANTS;
		IDP_EDITMASK;
	}
	SUBMENU IDS_BPMENU_FITLER
	{
		IDP_EXECUTE_LASTFILTER;
		SEPARATOR;
		IDP_BITMAPFILTER;
	}
	SUBMENU IDS_BPMENU_UVEDIT
	{
		PLUGIN_CMD_1011168;
		SEPARATOR;
		PLUGIN_CMD_1038963;
		SEPARATOR;
		PLUGIN_CMD_1054357;
		PLUGIN_CMD_1054358;
		PLUGIN_CMD_465002126;
		SEPARATOR;
		PLUGIN_CMD_1030000; 
		PLUGIN_CMD_1053301; // UV Unwrap
		PLUGIN_CMD_1053312; // UV Weld and Relax
		PLUGIN_CMD_1053373; // UV Weld
		SEPARATOR;
		PLUGIN_CMD_1031207;
		IDP_UVEDIT_INTERACTIVE_START;
		IDP_UVEDIT_INTERACTIVE_STOP;
		SEPARATOR;
		PLUGIN_CMD_1011163;
		PLUGIN_CMD_1011169;
		IDP_UVEDIT_FITCANVASTOUV;
		SEPARATOR;
		IDP_UVEDIT_MIRRORX;
		IDP_UVEDIT_MIRRORY;
		PLUGIN_CMD_1019827;
		PLUGIN_CMD_1055207;
		PLUGIN_CMD_1055347;
		IDM_UVEDIT_ALIGN_ISLANDS;
		PLUGIN_CMD_1019830;
		PLUGIN_CMD_1021103;
		PLUGIN_CMD_1021131;
		SEPARATOR;
		PLUGIN_CMD_1011161;
		PLUGIN_CMD_1011162;
		IDP_UVEDIT_RESETUV;
		PLUGIN_CMD_1011166;
		PLUGIN_CMD_1011165;
		PLUGIN_CMD_1011164;
		IDP_UVEDIT_BAKE;
		IDP_UVEDIT_BAKE_RESTORE;
		IDP_UVEDIT_REMAP;
	}
	SUBMENU IDS_PAINT_TOOLSMAIN
	{
		SUBMENU IDS_BPMENU_PAINTTOOLS
		{
			IDP_3DPAINT;
			SEPARATOR;
			IDP_TOOL_MOVELAYER;
			IDP_TOOL_MAGNIFY;
			SEPARATOR;
			IDP_TOOL_PICKUP;
			IDP_TOOL_BRUSH;
			IDP_TOOL_CLONE;
			IDP_TOOL_ERASER;
			IDP_TOOL_SMEAR;
			IDP_TOOL_DODGE;
			IDP_TOOL_BURN;
			IDP_TOOL_SPONGE;
			IDP_TOOL_BLUR;
			IDP_TOOL_SHARPEN;
			IDP_TOOL_HSV;
			SEPARATOR;
			IDP_TOOL_FILLBITMAP;
			IDP_TOOL_GRADIENT;
			IDP_TOOL_TRANSFORMBITMAP;
			SEPARATOR;
			IDP_TOOL_DRAWLINE;
			IDP_TOOL_DRAWTEXT;
			IDP_TOOL_POLYGONSHAPE;
			SEPARATOR;
			IDP_PAINT_BRUSH_SIZE_INC;
			IDP_PAINT_BRUSH_SIZE_DEC;
			IDP_PAINT_BRUSH_HARDNESS_INC;
			IDP_PAINT_BRUSH_HARDNESS_DEC;
			IDP_PAINT_BRUSH_PRESSURE_INC;
			IDP_PAINT_BRUSH_PRESSURE_DEC;
			IDP_PAINT_BRUSH_ROTATION_CLOCKWISE;
			IDP_PAINT_BRUSH_ROTATION_COUNTERCLOCKWISE;
		}
		SUBMENU IDS_BPMENU_UVTOOLS
		{
			PLUGIN_CMD_17038;
			PLUGIN_CMD_17039;
			SEPARATOR;
			PLUGIN_CMD_200000083;
			PLUGIN_CMD_200000084;
			PLUGIN_CMD_200000085;
			PLUGIN_CMD_200000086;
			SEPARATOR;
			PLUGIN_CMD_200000088;
			PLUGIN_CMD_200000089;
			IDM_UVEDIT_SCALE;
			PLUGIN_CMD_200000090;
			SEPARATOR;
			IDM_UVEDIT_SHEAR;
			IDM_UVEDIT_TAPER;
			IDM_UVEDIT_MAGNET;
			SEPARATOR;
			IDM_UVEDIT_UVGIZMO;
		}
		SUBMENU IDS_BPMENU_C4DTOOLS
		{
			PLUGIN_CMD_200000088;
			PLUGIN_CMD_200000089;
			PLUGIN_CMD_200000090;
			IDM_LUPE;
			SEPARATOR;
			PLUGIN_CMD_200000083;
			PLUGIN_CMD_200000084;
			PLUGIN_CMD_200000085;
			PLUGIN_CMD_200000086;
			SEPARATOR;
			PLUGIN_CMD_12100;
			PLUGIN_CMD_12101;
			PLUGIN_CMD_12139;
			PLUGIN_CMD_16351;
			PLUGIN_CMD_12187;
			IDM_ACHSEN;
			PLUGIN_CMD_12298;
			PLUGIN_CMD_12184;
			PLUGIN_CMD_17038;
			PLUGIN_CMD_17039;
			SEPARATOR;
			IDM_X;
			IDM_Y;
			IDM_Z;
			IDM_WELT;
			SEPARATOR;
			IDM_USE_ANIMATION;
			IDM_USE_EXPRESSIONS;
			IDM_USE_GENERATORS;
			IDM_USE_DEFORMERS;
		}
		SUBMENU IDS_EDITOR_OBJECTS
		{
			PLUGIN_CMD_5140;
			PLUGIN_CMD_1007455;
			PLUGIN_CMD_5142;
			SEPARATOR;
			PLUGIN_CMD_5159;
			PLUGIN_CMD_5170;
			PLUGIN_CMD_5160;
			PLUGIN_CMD_5168;
			PLUGIN_CMD_5162;
			SEPARATOR;
			PLUGIN_CMD_5103;
			IDM_CAMERATARGET;
			IDM_CAMERASTEREO;
			PLUGIN_CMD_5102;
			IDM_LIGHTSPOT;
			IDM_LIGHTINFINITE;
			IDM_LIGHTAREA;
			IDM_LIGHTTARGET;
		}
		SUBMENU IDS_EDITOR_STRUCTURE
		{
			IDM_MAKEFLAECHEN;
			SEPARATOR;
			IDM_MODELING_ALIGNNORMALS;
			IDM_MODELING_REVERSENORMALS;
			IDM_MODELING_OPTIMIZE;
			IDM_MODELING_TRIANGULATE;
			IDM_MODELING_UNTRIANGULATE;
		}
		SEPARATOR;
		IDP_PAINT_SETUPWIZARD;
		SEPARATOR;
		IDP_PROJECTIONPAINT;
		IDP_PROJECTIONPAINT_APPLY;
		IDP_PROJECTIONPAINT_DISCARD;
		IDP_PROJECTIONPAINT_RELEASE_PLANE;
		IDP_PROJECTIONPAINT_PROJECTBACK;
		SEPARATOR;
		IDP_TOGGLE_FGBG;
	}
	SUBMENU IDS_EDITOR_RENDER
	{
		IDM_RENDERALL;
		IDM_RENDERAUSSCHNITT;
		PLUGIN_CMD_430000021;
		IDM_RENDERAKTU;
		SEPARATOR;
		IDM_RAYTRACING;
		PLUGIN_CMD_300002144;
		SUBMENU IDS_MENU_TAKES
		{
			PLUGIN_CMD_431000067;
			PLUGIN_CMD_431000068;
			PLUGIN_CMD_431000095;
			PLUGIN_CMD_431000096;
		}
		PLUGIN_CMD_1000974;
		SEPARATOR;
		PLUGIN_CMD_465003525;
		PLUGIN_CMD_465003500;
		SEPARATOR;
		PLUGIN_CMD_12161;
		IDM_RENDERSETTINGS;
		SEPARATOR;
		PLUGIN_CMD_300002136;
		PLUGIN_CMD_300002167;
		SEPARATOR;
		SUBMENU IDS_MENU_NODE_SPACES
		{
			IDM_NODE_SPACES;
		}
		SEPARATOR;
		IDM_FLUSHSOLUTIONS;
		SEPARATOR;
		PLUGIN_CMD_1011133;
		PLUGIN_CMD_450000051;
	}
	SUBMENU IDS_EDITOR_PIPELINE
	{
		PLUGIN_CMD_12305;
		PLUGIN_CMD_300000116;
		PLUGIN_CMD_1001084;
		SUBMENU IDS_SUBMENU_TOOLS
		{
			IDM_EXECUTE_LAST;
			SEPARATOR;
			PLUGIN_CMD_1026375;
			SEPARATOR;
			PLUGIN_CMD_1023699;
			PLUGIN_CMD_1024490;
			SEPARATOR;
			PLUGIN_CMD_300002005; // Export License Overview
		}
		SEPARATOR;
		SUBMENU IDS_SCRIPTS
		{
			PLUGIN_CMD_1022807;
			PLUGIN_CMD_1022735;
			SEPARATOR;
			PLUGIN_CMD_65000;
		}	
		SEPARATOR;
		PLUGIN_CMD_465001955;
		PLUGIN_CMD_1032090;
		PLUGIN_CMD_1026593;
		PLUGIN_CMD_1039096;
		PLUGIN_CMD_1040642; // Moves by Maxon
		SUBMENU IDS_HOUDINI_ENGINE
		{
			PLUGIN_CMD_1032268;
			SEPARATOR;
		}
		SUBMENU IDS_SUBSTANCE_ENGINE
		{
			PLUGIN_CMD_1032109;
			PLUGIN_CMD_1032108;
		}
		SUBMENU IDS_ZYNC
		{
			PLUGIN_CMD_1039086;
			SEPARATOR;
			PLUGIN_CMD_1039093;
			PLUGIN_CMD_1039094;
			PLUGIN_CMD_1039095;
		}
		SUBMENU IDS_GOZ_BRIDGE
		{
			PLUGIN_CMD_1054230;
			PLUGIN_CMD_1053946;
			PLUGIN_CMD_1054167;
		}
		SUBMENU IDS_USD_BRIDGE
		{
			PLUGIN_CMD_1055413;
			PLUGIN_CMD_1055414;
		}
		SEPARATOR;
		IDM_PLUGINS;
	}
	SUBMENU IDS_EDITOR_WINDOW
	{
		SUBMENU IDS_LAYOUT
		{
			PLUGIN_CMD_300000186;
			SEPARATOR;
			SUBMENU IDS_MENU_MENUS
			{
				IDM_MAINMENU_C4D;
				IDM_MAINMENU_BP;
				IDM_MAINMENU_USER1;
				IDM_MAINMENU_USER2;
				IDM_MAINMENU_USER3;
				IDM_MAINMENU_USER4;
				IDM_MAINMENU_USER5;
			}
			M_COFFEEMANAGER_MENUMANAGER;
			SEPARATOR;
			SUBMENU IDS_MENU_LAYOUTS
			{
				IDM_DEFAULT_LAYOUTS;
			}
			IDM_LOADLAYOUT;
			IDM_SAVELAYOUT;
			IDM_SAVELAYOUTAS;
			IDM_LOCK_LAYOUT;
			SEPARATOR;
			IDM_CM_GROUPWINDOW;
			IDM_CM_NEWPALETTE;
			SEPARATOR;
			IDM_LOADPALETTE;
			IDM_CM_CUSTOMIZE;
			SEPARATOR;
			PLUGIN_CMD_202549;
		}
		SEPARATOR;
		IDM_FULLSCREEN;
		IDM_FULLSCREEN_GROUP;
		SEPARATOR;
		PLUGIN_CMD_1017163;
		PLUGIN_CMD_431000053;
		PLUGIN_CMD_100004700;
		IDM_MATERIAL_MANAGER;
		PLUGIN_CMD_1001072;
		PLUGIN_CMD_465002211;
		PLUGIN_CMD_465001541;
		PLUGIN_CMD_465001542;
		SEPARATOR;
		PLUGIN_CMD_1000468;
		IDM_INFO_MANAGER;
		PLUGIN_CMD_100004704;
		PLUGIN_CMD_1024015;
		IDM_SPREADSHEET;
		PLUGIN_CMD_1029486;
		SEPARATOR;
		PLUGIN_CMD_430000700;
		PLUGIN_CMD_200000045;
		IDM_NEWVIEW;
		SEPARATOR;
		SUBMENU IDS_PAINT_PAINTER
		{
			IDP_COLORSETTINGS;
			IDP_BRUSHPRESETS;
			IDP_COLORPRESETS;
			IDP_TEXTUREMANAGER;
			IDP_NEWTEXTUREVIEW;
		}
		SUBMENU IDS_MOREMANAGER
		{
			PLUGIN_CMD_100004701;
			PLUGIN_CMD_100004702;
			PLUGIN_CMD_100004703;
			PLUGIN_CMD_465001510;
			PLUGIN_CMD_465001511;
			PLUGIN_CMD_465001512;
			PLUGIN_CMD_465001513;
			PLUGIN_CMD_465001737;
		}
		SEPARATOR;
		PLUGIN_CMD_200000149;
		PLUGIN_CMD_1026761;
		PLUGIN_CMD_1026791;
		SEPARATOR;
		IDM_DOCUMENTS;
	}
	SUBMENU IDS_EDITOR_ABOUT
	{
		IDM_SHOWONLINEHELP;
		PLUGIN_CMD_1025120;
		IDM_MAXONSUPPORT;
		IDM_MAXONTUTORIALS;
		PLUGIN_CMD_1050249; // QuickStart
		SEPARATOR;
		PLUGIN_CMD_450000220;
		PLUGIN_CMD_450000229;
		SEPARATOR;
		PLUGIN_CMD_200000208;
		IDM_PERSONALIZE; // License Manager
		PLUGIN_CMD_1051496; // Sign Out
		SEPARATOR;
		PLUGIN_CMD_200000264; // C4D Licenses.html
		IDM_UEBER;
		SEPARATOR;
		PLUGIN_CMD_300001038;
	}
}
