// C4D Menu Resource

MENU M_VIEWPOPUP
{
  IDM_UNDO;
  IDM_SHOWACTIVE;
  IDM_SHOWSCENE;
  SEPARATOR;
  IDM_MAKEFLAECHEN;
  IDM_TAKEANIM;
  PLUGIN_CMD_100004772;
  IDM_VERBINDEN;
  IDM_CONNECTANDDELETE;
  IDM_BAKEASALEMBIC;
  IDM_BAKEASALEMBICDELETE;
  SEPARATOR;
  SUBMENU IDS_TAGSUBMENU
  {
    PLUGIN_CMD_100004788;
  }
  SUBMENU IDS_RESTORESELECTION
  {
    IDM_LISTSELECTIONS;
  }
  SEPARATOR;
  IDM_SELECTCHILDS;
  IDM_SHOWINTIMELINE;
  IDM_SHOWFCURVES;
  IDM_SHOWINMOTION;
  SEPARATOR;
  PLUGIN_CMD_1019940;
}
