// C4D Menu Resource

MENU M_COLORPRESETS
{
  SUBMENU IDS_PAINT_FILE
  {
	  IDP_COLOR_NEWLIB;
	  IDP_COLOR_NEWFOLDER;
		IDP_COLOR_IMPORT;
    SEPARATOR;
		IDP_COLOR_EXPORTSELECTION;
  }
  SUBMENU IDS_PAINT_COLOR_GROUP
  {
    IDP_COLOR_GROUPS;
  }
  SUBMENU IDS_PAINT_COLOR_VIEW
  {
    IDP_COLOR_ASLIST;
    IDP_COLOR_ASICON;
    SEPARATOR;
    IDP_COLOR_SMALLICONS;
    IDP_COLOR_MEDIUMICONS;
    IDP_COLOR_LARGEICONS;
  }
}
