// C4D-DialogResource
DIALOG vmapmanager
{
  NAME IDS_DIALOG; SCALE_V; SCALE_H; 
  
  GROUP ID_VM_OPERATIONSGROUP
  {
    NAME IDS_STATIC4; SCALE_V; SCALE_H; 
    BORDERSTYLE BORDER_THIN_IN; BORDERSIZE 4, 4, 4, 4; 
    COLUMNS 1;
    SPACE 4, 4;
    
    GROUP IDC_STATIC
    {
      NAME IDS_STATIC8; ALIGN_TOP; SCALE_H; 
      BORDERSIZE 0, 0, 0, 0; 
      COLUMNS 2;
      SPACE 4, 4;
      
      STATICTEXT IDC_STATIC { NAME IDS_STATIC1; CENTER_V; ALIGN_LEFT; }
      LINK ID_VM_SOURCELINK
      {
        ALIGN_TOP; SCALE_H; 
      }
      STATICTEXT IDC_STATIC { NAME IDS_STATIC2; CENTER_V; ALIGN_LEFT; }
      LINK ID_VM_TARGETLINK
      {
        ALIGN_TOP; SCALE_H; 
      }
    }
    SEPARATOR { SCALE_H; }
    GROUP ID_VM_VTYPESGROUP
    {
      NAME IDS_STATIC3; ALIGN_TOP; SCALE_H; 
      BORDERSTYLE BORDER_THIN_IN; BORDERSIZE 4, 4, 4, 4; 
      COLUMNS 2;
      SPACE 4, 4;
      
      
    }
    SEPARATOR { SCALE_H; }
    GROUP IDC_STATIC
    {
      NAME IDS_STATIC6; ALIGN_TOP; SCALE_H; 
      BORDERSIZE 0, 0, 0, 0; 
      COLUMNS 2;
      SPACE 4, 4;
      
      STATICTEXT IDC_STATIC { NAME IDS_STATIC5; CENTER_V; ALIGN_RIGHT; }
      COMBOBOX ID_VM_TRANSFERMETHOD
      {
        ALIGN_TOP; SCALE_H; SIZE 150, 0; 
        CHILDS
        {
          4, IDS_TRANSMODENS; 
          3, IDS_TRANSMODENP; 
          0, IDS_TRANSMODENORM; 
          1, IDS_TRANSMODESOURCEAXIS; 
          2, IDS_TRANSMODETARGETAXIS; 
        }
      }
      STATICTEXT IDC_STATIC { NAME IDS_STATIC9; CENTER_V; ALIGN_LEFT; }
      COMBOBOX ID_VM_FLIPDIRECTION
      {
        ALIGN_TOP; SCALE_H; SIZE 150, 0; 
        CHILDS
        {
          0, IDS_FLIPDIRECTION_OFF; 
          1, IDS_FLIPDIRECTION_YZ; 
          2, IDS_FLIPDIRECTION_XZ; 
          3, IDS_FLIPDIRECTION_XY; 
        }
      }
      STATICTEXT IDC_STATIC { NAME IDS_STATIC10; CENTER_V; ALIGN_LEFT; }
      COMBOBOX ID_VM_SPACE
      {
        ALIGN_TOP; SCALE_H; SIZE 150, 0; 
        CHILDS
        {
          0, IDS_VMSPACE_LOCAL; 
          1, IDS_VMSPACE_GLOBAL; 
        }
      }
    }
    SEPARATOR { SCALE_H; }
    BUTTON ID_VM_TRANSFERBUTTON { NAME IDS_BUTTON2; SCALE_H; }
  }
}
