// C4D-DialogResource
DIALOG IDD_NEW_CITY_DIALOG
{
  NAME IDS_NEW_CITY_DIALOG; CENTER_V; SCALE_H; 
  
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC; ALIGN_TOP; SCALE_H; 
    BORDERSTYLE BORDER_NONE; BORDERSIZE 0, 0, 0, 0; 
    COLUMNS 2;
    
    STATICTEXT IDC_STATIC { NAME IDS_NEW_CITY_NAME; CENTER_V; ALIGN_LEFT; }
    EDITTEXT IDD_NEW_CITY_NAME_EDIT
    { CENTER_V; SCALE_H; SIZE 70, 0; }
    STATICTEXT IDC_STATIC { NAME IDS_NEW_CITY_COUNTRY; CENTER_V; ALIGN_LEFT; }
    EDITTEXT IDD_NEW_CITY_COUNTRY_EDIT
    { CENTER_V; SCALE_H; SIZE 70, 0; }
    STATICTEXT IDC_STATIC { NAME IDS_NEW_CITY_CONTINENT; CENTER_V; ALIGN_LEFT; }
    EDITTEXT IDD_NEW_CITY_CONTINENT_EDIT
    { CENTER_V; SCALE_H; SIZE 70, 0; }
  }
  DLGGROUP { OK; CANCEL; }
}