CONTAINER OCloud
{
	NAME OCloud;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		BOOL SKY_CLOUD_OVERRIDE_GROUP { }

		BOOL SKY_CLOUD_GENERATOR_FLAG { }
		REAL SKY_CLOUD_MIX { CUSTOMGUI REALSLIDER; UNIT PERCENT; MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100; }

		REAL SKY_CLOUD_ALTITUDE { UNIT METER; MIN 0; }
		REAL SKY_CLOUD_FALLOFF { UNIT METER; MIN 0; }
		REAL SKY_CLOUD_LUM_FALLOFF { UNIT METER; MIN 0; }
		REAL SKY_CLOUD_TRANS_FALLOFF { UNIT METER; MIN 0; }
		COLOR SKY_CLOUD_COLOR { }
		BOOL SKY_CLOUD_HQ_LIGHTING { }
		SPLINE SKY_CLOUD_OBJECT_FALLOFF { }
		REAL SKY_CLOUD_OFFSET_DIST { UNIT METER; MIN 0; }
		BOOL SKY_CLOUD_KEEP_SHAPE { }

		LONG SKY_CLOUD_TYPE
		{
			CYCLE
			{
				SKY_CLOUD_TYPE_STANDARD;
				SKY_CLOUD_TYPE_ACPERL;
				SKY_CLOUD_TYPE_ACLENTI;
				SKY_CLOUD_TYPE_CBCAPINC;
			}
		}
		REAL SKY_CLOUD_COVERAGE { CUSTOMGUI REALSLIDER; UNIT PERCENT; MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100; }
		REAL SKY_CLOUD_CONTRAST { CUSTOMGUI REALSLIDER; UNIT PERCENT; MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100; }
		REAL SKY_CLOUD_SIZE_RATIO { CUSTOMGUI REALSLIDER; UNIT PERCENT; MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100; }
		REAL SKY_CLOUD_GROOVE_DEPTH { UNIT PERCENT; MIN 0; }
		REAL SKY_CLOUD_SHAPE_STRENGTH { CUSTOMGUI REALSLIDER; UNIT PERCENT; MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100; }
		VECTOR SKY_CLOUD_SCALE { UNIT PERCENT; MIN 1; }
		
		STATICTEXT SKY_CLOUD_GRID_POINTS { SCALE_H; }
	}
}
