CONTAINER Oskyshader
{
	INCLUDE Obase;
	NAME Oskyshader;

	GROUP Obaselist
	{
		HIDE ID_BASEOBJECT_SHADEDWIRECOLORMODE;
		HIDE ID_BASEOBJECT_SHADEDWIRECOLOR;
		HIDE ID_BASEOBJECT_XRAY;
		SEPARATOR { LINE; }

		GROUP
		{
			COLUMNS 2;
			BUTTON SKY_PRESET { }
			BUTTON SKY_WEATHERPRESET { }
		}

		SEPARATOR { LINE; }

		MATEDCOLUMNS 1;

		BOOL SKY_TIMEANDLOCATION { PAGE; HIDDEN; PARENTMSG ID_SKY_GROUP_DATE_TIME; }
		BOOL SKY_PHYSICALSKYPAGE { PARENTMSG ID_SKY_GROUP_PHYSICAL_SKY; }
		BOOL SKY_PHYSICAL_SUN_ENABLE { PARENTMSG ID_SKY_GROUP_PHYSICAL_SUN; }
		BOOL SKY_PHYSICAL_ATM_ENABLE { PARENTMSG ID_SKY_GROUP_PHYSICAL_ATM; }
		BOOL SKY_CLOUD_ENABLE { PARENTMSG ID_SKY_GROUP_CLOUDS; } 
		BOOL SKY_DETAILS { PAGE; HIDDEN; PARENTMSG ID_SKY_GROUP_GENERAL; }

		SEPARATOR SKY_LEFT_SEPARATOR { LINE; }

		BOOL SKY_VOL_CLOUDS_RENDER { PARENTMSG ID_SKY_GROUP_VOL_CLOUDS; }
		BOOL SKY_FOG_ENABLE { PARENTMSG ID_SKY_GROUP_FOG; }
		BOOL SKY_RAINBOW_RENDER { PARENTMSG ID_SKY_GROUP_RAINBOW; }
		BOOL SKY_BEAMS_ENABLE { PARENTMSG ID_SKY_GROUP_SUNBEAMS; }
		BOOL SKY_OBJECTS { PARENTMSG ID_SKY_GROUP_SKY_OBJECTS; }
	}

	GROUP ID_SKY_GROUP_DATE_TIME
	{
		DATETIME SKY_DATE_TIME { PARENTCOLLAPSE; NOW_BUTTON; ANIM MIX; OPEN; }
		BOOL SKY_TIME_NOW { ANIM OFF; PARENTCOLLAPSE SKY_DATE_TIME; }
		BOOL SKY_DATE_TODAY { ANIM OFF; PARENTCOLLAPSE SKY_DATE_TIME;  } 
		BOOL SKY_DATE_ANIMATE { ANIM OFF; PARENTCOLLAPSE SKY_DATE_TIME; }
		BOOL SKY_TIME_ANIMATE { ANIM OFF; PARENTCOLLAPSE SKY_DATE_TIME; }

		SEPARATOR { LINE; }

		STRING SKY_POS_CITY { HIDDEN; }
		LONG SKY_POS_CITY_COMBO
		{
			PARENTCOLLAPSE;
			CUSTOMGUI SKY_II_CITYLIST;
			ANIM OFF;
		}
		REAL SKY_POS_LATITUDE { UNIT DEGREE; CUSTOMGUI LONG_LAT; ANIM MIX; MIN -90; MAX 90; PARENTCOLLAPSE SKY_POS_CITY_COMBO; }
		REAL SKY_POS_LONGITUDE { UNIT DEGREE; CUSTOMGUI LONG_LAT; ANIM MIX; LONGITUDE; MIN -180; MAX 180; PARENTCOLLAPSE SKY_POS_CITY_COMBO; }
		LONG SKY_POS_TIMEZONE
		{
			PARENTCOLLAPSE SKY_POS_CITY_COMBO;
			CYCLE
			{
				SKY_POS_TZ_OS;
				SKY_POS_TZ_CUSTOM;
			}
		}
		LONG SKY_POS_DST_SETTINGS
		{ 
			PARENTCOLLAPSE SKY_POS_CITY_COMBO;
			CYCLE
			{
				SKY_POS_DST_OFF;
				SKY_POS_DST_LAST_MARCH_LAST_OCT;
				SKY_POS_DST_SECOND_MARCH_FIRST_NOV;
				SKY_POS_DST_FIRST_APR_LAST_OCT;
				SKY_POS_DST_FIRST_OCT_LAST_MARCH;
				SKY_POS_DST_LAST_OCT_LAST_MARCH;
			}
		}
		REAL SKY_POS_TIME_ZONE { PARENTCOLLAPSE SKY_POS_CITY_COMBO; }
		REAL SKY_POS_DST_TIME_ZONE { PARENTCOLLAPSE SKY_POS_CITY_COMBO; }
	}

	GROUP ID_SKY_GROUP_PHYSICAL_SKY
	{
		BOOL SKY_PHYSICAL_SKY_ENABLE 			{ }
		BOOL SKY_REAL_SKY_SKY_HORIZON			{ }
		REAL SKY_REAL_SKY_SKY_COLOR_WARMNESS		{ UNIT PERCENT; MIN 0.0; MAX 100.0; MAXSLIDER 100.0; }
		REAL SKY_REAL_SKY_SKY_INTENSITY			{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 10000.0; }
		REAL SKY_REAL_SKY_SKY_INTENSITY_NIGHT		{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 10000.0; }
		REAL SKY_REAL_SKY_SKY_SATURATION		{ UNIT PERCENT; MIN 0.0; MAX 200.0; MAXSLIDER 200.0; }
		REAL SKY_REAL_SKY_SKY_HUE			{ UNIT PERCENT; MIN 0.0; MAX 100.0; } 
		REAL SKY_REAL_SKY_SKY_GAMMA			{ UNIT REAL; MIN 0.1; MAX 10.0; MINSLIDER 0.1; MAXSLIDER 10.0; STEP 0.01; }
		REAL SKY_REAL_SKY_SKY_SEEN_INTENSITY		{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 10000.0; }
		REAL SKY_REAL_SKY_SKY_DITHER			{ UNIT PERCENT; MIN 0.0; MAX 100.0; MAXSLIDER 100.0; }

		SEPARATOR { LINE; }

		REAL SKY_REAL_SKY_TURBIDITY 			{ UNIT REAL; MIN 2.0; MAX 32.0; MAXSLIDER 32.0; STEP 0.1; }
		REAL SKY_REAL_SKY_OZONE    			{ UNIT REAL; MIN 0.0; MAX 50.0; MAXSLIDER 50.0; STEP 0.1; }
		
		SEPARATOR { LINE; }

		BOOL SKY_GENERAL_USER_HORIZON 			{ }
		REAL SKY_GENERAL_USER_HORIZON_MAX_ALT 		{ UNIT DEGREE; MIN 0; MAX 90; }
		GRADIENT SKY_GENERAL_USER_COLOR 		{ PARENTID SKY_GENERAL_USER_HORIZON; COLOR; ICC_BASEDOCUMENT; }

		SEPARATOR { LINE; }

		REAL SKY_GENERAL_STRENGTH			{ UNIT PERCENT; MIN 0; MAX 100; }
		REAL SKY_GENERAL_MOISTURE 			{ UNIT PERCENT; MIN 0; MAX 100; }
		REAL SKY_GENERAL_HORIZON_START 			{ UNIT DEGREE; MIN -89; MAX 89; }
		REAL SKY_GENERAL_EARTH_RADIUS 			{ MIN 10; }
	}

	GROUP ID_SKY_GROUP_PHYSICAL_SUN
	{
		COLOR SKY_REAL_SKY_SUN_COLOR			{ ANIM OFF; }

		SEPARATOR { LINE; }

		REAL SKY_REAL_SKY_SUN_INTENSITY			{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 10000.0; }
		REAL SKY_REAL_SKY_SUN_SATURATION		{ UNIT PERCENT; MIN 0.0; MAX 200.0; MAXSLIDER 200.0; }
		REAL SKY_REAL_SKY_SUN_HUE			{ UNIT PERCENT; MIN 0.0; MAX 100.0; } 
		REAL SKY_REAL_SKY_SUN_GAMMA			{ UNIT REAL; MIN 0.1; MAX 10.0; MINSLIDER 0.1; MAXSLIDER 10.0; STEP 0.01; }
		REAL SKY_REAL_SKY_SUN_SIZE_RATIO		{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 10000.0; }
		REAL SKY_REAL_SKY_SUN_SEEN_INTENSITY		{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 10000.0; }
		
		SEPARATOR { LINE; }
		BOOL SKY_GENERAL_CHANGE_SUN_COL { }
		COLOR SKY_GENERAL_SUN_COLOR { PARENTID SKY_GENERAL_CHANGE_SUN_COL; }

		SEPARATOR { LINE; }

		BOOL SKY_GENERAL_LENSFLARES { PARENTCOLLAPSE; }
		REAL SKY_GENERAL_MAX_FLARE_GLOW { PARENTCOLLAPSE SKY_GENERAL_LENSFLARES; UNIT PERCENT; MIN 0; MAX 100; }
		REAL SKY_GENERAL_MAX_FLARE_REFL { PARENTCOLLAPSE SKY_GENERAL_LENSFLARES; UNIT PERCENT; MIN 0; MAX 100; }
		
		REAL SKY_GENERAL_SUN_DIST_SCALE { UNIT PERCENT; MIN 0; MINSLIDER 0; MAXSLIDER 100; STEP 0.01; }
		LINK SKY_OBJECT_SUN_OBJECT { }

		GROUP SKY_GROUP_PHYSICAL_SUN_SHADOW
		{
			DEFAULT 1;
			LONG SKY_REAL_SKY_SUN_SHADOW_TYPE
			{
				CYCLE
				{
					SKY_SUN_SHADOW_TYPE_NONE;
					SKY_SUN_SHADOW_TYPE_HARD;
					SKY_SUN_SHADOW_TYPE_AREA;
				}
			}
			SEPARATOR { LINE; }
			REAL SKY_REAL_SKY_SUN_SHADOW_DENSITY		{ UNIT PERCENT; MIN 0.0; MAX 10000.0; }
			COLOR SKY_REAL_SKY_SUN_SHADOW_COLOR		{ }
			BOOL SKY_REAL_SKY_SUN_SHADOW_TRANSPARENCY 	{ }
			SEPARATOR { LINE; }
			REAL SKY_REAL_SKY_SUN_SAMPLING_QUALITY		{ MIN 0.0; MAX 100.0; UNIT PERCENT; }
			LONG SKY_REAL_SKY_SUN_SAMPLING_SAMPLES_MIN	{ MIN 1; MAX 16384; MINSLIDER 1; MAXSLIDER 4096; STEP 4; }
			LONG SKY_REAL_SKY_SUN_SAMPLING_SAMPLES_MAX	{ MIN 4; MAX 16384; MINSLIDER 4; MAXSLIDER 4096; STEP 16; }
		}		
	}

	GROUP ID_SKY_GROUP_PHYSICAL_ATM
	{
		REAL SKY_REAL_SKY_ATM_INTENSITY			{ UNIT PERCENT; MIN 0.0; MAX 1000.0; MAXSLIDER 1000.0; }
		REAL SKY_REAL_SKY_ATM_HORIZON			{ UNIT PERCENT; MIN 0.0; MAX 100.0; MAXSLIDER 100.0; }
		REAL SKY_REAL_SKY_ATM_SATURATION		{ UNIT PERCENT; MIN 0.0; MAX 200.0; MAXSLIDER 200.0; }
		REAL SKY_REAL_SKY_ATM_HUE			{ UNIT PERCENT; MIN 0.0; MAX 100.0; } 
		REAL SKY_REAL_SKY_ATM_GAMMA			{ UNIT REAL; MIN 0.1; MAX 10.0; MINSLIDER 0.1; MAXSLIDER 10.0; STEP 0.01; }
		REAL SKY_REAL_SKY_ATM_SCALE_RATIO		{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 10000.0; }
		REAL SKY_REAL_SKY_ATM_DITHER			{ UNIT PERCENT; MIN 0.0; MAX 100.0; MAXSLIDER 100.0; }
	}

	GROUP ID_SKY_GROUP_CLOUDS
	{
		GROUP
		{
			GRADIENT SKY_CLOUD_ROLLOFF { ALPHA; ICC_BASEDOCUMENT; NOPRESETS; }
			BOOL SKY_CLOUDS_SHADOW { }
		}

		SEPARATOR { LINE; }
		
		GROUP
		{
			COLUMNS 3;
			BOOL SKY_CLOUD_1_ACTIVE { }
			BOOL SKY_CLOUD_2_ACTIVE { }
			BOOL SKY_CLOUD_3_ACTIVE { }
			BOOL SKY_CLOUD_4_ACTIVE { }
			BOOL SKY_CLOUD_5_ACTIVE { }
			BOOL SKY_CLOUD_6_ACTIVE { }
		}
		
		GROUP ID_SKY_GROUP_LAYER_1
		{
			GROUP
			{
				LAYOUTGROUP; COLUMNS 2;
				GROUP
				{
					LONG SKY_CLOUD_1_NOISE
					{
						CYCLE
						{
						}
						CUSTOMGUI NOISE;
					}
					BUTTON SKY_CLOUD_1_SAVE_PRESET { }
					COLOR SKY_CLOUD_1_COLOR { }
					REAL SKY_CLOUD_1_HEIGHT { UNIT METER; MIN 0; MAX 50000; }
				}
				GROUP
				{
					MATPREVIEW SKY_CLOUD_1_PREVIEW { OPEN; }
				}
			}
			REAL SKY_CLOUD_1_DENSITY { UNIT PERCENT; MIN 0; MAX 5000; MINSLIDER 0; MAXSLIDER 500; }
			REAL SKY_CLOUD_1_COVERAGE { UNIT PERCENT; MIN 0; MAX 100; }
			REAL SKY_CLOUD_1_THICKNESS { UNIT PERCENT; MIN 0; MAX 5000; MINSLIDER 0; MAXSLIDER 500; }
			REAL SKY_CLOUD_1_TRANSPARENCY { UNIT PERCENT; MIN 0; MAX 100; }
			GROUP
			{
				COLUMNS 2;
				REAL SKY_CLOUD_1_SPEED { UNIT PERCENT; }
				REAL SKY_CLOUD_1_OFFSET { }
				REAL SKY_CLOUD_1_SCALE_NS { UNIT PERCENT; MIN 1; MINSLIDER 1; MAXSLIDER 1000; }
				REAL SKY_CLOUD_1_SCALE_WE { UNIT PERCENT; MIN 1; MINSLIDER 1; MAXSLIDER 1000; }
				REAL SKY_CLOUD_1_MOVE_NS { UNIT METER; }
				REAL SKY_CLOUD_1_MOVE_WE { UNIT METER; }
			}
		}

		GROUP ID_SKY_GROUP_LAYER_2
		{
			GROUP
			{
				LAYOUTGROUP; COLUMNS 2;
				GROUP
				{
					LONG SKY_CLOUD_2_NOISE
					{
						CYCLE
						{
						}
						CUSTOMGUI NOISE;
					}
					BUTTON SKY_CLOUD_2_SAVE_PRESET { }
					COLOR SKY_CLOUD_2_COLOR { }
					REAL SKY_CLOUD_2_HEIGHT { UNIT METER; MIN 0; MAX 50000; }
				}
				GROUP
				{
					MATPREVIEW SKY_CLOUD_2_PREVIEW { OPEN; }
				}
			}
			REAL SKY_CLOUD_2_DENSITY { UNIT PERCENT; MIN 0; MAX 5000; MINSLIDER 0; MAXSLIDER 500; }
			REAL SKY_CLOUD_2_COVERAGE { UNIT PERCENT; MIN 0; MAX 100; }
			REAL SKY_CLOUD_2_THICKNESS { UNIT PERCENT; MIN 0; MAX 5000; MINSLIDER 0; MAXSLIDER 500; }
			REAL SKY_CLOUD_2_TRANSPARENCY { UNIT PERCENT; MIN 0; MAX 100; }
			GROUP
			{
				COLUMNS 2;
				REAL SKY_CLOUD_2_SPEED { UNIT PERCENT; }
				REAL SKY_CLOUD_2_OFFSET { }
				REAL SKY_CLOUD_2_SCALE_NS { UNIT PERCENT; MIN 1; MINSLIDER 1; MAXSLIDER 1000; }
				REAL SKY_CLOUD_2_SCALE_WE { UNIT PERCENT; MIN 1; MINSLIDER 1; MAXSLIDER 1000; }
				REAL SKY_CLOUD_2_MOVE_NS { UNIT METER; }
				REAL SKY_CLOUD_2_MOVE_WE { UNIT METER; }
			}
		}

		GROUP ID_SKY_GROUP_LAYER_3
		{
			GROUP
			{
				LAYOUTGROUP; COLUMNS 2;
				GROUP
				{
					LONG SKY_CLOUD_3_NOISE
					{
						CYCLE
						{
						}
						CUSTOMGUI NOISE;
					}
					BUTTON SKY_CLOUD_3_SAVE_PRESET { }
					COLOR SKY_CLOUD_3_COLOR { }
					REAL SKY_CLOUD_3_HEIGHT { UNIT METER; MIN 0; MAX 50000; }
				}
				GROUP
				{
					MATPREVIEW SKY_CLOUD_3_PREVIEW { OPEN; }
				}
			}
			REAL SKY_CLOUD_3_DENSITY { UNIT PERCENT; MIN 0; MAX 5000; MINSLIDER 0; MAXSLIDER 500; }
			REAL SKY_CLOUD_3_COVERAGE { UNIT PERCENT; MIN 0; MAX 100; }
			REAL SKY_CLOUD_3_THICKNESS { UNIT PERCENT; MIN 0; MAX 5000; MINSLIDER 0; MAXSLIDER 500; }
			REAL SKY_CLOUD_3_TRANSPARENCY { UNIT PERCENT; MIN 0; MAX 100; }
			GROUP
			{
				COLUMNS 2;
				REAL SKY_CLOUD_3_SPEED { UNIT PERCENT; };
				REAL SKY_CLOUD_3_OFFSET { }
				REAL SKY_CLOUD_3_SCALE_NS { UNIT PERCENT; MIN 1; MINSLIDER 1; MAXSLIDER 1000; }
				REAL SKY_CLOUD_3_SCALE_WE { UNIT PERCENT; MIN 1; MINSLIDER 1; MAXSLIDER 1000; }
				REAL SKY_CLOUD_3_MOVE_NS { UNIT METER; }
				REAL SKY_CLOUD_3_MOVE_WE { UNIT METER; }
			}
		}

		GROUP ID_SKY_GROUP_LAYER_4
		{
			GROUP
			{
				LAYOUTGROUP; COLUMNS 2;
				GROUP
				{
					LONG SKY_CLOUD_4_NOISE
					{
						CYCLE
						{
						}
						CUSTOMGUI NOISE;
					}
					BUTTON SKY_CLOUD_4_SAVE_PRESET { }
					COLOR SKY_CLOUD_4_COLOR { }
					REAL SKY_CLOUD_4_HEIGHT { UNIT METER; MIN 0; MAX 50000; }
				}
				GROUP
				{
					MATPREVIEW SKY_CLOUD_4_PREVIEW { OPEN; }
				}
			}
			REAL SKY_CLOUD_4_DENSITY { UNIT PERCENT; MIN 0; MAX 5000; MINSLIDER 0; MAXSLIDER 500; }
			REAL SKY_CLOUD_4_COVERAGE { UNIT PERCENT; MIN 0; MAX 100; }
			REAL SKY_CLOUD_4_THICKNESS { UNIT PERCENT; MIN 0; MAX 5000; MINSLIDER 0; MAXSLIDER 500; }
			REAL SKY_CLOUD_4_TRANSPARENCY { UNIT PERCENT; MIN 0; MAX 100; }
			GROUP
			{
				COLUMNS 2;
				REAL SKY_CLOUD_4_SPEED { UNIT PERCENT; };
				REAL SKY_CLOUD_4_OFFSET { };
				REAL SKY_CLOUD_4_SCALE_NS { UNIT PERCENT; MIN 1; MINSLIDER 1; MAXSLIDER 1000; }
				REAL SKY_CLOUD_4_SCALE_WE { UNIT PERCENT; MIN 1; MINSLIDER 1; MAXSLIDER 1000; }
				REAL SKY_CLOUD_4_MOVE_NS { UNIT METER; }
				REAL SKY_CLOUD_4_MOVE_WE { UNIT METER; }
			}
		}

		GROUP ID_SKY_GROUP_LAYER_5
		{
			GROUP
			{
				LAYOUTGROUP; COLUMNS 2;
				GROUP
				{
					LONG SKY_CLOUD_5_NOISE
					{
						CYCLE
						{
						}
						CUSTOMGUI NOISE;
					}
					BUTTON SKY_CLOUD_5_SAVE_PRESET { }
					COLOR SKY_CLOUD_5_COLOR { }
					REAL SKY_CLOUD_5_HEIGHT { UNIT METER; MIN 0; MAX 50000; }
				}
				GROUP
				{
					MATPREVIEW SKY_CLOUD_5_PREVIEW { OPEN; }
				}
			}
			REAL SKY_CLOUD_5_DENSITY { UNIT PERCENT; MIN 0; MAX 5000; MINSLIDER 0; MAXSLIDER 500; }
			REAL SKY_CLOUD_5_COVERAGE { UNIT PERCENT; MIN 0; MAX 100; }
			REAL SKY_CLOUD_5_THICKNESS { UNIT PERCENT; MIN 0; MAX 5000; MINSLIDER 0; MAXSLIDER 500; }
			REAL SKY_CLOUD_5_TRANSPARENCY { UNIT PERCENT; MIN 0; MAX 100; }
			GROUP
			{
				COLUMNS 2;
				REAL SKY_CLOUD_5_SPEED { UNIT PERCENT; };
				REAL SKY_CLOUD_5_OFFSET { };
				REAL SKY_CLOUD_5_SCALE_NS { UNIT PERCENT; MIN 1; MINSLIDER 1; MAXSLIDER 1000; }
				REAL SKY_CLOUD_5_SCALE_WE { UNIT PERCENT; MIN 1; MINSLIDER 1; MAXSLIDER 1000; }
				REAL SKY_CLOUD_5_MOVE_NS { UNIT METER; }
				REAL SKY_CLOUD_5_MOVE_WE { UNIT METER; }
			}
		}

		GROUP ID_SKY_GROUP_LAYER_6
		{
			GROUP
			{
				LAYOUTGROUP; COLUMNS 2;
				GROUP
				{
					LONG SKY_CLOUD_6_NOISE
					{
						CYCLE
						{
						}
						CUSTOMGUI NOISE;
					}
					BUTTON SKY_CLOUD_6_SAVE_PRESET { }
					COLOR SKY_CLOUD_6_COLOR { }
					REAL SKY_CLOUD_6_HEIGHT { UNIT METER; MIN 0; MAX 50000; }
				}
				GROUP
				{
					MATPREVIEW SKY_CLOUD_6_PREVIEW { OPEN; }
				}
			}
			REAL SKY_CLOUD_6_DENSITY { UNIT PERCENT; MIN 0; MAX 5000; MINSLIDER 0; MAXSLIDER 500; }
			REAL SKY_CLOUD_6_COVERAGE { UNIT PERCENT; MIN 0; MAX 100; }
			REAL SKY_CLOUD_6_THICKNESS { UNIT PERCENT; MIN 0; MAX 5000; MINSLIDER 0; MAXSLIDER 500; }
			REAL SKY_CLOUD_6_TRANSPARENCY { UNIT PERCENT; MIN 0; MAX 100; }
			GROUP
			{
				COLUMNS 2;
				REAL SKY_CLOUD_6_SPEED { UNIT PERCENT; };
				REAL SKY_CLOUD_6_OFFSET { };
				REAL SKY_CLOUD_6_SCALE_NS { UNIT PERCENT; MIN 1; MINSLIDER 1; MAXSLIDER 1000; }
				REAL SKY_CLOUD_6_SCALE_WE { UNIT PERCENT; MIN 1; MINSLIDER 1; MAXSLIDER 1000; }
				REAL SKY_CLOUD_6_MOVE_NS { UNIT METER; }
				REAL SKY_CLOUD_6_MOVE_WE { UNIT METER; }
			}
		}
	}

	GROUP ID_SKY_GROUP_GENERAL
	{
		BOOL SKY_ASTRO_MOON_SHOW { PARENTCOLLAPSE; }
			REAL SKY_GENERAL_SCALE_MOON { UNIT PERCENT; MIN 0.1; MINSLIDER 0.1; MAXSLIDER 20000; PARENTCOLLAPSE SKY_ASTRO_MOON_SHOW; }
			REAL SKY_GENERAL_MOON_BRIGHT { UNIT PERCENT; MIN 0; MAX 100; PARENTCOLLAPSE SKY_ASTRO_MOON_SHOW; }
			REAL SKY_GENERAL_MOON_DARK { UNIT PERCENT; MIN 0; MAX 100; PARENTCOLLAPSE SKY_ASTRO_MOON_SHOW; }
			REAL SKY_GENERAL_MOON_DIST_SCALE { UNIT PERCENT; MIN 0; MINSLIDER 0; MAXSLIDER 100; STEP 0.01; PARENTCOLLAPSE SKY_ASTRO_MOON_SHOW; }
			LINK SKY_OBJECT_MOON_OBJECT { PARENTCOLLAPSE SKY_ASTRO_MOON_SHOW; }
			SEPARATOR { PARENTCOLLAPSE SKY_ASTRO_MOON_SHOW; LINE; }
		
		BOOL SKY_ASTRO_SHOW_STARS { PARENTCOLLAPSE; }
			REAL SKY_GENERAL_MIN_MAG { MIN 0; MAX 10.5; MINSLIDER 0; MAXSLIDER 10.5; STEP .1; PARENTCOLLAPSE SKY_ASTRO_SHOW_STARS; }
			BOOL SKY_GENERAL_RESIZE_STARS { PARENTCOLLAPSE SKY_ASTRO_SHOW_STARS;}
			REAL SKY_GENERAL_LIGHTEN_UP_STARS { UNIT PERCENT; MIN 0; MAX 100; PARENTCOLLAPSE SKY_ASTRO_SHOW_STARS;} 
			REAL SKY_GENERAL_STAR_RADIUS { MIN 0.1; MAX 5; MINSLIDER 0; MAXSLIDER 5; STEP .05; PARENTCOLLAPSE SKY_ASTRO_SHOW_STARS;}
			BOOL SKY_GENERAL_SHOW_CONSTELLATIONS { PARENTCOLLAPSE SKY_ASTRO_SHOW_STARS;}
			COLOR SKY_GENERAL_CONSTELLATION_COLOR { PARENTID SKY_GENERAL_SHOW_CONSTELLATIONS; PARENTCOLLAPSE SKY_ASTRO_SHOW_STARS;}
			REAL SKY_GENERAL_GRID_WIDTH { UNIT DEGREE; MIN 0; MAX 180; PARENTCOLLAPSE SKY_ASTRO_SHOW_STARS;}
			COLOR SKY_GENERAL_GRID_COLOR { PARENTCOLLAPSE SKY_ASTRO_SHOW_STARS;}
			SEPARATOR { PARENTCOLLAPSE SKY_ASTRO_SHOW_STARS; LINE; }

		BOOL SKY_ASTRO_PLANETS_SHOW { }

		SEPARATOR { LINE; }
		BOOL SKY_GENERAL_SKY_DOME {}

		SEPARATOR { LINE; }
		BOOL SKY_GENERAL_MERGE_SUN    {}

		SEPARATOR { LINE; }
		BOOL SKY_MATERIAL_GLOBALILLUM_GENERATE {}
		REAL SKY_MATERIAL_GLOBALILLUM_GENERATE_STRENGTH { UNIT PERCENT; MIN 0.0; MAX 10000.0; }
		REAL SKY_GENERAL_GI_SATURATION { UNIT PERCENT; MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100; }
		REAL SKY_GENERAL_GI_INFLUENCE { UNIT PERCENT; MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100; }
		SEPARATOR { LINE; }

		PRIORITY SKY_EXPRESSION_PRIORITY { ANIM OFF; NOCAMERA; }
		LONG SKY_MATERIAL_PREVIEWSIZE
		{
			CYCLE
			{
				SKY_MATERIAL_PREVIEWSIZE_DEF;
				SKY_MATERIAL_PREVIEWSIZE_64;
				SKY_MATERIAL_PREVIEWSIZE_128;
				SKY_MATERIAL_PREVIEWSIZE_256;
				SKY_MATERIAL_PREVIEWSIZE_512;
				SKY_MATERIAL_PREVIEWSIZE_1024;
				SKY_MATERIAL_PREVIEWSIZE_2048;
				SKY_MATERIAL_PREVIEWSIZE_4096;
			}
		}
		SEPARATOR { LINE; }
		BOOL SKY_SHOW_HUD { ANIM OFF; }
		BOOL SKY_UPDATE_EDITOR { }
	}


	GROUP ID_SKY_GROUP_VOL_CLOUDS
	{
		SCALE_V;

		GROUP
		{
			BOOL SKY_SHOW_CLOUD_BOX { }
			COLOR SKY_CLOUD_EDITOR_COLOR { }
			REAL SKY_CLOUD_EDITOR_QUALITY { UNIT PERCENT; MIN 0; MAX 100; }
			SEPARATOR { LINE; }
			BOOL SKY_VOL_CLOUDS_ADJUST_ALTITUDE { }
			BOOL SKY_VOL_CLOUDS_RECEIVE_SHADOWS { }
			REAL SKY_VOL_CLOUDS_SAMPLE_SIZE { UNIT METER; MIN 0; }
			SEPARATOR { LINE; }
			LONG SKY_VOL_CLOUDS_EDGE_NOISE_NOISE
			{
				CYCLE { }
				CUSTOMGUI NOISE;
			}
			REAL SKY_VOL_CLOUDS_EDGE_NOISE_CONTRAST { UNIT PERCENT; MIN 0; MAX 100; }
			REAL SKY_VOL_CLOUDS_EDGE_NOISE_SCALE { UNIT PERCENT; MIN 0; }
			REAL SKY_VOL_CLOUDS_EDGE_NOISE_SPEED { UNIT PERCENT; MIN 0; } 
		}

		GROUP
		{
			SCALE_V;
			IN_EXCLUDE SKY_VOL_CLOUDS_LIGHT_LIST { NUM_FLAGS 0; ACCEPT { Olight; } SCALE_V; }
		}
	}

	GROUP ID_SKY_GROUP_FOG
	{
		COLOR SKY_FOG_COLOR { }
		REAL SKY_FOG_START { UNIT METER; }
		REAL SKY_FOG_END { UNIT METER; }
		REAL SKY_FOG_MAXDIST { UNIT METER; MIN 0; MAX 200000; }
		REAL SKY_FOG_DENSITY { UNIT PERCENT; MIN 0; }
		SPLINE SKY_FOG_DENSITY_DISTRIB { SHOWGRID_H; SHOWGRID_V; MINSIZE_H 120;
																			MINSIZE_V 90; EDIT_H; EDIT_V; 
																			X_MIN 0; X_MAX 100; Y_MIN 0; Y_MAX 100; X_STEPS 1; Y_STEPS 1; }
		LONG SKY_FOG_NOISE
		{
			CYCLE
			{
			}
			CUSTOMGUI NOISE;
		}
		REAL SKY_FOG_NOISE_STRENGTH { UNIT PERCENT; MIN -1000; MAX 1000; }
		VECTOR SKY_FOG_SCALE { UNIT PERCENT; MIN 0; }
		VECTOR SKY_FOG_MOVEMENT { UNIT METER; }
		REAL SKY_FOG_SAMPLE_SIZE { MIN 5; UNIT METER; }
		REAL SKY_FOG_ANIMATION_SPEED { UNIT PERCENT; MIN 0; }
		REAL SKY_FOG_SHADOW_INTENSITY { UNIT PERCENT; MIN 0; MAX 100; }
		REAL SKY_FOG_ILLUM_INTENSITY { UNIT PERCENT; MIN 0; MAX 100; }
	}

	GROUP ID_SKY_GROUP_RAINBOW
	{
		REAL SKY_RAINBOW_MAX_STRENGTH { UNIT PERCENT; MIN 0; MAX 100; }
		BOOL SKY_RAINBOW_TURBIDITY_DEP { }
		REAL SKY_RAINBOW_TURBIDITY_THRESHOLD_MIN { UNIT PERCENT; MIN 0; MAX 100; }
		REAL SKY_RAINBOW_TURBIDITY_THRESHOLD_MAX { UNIT PERCENT; MIN 0; MAX 100; }
		REAL SKY_RAINBOW_1_INNER { UNIT DEGREE; MIN 0; MAX 180; }
		REAL SKY_RAINBOW_1_OUTER { UNIT DEGREE; MIN 0; MAX 180; }
		REAL SKY_RAINBOW_2_INNER { UNIT DEGREE; MIN 0; MAX 180; }
		REAL SKY_RAINBOW_2_OUTER { UNIT DEGREE; MIN 0; MAX 180; }
		REAL SKY_RAINBOW_START_CLIP { UNIT METER; }
		REAL SKY_RAINBOW_END_CLIP { UNIT METER; }
	}

	GROUP ID_SKY_GROUP_SUNBEAMS
	{
		BOOL SKY_BEAMS_TURBIDITY_DEPENDENT { } 
		REAL SKY_BEAMS_INTENS { UNIT PERCENT; MIN 0; MAX 100; }
		REAL SKY_BEAMS_MIN_BRIGHTNESS { UNIT PERCENT; MIN 0; MAX 200; MINSLIDER 0; MAXSLIDER 200; }
		REAL SKY_BEAMS_START { UNIT METER; MIN 0; }
		REAL SKY_BEAMS_END { UNIT METER; MIN 0; }
		REAL SKY_BEAMS_SAMPLE_DIST { UNIT METER; MIN 20; }
	}

	GROUP ID_SKY_GROUP_SKY_OBJECTS
	{
		SCALE_V;
		SKY_OBJECTS SKY_SKY_OBJECTS { NEWLINE; SCALE_V; }
		BUTTON SKY_SKY_OBECT_PLACE { }
	}
}
