CONTAINER ToolCloud
{
  NAME ToolCloud;
	INCLUDE ToolBase;

	GROUP MDATA_CLOUD_TOOLS
	{
		REAL MDATA_CLOUD_CREATE_BRUSH_RAD { UNIT METER; MIN 1; }
		REAL MDATA_CLOUD_CREATE_DENSITY { UNIT PERCENT; MIN 0; MAX 100; CUSTOMGUI REALSLIDER; MINSLIDER 1; MAXSLIDER 100;}
		VECTOR MDATA_CLOUD_CREATE_MAX_SIZE { UNIT METER; MAX 120000; }
		REAL MDATA_CLOUD_DRAW_THRESHOLD { UNIT PERCENT; MIN 1; MAX 100; }
		GROUP
		{
			COLUMNS 3;
			BUTTON MDATA_CLOUD_CLEAR { }
			BUTTON MDATA_CLOUD_FILL_PLANE { }
			BUTTON MDATA_CLOUD_FILL_SPHERE { }
		}
	}

	GROUP MDATA_CLOUD_SMOOTHING
	{
		REAL MDATA_CLOUD_SMOOTH_B_DIST { UNIT METER; MIN 0; }
		REAL MDATA_CLOUD_SMOOTH_B_VAR { UNIT PERCENT; MIN 0; MAX 100; CUSTOMGUI REALSLIDER; MINSLIDER 0; MAXSLIDER 100; }
		SPLINE MDATA_CLOUD_SMOOTH_B_SPLINE { }
		BUTTON MDATA_CLOUD_SMOOTH_BORDERS { }
		SEPARATOR { LINE; }
		REAL MDATA_CLOUD_SMOOTH_A_STR { UNIT PERCENT; MIN 0; MAX 100; CUSTOMGUI REALSLIDER; MINSLIDER 0; MAXSLIDER 100; }
		REAL MDATA_CLOUD_SMOOTH_A_VARIANCE { UNIT PERCENT; MIN 0; MAX 100; CUSTOMGUI REALSLIDER; MINSLIDER 0; MAXSLIDER 100; }
		BUTTON MDATA_CLOUD_SMOOTH_ALL { }
		SEPARATOR { LINE; }
		SPLINE MDATA_CLOUD_REMAP_SPLINE { }
		BUTTON MDATA_CLOUD_REMAP { }
	}

	GROUP MDATA_CLOUD_DISPLAY
	{
		REAL MDATA_CLOUD_DISPLAY_QUALITY { UNIT PERCENT; MIN 0; MAX 100; CUSTOMGUI REALSLIDER; MINSLIDER 0; MAXSLIDER 100; }
		BUTTON MDATA_RENDERPREVIEW_BTN { }
	}

	HIDE MDATA_COMMANDGROUP;
}
