CONTAINER Xskyshader
{
	NAME Xskyshader;
	INCLUDE Mpreview;
	INCLUDE Obaselist;

	GROUP Obaselist
	{
		//BOOL SKY_MATERIAL_PAGE_PROPERTIES { PAGE; HIDDEN; PARENTMSG ID_MATERIALPROPERTIES; }
	}

	INCLUDE Millum;
	GROUP ID_MATERIALGROUP_ILLUMINATION
	{
		LINK SKY_MATERIAL_SKY_OBJ { HIDDEN; }
	}
}  
