CONTAINER GVabs
{
	NAME GVabs;
	INCLUDE GVdynamic;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		DYNAMIC GV_ABS_INPUT  { INPORT;  STATICPORT; CREATEPORT; }
		DYNAMIC GV_ABS_OUTPUT { OUTPORT; STATICPORT; CREATEPORT; }
	}
}
