CONTAINER GVadapter
{
	NAME GVadapter;
	INCLUDE GVdynamic;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		DYNAMIC GV_ADAPTER_INPUT  { INPORT;  STATICPORT; CREATEPORT; }
		DYNAMIC GV_ADAPTER_OUTPUT { OUTPORT; STATICPORT; CREATEPORT; }
	}
}
