CONTAINER GVbitmap
{
	NAME GVbitmap;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		LONG GV_BITMAP_X  { INPORT; }
		LONG GV_BITMAP_Y  { INPORT; }
		FILENAME GV_BITMAP_FN_PORT { TEXTURE; INPORT; }
		LONG GV_BITMAP_WIDTH { OUTPORT; }
		LONG GV_BITMAP_HEIGHT { OUTPORT; }
		VECTOR GV_BITMAP_COLOR { OUTPORT; }
	}
}
