CONTAINER GVbox
{
	NAME GVbox;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
		LONG GV_BOX_MODE { CYCLE { GV_BOX_OPERATOR_MODE_GLOBAL; GV_BOX_OPERATOR_MODE_LOCAL; } }
		BOOL GV_BOX_USE_DEFORMED { }
	}

	GROUP ID_GVPORTS
	{
		GVGENERALOBJECT GV_BOX_INPUT_OBJECT { INPORT; STATICPORT; CREATEPORT; }

		VECTOR GV_BOX_OUTPUT_POINT_MIN { OUTPORT; CREATEPORT; }
		VECTOR GV_BOX_OUTPUT_POINT_MAX { OUTPORT; CREATEPORT; }
		VECTOR GV_BOX_OUTPUT_POINT_SIZE { OUTPORT; CREATEPORT; }
		VECTOR GV_BOX_OUTPUT_POINT1 { OUTPORT; }
		VECTOR GV_BOX_OUTPUT_POINT2 { OUTPORT; }
		VECTOR GV_BOX_OUTPUT_POINT3 { OUTPORT; }
		VECTOR GV_BOX_OUTPUT_POINT4 { OUTPORT; }
		VECTOR GV_BOX_OUTPUT_POINT5 { OUTPORT; }
		VECTOR GV_BOX_OUTPUT_POINT6 { OUTPORT; }
		VECTOR GV_BOX_OUTPUT_POINT7 { OUTPORT; }
		VECTOR GV_BOX_OUTPUT_POINT8 { OUTPORT; }
	}
}
