CONTAINER GVbool
{
	NAME GVbool;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
		LONG GV_BOOL_FUNCTION_ID 
		{ 
			CYCLE 
			{ 
				GV_AND_NODE_FUNCTION; 
				GV_OR_NODE_FUNCTION;
				GV_XOR_NODE_FUNCTION;
				GV_NAND_NODE_FUNCTION;
				GV_NOR_NODE_FUNCTION;
				GV_NXOR_NODE_FUNCTION;
			}
		}
	}

	GROUP ID_GVPORTS
	{
		BOOL GV_BOOL_INPUT  { INPORT; MULTIPLE; MINPORTS 2; }
		BOOL GV_BOOL_OUTPUT { OUTPORT; STATICPORT; CREATEPORT; }
	}
}
