CONTAINER GVclamp
{
	NAME GVclamp;
	INCLUDE GVdynamic;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		DYNAMIC GV_CLAMP_INPUT1  { INPORT;  STATICPORT; CREATEPORT; }
		DYNAMIC GV_CLAMP_INPUT2  { INPORT;  STATICPORT; CREATEPORT; }
		DYNAMIC GV_CLAMP_INPUT3  { INPORT;  STATICPORT; CREATEPORT; }

		DYNAMIC GV_CLAMP_OUTPUT  { OUTPORT; STATICPORT; CREATEPORT; }
	}
}
