CONTAINER GVcmp
{
	NAME GVcmp;
	INCLUDE GVdynamic;

	GROUP ID_GVPROPERTIES
	{
		LONG GV_CMP_FUNCTION 
		{
			CYCLE 
			{
				GV_EQU_NODE_FUNCTION;
				GV_LESS_NODE_FUNCTION;
				GV_LESSEQU_NODE_FUNCTION;
				GV_GREATER_NODE_FUNCTION;
				GV_GREATEREQU_NODE_FUNCTION;
				GV_NOT_EQU_NODE_FUNCTION;
			}
		}
	}

	GROUP ID_GVPORTS
	{
		DYNAMIC GV_CMP_INPUT1 { INPORT;  STATICPORT; CREATEPORT; }
		DYNAMIC GV_CMP_INPUT2 { INPORT;  STATICPORT; CREATEPORT; }
		BOOL GV_CMP_OUTPUT 		{ OUTPORT; STATICPORT; CREATEPORT; }
	}
}
