CONTAINER GVcondition
{
	NAME GVcondition;
	INCLUDE GVdynamic;

	GROUP ID_GVPROPERTIES
	{
	}
	GROUP ID_GVPORTS
	{
		LONG GV_CONDITION_SWITCH 			{ INPORT; STATICPORT; NEEDCONNECTION; CREATEPORT; }
		DYNAMIC GV_CONDITION_INPUT			{ INPORT; MULTIPLE; CREATEPORT 2; MINPORTS 1; }
		DYNAMIC GV_CONDITION_OUTPUT			{ OUTPORT; STATICPORT; CREATEPORT; }
	}
}
