CONTAINER GVconst
{
	NAME GVconst;
	INCLUDE GVdynamic;

	GROUP ID_GVPROPERTIES
	{
		DYNAMIC GV_CONST_VALUE { }
		LONG GV_CONSTANT_DEFAULT { CYCLE { } }
	}

	GROUP ID_GVPORTS
	{
		DYNAMIC GV_CONST_OUTPUT	{ OUTPORT; STATICPORT; CREATEPORT; }
	}
}
