CONTAINER GVdetails
{
	NAME GVdetails;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		GVGENERALINSTANCE GV_DETAILS_INPUT_OBJECT { INPORT; STATICPORT; CREATEPORT; }

		GVGENERALINSTANCE GV_DETAILS_OUTPUT_OBJECT { OUTPORT; STATICPORT; CREATEPORT; }
		LONG GV_DETAILS_OUTPUT_INDEX { OUTPORT; STATICPORT; CREATEPORT; }
	}
}
