CONTAINER GVdistance
{
	NAME GVdistance;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		VECTOR GV_DISTANCE_INPUT1	{ INPORT;  STATICPORT; CREATEPORT; }
		VECTOR GV_DISTANCE_INPUT2	{ INPORT;  STATICPORT; CREATEPORT; }
		REAL   GV_DISTANCE_OUTPUT	{ OUTPORT; STATICPORT; CREATEPORT; }
	}
}
