CONTAINER GVdot
{
	NAME GVdot;
	INCLUDE GVdynamic;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		DYNAMIC GV_DOT_INPUT1	{ INPORT; STATICPORT; CREATEPORT; }
		DYNAMIC GV_DOT_INPUT2	{ INPORT; STATICPORT; CREATEPORT; }
		REAL GV_DOT_OUTPUT	{ OUTPORT; STATICPORT; CREATEPORT; }
	}
}
