CONTAINER GVequ
{
	NAME GVequ;
	INCLUDE GVdynamic;

	GROUP ID_GVPROPERTIES
	{
		BOOL GV_EQU_NEGATE { }
	}

	GROUP ID_GVPORTS
	{
		DYNAMIC	GV_EQU_INPUT	{ INPORT;  MULTIPLE; CREATEPORT 2; }
		BOOL		GV_EQU_OUTPUT	{ OUTPORT; STATICPORT; CREATEPORT; }
	}
}
