CONTAINER GVfloatmath
{
	NAME GVfloatmath;
	INCLUDE GVdynamic;

	GROUP ID_GVPROPERTIES
	{
		LONG GV_FLOATMATH_FUNCTION_ID 
		{ 
			CYCLE 
			{ 
				GV_ADR_NODE_FUNCTION;
				GV_SUR_NODE_FUNCTION;
				GV_MUR_NODE_FUNCTION;
				GV_DIR_NODE_FUNCTION;
			}
		}
	}

	GROUP ID_GVPORTS
	{
		DYNAMIC GV_FLOATMATH_INPUT  { INPORT; STATICPORT; CREATEPORT; }
		REAL GV_FLOATMATH_REAL  { INPORT; STATICPORT; CREATEPORT; }
		DYNAMIC GV_FLOATMATH_OUTPUT { OUTPORT; STATICPORT; CREATEPORT; }
	}
}
