CONTAINER GVhierarchy
{
	NAME GVhierarchy;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
		SCALE_V;
		LINK GV_HIERARCHY_OBJECT_ID { }
		LONG GV_HIERARCHY_PATH_TYPE { CYCLE { GV_HIERARCHY_PATH_TYPE_START; GV_HIERARCHY_PATH_TYPE_ABSOLUTE; GV_HIERARCHY_PATH_TYPE_RELATIVE; } }
		LONG GV_HIERARCHY_START_TYPE_ID { }
		LONG GV_HIERARCHY_DISTANCE_ID { MIN 1; }
		STRING GV_HIERARCHY_PATH_ID { }
		STRING GV_HIERARCHY_START_ID { }
		STRING GV_HIERARCHY_ITERATION_ID { }
		IN_EXCLUDE GV_HIERARCHY_EXCLUDE_ID { SCALE_V; NUM_FLAGS 0; INIT_STATE 0; IMAGE_01_ON 1009316; IMAGE_01_OFF 1009320; ACCEPT { Obase; } }
	}

	GROUP ID_GVPORTS
	{
		GVGENERALOBJECT GV_HIERARCHY_INPUT_OBJECT { INPORT; }
		LONG GV_HIERARCHY_INPUT_MAX { INPORT; EDITPORT; MIN 0; }
		BOOL GV_HIERARCHY_OPERATOR_ON { INPORT; }

		GVGENERALOBJECT GV_HIERARCHY_OUTPUT_OBJECT { OUTPORT; STATICPORT; CREATEPORT; ITERATOR; }
		LONG GV_HIERARCHY_OUTPUT_COUNT { OUTPORT; }
	}
}
