CONTAINER GVinv
{
	NAME GVinv;
	INCLUDE GVdynamic;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		DYNAMIC GV_INV_INPUT  { INPORT;  STATICPORT; CREATEPORT; }
		DYNAMIC GV_INV_OUTPUT { OUTPORT; STATICPORT; CREATEPORT; }
	}
}
