CONTAINER GVinclude
{
	NAME GVinclude;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
		SCALE_V;
	}

	GROUP ID_GVPORTS
	{
		BOOL GV_INCLUDE_OPERATOR_ON { INPORT; }

		GVGENERALINSTANCE GV_INCLUDE_OUTPUT_OBJECT { OUTPORT; STATICPORT; CREATEPORT; ITERATOR;  }
		LONG GV_INCLUDE_OUTPUT_COUNT { OUTPORT; }
		IN_EXCLUDE GV_INCLUDE_LIST { INPORT; EDITPORT; NUM_FLAGS 0; INIT_STATE 0; IMAGE_01_ON 1009316; IMAGE_01_OFF 1009320; ACCEPT { Obase; } }
	}
}
