CONTAINER GViterate
{
	NAME GViterate;
	INCLUDE GVdynamic;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		LONG GV_ITERATE_INPUT_LOWER { INPORT; STATICPORT; CREATEPORT; }
		LONG GV_ITERATE_INPUT_UPPER { INPORT; STATICPORT; CREATEPORT; }

		BOOL GV_ITERATE_OPERATOR_ON { INPORT; }
		DYNAMIC GV_ITERATE_LINK_INPUT	{ INPORT; }

		LONG GV_ITERATE_OUTPUT { OUTPORT; STATICPORT; CREATEPORT; ITERATOR; }
		LONG GV_ITERATE_OUTPUT_COUNT { OUTPORT; }
		DYNAMIC GV_ITERATE_LINK_OUTPUT	{ OUTPORT; }
	}
}
