CONTAINER GVmaterial
{
	NAME GVmaterial;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
		SCALE_V;
		LONG GV_MATERIAL_TYPE { }
		IN_EXCLUDE GV_MATERIAL_EXCLUDE_ID { NUM_FLAGS 0; INIT_STATE 0; IMAGE_01_ON 1009316; IMAGE_01_OFF 1009320; ACCEPT { Mbase; } }
	}

	GROUP ID_GVPORTS
	{
		LONG GV_MATERIAL_INPUT_START { INPORT; }
		LONG GV_MATERIAL_INPUT_COUNT { INPORT; }
		BOOL GV_MATERIAL_OPERATOR_ON { INPORT; }

		GVGENERALMATERIAL GV_MATERIAL_OUTPUT_MATERIAL { OUTPORT; STATICPORT; CREATEPORT; ITERATOR; }
		LONG GV_MATERIAL_OUTPUT_COUNT { OUTPORT; }
	}
}
