CONTAINER GVmath
{
	NAME GVmath;
	INCLUDE GVdynamic;

	GROUP ID_GVPROPERTIES
	{
		LONG GV_MATH_FUNCTION_ID 
		{ 
			CYCLE 
			{ 
				GV_ADD_NODE_FUNCTION;
				GV_SUB_NODE_FUNCTION;
				GV_MUL_NODE_FUNCTION;
				GV_DIV_NODE_FUNCTION;
				GV_MOD_NODE_FUNCTION;
			}
		}
	}

	GROUP ID_GVPORTS
	{
		DYNAMIC GV_MATH_INPUT  { INPORT; MULTIPLE; CREATEPORT 2; }
		DYNAMIC GV_MATH_OUTPUT { OUTPORT; STATICPORT; CREATEPORT; }
	}
}
