CONTAINER GVmix
{
	NAME GVmix;
	INCLUDE GVdynamic;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		REAL GV_MIX_INPUT_MIXINGFACTOR { INPORT; STATICPORT; CREATEPORT; UNIT PERCENT; }
		DYNAMIC GV_MIX_INPUT1 { INPORT; STATICPORT; CREATEPORT; }
		DYNAMIC GV_MIX_INPUT2 { INPORT; STATICPORT; CREATEPORT; }

		DYNAMIC GV_MIX_OUTPUT { OUTPORT; STATICPORT; CREATEPORT; }
	}
}
