CONTAINER GVnearestpoint
{
	NAME GVnearestpoint;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
  {
    GVGENERALOBJECT GV_NEARESTPOINT_INPUT_SOURCEOBJECT { INPORT; STATICPORT; CREATEPORT; }
    VECTOR GV_NEARESTPOINT_INPUT_GLOBALPOSITION { INPORT; STATICPORT; CREATEPORT; }

		LONG GV_NEARESTPOINT_OUTPUT_POINTINDEX { OUTPORT; CREATEPORT; }
		VECTOR GV_NEARESTPOINT_OUTPUT_POINT { OUTPORT; CREATEPORT; }
		REAL GV_NEARESTPOINT_OUTPUT_DISTANCE { OUTPORT; CREATEPORT; }
		VECTOR GV_NEARESTPOINT_OUTPUT_DIFVECTOR { OUTPORT; CREATEPORT; }
	}
}
