CONTAINER GVneg
{
	NAME GVneg;
	INCLUDE GVdynamic;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		DYNAMIC GV_NEG_INPUT  { INPORT;  STATICPORT; CREATEPORT; }
		DYNAMIC GV_NEG_OUTPUT { OUTPORT; STATICPORT; CREATEPORT; }
	}
}
