CONTAINER GVnearestpointonspline
{
	NAME GVnearestpointonspline;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
  {
		GVGENERALOBJECT GV_NEARESTPOINTONSPLINE_INPUT_SPLINEOBJECT { INPORT; STATICPORT; CREATEPORT; }
		VECTOR GV_NEARESTPOINTONSPLINE_INPUT_GLOBALPOSITION { INPORT; STATICPORT; CREATEPORT; }
		REAL GV_NEARESTPOINTONSPLINE_INPUT_PRECISION { INPORT; STATICPORT; CREATEPORT; }
		LONG GV_NEARESTPOINTONSPLINE_INPUT_SPLINESEGMENT { INPORT; STATICPORT; CREATEPORT; }
		BOOL GV_NEARESTPOINTONSPLINE_INPUT_ALLSEGMENTS { INPORT; STATICPORT; CREATEPORT; }

		REAL GV_NEARESTPOINTONSPLINE_OUTPUT_SPLINEPOSITION { OUTPORT; CREATEPORT; }
		VECTOR GV_NEARESTPOINTONSPLINE_OUTPUT_NEARESTPOINT { OUTPORT; CREATEPORT; }
		LONG GV_NEARESTPOINTONSPLINE_OUTPUT_NEARESTSEGMENT { OUTPORT; CREATEPORT; }
		VECTOR GV_NEARESTPOINTONSPLINE_OUTPUT_TANGENT { OUTPORT; CREATEPORT; }
	}
}
