CONTAINER GVnil
{
	NAME GVnil;
	INCLUDE GVdynamic;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		DYNAMIC GV_NIL_INPUT { INPORT;  MULTIPLE; CREATEPORT 1; }
		BOOL GV_NIL_OUTPUT   { OUTPORT; STATICPORT; CREATEPORT; }
	}
}
