CONTAINER GVnoise
{
	NAME GVnoise;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
		LONG GV_NOISE_FUNCTION 
		{ 
			CYCLE 
			{ 
				GV_NOISE_NOISE;
				GV_NOISE_TURBULENCE;
				GV_NOISE_FRACTAL;
				GV_NOISE_FBM;
			}
		}
		BOOL GV_NOISE_POSITIVE { }
	}

	GROUP ID_GVPORTS
	{
		REAL GV_NOISE_LEVELS		{ INPORT; EDITPORT; STEP 0.01; MIN 1; MAX 10; }
		BASETIME GV_NOISE_TIME		{ INPORT; }
		REAL GV_NOISE_X 			{ INPORT; PORTONLY; }
		REAL GV_NOISE_Y 			{ INPORT; PORTONLY; }
		REAL GV_NOISE_Z 			{ INPORT; PORTONLY; }
		VECTOR GV_NOISE_VECTOR 		{ INPORT; PORTONLY; }
		REAL GV_NOISE_SCALE			{ INPORT; EDITPORT; MIN 0.0; STEP 0.01; }
		REAL GV_NOISE_FREQUENCY 	{ INPORT; EDITPORT; STEP 0.01; }
		REAL GV_NOISE_AMPLITUDE		{ INPORT; EDITPORT; }
		LONG GV_NOISE_SEED			{ INPORT; EDITPORT; }

		REAL GV_NOISE_OUTPUT 		{ OUTPORT; STATICPORT; CREATEPORT; }
	}
}
