CONTAINER GVobject
{
	NAME GVobject;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
		LINK GV_OBJECT_OBJECT_ID { }
		LONG GV_OBJECT_PATH_TYPE { CYCLE { GV_OBJECT_PATH_TYPE_START; GV_OBJECT_PATH_TYPE_ABSOLUTE; GV_OBJECT_PATH_TYPE_RELATIVE; } }
		LONG GV_OBJECT_START_TYPE_ID { }
		LONG GV_OBJECT_DISTANCE_ID { MIN 1; }
		LONG GV_OBJECT_HISTORY_DEPTH_ID { MIN 1; }
		STRING GV_OBJECT_PATH_ID { }
	}

	GROUP ID_GVPORTS
	{
		MATRIX GV_OBJECT_OPERATOR_LOCAL_IN 						{ INPORT; }
		MATRIX GV_OBJECT_OPERATOR_GLOBAL_IN 					{ INPORT; }
		LONG GV_OBJECT_OPERATOR_HISTORY_IN 						{ INPORT; }

		GVGENERALINSTANCE GV_OBJECT_OPERATOR_OBJECT_IN	{ INPORT; }
		BOOL GV_OBJECT_OPERATOR_ON						{ INPORT; }

		MATRIX GV_OBJECT_OPERATOR_LOCAL_OUT 					{ OUTPORT; }
		MATRIX GV_OBJECT_OPERATOR_GLOBAL_OUT 					{ OUTPORT; }

		GVGENERALINSTANCE GV_OBJECT_OPERATOR_OBJECT_OUT	{ OUTPORT; }

		VECTOR GV_OBJECT_OPERATOR_OLD_POS_OUT 				{ OUTPORT; }
		VECTOR GV_OBJECT_OPERATOR_OLD_ROT_OUT 				{ OUTPORT; }
		VECTOR GV_OBJECT_OPERATOR_OLD_SIZE_OUT 				{ OUTPORT; }
		MATRIX GV_OBJECT_OPERATOR_OLD_GLOBAL_OUT			{ OUTPORT; }
		MATRIX GV_OBJECT_OPERATOR_OLD_LOCAL_OUT 			{ OUTPORT; }
		VECTOR GV_OBJECT_OPERATOR_VELOCITY_POS_OUT 		{ OUTPORT; }
		VECTOR GV_OBJECT_OPERATOR_VELOCITY_ROT_OUT 		{ OUTPORT; }
		VECTOR GV_OBJECT_OPERATOR_VELOCITY_SIZE_OUT 	{ OUTPORT; }
	}
}
