CONTAINER GVorder
{
	NAME GVorder;
	INCLUDE GVdynamic;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		DYNAMIC GV_ORDER_INPUT1  { INPORT;  STATICPORT; CREATEPORT; }
		DYNAMIC GV_ORDER_INPUT2  { INPORT;  STATICPORT; CREATEPORT; }
		LONG GV_ORDER_OUTPUT 		 { OUTPORT; STATICPORT; CREATEPORT; }
	}
}
