CONTAINER GVpoint
{
	NAME GVpoint;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
		LONG GV_POINT_MODE { CYCLE { GV_POINT_OPERATOR_MODE_GLOBAL; GV_POINT_OPERATOR_MODE_LOCAL; } }
		BOOL GV_POINT_USE_DEFORMED { }
	}

	GROUP ID_GVPORTS
	{
		GVGENERALOBJECT GV_POINT_INPUT_OBJECT { INPORT; STATICPORT; CREATEPORT; }
		LONG GV_POINT_INPUT_POINT { INPORT; STATICPORT; CREATEPORT; }
		VECTOR GV_POINT_INPUT_POSITION { INPORT; }

		LONG GV_POINT_OUTPUT_POINT { OUTPORT; STATICPORT; CREATEPORT; }
		VECTOR GV_POINT_OUTPUT_POSITION { OUTPORT; STATICPORT; CREATEPORT; }
		NORMAL GV_POINT_OUTPUT_NORMAL { OUTPORT; }
	}
}
