CONTAINER GVpoly
{
	NAME GVpoly;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
		LONG GV_POLY_MODE { CYCLE { GV_POLY_OPERATOR_MODE_GLOBAL; GV_POLY_OPERATOR_MODE_LOCAL; } }
		BOOL GV_POLY_USE_DEFORMED { }
	}

	GROUP ID_GVPORTS
	{
		GVGENERALOBJECT GV_POLY_INPUT_OBJECT { INPORT; STATICPORT; CREATEPORT; }
		LONG GV_POLY_INPUT_POLY { INPORT; STATICPORT; CREATEPORT; }

		LONG GV_POLY_OUTPUT_POLY { OUTPORT; STATICPORT; CREATEPORT; }
		LONG GV_POLY_OUTPUT_POINT1 { OUTPORT; }
		LONG GV_POLY_OUTPUT_POINT2 { OUTPORT; }
		LONG GV_POLY_OUTPUT_POINT3 { OUTPORT; }
		LONG GV_POLY_OUTPUT_POINT4 { OUTPORT; }
		VECTOR GV_POLY_OUTPUT_NORMAL { OUTPORT; }
		VECTOR GV_POLY_OUTPUT_CENTER { OUTPORT; }
	}
}
