CONTAINER GVray
{
	NAME GVray;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
		BOOL GV_RAY_TEST_ONLY { }
		BOOL GV_RAY_GLOBAL { }
	}

	GROUP ID_GVPORTS
	{
		GVGENERALOBJECT GV_RAY_INPUT_OBJECT { INPORT; STATICPORT; CREATEPORT; }
		VECTOR GV_RAY_INPUT_POINT1 { INPORT; STATICPORT; CREATEPORT; }
		VECTOR GV_RAY_INPUT_POINT2 { INPORT; STATICPORT; CREATEPORT; }
		
		BOOL GV_RAY_OUTPUT { OUTPORT; STATICPORT; CREATEPORT; }
		VECTOR GV_RAY_OUTPUT_HITPOS { OUTPORT; }
		LONG GV_RAY_OUTPUT_FACE_INDEX { OUTPORT; }
		NORMAL GV_RAY_OUTPUT_FACE_NORMAL { OUTPORT; }
		NORMAL GV_RAY_OUTPUT_PHONG_NORMAL { OUTPORT; }
		REAL GV_RAY_OUTPUT_DISTANCE { OUTPORT; }
		BOOL GV_RAY_OUTPUT_BACKFACE { OUTPORT; }
	}
}
