CONTAINER GVrangemapper
{
	NAME GVrangemapper;
	INCLUDE GVdynamic;

	GROUP ID_GVPROPERTIES
	{
		LONG GV_RANGEMAPPER_INPUT_DEFS
		{
			CYCLE
			{
				GV_RANGEMAPPER_INPUT_USER;
				GV_RANGEMAPPER_INPUT_DEGREE;
				GV_RANGEMAPPER_INPUT_RADIANS;
				GV_RANGEMAPPER_INPUT_PERCENT;
				GV_RANGEMAPPER_INPUT_ZERO_TO_ONE;
				GV_RANGEMAPPER_INPUT_ZERO_TO_HUNDRED;
				GV_RANGEMAPPER_INPUT_ZERO_TO_THOUSAND;
			}
		}
		LONG GV_RANGEMAPPER_OUTPUT_DEFS
		{
			CYCLE
			{
				GV_RANGEMAPPER_OUTPUT_USER;
				GV_RANGEMAPPER_OUTPUT_DEGREE;
				GV_RANGEMAPPER_OUTPUT_RADIANS;
				GV_RANGEMAPPER_OUTPUT_PERCENT;
				GV_RANGEMAPPER_OUTPUT_ZERO_TO_ONE;
				GV_RANGEMAPPER_OUTPUT_ZERO_TO_HUNDRED;
				GV_RANGEMAPPER_OUTPUT_ZERO_TO_THOUSAND;
			}
		}
		BOOL GV_RANGEMAPPER_CLAMP_LOWER { }
		BOOL GV_RANGEMAPPER_CLAMP_UPPER { }
		BOOL GV_RANGEMAPPER_MODULO { }
		BOOL GV_RANGEMAPPER_REVERSE { }
		BOOL GV_RANGEMAPPER_USE_SPLINE { }
	}

	GROUP ID_GVPORTS
	{
		DYNAMIC GV_RANGEMAPPER_INPUT		{ INPORT;  STATICPORT; CREATEPORT; }
		DYNAMIC GV_RANGEMAPPER_RANGE11  { INPORT;  EDITPORT;  }
		DYNAMIC GV_RANGEMAPPER_RANGE12  { INPORT;  EDITPORT; }
		DYNAMIC GV_RANGEMAPPER_RANGE21  { INPORT;  EDITPORT; }
		DYNAMIC GV_RANGEMAPPER_RANGE22  { INPORT;  EDITPORT; }
		SPLINE GV_RANGEMAPPER_SPLINE		{ INPORT;  EDITPORT; SHOWGRID_H; SHOWGRID_V; EDIT_H; EDIT_V; }

		DYNAMIC GV_RANGEMAPPER_OUTPUT		{ OUTPORT; STATICPORT; CREATEPORT; }
	}
}
