CONTAINER GVreal2vect
{
	NAME GVreal2vect;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		REAL GV_REAL2VECT_INPUT_X { INPORT; STATICPORT; CREATEPORT; }
		REAL GV_REAL2VECT_INPUT_Y { INPORT; STATICPORT; CREATEPORT; }
		REAL GV_REAL2VECT_INPUT_Z { INPORT; STATICPORT; CREATEPORT; }

		VECTOR GV_REAL2VECT_OUTPUT_VECTOR { OUTPORT; STATICPORT; CREATEPORT; }
	}
}
