CONTAINER GVresult
{
	NAME GVresult;
	INCLUDE GVdynamic;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		DYNAMIC GV_RESULT_INPUT  { INPORT; STATICPORT; CREATEPORT; }
		DYNAMIC GV_RESULT_OUTPUT { OUTPORT; STATICPORT; CREATEPORT; HIDDEN; }
	}
}
