CONTAINER GVselection
{
	NAME GVselection;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		GVGENERALTAG GV_SELECTION_INPUT_TAG { INPORT; STATICPORT; CREATEPORT; }
		BOOL GV_SELECTION_OPERATOR_ON { INPORT; }

		LONG GV_SELECTION_OUTPUT { OUTPORT; STATICPORT; CREATEPORT; ITERATOR; }
		LONG GV_SELECTION_OUTPUT_COUNT { OUTPORT; }
	}
}
