CONTAINER GVsound
{
	NAME GVsound;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
		FILENAME GV_SOUND_FILENAME { }
		LONG GV_SOUND_PROBE { MIN 0; MAX 1024; }
	}

	GROUP ID_GVPORTS
	{
		BOOL GV_SOUND_PLAY  { INPORT; }
		BASETIME GV_SOUND_TIME  { INPORT; }
		LONG GV_SOUND_SAMPLE  { INPORT; }

		LONG GV_SOUND_OUTPUT_LEFT { OUTPORT; }
		LONG GV_SOUND_OUTPUT_RIGHT { OUTPORT; }
		BASETIME GV_SOUND_LENGTH { OUTPORT; } 
		LONG GV_SOUND_SAMPLES { OUTPORT; }

		LONG GV_SOUND_FFT_RES
		{
			CYCLE
			{
				GV_SOUND_FFT_RES_4;
				GV_SOUND_FFT_RES_8;
				GV_SOUND_FFT_RES_16;
				GV_SOUND_FFT_RES_32;
				GV_SOUND_FFT_RES_64;
				GV_SOUND_FFT_RES_128;
				GV_SOUND_FFT_RES_256;
				GV_SOUND_FFT_RES_512;
				GV_SOUND_FFT_RES_1024;
				GV_SOUND_FFT_RES_2048;
				GV_SOUND_FFT_RES_4096;
				GV_SOUND_FFT_RES_8192;
			}
		}

		LONG GV_SOUND_FFT_BIN { INPORT; }

		REAL GV_SOUND_FFT_BIN_LEFT { OUTPORT; }
		REAL GV_SOUND_FFT_BIN_RIGHT { OUTPORT; }
	}
}
