CONTAINER GVspline
{
	NAME GVspline;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
		LONG GV_SPLINE_MODE { CYCLE { GV_SPLINE_OPERATOR_MODE_GLOBAL; GV_SPLINE_OPERATOR_MODE_LOCAL; } }
		BOOL GV_SPLINE_USE_NATURAL { }
		BOOL GV_SPLINE_ALL_SEGMENTS { }
	}

	GROUP ID_GVPORTS
	{
		GVGENERALOBJECT GV_SPLINE_INPUT_OBJECT { INPORT; STATICPORT; CREATEPORT; }
		REAL GV_SPLINE_INPUT_POINT { INPORT; STATICPORT; CREATEPORT; UNIT PERCENT; MIN 0; MAX 100; }
		LONG GV_SPLINE_INPUT_SEGMENT { INPORT; MIN 0; }

		VECTOR GV_SPLINE_OUTPUT_POSITION { OUTPORT; CREATEPORT; }
		VECTOR GV_SPLINE_OUTPUT_TANGENT { OUTPORT; }
		REAL GV_SPLINE_OUTPUT_LENGTH { OUTPORT; }
		BOOL GV_SPLINE_OUTPUT_IS_CLOSED { OUTPORT; }
		LONG GV_SPLINE_OUTPUT_SEGMENTS { OUTPORT; }
	}
}
