CONTAINER GVtag
{
	NAME GVtag;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
		SCALE_V;
		LONG GV_TAG_TYPE { }
		IN_EXCLUDE GV_TAG_EXCLUDE_ID { NUM_FLAGS 0; INIT_STATE 0; IMAGE_01_ON 1009316; IMAGE_01_OFF 1009320; ACCEPT { Tbase; } }
	}

	GROUP ID_GVPORTS
	{
		GVGENERALOBJECT GV_TAG_INPUT_OBJECT { INPORT; STATICPORT; CREATEPORT; }
		LONG GV_TAG_INPUT_START { INPORT; }
		LONG GV_TAG_INPUT_COUNT { INPORT; }
		BOOL GV_TAG_OPERATOR_ON { INPORT; }

		GVGENERALTAG GV_TAG_OUTPUT_TAG { OUTPORT; STATICPORT; CREATEPORT; ITERATOR; }
		LONG GV_TAG_OUTPUT_COUNT { OUTPORT; }
	}
}
