CONTAINER GVtime
{
	NAME GVtime;
	INCLUDE GVbase;

	GROUP ID_GVPORTS
	{
		BASETIME GV_TIME_OPERATOR_OUTPUT_TIME 			{ OUTPORT; CREATEPORT; }
		REAL GV_TIME_OPERATOR_OUTPUT_REAL						{ OUTPORT; }
		LONG GV_TIME_OPERATOR_OUTPUT_FRAME					{ OUTPORT; }
		LONG GV_TIME_OPERATOR_OUTPUT_FPS						{ OUTPORT; }
		BASETIME GV_TIME_OPERATOR_OUTPUT_START			{ OUTPORT; }
		BASETIME GV_TIME_OPERATOR_OUTPUT_END				{ OUTPORT; }
		BASETIME GV_TIME_OPERATOR_OUTPUT_LOOP_START	{ OUTPORT; }
		BASETIME GV_TIME_OPERATOR_OUTPUT_LOOP_END		{ OUTPORT; }
		BASETIME GV_TIME_OPERATOR_OUTPUT_DELTA			{ OUTPORT; }
		BASETIME GV_TIME_OPERATOR_OUTPUT_PREVIOUS		{ OUTPORT; }
	}
}
