CONTAINER GVtrack
{
	NAME GVtrack;
	INCLUDE GVbase;
	
	GROUP ID_GVPROPERTIES
	{
		LINK GV_TRACK_LINK { ACCEPT { CTbase; } }
	}
	
	GROUP ID_GVPORTS
	{
		BASETIME GV_TRACK_INPUT_TIME { INPORT; STATICPORT; CREATEPORT; }
		DYNAMIC GV_TRACK_OUTPUT_VALUE { OUTPORT; STATICPORT; CREATEPORT; }
	}
}
