CONTAINER GVvertexcolormap
{
	NAME GVvertexcolormap;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		GVGENERALTAG GV_VERTEXCOLORMAP_INPUT_TAG { INPORT; STATICPORT; CREATEPORT; }
		LONG GV_VERTEXCOLORMAP_INPUT_INDEX { INPORT; STATICPORT; CREATEPORT; }
		VECTOR GV_VERTEXCOLORMAP_INPUT_VALUE_COLOR { INPORT; }
		REAL GV_VERTEXCOLORMAP_INPUT_VALUE_ALPHA { INPORT; }

		VECTOR GV_VERTEXCOLORMAP_OUTPUT_VALUE_COLOR { OUTPORT; STATICPORT; CREATEPORT; }
		REAL GV_VERTEXCOLORMAP_OUTPUT_VALUE_ALPHA { OUTPORT; STATICPORT; CREATEPORT; }
		LONG GV_VERTEXCOLORMAP_OUTPUT_COUNT { OUTPORT; }
	}
}
