CONTAINER GVvectcalcmat
{
	NAME GVvectcalcmat;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
		LONG GV_VECTCALCMAT_TYPE 
		{
			CYCLE
			{
				TYPE_XAXIS;
				TYPE_YAXIS;
				TYPE_ZAXIS;
			}
		}
	}

	GROUP ID_GVPORTS
	{
		NORMAL GV_VECTCALCMAT_INPUT  { INPORT; STATICPORT; CREATEPORT; }
		MATRIX GV_VECTCALCMAT_OUTPUT { OUTPORT; STATICPORT; CREATEPORT; }
	}
}
