CONTAINER GVvect2matrix
{
	NAME GVvect2matrix;
	INCLUDE GVbase;

	GROUP ID_GVPORTS
	{
		VECTOR GV_VECT2MATRIX_OFF	{ INPORT; STATICPORT; CREATEPORT; }
		VECTOR GV_VECT2MATRIX_V1	{ INPORT; STATICPORT; CREATEPORT; }
		VECTOR GV_VECT2MATRIX_V2	{ INPORT; STATICPORT; CREATEPORT; }
		VECTOR GV_VECT2MATRIX_V3	{ INPORT; STATICPORT; CREATEPORT; }
		MATRIX GV_VECT2MATRIX_OUT	{ OUTPORT; STATICPORT; CREATEPORT; }
	}
}
