CONTAINER GVweightmap
{
	NAME GVweightmap;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
	}

	GROUP ID_GVPORTS
	{
		GVGENERALTAG GV_WEIGHTMAP_INPUT_TAG { INPORT; STATICPORT; CREATEPORT; }
		LONG GV_WEIGHTMAP_INPUT_INDEX { INPORT; STATICPORT; CREATEPORT; }
		REAL GV_WEIGHTMAP_INPUT_VALUE { INPORT; }

		REAL GV_WEIGHTMAP_OUTPUT_VALUE { OUTPORT; STATICPORT; CREATEPORT; }
		LONG GV_WEIGHTMAP_OUTPUT_COUNT { OUTPORT; }
	}
}
