CONTAINER XSLAGradient
{
  NAME XSLAGradient;

  INCLUDE Mpreview;
  INCLUDE Xbase;

  GROUP ID_SHADERPROPERTIES
  {
    GRADIENT SLA_GRADIENT_GRADIENT { ICC_BASEDOCUMENT; }
    LONG SLA_GRADIENT_TYPE
    {
      CYCLE
      {
        SLA_GRADIENT_TYPE_2D_U;
        SLA_GRADIENT_TYPE_2D_V;
        SLA_GRADIENT_TYPE_2D_DIAG;
        SLA_GRADIENT_TYPE_2D_RAD;
        SLA_GRADIENT_TYPE_2D_CIRC;
        SLA_GRADIENT_TYPE_2D_BOX;
        SLA_GRADIENT_TYPE_2D_STAR;
        SLA_GRADIENT_TYPE_2D_FOUR_CORNER;
        SLA_GRADIENT_TYPE_3D_LINEAR;
        SLA_GRADIENT_TYPE_3D_CYLINDRICAL;
        SLA_GRADIENT_TYPE_3D_SPHERICAL;
      }
    }
    BOOL SLA_GRADIENT_CYCLE { }
    VECTOR SLA_GRADIENT_START { UNIT METER; }
    VECTOR SLA_GRADIENT_END { UNIT METER; }
    REAL SLA_GRADIENT_RADIUS { UNIT METER; }
    REAL SLA_GRADIENT_TURBULENCE { UNIT PERCENT; MIN 0; MAX 100; }
    REAL SLA_GRADIENT_OCTAVES { MIN 0; MAX 10; STEP .1; }
    REAL SLA_GRADIENT_SCALE { UNIT PERCENT; MIN 0; }
    REAL SLA_GRADIENT_FREQ { }
    LONG SLA_GRADIENT_SEED { }
    REAL SLA_GRADIENT_ANGLE { UNIT DEGREE; }
    BOOL SLA_GRADIENT_ABSOLUTE { }

    LONG SLA_GRADIENT_SPACE 
    {
      CYCLE
      {
        SLA_GRADIENT_SPACE_TEXTURE;
        SLA_GRADIENT_SPACE_OBJECT;
        SLA_GRADIENT_SPACE_WORLD;
        SLA_GRADIENT_SPACE_CAMERA;
        SLA_GRADIENT_SPACE_SCREEN;
        SLA_GRADIENT_SPACE_RASTER;
      }
    }
  }
}