CONTAINER XSLASpline
{
  NAME XSLASpline;

  INCLUDE Mpreview;
  INCLUDE Xbase;

  GROUP ID_SHADERPROPERTIES
  {
    LINK SLA_SPLINE_OBJECT { }
    SHADERLINK SLA_SPLINE_BACKGROUND_COLOR { }
    SHADERLINK SLA_SPLINE_LINE_COLOR { }
    SHADERLINK SLA_SPLINE_FILLET_COLOR { }

    REAL SLA_SPLINE_X_OFFSET { UNIT PERCENT; MIN -100000; MAX 100000; MINSLIDER -100; MAXSLIDER 100; CUSTOMGUI REALSLIDER;  }
    REAL SLA_SPLINE_Y_OFFSET { UNIT PERCENT; MIN -100000; MAX 100000; MINSLIDER -100; MAXSLIDER 100; CUSTOMGUI REALSLIDER;  }
    REAL SLA_SPLINE_X_SCALE { UNIT PERCENT; MIN -100000; MAX 100000; MINSLIDER -100; MAXSLIDER 100; CUSTOMGUI REALSLIDER;  }
    REAL SLA_SPLINE_Y_SCALE { UNIT PERCENT; MIN -100000; MAX 100000; MINSLIDER -100; MAXSLIDER 100; CUSTOMGUI REALSLIDER;  }
    LONG SLA_SPLINE_USE_PLANE
    {
      CYCLE
      {
        SLA_SPLINE_USE_PLANE_XY;
        SLA_SPLINE_USE_PLANE_XZ;
        SLA_SPLINE_USE_PLANE_YZ;
      }
    }
    BOOL SLA_SPLINE_SINGLE_PIXEL_WIDTH { } 
    REAL SLA_SPLINE_LINE_WIDTH { UNIT PERCENT; MIN 0; MAX 10000; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER;  }
    REAL SLA_SPLINE_SMOOTH_WIDTH { UNIT PERCENT; MIN 0; MAX 10000; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER;  }
    BOOL SLA_SPLINE_HAS_CAPS { }
    BOOL SLA_SPLINE_FILL { }
    BOOL SLA_SPLINE_FILL_COLOR { }
		REAL SLA_SPLINE_BUMP_WIDTH { UNIT PERCENT; MIN 0; MAX 10000; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER; }

    BOOL SLA_SPLINE_TEXT { }

		STRING SLA_SPLINE_TEXT_TEXT { CUSTOMGUI MULTISTRING; }
		FONT SLA_SPLINE_TEXT_FONT { }
    LONG SLA_SPLINE_TEXT_ALIGN { CYCLE { SLA_SPLINE_TEXT_ALIGN_LEFT;SLA_SPLINE_TEXT_ALIGN_MIDDLE;SLA_SPLINE_TEXT_ALIGN_RIGHT;}}
    REAL SLA_SPLINE_TEXT_HEIGHT { UNIT METER; } 
    REAL SLA_SPLINE_TEXT_HSPACING { UNIT METER; }
    REAL SLA_SPLINE_TEXT_VSPACING { UNIT METER; }
  }
}