CONTAINER XSLATiles
{
  NAME XSLATiles;

  INCLUDE Mpreview;
  INCLUDE Xbase;

  GROUP ID_SHADERPROPERTIES
  {
    COLOR     SLA_TILES_GROUT_COLOR { }
    COLOR     SLA_TILES_TILE_COLOR_1 { }
    COLOR     SLA_TILES_TILE_COLOR_2 { }
    COLOR     SLA_TILES_TILE_COLOR_3 { }
    LONG SLA_TILES_PATTERN
    {
      CYCLE
      {
        SLA_TILES_PATTERN_BRICK1;
        SLA_TILES_PATTERN_BRICK2;
        SLA_TILES_PATTERN_CIRCLES1;
        SLA_TILES_PATTERN_CIRCLES2;
        SLA_TILES_PATTERN_CIRCLES3;
        SLA_TILES_PATTERN_HEXAGONS;
        SLA_TILES_PATTERN_LINES1;
        SLA_TILES_PATTERN_LINES2;
        SLA_TILES_PATTERN_PARQUET;
        SLA_TILES_PATTERN_PLANKS;
        SLA_TILES_PATTERN_RADIAL_LINES1;
        SLA_TILES_PATTERN_RADIAL_LINES2;
        SLA_TILES_PATTERN_RANDOM;
        SLA_TILES_PATTERN_RINGS1;
        SLA_TILES_PATTERN_RINGS2;
        SLA_TILES_PATTERN_SAWTOOTH1;
        SLA_TILES_PATTERN_SAWTOOTH2;
        SLA_TILES_PATTERN_SCALES1;
        SLA_TILES_PATTERN_SCALES2;
        SLA_TILES_PATTERN_SPIRAL1;
        SLA_TILES_PATTERN_SPIRAL2;
        SLA_TILES_PATTERN_SQUARES;
        SLA_TILES_PATTERN_TRIANGLES1;
        SLA_TILES_PATTERN_TRIANGLES2;
        SLA_TILES_PATTERN_TRIANGLES3;
        SLA_TILES_PATTERN_WAVES1;
        SLA_TILES_PATTERN_WAVES2;
        SLA_TILES_PATTERN_WEAVE;
      }
    }
    REAL        SLA_TILES_GROUT_WIDTH { UNIT PERCENT; MIN 0.0; MAX 100.0; }
    REAL        SLA_TILES_BEVEL_WIDTH { UNIT PERCENT; MIN 0.0; MAX 100.0; }
    BOOL        SLA_TILES_SMOOTH_BEVEL { }
    BOOL        SLA_TILES_RANDOMIZE_COLOR { }
    LONG        SLA_TILES_ORIENTATION
    {
      CYCLE
      {
        SLA_TILES_ORIENTATION_U;
        SLA_TILES_ORIENTATION_V;
      }
    }
    REAL        SLA_TILES_GLOBAL_SCALE { UNIT PERCENT; MIN 0.0; }
    REAL        SLA_TILES_U_SCALE { UNIT PERCENT; MIN 0.0; }
    REAL        SLA_TILES_V_SCALE { UNIT PERCENT; MIN 0.0; }
    REAL        SLA_TILES_RADIAL_SCALE { UNIT PERCENT; MIN 0.0;; }
    REAL        SLA_TILES_ROTATE { UNIT DEGREE; }
    REAL        SLA_TILES_DELTA { UNIT PERCENT; MIN 0.0; }
    LONG				SLA_TILES_SEED { }
  }
}