CONTAINER XSLAProjector
{
  NAME XSLAProjector;

  INCLUDE Mpreview;
  INCLUDE Xbase;

  GROUP ID_SHADERPROPERTIES
  {
    SHADERLINK SLA_PROJECTOR_TEXTURE { }

    LONG SLA_PROJECTOR_PROJECTION
    {
      CYCLE
      {
        SLA_PROJECTOR_PROJECTION_SPHERICAL;
        SLA_PROJECTOR_PROJECTION_CYLINDRICAL;
        SLA_PROJECTOR_PROJECTION_FLAT;
        SLA_PROJECTOR_PROJECTION_CUBIC;
        SLA_PROJECTOR_PROJECTION_FRONTAL;
        SLA_PROJECTOR_PROJECTION_SPATIAL;
        SLA_PROJECTOR_PROJECTION_UVW;
        SLA_PROJECTOR_PROJECTION_SHRINKWRAP;
      }
    }
    //BOOL SLA_PROJECTOR_TILE_UV { }
    REAL SLA_PROJECTOR_OFFSET_X { UNIT PERCENT; }
    REAL SLA_PROJECTOR_OFFSET_Y { UNIT PERCENT; }
    REAL SLA_PROJECTOR_LENGTH_X { UNIT PERCENT; }
    REAL SLA_PROJECTOR_LENGTH_Y { UNIT PERCENT; }
    REAL SLA_PROJECTOR_TILES_X { }
    REAL SLA_PROJECTOR_TILES_Y { }
    BOOL SLA_PROJECTOR_TILE { }
    BOOL SLA_PROJECTOR_SEAMLESS { }
    VECTOR SLA_PROJECTOR_POSITION { UNIT METER; }
    VECTOR SLA_PROJECTOR_SIZE { UNIT PERCENT; }
    VECTOR SLA_PROJECTOR_ROTATION { UNIT DEGREE; }
    BUTTON SLA_PROJECTOR_PASTE_TAG { }
  }
}