CONTAINER XSLAFilter
{
	NAME XSLAFilter;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		SHADERLINK SLA_FILTER_TEXTURE { }
		REAL SLA_FILTER_HUE { CUSTOMGUI REALSLIDER; UNIT DEGREE; MIN 0; MAX 360; MINSLIDER 0; MAXSLIDER 360; }
		REAL SLA_FILTER_SATURATION { CUSTOMGUI REALSLIDER; UNIT PERCENT; MIN -100; MAX 100; MINSLIDER -100; MAXSLIDER 100; }
		REAL SLA_FILTER_LIGHTNESS { CUSTOMGUI REALSLIDER; UNIT PERCENT; MIN -100; MAX 100; MINSLIDER -100; MAXSLIDER 100; CUSTOMGUI REALSLIDER; }
		BOOL SLA_FILTER_COLORIZE { }
		REAL SLA_FILTER_BRIGHNESS { UNIT PERCENT; MIN -100; MAX 100; CUSTOMGUI REALSLIDER;  }
		REAL SLA_FILTER_CONTRAST { UNIT PERCENT; MIN -100; MAX 100; CUSTOMGUI REALSLIDER;  }
		REAL SLA_FILTER_GAMMA { MIN .1; MAX 100; MAXSLIDER 10; STEP 0.01; CUSTOMGUI REALSLIDER;  }
		BOOL SLA_FILTER_CLIPPING { }
		REAL SLA_FILTER_LOW_CLIP { UNIT PERCENT; MIN 0; MAX 10000; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER;  }
		REAL SLA_FILTER_HIGH_CLIP { UNIT PERCENT; MIN 0; MAX 10000; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER;  }

		GROUP SLA_FILTER_GRADING
		{
			DEFAULT 1;

			BOOL		SLA_FILTER_GRADING_ENABLED				{  }
			REAL		SLA_FILTER_GRADING_INTENSITY			{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
			SPLINE	SLA_FILTER_GRADING_CURVE_RGB			{  }

			SEPARATOR																	{ LINE; }

			SPLINE	SLA_FILTER_GRADING_CURVE_R				{  }
			SPLINE	SLA_FILTER_GRADING_CURVE_G				{  }
			SPLINE	SLA_FILTER_GRADING_CURVE_B				{  }
		}
	}
}