CONTAINER XSLAFresnel
{
	NAME XSLAFresnel;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		BOOL	SLA_FRESNEL_USE_BUMP 			{  }
		LONG SLA_FRESNEL_RENDER
		{
			CYCLE
			{
				SLA_FRESNEL_RENDER_FRONT_ONLY;
				SLA_FRESNEL_RENDER_FRONT_TRANS;
				SLA_FRESNEL_RENDER_BACK_ONLY;
				SLA_FRESNEL_RENDER_BACK_TRANS;
				SLA_FRESNEL_RENDER_FRONT_BACK;
			}
		}
		GRADIENT SLA_FRESNEL_GRADIENT 	{ ICC_BASEDOCUMENT; }

		SEPARATOR												{ LINE; }

		BOOL	SLA_FRESNEL_PHY_ENABLE		{  }

		GROUP
		{
			COLUMNS 2;

			REAL		SLA_FRESNEL_PHY_IOR		{ UNIT REAL; MIN 1.0; STEP 0.01; }
			LONG		SLA_FRESNEL_PHY_IOR_PRESET
			{
				CYCLE
				{
					SLA_FRESNEL_PHY_IOR_PRESET_CUSTOM;
					SLA_FRESNEL_PHY_IOR_PRESET_ASPHALT;
					SLA_FRESNEL_PHY_IOR_PRESET_BEER;
					SLA_FRESNEL_PHY_IOR_PRESET_BRONZE;
					SLA_FRESNEL_PHY_IOR_PRESET_COPPER;
					SLA_FRESNEL_PHY_IOR_PRESET_DIAMOND;
					SLA_FRESNEL_PHY_IOR_PRESET_EMERALD;
					SLA_FRESNEL_PHY_IOR_PRESET_ETHANOL;
					SLA_FRESNEL_PHY_IOR_PRESET_GLASS;
					SLA_FRESNEL_PHY_IOR_PRESET_HEAVYFLINTGLASS;
					SLA_FRESNEL_PHY_IOR_PRESET_IRON;
					SLA_FRESNEL_PHY_IOR_PRESET_JADE;
					SLA_FRESNEL_PHY_IOR_PRESET_MILK;
					SLA_FRESNEL_PHY_IOR_PRESET_MOONSTONE;
					SLA_FRESNEL_PHY_IOR_PRESET_OIL_VEGETABLE;
					SLA_FRESNEL_PHY_IOR_PRESET_OPAL;
					SLA_FRESNEL_PHY_IOR_PRESET_PEARL;
					SLA_FRESNEL_PHY_IOR_PRESET_PLASTIC;
					SLA_FRESNEL_PHY_IOR_PRESET_PET;
					SLA_FRESNEL_PHY_IOR_PRESET_PLEXIGLASS;
					SLA_FRESNEL_PHY_IOR_PRESET_RUBBER;
					SLA_FRESNEL_PHY_IOR_PRESET_RUBY;
					SLA_FRESNEL_PHY_IOR_PRESET_SALT;
					SLA_FRESNEL_PHY_IOR_PRESET_SAPPHIRE;
					SLA_FRESNEL_PHY_IOR_PRESET_TEFLON;
					SLA_FRESNEL_PHY_IOR_PRESET_TITANIUM;
					SLA_FRESNEL_PHY_IOR_PRESET_TOPAZ;
					SLA_FRESNEL_PHY_IOR_PRESET_WATER;
					SLA_FRESNEL_PHY_IOR_PRESET_WATER_ICE;
					SLA_FRESNEL_PHY_IOR_PRESET_WHISKEY;
					SLA_FRESNEL_PHY_IOR_PRESET_WOOD;
				}
			}
		}
		BOOL		SLA_FRESNEL_PHY_INVERT	{  }
  }
}
