CONTAINER XSLAFalloff
{
  NAME XSLAFalloff;

  INCLUDE Mpreview;
  INCLUDE Xbase;

  GROUP ID_SHADERPROPERTIES
  {
    VECTOR SLA_FALLOFF_VECTOR { }
    LONG SLA_FALLOFF_SPACE
    {
      CYCLE
      {
        SLA_FALLOFF_SPACE_OBJECT;
        SLA_FALLOFF_SPACE_WORLD;
        SLA_FALLOFF_SPACE_CAMERA;
      }
    }
    BOOL SLA_FALLOFF_USE_BUMP { }

    GRADIENT SLA_FALLOFF_GRADIENT { ICC_BASEDOCUMENT; }
  }
}