CONTAINER XSLABanzi
{
  NAME XSLABanzi;
  INCLUDE Mpreview;
	INCLUDE Mbase;

  GROUP Obaselist
  {
    BOOL SLA_BANZI_WOOD { PARENTMSG ID_BANZI_WOOD; }
    BOOL SLA_BANZI_DIFFUSE { PARENTMSG ID_BANZI_DIFFUSE; }
    BOOL SLA_BANZI_SPECULAR1 { PARENTMSG ID_BANZI_SPECULAR1; }
    BOOL SLA_BANZI_SPECULAR2 { PARENTMSG ID_BANZI_SPECULAR2; }
    BOOL SLA_BANZI_SPECULAR3 { PARENTMSG ID_BANZI_SPECULAR3; }
    BOOL SLA_BANZI_REFLECTION { PARENTMSG ID_BANZI_REFLECTION; }
    BOOL SLA_BANZI_ENVIRONMENT { PARENTMSG ID_BANZI_ENVIRONMENT; }
    BOOL SLA_BANZI_AMBIENT { PARENTMSG ID_BANZI_AMBIENT; }
    BOOL SLA_BANZI_ROUGHNESS { PARENTMSG ID_BANZI_ROUGHNESS; }
    BOOL SLA_BANZI_ANISOTROPY { PARENTMSG ID_BANZI_ANISOTROPY; }
  }
  GROUP ID_BANZI_WOOD
  {
    GRADIENT SLA_BANZI_WOOD_GRADIENT { ICC_BASEDOCUMENT; }
    REAL SLA_BANZI_WOOD_RING_INTENSITY { UNIT PERCENT; }
    REAL SLA_BANZI_WOOD_RING_SCALE { UNIT PERCENT; MIN 0; }
    REAL SLA_BANZI_WOOD_RING_TURBULENCE { UNIT PERCENT; MIN 0; }
    REAL SLA_BANZI_WOOD_TURBULENCE_SCALE { UNIT PERCENT; MIN 0; }
    REAL SLA_BANZI_WOOD_RING_VARIANCE { UNIT PERCENT; MIN 0; }
    REAL SLA_BANZI_WOOD_CORE_VARIANCE { UNIT PERCENT; MIN 0; }
    REAL SLA_BANZI_WOOD_VARIANCE_SCALE { UNIT PERCENT; MIN 0; }
    REAL SLA_BANZI_WOOD_RADIAL_VARIANCE { UNIT PERCENT; MIN 0; }
    REAL SLA_BANZI_WOOD_RADIAL_VARIANCE_SCALE { UNIT PERCENT; MIN 0; }
    REAL SLA_BANZI_WOOD_GRAIN_INTENSITY { UNIT PERCENT; }
    REAL SLA_BANZI_WOOD_GRAIN_SCALE { UNIT PERCENT; MIN 0; }
    REAL SLA_BANZI_WOOD_ATTENUATION { UNIT PERCENT; MIN 0; }
  }
  GROUP ID_BANZI_DIFFUSE
  {
    COLOR SLA_BANZI_DIFFUSE_SURF_COLOR { }
    LONG SLA_BANZI_DIFFUSE_ALGORITHM
    {
      CYCLE
      {
        SLA_BANZI_DIFFUSE_ALGORITHM_INTERNAL;
        SLA_BANZI_DIFFUSE_ALGORITHM_OREN_NAYAR;
      }
    }
    REAL SLA_BANZI_DIFFUSE_ROUGHNESS { UNIT PERCENT; MIN 0; MAX 200; }
    REAL SLA_BANZI_DIFFUSE_SURF_ILLUMINATION { UNIT PERCENT; MIN 0; MAX 1000; }
    REAL SLA_BANZI_DIFFUSE_CONTRAST { UNIT PERCENT; MIN -1000; MAX 1000; }
  }
  GROUP ID_BANZI_SPECULAR1
  {
    COLOR SLA_BANZI_SPEC1_COLOR { };
    REAL SLA_BANZI_SPEC1_INTENSITY { UNIT PERCENT; MIN 0; MAX 1000; }
    REAL SLA_BANZI_SPEC1_SIZE { UNIT PERCENT; MIN 0; MAX 200; }
    REAL SLA_BANZI_SPEC1_CONTRAST { UNIT PERCENT; MIN 0; MAX 100; }
    REAL SLA_BANZI_SPEC1_GLARE { UNIT PERCENT; MIN 0; MAX 1000; }
    REAL SLA_BANZI_SPEC1_FALLOFF { UNIT PERCENT; MIN 0; }
  }
  GROUP ID_BANZI_SPECULAR2
  {
    COLOR SLA_BANZI_SPEC2_COLOR { };
    REAL SLA_BANZI_SPEC2_INTENSITY { UNIT PERCENT; MIN 0; MAX 1000; }
    REAL SLA_BANZI_SPEC2_SIZE { UNIT PERCENT; MIN 0; MAX 200; }
    REAL SLA_BANZI_SPEC2_CONTRAST { UNIT PERCENT; MIN 0; MAX 100; }
    REAL SLA_BANZI_SPEC2_GLARE { UNIT PERCENT; MIN 0; MAX 1000; }
    REAL SLA_BANZI_SPEC2_FALLOFF { UNIT PERCENT; MIN 0; }
  }
  GROUP ID_BANZI_SPECULAR3
  {
    COLOR SLA_BANZI_SPEC3_COLOR { };
    REAL SLA_BANZI_SPEC3_INTENSITY { UNIT PERCENT; MIN 0; MAX 1000; }
    REAL SLA_BANZI_SPEC3_SIZE { UNIT PERCENT; MIN 0; MAX 200; }
    REAL SLA_BANZI_SPEC3_CONTRAST { UNIT PERCENT; MIN 0; MAX 100; }
    REAL SLA_BANZI_SPEC3_GLARE { UNIT PERCENT; MIN 0; MAX 1000; }
    REAL SLA_BANZI_SPEC3_FALLOFF { UNIT PERCENT; MIN 0; }
  }
  GROUP ID_BANZI_REFLECTION
  {
    REAL SLA_BANZI_REFLECTION_INTENSITY { UNIT PERCENT; MIN 0; MAX 1000; }
    REAL SLA_BANZI_REFLECTION_EDGE_INTENSITY { UNIT PERCENT; MIN 0; MAX 1000; }
    REAL SLA_BANZI_REFLECTION_FALLOFF { UNIT PERCENT; MIN 0; }
    SEPARATOR { LINE; }
    COLOR SLA_BANZI_REFLECTION_REFLECTION_COLOR { }
    COLOR SLA_BANZI_REFLECTION_EDGE_COLOR { }
  }
  GROUP ID_BANZI_ENVIRONMENT
  {
    SHADERLINK SLA_BANZI_ENVIRONMENT_IMAGE { }
    REAL SLA_BANZI_ENVIRONMENT_INTENSITY { UNIT PERCENT; MIN 0; MAX 1000; }
    REAL SLA_BANZI_ENVIRONMENT_GLARE { UNIT PERCENT; MIN 0; MAX 1000; }
    REAL SLA_BANZI_ENVIRONMENT_FALLOFF { UNIT PERCENT; MIN 0; }
    SEPARATOR { LINE; }
    BOOL SLA_BANZI_ENVIRONMENT_UTILIZE_ANISO_SCRATCHES { }
    REAL SLA_BANZI_ENVIRONMENT_BLUR { UNIT PERCENT; MIN 0; MAX 100; }
    LONG SLA_BANZI_ENVIRONMENT_SAMPLES { MIN 1; }
    REAL SLA_BANZI_ENVIRONMENT_JITTER { UNIT PERCENT; MIN 0; MAX 1000; }
    SEPARATOR { LINE; }
    COLOR SLA_BANZI_ENVIRONMENT_ENVIRONMENT_COLOR { }
    COLOR SLA_BANZI_ENVIRONMENT_EDGE_COLOR { }
  }
  GROUP ID_BANZI_AMBIENT
  {
    COLOR SLA_BANZI_AMBIENT_COLOR { }
    REAL SLA_BANZI_AMBIENT_INTENSITY { UNIT PERCENT; MIN 0; MAX 1000; }
    REAL SLA_BANZI_AMBIENT_EDGE_INTENSITY { UNIT PERCENT; MIN 0; MAX 1000; }
    REAL SLA_BANZI_AMBIENT_FALLOFF { UNIT PERCENT; MIN 0; }
  }
  GROUP ID_BANZI_ROUGHNESS
  {
    REAL SLA_BANZI_ROUGHNESS_AMPLITUDE { UNIT PERCENT; MIN -1000; MAX 1000; }
    REAL SLA_BANZI_ROUGHNESS_DELTA { UNIT PERCENT; MIN 0; }
    SEPARATOR { LINE; }
    REAL SLA_BANZI_ROUGHNESS_LOW_CLIP { UNIT PERCENT; MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER; }
    REAL SLA_BANZI_ROUGHNESS_HIGH_CLIP { UNIT PERCENT; MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER; }
    SEPARATOR { LINE; }
    COLOR SLA_BANZI_ROUGHNESS_GRIT_COLOR { }
    REAL SLA_BANZI_ROUGHNESS_GRIT_INTENSITY { UNIT PERCENT; MIN -200; MAX 200; MINSLIDER -200; MAXSLIDER 200; CUSTOMGUI REALSLIDER; }
    REAL SLA_BANZI_ROUGHNESS_GRIT_LOW_CLIP { UNIT PERCENT; MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER; }
    REAL SLA_BANZI_ROUGHNESS_GRIT_HIGH_CLIP { UNIT PERCENT; MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER; }
  }
  GROUP ID_BANZI_ANISOTROPY
  {
    LONG SLA_BANZI_ANISOTROPY_PROJECTION
    {
      CYCLE
      {
        SLA_BANZI_ANISOTROPY_PROJECTION_PLANAR;
        SLA_BANZI_ANISOTROPY_PROJECTION_AUTO_PLANAR;
        SLA_BANZI_ANISOTROPY_PROJECTION_SHRINK_WRAP;
        SLA_BANZI_ANISOTROPY_PROJECTION_RADIAL_AUTO_PLANAR;
        SLA_BANZI_ANISOTROPY_PROJECTION_RAD_PATTERN_AUTO_PLANAR;
        SLA_BANZI_ANISOTROPY_PROJECTION_RADIAL_PLANAR;
        SLA_BANZI_ANISOTROPY_PROJECTION_RAD_PATTERN_PLANAR;
      }
    }
    REAL SLA_BANZI_ANISOTROPY_PROJ_SCALE { UNIT PERCENT; MIN 0; MAX 1000; }
    SEPARATOR { LINE; }
    REAL SLA_BANZI_ANISOTROPY_X_ROUGH { UNIT PERCENT; MIN 0; }
    REAL SLA_BANZI_ANISOTROPY_Y_ROUGH { UNIT PERCENT; MIN 0; }
    SEPARATOR { LINE; }
    REAL SLA_BANZI_ANISOTROPY_AMPL { UNIT PERCENT; MIN 0; MAX 100; }
    REAL SLA_BANZI_ANISOTROPY_SCALE { UNIT PERCENT; MIN 0; }
    REAL SLA_BANZI_ANISOTROPY_LENGTH { UNIT PERCENT; MIN 0; }
    REAL SLA_BANZI_ANISOTROPY_ATT { UNIT PERCENT; MIN 0; }
    BOOL SLA_BANZI_ANISOTROPY_CHANNEL1 { }
    BOOL SLA_BANZI_ANISOTROPY_CHANNEL2 { }
    BOOL SLA_BANZI_ANISOTROPY_CHANNEL3 { }
  }
  INCLUDE Millum;
  INCLUDE Massign;
}
