CONTAINER XSLAPosterizer
{
  NAME XSLAPosterizer;

  INCLUDE Mpreview;
  INCLUDE Xbase;

  GROUP ID_SHADERPROPERTIES
  {
    SHADERLINK SLA_POSTERIZER_TEXTURE { }
    LONG SLA_POSTERIZER_LEVELS { MIN 1; MAX 40; MINSLIDER 0; MAXSLIDER 20; CUSTOMGUI LONGSLIDER;  }
    REAL SLA_POSTERIZER_FILTER { UNIT PERCENT; MIN 0; MAX 200; MINSLIDER 0; MAXSLIDER 200; CUSTOMGUI REALSLIDER;  }
  }
}