CONTAINER XSLABanj
{
  NAME XSLABanj;

  INCLUDE Mpreview;
  INCLUDE Xbase;

  GROUP ID_SHADERPROPERTIES
  {
    COLOR SLA_BANJ_COLOR { }
    LONG SLA_BANJ_ALGORITHM
    {
      CYCLE
      {
        SLA_BANJ_ALGORITHM_INTERNAL;
        SLA_BANJ_ALGORITHM_OREN_NAYAR;
        SLA_BANJ_ALGORITHM_SIMPLE;
      }
    }
    REAL SLA_BANJ_ILLIMINATION { UNIT PERCENT; MIN 0; MAX 1000; }
    REAL SLA_BANJ_ROUGHNESS { UNIT PERCENT; MIN 0; MAX 200; }
    REAL SLA_BANJ_SHADOW_INTENSITY { UNIT PERCENT; MIN 0; MAX 100; }
    BOOL SLA_BANJ_CLIP { }
    REAL SLA_BANJ_CONTRAST { UNIT PERCENT; MIN -500; MAX 500; }
  }
}