CONTAINER XSLAColorizer
{
  NAME XSLAColorizer;

  INCLUDE Mpreview;
  INCLUDE Xbase;

  GROUP ID_SHADERPROPERTIES
  {
    LONG SLA_COLORIZER_INPUT
    {
      CYCLE
      {
        SLA_COLORIZER_INPUT_LUMINANCE;
        SLA_COLORIZER_INPUT_HUE;
        SLA_COLORIZER_INPUT_SATURATION;
        SLA_COLORIZER_INPUT_LIGHTNESS;
        SLA_COLORIZER_INPUT_RED;
        SLA_COLORIZER_INPUT_GREEN;
        SLA_COLORIZER_INPUT_BLUE;
      }
    }
    BOOL SLA_COLORIZER_CYCLE { }
    SHADERLINK SLA_COLORIZER_TEXTURE { }
    GRADIENT SLA_COLORIZER_GRADIENT { ICC_BASEDOCUMENT; }
  }
}