CONTAINER XSLADanel
{
	NAME XSLADanel;
	INCLUDE Mpreview;
	INCLUDE Mbase;

	GROUP Obaselist
	{
		BOOL SLA_DANEL_DIFFUSE { PARENTMSG ID_DANEL_DIFFUSE; }
		BOOL SLA_DANEL_SPECULAR1 { PARENTMSG ID_DANEL_SPECULAR1; }
		BOOL SLA_DANEL_SPECULAR2 { PARENTMSG ID_DANEL_SPECULAR2; }
		BOOL SLA_DANEL_SPECULAR3 { PARENTMSG ID_DANEL_SPECULAR3; }
		BOOL SLA_DANEL_REFLECTION { PARENTMSG ID_DANEL_REFLECTION; }
		BOOL SLA_DANEL_ENVIRONMENT { PARENTMSG ID_DANEL_ENVIRONMENT; }
		BOOL SLA_DANEL_AMBIENT { PARENTMSG ID_DANEL_AMBIENT; }
		BOOL SLA_DANEL_ROUGHNESS { PARENTMSG ID_DANEL_ROUGHNESS; }
		BOOL SLA_DANEL_ANISOTROPY { PARENTMSG ID_DANEL_ANISOTROPY; }
	}
	GROUP ID_DANEL_DIFFUSE
	{
		COLOR SLA_DANEL_DIFFUSE_COLOR { }
		LONG SLA_DANEL_DIFFUSE_ALGORITHM
		{
			CYCLE
			{
				SLA_DANEL_DIFFUSE_ALGORITHM_INTERNAL;
				SLA_DANEL_DIFFUSE_ALGORITHM_OREN_NAYAR;
			}
		}
		REAL SLA_DANEL_DIFFUSE_ROUGHNESS { UNIT PERCENT; MIN 0; MAX 200; }
		REAL SLA_DANEL_DIFFUSE_ILLUMINATION { UNIT PERCENT; MIN 0; MAX 1000; }
		REAL SLA_DANEL_DIFFUSE_CONTRAST { UNIT PERCENT; MIN -1000; MAX 1000; }
	}
	GROUP ID_DANEL_SPECULAR1
	{
		COLOR SLA_DANEL_SPEC1_COLOR { };
		REAL SLA_DANEL_SPEC1_INTENSITY { UNIT PERCENT; MIN 0; MAX 1000; }
		REAL SLA_DANEL_SPEC1_SIZE { UNIT PERCENT; MIN 0; MAX 200; }
		REAL SLA_DANEL_SPEC1_CONTRAST { UNIT PERCENT; MIN 0; MAX 100; }
		REAL SLA_DANEL_SPEC1_GLARE { UNIT PERCENT; MIN 0; MAX 1000; }
		REAL SLA_DANEL_SPEC1_FALLOFF { UNIT PERCENT; MIN 0; }
	}
	GROUP ID_DANEL_SPECULAR2
	{
		COLOR SLA_DANEL_SPEC2_COLOR { };
		REAL SLA_DANEL_SPEC2_INTENSITY { UNIT PERCENT; MIN 0; MAX 1000; }
		REAL SLA_DANEL_SPEC2_SIZE { UNIT PERCENT; MIN 0; MAX 200; }
		REAL SLA_DANEL_SPEC2_CONTRAST { UNIT PERCENT; MIN 0; MAX 100; }
		REAL SLA_DANEL_SPEC2_GLARE { UNIT PERCENT; MIN 0; MAX 1000; }
		REAL SLA_DANEL_SPEC2_FALLOFF { UNIT PERCENT; MIN 0; }
	}
	GROUP ID_DANEL_SPECULAR3
	{
		COLOR SLA_DANEL_SPEC3_COLOR { };
		REAL SLA_DANEL_SPEC3_INTENSITY { UNIT PERCENT; MIN 0; MAX 1000; }
		REAL SLA_DANEL_SPEC3_SIZE { UNIT PERCENT; MIN 0; MAX 200; }
		REAL SLA_DANEL_SPEC3_CONTRAST { UNIT PERCENT; MIN 0; MAX 100; }
		REAL SLA_DANEL_SPEC3_GLARE { UNIT PERCENT; MIN 0; MAX 1000; }
		REAL SLA_DANEL_SPEC3_FALLOFF { UNIT PERCENT; MIN 0; }
	}
	GROUP ID_DANEL_REFLECTION
	{
		REAL SLA_DANEL_REFLECTION_INTENSITY { UNIT PERCENT; MIN 0; MAX 1000; }
		REAL SLA_DANEL_REFLECTION_EDGE_INTENSITY { UNIT PERCENT; MIN 0; MAX 1000; }
		REAL SLA_DANEL_REFLECTION_FALLOFF { UNIT PERCENT; MIN 0; }
		SEPARATOR { LINE; }
		BOOL SLA_DANEL_REFLECTION_DISTANCE_FALLOFF { }
		REAL SLA_DANEL_REFLECTION_MIN { UNIT METER; MIN 0; }
		REAL SLA_DANEL_REFLECTION_MAX { UNIT METER; MIN 0; }
		SEPARATOR { LINE; }
		BOOL SLA_DANEL_REFLECTION_UTILIZE_ANISO_SCRATCHES { }
		REAL SLA_DANEL_REFLECTION_BLUR { UNIT PERCENT; MIN 0; MAX 1000; }
		LONG SLA_DANEL_REFLECTION_SAMPLES { MIN 1; }
		REAL SLA_DANEL_REFLECTION_JITTER { UNIT PERCENT; MIN 0; MAX 1000; }
		SEPARATOR { LINE; }
		COLOR SLA_DANEL_REFLECTION_REFLECTION_COLOR { }
		COLOR SLA_DANEL_REFLECTION_EDGE_COLOR { }
	}
	GROUP ID_DANEL_ENVIRONMENT
	{
		SHADERLINK SLA_DANEL_ENVIRONMENT_IMAGE { }
		REAL SLA_DANEL_ENVIRONMENT_INTENSITY { UNIT PERCENT; MIN 0; MAX 1000; }
		REAL SLA_DANEL_ENVIRONMENT_GLARE { UNIT PERCENT; MIN 0; MAX 1000; }
		REAL SLA_DANEL_ENVIRONMENT_FALLOFF { UNIT PERCENT; MIN 0; }
		SEPARATOR { LINE; }
		BOOL SLA_DANEL_ENVIRONMENT_UTILIZE_ANISO_SCRATCHES { }
		REAL SLA_DANEL_ENVIRONMENT_BLUR { UNIT PERCENT; MIN 0; MAX 100; }
		LONG SLA_DANEL_ENVIRONMENT_SAMPLES { MIN 1; }
		REAL SLA_DANEL_ENVIRONMENT_JITTER { UNIT PERCENT; MIN 0; MAX 1000; }
		SEPARATOR { LINE; }
		COLOR SLA_DANEL_ENVIRONMENT_ENVIRONMENT_COLOR { }
		COLOR SLA_DANEL_ENVIRONMENT_EDGE_COLOR { }
	}
	GROUP ID_DANEL_AMBIENT
	{
		COLOR SLA_DANEL_AMBIENT_COLOR { }
		REAL SLA_DANEL_AMBIENT_INTENSITY { UNIT PERCENT; MIN 0; MAX 1000; }
		REAL SLA_DANEL_AMBIENT_EDGE_INTENSITY { UNIT PERCENT; MIN 0; MAX 1000; }
		REAL SLA_DANEL_AMBIENT_FALLOFF { UNIT PERCENT; MIN 0; }
	}
	GROUP ID_DANEL_ROUGHNESS
	{
		LONG SLA_DANEL_ROUGHNESS_SEED { }
		LONG SLA_DANEL_ROUGHNESS_NOISE
		{
			CYCLE
			{
			}
			CUSTOMGUI NOISE; NOISE_OFFSET 2100;
		}
		REAL SLA_DANEL_ROUGHNESS_AMPLITUDE { UNIT PERCENT; MIN -1000; MAX 1000; }
		REAL SLA_DANEL_ROUGHNESS_OCTAVES { MIN 0; MAX 20; STEP .5; }
		REAL SLA_DANEL_ROUGHNESS_SCALE { UNIT PERCENT; MIN 0; }
		REAL SLA_DANEL_ROUGHNESS_SPEED { UNIT PERCENT; MIN -100; MAX 100; }
		REAL SLA_DANEL_ROUGHNESS_ATTENUATION { UNIT PERCENT; MIN 0; MAX 1000; }
		REAL SLA_DANEL_ROUGHNESS_DELTA { UNIT PERCENT; MIN 0; }
		BOOL SLA_DANEL_ROUGHNESS_HARD_BUMP { }
		BOOL SLA_DANEL_ROUGHNESS_ABSOLUTE { }
		SEPARATOR { LINE; }
		REAL SLA_DANEL_ROUGHNESS_LOW_CLIP { UNIT PERCENT; MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER; }
		REAL SLA_DANEL_ROUGHNESS_HIGH_CLIP { UNIT PERCENT; MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER; }
		SEPARATOR { LINE; }
		COLOR SLA_DANEL_ROUGHNESS_GRIT_COLOR { }
		REAL SLA_DANEL_ROUGHNESS_GRIT_INTENSITY { UNIT PERCENT; MIN -200; MAX 200; MINSLIDER -200; MAXSLIDER 200; CUSTOMGUI REALSLIDER; }
		REAL SLA_DANEL_ROUGHNESS_GRIT_LOW_CLIP { UNIT PERCENT; MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER; }
		REAL SLA_DANEL_ROUGHNESS_GRIT_HIGH_CLIP { UNIT PERCENT; MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER; }
	}
	GROUP ID_DANEL_ANISOTROPY
	{
		LONG SLA_DANEL_ANISOTROPY_PROJECTION
		{
			CYCLE
			{
				SLA_DANEL_ANISOTROPY_PROJECTION_PLANAR;
				SLA_DANEL_ANISOTROPY_PROJECTION_AUTO_PLANAR;
				SLA_DANEL_ANISOTROPY_PROJECTION_SHRINK_WRAP;
				SLA_DANEL_ANISOTROPY_PROJECTION_RADIAL_AUTO_PLANAR;
				SLA_DANEL_ANISOTROPY_PROJECTION_RAD_PATTERN_AUTO_PLANAR;
				SLA_DANEL_ANISOTROPY_PROJECTION_RADIAL_PLANAR;
				SLA_DANEL_ANISOTROPY_PROJECTION_RAD_PATTERN_PLANAR;
			}
		}
		REAL SLA_DANEL_ANISOTROPY_PROJ_SCALE { UNIT PERCENT; MIN 0; MAX 1000; }
		SEPARATOR { LINE; }
		REAL SLA_DANEL_ANISOTROPY_X_ROUGH { UNIT PERCENT; MIN 0; }
		REAL SLA_DANEL_ANISOTROPY_Y_ROUGH { UNIT PERCENT; MIN 0; }
		SEPARATOR { LINE; }
		REAL SLA_DANEL_ANISOTROPY_AMPL { UNIT PERCENT; MIN 0; MAX 100; }
		REAL SLA_DANEL_ANISOTROPY_SCALE { UNIT PERCENT; MIN 0; }
		REAL SLA_DANEL_ANISOTROPY_LENGTH { UNIT PERCENT; MIN 0; }
		REAL SLA_DANEL_ANISOTROPY_ATT { UNIT PERCENT; MIN 0; }
		BOOL SLA_DANEL_ANISOTROPY_CHANNEL1 { }
		BOOL SLA_DANEL_ANISOTROPY_CHANNEL2 { }
		BOOL SLA_DANEL_ANISOTROPY_CHANNEL3 { }
	}

	INCLUDE Millum;
	INCLUDE Massign;
}