CONTAINER XSLAFusion
{
  NAME XSLAFusion;

  INCLUDE Mpreview;
  INCLUDE Xbase;

  GROUP ID_SHADERPROPERTIES
  {
    LONG SLA_FUSION_MODE
    {
      CYCLE
      {
        SLA_FUSION_MODE_NORMAL;
        SLA_FUSION_MODE_SEP_1;
        SLA_FUSION_MODE_MULTIPLY;
        SLA_FUSION_MODE_SCREEN;
        SLA_FUSION_MODE_OVERLAY;
        SLA_FUSION_MODE_HARD_LIGHT;
        SLA_FUSION_MODE_SOFT_LIGHT;
        SLA_FUSION_MODE_SEP_2;
        SLA_FUSION_MODE_DODGE;
        SLA_FUSION_MODE_BURN;
        SLA_FUSION_MODE_SEP_3;
        SLA_FUSION_MODE_DARKEN;
        SLA_FUSION_MODE_LIGHTEN;
        SLA_FUSION_MODE_ADD;
        SLA_FUSION_MODE_SUBTRACT;
        SLA_FUSION_MODE_DIFFERENCE;
        SLA_FUSION_MODE_EXCLUSION;
        SLA_FUSION_MODE_SEP_4;
        SLA_FUSION_MODE_HUE;
        SLA_FUSION_MODE_SAT;
        SLA_FUSION_MODE_COLOR;
        SLA_FUSION_MODE_LUMINANCE;
        SLA_FUSION_MODE_SEP_5;
        SLA_FUSION_MODE_LEVR;
      }
    }
    REAL SLA_FUSION_BLEND { UNIT PERCENT; MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER; }
    BOOL SLA_FUSION_USE_MASK { }
    BOOL SLA_FUSION_INVERT_MASK { }
    BOOL SLA_FUSION_INVERT_OUTPUT { }
    SHADERLINK SLA_FUSION_BLEND_CHANNEL { }
    SHADERLINK SLA_FUSION_MASK_CHANNEL { }
    SHADERLINK SLA_FUSION_BASE_CHANNEL { }
  }
}