CONTAINER BPbitmap
{
	NAME BPbitmap;
	INCLUDE Obaselist;

	GROUP Obaselist
	{
		DEFAULT 1;
		BITMAPBUTTON ID_PAINTBITMAP_PREVIEW { };
		HIDE ID_LAYER_LINK;
	}


	GROUP ID_PAINTBITMAP_GROUP
	{
		DEFAULT 1;
	}

	GROUP ID_PAINTBITMAP_INFO_GROUP
	{
		DEFAULT 1;
		STATICTEXT ID_PAINTBITMAP_SIZE_X	{  }
		STATICTEXT ID_PAINTBITMAP_SIZE_Y	{  }
		STATICTEXT ID_PAINTBITMAP_MEMORY	{  }
	}
}
