CONTAINER BPlayerbmp
{
	NAME BPlayerbmp;
	INCLUDE BPlayer;

	GROUP ID_PAINTBITMAP_GROUP
	{
		LONG ID_PAINTLAYERBMP_OFFSET_X { };
		LONG ID_PAINTLAYERBMP_OFFSET_Y { };
	}

	GROUP ID_PAINTBITMAP_INFO_GROUP
	{
		STATICTEXT ID_PAINTLAYERBMP_MODE {  }
	}
}
