CONTAINER BPlayer
{
	NAME BPlayer;
	INCLUDE BPbitmap;

	GROUP ID_PAINTBITMAP_GROUP
	{
		BOOL ID_PAINTLAYER_SHOW { }
		LONG ID_PAINTLAYER_BLEND
		{
			CYCLE
			{
				LAYER_PASSFOLDER;
				-1;
				LAYER_NORMAL;
				LAYER_DISSOLVE;
				0;
				LAYER_DARKEN;
				LAYER_MULTIPLY;
				LAYER_COLORBURN;
				LAYER_LINEARBURN;
				0;
				LAYER_LIGHTEN;
				LAYER_SCREEN;
				LAYER_COLORDODGE;
				LAYER_LINEARDODGE;
				LAYER_ADD;
				0;
				LAYER_OVERLAY;
				LAYER_SOFTLIGHT;
				LAYER_HARDLIGHT;
				LAYER_STAMP;
				LAYER_PINLIGHT;
				LAYER_HARDMIX;
				0;
				LAYER_DIFFERENCE;
				LAYER_EXCLUSION;
				LAYER_REFLECT;
				LAYER_NEGATION;
				LAYER_GLOW;
				LAYER_AVERAGE;
				LAYER_FREEZE;
				LAYER_HEAT;
				//0;
				//LAYER_HUE;
				//LAYER_SATURATION;
				//LAYER_COLOR;
				//LAYER_LUMINANCE;
			}
		}
		REAL ID_PAINTLAYER_OPACITY { MIN 0.0; MAX 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
		COLORPROFILE ID_PAINTLAYER_TEXPROFILE { }
	}

	GROUP ID_PAINTBITMAP_INFO_GROUP
	{
		LINK ID_PAINTLAYER_TEXTURE_LINK { HIDDEN; }
		STATICTEXT ID_PAINTLAYER_TEXTURE_NAME { }
	}
}
