CONTAINER BPlayerfilterbrco
{
	NAME BPlayerfilterbrco;
	INCLUDE BPlayerfilterbase;

	GROUP ID_PAINTBITMAP_GROUP
	{
		REAL ID_PAINTLAYERFILTERBRCO_BRIGHTNESS { MIN -100.0; MAX 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
		REAL ID_PAINTLAYERFILTERBRCO_CONTRAST   { MIN -100.0; MAX 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
	}
}
