CONTAINER BPsplinetext
{
	NAME BPsplinetext;
	INCLUDE BPspline;

	GROUP Obaselist
	{
	}

	GROUP ID_PAINTSPLINE_GROUP
	{
		STRING ID_PAINTSPLINETEXT_TEXT  { CUSTOMGUI MULTISTRING; }
		FONT	 ID_PAINTSPLINETEXT_FONT  { OPEN; }
		LONG   ID_PAINTSPLINETEXT_ALIGN { CYCLE { 0,PAINTSPLINETEXT_ALIGN_LEFT;1,PAINTSPLINETEXT_ALIGN_CENTER;2,PAINTSPLINETEXT_ALIGN_RIGHT; } }
		REAL   ID_PAINTSPLINETEXT_SIZE  { MIN 0; }
		REAL   ID_PAINTSPLINETEXT_SPACE_H { }
		REAL   ID_PAINTSPLINETEXT_SPACE_V { }
		BOOL	 ID_PAINTSPLINETEXT_SEPARATE { }
	}

	GROUP ID_PAINTSPLINE_INFO_GROUP
	{
	}
}
