CONTAINER CKvalue
{
	NAME CKvalue;
//	INCLUDE CKbase;

	GROUP ID_VKEY_PROPERTIES
	{
		DEFAULT	1;
		COLUMNS 2;

		LONG ID_CKEY_QUAT_INTER    { ALIGN_LEFT; CYCLE { ID_CKEY_QUAT_LINEAR; ID_CKEY_QUAT_CUBIC; } } // ID_CKEY_QUAT_SPLINE removed
		STATICTEXT {JOINEND;}
		LONG ID_CKEY_INTER    { ALIGN_LEFT; HIDDEN; CYCLE { ID_CKEY_SPLINE; ID_CKEY_LINEAR; ID_CKEY_STEP; } } 
		STATICTEXT {JOINEND;}

		SEPARATOR { LINE; } STATICTEXT { JOINEND; }
		BASETIME ID_VKEY_TIME {} 
		BOOL ID_VKEY_BREAKDOWN  {}

		REAL ID_CKEY_VALUE    {} 
		BOOL ID_VKEY_BREAKDOWNCOLOR	{}

		BOOL ID_VKEY_LOCK_T {}
		BOOL ID_VKEY_MUTE { }

		BOOL ID_CKEY_LOCK_V {}
		STATICTEXT {}


		SEPARATOR { LINE; } STATICTEXT { JOINEND; }
		LONG ID_CKEY_PRESET    
		{
			ALIGN_LEFT; ANIM OFF; PARENTCOLLAPSE;
			CYCLE { ID_CKEY_PRESET_CLASSICAUTO; ID_CKEY_PRESET_NEWAUTO; ID_CKEY_PRESET_NEWAUTOWEIGHTED; ID_CKEY_PRESET__CUSTOM; } 
		}
		STATICTEXT { JOINEND; }

		// Added in the preset Collapse UI
		BOOL ID_CKEY_AUTO  {PARENTCOLLAPSE ID_CKEY_PRESET;}
		LONG ID_CKEY_AUTOMODE   { PARENTCOLLAPSE ID_CKEY_PRESET; CYCLE { ID_CKEY_CLASSIC; ID_CKEY_FIXEDSLOPE; } }

		BOOL ID_CKEY_CLAMP {PARENTCOLLAPSE ID_CKEY_PRESET;}
		BOOL ID_CKEY_REMOVEOVERSHOOT {PARENTCOLLAPSE ID_CKEY_PRESET;}

		BOOL ID_CKEY_WEIGHTEDTANGENT {PARENTCOLLAPSE ID_CKEY_PRESET;}
		BOOL ID_CKEY_AUTOWEIGHT {PARENTCOLLAPSE ID_CKEY_PRESET;}


		SEPARATOR { LINE; } STATICTEXT { JOINEND; }
		BASETIME ID_CKEY_TIME_LEFT	{MAX 0.0; }
		BASETIME ID_CKEY_TIME_RIGHT  { MIN 0.0; }

		REAL     ID_CKEY_VALUE_LEFT	{}
		REAL     ID_CKEY_VALUE_RIGHT {}


		SEPARATOR { LINE; } STATICTEXT { JOINEND; }
		//BOOL ID_CKEY_ZERO_O {} 
		BOOL ID_CKEY_LOCK_O {}
		//BOOL ID_CKEY_ZERO_L {} 
		BOOL ID_CKEY_LOCK_L {}

		BOOL ID_CKEY_BREAK  {} 
		BOOL ID_CKEY_KEEPVISUALANGLE  {} 
	}
}

