CONTAINER	Fcadimport
{
	NAME Fcadimport;
	INCLUDE	Fbase;

	GROUP CADIMPORT_GROUP
	{
		GROUP CADIMPORT_GRP_GENERAL
		{
			COLUMNS 2;

			BOOL CADIMPORT_ORIGINAL_UNITS { }
			STATICTEXT { JOINEND; }
			UNITSCALE CADIMPORT_SCALE { }
			STATICTEXT { JOINEND; }
			BOOL CADIMPORT_GEOMETRY { DEFAULT 1; }
			STATICTEXT { JOINEND; }
			BOOL CADIMPORT_SPLINES { DEFAULT 1; }
			STATICTEXT { JOINEND; }
			LONG CADIMPORT_INSTANCES
			{
				DEFAULT CADIMPORT_INSTANCES_RENDERINSTANCE;

				CYCLE
				{
					CADIMPORT_INSTANCES_NONE;
					CADIMPORT_INSTANCES_INSTANCE;
					CADIMPORT_INSTANCES_RENDERINSTANCE;
				}
			}
			STATICTEXT { JOINEND; }
			BOOL CADIMPORT_HELPER { DEFAULT 0; }
			STATICTEXT { JOINEND; }
			BOOL CADIMPORT_LOAD_HIDDEN { DEFAULT 0; }
			STATICTEXT { JOINEND; }
		}

		GROUP CADIMPORT_GRP_OPTIONAL
		{
			COLUMNS 2;

			LONG CADIMPORT_NORMALS
			{
				DEFAULT CADIMPORT_NORMALS_NORMALTAG;

				CYCLE
				{
					CADIMPORT_NORMALS_NONE;
					CADIMPORT_NORMALS_NORMALTAG;
					CADIMPORT_NORMALS_PHONGTAG;
				}
			}
			STATICTEXT { JOINEND; }
			LONG CADIMPORT_DISPLAY_COLORS
			{
				DEFAULT CADIMPORT_DISPLAY_COLORS_ORIGINAL;
				CYCLE
				{
					CADIMPORT_DISPLAY_COLORS_NONE;
					CADIMPORT_DISPLAY_COLORS_ORIGINAL;
					CADIMPORT_DISPLAY_COLORS_RANDOM;
				}
			}
			STATICTEXT { JOINEND; }
			LONG CADIMPORT_LAYERS
			{
				DEFAULT CADIMPORT_LAYERS_ORIGINAL;
				CYCLE
				{
					CADIMPORT_LAYERS_NONE;
					CADIMPORT_LAYERS_ORIGINAL;
					CADIMPORT_LAYERS_SBT;
				}
			}
			STATICTEXT { JOINEND; }
			LONG CADIMPORT_MATERIALS
			{
				DEFAULT CADIMPORT_MATERIALS_ORIGINAL;
				CYCLE
				{
					CADIMPORT_MATERIALS_NONE;
					CADIMPORT_MATERIALS_ORIGINAL;
					CADIMPORT_MATERIALS_DISPLAY_COLORS;
					CADIMPORT_MATERIALS_RANDOM;
				}
			}
			STATICTEXT { JOINEND; }
			BOOL CADIMPORT_UVS { DEFAULT 1; }
			STATICTEXT { JOINEND; }
			BOOL CADIMPORT_VISIBILITY { DEFAULT 0; }
			STATICTEXT { JOINEND; }
		}

		GROUP CADIMPORT_GRP_MODIFICATIONS
		{
			COLUMNS 2;

			LONG CADIMPORT_SEW
			{
				DEFAULT CADIMPORT_SEW_KEEP_ORIGINAL_BODIES;
				CYCLE
				{
					CADIMPORT_SEW_NONE;
					CADIMPORT_SEW_KEEP_ORIGINAL_BODIES;
					CADIMPORT_SEW_CREATE_BODIES_BY_TOPOLOGY;
					CADIMPORT_SEW_CREATE_BODIES_BY_COLOR;
					CADIMPORT_SEW_CREATE_BODIES_BY_LAYER;
				}
			}
			STATICTEXT { JOINEND; }
			BOOL CADIMPORT_SWAP_YZAXIS { DEFAULT 0; }
			STATICTEXT { JOINEND; }
			BOOL CADIMPORT_HEAL { DEFAULT 0; }
			STATICTEXT { JOINEND; }
			LONG CADIMPORT_STITCH_COUNT { MIN 0; MAX 100; DEFAULT 0; STEP 1; }
			STATICTEXT { JOINEND; }
			BOOL CADIMPORT_OPTIMIZE_HIERARCHY { DEFAULT 1; }
			STATICTEXT { JOINEND; }
		}

		GROUP CADIMPORT_GRP_TESSELATION
		{
			BOOL CADIMPORT_SOURCE_MESH { DEFAULT 0; }
			BOOL CADIMPORT_LOD { DEFAULT 1; }
			BOOL CADIMPORT_SCALEBASEDTESSELATION { DEFAULT 0; }
			RANGE CADIMPORT_SCALEBASEDTESSELATION_RANGE { }
			BOOL CADIMPORT_SCALEBASEDTESSELATION_INTERPOLATION { DEFAULT 0; }

			GROUP CADIMPORT_SCALEBASEDTESSELATION_GROUP
			{
				COLUMNS 3;

				REAL CADIMPORT_LOW_MAX_SAG { MIN 0.0; MAX 999999.0; DEFAULT 2.0; STEP 0.1; }
				REAL CADIMPORT_LOW_MAX_ANGLE { MIN 0.0; MAX 180.0; DEFAULT 60.0; UNIT DEGREE; STEP 1.0; }
				REAL CADIMPORT_LOW_MAX_LENGTH { MIN 0.0; MAX 999999.0; DEFAULT 0.0; STEP 0.1; }

				REAL CADIMPORT_MEDIUM_MAX_SAG { MIN 0.0; MAX 999999.0; DEFAULT 0.2; STEP 0.1; }
				REAL CADIMPORT_MEDIUM_MAX_ANGLE { MIN 0.0; MAX 180.0; DEFAULT 30.0; UNIT DEGREE; STEP 1.0; }
				REAL CADIMPORT_MEDIUM_MAX_LENGTH { MIN 0.0; MAX 999999.0; DEFAULT 0.0; STEP 0.1; }

				REAL CADIMPORT_HIGH_MAX_SAG { MIN 0.0; MAX 999999.0; DEFAULT 0.05; STEP 0.1; }
				REAL CADIMPORT_HIGH_MAX_ANGLE { MIN 0.0; MAX 180.0; DEFAULT 10.0; UNIT DEGREE; STEP 1.0; }
				REAL CADIMPORT_HIGH_MAX_LENGTH { MIN 0.0; MAX 999999.0; DEFAULT 0.0; STEP 0.1; }
			}

			GROUP CADIMPORT_DETAILING_GROUP
			{
				LONG CADIMPORT_DETAILING
				{
					DEFAULT CADIMPORT_DETAILING_ORIGINAL;
					PARENTCOLLAPSE;

					CYCLE
					{
						CADIMPORT_DETAILING_ORIGINAL;
						CADIMPORT_DETAILING_CUSTOM;
						CADIMPORT_DETAILING_HIGH;
						CADIMPORT_DETAILING_MEDIUM;
						CADIMPORT_DETAILING_LOW;
					}
				}
				REAL CADIMPORT_MAX_SAG { MIN 0.0; MAX 999999.0; DEFAULT 1.0; STEP 0.1; PARENTCOLLAPSE CADIMPORT_DETAILING; }
				REAL CADIMPORT_MAX_ANGLE { MIN 0.0; MAX 180.0; DEFAULT 45.0; UNIT DEGREE; STEP 1.0; PARENTCOLLAPSE CADIMPORT_DETAILING; }
				REAL CADIMPORT_MAX_LENGTH { MIN 0.0; MAX 999999.0; DEFAULT 0.0; STEP 0.1; }
			}
		}
	}
}
