CONTAINER Fieldremapper
{
	NAME Fieldremapper;

	GROUP ID_FIELDCONTROLS
	{
		GROUP
		{
			FIT_H;
			COLUMNS 2;
			BOOL FIELD_REMAP_ENABLE { }
			BOOL FIELD_REMAP_MIRROR { HIDDEN; }
		}

		GROUP
		{
			FIT_H;

			GROUP
			{
				FIT_H;
				BITMAPBUTTON FIELD_PREVIEW { }
			}

			GROUP
			{
				FIT_H;
				SCALE_H;

				GROUP
				{
					FIT_H;

					COLUMNS 2;

					REAL FIELD_STRENGTH { SCALE_H; MINSLIDER 0.0; MAXSLIDER 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
					BOOL FIELD_INVERT { }

					REAL FIELD_INNER_OFFSET { SCALE_H; MIN 0.0; MAX 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
				}

				SEPARATOR { LINE; }

				GROUP FIELD_GROUP_RANGE
				{
					FIT_H;

					COLUMNS 2;

					REAL FIELD_MIN { SCALE_H; MINSLIDER 0.0; MAXSLIDER 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
					BOOL FIELD_CLAMP_MIN { }

					REAL FIELD_MAX { SCALE_H; MINSLIDER 0.0; MAXSLIDER 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
					BOOL FIELD_CLAMP_MAX { }
				}
			}
		}

		GROUP FIELD_GROUP_CONTOUR
		{
			DEFAULT 0;

			REAL FIELD_MULTIPLIER	{ MINSLIDER 0.0; MAXSLIDER 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; }

			LONG FIELD_CONTOUR_MODE
			{
				CYCLE
				{
					FIELD_CONTOUR_MODE_NONE;
					-1;
					FIELD_CONTOUR_MODE_QUAD;
					FIELD_CONTOUR_MODE_STEP;
					FIELD_CONTOUR_MODE_QUANTIZE;
					FIELD_CONTOUR_MODE_CURVE;
				}
			}

			REAL		 FIELD_CONTOUR_CURVE { UNIT PERCENT; MIN -100.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
			LONG		 FIELD_CONTOUR_STEPS { MIN 1; }
			SPLINE	 FIELD_CONTOUR_SPLINE { }
			BASETIME FIELD_CONTOUR_ANIMATION_SPEED { }
			REAL		 FIELD_CONTOUR_SPLINE_OFFSET { UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			REAL		 FIELD_CONTOUR_SPLINE_RANGE { UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		}
	}

	GROUP FIELD_GROUP_COLOR
	{
		DEFAULT 0;

		FIELD COLOR;

		LONG FIELD_COLOR_MODE
		{
			FIELD COLOR;

			CYCLE
			{
				FIELD_COLOR_MODE_OFF;
				-1;
				FIELD_COLOR_MODE_COLOR;
				FIELD_COLOR_MODE_GRADIENT;
			}
		}

		COLOR		 FIELD_COLOR { OPEN; FIELD COLOR; }
		GRADIENT FIELD_GRADIENT { OPEN; COLOR; ALPHA; FIELD COLOR; ICC_BASEDOCUMENT; }
	}

	GROUP FIELD_GROUP_DIRECTION
	{
		DEFAULT 0;

		FIELD DIRECTION;
		FIELD ROTATION;

		GROUP FIELD_DIRECTIONSUBGROUP
		{
			DEFAULT 1;
			FIELD DIRECTION;
			SCALE_H;

			LONG FIELD_DIRECTIONMODE
			{
				CYCLE
				{
					FIELD_DIRECTIONMODE_OFF;
					-1;
					FIELD_DIRECTIONMODE_NORMALIZE;
					-1;
					FIELD_DIRECTIONMODE_ATTENUATE;
					-1;
					FIELD_DIRECTIONMODE_INVERSESQUARE;
				}
			}
			REAL FIELD_DIRECTIONSCALE { MINSLIDER 0.0; MAXSLIDER 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
			BOOL FIELD_DIRECTIONINVERT {}
		}

		GROUP FIELD_ROTATIONSUBGROUP
		{
			DEFAULT 1;
			FIELD ROTATION;
			SCALE_H;

			HIDDEN;

			LONG FIELD_ROTATIONMODE
			{
				CYCLE
				{
					FIELD_ROTATIONMODE_OFF;
					-1;
					FIELD_ROTATIONMODE_NORMALIZE;
					-1;
					FIELD_ROTATIONMODE_REMAP;
					FIELD_ROTATIONMODE_ATTENUATE;
					-1;
					FIELD_ROTATIONMODE_INVERSESQUARE;
				}
			}
			REAL FIELD_ROTATIONSCALE { MINSLIDER 0.0; MAXSLIDER 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
			BOOL FIELD_ROTATIONINVERT { }
		}
		
	}
}
