CONTAINER FLbase
{
	NAME FLbase;

	GROUP ID_FIELDLAYER_BASICGROUP
	{
		DEFAULT 0;

		BOOL ID_FIELDLAYER_ENABLED { PARENTCOLLAPSE; }
		GROUP
		{
			COLUMNS 4;
			BOOL ID_FIELDLAYER_ENABLE_VALUE { PARENTCOLLAPSE ID_FIELDLAYER_ENABLED; FIELD VALUE; }
			BOOL ID_FIELDLAYER_ENABLE_COLOR { PARENTCOLLAPSE ID_FIELDLAYER_ENABLED; FIELD COLOR; }
			BOOL ID_FIELDLAYER_ENABLE_DIRECTION { PARENTCOLLAPSE ID_FIELDLAYER_ENABLED; FIELD DIRECTION; }
			BOOL ID_FIELDLAYER_ENABLE_ROTATION { PARENTCOLLAPSE ID_FIELDLAYER_ENABLED; FIELD ROTATION; }
		}

		SEPARATOR { LINE; }

		REAL ID_FIELDLAYER_STRENGTH { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }

		LONG ID_FIELDLAYER_BLENDINGMODE
		{
			CYCLE
			{
				ID_FIELDLAYER_BLENDINGMODE_NORMAL;
				-1;
				ID_FIELDLAYER_BLENDINGMODE_DARKEN;
				ID_FIELDLAYER_BLENDINGMODE_TRUESUBTRACT;
				ID_FIELDLAYER_BLENDINGMODE_MULTIPLY;
				-1;
				ID_FIELDLAYER_BLENDINGMODE_OVERLAY;
				-1;
				ID_FIELDLAYER_BLENDINGMODE_LIGHTEN;
				ID_FIELDLAYER_BLENDINGMODE_ADD;
				ID_FIELDLAYER_BLENDINGMODE_SCREEN;
				-1;
				ID_FIELDLAYER_BLENDINGMODE_LAYERMASK;
			}
		}
	}

	GROUP FLbase
	{
		DEFAULT 1;
	}
}
