CONTAINER Massign
{
	NAME Massign;
	INCLUDE Obaselist;

	GROUP Obaselist
	{
		BOOL MATERIAL_PAGE_ASSIGNMENT { PAGE; HIDDEN; PARENTMSG ID_MATERIALASSIGNMENTS_GROUP; }
	}

	GROUP ID_MATERIALASSIGNMENTS_GROUP
	{
		SCALE_V;
		MATASSIGN ID_MATERIALASSIGNMENTS { SCALE_V; }
	}
}
