CONTAINER Millum
{
	INCLUDE Obaselist;

	GROUP Obaselist
	{
		BOOL MATERIAL_PAGE_ILLUMINATION	{ PAGE; HIDDEN; PARENTMSG ID_MATERIALGROUP_ILLUMINATION; }
	}

	GROUP ID_MATERIALGROUP_ILLUMINATION
	{
		BOOL MATERIAL_GLOBALILLUM_AREA { HIDDEN; }
		BOOL MATERIAL_GLOBALILLUM_PORTAL { HIDDEN; }

		SEPARATOR { }

		GROUP
		{
			COLUMNS 2;

			BOOL MATERIAL_GLOBALILLUM_GENERATE {}
			REAL MATERIAL_GLOBALILLUM_GENERATE_STRENGTH { UNIT PERCENT; MIN 0.0; MAX 10000.0; }

			SEPARATOR { }
			REAL MATERIAL_GLOBALILLUM_GENERATE_SATURATION { UNIT PERCENT; MIN 0.0; MAX 1000.0; }

			BOOL MATERIAL_GLOBALILLUM_RECEIVE	{}
			REAL MATERIAL_GLOBALILLUM_RECEIVE_STRENGTH { UNIT PERCENT; MIN 0.0; MAX 10000.0; }

			SEPARATOR { }
			REAL MATERIAL_GLOBALILLUM_SATURATION { UNIT PERCENT; MIN 0.0; MAX 1000.0; }

			SEPARATOR { LINE; }
			STATICTEXT { JOINENDSCALE; }

			BOOL MATERIAL_CAUSTICS_GENERATE {}
			REAL MATERIAL_CAUSTICS_GENERATE_STRENGTH  { UNIT PERCENT; MIN 0.0; MAX 10000.0; }

			BOOL MATERIAL_CAUSTICS_RECEIVE {}
			REAL MATERIAL_CAUSTICS_RECEIVE_STRENGTH { UNIT PERCENT; MIN 0.0; MAX 10000.0; }

			SEPARATOR { }
			REAL MATERIAL_CAUSTICS_SAMPLERADIUS	{ UNIT METER; MIN 0.0; }
			SEPARATOR { }
			LONG MATERIAL_CAUSTICS_SAMPLES	{ MIN 1; MAX 10000; }
		}

		SEPARATOR { LINE; }
	}
}
