CONTAINER Oarray
{
	NAME Oarray;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL ARRAYOBJECT_RADIUS { UNIT METER; MIN 0.0; }
		LONG ARRAYOBJECT_COPIES { MIN 1; MAX 1000; }
		REAL ARRAYOBJECT_AMPLITUDE { UNIT METER; }
		REAL ARRAYOBJECT_FREQUENCY { MIN 0.0; STEP 0.01; }
		REAL ARRAYOBJECT_CIRCLEFREQ { MIN 0.0; STEP 0.01; }
		BOOL ARRAYOBJECT_RENDERINSTANCES {}
	}
}
