CONTAINER Obaselist
{
	NAME Obaselist;
	GROUP Obaselist
	{
		FIELD HIDE;

		GROUP ID_BASELIST_ICON_SETTINGS_GROUP
		{
			HIDDEN;
			TEXTURE	ID_BASELIST_ICON_FILE { ANIM OFF; }
			LONG ID_BASELIST_ICON_COLORIZE_MODE
			{
				CYCLE
				{
					ID_BASELIST_ICON_COLORIZE_MODE_NONE;
					ID_BASELIST_ICON_COLORIZE_MODE_CUSTOM;
				}
				ANIM OFF;
			}

			COLOR ID_BASELIST_ICON_COLOR { ANIM OFF; DEFAULT 1.0 0.9 0.4; }
			GROUP
			{
				ICONCHOOSER ID_BASELIST_ICON_PRESET_BUTTONS { }
			}
		}

		SEPARATOR { LINE; }

		STRING ID_BASELIST_NAME { ANIM OFF; MATEDNOTEXT; }
		LINK ID_LAYER_LINK
		{
			LAYERMODE;
			ANIM OFF;
			MATEDNOTEXT;
			ACCEPT
			{
				100004801;
			}
		}

		GROUP ID_BASELIST_NODESPACE_ADD_REMOVE_GROUP
		{
			HIDDEN;
			DEFAULT 1;
			NODESPACE_ADD_REMOVE ID_BASELIST_NODESPACE_ADD_REMOVE_BUTTONS { }
		}
	}
}
