CONTAINER Obase
{
	NAME Obase;
	INCLUDE Obaselist;
	
	GROUP Obaselist
	{
		SEPARATOR { LINE; }
		LONG ID_BASEOBJECT_VISIBILITY_EDITOR { CYCLE { OBJECT_UNDEF; OBJECT_ON; OBJECT_OFF; } }
		LONG ID_BASEOBJECT_VISIBILITY_RENDER { CYCLE { OBJECT_UNDEF; OBJECT_ON; OBJECT_OFF; } }

		SEPARATOR { LINE; }
		LONG  ID_BASEOBJECT_USECOLOR
		{
			CYCLE
			{
				ID_BASEOBJECT_USECOLOR_OFF;
				ID_BASEOBJECT_USECOLOR_AUTOMATIC;
				ID_BASEOBJECT_USECOLOR_ALWAYS;
				ID_BASEOBJECT_USECOLOR_LAYER;
			}
		}
		COLOR ID_BASEOBJECT_COLOR { }

		//LONG ID_BASEOBJECT_SHADEDWIRECOLORMODE { CYCLE { ID_BASEOBJECT_SHADEDWIRECOLORMODE_OFF; ID_BASEOBJECT_SHADEDWIRECOLORMODE_AUTO; ID_BASEOBJECT_SHADEDWIRECOLORMODE_ALWAYS; } }

		//COLOR ID_BASEOBJECT_SHADEDWIRECOLOR { }

		BOOL ID_BASEOBJECT_GENERATOR_FLAG { HIDDEN; }
		BOOL ID_BASEOBJECT_XRAY	{ HIDDEN; }

		SHOW ID_BASELIST_ICON_SETTINGS_GROUP;
	}

	GROUP ID_BASEOBJECT_GROUP1
	{				
		FIELD HIDE;

		GROUP
		{
			LAYOUTGROUP; COLUMNS 3; 
			GROUP
			{
				VECTOR ID_BASEOBJECT_REL_POSITION { UNIT METER;  CUSTOMGUI SUBDESCRIPTION; }
			}
			GROUP
			{
				VECTOR ID_BASEOBJECT_REL_SCALE    { STEP 0.01;   CUSTOMGUI SUBDESCRIPTION; }
			}
			GROUP
			{
				VECTOR ID_BASEOBJECT_REL_ROTATION { UNIT DEGREE; CUSTOMGUI SUBDESCRIPTION; }	
				LONG ID_BASEOBJECT_ROTATION_ORDER
				{
					ANIM OFF;
					CYCLE
					{
						ID_BASEOBJECT_ROTATION_ORDER_HPB;
						-1;
						ID_BASEOBJECT_ROTATION_ORDER_XYZ;
						ID_BASEOBJECT_ROTATION_ORDER_XZY;
						ID_BASEOBJECT_ROTATION_ORDER_YXZ;
						ID_BASEOBJECT_ROTATION_ORDER_YZX;
						ID_BASEOBJECT_ROTATION_ORDER_ZXY;
						ID_BASEOBJECT_ROTATION_ORDER_ZYX;
					}
				}
			}
		}

		GROUP ID_BASEOBJECT_QUATERNION_ROTATION
		{
			BOOL ID_BASEOBJECT_QUATERNION_ROTATION_INTERPOLATION { ANIM OFF; }
		}
			
		GROUP ID_BASEOBJECT_FROZEN_COORDS
		{
			GROUP
			{
				COLUMNS 2;
				
				BUTTON ID_BASEOBJECT_FREEZE { }
				BUTTON ID_BASEOBJECT_FROZEN_RESET { }
			}
			
			GROUP
			{
				LAYOUTGROUP; COLUMNS 3;
				GROUP
				{
					VECTOR ID_BASEOBJECT_FROZEN_POSITION { UNIT METER;  CUSTOMGUI SUBDESCRIPTION; }
					BUTTON ID_BASEOBJECT_FREEZE_P { SCALE_H; }
				}
				GROUP
				{
					VECTOR ID_BASEOBJECT_FROZEN_SCALE    { STEP 0.01;   CUSTOMGUI SUBDESCRIPTION; }
					BUTTON ID_BASEOBJECT_FREEZE_S { SCALE_H; }
				}
				GROUP
				{
					VECTOR ID_BASEOBJECT_FROZEN_ROTATION { UNIT DEGREE; CUSTOMGUI SUBDESCRIPTION; }
					BUTTON ID_BASEOBJECT_FREEZE_R { SCALE_H; }
				}
			}
		}
		
		VECTOR ID_BASEOBJECT_GLOBAL_POSITION { FORBID_SCALING; HIDDEN; UNIT METER; }
		VECTOR ID_BASEOBJECT_GLOBAL_ROTATION { HIDDEN; UNIT DEGREE; }
		VECTOR ID_BASEOBJECT_ABS_POSITION { FORBID_SCALING; HIDDEN; UNIT METER; }
		VECTOR ID_BASEOBJECT_ABS_SCALE { HIDDEN; }
		VECTOR ID_BASEOBJECT_ABS_ROTATION { HIDDEN; UNIT DEGREE; }
	}

	GROUP ID_OBJECTPROPERTIES
	{
		DEFAULT	1;
	}
}
