CONTAINER Oextrude
{
	NAME Oextrude;
	INCLUDE Obase;
	INCLUDE Onurbscaps;
  INCLUDE Onurbsselection;

	GROUP ID_OBJECTPROPERTIES
	{
		LONG EXTRUDEOBJECT_DIRECTION
		{
			CYCLE
			{
				EXTRUDEOBJECT_DIRECTION_AUTO;
				EXTRUDEOBJECT_DIRECTION_X;
				EXTRUDEOBJECT_DIRECTION_Y;
				EXTRUDEOBJECT_DIRECTION_Z;
				EXTRUDEOBJECT_DIRECTION_CUSTOM;
				EXTRUDEOBJECT_DIRECTION_ABSOLUTE;
			}
			ANIM ON;
		}
		REAL EXTRUDEOBJECT_EXTRUSIONOFFSET { UNIT METER; MINSLIDER 0.0; MAXSLIDER 1000.0; CUSTOMGUI REALSLIDER; }
		VECTOR EXTRUDEOBJECT_MOVE { UNIT METER; }
		LONG EXTRUDEOBJECT_SUB { MIN 1; MAX 4000; }
		LONG EXTRUDEOBJECT_ISOPARM { MIN 3; MAX 4000; }

		BOOL EXTRUDEOBJECT_FLIPNORMALS { }
		BOOL EXTRUDEOBJECT_HIERARCHIC  { }
	}
}
