CONTAINER Offd
{
	NAME Offd;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		VECTOR FFDOBJECT_SIZE	{ UNIT METER; }
		LONG   FFDOBJECT_XSUB { MIN 2; MAX 200; CUSTOMGUI LONGSLIDER; STEP 1; MINSLIDER 2; MAXSLIDER 10; DEFAULT 3; }
		LONG   FFDOBJECT_YSUB { MIN 2; MAX 200; CUSTOMGUI LONGSLIDER; STEP 1; MINSLIDER 2; MAXSLIDER 10; DEFAULT 3; } 
		LONG   FFDOBJECT_ZSUB { MIN 2; MAX 200; CUSTOMGUI LONGSLIDER; STEP 1; MINSLIDER 2; MAXSLIDER 10; DEFAULT 3; }
		SEPARATOR		{ LINE; }
		BUTTON	FFDOBJECT_FITTOPARENT	{  }
	}
}
