CONTAINER Oloft
{
	NAME Oloft;
	INCLUDE Obase;
	INCLUDE Onurbscaps;
	INCLUDE Onurbsselection;

	GROUP ID_OBJECTPROPERTIES
	{
		LONG LOFTOBJECT_SUBX { MIN 2; MAX 4000; }
		LONG LOFTOBJECT_SUBY { MIN 2; MAX 4000; }
		LONG LOFTOBJECT_ISOPARM { MIN 3; MAX 4000; }
		GROUP
		{
			COLUMNS 2;
			BOOL LOFTOBJECT_ORGANIC {}
			BOOL LOFTOBJECT_ADAPTIVEY {}
			BOOL LOFTOBJECT_CLOSEY {}
			BOOL LOFTOBJECT_LINEAR {}
			BOOL LOFTOBJECT_FITUV {}
			BOOL LOFTOBJECT_FLIPNORMALS {}
		}
	}
}
