CONTAINER Ometaball
{
	NAME Ometaball;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL METABALLOBJECT_THRESHOLD { UNIT PERCENT; MIN 0.0; MAX 1000.0; }
		REAL METABALLOBJECT_SUBEDITOR	{ UNIT METER; MIN 0.001; }
		REAL METABALLOBJECT_SUBRAY		{ UNIT METER; MIN 0.001; }
		BOOL METABALLOBJECT_EXPONENTIAL {}
		BOOL METABALLOBJECT_ACCURATENORMALS {}
	}
}
