CONTAINER Onull
{
	NAME Onull;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		LONG NULLOBJECT_DISPLAY	{ CYCLE { NULLOBJECT_DISPLAY_NONE; NULLOBJECT_DISPLAY_DOT; NULLOBJECT_DISPLAY_POINT; NULLOBJECT_DISPLAY_CIRCLE; NULLOBJECT_DISPLAY_RECTANGLE; NULLOBJECT_DISPLAY_DIAMOND; NULLOBJECT_DISPLAY_TRIANGLE; NULLOBJECT_DISPLAY_PENTAGON; NULLOBJECT_DISPLAY_HEXAGON; NULLOBJECT_DISPLAY_OCTAGON; NULLOBJECT_DISPLAY_STAR; NULLOBJECT_DISPLAY_AXIS; NULLOBJECT_DISPLAY_CUBE; NULLOBJECT_DISPLAY_PYRAMID; NULLOBJECT_DISPLAY_SPHERE; } }
		REAL NULLOBJECT_RADIUS { UNIT METER; MIN 0.0; }
		REAL NULLOBJECT_ASPECTRATIO	{ MIN 0.0; STEP 0.01; }
		LONG NULLOBJECT_ORIENTATION
		{
			CYCLE
			{
				NULLOBJECT_ORIENTATION_SCREEN;
				NULLOBJECT_ORIENTATION_ZY;
				NULLOBJECT_ORIENTATION_XZ;
				NULLOBJECT_ORIENTATION_XY;
			}
		}
	}
}
