CONTAINER Onurbscaps
{
	INCLUDE Obase;
	GROUP ID_CAPSANDBEVELS
	{
		BOOL CAPSANDBEVELS_CAP_ENABLE_START {}
		BOOL CAPSANDBEVELS_CAP_ENABLE_END {}

		SEPARATOR { LINE; }

		BOOL CAPSANDBEVELS_BEVEL_SEPARATE {}

		GROUP CAPSANDBEVELS_STARTBEVEL_GROUP
		{
			DEFAULT 1;
			LONG CAPSANDBEVELS_STARTBEVEL_TYPE
			{
				CYCLE
				{
					CAPSANDBEVELS_BEVEL_TYPE_ROUND;
					CAPSANDBEVELS_BEVEL_TYPE_CURVE;
					CAPSANDBEVELS_BEVEL_TYPE_SOLID;
					CAPSANDBEVELS_BEVEL_TYPE_STEP;
				}
			}

			REAL CAPSANDBEVELS_STARTBEVEL_OFFSET { UNIT METER; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 0.01; CUSTOMGUI REALSLIDER; }
			BOOL CAPSANDBEVELS_STARTBEVEL_MODE {}
			REAL CAPSANDBEVELS_STARTBEVEL_HEIGHT { UNIT METER; MINSLIDER -100.0; MAXSLIDER 100.0; STEP 0.01; CUSTOMGUI REALSLIDER; }
			SPLINE CAPSANDBEVELS_STARTBEVEL_CURVE {}
			REAL CAPSANDBEVELS_STARTBEVEL_DEPTH { UNIT PERCENT; MINSLIDER -100; MAXSLIDER 100; CUSTOMGUI REALSLIDER; PARENTCOLLAPSE;}
				BOOL CAPSANDBEVELS_STARTBEVEL_ALONGNORMALS { PARENTCOLLAPSE CAPSANDBEVELS_STARTBEVEL_DEPTH; }
				BOOL CAPSANDBEVELS_STARTBEVEL_ABSOLUTE { PARENTCOLLAPSE CAPSANDBEVELS_STARTBEVEL_DEPTH; }
				REAL CAPSANDBEVELS_STARTBEVEL_ABSOLUTEDEPTH { PARENTCOLLAPSE CAPSANDBEVELS_STARTBEVEL_DEPTH; UNIT METER; MINSLIDER -100; MAXSLIDER 100; CUSTOMGUI REALSLIDER;}

			LONG CAPSANDBEVELS_STARTBEVEL_SEGMENTS	{ MIN 1; MAX 100; }

			GROUP
			{
				COLUMNS 2;
				BUTTON CAPSANDBEVELS_STARTBEVEL_LOADPRESET {}
				BUTTON CAPSANDBEVELS_STARTBEVEL_SAVEPRESET {}
			}
		}

		GROUP CAPSANDBEVELS_ENDBEVEL_GROUP
		{
			DEFAULT 1;
			LONG CAPSANDBEVELS_ENDBEVEL_TYPE
			{
				CYCLE
				{
					CAPSANDBEVELS_BEVEL_TYPE_ROUND;
					CAPSANDBEVELS_BEVEL_TYPE_CURVE;
					CAPSANDBEVELS_BEVEL_TYPE_SOLID;
					CAPSANDBEVELS_BEVEL_TYPE_STEP;
				}
			}

			REAL CAPSANDBEVELS_ENDBEVEL_OFFSET	{ UNIT METER; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 0.01; CUSTOMGUI REALSLIDER; }
			BOOL CAPSANDBEVELS_ENDBEVEL_MODE {}
			REAL CAPSANDBEVELS_ENDBEVEL_HEIGHT { UNIT METER; MINSLIDER -100.0; MAXSLIDER 100.0; STEP 0.01; CUSTOMGUI REALSLIDER; }
			SPLINE CAPSANDBEVELS_ENDBEVEL_CURVE {}
			REAL CAPSANDBEVELS_ENDBEVEL_DEPTH { UNIT PERCENT; MINSLIDER -100; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; PARENTCOLLAPSE;}
				BOOL CAPSANDBEVELS_ENDBEVEL_ALONGNORMALS { PARENTCOLLAPSE CAPSANDBEVELS_ENDBEVEL_DEPTH; }
				BOOL CAPSANDBEVELS_ENDBEVEL_ABSOLUTE { PARENTCOLLAPSE CAPSANDBEVELS_ENDBEVEL_DEPTH; }
				REAL CAPSANDBEVELS_ENDBEVEL_ABSOLUTEDEPTH { PARENTCOLLAPSE CAPSANDBEVELS_ENDBEVEL_DEPTH; UNIT METER; MINSLIDER -100; MAXSLIDER 100; CUSTOMGUI REALSLIDER;}

			LONG CAPSANDBEVELS_ENDBEVEL_SEGMENTS	{ MIN 1; MAX 100; }

			GROUP
			{
				COLUMNS 2;
				BUTTON CAPSANDBEVELS_ENDBEVEL_LOADPRESET {}
				BUTTON CAPSANDBEVELS_ENDBEVEL_SAVEPRESET {}
			}
		}

		SEPARATOR { LINE; }

		BOOL CAPSANDBEVELS_BEVEL_OUTSIDE {}
		BOOL CAPSANDBEVELS_AVOIDINTERSECTION {}

		SEPARATOR { LINE; }

		LONG CAPSANDBEVELS_CAP_TYPE
		{
			CYCLE
			{
				CAPSANDBEVELS_CAP_TYPE_TRI;
				CAPSANDBEVELS_CAP_TYPE_QUAD;
				CAPSANDBEVELS_CAP_TYPE_NGON;
				CAPSANDBEVELS_CAP_TYPE_DELAUNAY;
				CAPSANDBEVELS_CAP_TYPE_REGULAR;
			}
			PARENTCOLLAPSE;
		}

		REAL CAPSANDBEVELS_CAP_DELAUNAY_GRAD { UNIT PERCENT; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER; STEP 0.01; PARENTCOLLAPSE CAPSANDBEVELS_CAP_TYPE; MAX 100;}
		REAL CAPSANDBEVELS_CAP_REGULAR_SIZE {UNIT METER; MINSLIDER 0; MAXSLIDER 100; CUSTOMGUI REALSLIDER; STEP 0.01; PARENTCOLLAPSE CAPSANDBEVELS_CAP_TYPE; MIN 0.0;}
		BOOL CAPSANDBEVELS_CAP_DELAUNAY_QUAD { PARENTCOLLAPSE CAPSANDBEVELS_CAP_TYPE; }

		BOOL CAPSANDBEVELS_PHONGBREAKROUNDING {}
	}
}
