CONTAINER Onurbsselection
{
	INCLUDE Obase;
	GROUP ID_GENERATOR_SELECTION_POLYGONS
	{
		GROUP 
		{
			DEFAULT 1;
			COLUMNS 2;

			BOOL GENERATOR_SELECTION_POLYGON_SHELL { ANIM OFF; }
			STATICTEXT GENERATOR_SELECTION_NAME_POLYGON_SHELL { SCALE_H; }
			BOOL GENERATOR_SELECTION_POLYGON_CAP_START { ANIM OFF; }
			STATICTEXT GENERATOR_SELECTION_NAME_POLYGON_CAP_START { SCALE_H; }
			BOOL GENERATOR_SELECTION_POLYGON_CAP_END { ANIM OFF; }
			STATICTEXT GENERATOR_SELECTION_NAME_POLYGON_CAP_END { SCALE_H; }
			BOOL GENERATOR_SELECTION_POLYGON_BEVEL_START { ANIM OFF; }
			STATICTEXT GENERATOR_SELECTION_NAME_POLYGON_BEVEL_START { SCALE_H; }
			BOOL GENERATOR_SELECTION_POLYGON_BEVEL_END { ANIM OFF; }
			STATICTEXT GENERATOR_SELECTION_NAME_POLYGON_BEVEL_END { SCALE_H; }
		}

		SEPARATOR ID_GENERATOR_SELECTION_EDGES {}
		GROUP 
		{
			DEFAULT 1;
			COLUMNS 2;

			BOOL GENERATOR_SELECTION_EDGE_SHELL_START { ANIM OFF; }
			STATICTEXT GENERATOR_SELECTION_NAME_EDGE_SHELL_START { SCALE_H; }
			BOOL GENERATOR_SELECTION_EDGE_SHELL_END { ANIM OFF; }
			STATICTEXT GENERATOR_SELECTION_NAME_EDGE_SHELL_END { SCALE_H; }
			BOOL GENERATOR_SELECTION_EDGE_CAP_START { ANIM OFF; }
			STATICTEXT GENERATOR_SELECTION_NAME_EDGE_CAP_START { SCALE_H; }
			BOOL GENERATOR_SELECTION_EDGE_CAP_END { ANIM OFF; }
			STATICTEXT GENERATOR_SELECTION_NAME_EDGE_CAP_END { SCALE_H; }
			BOOL GENERATOR_SELECTION_EDGE_STEP_START { ANIM OFF; }
			STATICTEXT GENERATOR_SELECTION_NAME_EDGE_STEP_START { SCALE_H; }
			BOOL GENERATOR_SELECTION_EDGE_STEP_END { ANIM OFF; }
			STATICTEXT GENERATOR_SELECTION_NAME_EDGE_STEP_END { SCALE_H; }
		}
	}
}
