CONTAINER Onurbscapslegacy
{
	INCLUDE Obase;
	GROUP ID_CAPSANDROUNDING
	{
		BUTTON CAP_MIGRATE_BUTTON {}

		LONG CAP_START
		{
			CYCLE
			{
				CAPTYPE_NOCAP;
				CAPTYPE_CAP;
				CAPTYPE_ROUNDING;
				CAPTYPE_ROUNDINGANDCAP;
			}
		}
		LONG CAP_STARTSTEPS  { PARENTID CAP_START; MIN 1; MAX 100; }
		REAL CAP_STARTRADIUS { PARENTID CAP_START; UNIT METER; MIN 0.0; }

		LONG CAP_END
		{
			CYCLE
			{
				CAPTYPE_NOCAP;
				CAPTYPE_CAP;
				CAPTYPE_ROUNDING;
				CAPTYPE_ROUNDINGANDCAP;
			}
		}
		LONG CAP_ENDSTEPS   { PARENTID CAP_END; MIN 1; MAX 100; }
		REAL CAP_ENDRADIUS  { PARENTID CAP_END; UNIT METER; MIN 0.0; }


		SEPARATOR { }

		LONG CAP_ROUNDING
		{
			CYCLE
			{
				CAP_ROUNDING_LINEAR;
				CAP_ROUNDING_CONVEX;
				CAP_ROUNDING_CONCAVE;
				CAP_ROUNDING_HALFCIRCLE;
				CAP_ROUNDING_STEP;
				CAP_ROUNDING_2STEPS;
				CAP_ROUNDING_ENGRAVED;
			}
		}


		REAL CAP_PHONG { UNIT DEGREE; MIN 0.0; MAX 180.0; }

		SEPARATOR { }

		BOOL CAP_HULLINWARD {}
		BOOL CAP_HOLEINWARD {}
		BOOL CAP_CONSTRAIN  {}
		BOOL CAP_CONNECT {}
		BOOL CAP_UVWROUDING {}

		SEPARATOR { }

		LONG CAP_TYPE
		{ 
			CYCLE
			{
				CAP_TYPE_TRI;
				CAP_TYPE_QUAD;
				CAP_TYPE_NGON;
			}			
		}
		BOOL CAP_REGULAR    {}
		REAL CAP_REGULARWIDTH { PARENTID CAP_REGULAR; UNIT METER; MIN 0.01; }
	}
}
