CONTAINER Ospline
{
	NAME Ospline;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		LONG SPLINEOBJECT_TYPE
		{
			CYCLE
			{
				SPLINEOBJECT_TYPE_LINEAR;
				SPLINEOBJECT_TYPE_CUBIC;
				SPLINEOBJECT_TYPE_AKIMA;
				SPLINEOBJECT_TYPE_BSPLINE;
				SPLINEOBJECT_TYPE_BEZIER;
			}
		}

		BOOL SPLINEOBJECT_CLOSED {}

		LONG SPLINEOBJECT_INTERPOLATION
		{
			CYCLE
			{
				SPLINEOBJECT_INTERPOLATION_NONE;
				SPLINEOBJECT_INTERPOLATION_NATURAL;
				SPLINEOBJECT_INTERPOLATION_UNIFORM;
				SPLINEOBJECT_INTERPOLATION_ADAPTIVE;
				SPLINEOBJECT_INTERPOLATION_SUBDIV;
			}
		}

		LONG SPLINEOBJECT_SUB { MIN 0; MAX 5000; }
		REAL SPLINEOBJECT_ANGLE { UNIT DEGREE; MIN 0.0; MAX 90.0; }
		REAL SPLINEOBJECT_MAXIMUMLENGTH	{ UNIT METER; MIN 0.01; }
	}
}
