CONTAINER Osweep
{
	NAME Osweep;
	INCLUDE Obase;
	INCLUDE Onurbscaps;
	INCLUDE Onurbsselection;

	GROUP ID_OBJECTPROPERTIES
	{
		GROUP
		{
			LONG SWEEPOBJECT_ISOPARM { MIN 3; MAX 10000; }
			REAL SWEEPOBJECT_SCALE  { UNIT PERCENT; MIN 0.0; }
			REAL SWEEPOBJECT_ROTATE { UNIT DEGREE; }
			REAL SWEEPOBJECT_STARTGROWTH { UNIT PERCENT; MIN 0.0; MAX 100.0; }
			REAL SWEEPOBJECT_GROWTH { UNIT PERCENT; MIN 0.0; MAX 100.0; }
		}
		GROUP
		{
			COLUMNS 2;
			BOOL SWEEPOBJECT_PARALLEL {}
			BOOL SWEEPOBJECT_CONSTANT {}
			BOOL SWEEPOBJECT_BANKING {}
			BOOL SWEEPOBJECT_KEEPSEGMENTS {}
			BOOL SWEEPOBJECT_RAILDIRECTION {}
			BOOL SWEEPOBJECT_BIRAIL {}
			BOOL SWEEPOBJECT_RAILSCALE {}
			BOOL SWEEPOBJECT_FLIPNORMALS {}
			BOOL SWEEPOBJECT_GROWUV {}
		}
		GROUP SWEEPOBJECT_PROFILES
		{
			SPLINE SWEEPOBJECT_SPLINESCALE { }
			SPLINE SWEEPOBJECT_SPLINEROTATION { }

			GROUP
			{
				COLUMNS 2;
				REAL SWEEPOBJECT_ROTATIONFROM	{ UNIT DEGREE; }
				REAL SWEEPOBJECT_ROTATIONTO	{ UNIT DEGREE; }
			}
		}
	}
}
