CONTAINER Osymmetry
{
	NAME Osymmetry;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		LONG SYMMETRYOBJECT_PLANE
		{
			CYCLE
			{
				SYMMETRYOBJECT_PLANE_XY;
				SYMMETRYOBJECT_PLANE_YZ;
				SYMMETRYOBJECT_PLANE_XZ;
			}
		}
		BOOL SYMMETRYOBJECT_WELD {}
		REAL SYMMETRYOBJECT_TOLERANCE { PARENTID SYMMETRYOBJECT_WELD; UNIT METER; MIN 0.0; }
		BOOL SYMMETRYOBJECT_ONPLANE { PARENTID SYMMETRYOBJECT_WELD; }
		GROUP SYMMETRYOBJECT_GROUP_MODELING
		{
			DEFAULT 1;
			BOOL SYMMETRYOBJECT_CLAMPPOINTS { ANIM OFF; PARENTID SYMMETRYOBJECT_WELD; }
			BOOL SYMMETRYOBJECT_DELETEPOLYGONS { ANIM OFF; PARENTID SYMMETRYOBJECT_WELD; }
			BOOL SYMMETRYOBJECT_AUTOFLIP { ANIM OFF; PARENTID SYMMETRYOBJECT_WELD; }
			BUTTON SYMMETRYOBJECT_FLIP { ANIM OFF; PARENTID SYMMETRYOBJECT_WELD; } 
		}
	}
}
