CONTAINER Prefstheme
{
	NAME Prefstheme;
	SCALE_V;
	
	GROUP PREF_THEME_MAIN_GROUP
	{
		DEFAULT 1;
		COLUMNS 1;
		SCALE_V;

		GROUP
		{	
			DEFAULT 1;
			COLUMNS 1;
			SCALE_V;

			LISTVIEW PREF_THEME_LIST { COLOR; SCALE_V; SCALE_H; }
		}
		
		GROUP
		{
			DEFAULT 1;
			COLUMNS 1;

			SEPARATOR { }
			LONG PREF_THEME_TYPE 
			{ 
				ANIM OFF; 
				CYCLE 
				{ 
					PREF_THEME_TYPERGB;
					PREF_THEME_TYPEBMP;
					PREF_THEME_TYPEREF;
				}
			}

			SEPARATOR { }
			COLOR PREF_THEME_COLORS { OPEN; }
			FILENAME PREF_THEME_BMP { }
			BITMAPBUTTON PREF_THEME_BMPPIC { BORDER;}	 
			LISTVIEW PREF_THEME_REF { COLOR;}

			SEPARATOR { LINE; }
			GROUP
			{
				DEFAULT 1;
				COLUMNS 2;
				BOOL PREF_THEME_LIVE { ANIM OFF; }
				BUTTON PREF_THEME_RESET { }
			}
		}
	}
}
