CONTAINER Tcoffeeexpression
{
  NAME Tcoffeeexpression;
  INCLUDE Tbase;

	GROUP Obaselist
	{
    SCALE_V;
    STRING COFFEEEXPRESSION_CODE { ANIM OFF; CUSTOMGUI MULTISTRING; READONLY; SCALE_V; }
  }

  GROUP ID_TAGPROPERTIES
  {
  }
}
