CONTAINER Tcompositing
{
	NAME Tcompositing;
	INCLUDE Tbase;

	GROUP ID_TAGPROPERTIES
	{
		GROUP
		{
			LAYOUTGROUP; COLUMNS 2;
			GROUP
			{
				BOOL COMPOSITINGTAG_CASTSHADOW		{ }
				BOOL COMPOSITINGTAG_RECEIVESHADOW	{ }
				BOOL COMPOSITINGTAG_SELFSHADOW		{ }

				SEPARATOR { }

				BOOL COMPOSITINGTAG_SEENBYCAMERA	{ }
				BOOL COMPOSITINGTAG_SEENBYRAYS		{ }
				BOOL COMPOSITINGTAG_SEENBYGI		{ }
			}

			GROUP
			{
				BOOL COMPOSITINGTAG_BACKGROUND		{ }
				BOOL COMPOSITINGTAG_BACKGROUND_GI	{ }
				
				STATICTEXT { }
				SEPARATOR { }

				BOOL COMPOSITINGTAG_SEENBYTRANSPARENCY	{ }
				BOOL COMPOSITINGTAG_SEENBYREFRACTION	{ }
				BOOL COMPOSITINGTAG_SEENBYREFLECTION	{ }
				BOOL COMPOSITINGTAG_SEENBYAO            { }
			}
		}

		SEPARATOR { }
		BOOL COMPOSITINGTAG_AAOVERWRITE		{ }
		LONG COMPOSITINGTAG_AAMINLEVEL		{ PARENTID COMPOSITINGTAG_AAOVERWRITE; CYCLE { COMPOSITINGTAG_AALEVEL_1;COMPOSITINGTAG_AALEVEL_2;COMPOSITINGTAG_AALEVEL_4;COMPOSITINGTAG_AALEVEL_8;COMPOSITINGTAG_AALEVEL_16; }}
		LONG COMPOSITINGTAG_AAMAXLEVEL		{ PARENTID COMPOSITINGTAG_AAOVERWRITE; CYCLE { COMPOSITINGTAG_AALEVEL_1;COMPOSITINGTAG_AALEVEL_2;COMPOSITINGTAG_AALEVEL_4;COMPOSITINGTAG_AALEVEL_8;COMPOSITINGTAG_AALEVEL_16; }}
		REAL COMPOSITINGTAG_AATHRESHOLD		{ PARENTID COMPOSITINGTAG_AAOVERWRITE; UNIT PERCENT; MIN 0; MAX 100; }
		SEPARATOR { }
		BOOL COMPOSITINGTAG_MATTEOBJECT		{ }
		COLOR COMPOSITINGTAG_MATTECOLOR	{ PARENTID COMPOSITINGTAG_MATTEOBJECT; }
	}

	GROUP COMPOSITINGTAG_GROUPGI
	{
		GROUP
		{
			BOOL COMPOSITINGTAG_GIENABLED			{ }			
			REAL COMPOSITINGTAG_GIINTENSITY			{ PARENTID COMPOSITINGTAG_GIENABLED; MIN 0.0; MAX 1000.0; UNIT PERCENT; }
			REAL COMPOSITINGTAG_GIQUALITY			{ PARENTID COMPOSITINGTAG_GIENABLED; MIN 1.0; MAX 1000.0; UNIT PERCENT; }
			REAL COMPOSITINGTAG_GIDENSITY			{ PARENTID COMPOSITINGTAG_GIENABLED; MIN 1.0; MAX 1000.0; UNIT PERCENT; }	
			BOOL COMPOSITINGTAG_GIQMC			{ PARENTID COMPOSITINGTAG_GIENABLED; }
			BOOL COMPOSITINGTAG_GITRANSPARENCY		{ PARENTID COMPOSITINGTAG_GIENABLED; }
			BOOL COMPOSITINGTAG_GIINTERPOLATION		{ PARENTID COMPOSITINGTAG_GIENABLED; }
		}

	}
	
	GROUP COMPOSITINGTAG_GROUPINEXCLUSION
	{
		SCALE_V;

		GROUP
		{
			SCALE_V;
			COLUMNS 2;
			LONG COMPOSITINGTAG_EXCLUSION_MODE
			{
				CYCLE
				{
					COMPOSITINGTAG_EXCLUSION_MODE_INCLUDE;
					COMPOSITINGTAG_EXCLUSION_MODE_EXCLUDE;
				}
			}
			STATICTEXT { DUMMY; }
			IN_EXCLUDE COMPOSITINGTAG_EXCLUSION_LIST { SCALE_V; NUM_FLAGS 4; INIT_STATE 14; IMAGE_01_ON 300000103; IMAGE_02_ON 300000104; IMAGE_03_ON 300000105; IMAGE_04_ON 1009316; IMAGE_01_OFF 300000100; IMAGE_02_OFF 300000101; IMAGE_03_OFF 300000102; IMAGE_04_OFF 1009320; ACCEPT { Obase; }; }
			STATICTEXT { JOINENDSCALE; }
		}
	}

	GROUP COMPOSITINGTAG_GROUPOBJBUFFER
	{
		COLUMNS 2;
		BOOL COMPOSITINGTAG_ENABLECHN0		{ }
		LONG COMPOSITINGTAG_IDCHN0				{ MIN 1; MAX 10000; }
		BOOL COMPOSITINGTAG_ENABLECHN1		{ }
		LONG COMPOSITINGTAG_IDCHN1				{ MIN 1; MAX 10000; }
		BOOL COMPOSITINGTAG_ENABLECHN2		{ }
		LONG COMPOSITINGTAG_IDCHN2				{ MIN 1; MAX 10000; }
		BOOL COMPOSITINGTAG_ENABLECHN3		{ }
		LONG COMPOSITINGTAG_IDCHN3				{ MIN 1; MAX 10000; }
		BOOL COMPOSITINGTAG_ENABLECHN4		{ }
		LONG COMPOSITINGTAG_IDCHN4				{ MIN 1; MAX 10000; }
		BOOL COMPOSITINGTAG_ENABLECHN5		{ }
		LONG COMPOSITINGTAG_IDCHN5				{ MIN 1; MAX 10000; }
		BOOL COMPOSITINGTAG_ENABLECHN6		{ }
		LONG COMPOSITINGTAG_IDCHN6				{ MIN 1; MAX 10000; }
		BOOL COMPOSITINGTAG_ENABLECHN7		{ }
		LONG COMPOSITINGTAG_IDCHN7				{ MIN 1; MAX 10000; }
		BOOL COMPOSITINGTAG_ENABLECHN8		{ }
		LONG COMPOSITINGTAG_IDCHN8				{ MIN 1; MAX 10000; }
		BOOL COMPOSITINGTAG_ENABLECHN9		{ }
		LONG COMPOSITINGTAG_IDCHN9				{ MIN 1; MAX 10000; }
		BOOL COMPOSITINGTAG_ENABLECHN10  	{ }
		LONG COMPOSITINGTAG_IDCHN10				{ MIN 1; MAX 10000; }
		BOOL COMPOSITINGTAG_ENABLECHN11		{ }
		LONG COMPOSITINGTAG_IDCHN11				{ MIN 1; MAX 10000; }
	}

	GROUP COMPOSITINGTAG_GROUPRPR
	{
		BOOL COMPOSITINGTAG_RPRSHADOWCATCHER		{ }
		BOOL COMPOSITINGTAG_RPRLIGHTPORTAL		{ }
		SEPARATOR COMPOSITINGTAG_RPROBJECTGROUPID_GROUP { }
		COLOR COMPOSITINGTAG_RPROBJECTGROUPID { }
	}
}
