CONTAINER Tdisplay
{
	NAME Tdisplay;
	INCLUDE Tbase;

	GROUP ID_TAGPROPERTIES
	{
		COLUMNS 2;
		BOOL DISPLAYTAG_AFFECT_DISPLAYMODE { }
		LONG DISPLAYTAG_SDISPLAYMODE
		{
			CYCLE
			{
				DISPLAYTAG_SDISPLAY_GOURAUD					;
				DISPLAYTAG_SDISPLAY_GOURAUD_WIRE		;
				DISPLAYTAG_SDISPLAY_QUICK						;
				DISPLAYTAG_SDISPLAY_QUICK_WIRE			;
				DISPLAYTAG_SDISPLAY_FLAT						;
				DISPLAYTAG_SDISPLAY_FLAT_WIRE				;
				DISPLAYTAG_SDISPLAY_HIDDENLINE			;
				DISPLAYTAG_SDISPLAY_NOSHADING				;
			}
		}
		STATICTEXT { DUMMY; }
		LONG DISPLAYTAG_WDISPLAYMODE
		{
			CYCLE
			{
				DISPLAYTAG_WDISPLAY_WIREFRAME				;
				DISPLAYTAG_WDISPLAY_ISOPARMS				;
				DISPLAYTAG_WDISPLAY_BOX							;
				DISPLAYTAG_WDISPLAY_SKELETON				;
			}
		}
		STATICTEXT { DUMMY; }
		LONG DISPLAYTAG_VDISPLAYMODE
		{
			CYCLE
			{
				DISPLAYTAG_VDISPLAY_DIRECTION;
				DISPLAYTAG_VDISPLAY_LENGTH;
			}
		}
		BOOL DISPLAYTAG_AFFECT_LEVELOFDETAIL { }
		REAL DISPLAYTAG_LEVELOFDETAIL { UNIT PERCENT; MIN 0.0; MAX 1000; }
		BOOL DISPLAYTAG_AFFECT_VISIBILITY { }
		REAL DISPLAYTAG_VISIBILITY { UNIT PERCENT; MIN 0.0; MAX 100.0; }
		BOOL DISPLAYTAG_AFFECT_BACKFACECULLING { }
		BOOL DISPLAYTAG_BACKFACECULLING { }
		BOOL DISPLAYTAG_AFFECT_TEXTURES { }
		BOOL DISPLAYTAG_TEXTURES { }
		BOOL DISPLAYTAG_AFFECT_REFLECTIONS { }
		BOOL DISPLAYTAG_REFLECTIONS { }
		BOOL DISPLAYTAG_AFFECT_TESSELLATION { }
		BOOL DISPLAYTAG_TESSELLATION { }
		
		DEFAULT 1;
	}


	GROUP ID_ONION_GROUP
	{
		COLUMNS 2;

		BOOL ONION_USE {ANIM OFF;} STATICTEXT {}
		LONG ONION_MODE
		{
			PARENTCOLLAPSE;
			ANIM OFF;
			CYCLE
			{
				ONION_MODE_OBJECT;
				ONION_MODE_POINT;
				ONION_MODE_AXIS;
				ONION_MODE_TRAIL;
				ONION_MODE_MTRAIL;
				ONION_MODE_VELOCITY;
			}
		}
		STATICTEXT {}

		REAL ONION_SCALE { PARENTCOLLAPSE ONION_MODE; MIN 0; MINEX;  ANIM OFF; UNIT PERCENT;}  STATICTEXT {NEWLINE;}
		LONG ONION_PSIZE { PARENTCOLLAPSE ONION_MODE; MIN 0; MINEX; MAX 10; ANIM OFF;}         STATICTEXT {NEWLINE;}

		LONG ONION_DISPLAYMODE
		{
			PARENTCOLLAPSE ONION_MODE;
			ANIM OFF; 
			
			CYCLE
			{
				ONION_DISPLAY_GOURAUD;
				ONION_DISPLAY_GOURAUD_WIRE;
				ONION_DISPLAY_QUICK;
				ONION_DISPLAY_QUICK_WIRE;
				ONION_DISPLAY_FLAT;
				ONION_DISPLAY_FLAT_WIRE;
				ONION_DISPLAY_NOSHADING;
			}
		}
		STATICTEXT {NEWLINE;}

		BOOL ONION_XRAY  { PARENTCOLLAPSE ONION_MODE; ANIM OFF;} STATICTEXT {NEWLINE;}

		SEPARATOR { LINE; }  STATICTEXT { JOINEND; }

		LONG ONION_FRAMES_BEFORE { MIN 0; ANIM OFF;} COLOR ONION_COL_FRAMES_BEFORE { SCALE_H; ANIM OFF;}
		LONG ONION_FRAMES_AFTER  { MIN 0; ANIM OFF;} COLOR ONION_COL_FRAMES_AFTER  { SCALE_H; ANIM OFF;}
		LONG ONION_FRAMES_STEP   { MIN 1; ANIM OFF;} STATICTEXT {}

		SEPARATOR { LINE; } STATICTEXT { JOINEND; }

		BOOL	ONION_ONLY_RANGE {ANIM OFF;} STATICTEXT {}
		BASETIME ONION_FROM    {ANIM OFF;} STATICTEXT {}
		BASETIME ONION_TO      {ANIM OFF;} STATICTEXT {}


		SEPARATOR { LINE; }  STATICTEXT { JOINEND; }

		BOOL ONION_USE_KEYS      {ANIM OFF;} STATICTEXT {}
		LONG ONION_KEYS_BEFORE   { MIN 0; ANIM OFF;} COLOR ONION_COL_KEYS_BEFORE   { SCALE_H; ANIM OFF;}
		LONG ONION_KEYS_AFTER    { MIN 0; ANIM OFF;} COLOR ONION_COL_KEYS_AFTER    { SCALE_H; ANIM OFF;}

		SEPARATOR { LINE; }  STATICTEXT { JOINEND; }

		BOOL   ONION_USE_CUSTOM {ANIM OFF;} STATICTEXT {}
		STRING ONION_CUSTOM     {ANIM OFF; ALIGN_LEFT; } COLOR ONION_COL_CUSTOM  { SCALE_H; ANIM OFF;}

		SEPARATOR { LINE; }  STATICTEXT { JOINEND; }

		BOOL	 ONION_CACHE       {ANIM OFF;}                  STATICTEXT {}
		STATICTEXT ONION_CACHE_INFO1 { SCALE_H;  ALIGN_LEFT;} STATICTEXT {}

		BUTTON ONION_CALCULATE   { } STATICTEXT {}
		BUTTON ONION_DELCACHE    { } STATICTEXT {}

		DEFAULT 0;
	}
}
