CONTAINER Tedgeselection
{
	NAME Tedgeselection;
	INCLUDE Texpression;

	GROUP Obaselist
	{
		DEFAULT 1;

		BOOL EDGESELECTIONTAG_ENABLEFIELDS {}

		GROUP
		{
			COLUMNS 3;
			
			BUTTON EDGESELECTIONTAG_COMMAND1 { FIT_H; }
			BUTTON EDGESELECTIONTAG_COMMAND3 { FIT_H; }
			BUTTON EDGESELECTIONTAG_COMMAND5 { FIT_H; }

			BUTTON EDGESELECTIONTAG_COMMAND2 { FIT_H; }
			BUTTON EDGESELECTIONTAG_COMMAND4 { FIT_H; }
			BUTTON EDGESELECTIONTAG_COMMAND6 { FIT_H; }
		}
	}

	GROUP EDGESELECTIONTAG_FIELDGROUP
	{
		FIELD HIDE;
		DEFAULT 1;
		REAL EDGESELECTIONTAG_FIELDTOLERANCE { UNIT PERCENT; ANIM ON; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		BOOL EDGESELECTIONTAG_DEFORMEDSTATE { ANIM ON; }
		FIELDLIST EDGESELECTIONTAG_FIELDS { NEWLINE; ANIM ON; NOCOLOR; NODIRECTION; NOROTATION; }
	}
}
