CONTAINER Tnormal
{
	NAME Tnormal;
	INCLUDE Texpression;

	GROUP ID_TAGPROPERTIES
	{
		BUTTON NORMALTAG_ALIGN_FACE2VERTEX {}
		BUTTON NORMALTAG_ALIGN_VERTEX2FACE {}
		BUTTON NORMALTAG_SWAP_NORMALS {}
		BOOL NORMALTAG_USE_FIELDS {}
	}
	GROUP	NORMALTAG_FIELDS_GROUP
	{
		BOOL NORMALTAG_DEFORMEDSTATE { ANIM ON; }
		FIELDLIST NORMALTAG_FIELDS { NEWLINE; ANIM ON; NOVALUE; NOCOLOR; NOROTATION; }
	}
}
