CONTAINER Tpolygonselection
{
	NAME Tpolygonselection;
	INCLUDE Texpression;

	GROUP Obaselist
	{
		DEFAULT 1;

		BOOL POLYGONSELECTIONTAG_ENABLEFIELDS {}

		GROUP
		{
			COLUMNS 3;
			
			BUTTON POLYGONSELECTIONTAG_COMMAND1 { FIT_H; }
			BUTTON POLYGONSELECTIONTAG_COMMAND3 { FIT_H; }
			BUTTON POLYGONSELECTIONTAG_COMMAND5 { FIT_H; }

			BUTTON POLYGONSELECTIONTAG_COMMAND2 { FIT_H; }
			BUTTON POLYGONSELECTIONTAG_COMMAND4 { FIT_H; }
			BUTTON POLYGONSELECTIONTAG_COMMAND6 { FIT_H; }
			}
	}

	GROUP POLYGONSELECTIONTAG_FIELDGROUP
	{
		FIELD HIDE;
		DEFAULT 1;
		REAL POLYGONSELECTIONTAG_FIELDTOLERANCE { UNIT PERCENT; ANIM ON; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		BOOL POLYGONSELECTIONTAG_DEFORMEDSTATE { ANIM ON; }
		FIELDLIST POLYGONSELECTIONTAG_FIELDS { NEWLINE; ANIM ON; NOCOLOR; NODIRECTION; NOROTATION; }
	}
}
