CONTAINER Tprotection
{
	NAME Tprotection;
	INCLUDE Tbase;
	
	GROUP ID_TAGPROPERTIES
	{
		GROUP
		{
			COLUMNS 4;
			
			LONG PROTECTION_P
			{
				CYCLE
				{
					PROTECTION_NONE;
					PROTECTION_LOCK;
					PROTECTION_LIMIT;
				}
			}
			
			BOOL PROTECTION_P_X { }
			REAL PROTECTION_P_MIN_X { UNIT METER; }
			REAL PROTECTION_P_MAX_X { UNIT METER; }
			
			STATICTEXT { }
			BOOL PROTECTION_P_Y { }
			REAL PROTECTION_P_MIN_Y { UNIT METER; }
			REAL PROTECTION_P_MAX_Y { UNIT METER; }

			STATICTEXT { }
			BOOL PROTECTION_P_Z { }
			REAL PROTECTION_P_MIN_Z { UNIT METER; }
			REAL PROTECTION_P_MAX_Z { UNIT METER; }			
		}
		
		SEPARATOR { }
		
		GROUP
		{
			COLUMNS 4;
			
			LONG PROTECTION_S
			{
				CYCLE
				{
					PROTECTION_NONE;
					PROTECTION_LOCK;
					PROTECTION_LIMIT;
				}
			}
			BOOL PROTECTION_S_X { }
			REAL PROTECTION_S_MIN_X { }
			REAL PROTECTION_S_MAX_X { }
			
			STATICTEXT { }
			BOOL PROTECTION_S_Y { }
			REAL PROTECTION_S_MIN_Y { }
			REAL PROTECTION_S_MAX_Y { }
						
			STATICTEXT { }
			BOOL PROTECTION_S_Z { }
			REAL PROTECTION_S_MIN_Z { }
			REAL PROTECTION_S_MAX_Z { }			
		}
		
		SEPARATOR { }
		
		GROUP
		{
			COLUMNS 4;
				
			LONG PROTECTION_R
			{
				CYCLE
				{
					PROTECTION_NONE;
					PROTECTION_LOCK;
					PROTECTION_LIMIT;
				}
			}
			
			BOOL PROTECTION_R_X { }
			REAL PROTECTION_R_MIN_X { UNIT DEGREE; }
			REAL PROTECTION_R_MAX_X { UNIT DEGREE; }
			
			STATICTEXT { }
			BOOL PROTECTION_R_Y { }
			REAL PROTECTION_R_MIN_Y { UNIT DEGREE; }
			REAL PROTECTION_R_MAX_Y { UNIT DEGREE; }
						
			STATICTEXT { }
			BOOL PROTECTION_R_Z { }
			REAL PROTECTION_R_MIN_Z { UNIT DEGREE; }
			REAL PROTECTION_R_MAX_Z { UNIT DEGREE; }			
		}
		
		BOOL PROTECTION_ALLOW_EXPRESSIONS { }
		BOOL PROTECTION_ALLOW_DUPLICATION { }
	}
}
