CONTAINER Tsticktexture
{
	NAME Tsticktexture;
	INCLUDE Tbase;

	GROUP ID_TAGPROPERTIES
	{
		BOOL STICKTEXTURETAG_ACTIVE    { }
		GROUP
		{
			COLUMNS 2;
			BUTTON STICKTEXTURETAG_RECORD  { }
			BUTTON STICKTEXTURETAG_RESET   { }
		}
	}
}
