CONTAINER Ttargetexpression
{
	NAME Ttargetexpression;
	INCLUDE Texpression;

	GROUP ID_TAGPROPERTIES
	{
		LINK TARGETEXPRESSIONTAG_LINK { ANIM MIX; ACCEPT { Obase; } }
		LINK TARGETEXPRESSIONTAG_UP_LINK { ANIM MIX; ACCEPT { Obase; } }
		BOOL TARGETEXPRESSIONTAG_PITCH { }
	}
}
