CONTAINER Ttexture
{
	NAME Ttexture;
	INCLUDE Tbase;

	GROUP ID_TAGPROPERTIES
	{
		GROUP
		{
			COLUMNS 2;

			LINK TEXTURETAG_MATERIAL { FIT_H; ANIM MIX; ACCEPT { Mbase; } REFUSE { 1011014; 1017730; } } // Mbase
			STATICTEXT { JOINENDSCALE; }

			BUTTON TEXTURETAG_STOPINTERACTIVEMAPPING { FIT_H; HIDDEN; }
			STATICTEXT { DUMMY; }

			STRING TEXTURETAG_RESTRICTION { FIT_H; }
			STATICTEXT { JOINENDSCALE; }

			LONG TEXTURETAG_PROJECTION
			{
				FIT_H;
				CYCLE
				{
					TEXTURETAG_PROJECTION_SPHERICAL;
					TEXTURETAG_PROJECTION_CYLINDRICAL;
					TEXTURETAG_PROJECTION_FLAT;
					TEXTURETAG_PROJECTION_CUBIC;
					TEXTURETAG_PROJECTION_FRONTAL;
					TEXTURETAG_PROJECTION_SPATIAL;
					TEXTURETAG_PROJECTION_UVW;
					TEXTURETAG_PROJECTION_SHRINKWRAP;
					TEXTURETAG_PROJECTION_CAMERAMAP;
				}
			}
			STATICTEXT { JOINENDSCALE; }

			LONG TEXTURETAG_PROJECTIONDISPLAY
			{
				FIT_H;
				CYCLE
				{
					TEXTURETAG_PROJECTIONDISPLAY_NONE;
					TEXTURETAG_PROJECTIONDISPLAY_GRID;
					TEXTURETAG_PROJECTIONDISPLAY_SOLID;
				}
			}
			STATICTEXT { JOINENDSCALE; }

			LONG TEXTURETAG_SIDE
			{
				FIT_H;
				CYCLE
				{
					TEXTURETAG_SIDE_FRONTANDBACK;
					TEXTURETAG_SIDE_FRONT;
					TEXTURETAG_SIDE_BACK;
				}
			}
			STATICTEXT { JOINENDSCALE; }

			SEPARATOR { FIT_H; LINE; }
			STATICTEXT { JOINENDSCALE; }

			LINK TEXTURETAG_CAMERA { FIT_H; ACCEPT { Ocamera; 1028083; } } // Oalembicgenerator
			STATICTEXT { JOINENDSCALE; }

			REAL TEXTURETAG_CAMERA_FILMASPECT  { ALIGN_LEFT; MIN 0.01; MAX 10000.0; STEP 0.01; }
			LONG TEXTURETAG_CAMERA_FILMPRESET { ANIM OFF; CYCLE { TEXTURETAG_CAMERA_FILMPRESET_CUSTOM; TEXTURETAG_CAMERA_FILMPRESET_SQUARE; TEXTURETAG_CAMERA_FILMPRESET_STANDARD; TEXTURETAG_CAMERA_FILMPRESET_HDTV; TEXTURETAG_CAMERA_FILMPRESET_35MMSTILL; TEXTURETAG_CAMERA_FILMPRESET_WIDESCREEN; TEXTURETAG_CAMERA_FILMPRESET_35MM; TEXTURETAG_CAMERA_FILMPRESET_PANAVISION; } }

			REAL TEXTURETAG_CAMERA_PIXELASPECT { ALIGN_LEFT; MIN 0.01; MAX 10000.0; STEP 0.01; }
			LONG TEXTURETAG_CAMERA_PIXELPRESET { ANIM OFF; CYCLE { TEXTURETAG_CAMERA_PIXELPRESET_CUSTOM; TEXTURETAG_CAMERA_PIXELPRESET_SQUARE; TEXTURETAG_CAMERA_PIXELPRESET_D1DVNTSC; TEXTURETAG_CAMERA_PIXELPRESET_D1DVPAL; TEXTURETAG_CAMERA_PIXELPRESET_D1DVNTSCWIDESCREEN; TEXTURETAG_CAMERA_PIXELPRESET_HDVANAMORPHIC; TEXTURETAG_CAMERA_PIXELPRESET_D1DVPALWIDESCREEN; TEXTURETAG_CAMERA_PIXELPRESET_ANAMORPHIC; } }

			BUTTON TEXTURETAG_CAMERA_CALCULATE	{ ALIGN_LEFT; }
			STATICTEXT { DUMMY; }

			SEPARATOR { FIT_H; LINE; }
			STATICTEXT { JOINENDSCALE; }

			BOOL TEXTURETAG_MIX { }
			STATICTEXT { JOINENDSCALE; }
			BOOL TEXTURETAG_TILE		 { }
			STATICTEXT { JOINENDSCALE; }

			BOOL TEXTURETAG_SEAMLESS { }
			STATICTEXT { JOINENDSCALE; }
			BOOL TEXTURETAG_UVBUMP { }
			STATICTEXT { JOINENDSCALE; }

			SEPARATOR { LINE; }
			STATICTEXT { JOINENDSCALE; }
		}

		GROUP
		{
			COLUMNS 2;

			REAL TEXTURETAG_OFFSETX { UNIT PERCENT; }
			REAL TEXTURETAG_OFFSETY { UNIT PERCENT; }

			REAL TEXTURETAG_LENGTHX	 { UNIT PERCENT; }
			REAL TEXTURETAG_LENGTHY	 { UNIT PERCENT; }

			REAL TEXTURETAG_TILESX	 { STEP 0.01; }
			REAL TEXTURETAG_TILESY   { STEP 0.01; }

			REAL TEXTURETAG_REPETITIONX { MIN 0; MAX 100000; STEP 1.0; }
			REAL TEXTURETAG_REPETITIONY { MIN 0; MAX 100000; STEP 1.0; }
		}
	}

	GROUP TEXTURETAG_COORDINATEGROUP
	{
		LAYOUTGROUP; COLUMNS 3;
		GROUP { VECTOR TEXTURETAG_POSITION { UNIT METER;  CUSTOMGUI SUBDESCRIPTION; } }
		GROUP { VECTOR TEXTURETAG_SIZE     { UNIT METER; STEP 0.01;   CUSTOMGUI SUBDESCRIPTION; } }
		GROUP { VECTOR TEXTURETAG_ROTATION { UNIT DEGREE; CUSTOMGUI SUBDESCRIPTION; } }
	}

	GROUP Obaselist
	{
		HIDE ID_BASELIST_ICON_SETTINGS_GROUP;
	}
}
