CONTAINER Tvertexcolor
{
	NAME Tvertexcolor;
	INCLUDE Texpression;

	GROUP ID_TAGPROPERTIES
	{
		LONG ID_VERTEXCOLOR_VERTEXCOLORMODE
		{
			CYCLE
			{
				ID_VERTEXCOLOR_VERTEXCOLORMODE_VERTEX;
				ID_VERTEXCOLOR_VERTEXCOLORMODE_POLYGON;
			}
		}
		BOOL ID_VERTEXCOLOR_ALPHAMODE { }
		BOOL ID_VERTEXCOLOR_DRAWPOINTS { }
		BOOL ID_VERTEXCOLOR_USEFIELDS { }
	}

	GROUP ID_VERTEXCOLORFIELDSGROUP
	{
		FIELD HIDE;
		DEFAULT 1;
		BOOL ID_VERTEXCOLOR_USEDEFORMEDPOINTS { ANIM ON; } 
		FIELDLIST ID_VERTEXCOLOR_FIELDS { NEWLINE; ANIM ON; NOVALUE; NODIRECTION; NOROTATION; }
	}
}
