CONTAINER Tvertexmap
{
	NAME Tvertexmap;

	INCLUDE Texpression;

	GROUP Obaselist
	{
		BOOL ID_TAGFIELD_ENABLE {}
		BOOL ID_TAGFIELD_INVERT {}
	}

	GROUP ID_TAGFIELDGROUP
	{
		FIELD HIDE;
		DEFAULT	1;
		BOOL ID_TAGFIELD_DEFORMED { ANIM ON; }
		FIELDLIST ID_TAGFIELDS { ANIM ON; NEWLINE; NOCOLOR; NODIRECTION; NOROTATION; }
	}
}
