CONTAINER VPcomic
{
	NAME VPcomic;
	INCLUDE VPbase;

	GROUP ID_VIDEOPOSTPROPERTIES
	{
		GROUP
		{
			COLUMNS 2;
			BOOL VP_COMICCOLOR				{ }
			BOOL VP_COMICILLUMINATION	{ }
			BOOL VP_COMICOUTLINE			{ }
			BOOL VP_COMICEDGES				{ }
		}
		SEPARATOR { }
		COLOR VP_COMICEDGECOLOR	{ }
		COLOR VP_COMICBACKCOLOR	{ }
		SEPARATOR { }
		GROUP
		{
			COLUMNS 1;
			BOOL VP_COMICQUANTIZE	{ }
			LONG VP_COMICQUANTIZELEVEL { PARENTID VP_COMICQUANTIZE; MIN 1; MAX 100; }
		}
	}
}
