CONTAINER VPdenoiser
{
	INCLUDE VPbase;

	GROUP VP_DENOISER_GROUP
	{
		LONG VP_DENOISER_ALBEDO_TYPE
		{
			ANIM OFF;

			CYCLE
			{
				VP_DENOISER_ALBEDO_TYPE_ALBEDO;
				VP_DENOISER_ALBEDO_TYPE_MATERIAL_COLOR;
			}
		}
		
		BOOL VP_DENOISER_USE_PASSES          { ANIM OFF; DEFAULT 0; }
		BOOL VP_DENOISER_ADDRAWLAYER         { ANIM OFF; DEFAULT 0; }
		
		GROUP VP_DENOISER_INFO_GROUP
		{
			SEPARATOR	{ LINE; }
			STATICTEXT VP_DENOISER_ADDRAWLAYER_INFO {}
			STATICTEXT VP_DENOISER_PASSES_INFO {}
		}
	}
}
