CONTAINER VPpreviewhardware
{
	NAME VPpreviewhardware;
	INCLUDE VPbase;

	GROUP ID_VIDEOPOSTPROPERTIES
	{
		BOOL VP_PREVIEWHARDWARE_ENHANCEDOPENGL { ANIM OFF; }
		SEPARATOR {}
		BOOL VP_PREVIEWHARDWARE_NOISE { ANIM OFF; }
		BOOL VP_PREVIEWHARDWARE_TRANSPARENCY { ANIM OFF; }
		BOOL VP_PREVIEWHARDWARE_SHADOW	{ ANIM OFF; PARENTCOLLAPSE; }
		LONG VP_PREVIEWHARDWARE_SHADOW_MAP_SIZE { MIN 32; MAX 4096; ANIM OFF; PARENTCOLLAPSE VP_PREVIEWHARDWARE_SHADOW; }
		BOOL VP_PREVIEWHARDWARE_ALTERNATIVESHADOWMAPPING  { ANIM OFF; PARENTCOLLAPSE VP_PREVIEWHARDWARE_SHADOW; }
		BOOL VP_PREVIEWHARDWARE_POSTEFFECT { ANIM OFF; }
		BOOL VP_PREVIEWHARDWARE_MAGICBULLETLOOKS { ANIM OFF; }
		BOOL VP_PREVIEWHARDWARE_TESSELLATION { ANIM OFF; }
		BOOL VP_PREVIEWHARDWARE_SSAO { ANIM OFF; }
		BOOL VP_PREVIEWHARDWARE_REFLECTIONS { ANIM OFF; }
		BOOL VP_PREVIEWHARDWARE_DEPTHOFFIELD { ANIM OFF; PARENTCOLLAPSE; }
		BOOL VP_PREVIEWHARDWARE_DEPTHOFFIELD_ANTIALIASED { ANIM OFF; PARENTCOLLAPSE VP_PREVIEWHARDWARE_DEPTHOFFIELD; }
		SEPARATOR {}
		BOOL VP_PREVIEWHARDWARE_IGNORE_HIDDEN_POLYGON_SELECTION  { ANIM OFF; }
		BOOL VP_PREVIEWHARDWARE_32BIT_DEPTH  { ANIM OFF; }
		LONG VP_PREVIEWHARDWARE_ANTIALIASING	{ ANIM OFF; CYCLE { } }	
		
		LONG VP_PREVIEWHARDWARE_SUPERSAMPLING
		{
			ANIM OFF;
			CYCLE
			{
				VP_PREVIEWHARDWARE_SUPERSAMPLING_NONE;
				VP_PREVIEWHARDWARE_SUPERSAMPLING_2;
				VP_PREVIEWHARDWARE_SUPERSAMPLING_3;
				VP_PREVIEWHARDWARE_SUPERSAMPLING_4;
				VP_PREVIEWHARDWARE_SUPERSAMPLING_5;
				VP_PREVIEWHARDWARE_SUPERSAMPLING_8;
				VP_PREVIEWHARDWARE_SUPERSAMPLING_16;
			}
		}
		SEPARATOR {}
		BUTTON VP_PREVIEWHARDWARE_COPY_VP_EFFECTS {}
	}

	GROUP VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP
	{
		BOOL VP_PREVIEWHARDWARE_ONLY_GEOMETRY { ANIM OFF; }

		SEPARATOR { LINE; }
		GROUP
		{
			COLUMNS 2;
			BOOL VP_PREVIEWHARDWARE_DISPLAYFILTER_NULL { ANIM OFF;}
			BOOL VP_PREVIEWHARDWARE_DISPLAYFILTER_FIELD { ANIM OFF;}
			BOOL VP_PREVIEWHARDWARE_DISPLAYFILTER_POLYGON { ANIM OFF;}
			BOOL VP_PREVIEWHARDWARE_DISPLAYFILTER_CAMERA { ANIM OFF;}
			BOOL VP_PREVIEWHARDWARE_DISPLAYFILTER_SPLINE { ANIM OFF;}
			BOOL VP_PREVIEWHARDWARE_DISPLAYFILTER_LIGHT { ANIM OFF;}
			BOOL VP_PREVIEWHARDWARE_DISPLAYFILTER_GENERATOR { ANIM OFF;}
			BOOL VP_PREVIEWHARDWARE_DISPLAYFILTER_JOINT { ANIM OFF;}
			BOOL VP_PREVIEWHARDWARE_DISPLAYFILTER_HYPERNURBS { ANIM OFF;}
			BOOL VP_PREVIEWHARDWARE_DISPLAYFILTER_PARTICLE { ANIM OFF;}
			BOOL VP_PREVIEWHARDWARE_DISPLAYFILTER_DEFORMER { ANIM OFF;}
			BOOL VP_PREVIEWHARDWARE_DISPLAYFILTER_HAIR { ANIM OFF;}
			BOOL VP_PREVIEWHARDWARE_DISPLAYFILTER_SCENE { ANIM OFF;}
			BOOL VP_PREVIEWHARDWARE_DISPLAYFILTER_OTHER { ANIM OFF;}
			SEPARATOR { }
			STATICTEXT { JOINENDSCALE; }
			BOOL VP_PREVIEWHARDWARE_DISPLAYFILTER_GRID { ANIM OFF;}
			BOOL VP_PREVIEWHARDWARE_DISPLAYFILTER_BASEGRID { ANIM OFF;}
			BOOL VP_PREVIEWHARDWARE_DISPLAYFILTER_OBJECTHANDLES { ANIM OFF;}
			BOOL VP_PREVIEWHARDWARE_DISPLAYFILTER_WORLDAXIS { ANIM OFF;}
			BOOL VP_PREVIEWHARDWARE_DISPLAYFILTER_MULTIAXIS { ANIM OFF;}
			BOOL VP_PREVIEWHARDWARE_DISPLAYFILTER_HANDLES { ANIM OFF;}
			BOOL VP_PREVIEWHARDWARE_DISPLAYFILTER_SDS { ANIM OFF;}
			BOOL VP_PREVIEWHARDWARE_DISPLAYFILTER_SDSCAGE { ANIM OFF;}
			BOOL VP_PREVIEWHARDWARE_DISPLAYFILTER_NGONLINES { ANIM OFF;}
			BOOL VP_PREVIEWHARDWARE_DISPLAYFILTER_GUIDELINES { ANIM OFF;}
			BOOL VP_PREVIEWHARDWARE_DATA_SHOWPATH { ANIM OFF;}
			BOOL VP_PREVIEWHARDWARE_DISPLAYFILTER_ONION { ANIM OFF;}
			BOOL VP_PREVIEWHARDWARE_DISPLAYFILTER_HUD { ANIM OFF;}
			BOOL VP_PREVIEWHARDWARE_DISPLAYFILTER_HORIZON { ANIM OFF;}
		}

		SEPARATOR {  }
		GROUP
		{
			COLUMNS 2;
			BUTTON VP_PREVIEWHARDWARE_DISPLAYFILTER_PRESET_LOAD {}
			BUTTON VP_PREVIEWHARDWARE_DISPLAYFILTER_PRESET_SAVE {}
		}
	}
}
