CONTAINER VPscenemotionblur
{
	NAME VPscenemotionblur;
	INCLUDE VPbase;

	GROUP ID_VIDEOPOSTPROPERTIES
	{
		LONG VP_SMBSUB { ANIM OFF; CYCLE { VP_SMBSUB_5; VP_SMBSUB_9; VP_SMBSUB_16; VP_SMBSUB_25; VP_SMBSUB_36; VP_SMBSUB_49; }}
		REAL VP_SMBDITHER { ANIM OFF; UNIT PERCENT; MIN 0.0; MAX 100.0; }
		BOOL VP_SMBAARESTRICTION { ANIM OFF; }
		BOOL VP_SMBCAMERAOFFSET	{ ANIM OFF; }
	}
}
