CONTAINER VPtonemapping
{
	NAME VPtonemapping;
	INCLUDE VPbase;

	GROUP ID_VIDEOPOSTPROPERTIES
	{
		DEFAULT 1;

		GROUP
		{
			COLUMNS 1;

			LONG VP_TONEMAPPING_OPERATOR
			{
				CYCLE
				{
					VP_TONEMAPPING_LINEAR;
					VP_TONEMAPPING_PHOTOLINEAR;
					VP_TONEMAPPING_AUTOLINEAR;
					VP_TONEMAPPING_MAXWHITE;
					VP_TONEMAPPING_REINHARD02;
				}
			}

			REAL VP_TONEMAPPING_SCALE { MIN 0; STEP 0.1; };

			REAL VP_TONEMAPPING_EXPOSURE { MIN 0; STEP 0.001; };
			REAL VP_TONEMAPPING_SENSITIVITY { MIN 0; STEP 10.0; };
			REAL VP_TONEMAPPING_FSTOP { MIN 0; STEP 0.1; };
			REAL VP_TONEMAPPING_GAMMA { MIN 0; STEP 0.1; };

			REAL VP_TONEMAPPING_PRESCALE { MIN 0; STEP 0.1; };
			REAL VP_TONEMAPPING_POSTSCALE { MIN 0; STEP 0.1; };
			REAL VP_TONEMAPPING_BURN { MIN 0; STEP 0.1; };
		}

		SEPARATOR															{  }
		STATICTEXT														{ JOINENDSCALE; }
		
		GROUP
		{
			STATICTEXT VP_TONEMAPPING_INFO { BOLD; }
		}
	}
}


