CONTAINER Xbase
{
	NAME Xbase;
	INCLUDE Obaselist;

	GROUP Obaselist
	{
		SEPARATOR { }
		REAL SHADER_MIPOFFSET { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		REAL SHADER_MIPSCALE { UNIT PERCENT; MIN -100.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
	
		GROUP ID_GPUPROPERTIES
		{
			DEFAULT 1;
			BOOL SHADER_GPUTEXENABLED { ANIM OFF; }
			LONG SHADER_GPUTEXSIZEX { MIN 1; MAX 8192; ANIM OFF; }
			LONG SHADER_GPUTEXSIZEY { MIN 1; MAX 8192; ANIM OFF; }
			LONG SHADER_GPUTEXBITDEPTH 
			{
				ANIM OFF;
			
				CYCLE
				{
					SHADER_GPUTEXBITDEPTH_8;
					SHADER_GPUTEXBITDEPTH_32;
				}
			}
		}
	}

	GROUP ID_SHADERPROPERTIES
	{
		DEFAULT	1;	
	}
}
