CONTAINER Xcolor
{
	NAME Xcolor;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		COLOR	COLORSHADER_COLOR { OPEN; }
		REAL COLORSHADER_BRIGHTNESS { UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
	}
}