CONTAINER Desc_falloffentry
{
	NAME Desc_falloffentry;

	GROUP	ID_FALLOFFENTRY_GROUP
	{
		DEFAULT 1;
		BOOL FALLOFFENTRY_ENABLED { }
		LINK FALLOFFENTRY_LINK { }
		REAL FALLOFFENTRY_STRENGTH { UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }

		SEPARATOR { LINE; }

		LONG FALLOFFENTRY_MODE
		{
			CYCLE
			{
				FALLOFFENTRY_MODE_NORMAL;

				FALLOFFENTRY_MODE_SEPARATOR;

				FALLOFFENTRY_MODE_ADD;
				FALLOFFENTRY_MODE_LIGHTEN;
				FALLOFFENTRY_MODE_MULTIPLY;
				FALLOFFENTRY_MODE_COLORDODGE;
				FALLOFFENTRY_MODE_LINEARDODGE;

				FALLOFFENTRY_MODE_SEPARATOR;

				FALLOFFENTRY_MODE_SUBTRACT;
				FALLOFFENTRY_MODE_DARKEN;
				FALLOFFENTRY_MODE_SCREEN;
				FALLOFFENTRY_MODE_COLORBURN;
				FALLOFFENTRY_MODE_LINEARBURN;

				FALLOFFENTRY_MODE_SEPARATOR;

				FALLOFFENTRY_MODE_OVERLAY;
				FALLOFFENTRY_MODE_SOFTLIGHT;
				FALLOFFENTRY_MODE_HARDLIGHT;
				FALLOFFENTRY_MODE_LINEARLIGHT;
				FALLOFFENTRY_MODE_VIVIDLIGHT;
				FALLOFFENTRY_MODE_PINLIGHT;
				FALLOFFENTRY_MODE_GLOW;

				FALLOFFENTRY_MODE_SEPARATOR;

				FALLOFFENTRY_MODE_AVERAGE;
				FALLOFFENTRY_MODE_DIFFERENCE;
				FALLOFFENTRY_MODE_NEGATION;
				FALLOFFENTRY_MODE_EXCLUSION;
				FALLOFFENTRY_MODE_PHOENIX;
				FALLOFFENTRY_MODE_REFLECT;

				FALLOFFENTRY_MODE_SEPARATOR;

				FALLOFFENTRY_MODE_HARDMIX;
				FALLOFFENTRY_MODE_LEVR;
				FALLOFFENTRY_MODE_COLOR;
				FALLOFFENTRY_MODE_COLOR_INV;
			}
		}

		SEPARATOR { LINE; }

		LONG FALLOFFENTRY_COLORMODE
		{
			CYCLE
			{
				FALLOFFENTRY_COLORMODE_PASS;
				FALLOFFENTRY_COLORMODE_COLOR;
				FALLOFFENTRY_COLORMODE_GRADIENT;
			}
		}

		COLOR		 FALLOFFENTRY_COLOR { }
		GRADIENT FALLOFFENTRY_GRADIENT { }
	}
}
