CONTAINER ETparameter
{
	NAME ETparameter;

	INCLUDE Texpression;

	GROUP	ID_TAGPROPERTIES
	{
		DEFAULT 1;

		REAL ETPARAMETERTAG_STRENGTH { MINSLIDER 0.0; MAXSLIDER 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; }

		BUTTON ETPARAMETERTAG_RESET { }
		LONG	 ETPARAMETERTAG_MODE
		{
			CYCLE
			{
				ETPARAMETERTAG_MODE_ABSOLUTE;
				ETPARAMETERTAG_MODE_RELATIVE;
			}
		}
		SEPARATOR { LINE; }
		BOOL ETPARAMETERTAG_HIDEUNUSED { }
	}

	GROUP ETPARAMETERTAG_FIELDGROUP
	{
		DEFAULT 0;
		LONG ETPARAMETERTAG_FIELDPOINT
		{
			CYCLE
			{
				ETPARAMETERTAG_FIELDPOINT_EXPRESSION;
				ETPARAMETERTAG_FIELDPOINT_DOUBLE;
				ETPARAMETERTAG_FIELDPOINT_NOEXPRESSION;
				ETPARAMETERTAG_FIELDPOINT_FIXPOINT;
			}
		}
		BUTTON		ETPARAMETERTAG_FIXPOSITION { }
		FIELDLIST ETPARAMETERTAG_FIELDS { ANIM ON; NEWLINE; }
	}
}
