CONTAINER Fformula
{
	NAME		Fformula;
	INCLUDE Ofield;

	GROUP ID_FIELDPROPERTIES
	{
		GROUP
		{
			COLUMNS 1;
			STRING FORMULAFIELD_STRING { }
		}
		GROUP FORMULAFIELD_GRP
		{
			COLUMNS 1;
			STATICTEXT FORMULAFIELD_HELP02 { }
			STATICTEXT FORMULAFIELD_HELP03 { }
			STATICTEXT FORMULAFIELD_HELP04 { }
			STATICTEXT FORMULAFIELD_HELP05 { }
			STATICTEXT FORMULAFIELD_HELP06 { }
			STATICTEXT FORMULAFIELD_HELP07 { }
			STATICTEXT FORMULAFIELD_HELP08 { }
			GROUP
			{
				REAL FORMULAFIELD_TIME
				{
					MINSLIDER -100.0;
					MAXSLIDER 100.0;
					STEP 0.1;
					UNIT			PERCENT;
					CUSTOMGUI REALSLIDER;
				}
				REAL FORMULAFIELD_FREQ
				{
					MINSLIDER -10.0;
					MAXSLIDER 10.0;
					STEP 0.001;
					CUSTOMGUI REALSLIDER;
				}
			}
		}
	}

	GROUP FORMULAFIELD_FIELDS_GRP
	{
		FIELD HIDE;

		FIELDLIST FORMULAFIELD_FIELDS
		{
			NEWLINE;
			ANIM ON;
			// Avoid NOVALUE since subfields sample value only, it won't show anyway since it is the only channel.
			NODIRECTION;
			NOCOLOR;
			NOROTATION;
		}
	}

	REARRANGE ID_FIELDCONTROLS;
	REARRANGE FIELD_GROUP_COLOR;
	REARRANGE FIELD_GROUP_DIRECTION;
}
