CONTAINER FLdelay
{
	NAME FLdelay;
	INCLUDE FLbase;

	GROUP FLbase
	{
		LONG FIELDLAYER_DELAY_MODE
		{
			CYCLE
			{
				FIELDLAYER_DELAY_MODE_LINEAR;
				FIELDLAYER_DELAY_MODE_SMOOTH;
				FIELDLAYER_DELAY_MODE_SPRING;
			}
		}

		REAL FIELDLAYER_DELAY_STRENGTH { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
	}

	GROUP FIELDLAYER_DELAY_FIELDS_GRP
	{
		FIELD HIDE;
		FIELDLIST FIELDLAYER_DELAY_FIELDS
		{
			NEWLINE;
			ANIM ON;
			// Avoid NOVALUE since subfields sample value only, it won't show anyway since it is the only channel.
			NODIRECTION;
			NOCOLOR;
			NOROTATION;
		}
	}
}
