CONTAINER FLmograph
{
	NAME		FLmograph;
	INCLUDE FLbase;

	GROUP FLbase
	{
		SEPARATOR { LINE; }
		LINK FIELDLAYERMOGRAPH_LINK { ACCEPT { Obase; } HIDDEN; }
		LONG FIELDLAYERMOGRAPH_MODE
		{
			CYCLE
			{
				FIELDLAYERMOGRAPH_MODE_INDEX;
				FIELDLAYERMOGRAPH_MODE_NEAREST;
				-1;
				FIELDLAYERMOGRAPH_MODE_PROXIMITYMAX;
				FIELDLAYERMOGRAPH_MODE_PROXIMITYDISTMIN;
				FIELDLAYERMOGRAPH_MODE_PROXIMITY;
			}
		}
		REAL FIELDLAYERMOGRAPH_RADIUS { MIN 0.0; UNIT METER; }
		BOOL FIELDLAYERMOGRAPH_DISTANCEFALLOFF { }
		SEPARATOR { LINE; }
		BOOL FIELDLAYERMOGRAPH_CONSTANTUPDATE { }
		LONG FIELDLAYERMOGRAPH_SUBINDEX { MIN 1; MAX 4; }
	}
}
