CONTAINER FLNoise
{
	NAME FLNoise;

	INCLUDE FLbase;

	GROUP	FLBase
	{
		DEFAULT 1;

		REAL FIELDLAYER_RANDOM_SEED { STEP 1.0; MIN 0.0; }

		LONG FIELDLAYER_RANDOM_MODE
		{
			CYCLE
			{
				FIELDLAYER_RANDOM_MODE_BOX;
				FIELDLAYER_RANDOM_MODE_BLISTEREDTURBULENCE;
				FIELDLAYER_RANDOM_MODE_BUYA;
				FIELDLAYER_RANDOM_MODE_CELL;
				FIELDLAYER_RANDOM_MODE_CRANAL;
				FIELDLAYER_RANDOM_MODE_DENTS;
				FIELDLAYER_RANDOM_MODE_DISPLACEDTURBULENCE;
				FIELDLAYER_RANDOM_MODE_ELECTRIC;
				FIELDLAYER_RANDOM_MODE_FBM;
				FIELDLAYER_RANDOM_MODE_GASEOUS;
				FIELDLAYER_RANDOM_MODE_HAMA;
				FIELDLAYER_RANDOM_MODE_LUKA;
				FIELDLAYER_RANDOM_MODE_MODNOISE;
				FIELDLAYER_RANDOM_MODE_NAKI;
				FIELDLAYER_RANDOM_MODE_PERLIN;
				FIELDLAYER_RANDOM_MODE_NUTOUS;
				FIELDLAYER_RANDOM_MODE_OBER;
				FIELDLAYER_RANDOM_MODE_PEZO;
				FIELDLAYER_RANDOM_MODE_POXO;
				FIELDLAYER_RANDOM_MODE_SEMA;
				FIELDLAYER_RANDOM_MODE_STUPL;
				FIELDLAYER_RANDOM_MODE_TURBULENCE;
				FIELDLAYER_RANDOM_MODE_VLNOISE;
				FIELDLAYER_RANDOM_MODE_WAVYTURBULENCE;
				-1;
				FIELDLAYER_RANDOM_MODE_CELLVORONOI;
				FIELDLAYER_RANDOM_MODE_DISPLACEDVORONOI;
				FIELDLAYER_RANDOM_MODE_VORONOI1;
				FIELDLAYER_RANDOM_MODE_VORONOI2;
				FIELDLAYER_RANDOM_MODE_VORONOI3;
				FIELDLAYER_RANDOM_MODE_ZADA;
				FIELDLAYER_RANDOM_MODE_RIDGEDMULTIFRACTAL;
			}
		}

		REAL FIELDLAYER_RANDOM_SCALE { UNIT PERCENT; MIN 0.01; STEP 1.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }

		REAL		 FIELDLAYER_RANDOM_ANIMATIONSPEED { UNIT PERCENT; STEP 1.0; }
		BASETIME FIELDLAYER_RANDOM_ANIMATIONPERIOD { }

		REAL		 FIELDLAYER_RANDOM_OFFSET { UNIT PERCENT; STEP 1.0; }
		BASETIME FIELDLAYER_RANDOM_OFFSETPERIOD { }

		SEPARATOR { LINE; }

		REAL FIELDLAYER_RANDOM_COLORSHIFT { UNIT PERCENT; MIN 0.0; STEP 1.0; }
	}
}
