CONTAINER FLparticleobject
{
	NAME		FLparticleobject;
	INCLUDE FLbase;

	GROUP FLbase
	{
		LINK FIELDLAYER_PARTICLE_OBJECT { ACCEPT { Opolygon; Obase; } HIDDEN; }

		SEPARATOR { LINE; }

		REAL FIELDLAYER_PARTICLE_DISTANCE { MIN 0.0; MAXSLIDER 100.0; UNIT METER; CUSTOMGUI REALSLIDER; }
		BOOL FIELDLAYER_PARTICLE_CLIP { NAME FIELDLAYER_PARTICLE_CLIP; }
		
		SEPARATOR { LINE; }
		
		LONG FIELDLAYER_PARTICLE_COLOR_ALPHA 
		{
			CYCLE
			{ 
				FIELDLAYER_PARTICLE_COLOR_ALPHA_NONE;
				FIELDLAYER_PARTICLE_COLOR_ALPHA_VALUE; 
			}
		}
	}
}
