CONTAINER FLpolygonobject
{
	NAME		FLpolygonobject;
	INCLUDE FLbase;

	GROUP FLbase
	{
		LINK FIELDLAYER_POLYGON_OBJECT { ACCEPT { Opolygon; Obase; } HIDDEN; }

		SEPARATOR { LINE; }

		LONG FIELDLAYER_POLYGON_MODE
		{
			CYCLE
			{
				FIELDLAYER_POLYGON_MODE_POINTS;
				FIELDLAYER_POLYGON_MODE_SURFACE;
				FIELDLAYER_POLYGON_MODE_VOLUME;
			}
		}

		SEPARATOR { LINE; }

		REAL FIELDLAYER_POLYGON_DISTANCE { MIN 0.0; MAXSLIDER 100.0; UNIT METER; CUSTOMGUI REALSLIDER; }

		LONG FIELDLAYER_POLYGON_VOLUME_CLIP
		{
			CYCLE
			{
				FIELDLAYER_POLYGON_VOLUME_CLIP_NONE;
				FIELDLAYER_POLYGON_VOLUME_CLIP_INSIDE;
				FIELDLAYER_POLYGON_VOLUME_CLIP_OUTSIDE;
				FIELDLAYER_POLYGON_VOLUME_CLIP_INSIDE_INVERT;
			}
		}
		BOOL FIELDLAYER_POLYGON_CLIP { NAME FIELDLAYER_POLYGON_CLIP; }
	}
}
