CONTAINER FLproximity
{
	NAME FLproximity;
	INCLUDE FLbase;

	GROUP FLbase
	{
		GROUP
		{
			COLUMNS 2;
			BUTTON FIELDLAYER_PROXIMITY_FORCE_SAVE{}
			BUTTON FIELDLAYER_PROXIMITY_FORCE_CLEAR{}
		}

		SEPARATOR { LINE; }

		LONG FIELDLAYER_PROXIMITY_MODE
		{
			CYCLE
			{
				FIELDLAYER_PROXIMITY_MODE_NONE;
				FIELDLAYER_PROXIMITY_MODE_MAX;
				FIELDLAYER_PROXIMITY_MODE_MIN;
				FIELDLAYER_PROXIMITY_MODE_AVG;
				FIELDLAYER_PROXIMITY_MODE_GROW;
			}
		}

		GROUP
		{
			COLUMNS 2;
			BOOL FIELDLAYER_PROXIMITY_DYNAMIC_UPDATE {}
			BOOL FIELDLAYER_PROXIMITY_SELF_AGGREGATE {}
			BOOL FIELDLAYER_PROXIMITY_USE_INPUT_CRC { HIDDEN; }
		}

		REAL FIELDLAYER_PROXIMITY_RADIUS
		{
			MIN 0.0;
			MAXSLIDER 500.0;
			UNIT METER;
		}

		REAL FIELDLAYER_PROXIMITY_EFFECT_RATIO
		{
			MIN 0.0;
			MAXSLIDER 200.0;
			UNIT PERCENT;
		}
	}

	GROUP FIELDLAYER_PROXIMITY_FIELDS_GRP
	{
		FIELD HIDE;
		FIELDLIST FIELDLAYER_PROXIMITY_FIELDS
		{
			NEWLINE;
			ANIM ON;
			// Avoid NOVALUE since subfields sample value only, it won't show anyway since it is the only channel.
			NODIRECTION;
			NOCOLOR;
			NOROTATION;
			FIELD HIDE;
		}
	}
}
