CONTAINER FLspline
{
	NAME		FLspline;
	INCLUDE FLbase;

	GROUP FLbase
	{
		LINK FIELDLAYER_SPLINE_OBJECT { ACCEPT { Ospline; Obase; } HIDDEN; }

		LONG FIELDLAYER_SPLINE_SHAPE
		{
			CYCLE
			{
				FIELDLAYER_SPLINE_SHAPE_CURVE;
				FIELDLAYER_SPLINE_SHAPE_MASK;
			}
		}

		LONG FIELDLAYER_SPLINE_DISTANCEMODE
		{
			CYCLE
			{
				FIELDLAYER_SPLINE_DISTANCEMODE_ALONG;
				FIELDLAYER_SPLINE_DISTANCEMODE_RADIUS;
				FIELDLAYER_SPLINE_DISTANCEMODE_BOTH;
			}
		}

		GROUP FIELDLAYER_SPLINE_GROUP_RADIUS
		{
			FIT_H;
			DEFAULT 1;

			REAL FIELDLAYER_SPLINE_DISTANCE { MIN 0.0; MAXSLIDER 100.0; UNIT METER; CUSTOMGUI REALSLIDER; }
			BOOL FIELDLAYER_SPLINE_CLIP {}
			SPLINE FIELDLAYER_SPLINE_RADIUSCURVE { }
		}

		GROUP FIELDLAYER_SPLINE_GROUP_ALONG
		{
			FIT_H;
			DEFAULT 1;

			LONG FIELDLAYER_SPLINE_ALONGMODE
			{
				CYCLE
				{
					FIELDLAYER_SPLINE_ALONGMODE_WHOLE;
					FIELDLAYER_SPLINE_ALONGMODE_PERSEGMENT;
				}
			}

			REAL FIELDLAYER_SPLINE_RANGE_START { MIN 0.0; MAX 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
			REAL FIELDLAYER_SPLINE_RANGE_END { MIN 0.0; MAX 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
			REAL FIELDLAYER_SPLINE_OFFSET { MINSLIDER -100.0; MAXSLIDER 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; }

			SPLINE FIELDLAYER_SPLINE_ALONGCURVE { }
			BOOL FIELDLAYER_SPLINE_ALONGCURVECYCLE { }
		}

		GROUP FIELDLAYER_SPLINE_GROUP_MASK
		{
			FIT_H;
			DEFAULT 1;

			LONG FIELDLAYER_SPLINE_PROJECTION
			{
				CYCLE
				{
					FIELDLAYER_SPLINE_PROJECTION_X;
					FIELDLAYER_SPLINE_PROJECTION_Y;
					FIELDLAYER_SPLINE_PROJECTION_Z;
				}
			}

			LONG FIELDLAYER_SPLINE_MASKFALLOFF
			{
				CYCLE
				{
					FIELDLAYER_SPLINE_MASKFALLOFF_INSIDE;
					FIELDLAYER_SPLINE_MASKFALLOFF_OUTSIDE;
				}
			}

			SEPARATOR { LINE; }

			REAL FIELDLAYER_SPLINE_MASK_DISTANCE { MIN 0.0; MAXSLIDER 100.0; UNIT METER; CUSTOMGUI REALSLIDER; }
			BOOL FIELDLAYER_SPLINE_MASK_CLIP {}
		}
	}
}
