CONTAINER FLtime
{
	NAME		FLtime;
	INCLUDE FLbase;

	GROUP FLbase
	{
		LONG TIMEFIELDLAYER_SHAPE
		{
			CYCLE
			{
				TIMEFIELDLAYER_SHAPE_NONE;
				TIMEFIELDLAYER_SHAPE_SINE;
				TIMEFIELDLAYER_SHAPE_TRIANGLE;
				TIMEFIELDLAYER_SHAPE_SAWTOOTH;
				TIMEFIELDLAYER_SHAPE_SQUARE;
			}
		}

		BASETIME TIMEFIELDLAYER_SPEED { }
		BASETIME TIMEFIELDLAYER_OFFSET { }
	}

	GROUP TIMEFIELDLAYER_FIELDS_GRP
	{
		FIELD HIDE;
		FIELDLIST TIMEFIELDLAYER_FIELDS
		{
			NEWLINE;
			ANIM ON;
			// Avoid NOVALUE since subfields sample value only, it won't show anyway since it is the only channel.
			NODIRECTION;
			NOCOLOR;
			NOROTATION;
		}
	}
}
