CONTAINER FLvolumeobject
{
	NAME		FLvolumeobject;
	INCLUDE FLbase;
		
	GROUP FLbase
	{
		LINK FIELDLAYER_VOLUME_OBJECT { ACCEPT { Ovolume; Obase; } HIDDEN; }

		SEPARATOR { LINE; }

		LONG FIELDLAYER_VOLUME_SAMPLEMODE
		{
			CYCLE
			{
				FIELDLAYER_VOLUME_SAMPLEMODE_NEAREST;
				FIELDLAYER_VOLUME_SAMPLEMODE_LINEAR;
				FIELDLAYER_VOLUME_SAMPLEMODE_QUADRATIC;
			}
		}
		BOOL FIELDLAYER_VOLUME_CLIP { NAME FIELDLAYER_VOLUME_CLIP; }
	}
}
