CONTAINER FLweight
{
	NAME		FLweight;
	INCLUDE FLbase;

	GROUP FLbase
	{
		LINK FIELDLAYER_WEIGHT_LINK { ACCEPT { Tbase; } HIDDEN; }
		LONG FIELDLAYER_WEIGHT_MODE
		{
			CYCLE
			{
				FIELDLAYER_WEIGHT_MODE_INDEX;
				FIELDLAYER_WEIGHT_MODE_NEAREST;
				-1;
				FIELDLAYER_WEIGHT_MODE_MAX;
				FIELDLAYER_WEIGHT_MODE_DISTMIN;
				FIELDLAYER_WEIGHT_MODE_AVG;
			}
		}
		REAL FIELDLAYER_WEIGHT_RADIUS { MIN 0.0; UNIT METER; }
		BOOL FIELDLAYER_WEIGHT_DISTANCEFALLOFF { }
		SEPARATOR { LINE; }
		BOOL FIELDLAYER_WEIGHT_USEDEFORMED { }
		BOOL FIELDLAYER_WEIGHT_CONSTANTUPDATE { }
	}

}
