CONTAINER Fradial
{
	NAME		Fradial;
	INCLUDE Ofield;

	GROUP ID_FIELDPROPERTIES
	{
		REAL FIELD_RADIAL_STARTANGLE		{ UNIT DEGREE; MINSLIDER 0.0; MAXSLIDER 360.0; CUSTOMGUI REALSLIDER; }
		REAL FIELD_RADIAL_STARTBLEND		{ UNIT DEGREE; MIN 0.0; MAX 360.0; CUSTOMGUI REALSLIDER; }

		SEPARATOR { LINE; }

		REAL FIELD_RADIAL_ENDANGLE			{ UNIT DEGREE; MINSLIDER 0.0; MAXSLIDER 360.0; CUSTOMGUI REALSLIDER; }
		REAL FIELD_RADIAL_ENDBLEND			{ UNIT DEGREE; MIN 0.0; MAX 360.0; CUSTOMGUI REALSLIDER; }

		SEPARATOR { LINE; }

		REAL FIELD_RADIAL_ITERATIONS		{ MIN 1.0; STEP 0.01; }
		REAL FIELD_RADIAL_OFFSET{UNIT DEGREE; MINSLIDER 0.0; MAXSLIDER 360.0; CUSTOMGUI REALSLIDER; }

		LONG FIELD_RADIAL_AXIS
		{
			CYCLE
			{
				FIELD_RADIAL_AXIS_X;
				FIELD_RADIAL_AXIS_Y;
				FIELD_RADIAL_AXIS_Z;
			}
		}
		BOOL FIELD_RADIAL_CLIP {}
	}

	GROUP FIELD_RADIAL_GROUP_OFFSET
	{
		FIELD HIDE;
		DEFAULT 0;
		FIELDLIST FIELD_RADIAL_OFFSETFIELD
		{
			NEWLINE;
			ANIM ON;
			// Avoid NOVALUE since subfields sample value only, it won't show anyway since it is the only channel.
			NODIRECTION;
			NOCOLOR;
			NOROTATION;
		}
	}

	GROUP ID_FIELDCONTROLS
	{
	}

	REARRANGE ID_FIELDCONTROLS;
	REARRANGE FIELD_GROUP_COLOR;
	REARRANGE FIELD_GROUP_DIRECTION;
}
