CONTAINER Frandom
{
	NAME Frandom;
	INCLUDE Ofield;

	GROUP ID_FIELDPROPERTIES
	{
		LONG FIELD_RANDOM_MODE
		{
			CYCLE
			{
				FIELD_RANDOM_MODE_RANDOM;
				FIELD_RANDOM_MODE_SORTED;
				FIELD_RANDOM_MODE_NOISE;
			}
		}

		REAL FIELD_RANDOM_SEED { STEP 1.0; MIN 0.0; }

		GROUP FIELD_RANDOM_NOISE_GROUP
		{
			LONG FIELD_RANDOM_NOISE_MODE
			{
				CYCLE
				{
					FIELD_RANDOM_NOISE_MODE_BOX;
					FIELD_RANDOM_NOISE_MODE_BLISTEREDTURBULENCE;
					FIELD_RANDOM_NOISE_MODE_BUYA;
					FIELD_RANDOM_NOISE_MODE_CELL;
					FIELD_RANDOM_NOISE_MODE_CRANAL;
					FIELD_RANDOM_NOISE_MODE_DENTS;
					FIELD_RANDOM_NOISE_MODE_DISPLACEDTURBULENCE;
					FIELD_RANDOM_NOISE_MODE_ELECTRIC;
					FIELD_RANDOM_NOISE_MODE_FBM;
					FIELD_RANDOM_NOISE_MODE_GASEOUS;
					FIELD_RANDOM_NOISE_MODE_HAMA;
					FIELD_RANDOM_NOISE_MODE_LUKA;
					FIELD_RANDOM_NOISE_MODE_MODNOISE;
					FIELD_RANDOM_NOISE_MODE_NAKI;
					FIELD_RANDOM_NOISE_MODE_PERLIN;
					FIELD_RANDOM_NOISE_MODE_NUTOUS;
					FIELD_RANDOM_NOISE_MODE_OBER;
					FIELD_RANDOM_NOISE_MODE_PEZO;
					FIELD_RANDOM_NOISE_MODE_POXO;
					FIELD_RANDOM_NOISE_MODE_SEMA;
					FIELD_RANDOM_NOISE_MODE_STUPL;
					FIELD_RANDOM_NOISE_MODE_TURBULENCE;
					FIELD_RANDOM_NOISE_MODE_VLNOISE;
					FIELD_RANDOM_NOISE_MODE_WAVYTURBULENCE;
					-1;
					FIELD_RANDOM_NOISE_MODE_CELLVORONOI;
					FIELD_RANDOM_NOISE_MODE_DISPLACEDVORONOI;
					FIELD_RANDOM_NOISE_MODE_VORONOI1;
					FIELD_RANDOM_NOISE_MODE_VORONOI2;
					FIELD_RANDOM_NOISE_MODE_VORONOI3;
					FIELD_RANDOM_NOISE_MODE_ZADA;
					FIELD_RANDOM_NOISE_MODE_RIDGEDMULTIFRACTAL;
				}
			}

			LONG FIELD_RANDOM_SPACE
			{
				CYCLE
				{
					FIELD_RANDOM_SPACE_GLOBAL;
					FIELD_RANDOM_SPACE_OBJECT;
					FIELD_RANDOM_SPACE_NONE;
				}
			}

			REAL FIELD_RANDOM_SCALE { UNIT PERCENT; MIN 0.01; STEP 1.0; }
			VECTOR FIELD_RANDOM_SCALE_LOCAL { UNIT PERCENT; MIN 0.01; STEP 1.0; }
			REAL FIELD_RANDOM_ANIMATIONSPEED { UNIT PERCENT; STEP 1.0; }
			BASETIME FIELD_RANDOM_ANIMATIONPERIOD { MIN 0; }

			SEPARATOR { LINE; }

			BOOL FIELD_RANDOM_INDEXED { }
			LONG FIELD_RANDOM_INDEXSEED { MIN 1; }
		}

		SEPARATOR { LINE; }

		REAL FIELD_RANDOM_COLORSHIFT { UNIT PERCENT; MIN 0.0; STEP 1.0; }
		LONG FIELD_RANDOM_COLORALPHA
		{
			CYCLE
			{
				FIELD_RANDOM_COLORALPHA_NONE;
				FIELD_RANDOM_COLORALPHA_STRENGTH;
			}
		}
	}

	GROUP FIELD_RANDOM_VIEWPLANES_GROUP
	{
		BOOL FIELD_RANDOM_VIEWPLANES { PARENTCOLLAPSE; }
		GROUP
		{
			COLUMNS 3;
			BOOL FIELD_RANDOM_VIEWPLANES_X { PARENTCOLLAPSE FIELD_RANDOM_VIEWPLANES; }
			BOOL FIELD_RANDOM_VIEWPLANES_Y { PARENTCOLLAPSE FIELD_RANDOM_VIEWPLANES; }
			BOOL FIELD_RANDOM_VIEWPLANES_Z { PARENTCOLLAPSE FIELD_RANDOM_VIEWPLANES; }
		}
		LONG FIELD_RANDOM_VIEWPLANES_DENSITY { MIN 0; MAX 500; STEP 1; }

		VECTOR FIELD_RANDOM_VIEWPLANES_SIZES { UNIT METER; STEP 0.1; CUSTOMGUI SUBDESCRIPTION; }
	}
}