CONTAINER Fshader
{
	NAME Fshader;

	INCLUDE Ofield;
	INCLUDE Oshader_panel;

	GROUP ID_FIELDPROPERTIES
	{
		REARRANGE ID_MG_SHADER_GROUPSHADER_NONAME;
	}

	REARRANGE ID_FIELDCONTROLS;
	REARRANGE FIELD_GROUP_COLOR;
	REARRANGE FIELD_GROUP_DIRECTION;

	HIDE ID_MG_SHADER_GROUPSHADER;

	GROUP ID_FIELDPROPERTIES
	{
		GROUP FIELD_SHADER_REFRESH_GROUP
		{
			DEFAULT 1;
			BOOL FIELD_SHADER_FRAME_DEPENDENT {}
		}
	}
}
