CONTAINER MGhoneycombarray
{
	NAME		MGhoneycombarray;
	INCLUDE Obase;
	INCLUDE otransform_panel;

	GROUP		ID_OBJECTPROPERTIES
	{
		GROUP
		{
			COLUMNS 1;

			GROUP
			{
				COLUMNS 2;
				FIT_H;

				LONG MG_HONEYCOMB_ORIENTATION
				{
					CYCLE
					{
						MG_HONEYCOMB_ORIENTATION_XY;
						MG_HONEYCOMB_ORIENTATION_ZY;
						MG_HONEYCOMB_ORIENTATION_XZ;
					}
				}

				LONG MG_HONEYCOMB_DIRECTION
				{
					CYCLE
					{
						MG_HONEYCOMB_DIRECTION_WIDTH;
						MG_HONEYCOMB_DIRECTION_HEIGHT;
					}
				}
			}

			REAL MG_HONEYCOMB_OFFSET { PARENTCOLLAPSE; MIN 0.0; MAX 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
			REAL MG_HONEYCOMB_OFFSET_VARIATION { PARENTCOLLAPSE MG_HONEYCOMB_OFFSET; MIN 0.0; MAX 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
			REAL MG_HONEYCOMB_VARIATION { PARENTCOLLAPSE MG_HONEYCOMB_OFFSET; MIN 0.0; MAX 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
			LONG MG_HONEYCOMB_SEED { PARENTCOLLAPSE MG_HONEYCOMB_OFFSET; MIN 0; }

			SEPARATOR { LINE; }

			LONG MG_HONEYCOMB_COUNT_X { MIN 1;	}
			LONG MG_HONEYCOMB_COUNT_Y { MIN 1;	}

			SEPARATOR { LINE; }

			LONG MG_HONEYCOMB_MODE
			{
				CYCLE
				{
					MG_HONEYCOMB_MODE_PERSTEP;
					MG_HONEYCOMB_MODE_ENDPOINT;
				}
			}

			REAL MG_HONEYCOMB_SIZE_X { UNIT METER; MIN 0.0; }
			REAL MG_HONEYCOMB_SIZE_Y { UNIT METER; MIN 0.0; }

			SEPARATOR { LINE; }

			LONG MG_HONEYCOMB_FORM
			{
				CYCLE
				{
					MG_HONEYCOMB_FORM_CIRCLE;
					MG_HONEYCOMB_FORM_SQUARE;
					MG_HONEYCOMB_FORM_SPLINE;
				}
			}

			LINK MG_HONEYCOMB_FORMOBJECT_LINK 
			{
				ACCEPT
				{
					Obase;
				}
			}
		}
	}
}
