CONTAINER Oereeffector
{
	NAME		Oereeffector;

	INCLUDE Obase;

	GROUP		MGREEFFECTOR_GROUPEFFECTOR
	{
		DEFAULT 1;
		FIT_H;
		SCALE_V;

		REAL	MGREEFFECTOR_STRENGTH
		{
			MINSLIDER 0.0;
			MAXSLIDER 100.0;
			UNIT			PERCENT;
			CUSTOMGUI REALSLIDER;
		}
		
		STRING MGREEFFECTOR_SELECTION
		{
		}

		SEPARATOR
		{
			LINE;
		}

		IN_EXCLUDE	MGREEFFECTOR_EFFECTORS
		{
			NUM_FLAGS 1;
			INIT_STATE 1;
			OPEN;

			IMAGE_01_ON 300000131;
			IMAGE_01_OFF 300000130;

			ACCEPT
			{
				Obaseeffector;
			}
		}

		GROUP MGREEFFECTOR_GROUPEFFECTORSLIDERS
		{
			SCALE_V;
		}
	}

	GROUP		MGREEFFECTOR_GROUPPARAMETER
	{
		GROUP MGREEFFECTOR_GROUPTRANSFORM
		{
			DEFAULT 1;

			GROUP
			{
				COLUMNS 2;

				BOOL MGREEFFECTOR_POSITION		{ PARENTCOLLAPSE; }
				REAL MGREEFFECTOR_POSITION_STRENGTH {  UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; SCALE_H; }

				BOOL MGREEFFECTOR_POSITION_X		{ PARENTCOLLAPSE MGREEFFECTOR_POSITION; }
				REAL MGREEFFECTOR_POSITION_STRENGTH_X {  UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; SCALE_H; PARENTCOLLAPSE MGREEFFECTOR_POSITION; }
				BOOL MGREEFFECTOR_POSITION_Y		{ PARENTCOLLAPSE MGREEFFECTOR_POSITION; }
				REAL MGREEFFECTOR_POSITION_STRENGTH_Y {  UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; SCALE_H; PARENTCOLLAPSE MGREEFFECTOR_POSITION; }
				BOOL MGREEFFECTOR_POSITION_Z		{ PARENTCOLLAPSE MGREEFFECTOR_POSITION; }
				REAL MGREEFFECTOR_POSITION_STRENGTH_Z {  UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; SCALE_H; PARENTCOLLAPSE MGREEFFECTOR_POSITION; }

				BOOL MGREEFFECTOR_SCALE				{ PARENTCOLLAPSE; }
				REAL MGREEFFECTOR_SCALE_STRENGTH	{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; SCALE_H; }

				BOOL MGREEFFECTOR_SCALE_X				{ PARENTCOLLAPSE MGREEFFECTOR_SCALE; }
				REAL MGREEFFECTOR_SCALE_STRENGTH_X	{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; SCALE_H; PARENTCOLLAPSE MGREEFFECTOR_SCALE; }
				BOOL MGREEFFECTOR_SCALE_Y				{ PARENTCOLLAPSE MGREEFFECTOR_SCALE; }
				REAL MGREEFFECTOR_SCALE_STRENGTH_Y	{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; SCALE_H; PARENTCOLLAPSE MGREEFFECTOR_SCALE; }
				BOOL MGREEFFECTOR_SCALE_Z			{ PARENTCOLLAPSE MGREEFFECTOR_SCALE; }
				REAL MGREEFFECTOR_SCALE_STRENGTH_Z	{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; SCALE_H; PARENTCOLLAPSE MGREEFFECTOR_SCALE; }


				BOOL MGREEFFECTOR_ROTATION		{ PARENTCOLLAPSE; }
				REAL MGREEFFECTOR_ROTATION_STRENGTH	{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; SCALE_H; }

				BOOL MGREEFFECTOR_ROTATION_H		{ PARENTCOLLAPSE MGREEFFECTOR_ROTATION; }
				REAL MGREEFFECTOR_ROTATION_STRENGTH_H	{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; SCALE_H; PARENTCOLLAPSE MGREEFFECTOR_ROTATION; }
				BOOL MGREEFFECTOR_ROTATION_P		{ PARENTCOLLAPSE MGREEFFECTOR_ROTATION; }
				REAL MGREEFFECTOR_ROTATION_STRENGTH_P	{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; SCALE_H; PARENTCOLLAPSE MGREEFFECTOR_ROTATION; }
				BOOL MGREEFFECTOR_ROTATION_B		{ PARENTCOLLAPSE MGREEFFECTOR_ROTATION; }
				REAL MGREEFFECTOR_ROTATION_STRENGTH_B	{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; SCALE_H; PARENTCOLLAPSE MGREEFFECTOR_ROTATION; }

				FIT_H;
			}
		}

		GROUP MGREEFFECTOR_GROUPCOLOR
		{
			DEFAULT 1;

			GROUP
			{
				COLUMNS 2;
				BOOL MGREEFFECTOR_COLOR				{ PARENTCOLLAPSE; }
				REAL MGREEFFECTOR_COLOR_STRENGTH	{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; SCALE_H; }

				BOOL MGREEFFECTOR_COLOR_R				{ PARENTCOLLAPSE MGREEFFECTOR_COLOR; }
				REAL MGREEFFECTOR_COLOR_STRENGTH_R	{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; SCALE_H; PARENTCOLLAPSE MGREEFFECTOR_COLOR; }
				BOOL MGREEFFECTOR_COLOR_G				{ PARENTCOLLAPSE MGREEFFECTOR_COLOR; }
				REAL MGREEFFECTOR_COLOR_STRENGTH_G	{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; SCALE_H; PARENTCOLLAPSE MGREEFFECTOR_COLOR; }
				BOOL MGREEFFECTOR_COLOR_B				{ PARENTCOLLAPSE MGREEFFECTOR_COLOR; }
				REAL MGREEFFECTOR_COLOR_STRENGTH_B	{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; SCALE_H; PARENTCOLLAPSE MGREEFFECTOR_COLOR; }

				FIT_H;
			}
		}

		GROUP MGREEFFECTOR_GROUPOTHER
		{
			DEFAULT 1;

			GROUP
			{
				COLUMNS 2;
				BOOL MGREEFFECTOR_WEIGHT			{ }
				REAL MGREEFFECTOR_WEIGHT_STRENGTH	{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; SCALE_H; }

				BOOL MGREEFFECTOR_CLONE				{ }
				REAL MGREEFFECTOR_CLONE_STRENGTH	{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; SCALE_H; }

				BOOL MGREEFFECTOR_TIME				{ }
				REAL MGREEFFECTOR_TIME_STRENGTH	{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; SCALE_H; }

				BOOL MGREEFFECTOR_U						{ }
				REAL MGREEFFECTOR_U_STRENGTH	{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; SCALE_H; }

				BOOL MGREEFFECTOR_V						{ }
				REAL MGREEFFECTOR_V_STRENGTH	{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; SCALE_H; }

				BOOL MGREEFFECTOR_VISIBILITY	{ }
				REAL MGREEFFECTOR_VISIBILITY_STRENGTH	{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; SCALE_H; }

				FIT_H;
			}
		}
	}

	INCLUDE Oedeformer_panel;
}
