CONTAINER Oesounddepreciated
{
	NAME		Oesounddepreciated;

	INCLUDE Obaseeffector;

	GROUP		ID_MG_BASEEFFECTOR_GROUPEFFECTOR
	{
		FILENAME	MGSOUNDEFFECTOR_FILE { ANIM OFF; }
		SEPARATOR
		{
			LINE;
		}
		BASETIME	MGSOUNDEFFECTOR_START {}
		GROUP
		{
			COLUMNS 2;

			LONG	MGSOUNDEFFECTOR_MGMODE
			{
				CYCLE
				{
					MGSOUNDEFFECTOR_MGMODE_ALL;
					MGSOUNDEFFECTOR_MGMODE_STEP;
				}
			}
			REAL	MGSOUNDEFFECTOR_FALLOFF
			{
				UNIT	PERCENT;
				MIN 0.0;
				MAX 100.0;
				CUSTOMGUI REALSLIDER;
				FIT_H;
			}
		}
		SEPARATOR
		{
			LINE;
		}
		GROUP
		{
			COLUMNS 2;

			LONG	MGSOUNDEFFECTOR_MODE
			{
				CYCLE
				{
					MGSOUNDEFFECTOR_MODE_PEAK;
					MGSOUNDEFFECTOR_MODE_AVE;
					MGSOUNDEFFECTOR_MODE_COMP;
				}
			}
			BOOL	MGSOUNDEFFECTOR_CLAMP {}
		}
		REAL	MGSOUNDEFFECTOR_LOWERLIMIT
		{
			UNIT	PERCENT;
			MIN 0.0;
			MAX 100.0;
			CUSTOMGUI REALSLIDER;
		}
		REAL	MGSOUNDEFFECTOR_MULTIPLIER
		{
			UNIT	PERCENT;
			MIN 0.0;
			MAX 100.0;
			CUSTOMGUI REALSLIDER;
		}
		BITMAPBUTTON	MGSOUNDEFFECTOR_GRAPH
		{
			FIT_H;
		}
		SPLINE	MGSOUNDEFFECTOR_FILTERSHAPE
		{
			FIT_H;
		}
		GRADIENT	MGSOUNDEFFECTOR_COLORGRADIENT
		{
			COLOR;
			ICC_BASEDOCUMENT;
		}
		GROUP
		{
			LAYOUTGROUP;
			COLUMNS 2;
			GROUP
			{
				REAL	MGSOUNDEFFECTOR_FREQ
				{
					MIN 0.01;
					MAXSLIDER 10000;
				}
				REAL	MGSOUNDEFFECTOR_BANDWIDTH
				{
					MIN 0.01;
					MAXSLIDER 10000;
				}
			}
			GROUP
			{
				BOOL	MGSOUNDEFFECTOR_LCHANNEL {}
				BOOL	MGSOUNDEFFECTOR_RCHANNEL {}
			}
		}
		BOOL	MGSOUNDEFFECTOR_FILTER {}
		SEPARATOR
		{
			LINE;
		}
		GROUP
		{
			COLUMNS 2;
			BUTTON	MGSOUNDEFFECTOR_PLAY {}
			BOOL	MGSOUNDEFFECTOR_SCRUB {}
		}
	}
}
