CONTAINER Oetarget
{
	NAME		Oetarget;

	INCLUDE Obase;

	GROUP		MGTARGETEFFECTOR_GROUPEFFECTOR
	{
		DEFAULT 1;

		REAL	MGTARGETEFFECTOR_STRENGTH
		{
			MINSLIDER 0.0;
			MAXSLIDER 100.0;
			UNIT			PERCENT;
			CUSTOMGUI REALSLIDER;
		}
		STRING MGTARGETEFFECTOR_SELECTION
		{
		}
		SEPARATOR
		{
			LINE;
		}
		LONG	MGTARGETEFFECTOR_MODE
		{
			CYCLE
			{
				MGTARGETEFFECTOR_MODE_OBJECT;
				MGTARGETEFFECTOR_MODE_CAMERA;
				MGTARGETEFFECTOR_MODE_NEXT;
				MGTARGETEFFECTOR_MODE_PREV;
				MGTARGETEFFECTOR_MODE_FIELDS;
			}
			FIT_H;
		}

		BOOL MGTARGETEFFECTOR_SETWEIGHT {}

		LINK	MGTARGETEFFECTOR_OBJECT
		{
			ACCEPT
			{
				Obase;
			}
		}
		SEPARATOR
		{
			LINE;
		}
		GROUP
		{
			COLUMNS 2;
			BOOL	MGTARGETEFFECTOR_PITCH
			{
			}
			BOOL	MGTARGETEFFECTOR_REVERSEVECTOR
			{
			}
		}
		GROUP MGTARGETEFFECTOR_GROUPUP
		{
			LONG	MGTARGETEFFECTOR_PRIMITIVEAXIS
			{
				CYCLE
				{
					MGTARGETEFFECTOR_PRIMITIVEAXIS_NONE;
					MGTARGETEFFECTOR_PRIMITIVEAXIS_LINK;
					MGTARGETEFFECTOR_PRIMITIVEAXIS_XP;
					MGTARGETEFFECTOR_PRIMITIVEAXIS_XN;
					MGTARGETEFFECTOR_PRIMITIVEAXIS_YP;
					MGTARGETEFFECTOR_PRIMITIVEAXIS_YN;
					MGTARGETEFFECTOR_PRIMITIVEAXIS_ZP;
					MGTARGETEFFECTOR_PRIMITIVEAXIS_ZN;
				}
			}
			LINK	MGTARGETEFFECTOR_UP
			{
				ACCEPT
				{
					Obase;
				}
			}
		}
		SEPARATOR
		{
			LINE;
		}
		BOOL	MGTARGETEFFECTOR_REACT
		{
		}
		REAL	MGTARGETEFFECTOR_RANGE
		{
			MIN 0.0;
			MINSLIDER 0.0;
			MAXSLIDER 100.0;
			UNIT			METER;
			CUSTOMGUI REALSLIDER;
		}
		REAL	ETARG_RANGE_STRENGTH
		{
			MINSLIDER 0.0;
			MAXSLIDER 100.0;
			UNIT			PERCENT;
			CUSTOMGUI REALSLIDER;
		}
	}
	INCLUDE Oedeformer_panel;
	
}
