CONTAINER Omograph_fracture
{
	NAME		Omograph_fracture;
	INCLUDE Obasemogen;

	HIDE		ID_MG_TRANSFORM_TIME;
	HIDE		ID_MG_MOTIONGENERATOR_GROUP_DISTRIBUTION;

	GROUP		ID_OBJECTPROPERTIES
	{
		LONG	MGFRACTUREOBJECT_MODE
		{
			CYCLE
			{
				MGFRACTUREOBJECT_MODE_NONE;
				MGFRACTUREOBJECT_MODE_EXPLODE;
				MGFRACTUREOBJECT_MODE_EXCONNECT;
			}
		}
	}
}
