CONTAINER Omograph_extrude
{
	NAME		Omograph_extrude;
	INCLUDE Obasemogen;

	HIDE		ID_MG_MOTIONGENERATOR_MODE;
	HIDE		ID_MG_MOTIONGENERATOR_GROUP_DISTRIBUTION;
	HIDE		ID_MG_TRANSFORM_DISPLAYMODE;
	HIDE		ID_MG_TRANSFORM_COLOR;
	HIDE		ID_MG_TRANSFORM_WEIGHT;
	HIDE		ID_MG_TRANSFORM_GROUPTIME;

	GROUP		ID_OBJECTPROPERTIES
	{
		COLUMNS 1;

		LONG	MGEXTRUDEDEFORMER_MODE
		{
			CYCLE
			{
				MGEXTRUDEDEFORMER_MODE_ROOT;
				MGEXTRUDEDEFORMER_MODE_STEP;
			}
		}
		LONG	MGEXTRUDEDEFORMER_STEPS
		{
			MIN 0;
		}
		LINK	MGEXTRUDEDEFORMER_SELECTION
		{
			ACCEPT
			{
				Tpolygonselection;
			}
		}
		LINK	MGEXTRUDEDEFORMER_SPLINE
		{
			ACCEPT
			{
				Obase;
				Ospline;
			}
			REFUSE
			{
				Osky;
				Ofloor;
			}
		}
	}
}