CONTAINER Omograph_splinemask
{
	NAME		Omograph_splinemask;
	INCLUDE Obase;

	GROUP		ID_OBJECTPROPERTIES
	{
		LONG	MGSPLINEMASKOBJECT_MODE
		{
			CYCLE
			{
				MGSPLINEMASKOBJECT_MODE_AUNIONB;
				MGSPLINEMASKOBJECT_MODE_AMINUSB;
				MGSPLINEMASKOBJECT_MODE_BMINUSA;
				MGSPLINEMASKOBJECT_MODE_AND;
				MGSPLINEMASKOBJECT_MODE_OR;
				MGSPLINEMASKOBJECT_MODE_INTERSECTION;
			}
		}
		LONG	MGSPLINEMASKOBJECT_AXIS
		{
			CYCLE
			{
				MGSPLINEMASKOBJECT_AXIS_XY;
				MGSPLINEMASKOBJECT_AXIS_ZY;
				MGSPLINEMASKOBJECT_AXIS_XZ;
				MGSPLINEMASKOBJECT_AXIS_SCREEN;
			}
		}
		BOOL	MGSPLINEMASKOBJECT_CREATECAP
		{
		}
	}
}
