CONTAINER Omograph_splinewrap
{
	NAME		Omograph_splinewrap;
	INCLUDE Obase;

	GROUP		ID_OBJECTPROPERTIES
	{
		DEFAULT 1;

		LINK	MGSPLINEWRAPDEFORMER_SPLINE
		{
			ACCEPT
			{
				Obase;
			}
		}
		LINK	MGSPLINEWRAPDEFORMER_RAIL_SPLINE
		{
			ACCEPT
			{
				Obase;
			}
		}

		LONG	MGSPLINEWRAPDEFORMER_AXIS
		{
			CYCLE
			{
				MGSPLINEWRAPDEFORMER_AXIS_XP;
				MGSPLINEWRAPDEFORMER_AXIS_XN;
				MGSPLINEWRAPDEFORMER_AXIS_YP;
				MGSPLINEWRAPDEFORMER_AXIS_YN;
				MGSPLINEWRAPDEFORMER_AXIS_ZP;
				MGSPLINEWRAPDEFORMER_AXIS_ZN;
			}
		}
		REAL	MGSPLINEWRAPDEFORMER_STRENGTH
		{
			MIN 0.0;
			MAXSLIDER 100.0;
			UNIT			PERCENT;
			CUSTOMGUI REALSLIDER;
		}
		REAL	MGSPLINEWRAPDEFORMER_OFFSET
		{
			MINSLIDER 0.0;
			MAXSLIDER 100.0;
			UNIT			PERCENT;
			CUSTOMGUI REALSLIDER;
		}
		REAL	MGSPLINEWRAPDEFORMER_FROM
		{
			MINSLIDER 0.0;
			MAXSLIDER 100.0;
			UNIT			PERCENT;
			CUSTOMGUI REALSLIDER;
		}
		REAL	MGSPLINEWRAPDEFORMER_TO
		{
			MINSLIDER 0.0;
			MAXSLIDER 100.0;
			UNIT			PERCENT;
			CUSTOMGUI REALSLIDER;
		}
		SEPARATOR
		{
			LINE;
		}
		GROUP
		{
			COLUMNS 2;
			LONG	MGSPLINEWRAPDEFORMER_LENMODE
			{
				CYCLE
				{
					MGSPLINEWRAPDEFORMER_LENMODE_FIT;
					MGSPLINEWRAPDEFORMER_LENMODE_KEEP;
				}
			}
			LONG	MGSPLINEWRAPDEFORMER_MODE
			{
				CYCLE
				{
					MGSPLINEWRAPDEFORMER_MODE_CLAMP;
					MGSPLINEWRAPDEFORMER_MODE_EXTEND;
				}
			}
		}
		GROUP MGSPLINEWRAPDEFORMER_SIZE_GRP
		{
			BOOL	MGSPLINEWRAPDEFORMER_RAIL_SCALE {}
			SPLINE	MGSPLINEWRAPDEFORMER_SIZE
			{
			}
			REAL	MGSPLINEWRAPDEFORMER_SIZESTRN
			{
				MINSLIDER 0.0;
				MAXSLIDER 100.0;
				UNIT			PERCENT;
				CUSTOMGUI REALSLIDER;
			}
			SEPARATOR
			{
				LINE;
			}
			SPLINE	MGSPLINEWRAPDEFORMER_SPLINESIZE
			{
			}
			REAL	MGSPLINEWRAPDEFORMER_SPLINESIZESTRN
			{
				MINSLIDER 0.0;
				MAXSLIDER 100.0;
				UNIT			PERCENT;
				CUSTOMGUI REALSLIDER;
			}
		}
		GROUP MGSPLINEWRAPDEFORMER_ROT_GRP
		{
			BOOL	MGSPLINEWRAPDEFORMER_RAIL_TARGET { }
			VECTOR MGSPLINEWRAPDEFORMER_UPVECTOR
			{
			}
			REAL	MGSPLINEWRAPDEFORMER_BANK
			{
				UNIT	DEGREE;
			}
			SPLINE	MGSPLINEWRAPDEFORMER_ROTATE
			{
			}
			REAL	MGSPLINEWRAPDEFORMER_ROTSTRN
			{
				MINSLIDER 0.0;
				MAXSLIDER 100.0;
				UNIT			PERCENT;
				CUSTOMGUI REALSLIDER;
			}
			SEPARATOR
			{
				LINE;
			}
			SPLINE	MGSPLINEWRAPDEFORMER_SLINEROTATE
			{
			}
			REAL	MGSPLINEWRAPDEFORMER_SPLINEROTSTRN
			{
				MINSLIDER 0.0;
				MAXSLIDER 100.0;
				UNIT			PERCENT;
				CUSTOMGUI REALSLIDER;
			}
		}
		GROUP MGSPLINEWRAPDEFORMER_BOUNDS_GRP
		{
			BOOL MGSPLINEWRAPDEFORMER_FIXBB
			{
			}
			VECTOR MGSPLINEWRAPDEFORMER_BB_CENTER
			{
			}
			VECTOR MGSPLINEWRAPDEFORMER_BB_RADIUS
			{
			}
		}
	}
}
