CONTAINER opointcreator_panel
{
	NAME	opointcreator_panel;
				
	GROUP ID_POINTCREATOR_CREATEPOINTSTAB
	{
		DEFAULT 1;
		
		GROUP
		{		
			STRING ID_POINTCREATOR_CREATEPOINTSNAME { ANIM OFF;};
		}
		
		
		SEPARATOR
		{
			LINE;
		}
		
		LONG ID_POINTCREATOR_CREATEPOINTSDISTRIBUTION
		{
			CYCLE
			{
				ID_POINTCREATOR_CREATEPOINTSUNIFORM;
				ID_POINTCREATOR_CREATEPOINTSNORMAL;
				ID_POINTCREATOR_CREATEPOINTSINVNORMAL;
				ID_POINTCREATOR_CREATEPOINTSEXPONENTIAL;
			}
			FIT_H;
		}
	
		REAL ID_POINTCREATOR_CREATEPOINTSNORMAL_STANDARDDEVIATION { UNIT REAL; MIN 0.01; MAX 0.7; STEP 0.01; CUSTOMGUI REALSLIDER;}
			

		LONG ID_POINTCREATOR_CREATEPOINTSEXPONENTIAL_X
		{
			CYCLE 
				{
					ID_POINTCREATOR_CREATEPOINTSEXPONENTIAL_ON;
					ID_POINTCREATOR_CREATEPOINTSEXPONENTIAL_INV;
					ID_POINTCREATOR_CREATEPOINTSEXPONENTIAL_OFF;
				}
				CUSTOMGUI QUICKTABRADIO;
		}
		
		LONG ID_POINTCREATOR_CREATEPOINTSEXPONENTIAL_Y
		{
			CYCLE 
			{
				ID_POINTCREATOR_CREATEPOINTSEXPONENTIAL_ON;
				ID_POINTCREATOR_CREATEPOINTSEXPONENTIAL_INV;
				ID_POINTCREATOR_CREATEPOINTSEXPONENTIAL_OFF;
			}
			CUSTOMGUI QUICKTABRADIO;
		}
		
		LONG ID_POINTCREATOR_CREATEPOINTSEXPONENTIAL_Z
		{
			CYCLE 
			{
				ID_POINTCREATOR_CREATEPOINTSEXPONENTIAL_ON;
				ID_POINTCREATOR_CREATEPOINTSEXPONENTIAL_INV;
				ID_POINTCREATOR_CREATEPOINTSEXPONENTIAL_OFF;
			}
			CUSTOMGUI QUICKTABRADIO;
		}
		
		SEPARATOR
		{
			LINE;
		}
		
		LONG ID_POINTCREATOR_CREATEDPOINTAMOUNT {  MIN 2; MAX 200000; STEP 1; SCALE_H;}
		LONG ID_POINTCREATOR_CREATEPOINTSSEED {  MIN 0; STEP 1; SCALE_H;}
		GROUP 
		{
			COLUMNS 2;
			BOOL ID_POINTCREATOR_CREATEPOINTS_ONLY_INSIDE { NAME ID_POINTCREATOR_CREATEPOINTS_ONLY_INSIDE;}
			BOOL ID_POINTCREATOR_CREATEPOINTS_ONLY_INSIDE_HIGH_QUALITY { NAME ID_POINTCREATOR_CREATEPOINTS_ONLY_INSIDE_HIGH_QUALITY;}
		}
		BOOL ID_POINTCREATOR_CREATEPOINTS_PEROBJECT { NAME ID_POINTCREATOR_CREATEPOINTS_PEROBJECT;}
						
		GROUP ID_POINTCREATOR_CREATEPOINTS_TRANSFORMATIONTAB
		{
			DEFAULT 0;
			COLUMNS 3;
			LAYOUTGROUP;

			GROUP
			{
				VECTOR	ID_POINTCREATOR_CREATEPOINTS_TRANSLATE
				{
					UNIT			METER;
					CUSTOMGUI SUBDESCRIPTION;
				}
			}
			GROUP
			{
				VECTOR	ID_POINTCREATOR_CREATEPOINTS_SCALE
				{
					MIN 0.01;
					STEP 0.01;
					CUSTOMGUI SUBDESCRIPTION;
				}
			}
			GROUP
			{
				VECTOR	ID_POINTCREATOR_CREATEPOINTS_ROTATE
				{
					UNIT			DEGREE;
					CUSTOMGUI SUBDESCRIPTION;
				}
			}
		}
		
	}
	GROUP ID_POINTCREATOR_SHADERTAB
	{
		DEFAULT 1;
		
		GROUP
		{		
			STRING ID_POINTCREATOR_SHADERNAME { ANIM OFF;};
		}
		
		SEPARATOR
		{
			LINE;
		}
		
		LONG ID_POINTCREATOR_SHADER_CHANNELSELECT
		{
			CYCLE
			{
				ID_POINTCREATOR_SHADER_CHANNELSELECT_COLOR;
				ID_POINTCREATOR_SHADER_CHANNELSELECT_LUMINANCE;
				ID_POINTCREATOR_SHADER_CHANNELSELECT_TRANSPARENCY;
				ID_POINTCREATOR_SHADER_CHANNELSELECT_ENVIRONMENT;
				ID_POINTCREATOR_SHADER_CHANNELSELECT_BUMP;
				ID_POINTCREATOR_SHADER_CHANNELSELECT_ALPHA;
				ID_POINTCREATOR_SHADER_CHANNELSELECT_DISPLACEMENT;
				ID_POINTCREATOR_SHADER_CHANNELSELECT_DIFFUSION;
				ID_POINTCREATOR_SHADER_CHANNELSELECT_NORMAL;
				ID_POINTCREATOR_SHADER_CHANNELSELECT_DIRECT;
			}
			FIT_H;
		}
		
		LINK ID_POINTCREATOR_SHADER_MATERIALTAG
		{
			ACCEPT
			{
				Ttexture;
			}
		}
		SHADERLINK	ID_POINTCREATOR_SHADER_SHADER
		{
		}
		
		SEPARATOR
		{
			LINE;
		}
		LONG ID_POINTCREATOR_SHADER_SAMPLEMODE
		{
			CYCLE
			{
				ID_POINTCREATOR_SHADER_SAMPLEMODE_VOLUME;
				ID_POINTCREATOR_SHADER_SAMPLEMODE_SURFACE;
			}
			FIT_H;
		}
		LONG ID_POINTCREATOR_SHADERSAMPLEAMOUNT { MIN 2; MAX 200000; STEP 1; SCALE_H; }
		LONG ID_POINTCREATOR_SHADERSAMPLEDENSITY { MIN 1; MAX 150; STEP 1; SCALE_H; }
		
		LONG ID_POINTCREATOR_SHADERSAMPLESEED { MIN 0; STEP 1; SCALE_H; }
		REAL ID_POINTCREATOR_SHADERSAMPLESAMPLEDEPTH { UNIT METER; MIN 0.0; STEP 0.01; }
		BOOL ID_POINTCREATOR_SHADER_PEROBJECT { NAME ID_POINTCREATOR_SHADER_PEROBJECT;}

		
		GROUP ID_POINTCREATOR_SHADER_GROUPPROJECTION
		{
			GROUP
			{
				COLUMNS 2;
				REAL	ID_POINTCREATOR_SHADER_TEXTAG_OFFSETX
				{
					STEP 0.01;
				}
				REAL	ID_POINTCREATOR_SHADER_TEXTAG_OFFSETY
				{
					STEP 0.01;
				}
				REAL	ID_POINTCREATOR_SHADER_TEXTAG_LENGTHX
				{
					UNIT	PERCENT;
				}
				REAL	ID_POINTCREATOR_SHADER_TEXTAG_LENGTHY
				{
					UNIT	PERCENT;
				}
			}
			BOOL	ID_POINTCREATOR_SHADER_TEXTAG_TILE
			{
			}
		}
		GROUP ID_POINTCREATOR_SHADER_GROUPALPHA
		{
			COLUMNS 2;
			LONG	ID_POINTCREATOR_SHADER_USE
			{
				CYCLE
				{
					ID_POINTCREATOR_SHADER_USE_ALPHA;
					ID_POINTCREATOR_SHADER_USE_GRAY;
					ID_POINTCREATOR_SHADER_USE_RED;
					ID_POINTCREATOR_SHADER_USE_GREEN;
					ID_POINTCREATOR_SHADER_USE_BLUE;
				}
			}
			BOOL	ID_POINTCREATOR_SHADER_INVERTALPHA
			{
			}
		}
	}
}
