CONTAINER Oshader_panel
{
	NAME Oshader_panel;

	GROUP ID_MG_SHADER_GROUPSHADER
	{
		GROUP ID_MG_SHADER_GROUPSHADER_NONAME
		{
			GROUP
			{
				COLUMNS 2;
				LONG ID_MG_SHADER_CHANNELSELECT
				{
					CYCLE
					{
						ID_MG_SHADER_CHANNELSELECT_COLOR;
						ID_MG_SHADER_CHANNELSELECT_LUMINANCE;
						ID_MG_SHADER_CHANNELSELECT_TRANSPARENCY;
						ID_MG_SHADER_CHANNELSELECT_ENVIRONMENT;
						ID_MG_SHADER_CHANNELSELECT_BUMP;
						ID_MG_SHADER_CHANNELSELECT_ALPHA;
						ID_MG_SHADER_CHANNELSELECT_SPECULAR;
						ID_MG_SHADER_CHANNELSELECT_DISPLACEMENT;
						ID_MG_SHADER_CHANNELSELECT_DIFFUSION;
						ID_MG_SHADER_CHANNELSELECT_NORMAL;
						ID_MG_SHADER_CHANNELSELECT_DIRECT;
					}
					FIT_H;
				}
				BUTTON ID_MG_SHADER_EDIT_CHANNEL
				{
				}
			}
			LINK ID_MG_SHADER_MATERIALTAG
			{
				ACCEPT
				{
					Ttexture;
				}
			}
			SHADERLINK ID_MG_SHADER_SHADER
			{
			}
			GROUP ID_MG_SHADER_GROUPPROJECTION
			{
				GROUP
				{
					COLUMNS 2;
					REAL ID_MG_SHADER_TEXTAG_OFFSETX
					{
						STEP 0.01;
					}
					REAL ID_MG_SHADER_TEXTAG_OFFSETY
					{
						STEP 0.01;
					}
					REAL ID_MG_SHADER_TEXTAG_LENGTHX
					{
						UNIT PERCENT;
					}
					REAL ID_MG_SHADER_TEXTAG_LENGTHY
					{
						UNIT PERCENT;
					}
				}
				BOOL ID_MG_SHADER_TEXTAG_TILE
				{
				}
			}
			GROUP ID_MG_SHADER_GROUPALPHA
			{
				COLUMNS 2;
				LONG ID_MG_SHADER_USE
				{
					CYCLE
					{
						ID_MG_SHADER_USE_ALPHA;
						ID_MG_SHADER_USE_GRAY;
						ID_MG_SHADER_USE_RED;
						ID_MG_SHADER_USE_GREEN;
						ID_MG_SHADER_USE_BLUE;
					}
				}
				BOOL ID_MG_SHADER_INVERTALPHA
				{
				}
			}
		}
	}
}
