CONTAINER tfracturevoronoi
{
	NAME	tfracturevoronoi;
	
	GROUP ID_FRACTURETAG_MAINTAB
	{
		DEFAULT 1;
		GROUP ID_FRACTURETAG_POLY
		{
			DEFAULT 1;
			LONG	ID_FRACTURETAG_POINTCREATIONTYPE
			{
				CYCLE
				{
					ID_FRACTURETAG_VERTICES;
					ID_FRACTURETAG_EDGES;
					ID_FRACTURETAG_POLYS;
					ID_FRACTURETAG_SURFACE;
					ID_FRACTURETAG_VOLUME;
				}
				FIT_H;
			}
		}
		
		GROUP ID_FRACTURETAG_SPLINE
		{
			DEFAULT 1;
			LONG	ID_FRACTURETAG_SPLINE_DISTRIBUTION
			{
				CYCLE
				{
					ID_FRACTURETAG_SPLINE_EVEN;
					ID_FRACTURETAG_SPLINE_STEP;
					ID_FRACTURETAG_SPLINE_COUNT;
					ID_FRACTURETAG_SPLINE_VERTICES;
				}
				FIT_H;
			}
		}
		
		GROUP ID_FRACTURETAG_TP
		{
			BOOL ID_FRACTURETAG_TP_SUBGROUPS {NAME ID_FRACTURETAG_TP_SUBGROUPS;};
		}
		
		LONG ID_FRACTURETAG_POINTAMOUNT { MIN 0; STEP 1; SCALE_H;}
		LONG ID_FRACTURETAG_SEED	{MIN 0; STEP 1; SCALE_H;}
		REAL ID_FRACTURETAG_OFFSET {STEP 0.1;}
		BOOL ID_FRACTURETAG_LOCK { NAME ID_FRACTURETAG_LOCK;}
	}
	
	
}