CONTAINER Tmgselection
{
	NAME		Tmgselection;

	INCLUDE Texpression;

	GROUP		ID_TAGPROPERTIES
	{
		BUTTON	MGSELECTIONTAG_CLEAR {}
		BUTTON	MGSELECTIONTAG_INVERT {}
		SEPARATOR { LINE; }
		BOOL MGSELECTIONTAG_NUMBERS { }
		BOOL MGSELECTIONTAG_USEFIELDS {}
	}

	GROUP MGSELECTIONTAG_FIELDGROUP
	{
		FIELD HIDE;
		DEFAULT 1;
		REAL MGSELECTIONTAG_FIELDTOLERANCE { MIN 0.0; MAX 100.0; ANIM ON;  UNIT PERCENT; CUSTOMGUI REALSLIDER; }
		BOOL MGSELECTIONTAG_FIELDDEFORM { ANIM ON; }
		FIELDLIST MGSELECTIONTAG_FIELDS { NEWLINE; ANIM ON; NOCOLOR; NODIRECTION; NOROTATION; }
	}
}
