CONTAINER Tmgweight
{
	NAME		Tmgweight;

	INCLUDE Texpression;

	GROUP		ID_TAGPROPERTIES
	{
		BUTTON	MGWEIGHTTAG_CLEAR {}
		BUTTON	MGWEIGHTTAG_INVERT {}
		BOOL MGWEIGHTTAG_USEFIELDS {}
	}

	GROUP MGWEIGHTTAG_GROUP_FIELDS
	{
		FIELD HIDE;
		DEFAULT 1;
		BOOL MGWEIGHTTAG_FIELDDEFORM { ANIM ON; }
		FIELDLIST MGWEIGHTTAG_FIELDS { NEWLINE; ANIM ON; NOCOLOR; NODIRECTION; NOROTATION; }
	}
}
