CONTAINER Tmograph_cache
{
	NAME		Tmograph_cache;

	INCLUDE Tbase;

	GROUP MGCACHETAG_GROUP_BUILD
	{
		DEFAULT 1;

		BOOL	MGCACHETAG_BAKESEQUENCE_ACTIVE { ANIM OFF; }
		GROUP
		{
			COLUMNS 2;

			BASETIME	MGCACHETAG_BAKEFROM {}
			BASETIME	MGCACHETAG_BAKETO {}
		}

		SEPARATOR { LINE; }

		GROUP
		{
			COLUMNS 2;
			SCALE_H;

			BUTTON	MGCACHETAG_BAKESEQUENCE { SCALE_H; }
			BUTTON	MGCACHETAG_BAKEFRAME { SCALE_H; }
			BUTTON	MGCACHETAG_CLEARCACHE { SCALE_H; }
			BUTTON	MGCACHETAG_CLEARFRAME { SCALE_H; }
		}

		SEPARATOR { LINE; }

		GROUP
		{
			COLUMNS 2;

			FILENAME MGCACHETAG_EXPORT_CACHEFILE { SAVE; ANIM OFF; SCALE_H; }
			POPUP MGCACHETAG_EXPORT_TOKENS 
			{
				ANIM OFF;
			}
		}

		GROUP
		{
			COLUMNS 2;
			SCALE_H;

			BUTTON	MGCACHETAG_BAKETOEXTERNAL { SCALE_H; }
			BUTTON	MGCACHETAG_CACHE_EXPORT { SCALE_H; }
		}

		SEPARATOR { LINE; }
	
		STATICTEXT	MGCACHETAG_MEMORYUSED {}

		FILENAME MGCACHETAG_ACTIVE_CACHEFILE { ANIM OFF; HIDDEN; }
		BOOL MGCACHETAG_CACHE_ISSEQUENCE { ANIM OFF; HIDDEN; }
		LONG MGCACHETAG_LOOPSTART { ANIM OFF; MIN 0; HIDDEN; }
		LONG MGCACHETAG_LOOPEND { ANIM OFF; MIN 0; HIDDEN; }
	}

	GROUP		MGCACHETAG_GROUP_PLAYBACK
	{
		DEFAULT 0;

		BOOL	MGCACHETAG_ACTIVE {}
		REAL	MGCACHETAG_STRENGTH { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }

		SEPARATOR { LINE; }

		LONG MGCACHETAG_MODE
		{
			CYCLE
			{
				MGCACHETAG_MODE_INTERNAL;
				MGCACHETAG_MODE_EXTERNAL;
			}
		}

		GROUP
		{
			COLUMNS 2;
			FILENAME MGCACHETAG_IMPORT_CACHEFILE { ANIM OFF; SCALE_H; }
			POPUP MGCACHETAG_IMPORT_TOKENS 
			{
				ANIM OFF;
			}
		}

		BUTTON MGCACHETAG_CACHE_IMPORT { ANIM OFF; SCALE_H; }

		SEPARATOR { LINE; }

		BASETIME MGCACHETAG_OFFSET {}
		BOOL MGCACHETAG_LOOP {} 
		REAL MGCACHETAG_LOOP_BLEND { MIN 0.0; MAX 100.0; UNIT PERCENT; }
	}

}
