CONTAINER Tool_MGWeight
{
	NAME		Tool_MGWeight;
	INCLUDE ToolBase;

	GROUP		MDATA_MAINGROUP
	{
		REAL MDATA_MGWEIGHTTOOL_STRENGTH { ANIM OFF; MIN 0.0; MAXSLIDER 100.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; }
		LONG MDATA_MGWEIGHTTOOL_MODE
		{
			ANIM OFF;
			CYCLE
			{
				MDATA_MGWEIGHTTOOL_MODE_ADD;
				MDATA_MGWEIGHTTOOL_MODE_ERASE;	
				MDATA_MGWEIGHTTOOL_MODE_ABS;
				MDATA_MGWEIGHTTOOL_MODE_SMOOTH;
			}
		}

		GROUP
		{
			COLUMNS 2;
			SCALE_H; 
			BUTTON MDATA_MGWEIGHTTOOL_APPLYALL { SCALE_H; }
			BUTTON MDATA_MGWEIGHTTOOL_APPLYSELECTED { SCALE_H; }
		}
	}

	GROUP MDATA_MGWEIGHTTOOL_GROUP_PAINTING
	{
		REAL MDATA_MGWEIGHTTOOL_RADIUS { ANIM OFF; MIN 0.0; MAXSLIDER 100.0; UNIT REAL; CUSTOMGUI REALSLIDER; }
		LONG MDATA_MGWEIGHTTOOL_STEP { ANIM OFF; MIN 1; MAX 100; CUSTOMGUI LONGSLIDER; }
		LONG MDATA_MGWEIGHTTOOL_PRESSURE
		{
			ANIM OFF;
			CYCLE
			{
				MDATA_MGWEIGHTTOOL_PRESSURE_NONE;
				MDATA_MGWEIGHTTOOL_PRESSURE_STRENGTH;
				MDATA_MGWEIGHTTOOL_PRESSURE_RADIUS;	
			}
		}

		GROUP
		{
			COLUMNS 2;
			SCALE_H;
			BOOL MDATA_MGWEIGHTTOOL_DISPLAY { SCALE_H; }
			BOOL MDATA_MGWEIGHTTOOL_VISIBLE_ONLY { SCALE_H; }
		}
	}
	
	HIDE MDATA_COMMANDGROUP;
}
