CONTAINER Xmg_multi
{
	NAME		Xmg_multi;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP		ID_SHADERPROPERTIES
	{
		LONG	MGMULTISHADER_MODE
		{
			CYCLE
			{
				MGMULTISHADER_MODE_INDEXRATIO;
				MGMULTISHADER_MODE_COLORBRIGHT;
				MGMULTISHADER_MODE_COLORX;
				MGMULTISHADER_MODE_COLORY;
				MGMULTISHADER_MODE_COLORZ;
				MGMULTISHADER_MODE_AVERAGECOL;
				MGMULTISHADER_MODE_AVERAGECOL_HSV;
			}
		}

		GROUP
		{
			SEPARATOR																			{ LINE; }

			REAL		MGMULTISHADER_BLENDCOLOR							{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }

			LONG		MGMULTISHADER_BLENDCOLOR_MODE
			{
				CYCLE
				{
					MGMULTISHADER_BLENDCOLOR_MODE_MULTIPLY;
					MGMULTISHADER_BLENDCOLOR_MODE_OVERLAY;
					MGMULTISHADER_BLENDCOLOR_MODE_COLOR;
				}
			}
		}

		GROUP
		{
			COLUMNS 4;

			SEPARATOR																			{ LINE; }
			STATICTEXT																		{ JOINENDSCALE; }
			STATICTEXT																		{ JOINENDSCALE; }
			STATICTEXT																		{ JOINENDSCALE; }

			BUTTON	MGMULTISHADER_ADD {}
			BUTTON	MGMULTISHADER_CLEAR {}
			BUTTON	MGMULTISHADER_CASTMOVIE {}
			BUTTON	MGMULTISHADER_ADDFOLDER {}
		}

		GROUP MGMULTISHADER_GROUPSHADER
		{
			DEFAULT 1;
		}
	}
}
