#ifndef C4D_SYMBOLS_H__
#define C4D_SYMBOLS_H__

enum
{
	IDS_START = 10000,

	IDS_MATERIAL_FOG,
	IDS_MATERIAL_TERRAIN,
	IDS_SHADER_BRICK,
	IDS_SHADER_CHECKERBOARD,
	IDS_SHADER_CLOUD,
	IDS_SHADER_CYCLONE,
	IDS_SHADER_EARTH,
	IDS_SHADER_FIRE,
	IDS_SHADER_FLAME,
	IDS_SHADER_GALAXY,
	IDS_SHADER_GRADIENT,
	IDS_SHADER_MARBLE,
	IDS_SHADER_METAL,
	IDS_SHADER_NOISE,
	IDS_SHADER_RUST,
	IDS_SHADER_STAR,
	IDS_SHADER_STARFIELD,
	IDS_SHADER_SUNBURST,
	IDS_SHADER_TURBULENCE,
	IDS_SHADER_PLANET,
	IDS_SHADER_VENUS,
	IDS_SHADER_WATER,
	IDS_SHADER_WOOD,
	IDS_SHADER_SPECTRAL,
	IDS_SHADER_COLORSTRIPES,
	IDS_SHADER_CHANLUM,
	IDS_SHADER_MOSAIC,
	IDS_SHADER_PAVEMENT,
	IDS_SHADER_TERRAINMASK,
	IDS_SHADER_RAIN,
	IDS_SHADER_NORMALIZER,
	IDS_SHADER_REFERENCE,
	IDS_SHADER_CHOOSER,
  IDS_SHADER_FORMULA,
  IDS_SHADER_VARIATION,

	IDS_CGFX_MODELVIEWPROJECTION,
	IDS_CGFX_FILE,
	IDS_CGFX_NORMALIZE_CUBE_TEXTURE,

	IDS_SHADER_CHOOSER_ACTIVE,
	IDS_SHADER_CHOOSER_UP,
	IDS_SHADER_CHOOSER_DWN,
	IDS_SHADER_CHOOSER_DEL,
	IDS_SHADER_CHOOSER_LAYER_SHADER,

	IDS_VARIATIONSHADER_SELECTFOLDER,
	IDS_VARIATIONSHADER_ACTIVE,
	IDS_VARIATIONSHADER_DEL,
	IDS_VARIATIONSHADER_FOLDERIMPORT_STATUS,
	IDS_VARIATIONSHADER_LAYER_SHADERTITLE,
	IDS_VARIATIONSHADER_FOLDERIMPORT_PICCOPY,
	IDS_VARIATIONSHADER_FOLDERIMPORT_COPYERROR,
	IDS_VARIATIONSHADER_PROBABILITY,

	IDS_SHADER_OBJECT_COLOR,

  IDS_SHADER_SHADOW_CATCHER,
	IDS_SHADER_THINFILM,

	_DUMMY_ELEMENT_
};

#endif // C4D_SYMBOLS_H__
