CONTAINER Desc_fieldentry
{
	NAME Desc_fieldentry;

	GROUP	ID_FIELDENTRY_GROUP
	{
		DEFAULT 1;
		BOOL FIELDENTRY_ENABLED { }
		LINK FIELDENTRY_LINK { }
		REAL FIELDENTRY_STRENGTH { UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }

		SEPARATOR { LINE; }

		LONG FIELDENTRY_MODE
		{
			CYCLE
			{
				FIELDENTRY_MODE_NORMAL;

				FIELDENTRY_MODE_SEPARATOR;

				FIELDENTRY_MODE_ADD;
				FIELDENTRY_MODE_LIGHTEN;
				FIELDENTRY_MODE_MULTIPLY;
				FIELDENTRY_MODE_COLORDODGE;
				FIELDENTRY_MODE_LINEARDODGE;

				FIELDENTRY_MODE_SEPARATOR;

				FIELDENTRY_MODE_SUBTRACT;
				FIELDENTRY_MODE_DARKEN;
				FIELDENTRY_MODE_SCREEN;
				FIELDENTRY_MODE_COLORBURN;
				FIELDENTRY_MODE_LINEARBURN;

				FIELDENTRY_MODE_SEPARATOR;

				FIELDENTRY_MODE_OVERLAY;
				FIELDENTRY_MODE_SOFTLIGHT;
				FIELDENTRY_MODE_HARDLIGHT;
				FIELDENTRY_MODE_LINEARLIGHT;
				FIELDENTRY_MODE_VIVIDLIGHT;
				FIELDENTRY_MODE_PINLIGHT;
				FIELDENTRY_MODE_GLOW;

				FIELDENTRY_MODE_SEPARATOR;

				FIELDENTRY_MODE_AVERAGE;
				FIELDENTRY_MODE_DIFFERENCE;
				FIELDENTRY_MODE_NEGATION;
				FIELDENTRY_MODE_EXCLUSION;
				FIELDENTRY_MODE_PHOENIX;
				FIELDENTRY_MODE_REFLECT;

				FIELDENTRY_MODE_SEPARATOR;

				FIELDENTRY_MODE_HARDMIX;
				FIELDENTRY_MODE_LEVR;
				FIELDENTRY_MODE_COLOR;
				FIELDENTRY_MODE_COLOR_INV;
			}
		}

		SEPARATOR { LINE; }

		LONG FIELDENTRY_COLORMODE
		{
			CYCLE
			{
				FIELDENTRY_COLORMODE_PASS;
				FIELDENTRY_COLORMODE_COLOR;
				FIELDENTRY_COLORMODE_GRADIENT;
			}
		}

		COLOR		 FIELDENTRY_COLOR { }
		GRADIENT FIELDENTRY_GRADIENT { }
	}
}
