CONTAINER Desc_fieldbg
{
	NAME Desc_fieldbg;

	GROUP	ID_FIELDBG_GROUP
	{
		DEFAULT 1;
		REAL	 ID_FIELDBG_VALUE { UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		COLOR	 ID_FIELDBG_COLOR { }
		VECTOR ID_FIELDBG_DIRECTION { }
	}
}
