CONTAINER Drendersettings
{
	NAME Drendersettings;
	INCLUDE Obaselist;

	GROUP Obaselist
	{
		HIDE ID_LAYER_LINK;

		SEPARATOR { LINE; }
		BOOL RDATA_GLOBALSAVE { ANIM OFF; }
		BOOL RDATA_MULTIPASS_ENABLE { ANIM OFF; }
		BOOL RDATA_STEREO { ANIM OFF; }
		BOOL RDATA_MATERIAL_OVERRIDE { ANIM OFF; }
		SEPARATOR { LINE; }

		LONG RDATA_RENDERENGINE { ANIM OFF; }
	}

	GROUP RDATA_GROUP_OUTPUT
	{
		DEFAULT 1;
		SCALE_V;

		GROUP
		{
			COLUMNS 3;
			POPUP RDATA_PRESET { ANIM OFF; }
			STATICTEXT RDATA_PRESETTEXT { ANIM OFF; }
			STATICTEXT { JOINENDSCALE; }
		}

		GROUP
		{
			COLUMNS 3;
			SCALE_V;

			REAL RDATA_XRES  { HIDDEN; ANIM OFF; STEP 1.0; MIN 0.0; MAX 128000.0; }
			REAL RDATA_XRES_VIRTUAL  { ANIM OFF; STEP 1.0; MIN 0.0; MAX 128000.0; }
			LONG RDATA_SIZEUNIT { ANIM OFF; CYCLE { RDATA_SIZEUNIT_PIXELS; RDATA_SIZEUNIT_CM; RDATA_SIZEUNIT_MM; RDATA_SIZEUNIT_INCHES; RDATA_SIZEUNIT_POINTS; RDATA_SIZEUNIT_PICAS; } }
			STATICTEXT { }

			REAL RDATA_YRES { HIDDEN; ANIM OFF; STEP 1.0; MIN 0.0; MAX 128000.0; }
			REAL RDATA_YRES_VIRTUAL { ANIM OFF; STEP 1.0; MIN 0.0; MAX 128000.0; }
			STATICTEXT { }
			STATICTEXT { }

			BOOL RDATA_LOCKRATIO { ANIM OFF; }
			STATICTEXT { }
			STATICTEXT { }

			BOOL RDATA_ADAPT_DATARATE { ANIM OFF; }
			STATICTEXT { }
			STATICTEXT { }

			REAL RDATA_PIXELRESOLUTION { HIDDEN; ANIM OFF; STEP 1.0; MIN 1.0; MAX 100000.0; }
			REAL RDATA_PIXELRESOLUTION_VIRTUAL { ANIM OFF; STEP 1.0; MIN 1.0; MAX 100000.0; }
			LONG RDATA_PIXELRESOLUTIONUNIT { ANIM OFF; CYCLE { RDATA_PIXELRESOLUTIONUNIT_PERCM; RDATA_PIXELRESOLUTIONUNIT_PERINCH; } }
			STATICTEXT { }

			STATICTEXT RDATA_INFOTEXT { ANIM OFF; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			STATICTEXT RDATA_PIXELRESOLUTION_WARNING { }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			BOOL RDATA_RENDERREGION { PARENTCOLLAPSE; ANIM OFF; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			LONG RDATA_RENDERREGION_LEFT { PARENTCOLLAPSE RDATA_RENDERREGION; ANIM OFF; MIN 0; MAX 128000; }
			BUTTON RDATA_FROMIRR { PARENTCOLLAPSE RDATA_RENDERREGION; }
			STATICTEXT { PARENTCOLLAPSE RDATA_RENDERREGION; }

			LONG RDATA_RENDERREGION_TOP { PARENTCOLLAPSE RDATA_RENDERREGION; ANIM OFF; MIN 0; MAX 128000; }
			STATICTEXT { PARENTCOLLAPSE RDATA_RENDERREGION; JOINEND; }
			STATICTEXT { PARENTCOLLAPSE RDATA_RENDERREGION; JOINENDSCALE; }

			LONG RDATA_RENDERREGION_RIGHT { PARENTCOLLAPSE RDATA_RENDERREGION; ANIM OFF; MIN 0; MAX 128000; }
			STATICTEXT { PARENTCOLLAPSE RDATA_RENDERREGION; JOINEND; }
			STATICTEXT { PARENTCOLLAPSE RDATA_RENDERREGION; JOINENDSCALE; }

			LONG RDATA_RENDERREGION_BOTTOM { PARENTCOLLAPSE RDATA_RENDERREGION; ANIM OFF; MIN 0; MAX 128000; }
			STATICTEXT { PARENTCOLLAPSE RDATA_RENDERREGION; JOINEND; }
			STATICTEXT { PARENTCOLLAPSE RDATA_RENDERREGION; JOINENDSCALE; }

			SEPARATOR { LINE; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			REAL RDATA_FILMASPECT { ANIM OFF; STEP 0.01; MIN 0.001; MAX 1000.0; }
			LONG RDATA_FILMPRESET { ANIM OFF; CYCLE { RDATA_FILMPRESET_CUSTOM; RDATA_FILMPRESET_SQUARE; RDATA_FILMPRESET_STANDARD; RDATA_FILMPRESET_HDTV; RDATA_FILMPRESET_35MMSTILL; RDATA_FILMPRESET_WIDESCREEN; RDATA_FILMPRESET_35MM; RDATA_FILMPRESET_PANAVISION; } }
			STATICTEXT { }

			REAL RDATA_PIXELASPECT { ANIM OFF; STEP 0.01; MIN 0.001; MAX 1000.0; }
			LONG RDATA_PIXELPRESET { ANIM OFF; CYCLE { RDATA_PIXELPRESET_CUSTOM; RDATA_PIXELPRESET_SQUARE; RDATA_PIXELPRESET_D1DVNTSC; RDATA_PIXELPRESET_D1DVPAL; RDATA_PIXELPRESET_D1DVNTSCWIDESCREEN; RDATA_PIXELPRESET_HDVANAMORPHIC; RDATA_PIXELPRESET_D1DVPALWIDESCREEN; RDATA_PIXELPRESET_ANAMORPHIC; } }
			STATICTEXT { }

			REAL RDATA_FRAMERATE { ANIM OFF; MIN 1.0; MAX 2500.0; STEP 1.0; }
			STATICTEXT { }
			STATICTEXT { }

			SEPARATOR { LINE; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			LONG RDATA_FRAMESEQUENCE { ANIM OFF; CYCLE { RDATA_FRAMESEQUENCE_MANUAL; RDATA_FRAMESEQUENCE_CURRENTFRAME; RDATA_FRAMESEQUENCE_ALLFRAMES; RDATA_FRAMESEQUENCE_PREVIEWRANGE; }}
			STATICTEXT { JOINEND; }
			STATICTEXT { }

			BASETIME RDATA_FRAMEFROM { ANIM OFF; MIN 0; }
			STATICTEXT { }
			STATICTEXT { }

			BASETIME RDATA_FRAMETO { ANIM OFF; MIN 0; }
			STATICTEXT { }
			STATICTEXT { }

			LONG RDATA_FRAMESTEP { ANIM OFF; MIN 1; MAX 1000000; }
			STATICTEXT { }
			STATICTEXT { }

			LONG RDATA_FIELD { ANIM OFF; CYCLE { RDATA_FIELD_NONE; RDATA_FIELD_EVEN; RDATA_FIELD_ODD; } }
			STATICTEXT { JOINEND; }
			STATICTEXT { }

			STATICTEXT RDATA_FRAMEOUTPUT { ANIM OFF; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			SEPARATOR { LINE; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			STRING RDATA_HELPTEXT { ANIM OFF; CUSTOMGUI MULTISTRING; WORDWRAP; SCALE_V; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }
		}
	}

	GROUP RDATA_GROUP_SAVE
	{
		DEFAULT 1;

		GROUP RDATA_GROUP_SAVEIMAGE
		{
			DEFAULT 1;
			COLUMNS 1;

			GROUP
			{
				COLUMNS 2;
				SCALE_H;
				BOOL RDATA_SAVEIMAGE { ANIM OFF; }
				STATICTEXT { NEWLINE; }
				FILENAME RDATA_PATH	{ ANIM OFF; SAVE; SCALE_H; TOKENPOPUP; }
				STATICTEXT { NEWLINE; }
			}

			GROUP
			{
				COLUMNS 2;
				SCALE_H;
				LONG RDATA_FORMAT	{ PARENTCOLLAPSE; ANIM OFF; CYCLE {}; }
				STATICTEXT { JOINENDSCALE; }
				STATICTEXT RDATA_FORMAT_WARNING { }
				STATICTEXT { JOINENDSCALE; }
				LINK RDATA_SAVEOPTIONS { PARENTCOLLAPSE RDATA_FORMAT; CUSTOMGUI INLINE; }
				STATICTEXT { JOINENDSCALE; }
				LONG RDATA_FORMATDEPTH { ANIM OFF; CYCLE { RDATA_FORMATDEPTH_8; RDATA_FORMATDEPTH_16; RDATA_FORMATDEPTH_32; } }
				STATICTEXT { JOINENDSCALE; }
				LONG RDATA_NAMEFORMAT { ANIM OFF; CYCLE { RDATA_NAMEFORMAT_0; RDATA_NAMEFORMAT_1; RDATA_NAMEFORMAT_2; RDATA_NAMEFORMAT_3; RDATA_NAMEFORMAT_4; RDATA_NAMEFORMAT_5; RDATA_NAMEFORMAT_6; } }
				STATICTEXT { JOINENDSCALE; }
				COLORPROFILE RDATA_IMAGECOLORPROFILE { }
				STATICTEXT { JOINENDSCALE; }
				BOOL RDATA_ALPHACHANNEL { ANIM OFF; }
				STATICTEXT { JOINENDSCALE; }
				BOOL RDATA_STRAIGHTALPHA { ANIM OFF; }
				STATICTEXT { JOINENDSCALE; }
				BOOL RDATA_SEPARATEALPHA	{ ANIM OFF; }
				STATICTEXT { JOINENDSCALE; }
				BOOL RDATA_TRUECOLORDITHERING	{ ANIM OFF; }
				STATICTEXT { JOINENDSCALE; }
				BOOL RDATA_INCLUDESOUND { ANIM OFF; }
				STATICTEXT { JOINENDSCALE; }
			}
		}

		GROUP RDATA_GROUP_QUICKTIMEVR
		{
			DEFAULT 1;
			LONG RDATA_VRGENERATE	{ ANIM OFF; CYCLE { RDATA_VRGENERATE_VR; RDATA_VRGENERATE_INTERMEDIATE; RDATA_VRGENERATE_BOTH; } }
			LONG RDATA_HSTEPS	{ ANIM OFF; MIN 1; MAX 1000; }
			REAL RDATA_HSTART { ANIM OFF; UNIT DEGREE; }
			REAL RDATA_HEND { ANIM OFF; UNIT DEGREE; }
			LONG RDATA_VSTEPS	{ ANIM OFF; MIN 1; MAX 1000; }
			REAL RDATA_VSTART { ANIM OFF; UNIT DEGREE; MIN -90.0; MAX 90.0; }
			REAL RDATA_VEND { ANIM OFF; UNIT DEGREE; MIN -90.0; MAX 90.0; }
			LONG RDATA_VRDEFAULTX	{ ANIM OFF; MIN 2; MAX 4000; }
			LONG RDATA_VRDEFAULTY	{ ANIM OFF; MIN 2; MAX 4000; }
		}

		GROUP RDATA_GROUP_SAVEMULTIPASSIMAGE
		{
			DEFAULT 1;
			COLUMNS 1;
			GROUP
			{
				COLUMNS 2;
				SCALE_H;
				BOOL RDATA_MULTIPASS_SAVEIMAGE { ANIM OFF; }
				STATICTEXT { NEWLINE; }
				FILENAME RDATA_MULTIPASS_FILENAME	{ ANIM OFF; SAVE; SCALE_H; TOKENPOPUP; }
			}

			GROUP
			{
				COLUMNS 2;
				LONG RDATA_MULTIPASS_SAVEFORMAT {	PARENTCOLLAPSE; ANIM OFF; CYCLE {} }
				STATICTEXT { JOINENDSCALE; }
				STATICTEXT RDATA_MULTIPASS_SAVEFORMAT_WARNING { }
				STATICTEXT { JOINENDSCALE; }
				LINK RDATA_MULTIPASS_SAVEOPTIONS { PARENTCOLLAPSE RDATA_MULTIPASS_SAVEFORMAT; CUSTOMGUI INLINE; }
				STATICTEXT { JOINENDSCALE; }
				LONG RDATA_MULTIPASS_SAVEDEPTH	{ ANIM OFF; CYCLE { RDATA_MULTIPASS_SAVEDEPTH_8; RDATA_MULTIPASS_SAVEDEPTH_16; RDATA_MULTIPASS_SAVEDEPTH_32; } }
				STATICTEXT { JOINENDSCALE; }
				BOOL RDATA_MULTIPASS_SAVEONEFILE { ANIM OFF; }
				STATICTEXT { JOINENDSCALE; }
				BOOL RDATA_MULTIPASS_SUFFIX	{ ANIM OFF; }
				STATICTEXT { JOINENDSCALE; }
				BOOL RDATA_MULTIPASS_USERNAMES { ANIM OFF; }
				STATICTEXT { JOINENDSCALE; }
				BOOL RDATA_MULTIPASS_STRAIGHTALPHA { ANIM OFF; }
				STATICTEXT { JOINENDSCALE; }
			}
		}

		GROUP RDATA_GROUP_PROJECTFILE
		{
			DEFAULT 0;
			BOOL RDATA_PROJECTFILE			{ ANIM OFF; }
			LONG RDATA_PROJECTFILETYPE		{ ANIM OFF; CYCLE { } }
			BOOL RDATA_PROJECTFILELOCAL		{ ANIM OFF;}
			BOOL RDATA_PROJECTFILEMARKER	{ ANIM OFF;}
			BOOL RDATA_PROJECTFILEDATA		{ ANIM OFF;}
			BOOL RDATA_PROJECTFILEFBX		{ ANIM OFF;}
			BOOL RDATA_PROJECTFILEABC		{ ANIM OFF;}
			BUTTON RDATA_PROJECTFILESAVE	{}
		}
	}

	GROUP RDATA_GROUP_MULTIPASS
	{
		DEFAULT 1;

		LONG RDATA_MULTIPASS_LIGHTS { ANIM OFF; CYCLE { RDATA_MULTIPASS_LIGHTS_NONE; RDATA_MULTIPASS_LIGHTS_ALL; RDATA_MULTIPASS_LIGHTS_SELECTED; } }
		LONG RDATA_MULTIPASS_LIGHTMODE { ANIM OFF; CYCLE { RDATA_MULTIPASS_LIGHTMODE_1CHANNEL; RDATA_MULTIPASS_LIGHTMODE_2CHANNELS; RDATA_MULTIPASS_LIGHTMODE_3CHANNELS; } }
		BOOL RDATA_MULTIPASS_SHADOWCORRECTION	{ ANIM OFF; }
	}

	GROUP RDATA_GROUP_ANTIALIASING
	{
		DEFAULT 1;
		COLUMNS 2;

		LONG RDATA_ANTIALIASING	{ ANIM OFF; CYCLE { RDATA_ANTIALIASING_NONE; RDATA_ANTIALIASING_GEOMETRY; RDATA_ANTIALIASING_BEST; } }
		STATICTEXT { }

		LONG RDATA_AAMINLEVEL { ANIM OFF; CYCLE { RDATA_AAMINLEVEL_1; RDATA_AAMINLEVEL_2; RDATA_AAMINLEVEL_4; RDATA_AAMINLEVEL_8; RDATA_AAMINLEVEL_16; } }
		STATICTEXT { }

		LONG RDATA_AAMAXLEVEL	{ ANIM OFF; CYCLE { RDATA_AAMAXLEVEL_1; RDATA_AAMAXLEVEL_2; RDATA_AAMAXLEVEL_4; RDATA_AAMAXLEVEL_8; RDATA_AAMAXLEVEL_16; } }
		STATICTEXT { }

		REAL RDATA_AATHRESHOLD { ANIM OFF; UNIT PERCENT; MIN 0.0; MAX 100.0;  }
		STATICTEXT { JOINENDSCALE; }

		BOOL RDATA_AAOBJECTPROPERTIES	{ ANIM OFF; }
		STATICTEXT { JOINENDSCALE; }

		BOOL RDATA_AACONSIDERMULTIPASSES { ANIM OFF; }
		STATICTEXT { JOINENDSCALE; }

		SEPARATOR { LINE; }
		STATICTEXT { JOINENDSCALE; }

		LONG RDATA_AAFILTER { ANIM OFF; CYCLE { RDATA_AAFILTER_STILLIMAGE; RDATA_AAFILTER_ANIMATION; RDATA_AAFILTER_MITCHELL; -1; RDATA_AAFILTER_SINC; RDATA_AAFILTER_BOX; RDATA_AAFILTER_TRIANGLE; RDATA_AAFILTER_CATMULL;	RDATA_AAFILTER_VIDEO; } }
		STATICTEXT { }

		BOOL RDATA_AACUSTOMFILTERSIZE { ANIM OFF; }
		STATICTEXT { JOINENDSCALE; }

		REAL RDATA_AAFILTERSIZEX { ANIM OFF; MIN 0.5; MAX 4.0; STEP 0.01; }
		STATICTEXT { JOINENDSCALE; }

		REAL RDATA_AAFILTERSIZEY { ANIM OFF; MIN 0.5; MAX 4.0; STEP 0.01; }
		STATICTEXT { JOINENDSCALE; }

		BOOL RDATA_AACLIPNEGATIVE { ANIM OFF; }
		STATICTEXT { JOINENDSCALE; }

		SEPARATOR { LINE; }
		STATICTEXT { JOINENDSCALE; }

		REAL RDATA_AAMIPGLOBAL	{ ANIM OFF; UNIT PERCENT; MIN 0.0; MAX 1000.0; }
		STATICTEXT { JOINENDSCALE; }

		LONG RDATA_SMALLFRAGMENTS { ANIM OFF; CYCLE { RDATA_SMALLFRAGMENTS_HYBRID; RDATA_SMALLFRAGMENTS_SCANLINE; RDATA_SMALLFRAGMENTS_RAYTRACE; } }
	}

  GROUP RDATA_GROUP_OVERRIDEMAT
  {
    DEFAULT 1;


    GROUP
    {
      COLUMNS 3;
      LINK RDATA_MATERIAL_OVERRIDE_LINK
      {
        ANIM OFF;
        ACCEPT
        {
          Mbase;
        }
      }

      STATICTEXT { JOINEND; }
      STATICTEXT { NEWLINE; }
      LONG RDATA_MATERIAL_OVERRIDE_EXCLUSION_MODE
      {
        ANIM OFF;
        CYCLE
        {
          RDATA_MATERIAL_OVERRIDE_EXCLUSION_MODE_INCLUDE;
          RDATA_MATERIAL_OVERRIDE_EXCLUSION_MODE_EXCLUDE;
        }
      }

      STATICTEXT { JOINEND; }
      STATICTEXT { NEWLINE; }
      IN_EXCLUDE RDATA_MATERIAL_OVERRIDE_EXCLUSION_LIST
      {
        ANIM OFF;
        ACCEPT
        {
          Mbase;
        }
      }
      STATICTEXT { JOINEND; }
      STATICTEXT { NEWLINE; }

			GROUP RDATA_GROUP_OVERRIDEMAT_PRESERVE
			{
				DEFAULT 1;
				BOOL RDATA_MATERIAL_OVERRIDE_COLOR      { ANIM OFF; }
				BOOL RDATA_MATERIAL_OVERRIDE_LUMINANCE  { ANIM OFF; }
     		BOOL RDATA_MATERIAL_OVERRIDE_TRANS      { ANIM OFF; }
      	BOOL RDATA_MATERIAL_OVERRIDE_REFL       { ANIM OFF; }
      	BOOL RDATA_MATERIAL_OVERRIDE_BUMP       { ANIM OFF; }
      	BOOL RDATA_MATERIAL_OVERRIDE_NORM       { ANIM OFF; }
      	BOOL RDATA_MATERIAL_OVERRIDE_ALPHA      { ANIM OFF; }
      	BOOL RDATA_MATERIAL_OVERRIDE_DSPL       { ANIM OFF; }
				STATICTEXT RDATA_GROUP_OVERRIDEMAT_PRESERVE_STR { ANIM OFF; }
    	}
		}
	}

	GROUP RDATA_GROUP_OPTIONS
	{
		DEFAULT 1;

		GROUP
		{
			COLUMNS 3;

			BOOL RDATA_OPTION_TRANSPARENCY	{ ANIM OFF; }
			REAL RDATA_THRESHOLD { ANIM OFF; UNIT PERCENT; MIN 0.0; MAX 100.0; }
			STATICTEXT { NEWLINE; }

			BOOL RDATA_OPTION_REFRACTION	{ ANIM OFF; }
			LONG RDATA_RAYDEPTH { ANIM OFF; MIN 0; MAX 500; }
			STATICTEXT { NEWLINE; }

			BOOL RDATA_OPTION_REFLECTION	{ ANIM OFF; }
			LONG RDATA_REFLECTIONDEPTH { ANIM OFF; MIN 1; MAX 200; }
			STATICTEXT { NEWLINE; }

			BOOL RDATA_OPTION_SHADOW { ANIM OFF; }
			LONG RDATA_SHADOWDEPTH { ANIM OFF; MIN 0; MAX 500; }
			STATICTEXT { NEWLINE; }

			SEPARATOR { LINE; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			BOOL RDATA_LIMITREFLECTION { ANIM OFF; }
			REAL RDATA_LOD { ANIM OFF; UNIT PERCENT; MIN 0.0; MAX 1000.0; }
			STATICTEXT { NEWLINE; }

			BOOL RDATA_ENABLEBLURRY			{ ANIM OFF; }
			REAL RDATA_GLOBALBRIGHTNESS { ANIM OFF; UNIT PERCENT; MIN 0.0; MAX 100000.0; }
			STATICTEXT { NEWLINE; }

			BOOL RDATA_LIMITSHADOW { ANIM OFF; }
			REAL RDATA_MOTIONLENGTH	{ ANIM OFF; MIN 1.0; MAX 65536.0; STEP 1.0; }
			STATICTEXT { NEWLINE; }

			BOOL RDATA_CACHESHADOWMAPS { ANIM OFF; }
			STATICTEXT { NEWLINE; }

			BOOL RDATA_ACTIVEOBJECTONLY { ANIM OFF; }
			STATICTEXT { NEWLINE; }

			BOOL RDATA_AUTOLIGHT { ANIM OFF; }
			STATICTEXT { NEWLINE; }

			BOOL RDATA_TEXTURES { ANIM OFF; }
			STATICTEXT { NEWLINE; }

			BOOL RDATA_TEXTUREERROR { ANIM OFF; }
			STATICTEXT { NEWLINE; }

			BOOL RDATA_VOLUMETRICLIGHTING { ANIM OFF; }
			STATICTEXT { NEWLINE; }

			BOOL RDATA_USELOD { ANIM OFF; }
			STATICTEXT { NEWLINE; }

			BOOL RDATA_SHOWHUD { ANIM OFF; }
			STATICTEXT { NEWLINE; }

			BOOL RDATA_RENDERDOODLE	{ ANIM OFF; }
			STATICTEXT { NEWLINE; }

			BOOL RDATA_ENABLESPD { ANIM OFF; }
			STATICTEXT { NEWLINE; }

			BOOL RDATA_POSTEFFECTS_ENABLE { ANIM OFF; }
			STATICTEXT { NEWLINE; }

			BOOL RDATA_NOISE_LOCK { ANIM OFF; }
			STATICTEXT { NEWLINE; }

			BOOL RDATA_SSS { ANIM OFF; }
			STATICTEXT { NEWLINE; }
		}

		GROUP
		{
			COLUMNS 2;

			LONG RDATA_BUCKETSEQUENCE { ANIM OFF; CYCLE { RDATA_BUCKETSEQUENCE_CENTERED; RDATA_BUCKETSEQUENCE_LEFTRIGHT; RDATA_BUCKETSEQUENCE_RIGHTLEFT; RDATA_BUCKETSEQUENCE_TOPBOTTOM; RDATA_BUCKETSEQUENCE_BOTTOMTOP; }}
			STATICTEXT { NEWLINE; }

			BOOL RDATA_AUTOMATICBUCKETSIZE { PARENTCOLLAPSE; ANIM OFF; }
			STATICTEXT { NEWLINE; }

			LONG RDATA_BUCKETSIZEX { PARENTCOLLAPSE RDATA_AUTOMATICBUCKETSIZE; ANIM OFF; MIN 8; MAX 256; }
			STATICTEXT { PARENTCOLLAPSE RDATA_AUTOMATICBUCKETSIZE; NEWLINE; }
			LONG RDATA_BUCKETSIZEY { PARENTCOLLAPSE RDATA_AUTOMATICBUCKETSIZE; ANIM OFF; MIN 8; MAX 256; }
			STATICTEXT { PARENTCOLLAPSE RDATA_AUTOMATICBUCKETSIZE; NEWLINE; }

			//SEPARATOR { LINE; }
			//STATICTEXT { JOINENDSCALE; }

			//LONG RDATA_REDUCEFRAGMENTS { ANIM OFF; CYCLE { RDATA_REDUCEFRAGMENTS_NONE; RDATA_REDUCEFRAGMENTS_LEVEL1; RDATA_REDUCEFRAGMENTS_LEVEL2; RDATA_REDUCEFRAGMENTS_LEVEL3; RDATA_REDUCEFRAGMENTS_LEVEL4; } }
			//STATICTEXT { NEWLINE; }
			//BOOL RDATA_EXPERIMENTAL1	{ ANIM OFF; }
			//STATICTEXT { NEWLINE; }
			//BOOL RDATA_EXPERIMENTAL2	{ ANIM OFF; }
		}
	}

	GROUP RDATA_GROUP_STEREO
	{
		DEFAULT 1;

		GROUP
		{
			COLUMNS 3;
			LONG RDATA_STEREO_CALCRESULT { ANIM OFF; CYCLE { RDATA_STEREO_CALCRESULT_S; RDATA_STEREO_CALCRESULT_R; RDATA_STEREO_CALCRESULT_SR; RDATA_STEREO_CALCRESULT_SINGLE;}}
			STATICTEXT { JOINEND; }
			STATICTEXT {  }

			LONG RDATA_STEREO_SINGLECHANNEL { ANIM OFF; MIN 1; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			BOOL RDATA_STEREO_CALCULATE_ORIGINAL { ANIM OFF; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			BOOL RDATA_STEREO_SAVE_FOLDER { ANIM OFF; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

			LONG RDATA_STEREO_CHANNELS { ANIM OFF; MIN 1; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }


			LONG RDATA_STEREO_MODE { ANIM OFF; CYCLE { RDATA_STEREO_MODE_ANAGLYPH; RDATA_STEREO_MODE_SIDEBYSIDE; RDATA_STEREO_MODE_INTERLACED; }}
			STATICTEXT { JOINEND; }
			STATICTEXT { }

			LONG RDATA_STEREO_PARALLAX { ANIM OFF; MIN 0; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }


			BOOL RDATA_STEREO_SWAP { ANIM OFF; }
			STATICTEXT { JOINEND; }
			STATICTEXT { JOINENDSCALE; }

		}

		GROUP RDATA_GROUP_STEREO_ANA
		{
			DEFAULT 1;
			COLUMNS 1;
			SCALE_H;

			GROUP
			{
				LONG RDATA_STEREO_ANAGLYPH_SYSTEM_FULL
				{
					ANIM OFF;
					CYCLE
					{
						RDATA_STEREO_ANAGLYPH_SYSTEM_F_RB;
						RDATA_STEREO_ANAGLYPH_SYSTEM_F_RG;
						RDATA_STEREO_ANAGLYPH_SYSTEM_F_RC;
						RDATA_STEREO_ANAGLYPH_SYSTEM_F_YB;
						RDATA_STEREO_ANAGLYPH_SYSTEM_F_GM;
						RDATA_STEREO_ANAGLYPH_SYSTEM_F_CUSTOM;
					}
				}
				LONG RDATA_STEREO_ANAGLYPH_SYSTEM_NON_FULL
				{
					ANIM OFF;
					CYCLE
					{
						RDATA_STEREO_ANAGLYPH_SYSTEM_N_R;
						RDATA_STEREO_ANAGLYPH_SYSTEM_N_G;
						RDATA_STEREO_ANAGLYPH_SYSTEM_N_B;
						RDATA_STEREO_ANAGLYPH_SYSTEM_N_Y;
						RDATA_STEREO_ANAGLYPH_SYSTEM_N_M;
						RDATA_STEREO_ANAGLYPH_SYSTEM_N_CUSTOM;
					}
				}
			}

			GROUP
			{
				COLUMNS 2;
				SCALE_H;

				COLOR RDATA_STEREO_ANAGLYPH_COL_LEFT { ANIM OFF; SCALE_H; }
				COLOR RDATA_STEREO_ANAGLYPH_COL_RIGHT { ANIM OFF; SCALE_H; }
			}

			LONG RDATA_STEREO_ANAGLYPH_METHOD
			{
				ANIM OFF;
				CYCLE
				{
					RDATA_STEREO_ANAGLYPH_METHOD_FULL;
					RDATA_STEREO_ANAGLYPH_METHOD_GRAY;
					RDATA_STEREO_ANAGLYPH_METHOD_HALFCOL;
					RDATA_STEREO_ANAGLYPH_METHOD_OPTIMIZED;
					RDATA_STEREO_ANAGLYPH_METHOD_COLOR;
				}
			}
		}

		GROUP RDATA_GROUP_STEREO_SBS
		{
			DEFAULT 1;
			COLUMNS 3;

			LONG RDATA_STEREO_SBS_ALIGN { ANIM OFF; CYCLE { RDATA_STEREO_SBS_ALIGN_HORIZONTAL; RDATA_STEREO_SBS_ALIGN_VERTICAL;}}
			STATICTEXT { JOINEND; }
			STATICTEXT { }

			BOOL RDATA_STEREO_SBS_LEFT_MX { ANIM OFF; }
			BOOL RDATA_STEREO_SBS_LEFT_MY { ANIM OFF; }
			STATICTEXT { JOINENDSCALE; }

			BOOL RDATA_STEREO_SBS_RIGHT_MX { ANIM OFF; }
			BOOL RDATA_STEREO_SBS_RIGHT_MY { ANIM OFF; }
			STATICTEXT { JOINENDSCALE; }

		}

		GROUP RDATA_GROUP_STEREO_INTER
		{
			DEFAULT 1;
			COLUMNS 3;

			LONG RDATA_STEREO_INTERLACED_TYPE { ANIM OFF; CYCLE { RDATA_STEREO_INTERLACED_TYPE_HORIZONTAL; RDATA_STEREO_INTERLACED_TYPE_VERTICAL; RDATA_STEREO_INTERLACED_TYPE_CHECKERBOARD; }}
			STATICTEXT { JOINEND; }
			STATICTEXT { }

		}
	}

	GROUP RDATA_GROUP_NET
	{
		DEFAULT 1;

		GROUP RDATA_GROUP_NET_SINGLEIMAGE
		{
			DEFAULT 1;

			BOOL RDATA_NET_CACHES_SSS { ANIM OFF; }
			BOOL RDATA_NET_CACHES_AO { ANIM OFF; }
			BOOL RDATA_NET_CACHES_GI { ANIM OFF; }
			BOOL RDATA_NET_CACHES_LM { ANIM OFF; }
			BOOL RDATA_NET_CACHES_RM { ANIM OFF; }
		}
	}
}
