CONTAINER Dsoundprobe
{
	NAME Dsoundprobe;

	GROUP SOUNDPROBESUBCHANNEL_PROBE_GROUP
	{
		DEFAULT 1;

		REAL SOUNDPROBESUBCHANNEL_LEFT { MIN 0.0; MAX 22050.0; STEP 1.0; }
		REAL SOUNDPROBESUBCHANNEL_RIGHT { MIN 0.0; MAX 22050.0; STEP 1.0; }
		REAL SOUNDPROBESUBCHANNEL_TOP { MIN 0.0; MAX 100.0; UNIT PERCENT; STEP 1.0; }
		REAL SOUNDPROBESUBCHANNEL_BOTTOM { MIN 0.0; MAX 100.0; UNIT PERCENT; STEP 1.0; }

		LONG SOUNDPROBESUBCHANNEL_COLOR_MODE
		{
			CYCLE
			{
				SOUNDPROBESUBCHANNEL_COLOR_MODE_OFF;
				SOUNDPROBESUBCHANNEL_COLOR_MODE_SOLID;
				SOUNDPROBESUBCHANNEL_COLOR_MODE_HORIZONTAL;
				SOUNDPROBESUBCHANNEL_COLOR_MODE_VERTICAL;
			}
		}

		COLOR SOUNDPROBESUBCHANNEL_COLOR {}
		GRADIENT SOUNDPROBESUBCHANNEL_GRADIENT {}

		BOOL SOUNDPROBESUBCHANNEL_HOLD {}
	}
}
