CONTAINER Dsounddata
{
	NAME Dsounddata;

	GROUP SOUNDDATASUBCHANNEL_GROUP
	{
		DEFAULT 1;

		REAL SOUNDDATASUBCHANNEL_LOG { MIN 0.0; MAX 100.0; STEP 1.0; UNIT PERCENT; }
		LONG SOUNDDATASUBCHANNEL_DIRECTION
		{
			CYCLE
			{
				SOUNDDATASUBCHANNEL_DIRECTION_HORIZ;
				SOUNDDATASUBCHANNEL_DIRECTION_VERT;
			}
		}

		GRADIENT SOUNDDATASUBCHANNEL_GRADIENT {}

		BOOL SOUNDDATASUBCHANNEL_FREEEZE {}
	}
	GROUP SOUNDDATASUBCHANNEL_PROBE_GROUP
	{
	}
}
