CONTAINER FLClamp
{
	NAME FLClamp;

	INCLUDE FLbase;

	GROUP	FLBase
	{
		DEFAULT 1;

		SEPARATOR { LINE; }

		GROUP
		{
			FIT_H;
			COLUMNS 2;

			REAL FIELDLAYER_CLAMP_MIN_VALUE { SCALE_H; UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			BOOL FIELDLAYER_CLAMP_MIN_ENABLED { }

			REAL FIELDLAYER_CLAMP_MAX_VALUE { SCALE_H; UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			BOOL FIELDLAYER_CLAMP_MAX_ENABLED { }
		}
	}
}
