CONTAINER FLColorize
{
	NAME FLColorize;

	INCLUDE FLbase;

	GROUP	FLBase
	{
		DEFAULT 1;

		SEPARATOR { LINE; }

		LONG FIELDLAYER_COLORIZE_SOURCE
		{
			CYCLE
			{
				FIELDLAYER_COLORIZE_SOURCE_VALUE;
				FIELDLAYER_COLORIZE_SOURCE_COLOR;
			}
		}

		LONG FIELDLAYER_COLORIZE_MODE
		{
			CYCLE
			{
				FIELDLAYER_COLORIZE_MODE_MONOCHROME;
				FIELDLAYER_COLORIZE_MODE_DUOTONE;
			}
		}

		SEPARATOR { LINE; }

		COLOR FIELDLAYER_COLORIZE_COLORBASE { OPEN; }
		REAL	FIELDLAYER_COLORIZE_COLORBASE_DENSITY { UNIT PERCENT; MIN 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }

		COLOR FIELDLAYER_COLORIZE_COLORTOP { OPEN; }
		REAL	FIELDLAYER_COLORIZE_COLORTOP_DENSITY { UNIT PERCENT; MINSLIDER 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }

		SEPARATOR{ LINE; }

		LONG FIELDLAYER_COLORIZE_COLORTOP_MODE
		{
			CYCLE
			{
				FIELDLAYER_COLORIZE_COLORTOP_MODE_PIGMENT;
				FIELDLAYER_COLORIZE_COLORTOP_MODE_DYE;
			}
		}

		SEPARATOR{ LINE; }
		
		BOOL FIELDLAYER_COLORIZE_CLIP {}
	}
}
