CONTAINER FLCurve
{
	NAME FLCurve;

	INCLUDE FLbase;

	GROUP	FLBase
	{
		DEFAULT 1;

		SEPARATOR { LINE; }

		SPLINE	 FIELDLAYER_CURVE_SPLINE { }
		REAL		 FIELDLAYER_CURVE_OFFSET { UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		BASETIME FIELDLAYER_CURVE_ANIMATIONSPEED { }

		GROUP
		{
			FIT_H;
			COLUMNS 2;

			LONG FIELDLAYER_CURVE_PREMODE
			{
				SCALE_H;
				CYCLE
				{
					FIELDLAYER_CURVE_MODE_CLAMP;
					-1;
					FIELDLAYER_CURVE_MODE_VELOCITY;
					FIELDLAYER_CURVE_MODE_CURVE;
					-1;
					FIELDLAYER_CURVE_MODE_LOOP;
					FIELDLAYER_CURVE_MODE_PINGPONG;
				}
			}

			LONG FIELDLAYER_CURVE_POSTMODE
			{
				SCALE_H;
				CYCLE
				{
					FIELDLAYER_CURVE_MODE_CLAMP;
					-1;
					FIELDLAYER_CURVE_MODE_VELOCITY;
					FIELDLAYER_CURVE_MODE_CURVE;
					-1;
					FIELDLAYER_CURVE_MODE_LOOP;
					FIELDLAYER_CURVE_MODE_PINGPONG;
				}
			}

		}

	}
}
