CONTAINER FLGradient
{
	NAME FLGradient;

	INCLUDE FLbase;

	GROUP	FLBase
	{
		DEFAULT 1;

		SEPARATOR { LINE; }

		LONG FIELDLAYER_GRADIENT_SOURCE
		{
			CYCLE
			{
				FIELDLAYER_GRADIENT_SOURCE_VALUE;
				FIELDLAYER_GRADIENT_SOURCE_COLOR;
				FIELDLAYER_GRADIENT_SOURCE_DIRECTION;
			}
		}

		SEPARATOR { LINE; }

		GRADIENT FIELDLAYER_GRADIENT_GRADIENT { COLOR; ALPHA; }

		SEPARATOR { LINE; }

		BOOL		 FIELDLAYER_GRADIENT_CYCLE { }
		REAL		 FIELDLAYER_GRADIENT_SCALE { UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		REAL		 FIELDLAYER_GRADIENT_OFFSET { UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		BASETIME FIELDLAYER_GRADIENT_ANIMATIONSPEED { }
	}
}
