CONTAINER FLRangemap
{
	NAME FLRangemap;

	INCLUDE FLbase;

	GROUP	FLBase
	{
		DEFAULT 1;

		GROUP
		{
			COLUMNS 2;
			SCALE_H;
			FIT_H;

			REAL FIELDLAYER_RANGEMAP_MININ { FIT_H; SCALE_H; UNIT PERCENT; MINSLIDER -100.0; MAXSLIDER 200.0;  CUSTOMGUI REALSLIDER; }
			REAL FIELDLAYER_RANGEMAP_MINOUT { FIT_H; SCALE_H; UNIT PERCENT; MINSLIDER -100.0; MAXSLIDER 200.0;  CUSTOMGUI REALSLIDER; }

			REAL FIELDLAYER_RANGEMAP_MAXIN { FIT_H; SCALE_H; UNIT PERCENT; MINSLIDER -100.0; MAXSLIDER 200.0; CUSTOMGUI REALSLIDER; }
			REAL FIELDLAYER_RANGEMAP_MAXOUT { FIT_H; SCALE_H; UNIT PERCENT; MINSLIDER -100.0; MAXSLIDER 200.0; CUSTOMGUI REALSLIDER; }
		}
	}
}
