CONTAINER FLSolid
{
	NAME FLSolid;

	INCLUDE FLbase;

	GROUP	FLBase
	{
		DEFAULT 1;

		SEPARATOR { LINE; }

		REAL	 FIELDLAYER_SOLID_VALUE { UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; FIELD VALUE; }
		COLOR	 FIELDLAYER_SOLID_COLOR { OPEN; FIELD COLOR; }
		VECTOR FIELDLAYER_SOLID_DIRECTION { FIELD DIRECTION; }
	}
}
