CONTAINER Pbodypaint
{
	NAME Pbodypaint;

	GROUP PBODYPAINT_GROUP_GENERAL
	{
		DEFAULT	1;
		COLUMNS 2;
		SEPARATOR PBODYPAINT_GROUP_TEX {}
		STATICTEXT {JOINENDSCALE;}	
		
		LONG PBODYPAINT_DEFAULTTEXTUREFORMAT {ANIM OFF; CYCLE { PBODYPAINT_DEFAULTTEXTUREFORMAT_B3D; PBODYPAINT_DEFAULTTEXTUREFORMAT_PSD; PBODYPAINT_DEFAULTTEXTUREFORMAT_TIF; } }
		STATICTEXT{}
		
		SEPARATOR PBODYPAINT_GROUP_BRUSH {}
		STATICTEXT {JOINENDSCALE;}	
		
		BOOL PBODYPAINT_SHOWBRUSHMOUSEMOVE {  ANIM OFF;}
		STATICTEXT{}
		
		BOOL PBODYPAINT_SHOWBRUSHPAINTING {  ANIM OFF;}
		STATICTEXT{}
		
		LONG PBODYPAINT_TOOLCURSOR
		{
			ANIM OFF; 
			CYCLE 
			{ 
				PBODYPAINT_TOOLCURSOR_STAND;
				PBODYPAINT_TOOLCURSOR_CROSS;
				PBODYPAINT_TOOLCURSOR_HIDE;

			} 
		}
		STATICTEXT{}
		
		SEPARATOR PBODYPAINT_GROUP_PRJPAINT {}
		STATICTEXT {JOINENDSCALE;}	
		
		LONG  PBODYPAINT_PIXELBORDER {ANIM OFF; MIN 0; MAX 20;}
		STATICTEXT{}
		BOOL PBODYPAINT_TILEU  {ANIM OFF;}
		STATICTEXT{}
		BOOL PBODYPAINT_TILEV  {ANIM OFF;}
		STATICTEXT{}
		BOOL PBODYPAINT_PROJECTON	{ANIM OFF;}
		STATICTEXT{}
		BOOL PBODYPAINT_PP_PROJECT_THROUGH_UNPAINTABLE	{ANIM OFF;}
		STATICTEXT{}	
		BOOL PBODYPAINT_BORDERON	{ANIM OFF;}
		STATICTEXT{}
		BOOL PBODYPAINT_CONTINUE	{ANIM OFF;}
		STATICTEXT{}
		
		SEPARATOR PBODYPAINT_GROUP_FILTER {}
		STATICTEXT {JOINENDSCALE;}	

		LONG PBODYPAINT_FILTER_WIDTH	
		{
			ANIM OFF;
			MIN 64;
			MAX 512;
		} 
		STATICTEXT{}
		LONG PBODYPAINT_FILTER_HEIGHT
		{
			ANIM OFF;
			MIN 64;
			MAX 512;
		} 
		STATICTEXT{}
		BOOL PBODYPAINT_FILTER_SHOWPREV	{ANIM OFF;}
		STATICTEXT{}
	}
}
