CONTAINER Prefscommunication
{
	NAME Prefscommunication;
	SCALE_V;

	GROUP PREF_COMMUNICATION_MAINGROUP
	{
		DEFAULT 1;
		COLUMNS 1;
        
		BOOL PREF_COMMUNICATION_QUICKSTART_DIALOG { ANIM OFF; HIDDEN; }
		
		BOOL PREF_COMMUNICATION_BUGREPORTS { ANIM OFF; }
		GROUP PREF_COMMUNICATION_UPDATEGROUP { }
		
		BOOL PREF_COMMUNICATION_UPDATE_AUTO { ANIM OFF; }
		BOOL PREF_COMMUNICATION_UPDATE_AUTO_DEVELOPER { ANIM OFF; }
		
		SEPARATOR {LINE;}	
	}
	GROUP 	
	{
		GROUP PREF_COMMUNICATION_LIVELINKGROUP
		{
			DEFAULT 0;
			NAME PREF_COMMUNICATION_LIVELINK;

			COLUMNS 1;
			GROUP
			{
				BOOL PREF_COMMUNICATION_LIVELINK_ENABLED{ ANIM OFF; }
				LONG PREF_COMMUNICATION_LIVELINK_PORT{ ANIM OFF; MIN  0; MAX 65536; }
			}
		}
	}
	GROUP
	{
		SCALE_V;

		GROUP PREF_COMMUNICATION_METRICSGROUP
		{
			DEFAULT 0;
			NAME METRICS_HEADLINE;
			SCALE_V;
			GROUP
			{
				COLUMNS 3;
				GROUP
				{
					COLUMNS 2;
					STATICTEXT PREF_COMMUNICATION_METRICS_DISABLE_CHECKBOX_NAME { PADDING 30; }
					BOOL PREF_COMMUNICATION_METRICS_DISABLE_CHECKBOX { 	}
				}
				
				BUTTON PREF_COMMUNICATION_METRICS_GOTO_PREFERENCE_DIRECTORY { NAME PREF_COMMUNICATION_METRICS_GOTO_PREFERENCE_DIRECTORY_NAME; }
				BUTTON PREF_COMMUNICATION_METRICS_GOTO_SERVER_LOCATION { NAME PREF_COMMUNICATION_METRICS_GOTO_SERVER_LOCATION_NAME; }
				
			}
			

			STRING PREF_COMMUNICATION_METRICS_INFO
			{ 
				CUSTOMGUI MULTISTRING; 
				SCALE_V;
				ANIM OFF;
				WORDWRAP;
				READONLY;
				NO_BORDER; 
					NO_DARK_BACKGROUND;
			}

			
			


			
		}
	}

	
}
