CONTAINER Prefsfiles
{
	NAME Prefsfiles;
	GROUP PREF_FILE_MAIN_GROUP
	{
		DEFAULT 1;
		COLUMNS 1;

		GROUP
		{
			DEFAULT 1;

			SEPARATOR PREFS_FILE_BASIC {}
			LONG PREF_FILE_RECENT  { ANIM OFF; MIN 0; MAX 100; }
			LONG PREF_FILE_BACKUP  { ANIM OFF; MIN 0; MAX 1000;}
			LONG PREF_FILE_ASSETS_LINK
			{
				ANIM OFF;
				CYCLE
				{
					PREF_FILE_ASSETS_LINK_RELATIVE;
					PREF_FILE_ASSETS_LINK_ABSOLUTE;
					PREF_FILE_ASSETS_LINK_ASK;
				}
			}

			SEPARATOR PREFS_FILE_AUTOSAVE {}
			GROUP
			{
				DEFAULT 1;
				COLUMNS 2;

				BOOL PREF_FILE_AUTOEVERY{ ANIM OFF; }
				LONG PREF_FILE_AUTOMIN  { ANIM OFF; MIN 1; MAX 10000;}

				BOOL PREF_FILE_AUTOLIMIT	{ ANIM OFF; }
				LONG PREF_FILE_AUTOCOPIES { ANIM OFF; MIN 1; MAX 1000; }
			}

			GROUP
			{
				DEFAULT 1;
				COLUMNS 2;
				LONG PREF_FILE_AUTOSAVETO { ANIM OFF; CYCLE { PREF_FILE_AUTOSAVE_PRJ; PREF_FILE_AUTOSAVE_USR; PREF_FILE_AUTOSAVE_CST;} }
				FILENAME PREF_FILE_AUTOSAVEDIR { SCALE_H; DIRECTORY; ANIM OFF;}
			}

			SEPARATOR ID_FILES_GROUP_XREF{}
			GROUP
			{
				DEFAULT 1;
				COLUMNS 1;
				BOOL ID_FILES_XREFPREFS_DEFERRED_LOAD { }
				BOOL ID_FILES_XREFPREFS_REDUCED_SAVE { }
			}
		}
	}
}
