CONTAINER Prefspaths
{
	SCALE_V;
	NAME Prefspaths;
	GROUP PREFS_PATHS_MAIN_GROUP
	{
		DEFAULT 1;
		COLUMNS 1;
		SCALE_V;

		GROUP PREFS_TEXPATH_GROUP
		{
			DEFAULT 1;
			COLUMNS 1;
			SCALE_V;
			STRING PREF_TEXPATHS { CUSTOMGUI PATHS; SCALE_V; ANIM OFF;}
		}

		GROUP PREFS_DATABASE_PATHS_GROUP
		{
			DEFAULT 1;
			COLUMNS 1;
			SCALE_V;
			STRING PREF_DATABASE_PATHS { CUSTOMGUI PATHS; SCALE_V; MODE 2; ANIM OFF;}
		}
	}
}
