CONTAINER Prefsimexport
{
	NAME Prefsimexport;
	GROUP PREF_IMEXPORT_MAIN_GROUP
	{
		DEFAULT 1;
		COLUMNS 1;

		BOOL PREF_IMEXPORT_SHOW_IMPORT_DLG {ANIM OFF; }
		BOOL PREF_IMEXPORT_SHOW_EXPORT_DLG {ANIM OFF; }
		STATICTEXT PREF_IMEXPORT_SHOW_DLG_INFO {}

		SEPARATOR { LINE; }

		BOOL PREF_IMEXPORT_MERGE_ON_DD {ANIM OFF; }
		STATICTEXT PREF_IMEXPORT_MERGE_ON_DD_INFO {}
	}
}
