CONTAINER PrefsRenderer
{
	NAME PrefsRenderer;
	GROUP PREF_RENDERER_MAIN_GROUP
	{
		DEFAULT 1;
		COLUMNS 1;

		GROUP
		{
			DEFAULT 1;
			COLUMNS 2;
			BOOL PREF_RENDERER_THREADCUSTOM {ANIM OFF; }
			LONG PREF_RENDERER_THREADNUMBER	{ ANIM OFF; MIN 1; MAX 256;}
		

			BOOL PREF_RENDERER_THREADPRIORITY {ANIM OFF;}
			STATICTEXT{}

			BOOL PREF_RENDERER_LOWERPROCESSPRIORITY {ANIM OFF;}
			STATICTEXT{JOINEND;}

			BOOL PREF_RENDERER_CREATELOG {ANIM OFF;}
			STATICTEXT{}

			BOOL PREF_RENDERER_GLOBALILLUM {ANIM OFF;}
			STATICTEXT{}

			SEPARATOR {LINE; }
			STATICTEXT { JOINENDSCALE; }

			BOOL PREF_RENDERER_RENDERQUEUELOG {ANIM OFF;}
			STATICTEXT{}

			BOOL PREF_RENDERER_RENDERQUEUE_AUTORENAME {ANIM OFF;}
			STATICTEXT{}
		}
	}
}
