CONTAINER Prefsmouse
{
	NAME Prefsmouse;

	GROUP PREF_MOUSE_MAIN_GROUP
	{
		DEFAULT 1;

		GROUP
		{		
			COLUMNS 2;
					
			BOOL PREF_MOUSE_BASICCURSOR	{ ANIM OFF; }
			STATICTEXT {}
			BOOL PREF_MOUSE_CURSOR	{ ANIM OFF; }
			STATICTEXT {}
			BOOL PREF_MOUSE_ACTIVATION {ANIM OFF;}
			STATICTEXT {}
			BOOL PREF_MOUSE_RMB_EMULATION {ANIM OFF;}
			STATICTEXT PREF_MOUSE_DUMMY_STR {}
			SEPARATOR {LINE;}
			STATICTEXT {JOINENDSCALE;}
			BOOL PREF_MOUSE_GRAPHICTABLET{ ANIM OFF; }
			STATICTEXT PREF_MOUSE_DUMMYGRAPHICTABLET_STR {}
			BOOL PREF_MOUSE_HIRESTABLET{ ANIM OFF; }
			STATICTEXT PREF_MOUSE_DUMMYHIRESTABLET_STR {}
			SEPARATOR {LINE;}
			STATICTEXT {JOINENDSCALE;}
			BOOL PREF_MOUSE_COMMANDER_AT_CURSOR{ ANIM OFF; }
			STATICTEXT {}
			SEPARATOR {LINE;}
			STATICTEXT {JOINENDSCALE;}
			LONG PREF_MOUSE_TOUCHSUPPORT
			{
				ANIM OFF;
				CYCLE
				{
					PREF_MOUSE_TS_AUTOMATIC;
					PREF_MOUSE_TS_WHEEL;
					PREF_MOUSE_TS_TOUCH;
				}
			}
		}
	}
}
