CONTAINER Prefsmemory
{
	NAME Prefsmemory;
	GROUP PREF_MEMORY_MAIN_GROUP
	{
	
		DEFAULT 1;
		COLUMNS 3;
		
		SEPARATOR PREFS_MEMORY_DOCGROUP {}
		STATICTEXT {JOINENDSCALE;}
		STATICTEXT {JOINENDSCALE;}
		LONG PREF_MEMORY_UNDO	{ ANIM OFF; MIN 1; MAX 10000;}
		STATICTEXT {}
		STATICTEXT {}
		LONG PREF_MEMORY_MATERIAL	{ ANIM OFF; MIN 1; MAX 10000;}
		STATICTEXT {}
		STATICTEXT {}
		
		SEPARATOR PREFS_MEMORY_RENDGROUP {}
		STATICTEXT {JOINENDSCALE;}
		STATICTEXT {JOINENDSCALE;}
		LONG PREF_MEMORY_RENDERER	{ ANIM OFF; MIN 1; MAX 10000;}
		STATICTEXT {}
		STATICTEXT {}
		
		SEPARATOR PREFS_MEMORY_BPGROUP {}
		STATICTEXT {JOINENDSCALE;}
		STATICTEXT {JOINENDSCALE;}
		
		LONG PREF_MEMORY_BP	{ ANIM OFF; MIN 1; MAX 10000;}
		STATICTEXT {}
		STATICTEXT{}
		LONG PREF_MEMORY_BPUNDO {  ANIM OFF; MIN 1; MAX 1000;}
		STATICTEXT {}
		STATICTEXT{}
		
		SEPARATOR PREFS_MEMORY_PVGROUP {}
		STATICTEXT {JOINENDSCALE;}
		STATICTEXT {JOINENDSCALE;}	
			
		LONG PREF_MEMORY_PVUSEAGE	{ ANIM OFF; MIN 50;}
		STATICTEXT {}
		STATICTEXT{}
		

		
		LONG PREF_MEMORY_PVHARDUSAGE	{ ANIM OFF; MIN 50;}
		BOOL PREF_MEMORY_PVHARDUNLIMIT {ANIM OFF;}
		STATICTEXT {}
		FILENAME PREF_MEMORY_PVHARDFOLDER {ANIM OFF; DIRECTORY;}				
		STATICTEXT {JOINENDSCALE;}
		STATICTEXT {JOINENDSCALE;}	

		SEPARATOR PREFS_MEMORY_SCULPTGROUP {}
		STATICTEXT {JOINENDSCALE;}
		STATICTEXT {JOINENDSCALE;}	
		
		LONG PREF_MEMORY_SCULPTUSAGE	{ ANIM OFF; MIN 1;}
		STATICTEXT {}
		STATICTEXT{}


		SEPARATOR PREFS_MEMORY_PHGROUP {}
		STATICTEXT {JOINENDSCALE;}
		STATICTEXT {JOINENDSCALE;}	
		
		LONG PREF_MEMORY_PHFOOTAGEMAXCACHEMB	{ ANIM OFF; MIN 10;}
		STATICTEXT {}
		STATICTEXT{}

		LONG PREF_MEMORY_PHFOOTAGESYSRESERVEMB	{ ANIM OFF; MIN 10;}
		STATICTEXT {}
		STATICTEXT{}

	}
}
