CONTAINER Prefsnodeeditor
{
	NAME Prefsnodeeditor;

	GROUP PREF_NODE_EDITOR_MAIN_GROUP
	{
		DEFAULT 1;

		BOOL PREF_NODE_EDITOR_PREVIEW	{ ANIM OFF; }

		BOOL PREF_NODE_EDITOR_GRID	{ ANIM OFF; }

		BOOL PREF_NODE_EDITOR_NAVIGATOR {ANIM OFF;}

		BOOL PREF_NODE_EDITOR_ERRORS {ANIM OFF;}

		LONG PREF_NODE_EDITOR_WIRE_STYLE
		{
			ANIM OFF;
			CYCLE
			{
				PREF_NODE_EDITOR_WIRE_STYLE_BEZIER;
				PREF_NODE_EDITOR_WIRE_STYLE_STRAIGHT;
			}
			CUSTOMGUI QUICKTABRADIO;
		}
	}
}
