CONTAINER prefsuvcolor
{
	NAME prefsuvcolor;
	SCALE_V;
	
	GROUP PREF_UVCOLOR_MAIN_GROUP
	{
		DEFAULT 1;
		COLUMNS 1;	
		SCALE_V;
		
		LISTVIEW PREF_UVCOLOR_LIST { COLOR; SCALE_V;}
		SEPARATOR { }
		COLOR PREF_UVCOLOR_COLORS { OPEN; }

		SEPARATOR { LINE; }

		BUTTON PREF_UVCOLOR_RESET { }
	}
}
