CONTAINER Prefsview
{
	NAME Prefsview;

	GROUP PREFS_VIEW_GROUP
	{
		DEFAULT 1;

		SEPARATOR PREFS_VIEW_PERFORMANCE_GROUP {}
		BOOL PREF_VIEW_FULLANIMREDRAW	{ ANIM OFF; }
		BOOL PREF_VIEW_REALTIME { ANIM OFF; }
		BOOL PREF_VIEW_REALTIME_MATERIAL{ ANIM OFF; }

		SEPARATOR PREFS_VIEW_HANDLES_GROUP {}
		GROUP
		{
			COLUMNS 2;
			DEFAULT 1;

			REAL PREF_VIEW_OBJECTAXIS_SCALE { UNIT PERCENT; MIN 0.0; MAX 400.0; ANIM OFF; }
			BOOL PREF_VIEW_DISPLAYFILTER_HANDLEBANDS { ANIM OFF; }
			REAL PREF_VIEW_ROTATION_CIRCLE { UNIT PERCENT; MIN 0.0; MAX 300.0; ANIM OFF; }
			BOOL PREF_VIEW_ROTATION_BANDS { ANIM OFF; }
			REAL PREF_VIEW_ROTBAND_SCALE { UNIT PERCENT; MIN 0.0; MAX 400.0; ANIM OFF; }
			BOOL PREF_VIEW_EDGE_POINTS { ANIM OFF; }
			LONG PREF_VIEW_POINT_HANDLE_SIZE { MIN 0; MAX 10; ANIM OFF; }
			LONG PREF_VIEW_POINT_SELECTED_SIZE { MIN 0; MAX 10; ANIM OFF; }
			LONG PREF_VIEW_EDGE_UNSELECTED_SIZE { MIN 0; MAX 10; ANIM OFF; }
			LONG PREF_VIEW_EDGE_SELECTED_SIZE { MIN 0; MAX 10; ANIM OFF; }
			LONG PREF_VIEW_SPLINE_WIDTH { MIN 0; MAX 10; ANIM OFF; }
			REAL PREF_VIEW_NORMALS_SCALE { UNIT PERCENT; MIN 0.0; MAX 400.0; ANIM OFF; }
		}

		SEPARATOR PREFS_VIEW_VP_ELEMENTS_GROUP {}
		GROUP
		{
			COLUMNS 2;
			DEFAULT 1;

			LONG PREF_VIEW_EDITOR_AXIS_POS { ANIM OFF; CYCLE { PREF_VIEW_AXIS_POS_OFF; PREF_VIEW_AXIS_POS_BL; PREF_VIEW_AXIS_POS_TL; PREF_VIEW_AXIS_POS_TR; PREF_VIEW_AXIS_POS_BR; } }
			STATICTEXT {}

			LONG PREF_VIEW_EDITOR_AXIS_TYPE { ANIM OFF;CYCLE { PREF_VIEW_AXIS_TYPE_WORLD; PREF_VIEW_AXIS_TYPE_OBJECT; } }
			STATICTEXT {}

			REAL PREF_VIEW_EDIT_AXIS_SCALE { ANIM OFF; UNIT PERCENT; MIN 0.0; MAX 400.0; }
			STATICTEXT {}

			BOOL PREF_VIEW_EDIT_AXIS_TEXT { ANIM OFF; }
			STATICTEXT {}

			BOOL PREF_VIEW_DISPLAYFILTER_GRADIENT { ANIM OFF; }
			STATICTEXT {}
		}

		SEPARATOR PREFS_VIEW_OBJ_SELECTION_GROUP {}
		GROUP
		{
			COLUMNS 2;
			DEFAULT 1;

			BOOL PREF_VIEW_OUTLINES { ANIM OFF; }
			REAL PREF_VIEW_OUTLINE_WIDTH { MIN 1.0; MAX 10.0; ANIM OFF; }
			BOOL PREF_VIEW_SEL_BOUNDINGBOXSELECTION { ANIM OFF; }
			BOOL PREF_VIEW_SEL_BOUNDINGBOXSELECTION_CHILDREN { ANIM OFF; }
			BOOL PREF_VIEW_SEL_WIREFRAMESELECTION { ANIM OFF; }
			BOOL PREF_VIEW_SEL_WIREFRAMESELECTION_CHILDREN { ANIM OFF; }
		}

		SEPARATOR PREFS_VIEW_SYSTEM_GROUP {}
		REAL PREF_VIEW_MONITORASPECT { ANIM OFF; MIN 0.0; STEP 0.01; }
		BOOL PREF_VIEW_LINEAR_WORKFLOW { ANIM OFF; }
		COLORPROFILE PREF_VIEW_COLORPROFILE { DISPLAYMODE; SCALE_H; }
		STATICTEXT PREF_VIEW_WARNING {}
	}
}
