CONTAINER Prefsunits
{
	NAME Prefsunits;
	GROUP PREF_UNITS_MAIN_GROUP
	{
		DEFAULT 1;
		COLUMNS 2;
		
		SEPARATOR PREFS_UNITS_BASICGR {}
		STATICTEXT {JOINENDSCALE;}

		BOOL PREF_UNITS_DISPLAY	{ ANIM OFF; }
		STATICTEXT {}

		BOOL PREF_UNITS_AUTOCONVERT	{ ANIM OFF; }		
		STATICTEXT {}

		LONG PREF_UNITS_BASIC 
		{ 
			ANIM OFF; 
			CYCLE 
			{ 
				PREF_UNITS_BASIC_KM;
				PREF_UNITS_BASIC_M;
				PREF_UNITS_BASIC_CM;
				PREF_UNITS_BASIC_MM;
				PREF_UNITS_BASIC_MICRO;
				PREF_UNITS_BASIC_NM;
				PREF_UNITS_BASIC_MILE;
				PREF_UNITS_BASIC_YARD;
				PREF_UNITS_BASIC_FOOT;
				PREF_UNITS_BASIC_INCH;

			} 
		}
		STATICTEXT {}
		
		SEPARATOR {LINE;}
		STATICTEXT {JOINENDSCALE;}

		LONG PREF_UNITS_ANIMATION 
		{ 
			ANIM OFF; 
			CYCLE 
			{ 
				PREF_UNITS_ANIM_FPS;
				PREF_UNITS_ANIM_SEC;
				PREF_UNITS_ANIM_SMPTE;
			} 
		}
		STATICTEXT {}

		SEPARATOR PREFS_UNITS_COLORGROUP {}
		STATICTEXT {JOINENDSCALE;}

		BOOL PREF_UNITS_COLORMODE_REMEMBER_LAST_LAYOUT { ANIM OFF; }
		STATICTEXT {}

		LONG PREF_UNITS_RGBRANGE
	  {
			ANIM OFF;
			CYCLE
			{
			  PREF_UNIT_RANGE_PERCENT; 
			  PREF_UNIT_RANGE_255;
			  PREF_UNIT_RANGE_65535;
			}
		}
		STATICTEXT {}

		GROUP PREF_UNITS_COLORMODEGROUP
		{
			DEFAULT 1;
			COLUMNS 2;

			BOOL PREF_UNITS_COLORMODE_COMPACT { ANIM OFF; }
			STATICTEXT {}

			LONG PREF_UNITS_COLORMODE_SPECIAL
	  	{
				ANIM OFF; PARENTCOLLAPSE;
				CYCLE
				{
			  	PREF_UNITS_COLORMODE_SPECIAL_DISABLED; 
			  	PREF_UNITS_COLORMODE_SPECIAL_COLORWHEEL;
			  	PREF_UNITS_COLORMODE_SPECIAL_SPECTRUM;
			  	PREF_UNITS_COLORMODE_SPECIAL_PICTURE;
				}
			}
			STATICTEXT {}

			LONG PREF_UNITS_COLORMODE_WHEEL_SIZE
			{
				ANIM OFF; PARENTCOLLAPSE PREF_UNITS_COLORMODE_SPECIAL;
				CYCLE
				{
					PREF_UNITS_COLORMODE_SIZE_SMALL;
					PREF_UNITS_COLORMODE_SIZE_MEDIUM;
					PREF_UNITS_COLORMODE_SIZE_LARGE;
				}
			}
			STATICTEXT { PARENTCOLLAPSE PREF_UNITS_COLORMODE_SPECIAL; }

			LONG PREF_UNITS_COLORMODE_WHEEL_SWATCH_SIZE
			{
				ANIM OFF; PARENTCOLLAPSE PREF_UNITS_COLORMODE_SPECIAL;
				CYCLE
				{
					PREF_UNITS_COLORMODE_SIZE_SMALL;
					PREF_UNITS_COLORMODE_SIZE_MEDIUM;
					PREF_UNITS_COLORMODE_SIZE_LARGE;
				}
			}
			STATICTEXT { PARENTCOLLAPSE PREF_UNITS_COLORMODE_SPECIAL; }

			LONG PREF_UNITS_COLORMODE_SPECTRUM_SIZE
			{
				ANIM OFF; PARENTCOLLAPSE PREF_UNITS_COLORMODE_SPECIAL;
				CYCLE
				{
					PREF_UNITS_COLORMODE_SIZE_SMALL;
					PREF_UNITS_COLORMODE_SIZE_MEDIUM;
					PREF_UNITS_COLORMODE_SIZE_LARGE;
				}
			}
			STATICTEXT { PARENTCOLLAPSE PREF_UNITS_COLORMODE_SPECIAL; }

			LONG PREF_UNITS_COLORMODE_PICTURE_SWATCH_SIZE
			{
				ANIM OFF; PARENTCOLLAPSE PREF_UNITS_COLORMODE_SPECIAL;
				CYCLE
				{
					PREF_UNITS_COLORMODE_SIZE_SMALL;
					PREF_UNITS_COLORMODE_SIZE_MEDIUM;
					PREF_UNITS_COLORMODE_SIZE_LARGE;
				}
			}
			STATICTEXT { PARENTCOLLAPSE PREF_UNITS_COLORMODE_SPECIAL; }

			BOOL PREF_UNITS_COLORMODE_RGB { ANIM OFF; PARENTCOLLAPSE; }
			STATICTEXT {}
			
			BOOL PREF_UNITS_COLORMODE_OLD_RGB_SLIDERS { ANIM OFF; PARENTCOLLAPSE PREF_UNITS_COLORMODE_RGB; }
			STATICTEXT { PARENTCOLLAPSE PREF_UNITS_COLORMODE_RGB; }

			BOOL PREF_UNITS_COLORMODE_HSV { ANIM OFF; }
			STATICTEXT {}

			BOOL PREF_UNITS_COLORMODE_KELVIN { ANIM OFF; }
			STATICTEXT {}

			BOOL PREF_UNITS_COLORMODE_MIXER { ANIM OFF; }
			STATICTEXT {}

			BOOL PREF_UNITS_COLORMODE_ALPHA { ANIM OFF; }
			STATICTEXT {}

			BOOL PREF_UNITS_COLORMODE_HEX { ANIM OFF; }
			STATICTEXT {}

			BOOL PREF_UNITS_COLORMODE_SWATCHES { ANIM OFF; PARENTCOLLAPSE; }
			STATICTEXT {}

			BOOL PREF_UNITS_COLORMODE_SWATCHES_SHOWNAMES  { ANIM OFF; PARENTCOLLAPSE PREF_UNITS_COLORMODE_SWATCHES; }
			STATICTEXT { PARENTCOLLAPSE PREF_UNITS_COLORMODE_SWATCHES; }

			LONG PREF_UNITS_COLORMODE_SWATCHES_SWATCH_SIZE
			{
				ANIM OFF; PARENTCOLLAPSE PREF_UNITS_COLORMODE_SWATCHES;
				CYCLE
				{
					PREF_UNITS_COLORMODE_SIZE_SMALL;
					PREF_UNITS_COLORMODE_SIZE_MEDIUM;
					PREF_UNITS_COLORMODE_SIZE_LARGE;
				}
			}
			STATICTEXT { PARENTCOLLAPSE PREF_UNITS_COLORMODE_SWATCHES; }

			BOOL PREF_UNITS_COLORMODE_LINEAR { ANIM OFF; }
			STATICTEXT {}

			STATICTEXT PREF_UNITS_COLORMODE_INFO { }
			STATICTEXT {}
		}

		SEPARATOR PREFS_UNITS_GRADIENTGROUP {}
		STATICTEXT {JOINENDSCALE;}

		LONG PREF_UNITS_GRADIENT_SIZE
		{
			ANIM OFF;
			CYCLE
			{
				PREF_UNITS_GRADIENT_SIZE_SMALL;
				PREF_UNITS_GRADIENT_SIZE_MEDIUM;
				PREF_UNITS_GRADIENT_SIZE_LARGE;
			}
		}
		STATICTEXT {}

		BOOL PREF_UNITS_GRADIENT_SELECTION_HANDLES { ANIM OFF; }
		STATICTEXT {}

		SEPARATOR PREFS_UNITS_ALPHAGROUP {}
		STATICTEXT {JOINENDSCALE;}

		LONG PREF_UNITS_ALPHA_GRIDCOLOR
		{
			ANIM OFF;
			CYCLE
			{
				PREF_UNITS_ALPHA_GRIDCOLOR_LIGHT;
				PREF_UNITS_ALPHA_GRIDCOLOR_MEDIUM;
				PREF_UNITS_ALPHA_GRIDCOLOR_DARK;
			}
		}
		STATICTEXT {}
	}
}
