CONTAINER Prefsopengl
{
	NAME Prefsopengl;
	SCALE_V;
	
	GROUP PREF_OPENGL_MAIN_GROUP
	{
		DEFAULT 1;
		SCALE_V;

		//GROUP
		//{
			//BOOL PREF_LEGACY_VIEWPORT { ANIM OFF; }
		//}
		GROUP
		{
			GROUP
			{
				COLUMNS 2;

				LONG PREF_OPENGL_TEXTUREMODE
				{
					ANIM OFF;
					CYCLE
					{
						PREF_OPENGL_TEXTUREMODE_NEAREST;
						PREF_OPENGL_TEXTUREMODE_LINEAR;
						PREF_OPENGL_TEXTUREMODE_MIPMAP;
					}
				}
				STATICTEXT{}

				LONG PREF_OPENGL_ANTIALIAS
				{
					ANIM OFF;
					CYCLE
					{
					}
				}
				STATICTEXT {}

				BOOL PREF_OPENGL_UVEDITOR_ANTIALIAS { ANIM OFF; }
				STATICTEXT{}
				LONG PREF_OPENGL_MAXTRANS  { MIN 0; MAX 10;}
				STATICTEXT{}
				LONG PREF_OPENGL_MAXLIGHT  { ANIM OFF;  MIN 1; MAX 1000;}
				STATICTEXT{}
				LONG PREF_OPENGL_MAXSHAD  { ANIM OFF;  MIN 0; MAX 100;}
				STATICTEXT{}
				BOOL PREF_OPENGL_USE_SHADER_CACHE { ANIM OFF; }
				STATICTEXT{}
				BOOL PREF_OPENGL_VIEWPORT_DITHERING { ANIM OFF; }
				STATICTEXT{}
			}

			GROUP PREF_OPENGL_GROUP_MINIMAL_SETTINGS
			{
				SEPARATOR {}
				GROUP
				{
					COLUMNS 2;
					BUTTON PREF_OPENGL_LOAD_PREVIOUS {}
					BUTTON PREF_OPENGL_SAVE_AS_STARTUP {}
				}
			}

			SEPARATOR PREF_OPENGL_INFO {}
			GROUP
			{
				STATICTEXT PREF_OPENGL_INFO_GPU { BOLD; SCALE_H; PADDING 20; SPACING -10; }
				STATICTEXT PREF_OPENGL_INFO_API { BOLD; SCALE_H; PADDING 20; SPACING -10; }
				STATICTEXT PREF_OPENGL_INFO_VERSION { BOLD; SCALE_H; PADDING 20; SPACING -10; }
				STATICTEXT PREF_OPENGL_INFO_GLSL_VERSION { BOLD; SCALE_H; PADDING 20; SPACING -10; }
			}
		}

		SEPARATOR PREF_OPENGL_NOTICE { SCALE_H; }
		STRING PREF_OPENGL_WARNING { ANIM OFF; CUSTOMGUI MULTISTRING; WORDWRAP; READONLY; SCALE_V; NO_BORDER; NO_DARK_BACKGROUND; }
	}
}
