CONTAINER Dprojobjs
{
	NAME Dprojobjs;
	
	GROUP ID_CA_PROJOBJS_GROUP_OPTIONS
	{
		BOOL ID_CA_PROJOBJS_CHILDREN { }
		
		LONG ID_CA_PROJOBJS_DEF_MODE
		{
			CYCLE
			{
				ID_CA_PROJOBJS_MODE_PROJECT;
				ID_CA_PROJOBJS_MODE_SURFACE;
				ID_CA_PROJOBJS_MODE_POINTS;
				ID_CA_PROJOBJS_MODE_COLLIDE;				
			}
		}
				
		LONG ID_CA_PROJOBJS_CTRL_MODE
		{
			CYCLE
			{
				ID_CA_PROJOBJS_MODE_PROJECT;
				ID_CA_PROJOBJS_MODE_SURFACE;
				ID_CA_PROJOBJS_MODE_POINTS;
				ID_CA_PROJOBJS_MODE_COLLIDE;					
			}
		}
		
		LONG ID_CA_PROJOBJS_SHIFT_MODE
		{
			CYCLE
			{
				ID_CA_PROJOBJS_MODE_PROJECT;
				ID_CA_PROJOBJS_MODE_SURFACE;
				ID_CA_PROJOBJS_MODE_POINTS;
				ID_CA_PROJOBJS_MODE_COLLIDE;				
			}
		}		
	}
}