CONTAINER Dxrefadd
{
	NAME Dxrefadd;
	
	GROUP ID_CA_XREFADD_GROUP_OPTIONS
	{
		COLUMNS 2;
		
		BOOL ID_CA_XREFADD_ENCAPSULATED { }
		BOOL ID_CA_XREFADD_GENERATOR { }
		
		LONG ID_CA_XREFADD_NAMESPACE
		{
			CYCLE
			{
				ID_CA_XREFADD_NAMESPACE_NONE;
				ID_CA_XREFADD_NAMESPACE_REFNAME;
				ID_CA_XREFADD_NAMESPACE_CUSTOM;
			}
		}
		BOOL ID_CA_XREFADD_NAMESPACE_AUTO { }
		
		STRING ID_CA_XREFADD_PREFIX { }	
		STRING ID_CA_XREFADD_NAMESPACE_SEP { }
	}
	
	GROUP ID_CA_XREFADD_GROUP_IMPORT
	{
		BOOL ID_CA_XREFADD_ANIM { PARENTCOLLAPSE; }
		BASETIME ID_CA_XREFADD_ANIM_FRAME { PARENTCOLLAPSE ID_CA_XREFADD_ANIM; }
		BASETIME ID_CA_XREFADD_ANIM_OFFSET { PARENTCOLLAPSE ID_CA_XREFADD_ANIM; }
		REAL ID_CA_XREFADD_ANIM_SCALE { PARENTCOLLAPSE ID_CA_XREFADD_ANIM; STEP 0.1; }

		BOOL ID_CA_XREFADD_MATERIALS { }
		BOOL ID_CA_XREFADD_POINTCACHE { }
	}
	
	GROUP ID_CA_XREFADD_GROUP_MODIFY
	{
		LAYOUTGROUP; COLUMNS 2;

		GROUP
		{
			BOOL ID_CA_XREFADD_HIERARCHY { }

			BOOL ID_CA_XREFADD_PSR { PARENTCOLLAPSE; }
			LONG ID_CA_XREFADD_PSR_MODE { PARENTCOLLAPSE ID_CA_XREFADD_PSR; CYCLE { ID_CA_XREFADD_PSR_MODE_ABS; ID_CA_XREFADD_PSR_MODE_REL; } }
		
			BOOL ID_CA_XREFADD_PARAMETERS { PARENTCOLLAPSE; }
			LONG ID_CA_XREFADD_PARAMETERS_MODE { PARENTCOLLAPSE ID_CA_XREFADD_PARAMETERS; CYCLE { ID_CA_XREFADD_PSR_MODE_ABS; ID_CA_XREFADD_PSR_MODE_REL; } }
		}

		GROUP
		{
			BOOL ID_CA_XREFADD_USERDATA { PARENTCOLLAPSE; }	
			LONG ID_CA_XREFADD_USERDATA_MODE { PARENTCOLLAPSE ID_CA_XREFADD_USERDATA; CYCLE { ID_CA_XREFADD_PSR_MODE_ABS; ID_CA_XREFADD_PSR_MODE_REL; } }

			BOOL ID_CA_XREFADD_POINTS { PARENTCOLLAPSE; }
			LONG ID_CA_XREFADD_POINTS_MODE { PARENTCOLLAPSE ID_CA_XREFADD_POINTS; CYCLE { ID_CA_XREFADD_PSR_MODE_ABS; ID_CA_XREFADD_PSR_MODE_REL; } }
		}
	}
	
	GROUP ID_CA_XREFADD_GROUP_FILE
	{
		COLUMNS 2;
		
		BOOL ID_CA_XREFADD_RELATIVE { }
		BOOL ID_CA_XREFADD_INCREMENTAL { }
	}

	GROUP ID_CA_XREFADD_PIVOT_GROUP
	{
		GROUP
		{
			LAYOUTGROUP; COLUMNS 3;
			GROUP { VECTOR ID_CA_XREFADD_PIVOT_POS { UNIT METER;  CUSTOMGUI SUBDESCRIPTION; } }
			GROUP { VECTOR ID_CA_XREFADD_PIVOT_SCL { STEP 0.01;   CUSTOMGUI SUBDESCRIPTION; } }
			GROUP { VECTOR ID_CA_XREFADD_PIVOT_ROT { UNIT DEGREE; CUSTOMGUI SUBDESCRIPTION; } }
		}
	}
}