CONTAINER Ocacorrectiondeformer
{
	NAME Ocacorrectiondeformer;
	INCLUDE Obase;
	
	GROUP ID_OBJECTPROPERTIES
	{
		GROUP
		{
			COLUMNS 2;
			
			BOOL ID_CA_CORRECTION_DEFORMER_OBJECT_LOCK { }
			BOOL ID_CA_CORRECTION_DEFORMER_OBJECT_SCALE { }
		}
		
		
		LONG ID_CA_CORRECTION_DEFORMER_OBJECT_MAP
		{
			CYCLE
			{
				ID_CA_CORRECTION_DEFORMER_OBJECT_MAP_UV;
				ID_CA_CORRECTION_DEFORMER_OBJECT_MAP_NEAREST;
				ID_CA_CORRECTION_DEFORMER_OBJECT_MAP_NORMAL;
			}
		}
		
		LINK ID_CA_CORRECTION_DEFORMER_OBJECT_UV { ACCEPT { Tuvw; } }
		
		REAL ID_CA_CORRECTION_DEFORMER_OBJECT_STRENGTH { UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		
		GROUP
		{
			COLUMNS 3;
			
			BUTTON ID_CA_CORRECTION_DEFORMER_OBJECT_UPDATE { }
			BUTTON ID_CA_CORRECTION_DEFORMER_OBJECT_FREEZE { }
			BUTTON ID_CA_CORRECTION_DEFORMER_OBJECT_RESET { }
		}
	}
}
