CONTAINER ocacapsulefalloff
{
	NAME	ocacapsulefalloff;
	INCLUDE Ofalloff_standard;

	GROUP FALLOFF_GROUPFALLOFF
	{
		REAL ID_CA_CAPSULEFALLOFF_OBJECT_TOP { UNIT PERCENT; MIN 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		REAL ID_CA_CAPSULEFALLOFF_OBJECT_BOTTOM { UNIT PERCENT; MIN 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
	}
}
