CONTAINER Ocameshdeformer
{
	NAME Ocameshdeformer;
	INCLUDE Obase;
	
	GROUP ID_OBJECTPROPERTIES
	{		
		GROUP
		{
			COLUMNS 4;
			
			BUTTON ID_CA_MESH_DEFORMER_OBJECT_INITIAL { }
			BUTTON ID_CA_MESH_DEFORMER_OBJECT_RESTORE { }
			BOOL ID_CA_MESH_DEFORMER_OBJECT_AUTO { }
			STATICTEXT ID_CA_MESH_DEFORMER_OBJECT_MEM { }
		}
		
		GROUP
		{
			REAL ID_CA_MESH_DEFORMER_OBJECT_STRENGTH { UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		}
		
		GROUP
		{					
			IN_EXCLUDE  ID_CA_MESH_DEFORMER_OBJECT_CAGE_INCLUDE
			{
				NUM_FLAGS 1; INIT_STATE 1; SEND_SELCHNGMSG 1;
				IMAGE_01_ON 1009316; IMAGE_01_OFF 1009320;
				ACCEPT { Obase; };
			}		
		}
		
		GROUP ID_CA_MESH_DEFORMER_GROUP_ADVANCED
		{		
			GROUP
			{
				COLUMNS 2;
				
				REAL ID_CA_MESH_DEFORMER_OBJECT_ACCURACY { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
				LONG ID_CA_MESH_DEFORMER_OBJECT_EXTERNAL
				{
					CYCLE
					{
						ID_CA_MESH_DEFORMER_OBJECT_EXTERNAL_IGNORE;
						ID_CA_MESH_DEFORMER_OBJECT_EXTERNAL_SURFACE;
						ID_CA_MESH_DEFORMER_OBJECT_EXTERNAL_SURFACE_AREA;
					}
				}
			}	
			
			BOOL ID_CA_MESH_DEFORMER_OBJECT_FIT { HIDDEN; }		
		}		
	}
}
