CONTAINER Ocamuscledeformer
{
	NAME Ocamuscledeformer;
	INCLUDE Obase;
	
	GROUP ID_OBJECTPROPERTIES
	{
		GROUP
		{	
			REAL ID_CA_MUSCLE_DEFORMER_PULL_STRENGTH { UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			REAL ID_CA_MUSCLE_DEFORMER_SLIDE_STRENGTH { UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			REAL ID_CA_MUSCLE_DEFORMER_FAT_OFFSET { UNIT METER; MIN 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }			
		}
			
		GROUP ID_CA_MUSCLE_DEFORMER_PULL_GROUP
		{
			DEFAULT 1;
			
			GROUP
			{
				COLUMNS 2;
				
				BUTTON ID_CA_MUSCLE_DEFORMER_INIT { }
				BUTTON ID_CA_MUSCLE_DEFORMER_FREE { }
				
				REAL ID_CA_MUSCLE_DEFORMER_DISTANCE { UNIT METER; MIN 0.0; MAXSLIDER 1000.0; CUSTOMGUI REALSLIDER; SCALE_H; }
				STATICTEXT { JOINENDSCALE; }
			}
				
			LONG ID_CA_MUSCLE_DEFORMER_PULL_MODE
			{
				PARENTCOLLAPSE;
			
				CYCLE
				{
					ID_CA_MUSCLE_DEFORMER_PULL_MODE_REL;
					ID_CA_MUSCLE_DEFORMER_PULL_MODE_ABS;
				}
			}
			
			SPLINE ID_CA_MUSCLE_DEFORMER_PULL_CURVE
			{
				PARENTCOLLAPSE ID_CA_MUSCLE_DEFORMER_PULL_MODE;
			}					
		}
		
		GROUP ID_CA_MUSCLE_DEFORMER_STRETCH_GROUP
		{
			COLUMNS 1; DEFAULT 1;
			
			BOOL ID_CA_MUSCLE_DEFORMER_STRETCH { }
			REAL ID_CA_MUSCLE_DEFORMER_STRETCH_STRENGTH { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
			LONG ID_CA_MUSCLE_DEFORMER_STRETCH_ITERATIONS { MIN 1; }
			REAL ID_CA_MUSCLE_DEFORMER_STRETCH_STIFFNESS { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		}
	}
	
	GROUP ID_CA_MUSCLE_DEFORMER_MUSCLES_GROUP
	{	
		SCALE_V;
		
		IN_EXCLUDE ID_CA_MUSCLE_DEFORMER_OBJECT_LIST
		{
			NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 1; SCALE_V; ANIM OFF;
			ACCEPT { 1026224; };
		}		
	}	
}