CONTAINER Ocasquash
{
	NAME Ocasquash;
	INCLUDE Obase;
	
	GROUP ID_OBJECTPROPERTIES
	{
		REAL ID_CA_SQUASH_OBJECT_HIGH { UNIT METER; MIN 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		REAL ID_CA_SQUASH_OBJECT_CENTER {UNIT PERCENT; MIN -100.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		REAL ID_CA_SQUASH_OBJECT_LOW { UNIT METER; MINSLIDER -100.0; MAX 0.0; CUSTOMGUI REALSLIDER; }
		REAL ID_CA_SQUASH_OBJECT_ASPECT { UNIT PERCENT; MINSLIDER -100.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		REAL ID_CA_SQUASH_OBJECT_FACTOR { UNIT PERCENT; MIN 0.0; MAXSLIDER 1000.0; CUSTOMGUI REALSLIDER; }
		REAL ID_CA_SQUASH_OBJECT_STRENGTH { UNIT PERCENT; MIN 0.0; MAXSLIDER 1000.0; CUSTOMGUI REALSLIDER; }		
		REAL ID_CA_SQUASH_OBJECT_SMOOTH_START { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		REAL ID_CA_SQUASH_OBJECT_SMOOTH_END { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		REAL ID_CA_SQUASH_OBJECT_CURVATURE { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		
		GROUP
		{
			COLUMNS 2;
			
			LONG ID_CA_SQUASH_OBJECT_CURVATURE_TYPE
			{
				CYCLE
				{
					ID_CA_SQUASH_OBJECT_CURVATURE_TYPE_SQUARE;
					ID_CA_SQUASH_OBJECT_CURVATURE_TYPE_CUBE;
					ID_CA_SQUASH_OBJECT_CURVATURE_TYPE_QUAD;
					ID_CA_SQUASH_OBJECT_CURVATURE_TYPE_CUSTOM;
					ID_CA_SQUASH_OBJECT_CURVATURE_TYPE_SPLINE;
				}
			}
			
			REAL ID_CA_SQUASH_OBJECT_CURVATURE_CUSTOM { MIN 0.0; }
		}
		
		SPLINE ID_CA_SQUASH_OBJECT_CURVATURE_SPLINE {  }
		SEPARATOR		{ LINE; }
		BUTTON	ID_CA_SQUASH_OBJECT_FITTOPARENT	{  }
	}
}
