CONTAINER Ocasmoothdeformer
{
	NAME Ocasmoothdeformer;
	INCLUDE Obase;
	
	GROUP ID_OBJECTPROPERTIES
	{
		GROUP
		{
			COLUMNS 2;
			
			BUTTON ID_CA_SMOOTHING_DEFORMER_OBJECT_INITIAL { }
			BUTTON ID_CA_SMOOTHING_DEFORMER_OBJECT_RESTORE { }
		}
		STATICTEXT ID_CA_SMOOTHING_DEFORMER_OBJECT_MEM { }
		
		REAL ID_CA_SMOOTHING_DEFORMER_OBJECT_STRENGTH { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
	
		LONG ID_CA_SMOOTHING_DEFORMER_OBJECT_TYPE
		{
			CYCLE
			{
				ID_CA_SMOOTHING_DEFORMER_OBJECT_TYPE_RELAX;
				ID_CA_SMOOTHING_DEFORMER_OBJECT_TYPE_SMOOTH;
				ID_CA_SMOOTHING_DEFORMER_OBJECT_TYPE_STRETCH;
			}
		}
		
		LONG ID_CA_SMOOTHING_DEFORMER_OBJECT_ITERATIONS { MIN 1; }
		REAL ID_CA_SMOOTHING_DEFORMER_OBJECT_STIFFNESS { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		
		BOOL ID_CA_SMOOTHING_DEFORMER_OBJECT_DELTA_LOCK { }
		LINK ID_CA_SMOOTHING_DEFORMER_OBJECT_STIFF_MAP { ACCEPT { 5682; } }
	}
}
