CONTAINER Ocaskin
{
	NAME Ocaskin;
	INCLUDE Obase;
		
	GROUP Obaselist
	{
		SEPARATOR { LINE; }

		PRIORITY ID_CA_SKIN_OBJECT_PRIORITY { ANIM OFF; NOCAMERA; }
	}
	
	GROUP ID_OBJECTPROPERTIES
	{
		GROUP
		{
			COLUMNS 2;

			LONG ID_CA_SKIN_OBJECT_COORD
			{
				FIT_H; SCALE_H;

				CYCLE
				{
					ID_CA_SKIN_OBJECT_COORD_MESH;
					ID_CA_SKIN_OBJECT_COORD_JOINTS;
					ID_CA_SKIN_OBJECT_COORD_DEFORMER;
				}
			}
			
			LONG ID_CA_SKIN_OBJECT_TYPE
			{
				FIT_H; SCALE_H;

				CYCLE
				{
					ID_CA_SKIN_OBJECT_TYPE_LINEAR;
					ID_CA_SKIN_OBJECT_TYPE_QUAT;
					ID_CA_SKIN_OBJECT_TYPE_BLENDED;
				}
			}
			
			LONG ID_CA_SKIN_OBJECT_TRANSFORM
			{
				FIT_H; SCALE_H;

				CYCLE
				{
					ID_CA_SKIN_OBJECT_TRANSFORM_BONES;
					ID_CA_SKIN_OBJECT_TRANSFORM_OBJECT;
				}
			}
			
			LONG ID_CA_SKIN_OBJECT_SCALING
			{
				FIT_H; SCALE_H;

				CYCLE
				{
					ID_CA_SKIN_OBJECT_SCALING_NONE;
					ID_CA_SKIN_OBJECT_SCALING_UNIFORM;
					ID_CA_SKIN_OBJECT_SCALING_BONE_AXIS;
					ID_CA_SKIN_OBJECT_SCALING_BONE_VOLUME;
				}
			}
		}

		REAL ID_CA_SKIN_OBJECT_BLEND_STRENGTH { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		LINK ID_CA_SKIN_OBJECT_BLEND_MAP { ACCEPT { 5682; } }
	}

	GROUP ID_CA_SKIN_OBJECT_INC_GROUP
	{
		SCALE_V;

		GROUP
		{
			COLUMNS 2;

			LONG ID_CA_SKIN_OBJECT_INCEXC
			{
				CYCLE
				{
					ID_CA_SKIN_OBJECT_INCEXC_INCLUDE;
					ID_CA_SKIN_OBJECT_INCEXC_EXCLUDE;
				}
			}

			BOOL ID_CA_SKIN_OBJECT_FORCE { }
		}

		IN_EXCLUDE  ID_CA_SKIN_OBJECT_INCLUDE
		{
			NUM_FLAGS 0; INIT_STATE 1; SCALE_V;

			ACCEPT { 5156; Tbase; };
		}
	}
}
