CONTAINER Tcaconstraint
{
	NAME Tcaconstraint;
	INCLUDE Texpression;

	GROUP Obaselist
	{
		GROUP ID_CA_CONSTRAINT_TAG_GROUP
		{
			COLUMNS 2; DEFAULT 1;
			
			BOOL ID_CA_CONSTRAINT_TAG_PSR { }
			BOOL ID_CA_CONSTRAINT_TAG_PARENT { }
			
			BOOL ID_CA_CONSTRAINT_TAG_UP { }
			BOOL ID_CA_CONSTRAINT_TAG_AIM { }
			
			BOOL ID_CA_CONSTRAINT_TAG_CLAMP { }
			BOOL ID_CA_CONSTRAINT_TAG_SPRING { }
			
			BOOL ID_CA_CONSTRAINT_TAG_MIRROR { }
			STATICTEXT { NEWLINE; }
			
			BOOL ID_CA_CONSTRAINT_TAG_COLLISION { HIDDEN; }
			
			SEPARATOR { LINE; }
			STATICTEXT { JOINENDSCALE; }
			
			BOOL ID_CA_CONSTRAINT_TAG_FRAMEUPDATE { ANIM OFF; }
			GROUP
			{
				COLUMNS 2;
				BUTTON ID_CA_CONSTRAINT_TAG_SET_INITIAL_STATE { }
				BOOL ID_CA_CONSTRAINT_TAG_USE_INITIAL_STATE { ANIM OFF; }
			}
			GROUP ID_CA_CONSTRAINT_TAG_INITIAL_SATE_GROUP
			{
				LAYOUTGROUP; COLUMNS 3;
				GROUP { VECTOR ID_CA_CONSTRAINT_INITIAL_STATE_VECTOR_P { UNIT METER; CUSTOMGUI SUBDESCRIPTION; ANIM OFF; } }
				GROUP { VECTOR ID_CA_CONSTRAINT_INITIAL_STATE_VECTOR_S { CUSTOMGUI SUBDESCRIPTION; ANIM OFF; } }
				GROUP { VECTOR ID_CA_CONSTRAINT_INITIAL_STATE_VECTOR_R { UNIT DEGREE; CUSTOMGUI SUBDESCRIPTION; ANIM OFF; } }
			}
		}
	}



	GROUP ID_CA_CONSTRAINT_TAG_PSR_GROUP
	{
		REAL ID_CA_CONSTRAINT_TAG_PSR_TWEIGHT { UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 0.1; CUSTOMGUI REALSLIDER; FIT_H; SCALE_H; }
	
		GROUP ID_CA_CONSTRAINT_TAG_PSR_OFFSET_GROUP
		{
			BOOL ID_CA_CONSTRAINT_TAG_PSR_MAINTAIN { }

			GROUP
			{
				LAYOUTGROUP; COLUMNS 3;

				GROUP { VECTOR ID_CA_CONSTRAINT_TAG_PSR_P_OFFSET { UNIT METER; CUSTOMGUI SUBDESCRIPTION; } }
				GROUP { VECTOR ID_CA_CONSTRAINT_TAG_PSR_S_OFFSET { CUSTOMGUI SUBDESCRIPTION; } }
				GROUP { VECTOR ID_CA_CONSTRAINT_TAG_PSR_R_OFFSET { UNIT DEGREE; CUSTOMGUI SUBDESCRIPTION; } }
			}
		}

		GROUP ID_CA_CONSTRAINT_TAG_PSR_CONSTRAIN_GROUP
		{
			COLUMNS 3;
			
			BOOL ID_CA_CONSTRAINT_TAG_PSR_CONSTRAIN_P_X { }
			BOOL ID_CA_CONSTRAINT_TAG_PSR_CONSTRAIN_S_X { }
			BOOL ID_CA_CONSTRAINT_TAG_PSR_CONSTRAIN_R_X { }

			BOOL ID_CA_CONSTRAINT_TAG_PSR_CONSTRAIN_P_Y { }
			BOOL ID_CA_CONSTRAINT_TAG_PSR_CONSTRAIN_S_Y { }
			BOOL ID_CA_CONSTRAINT_TAG_PSR_CONSTRAIN_R_Y { }

			BOOL ID_CA_CONSTRAINT_TAG_PSR_CONSTRAIN_P_Z { }
			BOOL ID_CA_CONSTRAINT_TAG_PSR_CONSTRAIN_S_Z { }
			BOOL ID_CA_CONSTRAINT_TAG_PSR_CONSTRAIN_R_Z { }
		}


		GROUP ID_CA_CONSTRAINT_TAG_PSR_TARGETS_GROUP
		{
			DEFAULT 1;

			GROUP
			{
				COLUMNS 3;
				
				BOOL ID_CA_CONSTRAINT_TAG_LOCAL_P { }
				BOOL ID_CA_CONSTRAINT_TAG_LOCAL_S { }
				BOOL ID_CA_CONSTRAINT_TAG_LOCAL_R { }				
			}
			
			GROUP
			{
				COLUMNS 2;

				BUTTON ID_CA_CONSTRAINT_TAG_PSR_ADD { FIT_H; SCALE_H; }
				BUTTON ID_CA_CONSTRAINT_TAG_PSR_REMOVE { FIT_H; SCALE_H; }
			}

			SEPARATOR { }

			LINK ID_CA_CONSTRAINT_TAG_PSR_LINK { HIDDEN; ACCEPT { Obase; } }		
			REAL ID_CA_CONSTRAINT_TAG_PSR_WEIGHT { HIDDEN; UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 0.1; CUSTOMGUI REALSLIDER; FIT_H; SCALE_H; }

			BOOL ID_CA_CONSTRAINT_TAG_PSR_P { HIDDEN; }
			BOOL ID_CA_CONSTRAINT_TAG_PSR_S { HIDDEN; }
			BOOL ID_CA_CONSTRAINT_TAG_PSR_R { HIDDEN; }
		}
	}

	GROUP ID_CA_CONSTRAINT_TAG_AIM_GROUP
	{
		REAL ID_CA_CONSTRAINT_TAG_AIM_TWEIGHT { UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 0.1; CUSTOMGUI REALSLIDER; FIT_H; SCALE_H; }

		GROUP ID_CA_CONSTRAINT_TAG_AIM_OFFSET_GROUP
		{
			BOOL ID_CA_CONSTRAINT_TAG_AIM_MAINTAIN { }

			VECTOR ID_CA_CONSTRAINT_TAG_AIM_OFFSET { UNIT DEGREE; SCALE_H; }
		}

		GROUP ID_CA_CONSTRAINT_TAG_AIM_CONSTRAIN_GROUP
		{
			COLUMNS 3;

			BOOL ID_CA_CONSTRAINT_TAG_AIM_CONSTRAIN_X { }
			BOOL ID_CA_CONSTRAINT_TAG_AIM_CONSTRAIN_Y { }
			BOOL ID_CA_CONSTRAINT_TAG_AIM_CONSTRAIN_Z { }
		}

		GROUP ID_CA_CONSTRAINT_TAG_AIM_TARGETS_GROUP
		{
			DEFAULT 1;

			GROUP
			{
				COLUMNS 2; 

				BUTTON ID_CA_CONSTRAINT_TAG_AIM_ADD { FIT_H; SCALE_H; }
				BUTTON ID_CA_CONSTRAINT_TAG_AIM_REMOVE { FIT_H; SCALE_H; }
			}

			SEPARATOR { }

			LINK ID_CA_CONSTRAINT_TAG_AIM_LINK { HIDDEN; ACCEPT { Obase; } }		
			REAL ID_CA_CONSTRAINT_TAG_AIM_WEIGHT { HIDDEN; UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 0.1; CUSTOMGUI REALSLIDER; FIT_H; SCALE_H; }

			LONG ID_CA_CONSTRAINT_TAG_AIM_AXIS
			{
				FIT_H; SCALE_H; HIDDEN;

				CYCLE
				{
					ID_CA_CONSTRAINT_TAG_AXIS_XP;
					ID_CA_CONSTRAINT_TAG_AXIS_XM;
					ID_CA_CONSTRAINT_TAG_AXIS_YP;
					ID_CA_CONSTRAINT_TAG_AXIS_YM;
					ID_CA_CONSTRAINT_TAG_AXIS_ZP;
					ID_CA_CONSTRAINT_TAG_AXIS_ZM;
				}
			}
		}
	}

	GROUP ID_CA_CONSTRAINT_TAG_UP_GROUP
	{
		REAL ID_CA_CONSTRAINT_TAG_UP_TWEIGHT { UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 0.1; CUSTOMGUI REALSLIDER; FIT_H; SCALE_H; }

		GROUP ID_CA_CONSTRAINT_TAG_UP_OFFSET_GROUP
		{
			BOOL ID_CA_CONSTRAINT_TAG_UP_MAINTAIN { }

			VECTOR ID_CA_CONSTRAINT_TAG_UP_OFFSET { UNIT DEGREE; SCALE_H; }
		}

		GROUP ID_CA_CONSTRAINT_TAG_UP_CONSTRAIN_GROUP
		{
			COLUMNS 3;

			BOOL ID_CA_CONSTRAINT_TAG_UP_CONSTRAIN_X { }
			BOOL ID_CA_CONSTRAINT_TAG_UP_CONSTRAIN_Y { }
			BOOL ID_CA_CONSTRAINT_TAG_UP_CONSTRAIN_Z { }
		}

		GROUP ID_CA_CONSTRAINT_TAG_UP_TARGETS_GROUP
		{
			DEFAULT 1;

			GROUP
			{
				COLUMNS 2; 

				BUTTON ID_CA_CONSTRAINT_TAG_UP_ADD { FIT_H; SCALE_H; }
				BUTTON ID_CA_CONSTRAINT_TAG_UP_REMOVE { FIT_H; SCALE_H; }
			}

			SEPARATOR { }

			LONG ID_CA_CONSTRAINT_TAG_UP_AXIS
			{
				HIDDEN;

				CYCLE
				{
					ID_CA_CONSTRAINT_TAG_AXIS_XP;
					ID_CA_CONSTRAINT_TAG_AXIS_XM;
					ID_CA_CONSTRAINT_TAG_AXIS_YP;
					ID_CA_CONSTRAINT_TAG_AXIS_YM;
					ID_CA_CONSTRAINT_TAG_AXIS_ZP;
					ID_CA_CONSTRAINT_TAG_AXIS_ZM;
				}
			}

			LONG ID_CA_CONSTRAINT_TAG_UP_ROT_AXIS
			{
				HIDDEN;

				CYCLE
				{
					ID_CA_CONSTRAINT_TAG_AXIS_XP;
					ID_CA_CONSTRAINT_TAG_AXIS_XM;
					ID_CA_CONSTRAINT_TAG_AXIS_YP;
					ID_CA_CONSTRAINT_TAG_AXIS_YM;
					ID_CA_CONSTRAINT_TAG_AXIS_ZP;
					ID_CA_CONSTRAINT_TAG_AXIS_ZM;
				}
			}

			LINK ID_CA_CONSTRAINT_TAG_UP_LINK { HIDDEN; ACCEPT { Obase; } }		
			REAL ID_CA_CONSTRAINT_TAG_UP_WEIGHT { HIDDEN; UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 0.1; CUSTOMGUI REALSLIDER; FIT_H; SCALE_H; }
		}
	}

	GROUP ID_CA_CONSTRAINT_TAG_PARENT_GROUP
	{
		REAL ID_CA_CONSTRAINT_TAG_PARENT_TWEIGHT { UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 0.1; CUSTOMGUI REALSLIDER; FIT_H; SCALE_H; }
	
		GROUP
		{
			COLUMNS 4;
		
			BOOL ID_CA_CONSTRAINT_TAG_PARENT_FROZEN { }
			BOOL ID_CA_CONSTRAINT_TAG_PARENT_RESET { }
			BOOL ID_CA_CONSTRAINT_TAG_PARENT_INTERACTIVEOFFSET { ANIM OFF; }
		}
		
		GROUP ID_CA_CONSTRAINT_TAG_PARENT_OFFSET_GROUP
		{
			BOOL ID_CA_CONSTRAINT_TAG_PARENT_MAINTAIN { }

			GROUP
			{
				LAYOUTGROUP; COLUMNS 3;

				GROUP { VECTOR ID_CA_CONSTRAINT_TAG_PARENT_P_OFFSET { UNIT METER; CUSTOMGUI SUBDESCRIPTION; } }
				GROUP { VECTOR ID_CA_CONSTRAINT_TAG_PARENT_S_OFFSET { CUSTOMGUI SUBDESCRIPTION; } }
				GROUP { VECTOR ID_CA_CONSTRAINT_TAG_PARENT_R_OFFSET { UNIT DEGREE; CUSTOMGUI SUBDESCRIPTION; } }
			}
		}

		GROUP ID_CA_CONSTRAINT_TAG_PARENT_TARGETS_GROUP
		{
			DEFAULT 1;

			GROUP
			{
				COLUMNS 2; 

				BUTTON ID_CA_CONSTRAINT_TAG_PARENT_ADD { FIT_H; SCALE_H; }
				BUTTON ID_CA_CONSTRAINT_TAG_PARENT_REMOVE { FIT_H; SCALE_H; }
			}

			SEPARATOR { }

			LINK ID_CA_CONSTRAINT_TAG_PARENT_LINK { HIDDEN; ACCEPT { Obase; } }		
			REAL ID_CA_CONSTRAINT_TAG_PARENT_WEIGHT { HIDDEN; UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 0.1; CUSTOMGUI REALSLIDER; FIT_H; SCALE_H; }

			BOOL ID_CA_CONSTRAINT_TAG_PARENT_P { HIDDEN; }
			BOOL ID_CA_CONSTRAINT_TAG_PARENT_S { HIDDEN; }
			BOOL ID_CA_CONSTRAINT_TAG_PARENT_R { HIDDEN; }

			GROUP ID_CA_CONSTRAINT_TAG_PARENT_LOCALTRANSFORM_GROUP
			{
				HIDDEN;

				GROUP
				{ 
					HIDDEN;
					LAYOUTGROUP; COLUMNS 3;
					GROUP { VECTOR ID_CA_CONSTRAINT_TAG_PARENT_P_LOCALTRANFORM { HIDDEN; UNIT METER; } }
					GROUP { VECTOR ID_CA_CONSTRAINT_TAG_PARENT_S_LOCALTRANFORM { HIDDEN; } }
					GROUP 
					{ 
						VECTOR ID_CA_CONSTRAINT_TAG_PARENT_R_LOCALTRANFORM { HIDDEN; UNIT DEGREE; } 
						LONG ID_CA_CONSTRAINT_TAG_PARENT_LOCALTRANFORM_ROTORDER
						{
							ANIM OFF;
							CYCLE
							{
								ID_CA_CONSTRAINT_TAG_PARENT_LOCALTRANFORM_ROTORDER_HPB;
								-1;
								ID_CA_CONSTRAINT_TAG_PARENT_LOCALTRANFORM_ROTORDER_XYZ;
								ID_CA_CONSTRAINT_TAG_PARENT_LOCALTRANFORM_ROTORDER_XZY;
								ID_CA_CONSTRAINT_TAG_PARENT_LOCALTRANFORM_ROTORDER_YXZ;
								ID_CA_CONSTRAINT_TAG_PARENT_LOCALTRANFORM_ROTORDER_YZX;
								ID_CA_CONSTRAINT_TAG_PARENT_LOCALTRANFORM_ROTORDER_ZXY;
								ID_CA_CONSTRAINT_TAG_PARENT_LOCALTRANFORM_ROTORDER_ZYX;
							}
						}
					}				
				}
			}
		}

		GROUP
		{
			COLUMNS 2; 

			LONG ID_CA_CONSTRAINT_TAG_PARENT_LOCALTRANFORM_UPDATEBUTTON 
			{ 
				CUSTOMGUI CYCLEBUTTON; 
				FIT_H; 
				SCALE_H; 
				CYCLE 
				{
					ID_CA_CONSTRAINT_TAG_PARENT_LOCALTRANFORM_UPDATEALL;
					ID_CA_CONSTRAINT_TAG_PARENT_LOCALTRANFORM_UPDATEPARENT;
				}
			}
			LONG ID_CA_CONSTRAINT_TAG_PARENT_LOCALTRANFORM_RECORDBUTTON 
			{ 
				CUSTOMGUI CYCLEBUTTON; 
				FIT_H; 
				SCALE_H; 
				CYCLE 
				{
					ID_CA_CONSTRAINT_TAG_PARENT_LOCALTRANFORM_RECORDOPTIMIZED;
					ID_CA_CONSTRAINT_TAG_PARENT_LOCALTRANFORM_RECORDALL;
				}
			}
		}



	}

	GROUP ID_CA_CONSTRAINT_TAG_CLAMP_GROUP
	{
		REAL ID_CA_CONSTRAINT_TAG_CLAMP_TWEIGHT { UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 0.1; CUSTOMGUI REALSLIDER; FIT_H; SCALE_H; }

		GROUP
		{
			COLUMNS 2;

			BOOL ID_CA_CONSTRAINT_TAG_CLAMP_SHOW { }
			COLOR ID_CA_CONSTRAINT_TAG_CLAMP_COLOR { SCALE_H; }
		}

		GROUP ID_CA_CONSTRAINT_TAG_CLAMP_TARGETS_GROUP
		{
			DEFAULT 1;

			GROUP
			{
				COLUMNS 2; 

				BUTTON ID_CA_CONSTRAINT_TAG_CLAMP_ADD { FIT_H; SCALE_H; }
				BUTTON ID_CA_CONSTRAINT_TAG_CLAMP_REMOVE { FIT_H; SCALE_H; }
			}

			SEPARATOR { }

			LINK ID_CA_CONSTRAINT_TAG_CLAMP_LINK { HIDDEN; ACCEPT { Obase; Tbase; } }
			BOOL ID_CA_CONSTRAINT_TAG_CLAMP_STICK { HIDDEN; }
			BOOL ID_CA_CONSTRAINT_TAG_CLAMP_NORMALS { HIDDEN; }

			REAL ID_CA_CONSTRAINT_TAG_CLAMP_WEIGHT { HIDDEN; UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 0.1; CUSTOMGUI REALSLIDER; FIT_H; SCALE_H; }
			REAL ID_CA_CONSTRAINT_TAG_CLAMP_DISTANCE { HIDDEN; UNIT METER; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 1.0; CUSTOMGUI REALSLIDER; FIT_H; SCALE_H; }

			LONG ID_CA_CONSTRAINT_TAG_CLAMP_TO
			{
				FIT_H; SCALE_H; HIDDEN;

				CYCLE
				{
					ID_CA_CONSTRAINT_TAG_CLAMP_TO_ORIGIN;
					ID_CA_CONSTRAINT_TAG_CLAMP_TO_AXIS;
					ID_CA_CONSTRAINT_TAG_CLAMP_TO_PLANE;
					ID_CA_CONSTRAINT_TAG_CLAMP_TO_POINT;
					ID_CA_CONSTRAINT_TAG_CLAMP_TO_SURFACE;
					ID_CA_CONSTRAINT_TAG_CLAMP_TO_SPLINE;
					ID_CA_CONSTRAINT_TAG_CLAMP_TO_BOUNDS;
				}
			}

			LONG ID_CA_CONSTRAINT_TAG_CLAMP_MODE
			{
				FIT_H; SCALE_H; HIDDEN;

				CYCLE
				{
					ID_CA_CONSTRAINT_TAG_CLAMP_MODE_MIN;
					ID_CA_CONSTRAINT_TAG_CLAMP_MODE_MAX;
					ID_CA_CONSTRAINT_TAG_CLAMP_MODE_FIX;
					ID_CA_CONSTRAINT_TAG_CLAMP_MODE_LOCK;
				}
			}

			LONG ID_CA_CONSTRAINT_TAG_CLAMP_ALIGN
			{
				FIT_H; SCALE_H; HIDDEN;

				CYCLE
				{
					ID_CA_CONSTRAINT_TAG_AXIS_XP;
					ID_CA_CONSTRAINT_TAG_AXIS_XM;
					ID_CA_CONSTRAINT_TAG_AXIS_YP;
					ID_CA_CONSTRAINT_TAG_AXIS_YM;
					ID_CA_CONSTRAINT_TAG_AXIS_ZP;
					ID_CA_CONSTRAINT_TAG_AXIS_ZM;
				}
			}

			LONG ID_CA_CONSTRAINT_TAG_CLAMP_ALIGN_TO
			{
				FIT_H; SCALE_H; HIDDEN;

				CYCLE
				{
					ID_CA_CONSTRAINT_TAG_CLAMP_ALIGN_NONE;
					ID_CA_CONSTRAINT_TAG_CLAMP_ALIGN_TO_CONSTRAINT;
					ID_CA_CONSTRAINT_TAG_CLAMP_ALIGN_TO_NORMAL;
					ID_CA_CONSTRAINT_TAG_CLAMP_ALIGN_TO_TANGENT;
					ID_CA_CONSTRAINT_TAG_CLAMP_ALIGN_TO_PLYNORMAL;
				}
			}

			LONG ID_CA_CONSTRAINT_TAG_CLAMP_AXIS
			{
				FIT_H; SCALE_H; HIDDEN;

				CYCLE
				{
					ID_CA_CONSTRAINT_TAG_AXIS_X;
					ID_CA_CONSTRAINT_TAG_AXIS_Y;
					ID_CA_CONSTRAINT_TAG_AXIS_Z;
				}
			}

			LONG ID_CA_CONSTRAINT_TAG_CLAMP_PLANE
			{
				HIDDEN; FIT_H; SCALE_H;

				CYCLE
				{
					ID_CA_CONSTRAINT_TAG_PLANE_XY;
					ID_CA_CONSTRAINT_TAG_PLANE_YZ;
					ID_CA_CONSTRAINT_TAG_PLANE_XZ;
					ID_CA_CONSTRAINT_TAG_PLANE_MXY;
					ID_CA_CONSTRAINT_TAG_PLANE_MYZ;
					ID_CA_CONSTRAINT_TAG_PLANE_MXZ;
				}
			}
		}
	}

	GROUP ID_CA_CONSTRAINT_TAG_SPRING_GROUP
	{
		GROUP
		{
			COLUMNS 2;
	
			REAL ID_CA_CONSTRAINT_TAG_SPRING_TWEIGHT { UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 0.1; CUSTOMGUI REALSLIDER; FIT_H; SCALE_H; }
			STATICTEXT { JOINENDSCALE; }
		
			REAL ID_CA_CONSTRAINT_TAG_SPRING_DRAG { UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 0.1; CUSTOMGUI REALSLIDER; FIT_H; SCALE_H; }
			REAL ID_CA_CONSTRAINT_TAG_SPRING_GRAVITY { UNIT METER; }
			
		}
		
		GROUP ID_CA_CONSTRAINT_TAG_SPRING_OFFSET_GROUP
		{
			GROUP
			{
				LAYOUTGROUP; COLUMNS 3;

				GROUP { VECTOR ID_CA_CONSTRAINT_TAG_SPRING_P_OFFSET { UNIT METER; CUSTOMGUI SUBDESCRIPTION; } }
				GROUP { VECTOR ID_CA_CONSTRAINT_TAG_SPRING_S_OFFSET { CUSTOMGUI SUBDESCRIPTION; } }
				GROUP { VECTOR ID_CA_CONSTRAINT_TAG_SPRING_R_OFFSET { UNIT DEGREE; CUSTOMGUI SUBDESCRIPTION; } }
			}
		}
						
		GROUP ID_CA_CONSTRAINT_TAG_SPRING_TARGETS_GROUP
		{
			DEFAULT 1;

			GROUP
			{
				COLUMNS 2; 

				BUTTON ID_CA_CONSTRAINT_TAG_SPRING_ADD { FIT_H; SCALE_H; }
				BUTTON ID_CA_CONSTRAINT_TAG_SPRING_REMOVE { FIT_H; SCALE_H; }
			}

			SEPARATOR { }

			BOOL ID_CA_CONSTRAINT_TAG_SPRING_P { HIDDEN; }
			BOOL ID_CA_CONSTRAINT_TAG_SPRING_S { HIDDEN; }
			BOOL ID_CA_CONSTRAINT_TAG_SPRING_R { HIDDEN; }
			
			LINK ID_CA_CONSTRAINT_TAG_SPRING_LINK { HIDDEN; ACCEPT { Obase; } }		
			REAL ID_CA_CONSTRAINT_TAG_SPRING_WEIGHT { HIDDEN; UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 0.1; CUSTOMGUI REALSLIDER; FIT_H; SCALE_H; }

			REAL ID_CA_CONSTRAINT_TAG_SPRING_LENGTH { HIDDEN; UNIT METER; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 1.0; CUSTOMGUI REALSLIDER; FIT_H; SCALE_H; }
			REAL ID_CA_CONSTRAINT_TAG_SPRING_STIFFNESS { HIDDEN; UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 0.1; CUSTOMGUI REALSLIDER; FIT_H; SCALE_H; }
		}
	}
	
	GROUP ID_CA_CONSTRAINT_TAG_MIRROR_GROUP
	{
		REAL ID_CA_CONSTRAINT_TAG_MIRROR_TWEIGHT { UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 0.1; CUSTOMGUI REALSLIDER; FIT_H; SCALE_H; }

		GROUP ID_CA_CONSTRAINT_TAG_MIRROR_OFFSET_GROUP
		{
			GROUP
			{
				LAYOUTGROUP; COLUMNS 3;

				GROUP { VECTOR ID_CA_CONSTRAINT_TAG_MIRROR_P_OFFSET { UNIT METER; CUSTOMGUI SUBDESCRIPTION; } }
				GROUP { VECTOR ID_CA_CONSTRAINT_TAG_MIRROR_R_OFFSET { UNIT DEGREE; CUSTOMGUI SUBDESCRIPTION; } }
			}
		}

		GROUP ID_CA_CONSTRAINT_TAG_MIRROR_TARGETS_GROUP
		{
			DEFAULT 1;

			GROUP
			{
				COLUMNS 2;

				BUTTON ID_CA_CONSTRAINT_TAG_MIRROR_ADD { SCALE_H; }
				BUTTON ID_CA_CONSTRAINT_TAG_MIRROR_REMOVE { SCALE_H; }
			}

			SEPARATOR { }

			LINK ID_CA_CONSTRAINT_TAG_MIRROR_LINK { HIDDEN; ACCEPT { Obase; } }		
			REAL ID_CA_CONSTRAINT_TAG_MIRROR_WEIGHT { HIDDEN; UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 0.1; CUSTOMGUI REALSLIDER; FIT_H; SCALE_H; }

			BOOL ID_CA_CONSTRAINT_TAG_MIRROR_P { HIDDEN; }
			BOOL ID_CA_CONSTRAINT_TAG_MIRROR_R { HIDDEN; }
			LINK ID_CA_CONSTRAINT_TAG_MIRROR_ORIGIN_LINK { HIDDEN; ACCEPT { Obase; } }
			LONG ID_CA_CONSTRAINT_TAG_MIRROR_ORIGIN
			{
				HIDDEN;
				CYCLE
				{
					ID_CA_CONSTRAINT_TAG_MIRROR_ORIGIN_WORLD;
					ID_CA_CONSTRAINT_TAG_MIRROR_ORIGIN_ROOT;
					ID_CA_CONSTRAINT_TAG_MIRROR_ORIGIN_PARENT;
					ID_CA_CONSTRAINT_TAG_MIRROR_ORIGIN_OBJECT;
				}
			}
			LONG ID_CA_CONSTRAINT_TAG_MIRROR_PLANE
			{
				HIDDEN;
				CYCLE
				{
					ID_CA_CONSTRAINT_TAG_MIRROR_PLANE_XY;
					ID_CA_CONSTRAINT_TAG_MIRROR_PLANE_YZ;
					ID_CA_CONSTRAINT_TAG_MIRROR_PLANE_ZX;
				}
			}
			LONG ID_CA_CONSTRAINT_TAG_MIRROR_AXIS
			{
				HIDDEN;
				CYCLE
				{
					ID_CA_CONSTRAINT_TAG_MIRROR_AXIS_XY;
					ID_CA_CONSTRAINT_TAG_MIRROR_AXIS_YZ;
					ID_CA_CONSTRAINT_TAG_MIRROR_AXIS_ZX;
				}
			}
		}
	}
	
	GROUP ID_CA_CONSTRAINT_TAG_COLLISION_GROUP
	{
		REAL ID_CA_CONSTRAINT_TAG_COLLISION_TWEIGHT { UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 0.1; CUSTOMGUI REALSLIDER; FIT_H; SCALE_H; }

		GROUP ID_CA_CONSTRAINT_TAG_COLLISION_TARGETS_GROUP
		{
			DEFAULT 1;

			GROUP
			{
				SCALE_V; COLUMNS 1;
				
				IN_EXCLUDE  ID_CA_CONSTRAINT_TAG_COLLISION_TARGETS
				{
					OPEN;
					
					NUM_FLAGS 2; INIT_STATE 3; SEND_SELCHNGMSG 1; SCALE_V;
					IMAGE_01_ON 1009316; IMAGE_01_OFF 1009320;
					IMAGE_02_ON 300000231; IMAGE_02_OFF 300000230;
					ACCEPT { Obase; Tbase; };
				}
			}
		}
	}	
}
