CONTAINER Tcageomcache
{
	NAME Tcageomcache;
	INCLUDE Texpression;

	GROUP ID_TAGPROPERTIES
	{
		GROUP
		{
			COLUMNS 2;
			
			BOOL ID_CA_GEOMCACHE_TAG_ENABLE { }
			BOOL ID_CA_GEOMCACHE_TAG_DEFORMER { }
			
			BOOL ID_CA_GEOMCACHE_TAG_PSR { }
			STATICTEXT { NEWLINE; }
		
			SEPARATOR { LINE; }
			STATICTEXT { JOINENDSCALE; }
			
			REAL ID_CA_GEOMCACHE_TAG_CACHE_STRENGTH { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINENDSCALE; }
			
			BOOL ID_CA_GEOMCACHE_TAG_COMPRESSED { SCALE_H; ANIM OFF; }
			STATICTEXT ID_CA_GEOMCACHE_TAG_INFO2 { SCALE_H; }
			
			BUTTON ID_CA_GEOMCACHE_TAG_STORE { SCALE_H; }
			BUTTON ID_CA_GEOMCACHE_TAG_RESTORE { SCALE_H; }

			BUTTON ID_CA_GEOMCACHE_TAG_CALCULATE { SCALE_H; }			
			BUTTON ID_CA_GEOMCACHE_TAG_UPDATE { SCALE_H; }
		
			BUTTON ID_CA_GEOMCACHE_TAG_DELETE { SCALE_H; }
			STATICTEXT { DUMMY; SCALE_H; }

			BUTTON ID_CA_GEOMCACHE_TAG_CACHE_LOAD { SCALE_H; }
			BUTTON ID_CA_GEOMCACHE_TAG_CACHE_SAVE { SCALE_H; }
			
			BOOL ID_CA_GEOMCACHE_TAG_CACHE_AUTOTIME { SCALE_H; ANIM OFF; }
			STATICTEXT { DUMMY; SCALE_H; }

			BASETIME ID_CA_GEOMCACHE_TAG_CACHE_START { SCALE_H; ANIM OFF; }
			BASETIME ID_CA_GEOMCACHE_TAG_CACHE_STOP  { SCALE_H; ANIM OFF; }
			
			BASETIME ID_CA_GEOMCACHE_TAG_CACHE_OFFSET { SCALE_H; ANIM OFF; }			
			REAL ID_CA_GEOMCACHE_TAG_CACHE_TIMESCALE { UNIT PERCENT; }
			
			LONG ID_CA_GEOMCACHE_TAG_CACHE_LOOP { MIN 1; }
			REAL ID_CA_GEOMCACHE_TAG_CACHE_LOOP_BLEND { UNIT PERCENT; MIN 0.0; MAX 100.0; }

			SEPARATOR { }
			STATICTEXT { JOINENDSCALE; }

			LONG ID_CA_GEOMCACHE_TAG_CACHE_LIMIT { MIN 1; MAX 1000; ANIM OFF; }
			STATICTEXT ID_CA_GEOMCACHE_TAG_TEXT_LIMIT {}
		}
	}
}
