CONTAINER Tcaikspline
{
	NAME Tcaikspline;
	INCLUDE Texpression;

	GROUP ID_TAGPROPERTIES
	{
		REAL ID_CA_IKSPLINE_TAG_STRENGTH { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }

		GROUP
		{
			COLUMNS 2;

			LONG ID_CA_IKSPLINE_TAG_TYPE
			{
				FIT_H; SCALE_H;

				CYCLE
				{
					ID_CA_IKSPLINE_TAG_TYPE_NONE;
					ID_CA_IKSPLINE_TAG_TYPE_FIT;
					ID_CA_IKSPLINE_TAG_TYPE_EQUAL;
					ID_CA_IKSPLINE_TAG_TYPE_REL;
				}
			}

			LONG ID_CA_IKSPLINE_TAG_AIM
			{
				FIT_H; SCALE_H;
				
				CYCLE
				{
					ID_CA_IKSPLINE_TAG_AIM_TANGENT;
					ID_CA_IKSPLINE_TAG_AIM_JOINT;
				}
			}
				
			LONG ID_CA_IKSPLINE_TAG_ALIGN_TANGENT
			{
				FIT_H; SCALE_H;

				CYCLE
				{
					ID_CA_IKSPLINE_TAG_ALIGN_X;
					ID_CA_IKSPLINE_TAG_ALIGN_Y;
					ID_CA_IKSPLINE_TAG_ALIGN_Z;
				}
			}
			LONG ID_CA_IKSPLINE_TAG_ALIGN_AXIS
			{
				FIT_H; SCALE_H;

				CYCLE
				{
					ID_CA_IKSPLINE_TAG_ALIGN_X;
					ID_CA_IKSPLINE_TAG_ALIGN_Y;
					ID_CA_IKSPLINE_TAG_ALIGN_Z;
				}
			}

			LINK ID_CA_IKSPLINE_TAG_SPLINE { ACCEPT { Ospline; } }
			STATICTEXT { JOINEND; }

			LINK ID_CA_IKSPLINE_TAG_END { ACCEPT { Obase; } }
			STATICTEXT { JOINEND; }

			LONG ID_CA_IKSPLINE_TAG_TWIST_TYPE
			{
				CYCLE
				{
					ID_CA_IKSPLINE_TAG_TWIST_TYPE_NONE;
					ID_CA_IKSPLINE_TAG_TWIST_TYPE_WORLD;
					ID_CA_IKSPLINE_TAG_TWIST_TYPE_LOCAL;
				}
			}
			LONG ID_CA_IKSPLINE_TAG_TWIST_AXIS
			{
				CYCLE
				{
					ID_CA_IKSPLINE_TAG_TWIST_AXIS_H;
					ID_CA_IKSPLINE_TAG_TWIST_AXIS_P;
					ID_CA_IKSPLINE_TAG_TWIST_AXIS_B;
				}
			}

			SPLINE ID_CA_IKSPLINE_TAG_TWIST_CURVE {  }
			STATICTEXT { JOINEND; }
		}
	}

	GROUP ID_CA_IKSPLINE_HANDLE_GROUP
	{
		COLUMNS 1; DEFAULT 1;

		GROUP
		{
			COLUMNS 3;

			BUTTON ID_CA_IKSPLINE_HANDLE_ADD { FIT_H; SCALE_H; }
			BUTTON ID_CA_IKSPLINE_HANDLE_CREATE { FIT_H; SCALE_H; }
			BUTTON ID_CA_IKSPLINE_HANDLE_REMOVE { FIT_H; SCALE_H; }
		}

		SEPARATOR { }

		GROUP ID_CA_IKSPLINE_HANDLE_LINKS_GROUP
		{
			COLUMNS 1;

			LONG ID_CA_IKSPLINE_HANDLE_INDEX { HIDDEN; MIN 0; }
			LINK ID_CA_IKSPLINE_HANDLE_LINK { HIDDEN; ACCEPT { Obase; } }
			BOOL ID_CA_IKSPLINE_HANDLE_TWIST { HIDDEN; }
			REAL ID_CA_IKSPLINE_HANDLE_LENGTH { HIDDEN; UNIT METER; MIN 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			BOOL ID_CA_IKSPLINE_HANDLE_OFFSET { HIDDEN; }
		}
	}

	GROUP ID_CA_IKSPLINE_DISPLAY_GROUP
	{
		LONG ID_CA_IKSPLINE_DISPLAY_MODE
		{
			HIDDEN;

			CYCLE
			{
				ID_CA_IKSPLINE_DISPLAY_MODE_OFF;
				ID_CA_IKSPLINE_DISPLAY_MODE_ACTIVE;
				ID_CA_IKSPLINE_DISPLAY_MODE_OBJECT;
				ID_CA_IKSPLINE_DISPLAY_MODE_ALWAYS;
			}
		}

		//BOOL ID_CA_IKSPLINE_DISPLAY_HANDLE_LINES { }
		BOOL ID_CA_IKSPLINE_DISPLAY_TANGENT { }

		//COLOR ID_CA_IKSPLINE_DISPLAY_LINES_COL { }
		COLOR ID_CA_IKSPLINE_DISPLAY_TANGENT_COL { }
	}
}
