CONTAINER Tcarigpart
{
	NAME Tcarigpart;
	INCLUDE Tbase;

	GROUP ID_TAGPROPERTIES
	{
		COLUMNS 1;
		
		GROUP
		{
			COLUMNS 2;
		
			LONG ID_CA_RIGPART_TAG_TYPE
			{
				SCALE_H; ANIM OFF;
				
				CYCLE
				{
					ID_CA_RIGPART_TAG_TYPE_NONE;
					-1;
					ID_CA_RIGPART_TAG_TYPE_PELVIS~1022792;
					ID_CA_RIGPART_TAG_TYPE_LIMB~1022793;
					ID_CA_RIGPART_TAG_TYPE_SPINE~1022794;
					ID_CA_RIGPART_TAG_TYPE_HAND~1022956;
					ID_CA_RIGPART_TAG_TYPE_FOOT~1022957;
					ID_CA_RIGPART_TAG_TYPE_DIGIT~1022795;
					ID_CA_RIGPART_TAG_TYPE_HEAD~1022796;
					ID_CA_RIGPART_TAG_TYPE_TAIL~1022797;
					ID_CA_RIGPART_TAG_TYPE_WING~1022798;
					ID_CA_RIGPART_TAG_TYPE_GROUP~1022792;
					ID_CA_RIGPART_TAG_TYPE_CONTROLLER~1022941;
					ID_CA_RIGPART_TAG_TYPE_COMPONENT~1022292;
					ID_CA_RIGPART_TAG_TYPE_CHARACTER~1021433;
					ID_CA_RIGPART_TAG_TYPE_LEG~1026942;
					ID_CA_RIGPART_TAG_TYPE_EYE~1026943;
					ID_CA_RIGPART_TAG_TYPE_EAR~1026944;
					ID_CA_RIGPART_TAG_TYPE_NOSE~1026945;
					ID_CA_RIGPART_TAG_TYPE_LIPS~1026946;
					ID_CA_RIGPART_TAG_TYPE_MOUTH~1026947;
					-1;
					ID_CA_RIGPART_TAG_TYPE_CUSTOM;
				}
			}
			STRING ID_CA_RIGPART_TAG_TYPE_NAME {  ANIM OFF; }
			
			LONG ID_CA_RIGPART_TAG_CHARACTER_TYPE
			{
				HIDDEN; ANIM OFF;
				
				CYCLE
				{					
					ID_CA_RIGPART_TAG_CHARACTER_TYPE_NONE;
					-1;
					ID_CA_RIGPART_TAG_CHARACTER_TYPE_BIPED~1021433;
					ID_CA_RIGPART_TAG_CHARACTER_TYPE_QUAD~1022962;
					ID_CA_RIGPART_TAG_CHARACTER_TYPE_INSECT~1022963;
					ID_CA_RIGPART_TAG_CHARACTER_TYPE_WING~1022964;
					ID_CA_RIGPART_TAG_CHARACTER_TYPE_AMPHIBIAN~1022965;
					ID_CA_RIGPART_TAG_CHARACTER_TYPE_ALIEN~1022966;
					ID_CA_RIGPART_TAG_CHARACTER_TYPE_FISH~1022967;
					ID_CA_RIGPART_TAG_CHARACTER_TYPE_REPTILE~1022968;
					ID_CA_RIGPART_TAG_CHARACTER_TYPE_FACE~1022970;
					ID_CA_RIGPART_TAG_CHARACTER_TYPE_TENTACLE~1022971;
					-1;
					ID_CA_RIGPART_TAG_CHARACTER_TYPE_CUSTOM~1022972;
				}
			}
			STRING ID_CA_RIGPART_TAG_CHARACTER_TYPE_NAME { HIDDEN; ANIM OFF; }

			STRING ID_CA_RIGPART_TAG_PART_NAME { SCALE_H; ANIM OFF; }
			STATICTEXT { JOINENDSCALE; }
			
			STRING ID_CA_RIGPART_TAG_DISPLAY_NAME { SCALE_H; ANIM OFF; }
			STRING ID_CA_RIGPART_TAG_SUBTYPE_NAME { SCALE_H; ANIM OFF; }

			TEXTURE ID_CA_RIGPART_TAG_PART_ICON { SCALE_H; ANIM OFF; }
			STATICTEXT { JOINENDSCALE; }
		}

		GROUP ID_CA_RIGPART_TAG_GROUP_CONTROLS
		{	
			COLUMNS 1; DEFAULT 1;
						
			BOOL ID_CA_RIGPART_TAG_CONTROLLER_COLOR { ANIM OFF; HIDDEN; }
			
			LINK ID_CA_RIGPART_TAG_CONTROLLER_TARGET { ANIM OFF; ACCEPT { Obase; } }
			
			IN_EXCLUDE  ID_CA_RIGPART_TAG_USER_DATA_LIST
			{
				NUM_FLAGS 1; INIT_STATE 0; SEND_SELCHNGMSG 1; ANIM OFF; 
				IMAGE_01_ON 1009316; IMAGE_01_OFF 1009320;
				ACCEPT { Obase; Tbase; };
			}				
		}
		
		GROUP ID_CA_RIGPART_TAG_GROUP_AXES
		{
			COLUMNS 2;	DEFAULT 1; HIDDEN;
			
			LONG ID_CA_RIGPART_TAG_CHARACTER_FACING
			{	
				SCALE_H; ANIM OFF;
				
				CYCLE
				{
					ID_CA_RIGPART_TAG_AXIS_X;
					ID_CA_RIGPART_TAG_AXIS_Y;
					ID_CA_RIGPART_TAG_AXIS_Z;
					ID_CA_RIGPART_TAG_AXIS_NX;
					ID_CA_RIGPART_TAG_AXIS_NY;
					ID_CA_RIGPART_TAG_AXIS_NZ;
				}
			}
					
			LONG ID_CA_RIGPART_TAG_CHARACTER_VERTICAL
			{
				SCALE_H; ANIM OFF;
				
				CYCLE
				{
					ID_CA_RIGPART_TAG_AXIS_X;
					ID_CA_RIGPART_TAG_AXIS_Y;
					ID_CA_RIGPART_TAG_AXIS_Z;
					ID_CA_RIGPART_TAG_AXIS_NX;
					ID_CA_RIGPART_TAG_AXIS_NY;
					ID_CA_RIGPART_TAG_AXIS_NZ;
				}
			}
			
			LONG ID_CA_RIGPART_TAG_CHARACTER_SIZE
			{
				HIDDEN;
				
				CYCLE
				{
					ID_CA_RIGPART_TAG_CHARACTER_SIZE_NONE;
					ID_CA_RIGPART_TAG_CHARACTER_SIZE_AUTO;
					ID_CA_RIGPART_TAG_CHARACTER_SIZE_MANUAL;
				}
			}
			
			REAL ID_CA_RIGPART_TAG_CHARACTER_HEIGHT { UNIT METER; MIN 0.0; HIDDEN; }
			
			BOOL ID_CA_RIGPART_TAG_CHARACTER_NAMING { HIDDEN; }
			STATICTEXT { NEWLINE; }
		}
	
		GROUP ID_CA_RIGPART_TAG_GROUP_TRANSFORM
		{
			LAYOUTGROUP; COLUMNS 3;

			GROUP { VECTOR ID_CA_RIGPART_TAG_TRANS_P { UNIT METER; CUSTOMGUI SUBDESCRIPTION;  ANIM OFF; } }
			GROUP { VECTOR ID_CA_RIGPART_TAG_TRANS_S { CUSTOMGUI SUBDESCRIPTION;  ANIM OFF; } }
			GROUP { VECTOR ID_CA_RIGPART_TAG_TRANS_R { UNIT DEGREE; CUSTOMGUI SUBDESCRIPTION;  ANIM OFF; } }
		}
	}
		
	GROUP ID_CA_RIGPART_TAG_GROUP_INSERT
	{
		COLUMNS 1; SCALE_V;
		
		GROUP
		{
			COLUMNS 1;
				
			LINK ID_CA_RIGPART_TAG_INSERT_CHILD { ANIM OFF; ACCEPT { Obase; } }
			
			GROUP ID_CA_RIGPART_TAG_GROUP_INSERT_USER
			{
				GROUP
				{
					COLUMNS 2;

					BUTTON ID_CA_RIGPART_TAG_CHAIN_INSERT_ADD { SCALE_H; }
					BUTTON ID_CA_RIGPART_TAG_CHAIN_INSERT_REMOVE { SCALE_H; }
				}
								
				GROUP ID_CA_RIGPART_TAG_GROUP_INSERT_CONTROLLER
				{
					COLUMNS 1; HIDDEN;
									
					LINK ID_CA_RIGPART_TAG_CHAIN_OBJECT { ANIM OFF; ACCEPT { Obase; } }
				}

				GROUP ID_CA_RIGPART_TAG_GROUP_INSERT_USER_MULTIPLE
				{
					COLUMNS 2;
									
					LINK ID_CA_RIGPART_TAG_CHAIN_START { ANIM OFF; ACCEPT { Obase; } }
					LINK ID_CA_RIGPART_TAG_CHAIN_END { ANIM OFF; ACCEPT { Obase; } }
						
					LINK ID_CA_RIGPART_TAG_CHAIN_INSERT { ANIM OFF; ACCEPT { Obase; } }
					STATICTEXT { JOINENDSCALE; }
				}
			}
		}
		
		GROUP ID_CA_RIGPART_TAG_GROUP_PARENTS
		{
			COLUMNS 1; DEFAULT 1;
			
			GROUP
			{
				COLUMNS 2; 
				
				BUTTON ID_CA_RIGPART_TAG_PARENT_ADD { SCALE_H; }
				BUTTON ID_CA_RIGPART_TAG_PARENT_REMOVE { SCALE_H; }
			}
			
			GROUP
			{
				COLUMNS 1;
				
				ITEMTREE ID_CA_RIGPART_TAG_PARENT_TREE { SCALE_H; MULTIPLE; COLUMNS 5; HEADERS; ICON; NORENAME; FOLDERS; DRAGDROP; CHECKBOX; }
			}
						
			GROUP
			{
				COLUMNS 2;
				
				LONG ID_CA_RIGPART_TAG_PARENT_TYPE
				{
					HIDDEN; ANIM OFF;
					
					CYCLE
					{
						ID_CA_RIGPART_TAG_PARENT_TYPE_INITIAL;
						ID_CA_RIGPART_TAG_PARENT_TYPE_ANY;
						ID_CA_RIGPART_TAG_PARENT_TYPE_HUB;
						ID_CA_RIGPART_TAG_PARENT_TYPE_PARENT;
						ID_CA_RIGPART_TAG_PARENT_TYPE_PARENT_TYPE;
						ID_CA_RIGPART_TAG_PARENT_TYPE_NAME;
					}
				}
				LINK ID_CA_RIGPART_TAG_PARENT { HIDDEN; ANIM OFF; ACCEPT { Obase; } }
				STRING ID_CA_RIGPART_TAG_PARENT_NAME { ANIM OFF; HIDDEN; }

				COLUMNS 2;
				
				LONG ID_CA_RIGPART_TAG_INSERT_TYPE
				{
					HIDDEN; ANIM OFF;
					
					CYCLE
					{
						ID_CA_RIGPART_TAG_INSERT_TYPE_FIRST;
						ID_CA_RIGPART_TAG_INSERT_TYPE_LAST;
						ID_CA_RIGPART_TAG_INSERT_TYPE_BEFORE;
						ID_CA_RIGPART_TAG_INSERT_TYPE_AFTER;
						ID_CA_RIGPART_TAG_INSERT_TYPE_ACTIVE;
						ID_CA_RIGPART_TAG_INSERT_TYPE_END;
						ID_CA_RIGPART_TAG_INSERT_TYPE_PYTHON;
					}
				}
				LINK ID_CA_RIGPART_TAG_INSERT { ANIM OFF; HIDDEN; ACCEPT { Obase; } }
				STRING ID_CA_RIGPART_TAG_INSERT_NAME { ANIM OFF; HIDDEN; }
				
				LONG ID_CA_RIGPART_TAG_INSERT_RULE
				{
					HIDDEN; ANIM OFF;
					
					CYCLE
					{	
						ID_CA_RIGPART_TAG_INSERT_RULE_ANY;
						ID_CA_RIGPART_TAG_INSERT_RULE_SINGLE;
						ID_CA_RIGPART_TAG_INSERT_RULE_NO_SAMELEVEL;
						ID_CA_RIGPART_TAG_INSERT_RULE_NO_ROOT;
					}
				}
				
				STRING ID_CA_RIGPART_TAG_INSERT_PYTHON { CUSTOMGUI MULTISTRING; SCALE_V; ANIM OFF; PYTHON; HIDDEN; }		
			}

			GROUP ID_CA_RIGPART_TAG_GROUP_INSERT_TRANSFORM
			{
				HIDDEN; COLUMNS 1;
			 
				GROUP ID_CA_RIGPART_TAG_GROUP_INSERT_TRANSFORM_COORDS
				{
					COLUMNS 2;
					
					BOOL ID_CA_RIGPART_TAG_INSERT_LOCAL { ANIM OFF; }
					BOOL ID_CA_RIGPART_TAG_INSERT_LOCAL_PSR { ANIM OFF; }
					BOOL ID_CA_RIGPART_TAG_INSERT_FREEZE { ANIM OFF; }
				}
			 
				GROUP ID_CA_RIGPART_TAG_GROUP_INSERT_TRANSFORM_INHERIT
				{
					COLUMNS 3;
					
					
					BOOL ID_CA_RIGPART_TAG_INSERT_P { ANIM OFF; }
					BOOL ID_CA_RIGPART_TAG_INSERT_S { ANIM OFF; }
					BOOL ID_CA_RIGPART_TAG_INSERT_R { ANIM OFF; }
				}
				
				GROUP ID_CA_RIGPART_TAG_GROUP_INSERT_TRANSFORM_OFFSET
				{
					LAYOUTGROUP; COLUMNS 3;

					GROUP { VECTOR ID_CA_RIGPART_TAG_INSERT_TRANS_P { UNIT METER; CUSTOMGUI SUBDESCRIPTION; ANIM OFF; } }
					GROUP { VECTOR ID_CA_RIGPART_TAG_INSERT_TRANS_S { CUSTOMGUI SUBDESCRIPTION; ANIM OFF; } }
					GROUP { VECTOR ID_CA_RIGPART_TAG_INSERT_TRANS_R { UNIT DEGREE; CUSTOMGUI SUBDESCRIPTION; ANIM OFF; } }
				}
			}
		}
	}
	
	GROUP ID_CA_RIGPART_TAG_GROUP_MIRROR
	{		
		GROUP ID_CA_RIGPART_TAG_GROUP_MIRROR_CONTROLLERS
		{
			COLUMNS 2; HIDDEN;
			
			LONG ID_CA_RIGPART_TAG_MIRROR_CONTROLLER_AXIS
			{
				SCALE_H; ANIM OFF;
				
				CYCLE
				{
					ID_CA_RIGPART_TAG_MIRROR_AXES_NONE;
					ID_CA_RIGPART_TAG_MIRROR_AXES_XY;
					ID_CA_RIGPART_TAG_MIRROR_AXES_YZ;
					ID_CA_RIGPART_TAG_MIRROR_AXES_ZX;
					ID_CA_RIGPART_TAG_MIRROR_AXES_ROTATE;
				}
			}
			BOOL ID_CA_RIGPART_TAG_MIRROR_CONTROLLER_POINTS { SCALE_H; ANIM OFF; }
		}
		
		GROUP ID_CA_RIGPART_TAG_GROUP_MIRROR_COMPONENTS
		{
			COLUMNS 1;
			
			GROUP
			{
				COLUMNS 2;
					
				LONG ID_CA_RIGPART_TAG_MIRROR_PLANE
				{
					SCALE_H; ANIM OFF;
					
					CYCLE
					{
						ID_CA_RIGPART_TAG_MIRROR_PLANE_DEF;
						ID_CA_RIGPART_TAG_MIRROR_PLANE_XY;
						ID_CA_RIGPART_TAG_MIRROR_PLANE_YZ;
						ID_CA_RIGPART_TAG_MIRROR_PLANE_XZ;
					}
				}
				
				LINK ID_CA_RIGPART_TAG_MIRROR_ORIGIN { ANIM OFF; ACCEPT { Obase; } }
			}
			
			SEPARATOR { LINE; }
			
			GROUP
			{
				COLUMNS 2;
				
				BOOL ID_CA_RIGPART_TAG_TYPE_MIRROR { ANIM OFF; }
				LINK ID_CA_RIGPART_TAG_TYPE_MIRROR_LINK { ANIM OFF; ACCEPT { Obase; } }
				
				LINK ID_CA_RIGPART_TAG_TYPE_MIRROR_FROM { ANIM OFF; ACCEPT { Obase; } HIDDEN; }
				STATICTEXT ID_CA_RIGPART_TAG_TYPE_MIRROR_FROM_JOIN { JOINENDSCALE; HIDDEN; }
		
				LONG ID_CA_RIGPART_TAG_MIRROR_AXIS
				{
					ANIM OFF;
				
					CYCLE
					{
						ID_CA_RIGPART_TAG_MIRROR_AXES_NONE;
						ID_CA_RIGPART_TAG_MIRROR_AXES_XY;
						ID_CA_RIGPART_TAG_MIRROR_AXES_YZ;
						ID_CA_RIGPART_TAG_MIRROR_AXES_ZX;
						ID_CA_RIGPART_TAG_MIRROR_AXES_ROTATE;
					}
				}
				BOOL ID_CA_RIGPART_TAG_MIRROR_FREEZE { ANIM OFF; }
				
				BOOL ID_CA_RIGPART_TAG_MIRROR_COL_USE { ANIM OFF; }		
				COLOR ID_CA_RIGPART_TAG_MIRROR_COL { ANIM OFF; }

				BOOL ID_CA_RIGPART_TAG_MIRROR_REPLACE_CASE { ANIM OFF; }
				STATICTEXT { DUMMY; }
						
				STRING ID_CA_RIGPART_TAG_MIRROR_REPLACE { ANIM OFF; }
				STRING ID_CA_RIGPART_TAG_MIRROR_WITH { ANIM OFF; }
			}
			
			GROUP ID_CA_RIGPART_TAG_GROUP_MIRROR_SYMMETRY
			{
				DEFAULT 1; COLUMNS 2;
								
				LONG ID_CA_RIGPART_TAG_MIRROR_SYM
				{
					ANIM OFF;
					
					CYCLE
					{
						ID_CA_RIGPART_TAG_MIRROR_SYM_COMPONENT;
						ID_CA_RIGPART_TAG_MIRROR_SYM_ANY;
						ID_CA_RIGPART_TAG_MIRROR_SYM_SELF;
					}
				}
				BOOL ID_CA_RIGPART_TAG_MIRROR_SYM_NAME { ANIM OFF; }
				
				REAL ID_CA_RIGPART_TAG_MIRROR_SYM_TOL { UNIT METER; MIN 0.0; ANIM OFF; }
				STATICTEXT { DUMMY; }
			}
				
			GROUP ID_CA_RIGPART_TAG_GROUP_MIRROR_OBJECTS
			{
				DEFAULT 1; COLUMNS 1;
				
				GROUP
				{
					COLUMNS 2;
					
					BUTTON ID_CA_RIGPART_TAG_MIRROR_ADD { SCALE_H; }
					BUTTON ID_CA_RIGPART_TAG_MIRROR_REMOVE { SCALE_H; }
				}
				
				GROUP
				{
					COLUMNS 1;
					
					ITEMLIST ID_CA_RIGPART_TAG_MIRROR_LIST { SCALE_H; MULTIPLE; }	
				}
				
				GROUP ID_CA_RIGPART_TAG_GROUP_MIRROR_OBJECTS_CONTROLS
				{
					COLUMNS 2;
				}
				
				LINK ID_CA_RIGPART_TAG_MIRROR_LINK { HIDDEN; ACCEPT { Obase; } }
				LONG ID_CA_RIGPART_TAG_MIRROR_LINK_AXES
				{
					HIDDEN;
					
					CYCLE
					{
						ID_CA_RIGPART_TAG_MIRROR_AXES_NONE;
						ID_CA_RIGPART_TAG_MIRROR_AXES_XY;
						ID_CA_RIGPART_TAG_MIRROR_AXES_YZ;
						ID_CA_RIGPART_TAG_MIRROR_AXES_ZX;
					}
				}
			}
		}
	}
	
	GROUP ID_CA_RIGPART_TAG_GROUP_INCLUDE
	{
		COLUMNS 1; SCALE_V;
		
		GROUP
		{
			COLUMNS 2;
			
			LONG ID_CA_RIGPART_TAG_INCLUDE_SEARCH
			{
				ANIM OFF;
			
				CYCLE
				{
					ID_CA_RIGPART_TAG_INCLUDE_SEARCH_UP_LEVEL;
					ID_CA_RIGPART_TAG_INCLUDE_SEARCH_UP;
					ID_CA_RIGPART_TAG_INCLUDE_SEARCH_DOWN;
					ID_CA_RIGPART_TAG_INCLUDE_SEARCH_UP_DOWN;
					ID_CA_RIGPART_TAG_INCLUDE_SEARCH_FULL;
				}
			}
			
			LONG ID_CA_RIGPART_TAG_INCLUDE_SEARCH_MATCH
			{
				ANIM OFF;
			
				CYCLE
				{
					ID_CA_RIGPART_TAG_INCLUDE_SEARCH_MATCH_MARKER;
					ID_CA_RIGPART_TAG_INCLUDE_SEARCH_MATCH_NAME_TYPE;
					ID_CA_RIGPART_TAG_INCLUDE_SEARCH_MATCH_NAME_NOCASE;
				}
			}
			
			BOOL ID_CA_RIGPART_TAG_INCLUDE_TAGS { ANIM OFF; }
			STATICTEXT { NEWLINE; }
		}
		
		IN_EXCLUDE  ID_CA_RIGPART_TAG_INCLUDE
		{
			NUM_FLAGS 3; INIT_STATE 0; SEND_SELCHNGMSG 1; SCALE_V; ANIM OFF;
			IMAGE_01_ON 1009316; IMAGE_01_OFF 1009320;
			IMAGE_02_ON 1022932; IMAGE_02_OFF 1022942;
			IMAGE_03_ON 1022933; IMAGE_03_OFF 1022943;
			ACCEPT { Obase; };
		}	
	}

	GROUP ID_CA_RIGPART_TAG_GROUP_MATERIALS
	{
		COLUMNS 1; SCALE_V;
		
		GROUP
		{
			COLUMNS 1;
			
			BOOL ID_CA_RIGPART_TAG_MATERIALS_TAGS { ANIM OFF; }
			STATICTEXT { NEWLINE; }
		}
		
		IN_EXCLUDE  ID_CA_RIGPART_TAG_MATERIALS
		{
			NUM_FLAGS 2; INIT_STATE 0; SEND_SELCHNGMSG 1; SCALE_V; ANIM OFF;
			IMAGE_01_ON 1022932; IMAGE_01_OFF 1022942;
			IMAGE_02_ON 1022933; IMAGE_02_OFF 1022943;
			ACCEPT { Mbase; };
		}	
	}

	GROUP ID_CA_RIGPART_TAG_GROUP_LAYERS
	{
		COLUMNS 1; SCALE_V;
		
		GROUP
		{
			COLUMNS 1;
			
			LONG ID_CA_RIGPART_TAG_LAYERS_INEX
			{
				SCALE_H; ANIM OFF;
					
				CYCLE
				{
					ID_CA_RIGPART_TAG_LAYERS_INEX_INCLUDE;
					ID_CA_RIGPART_TAG_LAYERS_INEX_EXCLUDE;
				}
			}
		}
		
		IN_EXCLUDE  ID_CA_RIGPART_TAG_LAYERS
		{
			NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 1; SCALE_V; ANIM OFF;
			ACCEPT { Olayer; };
		}	
	}

	GROUP ID_CA_RIGPART_TAG_GROUP_SELECTION
	{
		COLUMNS 1; SCALE_V;
	
		IN_EXCLUDE  ID_CA_RIGPART_TAG_KEYFRAME
		{
			NUM_FLAGS 1; INIT_STATE 0; SEND_SELCHNGMSG 1; SCALE_V; ANIM OFF;
			IMAGE_01_ON 1009316; IMAGE_01_OFF 1009320;
			ACCEPT { Obase; };
		}
	}
		
	GROUP ID_CA_RIGPART_TAG_GROUP_WEIGHT
	{
		COLUMNS 1; SCALE_V;
		
		IN_EXCLUDE  ID_CA_RIGPART_TAG_WEIGHT
		{
			NUM_FLAGS 1; INIT_STATE 0; SEND_SELCHNGMSG 1; SCALE_V; ANIM OFF;
			IMAGE_01_ON 1009316; IMAGE_01_OFF 1009320;
			ACCEPT { Obase; };
		}	
	}
	
	GROUP ID_CA_RIGPART_TAG_GROUP_ADJUSTMENTS
	{
		COLUMNS 1; SCALE_V;
		
		GROUP
		{
			COLUMNS 3;
			
			BOOL ID_CA_RIGPART_TAG_ADJUST_UPDATE_PREF { ANIM OFF; }
			BOOL ID_CA_RIGPART_TAG_ADJUST_UPDATE_IK { ANIM OFF; }
			BOOL ID_CA_RIGPART_TAG_ADJUST_ALIGN {ANIM OFF;  }
		}
		
		GROUP
		{
			LINK ID_CA_RIGPART_TAG_ADJUST_OBJECT { ANIM OFF; }
		}

		GROUP ID_CA_RIGPART_TAG_GROUP_ADJUSTMENTS_FREEZE
		{
			COLUMNS 3; DEFAULT 1;

			BOOL ID_CA_RIGPART_TAG_ADJUST_FREEZE_P { ANIM OFF; }
			BOOL ID_CA_RIGPART_TAG_ADJUST_FREEZE_S { ANIM OFF; }
			BOOL ID_CA_RIGPART_TAG_ADJUST_FREEZE_R { ANIM OFF; }
		}
		
		GROUP ID_CA_RIGPART_TAG_GROUP_OBJECTLINKS
		{
			DEFAULT 1;
			
			BOOL ID_CA_RIGPART_TAG_ADJUST_UPDATE_AUTO { ANIM OFF; }
			
			GROUP
			{
				COLUMNS 2;
				
				BUTTON ID_CA_RIGPART_TAG_OBJECTLINKS_ADD { SCALE_H; }
				BUTTON ID_CA_RIGPART_TAG_OBJECTLINKS_REMOVE { SCALE_H; }
			}
			
			GROUP
			{
				COLUMNS 1;
				
				ITEMTREE ID_CA_RIGPART_TAG_ADJUST_LINKS { SCALE_H; MULTIPLE; CHECKBOX; COLUMNS 4; HEADERS; ICON; NORENAME; FOLDERS; DRAGDROP; INCREMENT_FOLDER_NAME; }
			}
			
			GROUP ID_CA_RIGPART_TAG_GROUP_OBJECTLINKS_CONTROLS
			{
				COLUMNS 2;
			}
			
			GROUP
			{
				HIDDEN;
				
				LONG ID_CA_RIGPART_TAG_OBJECTLINKS_TYPE
				{
					HIDDEN; ANIM OFF;
					
					CYCLE
					{
						ID_CA_RIGPART_TAG_OBJECTLINKS_TYPE_PSR;
						ID_CA_RIGPART_TAG_OBJECTLINKS_TYPE_PLANE;
						ID_CA_RIGPART_TAG_OBJECTLINKS_TYPE_AIM;
						ID_CA_RIGPART_TAG_OBJECTLINKS_TYPE_POINT;
						ID_CA_RIGPART_TAG_OBJECTLINKS_TYPE_SELECTION;
						ID_CA_RIGPART_TAG_OBJECTLINKS_TYPE_CUSTOM;
					}
				}
				
				LINK ID_CA_RIGPART_TAG_OBJECTLINKS_LINK_A { ANIM OFF; HIDDEN; ACCEPT { Obase; } }
				LINK ID_CA_RIGPART_TAG_OBJECTLINKS_LINK_B { ANIM OFF; HIDDEN; ACCEPT { Obase; } }
				LINK ID_CA_RIGPART_TAG_OBJECTLINKS_LINK_C { ANIM OFF; HIDDEN; ACCEPT { Obase; } }
				LINK ID_CA_RIGPART_TAG_OBJECTLINKS_LINK_D { ANIM OFF; HIDDEN; ACCEPT { Obase; } }
				
				LONG ID_CA_RIGPART_TAG_OBJECTLINKS_INDEX { ANIM OFF; HIDDEN; }
				BOOL ID_CA_RIGPART_TAG_OBJECTLINKS_ALWAYS { ANIM OFF; HIDDEN; }
				
				LONG ID_CA_RIGPART_TAG_OBJECTLINKS_PSR_MODE
				{
					HIDDEN; ANIM OFF;
					
					CYCLE
					{
						ID_CA_RIGPART_TAG_OBJECTLINKS_PSR_MODE_OFF;
						ID_CA_RIGPART_TAG_OBJECTLINKS_PSR_MODE_FREEZE;
						ID_CA_RIGPART_TAG_OBJECTLINKS_PSR_MODE_RETAIN;
					}
				}
								
				LONG ID_CA_RIGPART_TAG_OBJECTLINKS_AIM_MODE
				{
					HIDDEN; ANIM OFF;
					
					CYCLE
					{
						ID_CA_RIGPART_TAG_OBJECTLINKS_AIM_MODE_X;
						ID_CA_RIGPART_TAG_OBJECTLINKS_AIM_MODE_Y;
						ID_CA_RIGPART_TAG_OBJECTLINKS_AIM_MODE_Z;
						ID_CA_RIGPART_TAG_OBJECTLINKS_AIM_MODE_NX;
						ID_CA_RIGPART_TAG_OBJECTLINKS_AIM_MODE_NY;
						ID_CA_RIGPART_TAG_OBJECTLINKS_AIM_MODE_NZ;
					}
				}
				
				LONG ID_CA_RIGPART_TAG_OBJECTLINKS_SELECTION_MODE
				{
					HIDDEN; ANIM OFF;
					
					CYCLE
					{
						ID_CA_RIGPART_TAG_OBJECTLINKS_SELECTION_MODE_PSR;
						ID_CA_RIGPART_TAG_OBJECTLINKS_SELECTION_MODE_POS;
						ID_CA_RIGPART_TAG_OBJECTLINKS_SELECTION_MODE_POSSCL;
						ID_CA_RIGPART_TAG_OBJECTLINKS_SELECTION_MODE_SCL;
					}
				}
				
				REAL ID_CA_RIGPART_TAG_OBJECTLINKS_SELECTION_SIZE { UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; HIDDEN; }
				
				BOOL ID_CA_RIGPART_TAG_OBJECTLINKS_CHILDREN { HIDDEN; }
				BOOL ID_CA_RIGPART_TAG_OBJECTLINKS_WORLD { HIDDEN; }
				BOOL ID_CA_RIGPART_TAG_OBJECTLINKS_ALIGN { HIDDEN; }
				BOOL ID_CA_RIGPART_TAG_OBJECTLINKS_AXIS { HIDDEN; }
					
				BOOL ID_CA_RIGPART_TAG_OBJECTLINKS_POS { HIDDEN; }
				BOOL ID_CA_RIGPART_TAG_OBJECTLINKS_SCALE { HIDDEN; }
				BOOL ID_CA_RIGPART_TAG_OBJECTLINKS_ROT { HIDDEN; }
				
				STRING ID_CA_RIGPART_TAG_OBJECTLINKS_CUSTOM_CODE { CUSTOMGUI MULTISTRING; HIDDEN; }
				STATICTEXT ID_CA_RIGPART_TAG_OBJECTLINKS_CUSTOM_STATUS { HIDDEN; }
				BUTTON ID_CA_RIGPART_TAG_OBJECTLINKS_CUSTOM_CODEEDIT { HIDDEN; }
			}
		}
		
		GROUP ID_CA_RIGPART_TAG_GROUP_PARAMLINKS
		{
			DEFAULT 0;
			
			GROUP
			{
				COLUMNS 2;
				
				BUTTON ID_CA_RIGPART_TAG_PARAMLINKS_ADD { SCALE_H; }
				BUTTON ID_CA_RIGPART_TAG_PARAMLINKS_REMOVE { SCALE_H; }
			}
			
			GROUP
			{
				COLUMNS 1;
				
				ITEMLIST ID_CA_RIGPART_TAG_PARAMLINKS_LIST { SCALE_H; MULTIPLE; }	
			}
							
			GROUP ID_CA_RIGPART_TAG_GROUP_PARAMLINKS_CONTROLS
			{
				COLUMNS 2;
			}
			
			LINK ID_CA_RIGPART_TAG_PARAMLINKS_LINK_A { HIDDEN; ACCEPT { Obase; Tbase; } }
			LINK ID_CA_RIGPART_TAG_PARAMLINKS_LINK_B { HIDDEN; ACCEPT { Obase; } }
			LINK ID_CA_RIGPART_TAG_PARAMLINKS_LINK_C { HIDDEN; ACCEPT { Obase; } }
			
			LONG ID_CA_RIGPART_TAG_PARAMLINKS_PARAMS { HIDDEN; CYCLE { } }
		}
		
		GROUP ID_CA_RIGPART_TAG_GROUP_HANDLES
		{
			DEFAULT 1; COLUMNS 1; SCALE_V;
			
			GROUP
			{
				COLUMNS 2;
				
				LONG ID_CA_RIGPART_TAG_HANDLES_INEX
				{
					SCALE_H; ANIM OFF;
					
					CYCLE
					{
						ID_CA_RIGPART_TAG_HANDLES_INEX_INCLUDE;
						ID_CA_RIGPART_TAG_HANDLES_INEX_EXCLUDE;
					}
				}
				BOOL ID_CA_RIGPART_TAG_HANDLES_BLOCK { SCALE_H; }

				LONG ID_CA_RIGPART_TAG_HANDLES_COL
				{
					SCALE_H; ANIM OFF;

					CYCLE
					{
						ID_CA_RIGPART_TAG_HANDLES_COL_COMPONENT;
						ID_CA_RIGPART_TAG_HANDLES_COL_OBJECT;
						ID_CA_RIGPART_TAG_HANDLES_COL_CUSTOM;
					}
				}
				COLOR ID_CA_RIGPART_TAG_HANDLES_COL_USER { ANIM OFF; SCALE_H; }
			}
			
			GROUP
			{
				SCALE_V; COLUMNS 1;
				
				IN_EXCLUDE  ID_CA_RIGPART_TAG_HANDLES_INCLUDE
				{
					NUM_FLAGS 1; INIT_STATE 0; SEND_SELCHNGMSG 1; ANIM OFF;
					IMAGE_01_ON 1009316; IMAGE_01_OFF 1009320;
					ACCEPT { Obase; };
				}
			}
		}
		
		GROUP ID_CA_RIGPART_TAG_GROUP_HIDING
		{
			DEFAULT 0; COLUMNS 1; SCALE_V;

			IN_EXCLUDE  ID_CA_RIGPART_TAG_HIDING_INCLUDE
			{
				NUM_FLAGS 1; INIT_STATE 0; SEND_SELCHNGMSG 1; ANIM OFF;
				IMAGE_01_ON 1009316; IMAGE_01_OFF 1009320;
				ACCEPT { Obase; };
			}
		}
		
		GROUP ID_CA_RIGPART_TAG_GROUP_EXPRESSIONS
		{
			DEFAULT 0; COLUMNS 1; SCALE_V;
			
			GROUP
			{
				COLUMNS 2;
				
				LONG ID_CA_RIGPART_TAG_EXPRESSIONS_INEX
				{
					SCALE_H; ANIM OFF;
					
					CYCLE
					{
						ID_CA_RIGPART_TAG_EXPRESSIONS_INEX_INCLUDE;
						ID_CA_RIGPART_TAG_EXPRESSIONS_INEX_EXCLUDE;
					}
				}
			}
			
			GROUP
			{
				SCALE_V; COLUMNS 1;
				
				IN_EXCLUDE  ID_CA_RIGPART_TAG_EXPRESSIONS_INCLUDE
				{
					NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 1; ANIM OFF;
					ACCEPT { Tbase; };
				}
			}
		}
	}
	
	GROUP ID_CA_RIGPART_TAG_GROUP_HOTSPOTS
	{
		GROUP
		{
			COLUMNS 2;
			
			BUTTON ID_CA_RIGPART_TAG_HOTSPOTS_ADD { SCALE_H; }
			BUTTON ID_CA_RIGPART_TAG_HOTSPOTS_REMOVE { SCALE_H; }
		}
	
		GROUP
		{
			COLUMNS 1;
			
			ITEMLIST ID_CA_RIGPART_TAG_HOTSPOTS_LIST { SCALE_H; MULTIPLE; }	
		}
		
		GROUP ID_CA_RIGPART_TAG_GROUP_HOTSPOTS_CONTROLS
		{
			COLUMNS 2;
		}
		
		LINK ID_CA_RIGPART_TAG_HOTSPOTS_LINK { ANIM OFF; HIDDEN; ACCEPT { Obase; Tbase; } }
		TEXTURE ID_CA_RIGPART_TAG_HOTSPOTS_ICON { ANIM OFF; HIDDEN; }
		STRING ID_CA_RIGPART_TAG_HOTSPOTS_TEXT { ANIM OFF; HIDDEN; }
		STRING ID_CA_RIGPART_TAG_HOTSPOTS_COMMAND { ANIM OFF; HIDDEN; }
		LONG ID_CA_RIGPART_TAG_HOTSPOTS_ACTION
		{
			HIDDEN; ANIM OFF;
			CYCLE
			{
				ID_CA_RIGPART_TAG_HOTSPOTS_ACTION_NONE;
				ID_CA_RIGPART_TAG_HOTSPOTS_ACTION_MOVE;
				ID_CA_RIGPART_TAG_HOTSPOTS_ACTION_SCALE;
				ID_CA_RIGPART_TAG_HOTSPOTS_ACTION_ROTATE;
				ID_CA_RIGPART_TAG_HOTSPOTS_ACTION_COMMAND;
			}
		}
	}
		
	GROUP ID_CA_RIGPART_TAG_GROUP_NOTES
	{
		COLUMNS 1; SCALE_V;
		
		STRING ID_CA_RIGPART_TAG_NOTES { ANIM OFF; CUSTOMGUI MULTISTRING; SCALE_V; }
	}
	
	GROUP ID_CA_RIGPART_TAG_GROUP_ANIMATE
	{
		DEFAULT 0; COLUMNS 1; SCALE_V;
		
		GROUP
		{
			SCALE_V; COLUMNS 1;
			
			IN_EXCLUDE  ID_CA_RIGPART_TAG_BUILD_ANIMATE_INCLUDE
			{
				NUM_FLAGS 1; INIT_STATE 1; SEND_SELCHNGMSG 1; SCALE_V; ANIM OFF;
				IMAGE_01_ON 300000231; IMAGE_01_OFF 300000230;
				ACCEPT { Tbase; };
			}
		}
	}
	
	GROUP ID_CA_RIGPART_TAG_GROUP_WALK
	{
		COLUMNS 2;
				
		LONG ID_CA_RIGPART_TAG_WALK_CYCLE
		{
			ANIM OFF;
		
			CYCLE
			{
				ID_CA_RIGPART_TAG_WALK_CYCLE_NONE;
				ID_CA_RIGPART_TAG_WALK_CYCLE_HUB_SINGLE;
				ID_CA_RIGPART_TAG_WALK_CYCLE_HUB_MULTI;
				ID_CA_RIGPART_TAG_WALK_CYCLE_TARGET;
			}
		}
		
		LONG ID_CA_RIGPART_TAG_WALK_TARGET_DRIVER
		{
			ANIM OFF;
			
			CYCLE
			{
				ID_CA_RIGPART_TAG_WALK_TARGET_DRIVER_NONE;
				ID_CA_RIGPART_TAG_WALK_TARGET_DRIVER_HUB;
				ID_CA_RIGPART_TAG_WALK_TARGET_DRIVER_PATH;
				ID_CA_RIGPART_TAG_WALK_TARGET_DRIVER_STEPS;
			}
		}
					
		LONG ID_CA_RIGPART_TAG_WALK_HUB_DRIVER
		{
			ANIM OFF; HIDDEN;
			
			CYCLE
			{
				ID_CA_RIGPART_TAG_WALK_TARGET_DRIVER_NONE;
				ID_CA_RIGPART_TAG_WALK_TARGET_DRIVER_PATH;
			}
		}
			
		LINK ID_CA_RIGPART_TAG_WALK_CONTROLLER { ANIM OFF; ACCEPT { Obase; } }
		STATICTEXT { JOINENDSCALE; }

		REAL ID_CA_RIGPART_TAG_WALK_TARGET_H_OFFSET { UNIT METER; ANIM OFF; }
		REAL ID_CA_RIGPART_TAG_WALK_TARGET_MIRROR_H_OFFSET { UNIT METER; ANIM OFF; }
		
		REAL ID_CA_RIGPART_TAG_WALK_TARGET_V_OFFSET { UNIT METER; ANIM OFF; }
		REAL ID_CA_RIGPART_TAG_WALK_TARGET_MIRROR_V_OFFSET { UNIT METER; ANIM OFF; }
		
		REAL ID_CA_RIGPART_TAG_WALK_TARGET_PHASE { UNIT PERCENT; MIN -100.0; MAX 100.0; ANIM OFF; }
		REAL ID_CA_RIGPART_TAG_WALK_TARGET_MIRROR_PHASE { UNIT PERCENT; MIN -100.0; MAX 100.0; ANIM OFF; }
		
		REAL ID_CA_RIGPART_TAG_WALK_TARGET_POS { ANIM OFF; }
		REAL ID_CA_RIGPART_TAG_WALK_TARGET_MIRROR_POS { ANIM OFF; }
		
		REAL ID_CA_RIGPART_TAG_WALK_TARGET_POS_DELTA { ANIM OFF; }
		REAL ID_CA_RIGPART_TAG_WALK_TARGET_PHASE_DELTA { UNIT PERCENT; MIN -100.0; MAX 100.0; ANIM OFF; }
										
		LINK ID_CA_RIGPART_TAG_WALK_HUB { ANIM OFF; HIDDEN; ACCEPT { Obase; } }
		
		GROUP ID_CA_RIGPART_TAG_GROUP_WALK_HUBS
		{
			COLUMNS 1; DEFAULT 1;
			
			GROUP
			{
				COLUMNS 2;
			
				BUTTON ID_CA_RIGPART_TAG_WALK_HUB_ADD { SCALE_H; }
				BUTTON ID_CA_RIGPART_TAG_WALK_HUB_REMOVE { SCALE_H; }
			
				SEPARATOR { LINE; }
				STATICTEXT { JOINENDSCALE; }
			}
		}
	}
		
	GROUP ID_CA_RIGPART_TAG_GROUP_PYTHON
	{
		SCALE_V;
		
		STRING ID_CA_RIGPART_TAG_PYTHON { CUSTOMGUI MULTISTRING; SCALE_V; ANIM OFF; PYTHON; }
	}
	
	GROUP ID_CA_RIGPART_TAG_GROUP_ADVANCED
	{	
		SCALE_V;
		
		GROUP
		{
			COLUMNS 2;
			
			STRING ID_CA_RIGPART_TAG_IDENT { SCALE_H; ANIM OFF; }
			BUTTON ID_CA_RIGPART_TAG_IDENT_GEN { }
			
			STRING ID_CA_RIGPART_TAG_BUILDIDENT { SCALE_H; HIDDEN; ANIM OFF; }
			STRING ID_CA_RIGPART_TAG_BUILDCOUNT { SCALE_H; HIDDEN; ANIM OFF; }
			
			STRING ID_CA_RIGPART_TAG_TEMPLATE_NAME { SCALE_H; HIDDEN; ANIM OFF; }
			STRING ID_CA_RIGPART_TAG_TEMPLATE_IDENT { SCALE_H; HIDDEN; ANIM OFF; }
			
			STRING ID_CA_RIGPART_TAG_TEMPLATE_BUILDIDENT { SCALE_H; HIDDEN; ANIM OFF; }
			STRING ID_CA_RIGPART_TAG_TEMPLATE_BUILDCOUNT { SCALE_H; HIDDEN; ANIM OFF; }
			
			STRING ID_CA_RIGPART_TAG_TEMPLATE_CSUM { SCALE_H; HIDDEN; ANIM OFF; }
			STATICTEXT { NEWLINE; }
			
			STRING ID_CA_RIGPART_TAG_COMPONENT_BUILD_IDENT { SCALE_H; HIDDEN; ANIM OFF; }
			STRING ID_CA_RIGPART_TAG_COMPONENT_CSUM { SCALE_H; HIDDEN; ANIM OFF; }
			
			SEPARATOR { LINE; }
			STATICTEXT { JOINENDSCALE; }
			
			LINK ID_RIGPART_COMPONENT_NEXT { ACCEPT { Obase; } ANIM OFF; }
			LINK ID_RIGPART_COMPONENT_PREV { ACCEPT { Obase; } ANIM OFF; }
			LINK ID_RIGPART_COMPONENT_UP { ACCEPT { Obase; } ANIM OFF; }
			LINK ID_RIGPART_COMPONENT_DOWN { ACCEPT { Obase; } ANIM OFF; }
			
			SEPARATOR { LINE; }
			STATICTEXT { JOINENDSCALE; }
			
			BOOL ID_RIGPART_COMPONENT_MIRRORED { ANIM OFF; }
			STATICTEXT { DUMMY; }
		}
		
		GROUP ID_CA_RIGPART_TAG_GROUP_ADVANCED_OBJECTS
		{
			SCALE_V; DEFAULT 1;
			
			IN_EXCLUDE  ID_CA_RIGPART_TAG_COMPONENT_OBJECTS
			{
				NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 1; SCALE_V; ANIM OFF;
				ACCEPT { Obase; };
			}	
			
			IN_EXCLUDE  ID_CA_RIGPART_TAG_INCLUDED_OBJECTS
			{
				NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 1; SCALE_V; ANIM OFF;
				ACCEPT { Obase; };
			}			
		}
	}

	GROUP Obaselist
	{
		HIDE ID_BASELIST_ICON_SETTINGS_GROUP;
	}
}
