CONTAINER Tcavs
{
	NAME Tcavs;
	INCLUDE Tbase;
	
	GROUP ID_TAGPROPERTIES
	{
		SCALE_V;
		
		GROUP
		{
			SCALE_V;
							
			IMAGE ID_CA_TAG_VS_IMAGE { SCALE_V; }
		}
	}
	
	GROUP ID_CA_TAG_VS_GROUP_SETUP
	{
		SCALE_V;
		GROUP
		{
			LONG ID_CA_TAG_VS_MODE
			{
				SCALE_H; ANIM OFF; 
				
				CUSTOMGUI RADIOBUTTONS; COLUMNS 2;
				
				CYCLE
				{
					ID_CA_TAG_VS_MODE_EDIT;
					ID_CA_TAG_VS_MODE_ANIMATE;
				}
			}
			
			ITEMTREE ID_CA_TAG_VS_HOTSPOTS
			{
				DRAGDROP;
			}
		}
		
		GROUP
		{
			COLUMNS 3;
			
			BUTTON ID_CA_TAG_VS_ADD_VIEW { SCALE_H; }
			BUTTON ID_CA_TAG_VS_ADD_HOTSPOT { SCALE_H; }
			BUTTON ID_CA_TAG_VS_REMOVE { SCALE_H; }
		}
		
		GROUP ID_CA_TAG_VS_GROUP_IMAGE
		{
			DEFAULT 1;
		
			TEXTURE ID_CA_TAG_VS_IMAGE_NAME { ANIM OFF; }
			REAL ID_CA_TAG_VS_ZOOM { UNIT PERCENT; MIN 0.0; MAXSLIDER 400.0; MAX 1600; CUSTOMGUI REALSLIDER; ANIM OFF; PARENTCOLLAPSE; }
			
			GROUP
			{
				COLUMNS 2;
				
				LONG ID_CA_TAG_VS_LEFT { ANIM OFF; PARENTCOLLAPSE ID_CA_TAG_VS_ZOOM; MIN 0; MAXSLIDER 2000; }
				LONG ID_CA_TAG_VS_TOP { ANIM OFF; PARENTCOLLAPSE ID_CA_TAG_VS_ZOOM; MIN 0; MAXSLIDER 2000; }
				
				LONG ID_CA_TAG_VS_RIGHT { ANIM OFF; PARENTCOLLAPSE ID_CA_TAG_VS_ZOOM; MIN 0; MAXSLIDER 2000; }
				LONG ID_CA_TAG_VS_BOTTOM { ANIM OFF; PARENTCOLLAPSE ID_CA_TAG_VS_ZOOM; MIN 0; MAXSLIDER 2000; }
			}
		}
		
		GROUP ID_CA_TAG_VS_GROUP_HOTSPOT
		{	
			DEFAULT 1;
			SCALE_V;
		
			COLOR ID_CA_TAG_VS_COL { ANIM OFF; }
			REAL ID_CA_TAG_VS_TRANS { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; ANIM OFF; PARENTCOLLAPSE; }
			
			COLOR ID_CA_TAG_VS_HIGHLIGHT_COL { ANIM OFF; PARENTCOLLAPSE ID_CA_TAG_VS_TRANS; }
			REAL ID_CA_TAG_VS_HIGHLIGHT_TRANS { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; ANIM OFF; PARENTCOLLAPSE ID_CA_TAG_VS_TRANS; }
			
			SEPARATOR { LINE; PARENTCOLLAPSE ID_CA_TAG_VS_TRANS; }
			
			COLOR ID_CA_TAG_VS_SELECT_COL { ANIM OFF; PARENTCOLLAPSE ID_CA_TAG_VS_TRANS; }
			REAL ID_CA_TAG_VS_SELECT_TRANS { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; ANIM OFF; PARENTCOLLAPSE ID_CA_TAG_VS_TRANS; }

			LINK ID_CA_TAG_VS_LINK { ANIM OFF; }
			
			LONG ID_CA_TAG_VS_ACTION
			{
				ANIM OFF;
			
				CYCLE
				{
					ID_CA_TAG_VS_ACTION_NONE;
					ID_CA_TAG_VS_ACTION_MOVE;
					ID_CA_TAG_VS_ACTION_SCALE;
					ID_CA_TAG_VS_ACTION_ROTATE;
					ID_CA_TAG_VS_ACTION_COMMAND;
					ID_CA_TAG_VS_ACTION_VIEW;
					ID_CA_TAG_VS_ACTION_SCRIPT;
				}
			}
			
			STRING ID_CA_TAG_VS_COMMAND { HIDDEN; ANIM OFF; }
			
			STRING ID_CA_TAG_VS_PYTHON { CUSTOMGUI MULTISTRING; ANIM OFF; PYTHON; HIDDEN; SCALE_V;}
			
			LONG ID_CA_TAG_VS_VIEW
			{
				ANIM OFF; HIDDEN; 
				
				CYCLE
				{
				}
			}
		}
		
		GROUP ID_CA_TAG_VS_GROUP_TOOLS
		{
			DEFAULT 1;
			
			LONG ID_CA_TAG_VS_BRUSH { MIN 1; MAXSLIDER 1000; CUSTOMGUI LONGSLIDER; ANIM OFF; }
			LONG ID_CA_TAG_VS_LASSO
			{
				HIDDEN; ANIM OFF;
				CYCLE
				{
					ID_CA_TAG_VS_LASSO_FREE;
					ID_CA_TAG_VS_LASSO_POLY;
					ID_CA_TAG_VS_LASSO_RECT;
				}
			}
			LONG ID_CA_TAG_VS_SHAPE
			{
				HIDDEN; ANIM OFF;
				CYCLE
				{
					ID_CA_TAG_VS_SHAPE_RECT;
					ID_CA_TAG_VS_SHAPE_ELLIPSE;
				}			
			}
		}		
	}
	
	GROUP ID_CA_TAG_VS_GROUP_COORDS
	{
		HIDDEN;
	}
	
	GROUP ID_CA_TAG_VS_GROUP_USERDATA
	{
		HIDDEN;
	}	
}
