CONTAINER Toolcanaming
{
	NAME Toolcanaming;
	INCLUDE ToolBase;

	HIDE MDATA_COMMANDGROUP;

	GROUP MDATA_MAINGROUP
	{
		GROUP
		{
			COLUMNS 4;
      LONG ID_CA_JOINT_NAMING_NODETYPE
      {
        CYCLE
        {
          ID_CA_JOINT_NAMING_NODETYPE_OBJECT;
          ID_CA_JOINT_NAMING_NODETYPE_TAG;
          ID_CA_JOINT_NAMING_NODETYPE_MATERIAL;
          ID_CA_JOINT_NAMING_NODETYPE_LAYER;
          ID_CA_JOINT_NAMING_NODETYPE_TAKE;
        }
      }

			LONG ID_CA_JOINT_NAMING_TYPE
			{
				CYCLE
				{
				}
			}
				
			BUTTON ID_CA_JOINT_NAMING_STORE { }
			BUTTON ID_CA_JOINT_NAMING_REMOVE { }
		}

		GROUP
		{
			COLUMNS 2;
			
			BUTTON ID_CA_JOINT_NAMING_LOAD { }
			BUTTON ID_CA_JOINT_NAMING_SAVE { }
					
			STRING ID_CA_JOINT_NAMING_PRE { SCALE_H; }
			STRING ID_CA_JOINT_NAMING_POST { SCALE_H; }

			SEPARATOR { }
			STATICTEXT { JOINEND; }

			BUTTON ID_CA_JOINT_NAMING_APPLY { SCALE_H; }
			STATICTEXT { JOINEND; }
		}
		
		GROUP ID_CA_JOINT_NAMING_RENAME
		{
			DEFAULT 1; COLUMNS 2;

			STRING ID_CA_JOINT_NAMING_REPLACE_PRE { SCALE_H; }
			STRING ID_CA_JOINT_NAMING_REPLACE_POST { SCALE_H; }
			
			STRING ID_CA_JOINT_NAMING_REPLACE { SCALE_H; }
			STRING ID_CA_JOINT_NAMING_REPLACE_WITH { SCALE_H; }
		
			BOOL ID_CA_JOINT_NAMING_CASE { }
			STATICTEXT { NEWLINE; }

			SEPARATOR { }
			STATICTEXT { JOINEND; }

			BUTTON ID_CA_JOINT_NAMING_REPLACE_APPLY { }
			STATICTEXT { JOINEND; }
		}

		GROUP ID_CA_JOINT_NAMING_NAMES
		{
			COLUMNS 2;

			BUTTON ID_CA_JOINT_NAMING_SET_NAME { HIDDEN; }
		}
	}
}
