CONTAINER Toolcaweight
{
	NAME Toolcaweight;

	INCLUDE ToolBase;
	INCLUDE ToolWeightBase;

	HIDE MDATA_COMMANDGROUP;

	GROUP MDATA_MAINGROUP
	{
		COLUMNS 1;
						
		GROUP ID_CA_WEIGHT_TOOL_PAINT_GROUP
		{
			COLUMNS 2;
			
			BOOL ID_CA_WEIGHT_TOOL_PROJECTION { }
			BOOL ID_CA_WEIGHT_TOOL_VISIBLE_ONLY { }
			
			BOOL ID_CA_WEIGHT_TOOL_SELECTED { }
			BOOL ID_CA_WEIGHT_TOOL_NORMALIZE { }
		}
				
		GROUP
		{
			COLUMNS 2;

			LONG ID_CA_WEIGHT_TOOL_MODE
			{
				FIT_H; SCALE_H;

				CYCLE
				{
					ID_CA_WEIGHT_BASE_MODE_ADD;
					ID_CA_WEIGHT_BASE_MODE_SPRAY;
					ID_CA_WEIGHT_BASE_MODE_SUBTRACT;
					ID_CA_WEIGHT_BASE_MODE_ABS;
					ID_CA_WEIGHT_BASE_MODE_SMOOTH;
					ID_CA_WEIGHT_BASE_MODE_BLEED;
					ID_CA_WEIGHT_BASE_MODE_INTENSITY;
					ID_CA_WEIGHT_BASE_MODE_REMAP;
					ID_CA_WEIGHT_BASE_MODE_PRUNE;
					ID_CA_WEIGHT_BASE_MODE_DROPPER;
				}
			}
			REAL ID_CA_WEIGHT_TOOL_STRENGTH { UNIT PERCENT; MIN -100.0; MINSLIDER 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; SCALE_H; }
			
			SPLINE ID_CA_WEIGHT_TOOL_SPLINE	{  }
			STATICTEXT { JOINENDSCALE; }	
		}

		GROUP ID_CA_WEIGHT_TOOL_BRUSH_GROUP
		{
			COLUMNS 2; DEFAULT 1;
			
			LONG ID_CA_WEIGHT_TOOL_FALLOFF
			{
				FIT_H; SCALE_H;

				CYCLE
				{
					ID_CA_WEIGHT_TOOL_FALLOFF_NONE;
					ID_CA_WEIGHT_TOOL_FALLOFF_SIMPLE;
					ID_CA_WEIGHT_TOOL_FALLOFF_LINEAR;
					ID_CA_WEIGHT_TOOL_FALLOFF_DOME;
					ID_CA_WEIGHT_TOOL_FALLOFF_BELL;
					ID_CA_WEIGHT_TOOL_FALLOFF_CIRCLE;
					ID_CA_WEIGHT_TOOL_FALLOFF_NEEDLE;
					ID_CA_WEIGHT_TOOL_FALLOFF_SPLINE;
				}
			}

			LONG ID_CA_WEIGHT_TOOL_PEN
			{
				FIT_H; SCALE_H;

				CYCLE
				{
					ID_CA_WEIGHT_TOOL_PEN_NONE;
					ID_CA_WEIGHT_TOOL_PEN_RADIUS;
					ID_CA_WEIGHT_TOOL_PEN_STRENGTH;
					ID_CA_WEIGHT_TOOL_PEN_HARDNESS;
				}
			}
			
			REAL ID_CA_WEIGHT_TOOL_RADIUS { FIT_H; SCALE_H; MIN 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINENDSCALE; }
			
			REAL ID_CA_WEIGHT_TOOL_WIDTH { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINENDSCALE; }
			
			REAL ID_CA_WEIGHT_TOOL_HARDNESS { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
			STATICTEXT { JOINENDSCALE; }

			SPLINE ID_CA_WEIGHT_TOOL_FALLOFF_CURVE {  }
			STATICTEXT { JOINENDSCALE; }
		}	
		
		GROUP ID_CA_WEIGHT_TOOL_CLAMP_GROUP
		{
			COLUMNS 2;

			BOOL ID_CA_WEIGHT_TOOL_CLAMP_LOWER_ENABLE { }
			REAL ID_CA_WEIGHT_TOOL_CLAMP_LOWER { FIT_H; SCALE_H; UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }

			BOOL ID_CA_WEIGHT_TOOL_CLAMP_UPPER_ENABLE { }
			REAL ID_CA_WEIGHT_TOOL_CLAMP_UPPER { FIT_H; SCALE_H; UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		}
	}
	
	GROUP ID_CA_WEIGHT_TOOL_SYMMETRY_GROUP
	{
		COLUMNS 2;
		
		BOOL ID_CA_WEIGHT_TOOL_SYMMETRY { }
		STATICTEXT { NEWLINE; }

		LONG ID_CA_WEIGHT_TOOL_SYMMETRY_MODE
		{
			SCALE_H;
		
			CYCLE
			{
				ID_CA_WEIGHT_TOOL_SYMMETRY_MODE_NONE;
				ID_CA_WEIGHT_TOOL_SYMMETRY_MODE_NAME;
				ID_CA_WEIGHT_TOOL_SYMMETRY_MODE_HIEARCHY;
			}
		}
		REAL ID_CA_WEIGHT_TOOL_SYMMETRY_RAD { SCALE_H; UNIT METER; MIN 0.0; MAXSLIDER 10.0; STEP 0.1; CUSTOMGUI REALSLIDER; }
		
		STRING ID_CA_WEIGHT_TOOL_SYMMETRY_MODE_NAME_LEFT { }
		STRING ID_CA_WEIGHT_TOOL_SYMMETRY_MODE_NAME_RIGHT { }
		
		LONG ID_CA_WEIGHT_TOOL_SYMMETRY_COORD
		{
			SCALE_H;
		
			CYCLE
			{
				ID_CA_WEIGHT_TOOL_SYMMETRY_COORD_LOCAL;
				ID_CA_WEIGHT_TOOL_SYMMETRY_COORD_WORLD;
				ID_CA_WEIGHT_TOOL_SYMMETRY_COORD_CUSTOM;
			}
		}
		
		LONG ID_CA_WEIGHT_TOOL_SYMMETRY_MIRROR
		{
			SCALE_H;
		
			CYCLE
			{
				ID_CA_WEIGHT_TOOL_SYMMETRY_MIRROR_XY;
				ID_CA_WEIGHT_TOOL_SYMMETRY_MIRROR_YZ;
				ID_CA_WEIGHT_TOOL_SYMMETRY_MIRROR_XZ;
			}
		}
		
		LINK ID_CA_WEIGHT_TOOL_SYMMETRY_COORD_CUSTOM_OBJECT { ACCEPT { Obase; } }
		STATICTEXT { JOINEND; }
	}
  	
	GROUP ID_CA_WEIGHT_TOOL_DISPLAY_GROUP
	{
		GROUP ID_CA_WEIGHT_TOOL_DISPLAY_SUB_GROUP
		{
			DEFAULT 1;
			COLUMNS 2;
			FIT_H;
			SCALE_H;
	
			BOOL ID_CA_WEIGHT_TOOL_ENABLE_DISPLAY { }
			BOOL ID_CA_WEIGHT_TOOL_DISPLAY_FALLOFF { }
			BOOL ID_CA_WEIGHT_TOOL_DISPLAY_CURSOR { }
			BOOL ID_CA_WEIGHT_TOOL_DISPLAY_MOUSEIN { }
		}

		SEPARATOR { LINE; }

		GROUP ID_CA_WEIGHT_TOOL_DISPLAY_COLORS_GROUP
		{
			DEFAULT 1;
			
			COLOR ID_CA_WEIGHT_TOOL_DISPLAY_CURSOR_COLOR { }
			COLOR ID_CA_WEIGHT_TOOL_DISPLAY_FALLOFF_COLOR { }
			COLOR ID_CA_WEIGHT_TOOL_DISPLAY_ERASE_COLOR { }
		}
	}
}
