CONTAINER Toolcaalign
{
	NAME Toolcaalign;
	INCLUDE ToolBase;

	HIDE MDATA_COMMANDGROUP;

	GROUP MDATA_MAINGROUP
	{
		COLUMNS 2;
		
		LONG ID_CA_JOINT_ALIGN_PRIMARY_AXIS
		{
			CYCLE
			{
				ID_CA_JOINT_ALIGN_AXIS_FROMJOINT;
				ID_CA_JOINT_ALIGN_AXIS_X;
				ID_CA_JOINT_ALIGN_AXIS_Y;
				ID_CA_JOINT_ALIGN_AXIS_Z;
				ID_CA_JOINT_ALIGN_AXIS_NONE;
			}
		}
		
		LONG ID_CA_JOINT_ALIGN_PRIMARY_DIRECTION
		{
			CYCLE
			{
				ID_CA_JOINT_ALIGN_DIRECTION_BONE;
				ID_CA_JOINT_ALIGN_DIRECTION_WORLD_AXIS;
				ID_CA_JOINT_ALIGN_DIRECTION_OBJECT_AXIS;
				ID_CA_JOINT_ALIGN_DIRECTION_OBJECT;
				ID_CA_JOINT_ALIGN_DIRECTION_ROOT_AXIS;
			}
		}
				
		LINK ID_CA_JOINT_ALIGN_PRIMARY_LINK { ACCEPT { Obase; } }
		STATICTEXT { JOINENDSCALE; }
		
		LONG ID_CA_JOINT_ALIGN_UP_AXIS
		{
			CYCLE
			{
				ID_CA_JOINT_ALIGN_AXIS_X;
				ID_CA_JOINT_ALIGN_AXIS_Y;
				ID_CA_JOINT_ALIGN_AXIS_Z;
				ID_CA_JOINT_ALIGN_AXIS_NONE;
			}
		}
		
		LONG ID_CA_JOINT_ALIGN_UP_DIRECTION
		{
			CYCLE
			{
				ID_CA_JOINT_ALIGN_DIRECTION_WORLD_AXIS;
				ID_CA_JOINT_ALIGN_DIRECTION_OBJECT_AXIS;
				ID_CA_JOINT_ALIGN_DIRECTION_OBJECT;
				ID_CA_JOINT_ALIGN_DIRECTION_ROOT_AXIS;
			}
		}
		
		LINK ID_CA_JOINT_ALIGN_UP_LINK { ACCEPT { Obase; } }
		STATICTEXT { JOINENDSCALE; }
		
		BOOL ID_CA_JOINT_ALIGN_UP_FROMPREV { }
		BOOL ID_CA_JOINT_ALIGN_CHILDREN { }
		
		BUTTON ID_CA_JOINT_ALIGN { }
		STATICTEXT { JOINENDSCALE; }
	}
}
