CONTAINER Toolbrushbase
{
	NAME Toolbrushbase;

	INCLUDE ToolBase;

	HIDE MDATA_COMMANDGROUP;
	
	GROUP MDATA_MAINGROUP
	{
		REAL ID_BRUSH_BASE_TOOL_STRENGTH { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
	}
	
	GROUP ID_BRUSH_BASE_TOOL_GROUP_PAINT
	{
		COLUMNS 3; DEFAULT 1;

		BOOL ID_BRUSH_BASE_TOOL_PROJECTION { }
		BOOL ID_BRUSH_BASE_TOOL_VISIBLE_ONLY { }
		BOOL ID_BRUSH_BASE_TOOL_SELECTED { }

		REAL ID_BRUSH_BASE_TOOL_RADIUS { FIT_H; SCALE_H; MIN 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINEND; }
		
		LONG ID_BRUSH_BASE_TOOL_STEP { MIN 1; MAX 1000; MINSLIDER 1; MAXSLIDER 100; CUSTOMGUI LONGSLIDER; }
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINEND; }
	
		LONG ID_BRUSH_BASE_TOOL_FALLOFF
		{
			FIT_H; SCALE_H;

			CYCLE
			{
				ID_BRUSH_BASE_TOOL_FALLOFF_NONE;
				ID_BRUSH_BASE_TOOL_FALLOFF_SIMPLE;
				ID_BRUSH_BASE_TOOL_FALLOFF_LINEAR;
				ID_BRUSH_BASE_TOOL_FALLOFF_DOME;
				ID_BRUSH_BASE_TOOL_FALLOFF_BELL;
				ID_BRUSH_BASE_TOOL_FALLOFF_CIRCLE;
				ID_BRUSH_BASE_TOOL_FALLOFF_NEEDLE;
				ID_BRUSH_BASE_TOOL_FALLOFF_SPLINE;
			}
		}
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINEND; }
		
		REAL ID_BRUSH_BASE_TOOL_WIDTH { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINEND; }
		
		REAL ID_BRUSH_BASE_TOOL_HARDNESS { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINEND; }
		
		SPLINE ID_BRUSH_BASE_TOOL_FALLOFF_CURVE {  }
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINEND; }
		
		SEPARATOR { }
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINEND; }
		
		LONG ID_BRUSH_BASE_TOOL_PEN
		{
			FIT_H; SCALE_H;

			CYCLE
			{
				ID_BRUSH_BASE_TOOL_PEN_NONE;
				ID_BRUSH_BASE_TOOL_PEN_RADIUS;
				ID_BRUSH_BASE_TOOL_PEN_STRENGTH;
				ID_BRUSH_BASE_TOOL_PEN_HARDNESS;
			}
		}
		STATICTEXT { JOINEND; }
		STATICTEXT { JOINEND; }
	}
}
