CONTAINER Toolcamirror
{
	NAME Toolcamirror;
	INCLUDE ToolBase;
	INCLUDE ToolMirrorBase;

	HIDE MDATA_COMMANDGROUP;

	GROUP ID_CA_MIRROR_TOOL_GROUP_AXIS
	{
		COLUMNS 1; DEFAULT 1;
		
		GROUP
		{
			COLUMNS 2;
						
			LONG ID_CA_MIRROR_TOOL_ORIGIN
			{
				SCALE_H;
				
				CYCLE
				{
					ID_CA_TOOL_MIRROR_BASE_ORIGIN_SELECTED;
					ID_CA_TOOL_MIRROR_BASE_ORIGIN_ROOT;
					ID_CA_TOOL_MIRROR_BASE_ORIGIN_PARENT;
					ID_CA_TOOL_MIRROR_BASE_ORIGIN_HUB;
					ID_CA_TOOL_MIRROR_BASE_ORIGIN_OBJECT;
					ID_CA_TOOL_MIRROR_BASE_ORIGIN_WORLD;
					ID_CA_TOOL_MIRROR_BASE_ORIGIN_MESH;
				}
			}
			LONG ID_CA_MIRROR_TOOL_COORDS
			{	
				SCALE_H;
				
				CYCLE
				{
					ID_CA_TOOL_MIRROR_BASE_COORDS_WORLD;
					ID_CA_TOOL_MIRROR_BASE_COORDS_LOCAL;
					ID_CA_TOOL_MIRROR_BASE_COORDS_VIEW;
				}
			}
			
			LONG ID_CA_MIRROR_TOOL_DIRECTION
			{	
				SCALE_H;
				
				CYCLE
				{
					ID_CA_TOOL_MIRROR_BASE_DIRECTION_X;
					ID_CA_TOOL_MIRROR_BASE_DIRECTION_Y;
					ID_CA_TOOL_MIRROR_BASE_DIRECTION_Z;
				}
			}
			LONG ID_CA_MIRROR_TOOL_TYPE
			{	
				SCALE_H;
				
				CYCLE
				{
					ID_CA_TOOL_MIRROR_BASE_TYPE_REFLECT;
					ID_CA_TOOL_MIRROR_BASE_TYPE_P2N;
					ID_CA_TOOL_MIRROR_BASE_TYPE_N2P;
				}
			}
			
			LINK ID_CA_MIRROR_TOOL_OBJECT_LINK { ACCEPT { Obase; } }
			STATICTEXT { JOINENDSCALE; }
		}
	}
	
	GROUP ID_CA_MIRROR_TOOL_GROUP_OPTIONS
	{
		COLUMNS 2;
				
		LONG ID_CA_MIRROR_TOOL_TARGET
		{
			CYCLE
			{
				ID_CA_MIRROR_TOOL_TARGET_CLONE;
				ID_CA_MIRROR_TOOL_TARGET_OBJECT;
				ID_CA_MIRROR_TOOL_TARGET_SELF;
			}
		}
		
		LINK ID_CA_MIRROR_TOOL_TARGET_LINK { ACCEPT { Obase; } }
					
		BOOL ID_CA_MIRROR_TOOL_AUTO_INCLUDE { SCALE_H; }
		BOOL ID_CA_MIRROR_TOOL_SET_JOINT_LINK { }
		
		BOOL ID_CA_MIRROR_TOOL_FREEZE_PSR { }
		STATICTEXT { NEWLINE; }
			
		GROUP ID_CA_MIRROR_TOOL_GROUP_PROPERTIES
		{
			COLUMNS 2; DEFAULT 1;
			
			BOOL ID_CA_MIRROR_TOOL_PSR { SCALE_H; }
			LONG ID_CA_MIRROR_TOOL_AXIS
			{
				SCALE_H; 
				
				CYCLE
				{
					ID_CA_MIRROR_TOOL_AXIS_NONE;
					ID_CA_MIRROR_TOOL_AXIS_ROTATE;
					ID_CA_MIRROR_TOOL_AXIS_ALIGN_X;
					ID_CA_MIRROR_TOOL_AXIS_ALIGN_Y;
					ID_CA_MIRROR_TOOL_AXIS_ALIGN_Z;
				}
			}
			
			BOOL ID_CA_MIRROR_TOOL_WEIGHTS { }
			BOOL ID_CA_MIRROR_TOOL_POINTS { }
		}
		
		GROUP ID_CA_MIRROR_TOOL_GROUP_CLONE
		{
			COLUMNS 2;
			
			BOOL ID_CA_MIRROR_TOOL_CLONE_TAGS { }
			BOOL ID_CA_MIRROR_TOOL_CLONE_ANIM { }	
		}
	}
	
	GROUP ID_CA_MIRROR_TOOL_GROUP_NAMING
	{
		COLUMNS 2;
					
		BOOL ID_CA_MIRROR_TOOL_CASE { }
		STATICTEXT { NEWLINE; }
		
		STRING ID_CA_MIRROR_TOOL_PRE { SCALE_H; }
		STRING ID_CA_MIRROR_TOOL_POST { SCALE_H; }
		
		STRING ID_CA_MIRROR_TOOL_REPLACE { SCALE_H; }
		STRING ID_CA_MIRROR_TOOL_WITH { SCALE_H; }
	}

	GROUP ID_CA_MIRROR_TOOL_GROUP_WEIGHT
	{
		SCALE_H; 

		GROUP ID_CA_MIRROR_TOOL_GROUP_WEIGHT_POINT
		{
			DEFAULT 1;
			COLUMNS 2;

			LONG ID_CA_MIRROR_TOOL_SEARCH
			{
				SCALE_H; 
				
				CYCLE
				{
					ID_CA_TOOL_MIRROR_BASE_SEARCH_RADIUS;
					ID_CA_TOOL_MIRROR_BASE_SEARCH_NEAREST;
					ID_CA_TOOL_MIRROR_BASE_SEARCH_SURFACE;
					ID_CA_TOOL_MIRROR_BASE_SEARCH_NORMALS;
				}
			}
			REAL ID_CA_MIRROR_TOOL_POINT_RADIUS { UNIT METER; STEP 0.01; MIN 0.00001; }
			REAL ID_CA_MIRROR_TOOL_SIDE_THRESHOLD{ HIDDEN; UNIT METER; STEP 0.001; MIN 0.000001; }
		}
		
		GROUP ID_CA_MIRROR_TOOL_GROUP_WEIGHT_JOINT
		{
			DEFAULT 1;

			GROUP
			{
				COLUMNS 2;

				LONG ID_CA_MIRROR_TOOL_JOINT_ALGO_PASS1
				{	
					CYCLE
					{
						ID_CA_TOOL_MIRROR_BASE_JOINT_MATCH_TOPO;
						ID_CA_TOOL_MIRROR_BASE_JOINT_MATCH_POS;
						ID_CA_TOOL_MIRROR_BASE_JOINT_MATCH_SPATIAL_PART;
						ID_CA_TOOL_MIRROR_BASE_JOINT_MATCH_NAME;
					}
				}
				STATICTEXT{ JOINEND; }

				LONG ID_CA_MIRROR_TOOL_JOINT_ALGO_PASS2
				{	
					CYCLE
					{
						ID_CA_TOOL_MIRROR_BASE_JOINT_MATCH_NONE;
						ID_CA_TOOL_MIRROR_BASE_JOINT_MATCH_TOPO;
						ID_CA_TOOL_MIRROR_BASE_JOINT_MATCH_POS;
						ID_CA_TOOL_MIRROR_BASE_JOINT_MATCH_SPATIAL_PART;
						ID_CA_TOOL_MIRROR_BASE_JOINT_MATCH_NAME;
					}
				}
				STATICTEXT{ JOINEND; }

				BOOL ID_CA_MIRROR_TOOL_JOINT_ALGO_PASS_FINAL { HIDDEN; }
			}

			GROUP ID_CA_MIRROR_TOOL_GROUP_WEIGHT_SPATIAL
			{
				DEFAULT 0;
				COLUMNS 2;
				SEPARATOR{ LINE; SCALE_H; }
				STATICTEXT{ JOINEND; }
				GROUP
				{
					DEFAULT 1;
					SCALE_H;
					COLUMNS 2;
					// ADAPTATIVE IS NOT 100% FUNCTIONAL YET.
					BOOL ID_CA_MIRROR_TOOL_SPATIAL_PART_ADAPTATIVE { HIDDEN; }
					REAL ID_CA_MIRROR_TOOL_SPATIAL_PART_FACTOR { UNIT PERCENT; STEP 1.0; MIN 1.0; MAX 200.0; }
					STATICTEXT{ JOINEND; }
				}
			}
			GROUP ID_CA_MIRROR_TOOL_GROUP_WEIGHT_POSITION
			{
				DEFAULT 0;
				COLUMNS 2;
				SEPARATOR{ LINE; SCALE_H; }
				STATICTEXT{ JOINEND; }
				REAL ID_CA_MIRROR_TOOL_JOINT_TOLERANCE{ UNIT METER; STEP 0.01; MIN 0.00001; }
			}
			GROUP ID_CA_MIRROR_TOOL_GROUP_WEIGHT_NAME
			{
				DEFAULT 0;
				COLUMNS 2;
				SEPARATOR { LINE; SCALE_H; }
				STATICTEXT { JOINEND; }
				BOOL ID_CA_MIRROR_TOOL_JOINT_NAME_MATCH_CASE{}
				STATICTEXT{ JOINEND; }
				GROUP
				{
					COLUMNS 2;
					STRING ID_CA_MIRROR_TOOL_JOINT_NAME_NEG_PREFIX{}
					STRING ID_CA_MIRROR_TOOL_JOINT_NAME_POS_PREFIX{}
				}
				STATICTEXT{ JOINEND; }
			}
		}

		BUTTON ID_CA_MIRROR_TOOL_MIRROR_WEIGHTS { SCALE_H; }
	}
	
	GROUP ID_CA_MIRROR_TOOL_GROUP_TOOL
	{
		DEFAULT 1;
	
		GROUP
		{
			BOOL ID_CA_MIRROR_TOOL_HIERARCHY { }
		}
		BUTTON ID_CA_MIRROR_TOOL { SCALE_H; }
	}	
}
