CONTAINER Toolcajoint
{
	NAME Toolcajoint;
	INCLUDE ToolBase;

	HIDE MDATA_COMMANDGROUP;

	GROUP MDATA_MAINGROUP
	{
		GROUP
		{
			COLUMNS 2;

			LONG ID_CA_JOINT_TOOL_CREATE
			{
				CYCLE
				{
					ID_CA_JOINT_TOOL_CREATE_AXIS;
					ID_CA_JOINT_TOOL_CREATE_FROMPARENT;
					ID_CA_JOINT_TOOL_CREATE_TOCHILD;
				}
			}

			LONG ID_CA_JOINT_TOOL_IK_CHAIN
			{
				CYCLE
				{
					ID_CA_JOINT_TOOL_IK_CHAIN_NONE;
					ID_CA_JOINT_TOOL_IK_CHAIN_2D;
					ID_CA_JOINT_TOOL_IK_CHAIN_3D;
					ID_CA_JOINT_TOOL_IK_CHAIN_SPLINE;
				}
			}

			LONG ID_CA_JOINT_TOOL_SIZE
			{
				CYCLE
				{
					ID_CA_JOINT_TOOL_SIZE_LENGTH;
					ID_CA_JOINT_TOOL_SIZE_CUSTOM;
				}
			}

			REAL ID_CA_JOINT_TOOL_SIZE_USER { UNIT METER; MIN 0.0; }

			BOOL ID_CA_JOINT_TOOL_CREATE_ROOT { }
			BOOL ID_CA_JOINT_TOOL_CREATE_POLE { }

			BOOL ID_CA_JOINT_TOOL_ALIGN_AXIS { }
			BOOL ID_CA_JOINT_TOOL_PROJECTION { }
		}

		GROUP ID_CA_JOINT_TOOL_GROUP_DISPLAY
		{
			COLUMNS 2;

			BOOL ID_CA_JOINT_TOOL_HIGHLIGHT { }
			BOOL ID_CA_JOINT_TOOL_BOUNDING_BOX { }
		}

		GROUP ID_CA_JOINT_TOOL_GROUP_SYMMETRY
		{
			COLUMNS 1;

			GROUP
			{
				COLUMNS 2;
							
				LONG ID_CA_JOINT_TOOL_SYMMETRY
				{
					CYCLE
					{
						ID_CA_JOINT_TOOL_SYMMETRY_NONE;
						ID_CA_JOINT_TOOL_SYMMETRY_DRAW;
						ID_CA_JOINT_TOOL_SYMMETRY_LINKED;
					}
				}
					
				LONG ID_CA_JOINT_TOOL_MIRROR_PLANE
				{
					CYCLE
					{
						ID_CA_JOINT_TOOL_MIRROR_WORLD_XY;
						ID_CA_JOINT_TOOL_MIRROR_WORLD_XZ;
						ID_CA_JOINT_TOOL_MIRROR_WORLD_YZ;
						ID_CA_JOINT_TOOL_MIRROR_LOCAL_XY;
						ID_CA_JOINT_TOOL_MIRROR_LOCAL_XZ;
						ID_CA_JOINT_TOOL_MIRROR_LOCAL_YZ;
					}
				}

				LONG ID_CA_JOINT_TOOL_MIRROR_ORIGIN
				{
					CYCLE
					{
						ID_CA_JOINT_TOOL_MIRROR_ORIGIN_WORLD;
						ID_CA_JOINT_TOOL_MIRROR_ORIGIN_ROOT;
						ID_CA_JOINT_TOOL_MIRROR_ORIGIN_HUB;
						ID_CA_JOINT_TOOL_MIRROR_ORIGIN_PARENT;
						ID_CA_JOINT_TOOL_MIRROR_ORIGIN_OBJECT;
					}
				}
				STATICTEXT { NEWLINE; }

				LINK ID_CA_JOINT_TOOL_MIRROR_ORIGIN_LINK { ACCEPT { Obase; } }
				STATICTEXT { JOINEND; }
			}
		}

		GROUP ID_CA_JOINT_TOOL_GROUP_MODIFIERS
		{
			COLUMNS 1;

			LONG ID_CA_JOINT_TOOL_MODIFIER_DEFAULT
			{
				CYCLE
				{
					ID_CA_JOINT_TOOL_MODIFIER_DRAW;
					ID_CA_JOINT_TOOL_MODIFIER_MOVE_JOINT;
					ID_CA_JOINT_TOOL_MODIFIER_MOVE_CHAIN;
					ID_CA_JOINT_TOOL_MODIFIER_SPLIT;
					ID_CA_JOINT_TOOL_MODIFIER_ALIGN;
					ID_CA_JOINT_TOOL_MODIFIER_SNAP;
				}
			}

			LONG ID_CA_JOINT_TOOL_MODIFIER_CTRL
			{
				CYCLE
				{
					ID_CA_JOINT_TOOL_MODIFIER_DRAW;
					ID_CA_JOINT_TOOL_MODIFIER_MOVE_JOINT;
					ID_CA_JOINT_TOOL_MODIFIER_MOVE_CHAIN;
					ID_CA_JOINT_TOOL_MODIFIER_SPLIT;
					ID_CA_JOINT_TOOL_MODIFIER_ALIGN;
					ID_CA_JOINT_TOOL_MODIFIER_SNAP;
				}
			}

			LONG ID_CA_JOINT_TOOL_MODIFIER_SHIFT
			{
				CYCLE
				{
					ID_CA_JOINT_TOOL_MODIFIER_DRAW;
					ID_CA_JOINT_TOOL_MODIFIER_MOVE_JOINT;
					ID_CA_JOINT_TOOL_MODIFIER_MOVE_CHAIN;
					ID_CA_JOINT_TOOL_MODIFIER_SPLIT;
					ID_CA_JOINT_TOOL_MODIFIER_ALIGN;
					ID_CA_JOINT_TOOL_MODIFIER_SNAP;
				}
			}
		}
	}
}
