CONTAINER NeutronSceneHook
{
	NAME name;

	GROUP NEUTRON_GROUP_VIEWPORT
	{
		DEFAULT 1;

		LONG NEUTRON_VIEWPORT_MODE {CYCLE {NEUTRON_VIEWPORT_MODE_NONE; NEUTRON_VIEWPORT_MODE_NEUTRON; NEUTRON_VIEWPORT_MODE_LEGACY;};}
	}
}
