CONTAINER GVhair_selection
{
	NAME GVhair_selection;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
		LONG GV_HAIR_SELECTION_MODE
		{ 
			CYCLE 
			{  
				GV_HAIR_SELECTION_MODE_ASIS; 
				GV_HAIR_SELECTION_MODE_POINTS;
				GV_HAIR_SELECTION_MODE_GUIDES;
			} 
		}
	}

	GROUP ID_GVPORTS
	{
		GVGENERALTAG GV_HAIR_SELECTION_INPUT_TAG { INPORT; STATICPORT; CREATEPORT; }
		BOOL GV_HAIR_SELECTION_OPERATOR_ON { INPORT; }

		LONG GV_HAIR_SELECTION_OUTPUT { OUTPORT; STATICPORT; CREATEPORT; ITERATOR; }
		LONG GV_HAIR_SELECTION_OUTPUT_COUNT { OUTPORT; }
	}
}
