CONTAINER GVhair_collision
{
	NAME GVhair_collision;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
		LINK GV_HAIR_COLLISION_OBJECT { ACCEPT { 1017305; } }
	}

	GROUP ID_GVPORTS
	{
		GVGENERALOBJECT GV_HAIR_COLLISION_INPUT_OBJECT { INPORT; STATICPORT; CREATEPORT; }
		LONG GV_HAIR_COLLISION_INPUT_NUM { INPORT; STATICPORT; CREATEPORT; }

		LONG GV_HAIR_COLLISION_OUTPUT_COUNT { OUTPORT; STATICPORT; CREATEPORT; }
		LONG GV_HAIR_COLLISION_OUTPUT_GID { OUTPORT; STATICPORT; CREATEPORT; }
		LONG GV_HAIR_COLLISION_OUTPUT_SID { OUTPORT; STATICPORT; CREATEPORT; }
		REAL GV_HAIR_COLLISION_OUTPUT_SEG_DELTA { OUTPORT; STATICPORT; CREATEPORT; }
		LONG GV_HAIR_COLLISION_OUTPUT_POLYINDEX { OUTPORT; STATICPORT; CREATEPORT; }
		VECTOR GV_HAIR_COLLISION_OUTPUT_HITPOINT { OUTPORT; }
		VECTOR GV_HAIR_COLLISION_OUTPUT_VELOCITY_IN { OUTPORT; }
		VECTOR GV_HAIR_COLLISION_OUTPUT_VELOCITY_OUT { OUTPORT; }
		REAL GV_HAIR_COLLISION_OUTPUT_FRAME_DELTA { OUTPORT; }
		GVGENERALOBJECT GV_HAIR_COLLISION_OUTPUT_OBJECT { OUTPORT; STATICPORT; CREATEPORT; }
	}
}
