CONTAINER GVhair_intersection
{
	NAME GVhair_intersection;
	INCLUDE GVbase;

	GROUP ID_GVPROPERTIES
	{
		LINK GV_HAIR_INTERSECTION_OBJECT { ACCEPT { 1017305; } }

		LONG GV_HAIR_INTERSECTION_MODE
		{ 
			CYCLE 
			{  
				GV_HAIR_INTERSECTION_MODE_GUIDE; 
				GV_HAIR_INTERSECTION_MODE_DYNAMIC_GUIDE;
				GV_HAIR_INTERSECTION_MODE_HAIR;
			} 
		}

		LONG GV_HAIR_INTERSECTION_VELOCITY_MODE
		{ 
			CYCLE 
			{  
				GV_HAIR_INTERSECTION_VELOCITY_MODE_FRAME; 
				GV_HAIR_INTERSECTION_VELOCITY_MODE_SECOND;
			} 
		}
	}

	GROUP ID_GVPORTS
	{
		GVGENERALOBJECT GV_HAIR_INTERSECTION_INPUT_OBJECT { INPORT; STATICPORT; CREATEPORT; }
		VECTOR GV_HAIR_INTERSECTION_INPUT_POSITION { INPORT; STATICPORT; CREATEPORT; }
		VECTOR GV_HAIR_INTERSECTION_INPUT_VELOCITY { INPORT; STATICPORT; CREATEPORT; }
		REAL GV_HAIR_INTERSECTION_INPUT_RADIUS { INPORT; STATICPORT; CREATEPORT; }

		BOOL GV_HAIR_INTERSECTION_INTERSECTION { OUTPORT; STATICPORT; CREATEPORT; }
		LONG GV_HAIR_INTERSECTION_GUIDE { OUTPORT; STATICPORT; CREATEPORT; }
		LONG GV_HAIR_INTERSECTION_SEGMENT { OUTPORT; STATICPORT; CREATEPORT; }
		REAL GV_HAIR_INTERSECTION_SEGMENT_T { OUTPORT; STATICPORT; CREATEPORT; }
		REAL GV_HAIR_INTERSECTION_RAY_T { OUTPORT; STATICPORT; CREATEPORT; }
		VECTOR GV_HAIR_INTERSECTION_POSITION { OUTPORT; STATICPORT; CREATEPORT; }
	}
}
