CONTAINER Ofur
{
	NAME Ofur;
	INCLUDE Obase;
	
	GROUP ID_OBJECTPROPERTIES
	{
		LINK FUR_GENERATOR_LINK { ACCEPT { Obase; Tpolygonselection; 5682; } }

		GROUP
		{
			COLUMNS 2;
			
			LONG FUR_GENERATOR_COUNT { MIN 1; }
			LONG FUR_GENERATOR_SEGMENTS { MIN 1; MAX 4096; }
			
			REAL FUR_GENERATOR_LENGTH { UNIT METER; MIN 0.0; }
			REAL FUR_GENERATOR_LENGTH_VAR { UNIT METER; MIN 0.0; }

			REAL FUR_GENERATOR_RANDOMIZE { UNIT DEGREE; MIN 0.0; }
			STATICTEXT { NEWLINE; }
		}

		SEPARATOR { LINE; }

		LINK FUR_GENERATOR_COMB_X { ACCEPT { 5682; } }
		LINK FUR_GENERATOR_COMB_Y { ACCEPT { 5682; } }
		LINK FUR_GENERATOR_COMB_Z { ACCEPT { 5682; } }

		SEPARATOR { LINE; }

		LINK FUR_GENERATOR_DENSITY { ACCEPT { 5682; } }

		SEPARATOR { LINE; }

		BOOL FUR_GENERATOR_RENDER_CACHED { HIDDEN; }

		GROUP
		{
			COLUMNS 2;

			BOOL FUR_GENERATOR_EDITOR { }
			REAL FUR_GENERATOR_LOD { UNIT PERCENT; MIN 0.0; MAX 100.0; }
		}
	}
}
