CONTAINER Ohairfeather
{
	NAME Ohairfeather;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		DEFAULT 1;

		GROUP
		{
			COLUMNS 2;

			BOOL FEATHER_OBJECT_SHOW_EDITOR { }
			REAL FEATHER_OBJECT_EDITOR_LOD { UNIT PERCENT; MIN 0.0; MAX 100.0; }
		}

		GROUP FEATHER_OBJECT_GROUP_GENERATE
		{
			GROUP
			{
				COLUMNS 2;

				LONG FEATHER_OBJECT_GENERATE
				{
					CYCLE
					{
						FEATHER_OBJECT_GENERATE_HAIR;
						FEATHER_OBJECT_GENERATE_SPLINES;
					}
				}

				BOOL FEATHER_OBJECT_REVERSE { }
			}

			LONG FEATHER_OBJECT_SEGMENTS { MIN 1; MAX 1024; }
		}

		GROUP FEATHER_OBJECT_GROUP_SPACING
		{
			DEFAULT 1;

			LONG FEATHER_OBJECT_SPACING
			{
				CYCLE
				{
					FEATHER_OBJECT_SPACING_COUNT;
					FEATHER_OBJECT_SPACING_SPACE;
				}
			}

			GROUP
			{
				COLUMNS 2;

				BOOL FEATHER_OBJECT_RELATIVE { }
				REAL FEATHER_OBJECT_REFERENCE { UNIT METER; MIN 0.0; }
			}

			GROUP
			{
				COLUMNS 2;

				REAL FEATHER_OBJECT_RACHIS_RADIUS_BASE { UNIT METER; MIN 0.0; }
				REAL FEATHER_OBJECT_RACHIS_RADIUS_TOP { UNIT METER; MIN 0.0; }

				REAL FEATHER_OBJECT_BARB_START { UNIT PERCENT; MIN 0.0; MAX 100.0; }
				REAL FEATHER_OBJECT_BARB_END { UNIT PERCENT; MIN 0.0; MAX 100.0; }

				REAL FEATHER_OBJECT_BARB_SPACING { UNIT METER; MIN 0.0; STEP 0.1; }
				REAL FEATHER_OBJECT_BARB_SPACING_VAR { UNIT METER; MIN 0.0; STEP 0.1; }

				LONG FEATHER_OBJECT_BARB_COUNT { MIN 1; }
				STATICTEXT { NEWLINE; }

				REAL FEATHER_OBJECT_BARB_LENGTH { UNIT METER; MIN 0.0; }
				REAL FEATHER_OBJECT_BARB_LENGTH_VAR { UNIT METER; MIN 0.0; }
			}
		}

		GROUP FEATHER_OBJECT_GROUP_DISPLACE
		{	
			COLUMNS 2;

			REAL FEATHER_OBJECT_BARB_Y_DISP_T { UNIT METER; MIN 0.0; }
			REAL FEATHER_OBJECT_BARB_Y_DISP_T_VAR { UNIT METER; MIN 0.0; }

			REAL FEATHER_OBJECT_BARB_Y_DISP { UNIT METER; MIN 0.0; }
			REAL FEATHER_OBJECT_BARB_Y_DISP_VAR { UNIT METER; MIN 0.0; }

			REAL FEATHER_OBJECT_BARB_Z_DISP { UNIT METER; MIN 0.0; }
			REAL FEATHER_OBJECT_BARB_Z_DISP_VAR { UNIT METER; MIN 0.0; }
		}

		GROUP FEATHER_OBJECT_GROUP_ROTATION
		{
			COLUMNS 2;

			REAL FEATHER_OBJECT_RACHIS_ROTATION_DELTA { UNIT DEGREE; }
			REAL FEATHER_OBJECT_RACHIS_ROTATION_DELTA_VAR { UNIT DEGREE; }

			REAL FEATHER_OBJECT_RACHIS_ROTATION { UNIT DEGREE; }
			REAL FEATHER_OBJECT_RACHIS_ROTATION_VAR { UNIT DEGREE; MIN 0.0; }

			REAL FEATHER_OBJECT_BARB_ROTATION_Y_VAR { UNIT DEGREE; MIN 0.0; }
			REAL FEATHER_OBJECT_BARB_ROTATION_Z_VAR { UNIT DEGREE; MIN 0.0; }
		}

		GROUP FEATHER_OBJECT_GROUP_GAPS
		{
			COLUMNS 2;

			REAL FEATHER_OBJECT_BARB_GAPS { UNIT METER; MIN 0.0; }
			REAL FEATHER_OBJECT_BARB_GAPS_VAR { UNIT METER; MIN 0.0; }

			REAL FEATHER_OBJECT_BARB_GAPS_OCCUR { UNIT PERCENT; MIN 0.0; MAX 100.0; }
			STATICTEXT { NEWLINE; }
		}
	}

	GROUP FEATHER_OBJECT_GROUP_SHAPE
	{
		DEFAULT 1;

		GROUP FEATHER_OBJECT_GROUP_RACHIS
		{
			DEFAULT 1;

			COLUMNS 2;
			
			SPLINE FEATHER_OBJECT_RACHIS_LEFT { }
			SPLINE FEATHER_OBJECT_RACHIS_RIGHT { }
		}

		GROUP FEATHER_OBJECT_GROUP_SECTION
		{
			DEFAULT 1;

			COLUMNS 2;

			SPLINE FEATHER_OBJECT_RACHIS_SECTION_LEFT { }
			SPLINE FEATHER_OBJECT_RACHIS_SECTION_RIGHT { }
		}

		GROUP FEATHER_OBJECT_GROUP_CURVE
		{
			DEFAULT 1;

			COLUMNS 2;

			SPLINE FEATHER_OBJECT_RACHIS_CURVE_LEFT { }
			SPLINE FEATHER_OBJECT_RACHIS_CURVE_RIGHT { }
		}
	}
}
