CONTAINER prefshaircolor
{
	NAME prefshaircolor;
	SCALE_V;

	GROUP PREF_HAIRCOLOR_MAIN_GROUP
	{
		DEFAULT 1;
		COLUMNS 1;
		SCALE_V;
		
		LISTVIEW PREF_HAIRCOLOR_LIST { COLOR; SCALE_V;}
		SEPARATOR { }
		COLOR PREF_HAIRCOLOR_COLORS { OPEN; }

		SEPARATOR { LINE; }

		BUTTON PREF_HAIRCOLOR_RESET { }
	}
}
