CONTAINER Thairselection
{
	NAME Thairselection;
	INCLUDE Tbase;

	GROUP ID_TAGPROPERTIES
	{
		GROUP
		{
			COLUMNS 2;

			BUTTON HAIR_SELECTION_TAG_SET { }
			BUTTON HAIR_SELECTION_TAG_RESTORE { }

			SEPARATOR { }
			STATICTEXT { NEWLINE; }

			BUTTON HAIR_SELECTION_TAG_SELECT { }
			BUTTON HAIR_SELECTION_TAG_DESELECT { }

			SEPARATOR { }
			STATICTEXT { NEWLINE; }
			
			BUTTON HAIR_SELECTION_TAG_LOCK { }
			BUTTON HAIR_SELECTION_TAG_UNLOCK { }

			SEPARATOR { }
			STATICTEXT { NEWLINE; }
			
			BUTTON HAIR_SELECTION_TAG_HIDE { }
			BUTTON HAIR_SELECTION_TAG_SHOW { }
		}
	}
}
