CONTAINER Thairlight
{
	NAME Thairlight;
	INCLUDE Tbase;

	GROUP ID_TAGPROPERTIES
	{
		BOOL HAIR_LIGHT_TAG_INCLUDE { }

		SEPARATOR { LINE; }

		LONG HAIR_LIGHT_TAG_SHADOWS
		{
			CYCLE
			{
				HAIR_LIGHT_TAG_SHADOWS_NONE;
				HAIR_LIGHT_TAG_SHADOWS_SOFT;
			}
		}

		SEPARATOR { }

		REAL HAIR_LIGHT_TAG_SHADOW_TRANS_ACCURACY { UNIT PERCENT; MIN 0.0; MAX 100.0; HIDDEN; }
		REAL HAIR_LIGHT_TAG_SHADOW_DIST_ACCURACY { UNIT METER; MIN 0.0; HIDDEN; }

		SEPARATOR { LINE; }

		LONG HAIR_LIGHT_TAG_SHADOW_AA_LEVEL
		{
			HIDDEN;

			CYCLE
			{
				HAIR_LIGHT_TAG_SHADOW_AA_NONE;
				HAIR_LIGHT_TAG_SHADOW_AA_LOW;
				HAIR_LIGHT_TAG_SHADOW_AA_MED;
				HAIR_LIGHT_TAG_SHADOW_AA_HIGH;
				HAIR_LIGHT_TAG_SHADOW_AA_BEST;
				HAIR_LIGHT_TAG_SHADOW_AA_USER;
			}
		}

		REAL HAIR_LIGHT_TAG_SHADOW_AA_USER_LEVEL { UNIT PERCENT; MIN 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; HIDDEN; }

		REAL HAIR_LIGHT_TAG_SHADOW_DENSITY	{ UNIT PERCENT; MIN 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		REAL HAIR_LIGHT_TAG_CAST_SHADOW		{ UNIT PERCENT; MIN 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
		LONG HAIR_LIGHT_TAG_SHADOW_SAMPLE_SIZE { MIN 0; MAX 512; }

		GROUP
		{
			COLUMNS 2;

			LONG HAIR_LIGHT_TAG_SHADOWS_MAP
			{
				CYCLE
				{
					HAIR_LIGHT_TAG_SHADOWS_MAP_250;
					HAIR_LIGHT_TAG_SHADOWS_MAP_500;
					HAIR_LIGHT_TAG_SHADOWS_MAP_750;
					HAIR_LIGHT_TAG_SHADOWS_MAP_1000;
					HAIR_LIGHT_TAG_SHADOWS_MAP_1250;
					HAIR_LIGHT_TAG_SHADOWS_MAP_1500;
					HAIR_LIGHT_TAG_SHADOWS_MAP_1750;
					HAIR_LIGHT_TAG_SHADOWS_MAP_2000;
					HAIR_LIGHT_TAG_SHADOWS_MAP_CUSTOM;
				}
			}
			STATICTEXT { NEWLINE; }
		}

		LONG HAIR_LIGHT_TAG_MAP_SIZE { MIN 64; MAX 16384; }

		REAL HAIR_LIGHT_TAG_SHADOW_WIDTH { UNIT DEGREE; MIN 0.0; MAX 89.0; HIDDEN; }
	}
}
