CONTAINER Thairconstraint
{
	NAME Thairconstraint;
	INCLUDE Tbase;

	GROUP ID_TAGPROPERTIES
	{
		BOOL HAIR_CONSTRAINTS_TAG_DRAW_ANCHOR { }

		GROUP
		{
			COLUMNS 4;

			BUTTON HAIR_CONSTRAINTS_TAG_SET_ANCHOR { }
			BUTTON HAIR_CONSTRAINTS_TAG_RELEASE_ANCHOR { }
			BUTTON HAIR_CONSTRAINTS_TAG_CLEAR_ANCHOR { }
		}

		LINK HAIR_CONSTRAINTS_TAG_ANCHOR_LINK { ACCEPT { Obase; } }

		SEPARATOR { LINE; }

		REAL HAIR_CONSTRAINTS_TAG_STRENGTH { UNIT PERCENT; MIN 0.0; MAX 100.0; }
		REAL HAIR_CONSTRAINTS_TAG_OFFSET { UNIT PERCENT; }

		SEPARATOR { LINE; }

		LINK HAIR_CONSTRAINTS_TAG_STRENGTH_LINK { ACCEPT { 5682; 1018329; } }
		LINK HAIR_CONSTRAINTS_TAG_OFFSET_LINK { ACCEPT { 5682; 1018329; } }
	}
}
