CONTAINER Thairprefs
{
	NAME Thairprefs;

	GROUP HAIR_PREFS_MAIN_GROUP
	{
		DEFAULT 1; COLUMNS 2;

		BOOL HAIR_PREFS_SETUP_AUTOVP { }
		STATICTEXT{}
		BOOL HAIR_PREFS_SETUP_AUTO_LINK { }
		STATICTEXT{}
		
		BOOL HAIR_PREFS_SETUP_AUTO_MATERIAL { }
		STATICTEXT{}
		BOOL HAIR_PREFS_SETUP_TOCHILD { }
		STATICTEXT{}

		SEPARATOR { LINE; }
		STATICTEXT {JOINENDSCALE;}	

		BOOL HAIR_PREFS_HIGHLIGHTING { }
		STATICTEXT{}
		BOOL HAIR_PREFS_UNROOTED { }
		STATICTEXT{}

		LONG HAIR_PREFS_SHOW_CURSOR
		{
			CYCLE
			{
				HAIR_PREFS_SHOW_CURSOR_OFF;
				HAIR_PREFS_SHOW_CURSOR_ALWAYS;
				HAIR_PREFS_SHOW_CURSOR_DRAG;
			}
		}
		STATICTEXT{}
	
		SEPARATOR { LINE; }
		STATICTEXT {JOINENDSCALE;}	

		BOOL HAIR_PREFS_OBJECT_UNDO { }
		STATICTEXT{}
		BOOL HAIR_PREFS_DYNAMICS_UNDO { }
		STATICTEXT{}

		SEPARATOR { LINE; }
		STATICTEXT {JOINENDSCALE;}	

		LONG HAIR_PREFS_PREVIEW
		{
			CYCLE
			{
				HAIR_PREFS_PREVIEW_STANDARD;
				HAIR_PREFS_PREVIEW_CUBE;
				HAIR_PREFS_PREVIEW_ROUNDCUBE;
				HAIR_PREFS_PREVIEW_PLANE;
				HAIR_PREFS_PREVIEW_CYLINDER;
				HAIR_PREFS_PREVIEW_TORUS;
				HAIR_PREFS_PREVIEW_PLANEBACK;
				HAIR_PREFS_PREVIEW_SPHERE;
				HAIR_PREFS_PREVIEW_DOUBLETORUS;
				HAIR_PREFS_PREVIEW_KNOT;
				HAIR_PREFS_PREVIEW_STRAND;
				HAIR_PREFS_PREVIEW_CUSTOM;
			}
		}
		STATICTEXT{}
		
		LONG HAIR_PREFS_CUSTOMPREVIEW
		{
			CYCLE
			{
			}
		}
	}
}
