CONTAINER Thairsplinedynamics
{
	NAME Thairsplinedynamics;
	INCLUDE Texpression;

	GROUP ID_TAGPROPERTIES
	{
		//BOOL HAIR_SDYNAMICS_TAG_ENABLE { }
		BOOL HAIR_SDYNAMICS_TAG_COLLISIONS { }
		BOOL HAIR_SDYNAMICS_TAG_EXTRA_STIFF { }

		SEPARATOR { }

		BUTTON HAIR_SDYNAMICS_TAG_SET_STATE { }
	}
		
	GROUP HAIR_SDYNAMICS_TAG_GROUP_PROPERTIES
	{
		GROUP
		{
			COLUMNS 2;

			REAL HAIR_SDYNAMICS_TAG_DRAG { UNIT PERCENT; MIN 0.0; MAX 100.0; }
			REAL HAIR_SDYNAMICS_TAG_RADIUS { MIN 0.0; }
			
			REAL HAIR_SDYNAMICS_TAG_STIFFNESS   { UNIT PERCENT; MIN 0.0; MAX 100.0; }
			REAL HAIR_SDYNAMICS_TAG_RUBBER   { UNIT PERCENT; MIN 0.0; MAX 100.0; }

			REAL HAIR_SDYNAMICS_REST_MIX   { UNIT PERCENT; MIN 0.0; MAX 100.0; }
			REAL HAIR_SDYNAMICS_REST_HOLD   { UNIT PERCENT; MIN 0.0; MAX 100.0; }
		
			REAL HAIR_SDYNAMICS_ELASTIC_LIMIT { UNIT PERCENT; MIN 0.0; }
			REAL HAIR_SDYNAMICS_ELASTIC_DEFORM { UNIT PERCENT; MIN 0.0; MAX 100.0; }
		}

		SEPARATOR { LINE; }

		BOOL HAIR_SDYNAMICS_TAG_DRAW_FIXED { }

		GROUP
		{
			COLUMNS 2;

			REAL HAIR_SDYNAMICS_TAG_MASS { }
			BUTTON HAIR_SDYNAMICS_TAG_SETMASS { }
		}

		SEPARATOR { }

		GROUP
		{
			COLUMNS 4;

			STATICTEXT HAIR_SDYNAMICS_TAG_FIXED { NOTEXT; }
			BUTTON HAIR_SDYNAMICS_TAG_SET_FIXED { }
			BUTTON HAIR_SDYNAMICS_TAG_RELEASE_FIXED { }
			BUTTON HAIR_SDYNAMICS_TAG_CLEAR_FIXED { }
		}
	}

	GROUP HAIR_SDYNAMICS_TAG_GROUP_FORCES
	{
		SCALE_V;

		GROUP
		{
			REAL HAIR_SDYNAMICS_TAG_GRAVITY { STEP 0.1; }

			SEPARATOR { }

			LONG HAIR_SDYNAMICS_TAG_FORCES_INCEXC
			{
				CYCLE
				{
					HAIR_SDYNAMICS_TAG_INCEXC_INCLUDE;
					HAIR_SDYNAMICS_TAG_INCEXC_EXCLUDE;
				}
			}
		}

		IN_EXCLUDE  HAIR_SDYNAMICS_TAG_FORCES_INCLUDE
		{
			NUM_FLAGS 0; INIT_STATE 0; SEND_SELCHNGMSG 1; SCALE_V;
			ACCEPT { Obase; };
		}
	}

	GROUP HAIR_SDYNAMICS_TAG_GROUP_CACHE
	{
		BOOL HAIR_SDYNAMICS_CACHE_ENABLE { }

		SEPARATOR { LINE; }

		GROUP
		{
			COLUMNS 2;

			BUTTON HAIR_SDYNAMICS_CACHE_CALCULATE {  FIT_H; }
			BOOL HAIR_SDYNAMICS_CACHE_COMPRESSED { ANIM OFF; }				

			BUTTON HAIR_SDYNAMICS_CACHE_DELETE { FIT_H; }
			STATICTEXT HAIR_SDYNAMICS_CACHE_INFO2 { SCALE_H; }

			BUTTON HAIR_SDYNAMICS_CACHE_CACHE_FRAME {  FIT_H; }
			STATICTEXT { DUMMY; SCALE_H; }

			BUTTON HAIR_SDYNAMICS_CACHE_CACHE_LOAD {  FIT_H; }
			STATICTEXT { DUMMY; SCALE_H; }

			BUTTON HAIR_SDYNAMICS_CACHE_CACHE_SAVE {  FIT_H; }
			STATICTEXT { DUMMY; SCALE_H; }

			SEPARATOR { } STATICTEXT { JOINENDSCALE; }

			LONG HAIR_SDYNAMICS_CACHE_CACHE_LIMIT { MIN 1; MAX 1000; ANIM OFF; }
			STATICTEXT HAIR_SDYNAMICS_CACHE_TEXT_LIMIT {}
		}
	}

	GROUP HAIR_SDYNAMICS_TAG_GROUP_ADVANCED
	{
		LONG HAIR_SDYNAMICS_TAG_SUBDIV { MIN 1; MAX 100; }
		LONG HAIR_SDYNAMICS_TAG_ITERATIONS  { MIN 0; }

		SEPARATOR { }

		GROUP
		{
			COLUMNS 3;

			BOOL HAIR_SDYNAMICS_TAG_AUTOTIME { ANIM OFF; }

			BASETIME HAIR_SDYNAMICS_TAG_START { ANIM OFF; }
			BASETIME HAIR_SDYNAMICS_TAG_STOP  { ANIM OFF; }
		}
	}
}
