CONTAINER Thaircollider
{
	NAME Thaircollider;
	INCLUDE Tbase;

	GROUP ID_TAGPROPERTIES
	{
		BOOL HAIR_COLLIDER_COLLISIONS { }

		REAL HAIR_COLLIDER_FRICTION { UNIT PERCENT; MIN 0.0; MAX 100.0; }
		REAL HAIR_COLLIDER_BOUNCE { UNIT PERCENT; MIN 0.0; }

		SEPARATOR { LINE; }

		BOOL HAIR_COLLIDER_FORCES { }

		GROUP
		{
			COLUMNS 2;

			REAL HAIR_COLLIDER_FORCES_OBJECTS_RADIUS { UNIT METER; MIN 0.0; }
			STATICTEXT { NEWLINE; }

			REAL HAIR_COLLIDER_FORCE_STRENGTH { }
			REAL HAIR_COLLIDER_FORCES_OBJECTS_MAXSTRENGTH { }
		}

		LONG HAIR_COLLIDER_FORCES_OBJECTS_FALLOFF
		{
			CYCLE
			{
				HAIR_COLLIDER_FORCES_FALLOFF_CONSTANT;
				HAIR_COLLIDER_FORCES_FALLOFF_LINEAR;
				HAIR_COLLIDER_FORCES_FALLOFF_SQUARE;
				HAIR_COLLIDER_FORCES_FALLOFF_CUBIC;
				HAIR_COLLIDER_FORCES_FALLOFF_CUSTOM;
			}
		}

		SPLINE HAIR_COLLIDER_FORCES_OBJECTS_FALLOFF_SPLINE { }

		SEPARATOR { LINE; }

		LINK HAIR_COLLIDER_LINK { ACCEPT { 5673; } }
		LINK HAIR_COLLIDER_FORCE_STRENGTH_LINK { ACCEPT { 5682; } }
	}
}
