CONTAINER ToolHairSymmetry
{
	NAME ToolHairSymmetry;
	INCLUDE ToolBase;

	HIDE MDATA_COMMANDGROUP;

	GROUP MDATA_MAINGROUP
	{
		NOTITLE;

		BOOL HAIR_SYMMETRY { }
		
		REAL HAIR_SYMMETRY_SEARCH { UNIT METER; MIN 0.0; }
				
		GROUP
		{
			COLUMNS 2;

			LONG HAIR_SYMMETRY_COORDS
			{
				CYCLE
				{
					HAIR_SYMMETRY_COORDS_WORLD;
					HAIR_SYMMETRY_COORDS_LOCAL;
					HAIR_SYMMETRY_COORDS_OBJECT;
				}
			}

			LONG HAIR_SYMMETRY_PLANE
			{
				CYCLE
				{
					HAIR_SYMMETRY_PLANE_XY;
					HAIR_SYMMETRY_PLANE_XZ;
					HAIR_SYMMETRY_PLANE_YZ;
				}
			}
		}

		LINK HAIR_SYMMETRY_LINK { ACCEPT { Obase; } }
	}
}
