CONTAINER ToolHairComb
{
	NAME ToolHairComb;
	INCLUDE ToolBase;

	GROUP MDATA_MAINGROUP
	{
		GROUP
		{
			COLUMNS 2;

			LONG HAIR_TOOL_COMB_DIRECTION
			{
				CYCLE
				{
					HAIR_TOOL_COMB_DIRECTION_CAMERA_X;
					HAIR_TOOL_COMB_DIRECTION_CAMERA_Y;
					HAIR_TOOL_COMB_DIRECTION_CAMERA_Z;
					HAIR_TOOL_COMB_DIRECTION_WORLD_X;
					HAIR_TOOL_COMB_DIRECTION_WORLD_Y;
					HAIR_TOOL_COMB_DIRECTION_WORLD_Z;
					HAIR_TOOL_COMB_DIRECTION_LOCAL_X;
					HAIR_TOOL_COMB_DIRECTION_LOCAL_Y;
					HAIR_TOOL_COMB_DIRECTION_LOCAL_Z;
					HAIR_TOOL_COMB_DIRECTION_SPLINE;
					HAIR_TOOL_COMB_DIRECTION_SHADER;
				}
			}

			REAL HAIR_TOOL_COMB_STRENGTH { UNIT PERCENT; MIN -100.0; MAX 100.0; }
		}

		LINK HAIR_TOOL_COMB_SPLINE { ACCEPT { Obase; } }
		TEXTURE HAIR_TOOL_COMB_SHADER { }

		SPLINE HAIR_TOOL_COMB_CURVE
		{ 
		}

		GROUP
		{
			COLUMNS 2;

			BOOL HAIR_TOOL_COMB_FROMROOT { }
			BOOL HAIR_TOOL_COMB_INTERSECT { }

			BOOL HAIR_TOOL_COMB_WEIGHTED { }
			STATICTEXT { NEWLINE; }
		}

		REAL HAIR_TOOL_COMB_WEIGHT { UNIT PERCENT; MIN 0.0; MAX 100.0; }

		GROUP
		{
			COLUMNS 2;

			BOOL HAIR_TOOL_COMB_LIMIT_DISTANCE { }
			REAL HAIR_TOOL_COMB_DISTANCE { UNIT METER; MIN 0.0; }
		}
	}
}
