CONTAINER ToolHairGrowSelection
{
	NAME ToolHairGrowSelection;
	INCLUDE ToolBase;

	GROUP MDATA_MAINGROUP
	{
		LONG HAIR_GROWSELECTION_NEIGHBORS { MIN 0; }
		REAL HAIR_GROWSELECTION_DISTANCE { MIN 0.0; }
	}
}
