CONTAINER ToolHairPush
{
	NAME ToolHairPush;
	INCLUDE ToolBase;

	GROUP MDATA_MAINGROUP
	{		
		BOOL HAIR_TOOL_PUSH_SELECT { }

		SEPARATOR { LINE; }

		GROUP
		{
			COLUMNS 2;

			BOOL HAIR_TOOL_PUSH_SURFACE { }
			BOOL HAIR_TOOL_PUSH_USE_NORMAL { }

			REAL HAIR_TOOL_PUSH_DISTANCE	{ UNIT METER; MIN 0.0; }
			STATICTEXT { NEWLINE; }
		}

		SPLINE HAIR_TOOL_PUSH_CURVE
		{ 
		}

		SEPARATOR { LINE; }
		
		GROUP
		{
			COLUMNS 2;

			BOOL HAIR_TOOL_PUSH_GUIDES { }
			STATICTEXT { NEWLINE; }

			REAL HAIR_TOOL_PUSH_GUIDES_DISTANCE { UNIT METER; MIN 0.0; }
			REAL HAIR_TOOL_PUSH_GUIDES_RELAX { MIN 4; MAX 1000; }
		}

		SPLINE HAIR_TOOL_PUSH_GUIDES_CURVE
		{ 
		}
	}
}
