CONTAINER ToolHairSoftSelection
{
	NAME ToolHairSoftSelection;
	INCLUDE ToolBase;

	HIDE MDATA_COMMANDGROUP;

	GROUP MDATA_MAINGROUP
	{
		NOTITLE;

		GROUP
		{
			COLUMNS 2;

			BOOL HAIR_SOFTSELECTION { }
			BOOL HAIR_SOFTSELECTION_PREVIEW { }

			BOOL HAIR_SOFTSELECTION_TWEAK { }
			BOOL HAIR_SOFTSELECTION_VISIBLE { }
		}

		SEPARATOR { }

		GROUP
		{
			COLUMNS 2;
						
			LONG HAIR_SOFTSELECTION_TYPE
			{
				CYCLE
				{
					HAIR_SOFTSELECTION_TYPE_SINGLE;
					HAIR_SOFTSELECTION_TYPE_VOLUME;
					HAIR_SOFTSELECTION_TYPE_ROOT;
				}
			}
			
			LONG HAIR_SOFTSELECTION_SPACE
			{
				CYCLE
				{
					HAIR_SOFTSELECTION_SPACE_WORLD;
					HAIR_SOFTSELECTION_SPACE_SCREEN;
				}
			}
		}

		SEPARATOR { }

		REAL HAIR_SOFTSELECTION_RADIUS		{ UNIT METER; MIN 0.0; }

		REAL HAIR_SOFTSELECTION_STRENGTH	{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		BOOL HAIR_SOFTSELECTION_CLIP { }

		LONG HAIR_SOFTSELECTION_FALLOFF
		{
			CYCLE
			{
				HAIR_SOFTSELECTION_FALLOFF_NONE;
				HAIR_SOFTSELECTION_FALLOFF_LINEAR;
				HAIR_SOFTSELECTION_FALLOFF_DOME;
				HAIR_SOFTSELECTION_FALLOFF_BELL;
				HAIR_SOFTSELECTION_FALLOFF_CIRCLE;
				HAIR_SOFTSELECTION_FALLOFF_NEEDLE;
				HAIR_SOFTSELECTION_FALLOFF_SPLINE;
			}
		}

		REAL HAIR_SOFTSELECTION_WIDTH { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }

		SPLINE HAIR_SOFTSELECTION_FALLOFF_CURVE
		{ 
		}
	}
}
