CONTAINER ToolHairAddRoot
{
	NAME ToolHairAddRoot;
	INCLUDE ToolBase;

	HIDE MDATA_COMMANDGROUP;

	GROUP MDATA_MAINGROUP
	{
		GROUP
		{
			COLUMNS 2;

			REAL HAIR_TOOL_ADDROOT_RADIUS { MIN 0.0; }
			LONG HAIR_TOOL_ADDROOT_STEP { MIN 0; }

			LONG HAIR_TOOL_ADDROOT_COUNT { MIN 1; }
			REAL HAIR_TOOL_ADDROOT_LENGTH { UNIT METER; MIN 0.0; }

			REAL HAIR_TOOL_ADDROOT_MINSPACING { UNIT METER; MIN 0.0; }
			LONG HAIR_TOOL_ADDROOT_PEN
			{
				CYCLE
				{
					HAIR_TOOL_ADDROOT_PEN_NONE;
					HAIR_TOOL_ADDROOT_PEN_RADIUS;
					HAIR_TOOL_ADDROOT_PEN_LENGTH;
					HAIR_TOOL_ADDROOT_PEN_COUNT;
				}
			}
			
			BOOL HAIR_TOOL_ADDROOT_INTERPOLATE { }
			REAL HAIR_TOOL_ADDROOT_INTERPOLATE_STRENGTH { UNIT PERCENT; MIN 0.0; MAX 100.0; }
		}
	}
}
