CONTAINER ToolHairSelection
{
	NAME ToolHairSelection;
	INCLUDE ToolBase;

	GROUP MDATA_MAINGROUP
	{
		GROUP
		{
			COLUMNS 2;

			LONG HAIR_SELECTION_MODE
			{
				CYCLE
				{
					HAIR_SELECTION_MODE_NEW;
					HAIR_SELECTION_MODE_ADD;
					HAIR_SELECTION_MODE_REMOVE;
				}
			}
			STATICTEXT { NEWLINE; }

			LONG HAIR_SELECTION_SELECT
			{
				CYCLE
				{
					HAIR_SELECTION_SELECT_UNROOTED;
					HAIR_SELECTION_SELECT_INTERSECTING;
					HAIR_SELECTION_SELECT_ZERO;
				}
			}
			BOOL HAIR_SELECTION_INVERT { }
		}
	}
}
