CONTAINER ToolHairCurl
{
	NAME ToolHairCurl;
	INCLUDE ToolBase;

	GROUP MDATA_MAINGROUP
	{
		REAL HAIR_TOOL_CURL_STRENGTH { UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }

		GROUP
		{
			COLUMNS 2;
		
			REAL HAIR_TOOL_CURL_ANGLE { UNIT DEGREE; }
			REAL HAIR_TOOL_CURL_TIGHTNESS { UNIT PERCENT; }

			REAL HAIR_TOOL_CURL_AMP_X { UNIT METER; MIN 0.0; }
			REAL HAIR_TOOL_CURL_PERIOD_X { UNIT METER; MIN 0.0; }

			REAL HAIR_TOOL_CURL_AMP_Y { UNIT METER; MIN 0.0; }
			REAL HAIR_TOOL_CURL_PERIOD_Y { UNIT METER; MIN 0.0; }
		}
	}

	GROUP HAIR_TOOL_CURL_GROUP_CURLING
	{
		SPLINE HAIR_TOOL_CURL_X
		{ 
		}

		SPLINE HAIR_TOOL_CURL_Y
		{ 
		}
	}

	GROUP HAIR_TOOL_CURL_GROUP_STRENGTH
	{
		SPLINE HAIR_TOOL_CURL_STRENGTH_X
		{ 
		}

		SPLINE HAIR_TOOL_CURL_STRENGTH_Y
		{ 
		}
	}

	GROUP HAIR_TOOL_CURL_GROUP_TIGHTEN
	{
		SPLINE HAIR_TOOL_CURL_TIGHTEN
		{ 
		}
	}
}
