CONTAINER ToolHairStraighten
{
	NAME ToolHairStraighten;
	INCLUDE ToolBase;

	GROUP MDATA_MAINGROUP
	{
		GROUP
		{
			COLUMNS 2;

			LONG HAIR_TOOL_STRAIGHTEN_TOWARDS
			{
				CYCLE
				{
					HAIR_TOOL_STRAIGHTEN_TOWARDS_ROOT;
					HAIR_TOOL_STRAIGHTEN_TOWARDS_NORMAL;
					HAIR_TOOL_STRAIGHTEN_TOWARDS_GUIDE;
				}
			}

			REAL HAIR_TOOL_STRAIGHTEN_STRENGTH	{ UNIT PERCENT; MIN -100.0; MAX 100.0; }
		}

		SPLINE HAIR_TOOL_STRAIGHTEN_CURVE
		{ 
		}
	}
}
