CONTAINER ToolHairMirror
{
	NAME ToolHairMirror;
	INCLUDE ToolBase;

	GROUP MDATA_MAINGROUP
	{		
		GROUP
		{
			COLUMNS 2;

			LONG HAIR_MIRROR_MODE
			{
				CYCLE
				{
					HAIR_MIRROR_MODE_CLONE;
					HAIR_MIRROR_MODE_INTERPOLATED;
				}
			}

			BOOL HAIR_MIRROR_ROOT { }
		}

		REAL HAIR_MIRROR_STRENGTH { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }

		GROUP
		{
			COLUMNS 2;

			REAL HAIR_MIRROR_SEARCH { UNIT METER; MIN 0.0; }
			LONG HAIR_MIRROR_NEIGHBORS { }
		}
				
		GROUP
		{
			COLUMNS 2;

			LONG HAIR_MIRROR_COORDS
			{
				CYCLE
				{
					HAIR_MIRROR_COORDS_WORLD;
					HAIR_MIRROR_COORDS_LOCAL;
					HAIR_MIRROR_COORDS_OBJECT;
				}
			}

			LONG HAIR_MIRROR_PLANE
			{
				CYCLE
				{
					HAIR_MIRROR_PLANE_XY;
					HAIR_MIRROR_PLANE_XZ;
					HAIR_MIRROR_PLANE_YZ;
				}
			}
		}

		LINK HAIR_MIRROR_LINK { ACCEPT { Obase; } }
	}
}
