CONTAINER ToolHairClump
{
	NAME ToolHairClump;
	INCLUDE ToolBase;

	GROUP MDATA_MAINGROUP
	{
		LONG HAIR_TOOL_CLUMP_TO
		{
			CYCLE
			{
				HAIR_TOOL_CLUMP_TO_LINE;
				HAIR_TOOL_CLUMP_TO_CENTER;
				HAIR_TOOL_CLUMP_TO_AVERAGE;
			}
		}

		BOOL HAIR_TOOL_CLUMP_FIXED_LENGTH { } 

		REAL HAIR_TOOL_CLUMP_STRENGTH	{ UNIT PERCENT; MIN -100.0; MAX 100.0; }

		SPLINE HAIR_TOOL_CLUMP_CURVE
		{ 
		}

		BOOL HAIR_TOOL_CLUMP_ROTATE { }
		REAL HAIR_TOOL_CLUMP_FREQ { UNIT DEGREE; STEP 0.1; }

		SPLINE HAIR_TOOL_CLUMP_FREQ_CURVE
		{ 
		}
	}
}
