CONTAINER ToolHairPolySelect
{
	NAME ToolHairPolySelect;
	INCLUDE ToolHairLiveSelect;

	HIDE MDATA_COMMANDGROUP;
	HIDE HAIR_LIVESELECT_RADIUS;
	HIDE HAIR_LIVESELECT_SHAPE;
	HIDE HAIR_LIVESELECT_SHAPE_ASPECT;
	HIDE HAIR_LIVESELECT_SHAPE_ANGLE;
	HIDE HAIR_LIVESELECT_PEN;

	GROUP MDATA_MAINGROUP
	{
	}
}
