CONTAINER ToolHairBrush
{
	NAME ToolHairBrush;
	INCLUDE ToolHairLiveSelect;

	HIDE MDATA_COMMANDGROUP;
	HIDE HAIR_LIVESELECT_LOCKED;

	GROUP MDATA_MAINGROUP
	{
		SEPARATOR { LINE;  }

		GROUP
		{
			COLUMNS 2;

			BOOL HAIR_TOOL_BRUSH_LOCK { }
			BOOL HAIR_TOOL_BRUSH_SELECTED { }

			BOOL HAIR_TOOL_BRUSH_IK { }
			BOOL HAIR_TOOL_BRUSH_COLLISIONS { }

			REAL HAIR_TOOL_BRUSH_RADIUS { UNIT METER; MIN 0.0; }
			STATICTEXT { NEWLINE; }
		}

		SEPARATOR { LINE; }
		
		GROUP
		{
			COLUMNS 2;

			LONG HAIR_TOOL_BRUSH_TYPE
			{
				CYCLE
				{
					HAIR_TOOL_BRUSH_TYPE_MOVE;
					HAIR_TOOL_BRUSH_TYPE_TWIST;
					HAIR_TOOL_BRUSH_TYPE_REPEL;
					HAIR_TOOL_BRUSH_TYPE_KINK;
					HAIR_TOOL_BRUSH_TYPE_SMOOTH;
					HAIR_TOOL_BRUSH_TYPE_SCALE;
					HAIR_TOOL_BRUSH_TYPE_STRAIGHTEN;
					HAIR_TOOL_BRUSH_TYPE_DELETE;
					HAIR_TOOL_BRUSH_TYPE_PAINT_VERTEX;
				}
			}

			LONG HAIR_TOOL_BRUSH_FALLOFF
			{
				CYCLE
				{
					HAIR_TOOL_BRUSH_FALLOFF_NONE;
					HAIR_TOOL_BRUSH_FALLOFF_LINEAR;
					HAIR_TOOL_BRUSH_FALLOFF_DOME;
					HAIR_TOOL_BRUSH_FALLOFF_BELL;
					HAIR_TOOL_BRUSH_FALLOFF_CIRCLE;
					HAIR_TOOL_BRUSH_FALLOFF_NEEDLE;
					HAIR_TOOL_BRUSH_FALLOFF_SPLINE;
				}
			}
		}

		REAL HAIR_TOOL_BRUSH_STRENGTH	{ UNIT PERCENT; MINSLIDER 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }

		REAL HAIR_TOOL_BRUSH_WIDTH { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }

		SPLINE HAIR_TOOL_BRUSH_FALLOFF_CURVE
		{ 
		}
	}

	GROUP HAIR_TOOL_BRUSH_GROUP_DISTANCE
	{
		GROUP
		{
			COLUMNS 2;

			BOOL HAIR_TOOL_BRUSH_DISTANCE_FADE { }
			REAL HAIR_TOOL_BRUSH_DISTANCE { MIN 0.0; }
		}

		SPLINE HAIR_TOOL_BRUSH_DISTANCE_CURVE
		{ 
		}
	}

	GROUP HAIR_TOOL_BRUSH_GROUP_VIEW
	{
		BOOL HAIR_TOOL_BRUSH_VIEW_FALLOFF { }

		SPLINE HAIR_TOOL_BRUSH_VIEW_FALLOFF_CURVE
		{ 
		}
	}

	GROUP HAIR_TOOL_BRUSH_GROUP_GUIDE
	{
		BOOL HAIR_TOOL_BRUSH_GUIDE_FALLOFF { }

		SPLINE HAIR_TOOL_BRUSH_GUIDE_FALLOFF_CURVE
		{ 
		}
	}
}
