CONTAINER ToolHairScale
{
	NAME ToolHairScale;
	INCLUDE ToolBase;

	GROUP MDATA_MAINGROUP
	{
		LONG HAIR_SCALE_TYPE
		{
			CYCLE
			{
				HAIR_SCALE_TYPE_ROOT;
				HAIR_SCALE_TYPE_NORMALS;
				HAIR_SCALE_TYPE_WORLD;
			}
		}

		BOOL HAIR_SCALE_RELATIVE { }

		REAL HAIR_SCALE_PERCENT { UNIT PERCENT; MIN 0.0; }
		REAL HAIR_SCALE_ABSOLUTE { UNIT METER; MIN 0.0; }
	}
}
