CONTAINER ToolHairCut
{
	NAME ToolHairCut;
	INCLUDE ToolHairLiveSelect;

	SHOW MDATA_COMMANDGROUP;
	HIDE HAIR_LIVESELECT_LOCKED;

	GROUP MDATA_MAINGROUP
	{
		BOOL HAIR_TOOL_CUT_SELECTED { }

		REAL HAIR_TOOL_CUT_LENGTH	{ MIN 0.0; }

		SEPARATOR { LINE; }

		LINK HAIR_TOOL_CUT_LINK { ACCEPT { 5100; } }
		BUTTON HAIR_TOOL_CUT_APPLY { }
	}
}
