CONTAINER Xhair
{
	NAME Xhair;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		GRADIENT HAIR_SHADER_COLOR { COLOR; ICC_BASEDOCUMENT; }

		REAL HAIR_SHADER_DIFFUSE_STRENGTH	{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }

		SHADERLINK HAIR_SHADER_DIFFUSE_SHADER { }

		GROUP HAIR_SHADER_GROUP_SPECULAR
		{
			DEFAULT 1;

			REAL HAIR_SHADER_SPECULAR_STRENGTH	{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			REAL HAIR_SHADER_SPECULAR_POWER	{ MIN 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }

			SHADERLINK HAIR_SHADER_SPECULAR_SHADER { }
		}

		GROUP HAIR_SHADER_GROUP_ISPECULAR
		{
			DEFAULT 1;

			REAL HAIR_SHADER_ISPECULAR_STRENGTH	{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			REAL HAIR_SHADER_ISPECULAR_POWER	{ MIN 0.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }

			SHADERLINK HAIR_SHADER_ISPECULAR_SHADER { }
		}

		GROUP HAIR_SHADER_GROUP_ILLUMINATION
		{
			REAL HAIR_SHADER_ROUGHNESS	{ UNIT PERCENT; MIN 0.0; MAX 100.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			REAL HAIR_SHADER_ROUGHNESS_VAR	{ UNIT PERCENT; MIN 0.0; MAX 100.0; MAXSLIDER 100.0; CUSTOMGUI REALSLIDER; }
			
			SEPARATOR { LINE; }
							
			REAL HAIR_SHADER_REFLECT	{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
			REAL HAIR_SHADER_TRANSMIT	{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
			REAL HAIR_SHADER_SHADOW		{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }

			SEPARATOR { LINE; }

			LONG HAIR_SHADER_ALPHA_DEPTH	{ MIN 1; }
			REAL HAIR_SHADER_SHADOW_TRANSPARENCY { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		}

		SEPARATOR { LINE; }

		BOOL HAIR_SHADER_FROM_MATERIAL { }
	}	
}