CONTAINER Mfog
{
	NAME Mfog;

	INCLUDE Mpreview;
	INCLUDE Mbase;

	GROUP Obaselist
	{
		BOOL MATERIAL_PAGE_PROPERTIES { HIDDEN; PAGE; PARENTMSG ID_MATERIALPROPERTIES; }
	}

	GROUP ID_MATERIALPROPERTIES
	{
		COLOR 	FOGSHADER_COLOR {}
		LONG		FOGSHADER_SAMPLES { MIN 4; MAX 100; }
		BOOL		FOGSHADER_VOLUMETRIC {}

		SEPARATOR { }
		VECTOR  FOGSHADER_SCALE { MIN 0.0; STEP 0.01; }
		SEPARATOR { }

		LONG FOGSHADER_TYPE
		{
			CYCLE
			{
				FOGSHADER_TYPE_LINEAR;
				FOGSHADER_TYPE_EXPONENTIAL;
				FOGSHADER_TYPE_NODECREASE;
			}
		}

		REAL FOGSHADER_THICKNESS { UNIT PERCENT; MIN 0.0; }
		REAL FOGSHADER_DECREASE { UNIT PERCENT; MIN 0.0; }
		SEPARATOR {  }

		REAL FOGSHADER_TURBULENCE { UNIT PERCENT; MIN 0.0; }
		REAL FOGSHADER_AMPLITUDE { UNIT PERCENT; MIN 0.0; MAX 1000.0; }
		REAL FOGSHADER_FREQUENCY { UNIT PERCENT; MIN 0.0; STEP 0.01; }
	}
	INCLUDE Massign;
}
