CONTAINER Mterrain
{
	NAME Mterrain;
	INCLUDE Mpreview;
	INCLUDE Mbase;

	GROUP Obaselist
	{
		BOOL MATERIAL_PAGE_PROPERTIES { HIDDEN; PAGE; PARENTMSG ID_MATERIALPROPERTIES; }
	}

	GROUP ID_MATERIALPROPERTIES
	{
		LONG TERRAINSHADER_TYPE
		{
			ANIM OFF;
			CYCLE
			{
				TERRAINSHADER_TYPE_CUSTOM;
				TERRAINSHADER_TYPE_MOUNTAIN;
				TERRAINSHADER_TYPE_MARS;
				TERRAINSHADER_TYPE_MOON;
				TERRAINSHADER_TYPE_DESERT;
				TERRAINSHADER_TYPE_POLAR;
			}
		}
		SEPARATOR { }
		GRADIENT TERRAINSHADER_COLOR { ICC_BASEDOCUMENT; }
		REAL  	TERRAINSHADER_HEIGHT { UNIT PERCENT; MIN 0.0; MAX 100.0; }
	}
	INCLUDE Massign;
}
