CONTAINER Xchanlum
{
	NAME Xchanlum;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		LONG CHANLUM_SAMPLES { MIN 1; }
		REAL CHANLUM_OFFSET { UNIT METER; }
		REAL CHANLUM_RADIUS { UNIT METER; }

		LONG CHANLUM_TYPE
		{
			CYCLE
			{
				CHANLUM_TYPE_NORMAL;
				CHANLUM_TYPE_AREA;
				//CHANLUM_TYPE_TEST1;
			}
		}

		GROUP
		{
			COLUMNS 3;

			BOOL CHANLUM_STOCASTIC { }
			BOOL CHANLUM_GAUSSIAN { }
			BOOL CHANLUM_SHADOWS { }
		}

		SEPARATOR { LINE; }

		LONG CHANLUM_SEED { }

		SEPARATOR { LINE; }

		//BOOL CHANLUM_LIGHTS_LIGHT_EXCLUSION { }

		LONG CHANLUM_LIGHTS_MODE
		{
			CYCLE
			{
				CHANLUM_LIGHTS_MODE_INCLUDE;
				CHANLUM_LIGHTS_MODE_EXCLUDE;
			}
		}

		IN_EXCLUDE  CHANLUM_LIGHTS
		{
			NUM_FLAGS 0;
			INIT_STATE 0;
			SEND_SELCHNGMSG 1;
			ACCEPT { Olight; };
		}
	}
}