CONTAINER Xcloud
{
	NAME Xcloud;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		GRADIENT	CLOUDSHADER_COLOR { ICC_BASEDOCUMENT; }
		REAL  		CLOUDSHADER_SCALEX { MIN 0.0; STEP 0.01; }
		REAL  		CLOUDSHADER_SCALEY { MIN 0.0; STEP 0.01; }
		REAL  		CLOUDSHADER_LEVEL	 { UNIT PERCENT; MIN 0.0; MAX 100.0; }
		BOOL			CLOUDSHADER_COMPATIBILITY { }
	}
}
