CONTAINER Xcyclone
{
	NAME Xcyclone;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		GRADIENT CYCLONESHADER_COLOR { ICC_BASEDOCUMENT; }
		REAL  CYCLONESHADER_FREQUENCY { MIN 0.0; STEP 0.01; }
		REAL  CYCLONESHADER_ROTATION	{ STEP 0.01; }
		REAL  CYCLONESHADER_LEVEL			{ UNIT PERCENT; MIN 0.0; MAX 100.0; }
	}
}