CONTAINER Xearth
{
	NAME Xearth;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		COLOR EARTHSHADER_SEA 			{}
		COLOR EARTHSHADER_LAND			{}
		COLOR EARTHSHADER_MOUNTAIN	{}
		REAL  EARTHSHADER_FREQUENCY { MIN 0.0; STEP 0.01; }
		REAL  EARTHSHADER_LEVEL			{ UNIT PERCENT; MIN 0.0; MAX 100.0; }
	}
}