CONTAINER Xfire
{
	NAME Xfire;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		GRADIENT FIRESHADER_COLOR	{ ICC_BASEDOCUMENT; }
		REAL  FIRESHADER_SCALEX  		{ MIN 0.0; STEP 0.01; }
		REAL  FIRESHADER_SCALEY  		{ MIN 0.0; STEP 0.01; }
		REAL  FIRESHADER_FREQUENCY	{ MIN 0.0; STEP 0.01; }
		REAL  FIRESHADER_TURBULENCE { MIN 0.0; STEP 0.01; }
	}
}