CONTAINER Xflame
{
	NAME Xflame;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		GRADIENT FLAMESHADER_COLOR { ICC_BASEDOCUMENT; }
		REAL  FLAMESHADER_FREQUENCY	{ MIN 0.0; STEP 0.01; }
		REAL  FLAMESHADER_TURBULENCE { MIN 0.0; STEP 0.01; }
	}
}