CONTAINER Xformula
{
	NAME Xformula;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		GROUP
		{
			COLUMNS 1;

			STRING FORMULASHADER_EXPRESSION {}
			BOOL FORMULASHADER_USEWORLDSPACE {}
		}
		GROUP FORMULASHADER_GRP
		{
			COLUMNS 1;

			STATICTEXT	FORMULASHADER_HELP01 {}
			STATICTEXT	FORMULASHADER_HELP02 {}
			STATICTEXT	FORMULASHADER_HELP03 {}
		}
	}
}