CONTAINER Xgalaxy
{
	NAME Xgalaxy;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		GRADIENT GALAXYSHADER_COLOR { ICC_BASEDOCUMENT; }
		REAL  GALAXYSHADER_ANGLE { UNIT DEGREE; }
		REAL	GALAXYSHADER_SPIRALARMS	{ MIN 0.0; MAX 10.0; }
	}
}