CONTAINER Xmetal
{
	NAME Xmetal;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		GRADIENT METALSHADER_COLOR { ICC_BASEDOCUMENT; }
		REAL  METALSHADER_FREQUENCY { MIN 0.0; STEP 0.01; }
	}
}