CONTAINER Xmosaic
{
	NAME Xmosaic;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		SHADERLINK MOSAICSHADER_TEXTURE { }
		BOOL MOSAICSHADER_SMOOTH		{ }
		REAL MOSAICSHADER_TILE_U		{ UNIT REAL; MIN 1.0; STEP 1.0; }
		REAL MOSAICSHADER_TILE_V		{ UNIT REAL; MIN 1.0; STEP 1.0; }
	}
}
