CONTAINER Xnoise
{
	NAME Xnoise;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		GRADIENT NOISESHADER_COLOR { ICC_BASEDOCUMENT; }
		REAL 		NOISESHADER_SCALEX { MIN 0.0; STEP 0.01; }
		REAL 		NOISESHADER_SCALEY { MIN 0.0; STEP 0.01; }
	}
}