CONTAINER Xspectral
{
	NAME Xspectral;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		REAL     SPEC_INT      { MIN 0.0; UNIT PERCENT; }
		REAL     SPEC_VAR	   { UNIT PERCENT; }
		LONG     SPEC_RTYPE    { CYCLE { SPEC_RTYPE_STOP; SPEC_RTYPE_MIRROR; SPEC_RTYPE_TILING; } }
		GRADIENT SPEC_GRADIENT { COLOR; ICC_BASEDOCUMENT; }

		BOOL     SPEC_CD_ON    { }
		REAL     SPEC_CD_WIDTH { MIN 0.0; UNIT PERCENT; }
		REAL     SPEC_CD_PEAK  { MIN 0.0; MAX 100.0; UNIT PERCENT; }
		REAL     SPEC_CD_WFAC  { MIN 0.0; MAX 200.0; UNIT PERCENT; }
		REAL     SPEC_CD_DINT  { MIN 0.0; UNIT PERCENT; }
		REAL     SPEC_CD_DVAR  { UNIT PERCENT; }
		LONG     SPEC_CD_STYPE { CYCLE { SPEC_STYPE_XY; SPEC_STYPE_YZ; SPEC_STYPE_ZX; } }
	}
}
