CONTAINER Xsunburst
{
	NAME Xsunburst;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		GRADIENT SUNBURSTSHADER_COLOR   { ICC_BASEDOCUMENT; }
		REAL  SUNBURSTSHADER_SCALE_R  	{ MIN 0.0; STEP 0.01; }
		REAL  SUNBURSTSHADER_SCALE_A  	{ MIN 0.0; STEP 0.01; }
		REAL  SUNBURSTSHADER_FREQUENCY	{ MIN 0.0; STEP 0.01; }
		REAL  SUNBURSTSHADER_TURBULENCE { MIN 0.0; STEP 0.01; }
		REAL  SUNBURSTSHADER_RADIUS 		{ UNIT PERCENT; MIN 0.0; MAX 100.0; }
		REAL  SUNBURSTSHADER_HEIGHT 		{ UNIT PERCENT; MIN 0.0; MAX 100.0; }
	}
}