CONTAINER Xturbulence
{
	NAME Xturbulence;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		GRADIENT TURBULENCESHADER_COLOR { ICC_BASEDOCUMENT; }
		REAL 		TURBULENCESHADER_SCALEX { MIN 0.0; STEP 0.01; }
		REAL 		TURBULENCESHADER_SCALEY { MIN 0.0; STEP 0.01; }
		REAL  	TURBULENCESHADER_OCTAVES { MIN 0.0; MAX 10.0; STEP 0.01; }
	}
}