CONTAINER Xvenus
{
	NAME Xvenus;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		GRADIENT VENUSSHADER_COLOR { ICC_BASEDOCUMENT; }
		VECTOR 	VENUSSHADER_SCALE { MIN 0.0; STEP 0.01; }
		REAL  	VENUSSHADER_ROTATION { UNIT DEGREE; }
	}
}