CONTAINER Xwater
{
	NAME Xwater;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		GRADIENT WATERSHADER_COLOR { ICC_BASEDOCUMENT; }
		REAL  WATERSHADER_SCALEX { MIN 0.0; STEP 0.01; }
		REAL  WATERSHADER_SCALEY { MIN 0.0; STEP 0.01; }
		REAL  WATERSHADER_FREQUENCY { MIN 0.0; STEP 0.01; }
		REAL  WATERSHADER_WIND { MIN 0.0; STEP 0.01; }
	}
}