// C4D-DialogResource
DIALOG IDD_LICENSERLM_SETUP
{
	NAME IDS_DIALOG; CENTER_V; CENTER_H; 
  
	GROUP IDC_STATIC
	{
		ALIGN_TOP; SCALE_H; 

		BORDERSTYLE BORDER_NONE; BORDERSIZE 0, 0, 0, 0; 
		COLUMNS 2;

		STATICTEXT { NAME IDS_STATIC3; CENTER_V; ALIGN_LEFT; }
		EDITTEXT IDC_SETUP_RLM_SERVER_EDIT { CENTER_V; SCALE_H; SIZE 70, 0; }

		STATICTEXT { NAME IDS_STATIC4; CENTER_V; ALIGN_LEFT; }
		EDITNUMBER IDC_SETUP_RLM_PORT_EDIT { CENTER_V; SCALE_H; SIZE 70, 0; }

//		STATICTEXT { NAME IDS_PASSWD; CENTER_V; ALIGN_LEFT; }
//		EDITTEXT IDC_SETUP_RLM_PASSWD { CENTER_V; SCALE_H; SIZE 70, 0; }

		STATICTEXT { NAME IDS_INSTALL_LICENSE; CENTER_V; ALIGN_LEFT; }
		FILENAME IDC_SETUP_RLM_FILE_BTN { }

		STATICTEXT { NAME IDS_INSTALL_HARDWAREID; CENTER_V; ALIGN_LEFT; }
		STATICTEXT IDC_SETUP_RLM_HARDWAREID { CENTER_V; SCALE_H; SIZE 130, 0; BORDERSTYLE BORDER_THIN_IN; }
	}
	DLGGROUP { OK; CANCEL; }
}
