// C4D-DialogResource
DIALOG IDD_LICENSESERVER_SETUP
{
	NAME IDS_DIALOG; CENTER_V; CENTER_H; 
  
  	COMBOBOX IDC_SETUP_LICSERVER_SERVER_MODE { ALIGN_TOP; ALIGN_LEFT; CHILDS { 1, IDS_MODE_LS_HTTP; 2, IDS_MODE_LS_HTTPS; } }

	GROUP IDC_STATIC
	{
		ALIGN_TOP; SCALE_H; 

		BORDERSTYLE BORDER_NONE; BORDERSIZE 0, 0, 0, 0; 
		COLUMNS 2;

		STATICTEXT { NAME IDS_STATIC3; CENTER_V; ALIGN_LEFT; }
		EDITTEXT IDC_SETUP_LICSERVER_SERVER_EDIT { CENTER_V; SCALE_H; SIZE 70, 0; }

		STATICTEXT { NAME IDS_STATIC4; CENTER_V; ALIGN_LEFT; }
		EDITNUMBER IDC_SETUP_LICSERVER_PORT_EDIT { CENTER_V; SCALE_H; SIZE 70, 0; }

		STATICTEXT { NAME IDS_USERNAME; CENTER_V; ALIGN_LEFT; }
		EDITTEXT IDC_SETUP_LICSERVER_USERNAME { CENTER_V; SCALE_H; SIZE 70, 0; }

		STATICTEXT { NAME IDS_PASSWD; CENTER_V; ALIGN_LEFT; }
		EDITTEXT IDC_SETUP_LICSERVER_PASSWD { CENTER_V; SCALE_H; SIZE 70, 0; }
	}
//	BUTTON IDC_SETUP_LICSERVER_FILE_BTN { NAME IDS_SETUP_LICSERVER_FILE; ALIGN_TOP; ALIGN_LEFT; }
	DLGGROUP { OK; CANCEL; }
}
