// C4D-DialogResource

DIALOG P_PAINTTOOL_POLYGONSHAPE
{
  NAME TITLE;
	SCALE_H;

  GROUP
  {
		COLUMNS 1;
		SCALE_H; SCALE_V;

		GROUP
		{
			COLUMNS 1;
			RADIOGROUP PGD_POLY_DRAWMODE
			{
				GROUP
				{
					ROWS 1;
					RADIOGADGET PGD_DRAWMODE_FILLED   { NAME TFILLED; }
					RADIOGADGET PGD_DRAWMODE_OUTLINED { NAME TOUTLINE; }
//					RADIOGADGET PGD_DRAWMODE_PATH			{ NAME TPATH; }
				}
			}
			//CHECKBOX PGD_DRAWMODE_OUTLINED { NAME TOUTLINE; }
		}

		SEPARATOR { SCALE_H; }

		GROUP
		{
			ROWS 1;
			STATICTEXT { NAME TSHAPE; }
			COMBOBOX PGD_SELECTION_SHAPE
			{
				SCALE_H;
				CHILDS
				{
					1,TCIRCLE;
					2,TRECT;
					4,T4SIDE;
					5,TNSIDE;
					6,TSTAR;
					7,TCOG;
					8,TFLOWER;
					9,TPROFILE;
				}
			}
			BUTTON IDC_EDIT1 { NAME TPPP; }
		}
		RADIOGROUP PGD_SELECTION_HANDLE
		{
			GROUP
			{
				RADIOGADGET HANDLE_BOX   { NAME TRECTH; }
				RADIOGADGET HANDLE_MID   { NAME TMIDPOINT; }
				RADIOGADGET HANDLE_DIA	 { NAME TDIAMETER; }
			}
		}

		SEPARATOR { SCALE_H; }

		TAB PGD_POLYFILL_BRUSHEDITORTAB
		{
			SELECTION_NONE;
			SCALE_H; SCALE_V;

			GROUP IDC_X1 
			{
				COLUMNS 1;
				SCALE_H;
				GROUP
				{
					COLUMNS 1;
					CHECKBOX PGD_POLYFILL_ANTIALIAS { NAME TAA; }
				}
				GROUP
				{
					COLUMNS 2;
					SCALE_H;
					STATICTEXT { NAME TTOLERANCE; }
					EDITSLIDER PGD_POLYFILL_BORDER { SCALE_H; }
				}
			}
			GROUP PGD_POLYFILL_BRUSHEDITOR 
			{
				SCALE_H; SCALE_V;
				BRUSHEDITOR { SCALE_H; SCALE_V; }
			}
		}
  }
}
