// C4D-DialogResource

DIALOG P_PAINTTOOL_GRADIENT
{
  NAME TITLE;

  GROUP
  {
		COLUMNS 1;
		SCALE_H;
		SPACE 4,1;

		GROUP
		{
			ROWS 1;
			SCALE_H;
			SPACE 4,1;

			BITMAPBUTTON PGD_GRADIENT_PREVIEW { ALIGN_LEFT; ALIGN_TOP; SIZE -50,-50; }

			GROUP
			{
				COLUMNS 1;
				SCALE_H;

				GROUP
				{
					COLUMNS 3;
					SCALE_H;
					SPACE 4,1;

					STATICTEXT { NAME TTYPE; }
					COMBOBOX PGD_GRADIENT_TYPE
					{
						FIT_H;
						SIZE 0,11;
						CHILDS
						{
							PGD_GRADIENT_TYPE_LINEAR			, TLINEAR			;
							PGD_GRADIENT_TYPE_REFLECTIVE	, TREFLECTIVE	;
							PGD_GRADIENT_TYPE_RADIAL			, TRADIAL			;
							PGD_GRADIENT_TYPE_CIRCLE			, TCIRCLE			;
						}
					}
					
					BUTTON PGD_GRADIENT_ADDPRESET { NAME TADD; SIZE 0,11; }

					STATICTEXT { NAME TBLEND; }
					COMBOBOX PGD_GRADIENT_BLENDMODE 
					{
						FIT_H;
						SIZE 0,11;
						CHILDS 
						{
							0, TL0;
							0, TSEP;
							1, TL1;
							2, TL2;
							3, TL3;
							4, TL4;
							5, TL5;
							6, TL6;
							7, TL7;
							8, TL8;
							9, TL9;
						}
					}
					STATICTEXT { }
				}
				GROUP
				{
					ROWS 1;
					SCALE_H;
					SPACE 4,1;

					STATICTEXT { NAME TSTRENGTH; }
					EDITSLIDER PGD_GRADIENT_BLENDSTRENGTH { SCALE_H; SIZE 0,11; }
				}
			}
		}
		GRADIENT PGD_GRADIENT_COL { SCALE_H; COLOR; ALPHA; OPEN; EDITH 11; ICC_BPTEXTURE; }
	}
  GROUP
  {
		COLUMNS 2;
		SCALE_H;
		SPACE 4,1;

		STATICTEXT { NAME TNOISEVARIATION; }
		EDITSLIDER PGD_GRADIENT_NOISEVARIATION { SCALE_H; SIZE 0,11; }

		STATICTEXT { NAME TNOISESCALE; }
		EDITSLIDER PGD_GRADIENT_NOISESCALE { SCALE_H; SIZE 0,11; }
	}

	GROUP
	{
		ROWS 1;
		SPACE 4,1;
		CHECKBOX PGD_GRADIENT_DITHER { NAME TDITHER; }
		CHECKBOX PGD_GRADIENT_ALPHA  { NAME TALPHA;  }
		CHECKBOX PGD_GRADIENT_INVERT { NAME TINVERT; }
	}
}
