// C4D-DialogResource

DIALOG P_PAINTTOOL_TEXT
{
  NAME TITLE;
	SCALE_H;
	SCALE_V;

  GROUP
  {
		COLUMNS 1;
		SCALE_H;
		SCALE_V;

		GROUP
		{
			COLUMNS 1;
			RADIOGROUP PGD_POLY_DRAWMODE
			{
				GROUP
				{
					ROWS 1;
					RADIOGADGET PGD_DRAWMODE_FILLED   { NAME TFILLED; }
					RADIOGADGET PGD_DRAWMODE_OUTLINED { NAME TOUTLINE; }
//					RADIOGADGET PGD_DRAWMODE_PATH			{ NAME TPATH; }
				}
			}
		}

		GROUP
		{
			COLUMNS 1;
			SCALE_H;
			MULTILINEEDIT IDC_EDIT1 { SCALE_H; SIZE 100,30; }
		}

		GROUP
		{
			COLUMNS 3;

			GROUP
			{
				COLUMNS 2;
				SPACE 4,1;

				STATICTEXT { NAME TFONT; }
				GROUP
				{
					ROWS 1;
					SCALE_H;
					//EDITTEXT IDC_EDIT2 { SCALE_H; }
					BUTTON IDC_EDIT2 { NAME TPPP; SCALE_H; }
				}

				STATICTEXT { NAME TSIZE; }
				EDITNUMBERARROWS IDC_EDIT3 { SCALE_H; SIZE 60,0; }

				STATICTEXT { NAME TALIGN; }
				COMBOBOX IDC_EDIT4
				{
					SCALE_H;
					CHILDS
					{
						0,TLEFT;
						1,TCENTER;
						2,TRIGHT;
					}
				}
			}

			SEPARATOR { SCALE_V; }

			GROUP
			{
				COLUMNS 1;

				RADIOGROUP PGD_SELECTION_HANDLE
				{
					GROUP
					{
						RADIOGADGET HANDLE_BOX   { NAME TRECTH; }
						RADIOGADGET HANDLE_MID   { NAME TMIDPOINT; }
					}
				}
			}
		}
		SEPARATOR { SCALE_H; }
		TAB PGD_POLYFILL_BRUSHEDITORTAB
		{
			SELECTION_NONE;
			SCALE_H; SCALE_V;

			GROUP IDC_X1 
			{
				COLUMNS 1;
				SCALE_H;
				GROUP
				{
					COLUMNS 1;
					CHECKBOX PGD_POLYFILL_ANTIALIAS { NAME TAA; }
				}
				GROUP
				{
					COLUMNS 2;
					SCALE_H;
					STATICTEXT { NAME TTOLERANCE; }
					EDITSLIDER PGD_POLYFILL_BORDER { SCALE_H; }
				}
			}
			GROUP PGD_POLYFILL_BRUSHEDITOR 
			{
				SCALE_H; SCALE_V;
				BRUSHEDITOR { SCALE_H; SCALE_V; }
			}
		}
  }
}
