// C4D-DialogResource

DIALOG P_PAINTTOOL_SELECTION
{
  NAME TITLE;

  GROUP
  {
		COLUMNS 1;
		SCALE_H;
		
		GROUP
		{
			COLUMNS 2;
			SCALE_H;
			STATICTEXT { NAME TSHAPE; }
			COMBOBOX PGD_SELECTION_SHAPE 
			{
				SCALE_H;
				CHILDS
				{
					2,TRECT;
					1,TCIRCLE;
					3,TFREEHAND;
					4,TLINES;
				}
			}

//			STATICTEXT { NAME THANDLE; }
//			COMBOBOX PGD_SELECTION_HANDLE
//			{
//				SCALE_H;
//				CHILDS
//				{
//					HANDLE_BOX,TRECTH;
//					HANDLE_MID,TMIDPOINT;
//					HANDLE_DIA,TDIAMETER;
//				}
//			}
		}
		RADIOGROUP PGD_SELECTION_HANDLE
		{
			GROUP
			{
				RADIOGADGET HANDLE_BOX   { NAME TRECTH; }
				RADIOGADGET HANDLE_MID   { NAME TMIDPOINT; }
				RADIOGADGET HANDLE_DIA	 { NAME TDIAMETER; }
			}
		}

		SEPARATOR { SCALE_H; }

		GROUP
		{
			COLUMNS 2;
			CHECKBOX PGD_POLYFILL_ANTIALIAS { NAME TAA; }
		}
		GROUP
		{
			COLUMNS 2;
			SCALE_H;
			STATICTEXT { NAME TTOLERANCE; }
			EDITSLIDER PGD_POLYFILL_BORDER { SCALE_H; }
		}

		SEPARATOR { SCALE_H; }

		RADIOGROUP PGD_MAGIC_MODE
		{
			GROUP
			{
				COLUMNS 1;
				RADIOGADGET PGD_MAGIC_NEWSELECT        { NAME TNEWSELECTION; }
				RADIOGADGET PGD_MAGIC_NEWINVERSESELECT { NAME TNEWINVSEL; }
				RADIOGADGET PGD_MAGIC_ADDSELECT        { NAME TADDSELECTION; }
				RADIOGADGET PGD_MAGIC_SUBSELECT        { NAME TSUBSELECTION; }
			}
		}
  }
}
