// C4D-DialogResource

DIALOG P_PAINT_BRUSHEDITOR
{
  NAME TITLE;

	SCALE_H;
	SCALE_V;

	SCROLLGROUP
	{
		SCROLL_AUTO_V;
		SCROLL_AUTO_H;
		SCALE_H;
		SCALE_V;

		GROUP
		{
			COLUMNS 1;
			SCALE_H;

			GROUP IDC_BRUSHEDIT_GROUP_PREVIEW
			{
				SCALE_H;
				SPACE 1,4;
				COLUMNS 1;
				USERAREA IDC_BRUSHEDIT_STROKEPREVIEW { SCALE_H; SIZE -80,-80; }
			}

			GROUP IDC_BRUSHEDIT_GROUP_SETTINGS
			{
				COLUMNS 1;
				SCALE_H;

				QUICKTAB { SCALE_H; BAR; BARTITLE TSETTINGS; }

				GROUP IDC_BRUSH_TYPE_SIMPLE
				{
					SCALE_H; SCALE_V;
					COLUMNS 2;
					SPACE 4,1;
					
					DESCRIPTIONPROPERTY { NAME T4; }
					COMBOBOX IDC_BRUSHEDIT_SHAPE
					{
						ALIGN_LEFT;
						SIZE 0,11;
						CHILDS 
						{
							0, T5;
							1, T6;
						}
					}
					//STATICTEXT { FIT_H; }

					DESCRIPTIONPROPERTY IDC_BRUSHEDIT_PROFILE_EDIT { NAME T7; }
					COMBOBOX IDC_BRUSHEDIT_PROFILE
					{
						ALIGN_LEFT;
						SIZE 0,11;
						CHILDS 
						{
							2, T9;
							3, T10;
							4, T11;
							5, T12;
							1, T8;
						}
					}
					//BUTTON IDC_BRUSHEDIT_PROFILE_EDIT { SIZE 0,11; FIT_H; NAME TPP; }

					DESCRIPTIONPROPERTY IDC_BRUSHEDIT_SIZE_MOD { NAME TA1; }
					EDITSLIDER IDC_BRUSHEDIT_SIZE { SIZE 0,11; SCALE_H; }
					//BUTTON IDC_BRUSHEDIT_SIZE_MOD { SIZE 0,11; FIT_H; NAME TPP; }

					DESCRIPTIONPROPERTY IDC_BRUSHEDIT_PRESSURE_MOD { NAME TA2; }
					EDITSLIDER IDC_BRUSHEDIT_PRESSURE { SIZE 0,11; SCALE_H; }
					//BUTTON IDC_BRUSHEDIT_PRESSURE_MOD { SIZE 0,11; FIT_H; NAME TPP; }

					DESCRIPTIONPROPERTY IDC_BRUSHEDIT_HARDNESS_MOD { NAME TA3; }
					EDITSLIDER IDC_BRUSHEDIT_HARDNESS { SIZE 0,11; SCALE_H; }
					//BUTTON IDC_BRUSHEDIT_HARDNESS_MOD { SIZE 0,11; FIT_H; NAME TPP; }

					GROUP
					{
						ROWS 1;
						CHECKBOX IDC_BRUSHEDIT_DISTANCE_ON { NAME TA4; }
						//DESCRIPTIONPROPERTY { NAME TA4; }
					}
					EDITSLIDER IDC_BRUSHEDIT_DISTANCE { SIZE 0,11; SCALE_H; }
					//STATICTEXT { FIT_H; }

					DESCRIPTIONPROPERTY IDC_BRUSHEDIT_SQUEEZE_MOD { NAME TA6; }
					EDITSLIDER IDC_BRUSHEDIT_SQUEEZE { SIZE 0,11; SCALE_H; }

					DESCRIPTIONPROPERTY IDC_BRUSHEDIT_ROTATION_MOD { NAME TA7; }
					EDITSLIDER IDC_BRUSHEDIT_ROTATION { SIZE 0,11; SCALE_H; }

					GROUP
					{
						ROWS 1;
						CHECKBOX IDC_BRUSHEDIT_AIRSPEED_ON { }
						DESCRIPTIONPROPERTY IDC_BRUSHEDIT_AIRSPEED_MOD { NAME AIRSPEED; }
					}
					EDITSLIDER IDC_BRUSHEDIT_AIRSPEED { SIZE 0,11; SCALE_H; }

					GROUP
					{
						ROWS 1;
						CHECKBOX IDC_BRUSHEDIT_DISPLACEMENT_ON { }
						DESCRIPTIONPROPERTY IDC_BRUSHEDIT_DISPLACEMENT_MOD { NAME TA5; }
					}
					EDITSLIDER IDC_BRUSHEDIT_DISPLACEMENT { SIZE 0,11; SCALE_H; }

					DESCRIPTIONPROPERTY IDC_BRUSHEDIT_DISPLACEMENT_COUNT_MOD { NAME JITTERCOUNT; }
					GROUP
					{
						ROWS 1; SCALE_H;
						EDITSLIDER IDC_BRUSHEDIT_DISPLACEMENT_COUNT { SIZE 0,11; SCALE_H; }
						CHECKBOX IDC_BRUSHEDIT_DISPLACEMENT_BOTHAXIS { NAME BOTHAXIS; }
					}
				}

				GROUP IDC_BRUSH_TYPE_BITMAP
				{
					SCALE_H; SCALE_V;
					COLUMNS 2;
					SPACE 4,1;

					STATICTEXT { NAME TB1; }
					GROUP
					{
						ROWS 1;
						SCALE_H; 
						SPACE 1,1;

						POPUPBUTTON IDC_BRUSHEDIT_BMP_POPUP { FIT_H; FIT_V; }
						GROUP
						{
							SCALE_H;
							BORDERSTYLE BORDER_THIN_IN;
							BORDERSIZE 1,1,1,1;
							STATICTEXT IDC_BRUSHEDIT_BMP_NAME { SIZE 11,11; SCALE_H; }
						}
						BUTTON IDC_BRUSHEDIT_BMP_SETSAMPLESIZE { NAME SETSAMPLESIZE; }
					}
					//STATICTEXT {}

					DESCRIPTIONPROPERTY IDC_BRUSHEDIT_BMP_SIZE_MOD { NAME TB2; }
					EDITSLIDER IDC_BRUSHEDIT_BMP_SIZE { SIZE 0,11; SCALE_H; }
					//BUTTON IDC_BRUSHEDIT_BMP_SIZE_MOD { SIZE 0,11; FIT_H; NAME TPP; }

					DESCRIPTIONPROPERTY IDC_BRUSHEDIT_BMP_PRESSURE_MOD { NAME TB3; }
					EDITSLIDER IDC_BRUSHEDIT_BMP_PRESSURE { SIZE 0,11; SCALE_H; }
					//BUTTON IDC_BRUSHEDIT_BMP_PRESSURE_MOD { SIZE 0,11; FIT_H; NAME TPP; }

					DESCRIPTIONPROPERTY IDC_BRUSHEDIT_BMP_ROTATION_MOD { NAME TB6; }
					EDITSLIDER IDC_BRUSHEDIT_BMP_ROTATION { SIZE 0,11; SCALE_H; }
					//BUTTON IDC_BRUSHEDIT_BMP_ROTATION_MOD { SIZE 0,11; FIT_H; NAME TPP; }

					CHECKBOX IDC_BRUSHEDIT_BMP_DISTANCE_ON { NAME TB4; }
					EDITSLIDER IDC_BRUSHEDIT_BMP_DISTANCE { SIZE 0,11; SCALE_H; }
					//STATICTEXT { }

					GROUP
					{
						ROWS 1;
						CHECKBOX IDC_BRUSHEDIT_BMP_AIRSPEED_ON { }
						DESCRIPTIONPROPERTY IDC_BRUSHEDIT_BMP_AIRSPEED_MOD { NAME AIRSPEED; }
					}
					EDITSLIDER IDC_BRUSHEDIT_BMP_AIRSPEED { SIZE 0,11; SCALE_H; }

					GROUP
					{
						ROWS 1;
						CHECKBOX IDC_BRUSHEDIT_BMP_DISPLACEMENT_ON { }
						DESCRIPTIONPROPERTY IDC_BRUSHEDIT_BMP_DISPLACEMENT_MOD { NAME TB5; }
					}
					EDITSLIDER IDC_BRUSHEDIT_BMP_DISPLACEMENT { SIZE 0,11; SCALE_H; }

					DESCRIPTIONPROPERTY IDC_BRUSHEDIT_BMP_DISPLACEMENT_COUNT_MOD { NAME JITTERCOUNT; }
					GROUP
					{
						ROWS 1; SCALE_H;
						EDITSLIDER IDC_BRUSHEDIT_BMP_DISPLACEMENT_COUNT { SIZE 0,11; SCALE_H; }
						CHECKBOX IDC_BRUSHEDIT_BMP_DISPLACEMENT_BOTHAXIS { NAME BOTHAXIS; }
					}
				}
			}

			GROUP IDC_BRUSHEDIT_GROUP_FILTER
			{
				SCALE_H;
				COLUMNS 1;
			
				QUICKTAB { SCALE_H; BAR; BARTITLE TFILTER; }

				GROUP
				{
					SCALE_H;
					ROWS 1;
					
					GROUP
					{
						SCALE_H;
						COLUMNS 2;
						SPACE 4,1;

						DESCRIPTIONPROPERTY { NAME TC1; }
						GROUP
						{
							SCALE_H;
							ROWS 1;

							COMBOBOX IDC_BRUSHEDIT_FILTER
							{
								SIZE 0,11;
								CHILDS 
								{
									0, TN0;
									0, TSEP; 
									1, TN1;
									2, TN2;
									3, TN3;
									4, TN4;
									5, TN5;
									6, TN6;
									7, TN7;
									8, TN8;
									9, TN9;
									10, TN10;
								}
							}

							CHECKBOX IDC_BRUSHEDIT_FILTER_SMUDGEFLATTEN { NAME TC2; }
						}
						//STATICTEXT {}

						DESCRIPTIONPROPERTY IDC_BRUSHEDIT_FILTER_SMUDGECOLOR_MOD { NAME TC3; }
						EDITSLIDER IDC_BRUSHEDIT_FILTER_SMUDGECOLOR { SCALE_H; SIZE 0,11; }
						//BUTTON IDC_BRUSHEDIT_FILTER_SMUDGECOLOR_MOD { SIZE 0,11; NAME TPP; }
					}
				}
			}
		}
	}
}
