// C4D-DialogResource

DIALOG P_PAINTTOOL_CLONE
{
	NAME TITLE;
	SCALE_H; SCALE_V;

	GROUP
	{
		COLUMNS 1;
		SCALE_H; SCALE_V;

		CHECKBOX PGD_FILL_MERGELAYER { NAME TMERGELAYERS; }
		CHECKBOX PGD_CLONE_RELATIVE  { NAME TRELATIVE; }

		GROUP
		{
			COLUMNS 2;
			SCALE_H;

			STATICTEXT { NAME TSCALE; }
			EDITSLIDER PGD_CLONE_SCALE	 { SCALE_H; SIZE 0,11; }

			STATICTEXT { NAME TROTATION; }
			EDITSLIDER PGD_CLONE_ROT		 { SCALE_H; SIZE 0,11; }
		}

		BRUSHEDITOR { SCALE_H; SCALE_V; }
	}
}
