// C4D-DialogResource

DIALOG P_PAINTTOOL_PICKUP
{
  NAME TITLE;

  GROUP
  {
		COLUMNS 1;
		SCALE_H; 
		
		RADIOGROUP PGD_PICKUP_MODE
		{
			GROUP
			{
				COLUMNS 2;
				RADIOGADGET PICKUP_MODE_SOLIDCOLOR   { NAME TSOLIDCOLOR; }
				RADIOGADGET PICKUP_MODE_TEXTURECLONE { NAME TTEXTURE; }
			}
		}

		SEPARATOR { SCALE_H; }

		GROUP
		{
			COLUMNS 1;
			CHECKBOX PGD_FILL_MERGELAYER { NAME TMERGELAYERS; }
		}
		GROUP
		{
			COLUMNS 2;
			SCALE_H;
			CHECKBOX PGD_PICKUP_SOLID_ENABLESAMPLING { NAME TSAMPLE; }
			EDITSLIDER PGD_PICKUP_SOLID_RANGE { SCALE_H; }
		}
  }
}
