// C4D-DialogResource

DIALOG P_PAINTTOOL_SELECTCOLOR
{
  NAME TITLE;
	SCALE_H;

  GROUP
  {
		COLUMNS 1;
		SCALE_H;

		GROUP
		{
			COLUMNS 2;
			CHECKBOX PGD_FILL_MERGELAYER { NAME TMERGELAYERS; }
			//CHECKBOX PGD_FILL_AA         { NAME TAA; }
		}
		GROUP
		{
			COLUMNS 2;
			SCALE_H;
			STATICTEXT { NAME TTOLERANCE; }
			EDITSLIDER PGD_FILL_TOLERANCE { SCALE_H; }
		}
		RADIOGROUP PGD_MAGIC_MODE
		{
			GROUP
			{
				COLUMNS 1;
				RADIOGADGET PGD_MAGIC_NEWSELECT        { NAME TNEWSELECTION; }
				RADIOGADGET PGD_MAGIC_NEWINVERSESELECT { NAME TNEWINVSEL; }
				RADIOGADGET PGD_MAGIC_ADDSELECT        { NAME TADDSELECTION; }
				RADIOGADGET PGD_MAGIC_SUBSELECT        { NAME TSUBSELECTION; }
			}
		}
  }
}
