// C4D-DialogResource

DIALOG P_SAVEFORMAT
{
	NAME TITLE;

	GROUP
	{
		COLUMNS 3;

		STATICTEXT { NAME TFORMAT; }
		COMBOBOX IDC_X1 { }
		BUTTON IDC_X2 { NAME TOPTIONS; }
	}
	GROUP
	{
		COLUMNS 1;
		BORDERSIZE 4,4,4,4;
		BORDERSTYLE BORDER_THIN_IN;
		SCALE_H;
		STATICTEXT IDC_Y1 { SCALE_H; }
		STATICTEXT IDC_Y2 { SCALE_H; }
		STATICTEXT IDC_Y3 { SCALE_H; }
		STATICTEXT IDC_Y4 { SCALE_H; }
		STATICTEXT IDC_Y5 { SCALE_H; }
	}

	DLGGROUP { OK;CANCEL;HELP; }
}
