// C4D-DialogResource

DIALOG P_UVGIZMO_PREFS
{
  NAME TITLE;

	SCALE_H;
	SCALE_V;

	GROUP IDC_GET1
	{
		SCALE_H;
		SCALE_V;

		BORDERSIZE 4,4,4,4;

		COLUMNS 1;

		CHECKBOX IDC_GIZMO_HIDE { NAME THIDEGIZMO; }
		CHECKBOX IDC_GIZMO_KEEPFACENEIGHBORS { NAME TGIZMOLINKMODE; }

		SEPARATOR { SCALE_H; }

		CHECKBOX IDC_GIZMO_X4 { NAME TGIZMOSOFTSELECT; }

		GROUP
		{
			STATICTEXT { NAME TGIZMORADIUS; }
 			EDITNUMBERARROWS IDC_GIZMO_X5 {SCALE_H; SIZE 80,0;}
		}
	}
}