// C4D-DialogResource
DIALOG R_CREATEMARKER
{
	NAME TITLE;
	GROUP
	{
		SCALE_V; SCALE_H;
		COLUMNS 2;
		STATICTEXT { NAME MARKER_NAME; };
		EDITTEXT		ID_MARKER_NAME {SCALE_H;};
		
		STATICTEXT { NAME LAYER; };
		LINK ID_MARKER_LAYER
		{
			SCALE_H;
			LAYERMODE;
			NO_PICKER;
		};
	}
	TAB ID_MARKER_TAB
	{
		SCALE_V; SCALE_H; SELECTION_TABS;
		GROUP ID_MARKER_TAB_SINGLE
		{
			NAME TAB_SINGLE;
			COLUMNS 2;
			
			STATICTEXT { NAME TIME; }
			EDITNUMBER ID_MARKER_TIME { SIZE 80,0; }
			STATICTEXT { NAME TIME_LENGTH; }
			EDITNUMBER ID_MARKER_TIME_LENGTH { SIZE 80,0; }
			STATICTEXT { NAME COLOR; }
			COLORFIELD ID_MARKER_COLOR {NOBRIGHTNESS; NOCOLOR; NOMODEBUTTONS;  SCALE_H;}
		}
		GROUP ID_MARKER_TAB_MULTI
		{
			NAME TAB_MULTI;
			COLUMNS 2;
			STATICTEXT {NAME Mode;};
			RADIOGADGET ID_MARKER_MULTI_BPM {NAME BPM;};
			
			STATICTEXT {};
			RADIOGADGET ID_MARKER_MULTI_COUNT {NAME COUNT_NAME;};
			
			STATICTEXT {NAME BPM_NAME;};
			EDITNUMBER ID_MARKER_VAL_COUNTBPM { SIZE 100,0; }
			
			STATICTEXT {NAME PREVIEWRANGE;};
			CHECKBOX ID_MARKER_PREVIEWRANGE {};
			
			STATICTEXT {NAME AUTOLENGTH;};
			CHECKBOX ID_MARKER_MULTI_USE_LENGTH {};
			
			STATICTEXT { NAME COLORFIRST; }
			GRADIENT ID_MARKER_TIME_MULTI_COLFIRST {COLOR; SCALE_H; SCALE_V;}
		}
	}

	DLGGROUP { OK;CANCEL;}
}
