// C4D-DialogResource

DIALOG R_MODELING_CREATEOUTLINE
{
  NAME T1;
  GROUP
  {
    COLUMNS 1;
    
    CHECKBOX IDC_CREATEOUTLINE_SEPARATE { NAME T2; }
    GROUP
    {
    	COLUMNS 2;
	    
			STATICTEXT { NAME T3; }
			EDITNUMBERARROWS IDC_CREATEOUTLINE_RADIUS { SCALE_H;NAME T4; }
			STATICTEXT { }
			BUTTON IDC_OK { NAME T5; }
    }
  }
}
