// C4D-DialogResource

DIALOG R_MODELING_MIRROR
{
  NAME T1;
  GROUP
  {
    COLUMNS 2;
    SPACE 4,1;
    CENTER_H;

    STATICTEXT { NAME T2; }
    COMBOBOX IDC_MIRROR_SYSTEM { CHILDS { 0,T3; 1,T4; 2,T5; } }
    STATICTEXT { NAME T6; }
    COMBOBOX IDC_MIRROR_PLANE { CHILDS { 0,T7; 1,T8; 2,T9; } }
    STATICTEXT { SIZE -1,-2; }
    STATICTEXT { SIZE -1,-2; }

    STATICTEXT { SIZE -1,-2; }
    STATICTEXT { SIZE -1,-2; }

		CHECKBOX IDC_MIRROR_WELD { NAME T13; }
    EDITNUMBERARROWS IDC_MIRROR_TOLERANCE { SCALE_H;NAME T14; }

		CHECKBOX IDC_MIRROR_ONPLANE { NAME T17; }
		STATICTEXT { }		

    STATICTEXT { NAME T15; }
    EDITNUMBERARROWS IDC_MIRROR_VALUE  { SCALE_H;NAME T14; }
	}
  GROUP
  {
    COLUMNS 2;
    SPACE 4,1;
		GROUP
		{
			COLUMNS 1;
			SPACE 4,1;

			CHECKBOX IDC_MIRROR_DUPLICATE { NAME T10; }		
			CHECKBOX IDC_MIRROR_SELECTIONS { NAME T12; }		
			CHECKBOX IDC_MIRROR_SNAPPOINTS { NAME T11; }
		}
		BUTTON IDC_OK { ALIGN_BOTTOM;ALIGN_RIGHT; NAME T16; }
	}
}
