// C4D-DialogResource

DIALOG R_MODELING_OPTIMIZE
{
  NAME T1;
  GROUP
  {
	  COLUMNS 1;
	  
    CHECKBOX IDC_OPTIMIZE_POLYGONS {  NAME T2; };
    CHECKBOX IDC_OPTIMIZE_UNUSEDPOINTS {  NAME T3; };
    CHECKBOX IDC_OPTIMIZE_POINTS { NAME T4; };
	}
  GROUP
  {
	  COLUMNS 2;
	  
	  STATICTEXT { NAME T5; }
    EDITNUMBERARROWS IDC_OPTIMIZE_TOLERANCE { SIZE 100,0; }
  }
  DLGGROUP { OK;CANCEL;HELP; }
}
