// C4D-DialogResource
DIALOG R_MODELING_UNTRIANGULATE
{
  NAME T1; CENTER_V; CENTER_H;

  CHECKBOX IDC_UNTRIANGULATE_ANGLE { NAME T2; CENTER_V; FIT_H;  }
  CHECKBOX IDC_UNTRIANGULATE_NGON { NAME T3; ALIGN_TOP; ALIGN_LEFT;  }
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC1; ALIGN_TOP; ALIGN_LEFT;
    BORDERSTYLE BORDER_NONE; BORDERSIZE 0, 0, 0, 0;
    COLUMNS 2;

    STATICTEXT IDC_STATIC { NAME IDS_STATIC; CENTER_V; ALIGN_LEFT; }
    EDITNUMBERARROWS IDC_UNTRIANGULATE_ANGLE_EDIT { CENTER_V; CENTER_H; SIZE 70, 0; }
  }
  STATICTEXT  { CENTER_V; FIT_H; }
  DLGGROUP { OK; CANCEL; HELP; }
}