// C4D-DialogResource

DIALOG R_MODELING_SUBDIVIDE
{
  NAME T1;
	
  GROUP
  {
    COLUMNS 2;

    STATICTEXT IDC_SUBDIVIDE_PATTERN_STRING { NAME T7; }
    COMBOBOX IDC_SUBDIVIDE_PATTERN
    {
      CHILDS
      {
        0,T8;
        1,T9;
        2,T10;
      }
    }
    STATICTEXT { NAME T4; }
    CHECKBOX IDC_SUBDIVIDE_HYPER { }

    STATICTEXT IDC_SUBDIVIDE_SIMPLESUB_STRING { NAME T6; }
    EDITNUMBERARROWS IDC_SUBDIVIDE_SIMPLESUB { NAME T3; }

    STATICTEXT IDC_SUBDIVIDE_SUB_STRING { NAME T2; }
    EDITNUMBERARROWS IDC_SUBDIVIDE_SUB { NAME T3; }

    STATICTEXT IDC_SUBDIVIDE_ANGLE_STRING { NAME T5; }
    EDITNUMBERARROWS IDC_SUBDIVIDE_ANGLE { NAME T3; }
  }

  DLGGROUP { OK;CANCEL;HELP; }
}
