// C4D-DialogResource
DIALOG R_REGISTER
{
	NAME T1; SCALE_V; SCALE_H; 

	GROUP
	{
		SCALE_V; SCALE_H; 
		BORDERSIZE 4, 0, 0, 0; 
		COLUMNS 1;
		SPACE 4, 4;

		GROUP 
		{
			SCALE_H; 
			BORDERSIZE 0, 0, 0, 0; 
			ROWS 1;
			SPACE 4, 4;

			GROUP
			{
				BUTTON IDC_REGISTER_BACKWARD { NAME IDS_REGISTER_BACKWARD; }
				BUTTON IDC_REGISTER_FORWARD { NAME IDS_REGISTER_FORWARD; }
				BUTTON IDC_REGISTER_HOME { NAME IDS_REGISTER_HOME; }
			}

			STATICTEXT { SCALE_H; }

			STATICTEXT { NAME IDS_LICENSETYPE; }

			COMBOBOX IDC_BINARY_SWITCH
			{
			}
		}
		
		TAB IDC_BINARY_TYPE
		{
			SELECTION_NONE;
			COLUMNS 1;
			SCALE_H; SCALE_V;

			GROUP IDC_REGISTER_ACCOUNT
			{
				NAME TTYPE_ACCOUNT;
				COLUMNS 1;

				SCALE_H; SCALE_V;
				HTMLVIEWER IDC_DEMOHTML
				{
					SCALE_H; SCALE_V;
					SIZE -1060, -670;
				}
			}
		}
	}
}