// C4D-DialogResource
DIALOG R_RLA
{
  NAME T1;
  
  GROUP
	{
		COLUMNS 1;
		SPACE 4,2;
		
		CHECKBOX IDC_RLA_Z { NAME T2; }
		CHECKBOX IDC_RLA_OBJECTBUFFER { NAME T3; }
		CHECKBOX IDC_RLA_UV { NAME T4; }
		CHECKBOX IDC_RLA_NORMAL { NAME T5; }
		CHECKBOX IDC_RLA_ORIGCOLOR	 { NAME T6; }
		CHECKBOX IDC_RLA_COVERAGE { NAME T7; }
	}
	DLGGROUP { OK;CANCEL;HELP; }
}
