// C4D-DialogResource
DIALOG R_RPF
{
  NAME T1;
  
  GROUP
	{
		COLUMNS 1;
		SPACE 4,2;
		
		CHECKBOX IDC_RPF_Z { NAME T2; }
		CHECKBOX IDC_RPF_OBJECTBUFFER { NAME T3; }
		CHECKBOX IDC_RPF_UV { NAME T4; }
		CHECKBOX IDC_RPF_NORMAL { NAME T5; }
		CHECKBOX IDC_RPF_ORIGCOLOR	 { NAME T6; }
		CHECKBOX IDC_RPF_COVERAGE { NAME T7; }

		CHECKBOX IDC_RPF_OBJECTID { NAME T8; }
		CHECKBOX IDC_RPF_COLOR { NAME T9; }
		//CHECKBOX IDC_RPF_TRANSPARENCY { NAME T10; }
		CHECKBOX IDC_RPF_SUBPIXEL_WEIGHT { NAME T11; }
		CHECKBOX IDC_RPF_SUBPIXEL_MASK { NAME T12; }
	}
	DLGGROUP { OK;CANCEL;HELP; }
}
