// C4D-DialogResource

DIALOG R_SELECTDLG
{
  NAME T1;

	TAB IDC_SELECTDLG_TAB
	{
		SELECTION_TABS;
		SCALE_H;
		SCALE_V;

		GROUP IDC_SELECTDLG_TAB_OBJECTS
		{
			NAME TOBJECTS;
			COLUMNS 1; 

			CHECKBOX IDC_SELECTDLG_C1 { NAME TC1; }
			CHECKBOX IDC_SELECTDLG_C2 { NAME TC2; }
			CHECKBOX IDC_SELECTDLG_C3 { NAME TC3; }
			CHECKBOX IDC_SELECTDLG_C4 { NAME TC4; }
			CHECKBOX IDC_SELECTDLG_C5 { NAME TC5; }
			//CHECKBOX IDC_SELECTDLG_C6 { NAME TC6; }
			CHECKBOX IDC_SELECTDLG_C7 { NAME TC7; }
			CHECKBOX IDC_SELECTDLG_C8 { NAME TC8; }
			CHECKBOX IDC_SELECTDLG_C9 { NAME TC9; }
			CHECKBOX IDC_SELECTDLG_C10 { NAME TC10; }
			CHECKBOX IDC_SELECTDLG_C11 { NAME TC11; }
			CHECKBOX IDC_SELECTDLG_C12 { NAME TC12; }
			CHECKBOX IDC_SELECTDLG_C13 { NAME TC13; }
		}

		GROUP IDC_SELECTDLG_TAB_TAGS
		{
			NAME TTAGS;
			COLUMNS 1; 

			CHECKBOX IDC_RESTRICTTOACTIVE	{ NAME TRESTRICT; }
			STATICTEXT { }

			GROUP
			{
				COLUMNS 2;

				GROUP
				{
					COLUMNS 1;
					CHECKBOX IDC_SELECTDLG_T1  { NAME TT1; }
					CHECKBOX IDC_SELECTDLG_T2  { NAME TT2; }
					CHECKBOX IDC_SELECTDLG_T3  { NAME TT3; }
					CHECKBOX IDC_SELECTDLG_T4  { NAME TT4; }
					CHECKBOX IDC_SELECTDLG_T5  { NAME TT5; }
					CHECKBOX IDC_SELECTDLG_T6  { NAME TT6; }
					CHECKBOX IDC_SELECTDLG_T7  { NAME TT7; }
					CHECKBOX IDC_SELECTDLG_T8  { NAME TT8; }
					CHECKBOX IDC_SELECTDLG_T9  { NAME TT9; }
					CHECKBOX IDC_SELECTDLG_T10 { NAME TT10; }
					CHECKBOX IDC_SELECTDLG_T11 { NAME TT11; }
					CHECKBOX IDC_SELECTDLG_T12 { NAME TT12; }
					CHECKBOX IDC_SELECTDLG_TNN { NAME TTNN; }
					CHECKBOX IDC_SELECTDLG_T13 { NAME TT13; }
					CHECKBOX IDC_SELECTDLG_T19 { NAME TT19; }
				}
				GROUP
				{
					COLUMNS 1;
					CHECKBOX IDC_SELECTDLG_T14 { NAME TT14; }
					CHECKBOX IDC_SELECTDLG_T15 { NAME TT15; }
					CHECKBOX IDC_SELECTDLG_T17 { NAME TT17; }
					CHECKBOX IDC_SELECTDLG_T18 { NAME TT18; }
				}
			}
		}
	}
}
