// C4D-DialogResource

DIALOG R_TANEDIT1
{
  NAME T1;
  
  GROUP
	{
		ROWS 4;
		
		STATICTEXT { }
		STATICTEXT { NAME T2; }
		STATICTEXT { NAME T3; }
		STATICTEXT { NAME T4; }
		
		STATICTEXT { NAME T5; CENTER_H; }
		EDITNUMBERARROWS IDC_X { SIZE 80,0; }
		EDITNUMBERARROWS IDC_Y { SIZE 80,0; }
		EDITNUMBERARROWS IDC_Z { SIZE 80,0; }
		
		STATICTEXT { }
		STATICTEXT { NAME T2; }
		STATICTEXT { NAME T3; }
		STATICTEXT { NAME T4; }
		
		STATICTEXT { NAME T6; CENTER_H; }
		EDITNUMBERARROWS IDC_X2 { SIZE 80,0; }
		EDITNUMBERARROWS IDC_Y2 { SIZE 80,0; }
		EDITNUMBERARROWS IDC_Z2 { SIZE 80,0; }
		
		STATICTEXT { }
		STATICTEXT { NAME T2; }
		STATICTEXT { NAME T3; }
		STATICTEXT { NAME T4; }
		
		STATICTEXT { NAME T7; CENTER_H; }
		EDITNUMBERARROWS IDC_X3 { SIZE 80,0; }
		EDITNUMBERARROWS IDC_Y3 { SIZE 80,0; }
		EDITNUMBERARROWS IDC_Z3 { SIZE 80,0; }
	}
			
  DLGGROUP { OK;CANCEL;HELP; }
}


