enum
{
	// string table definitions
	IDS_START = 10000,

	IDS_CREATE_SKY_MATERIAL,
	IDS_CREATE_SKY_MATERIAL_HELP,
	IDS_SKY_OBJECT_SKY,
	IDS_SKY_OBJECT_NULL,
	IDS_SKY_OBJECT_SUN,
	IDS_SKY_OBJECT_SUN_LIGHT,
	IDS_SKY_OBJECT_SUN_FLARE,
	IDS_SKY_OBJECT_MOON,
	IDS_SKY_OBJECT_MOON_LIGHT,
	IDS_SKY_MATERIAL,
	IDS_SKY_VOLUME_MATERIAL,
	IDS_SKY_VIDEOPOST,
	IDS_SKY_SHADOW_PLANE,
	IDS_SKY_CLOUD_GROUP_NAME,
	IDS_SKY_CLOUD_GROUP_HELP,
	IDS_SKY_CLOUD_NAME,
	IDS_SKY_CLOUD_HELP,
	IDS_NAME,
	IDS_CONTROL_CENTER,
	IDS_CONTROL_CENTER_HELP,
	IDS_SET_OBJECT,
	IDS_SET_OBJECT_HELP,
	IDS_CLOUD_TOOL,
	IDS_CLOUD_TOOL_HELP,
	IDC_CONNECT_CLOUD,
	IDC_CONNECT_CLOUD_HELP,

	IDS_SUNDAY,
	IDS_MONDAY,
	IDS_TUESDAY,
	IDS_WEDNESDAY,
	IDS_THURSDAY,
	IDS_FRIDAY,
	IDS_SATURDAY,

	IDS_TIME_FORMAT,
	IDS_SKY_PREFS,
	IDS_HOUR_SHORT,
	IDS_MINUTE_SHORT,
	IDS_SECOND_SHORT,
	IDS_KM_SHORT,
	IDS_AU_SHORT,

	IDS_DIRECTION_N,
	IDS_DIRECTION_NE,
	IDS_DIRECTION_E,
	IDS_DIRECTION_SE,
	IDS_DIRECTION_S,
	IDS_DIRECTION_SW,
	IDS_DIRECTION_W,
	IDS_DIRECTION_NW,
	IDS_AZIMUTH,
	IDS_ALTITUDE,
	IDS_AZIMUTH_SHORT,
	IDS_ALTITUDE_SHORT,
	IDS_ANGLE,
	IDS_ILLUMINATE,
	IDS_INTENSITY,
	IDS_SELECT_IMAGE,

	IDS_SAVE_PRESET,
	IDS_SAVE_SKY_PRESET,
	IDS_SAVE_WEATHER_PRESET,

	IDS_NO_PRESET_SAVE,
	IDS_NO_PRESET_LOAD,
	IDS_PRESET_EXISTS,
	IDS_REALLY_DELETE_PRESET,
	IDS_NEW,
	IDS_PRESET_CATALOG,
	IDS_OPENBROWSER_CMD,
	IDS_OPENBROWSER_HELP,
	IDS_PRESET_CATALOG_SKIES,
	IDS_PRESET_CATALOG_WEATHER,
	IDS_PRESET_CATALOG_LAYER,
	IDS_PRESET_KIND_SKY,
	IDS_PRESET_KIND_WEATHER,
	IDS_PRESET_KIND_LAYER,

	IDS_CUSTOM,
	IDS_NEW_CITY,
	IDS_DELETE_CITY,
	IDS_ALREADY_EXISTS,
	IDS_SELECT_MORE_CLOUDS,
	IDS_NO_MEMORY,
	IDS_ERROR_CLOUD_CREATE,
	IDS_CLOUD_SIZE,
	IDS_SKY_PICCOPY,

	// Dialog definitions of IDD_CLOUD_GROUP_DIALOG start here
	IDD_CLOUD_GROUP_DIALOG,
	IDC_SKY_GROUP_LIST,
	IDC_SKY_GROUP_NEW_BTN,
	IDC_SKY_CLOUD_NEW_BTN,
	// Dialog definitions of IDD_CLOUD_GROUP_DIALOG end here

	// Dialog definitions of IDD_NEW_CITY_DIALOG start here
	IDD_NEW_CITY_DIALOG,
	IDD_NEW_CITY_NAME_EDIT,
	IDD_NEW_CITY_COUNTRY_EDIT,
	IDD_NEW_CITY_CONTINENT_EDIT,
	// Dialog definitions of IDD_NEW_CITY_DIALOG end here


	// Dialog definitions of idd_sky_wizard start here
	IDD_SKY_WIZARD,
	IDC_WIZARD_PRESET_COMBO,
	IDC_WIZARD_SAVE_PRESET_BTN,
	IDC_WIZARD_DELETE_PRESET_BTN,
	IDC_WIZARD_GENERAL_PAGE,
	IDC_WIZARD_TIME,
	IDC_WIZARD_DATE,
	IDC_WIZARD_CITY_LIST,
	IDC_WIZARD_LATITUDE,
	IDC_WIZARD_LONGITUDE,
	IDC_WIZARD_APPERANCE_PAGE,
	IDC_WIZARD_CLOUDS_PAGE,
	IDC_WIZARD_CLOUD_EDIT,
	IDC_WIZARD_RANDOM_SEEK_EDIT,
	IDC_WIZARD_CLOUD_MIN_X_EDIT,
	IDC_WIZARD_CLOUD_MAX_X_EDIT,
	IDC_WIZARD_CLOUD_MIN_Y_EDIT,
	IDC_WIZARD_CLOUD_MAX_Y_EDIT,
	IDC_WIZARD_CLOUD_MIN_Z_EDIT,
	IDC_WIZARD_CLOUD_MAX_Z_EDIT,
	IDC_WIZARD_NO_OVERLAP_CHK,
	IDC_WIZARD_AREA_PAGE,
	IDC_WIZARD_AREA_WIDTH_EDIT,
	IDC_WIZARD_AREA_LENGTH_EDIT,
	IDC_WIZARD_AREA_MIN_ALTITUDE_EDIT,
	IDC_WIZARD_AREA_MAX_ALTITUDE_EDIT,
	// Dialog definitions of idd_sky_wizard end here


	// Dialog definitions of IDD_NEW_PRESET_DIALOG start here
	IDD_NEW_PRESET_DIALOG,
	IDC_NEW_PRESET_NAME_EDIT,
	IDC_NEW_PRESET_AUTHOR_EDIT,
	IDC_NEW_PRESET_INFO_EDIT,
	// Dialog definitions of IDD_NEW_PRESET_DIALOG end here


	// Dialog definitions of IDD_SKY_PREFS_DIALOG start here
	IDD_SKY_PREFS_DIALOG,
	IDC_SKY_PREFS_PRESET_PATH_EDIT,
	// Dialog definitions of IDD_SKY_PREFS_DIALOG end here

	// Dialog definitions of idc_sky_dialog start here
	IDC_SKY_DIALOG,
	IDC_SKY_MATERIAL_PREVIEW,
	IDC_SKY_LEFT_ATTRIB_MANAGER,
	IDC_SKY_ATTRIB_MANAGER,
	IDC_SKY_SETTINGS_CURRENT_TIME,
	// Dialog definitions of idc_sky_dialog end here

	IDC_SKY_SKYPRESET,
	IDC_SKY_WEATHERPRESET,

// End of symbol definition
	_DUMMY_ELEMENT_
};
