// C4D-DialogResource
DIALOG IDD_SCULPTBAKE_DIALOG
{
	NAME IDS_SCULPTBAKE_DIALOG;  SCALE_H; SCALE_V;   

	GROUP
	{
		BORDERSIZE 4, 4, 4, 4; 
		SPACE 4, 4;
		SCALE_H;  SCALE_V;   
		COLUMNS 1;

		GROUP 
		{
			COLUMNS 4;
			BORDERSIZE 4, 4, 4, 4; 
			SPACE 4, 4;
			MATPREVIEW IDC_SCULPTBAKE_PREVIEWIMAGE
			{
				OPEN; 
				MIN_WIDTH 150; 
				MIN_HEIGHT 150; 
			}
		}

		GROUP 
		{
			COLUMNS 3;
			BORDERSIZE 4, 4, 4, 4; 
			SPACE 4, 4;
			BUTTON IDC_SCULPTBAKE_PREVIEW { NAME IDS_SCULPTBAKE_PREVIEW; }
			BUTTON IDC_SCULPTBAKE_BAKE { NAME IDS_SCULPTBAKE_BAKE; }
			BUTTON IDC_SCULPTBAKE_STOP { NAME IDS_SCULPTBAKE_STOP; }
		}

		TAB
		{
			SCALE_H; SCALE_V;
			SELECTION_TABS;
			GROUP IDC_SCULPTBAKE_BAKING
			{
				COLUMNS 1;
				NAME IDS_BAKING;
				BORDERSIZE 4, 4, 4, 4; 
				SPACE 4, 4;
				ALIGN_TOP; SCALE_H; SCALE_V;
				GROUP
				{
					ALIGN_TOP; SCALE_H; 
					BORDERSIZE 4, 4, 4, 4; 
					COLUMNS 2;
					SPACE 4, 4;

					STATICTEXT { NAME IDS_SCULPTBAKE_FILENAME; CENTER_V; ALIGN_LEFT; }
  					FILENAME IDC_SCULPTBAKE_FILENAME
					{ 
						NAME IDS_SCULPTBAKE_FILENAME; 
						SAVE;
					}

					STATICTEXT { NAME IDS_SCULPTBAKE_FORMAT; CENTER_V; ALIGN_LEFT; }
					COMBOBOX IDC_SCULPTBAKE_FORMAT
					{
						ALIGN_TOP; SCALE_H; SIZE 150, 0; 
						CHILDS
						{
						}
					}

					STATICTEXT { NAME IDS_SCULPTBAKE_COLORDEPTH; CENTER_V; ALIGN_LEFT; }
					GROUP
					{
						ALIGN_TOP; SCALE_H; 
						BORDERSIZE 0, 0, 0, 0; 
						COLUMNS 2;
						SPACE 4, 4;
          
						COMBOBOX IDC_SCULPTBAKE_COLORDEPTH
						{
							ALIGN_TOP; SCALE_H; SIZE 150, 0; 
							CHILDS
							{
							}
						}
						BUTTON IDC_SCULPTBAKE_FORMAT_OPTIONS { NAME IDS_SCULPTBAKE_FORMAT_OPTIONS; ALIGN_TOP; ALIGN_LEFT; }
					}
				}

				GROUP
				{
					ALIGN_TOP; SCALE_H; ALIGN_LEFT;
					BORDERSIZE 4, 4, 4, 4; 
					COLUMNS 2;
					SPACE 4, 4;

					STATICTEXT { NAME IDS_SCULPTBAKE_SIZEPRESET; CENTER_V; ALIGN_LEFT; }
					COMBOBOX IDC_SCULPTBAKE_SIZEPRESET
					{
						ALIGN_TOP; SCALE_H; SIZE 150, 0; 
						CHILDS
						{
						}
					}
					STATICTEXT { NAME IDS_SCULPTBAKE_LOCKRATIO; CENTER_V; ALIGN_LEFT; }
					CHECKBOX  IDC_SCULPTBAKE_LOCKRATIO { CENTER_V; ALIGN_LEFT; SIZE 70, 0; }

					STATICTEXT { NAME IDS_SCULPTBAKE_WIDTH; CENTER_V; ALIGN_LEFT; }
					EDITNUMBERARROWS IDC_SCULPTBAKE_WIDTH { CENTER_V; ALIGN_LEFT; SIZE 70, 0; }
		
					STATICTEXT { NAME IDS_SCULPTBAKE_HEIGHT; CENTER_V; ALIGN_LEFT; }
					EDITNUMBERARROWS IDC_SCULPTBAKE_HEIGHT { CENTER_V; ALIGN_LEFT; SIZE 70, 0; }

					STATICTEXT { NAME IDS_SCULPTBAKE_PIXELBORDER; CENTER_V; ALIGN_LEFT; }
					EDITNUMBERARROWS IDC_SCULPTBAKE_PIXELBORDER { CENTER_V; ALIGN_LEFT; SIZE 70, 0; }
							
					STATICTEXT { NAME IDS_SCULPTBAKE_SINGLEFILE; CENTER_V; ALIGN_LEFT; }
					CHECKBOX  IDC_SCULPTBAKE_SINGLEFILE { CENTER_V; ALIGN_LEFT; SIZE 70, 0; }

					STATICTEXT { NAME IDS_SCULPTBAKE_CREATERESULTCOPY; CENTER_V; ALIGN_LEFT; }
					CHECKBOX  IDC_SCULPTBAKE_CREATERESULTCOPY { CENTER_V; ALIGN_LEFT; SIZE 70, 0; }

				}
			}

			GROUP IDC_SCULPTBAKE_OPTIONS
			{  
				NAME IDS_OPTIONS;
				BORDERSIZE 4, 4, 4, 4; 
				SPACE 4, 4;
				SCALE_H; SCALE_V; FIT_V;
				COLUMNS 1;
				ALIGN_TOP;

				GROUP
				{
					BORDERSIZE 4, 4, 4, 4; 
					SPACE 4, 4;
					ALIGN_TOP;
					SCALE_H; FIT_V;
					COLUMNS 2;

					STATICTEXT { NAME IDS_SCULPTBAKE_CHANNEL_DISPLACEMENT; CENTER_V; ALIGN_LEFT; }
					CHECKBOX  IDC_SCULPTBAKE_CHANNEL_DISPLACEMENT { CENTER_V; ALIGN_LEFT; SIZE 70, 0; }
		
					STATICTEXT { NAME IDS_SCULPTBAKE_CHANNEL_NORMAL; CENTER_V; ALIGN_LEFT; }
					CHECKBOX  IDC_SCULPTBAKE_CHANNEL_NORMAL { CENTER_V; ALIGN_LEFT; SIZE 70, 0; }
		
					STATICTEXT { NAME IDS_SCULPTBAKE_CHANNEL_AMBIENTOCCLUSION; CENTER_V; ALIGN_LEFT; }
					CHECKBOX  IDC_SCULPTBAKE_CHANNEL_AMBIENTOCCLUSION { CENTER_V; ALIGN_LEFT; SIZE 70, 0; }

					STATICTEXT { NAME IDS_SCULPTBAKE_MAPPING; CENTER_V; ALIGN_LEFT; }
					COMBOBOX IDC_SCULPTBAKE_MAPPING
					{
						ALIGN_TOP; SCALE_H; SIZE 150, 0; 
						CHILDS
						{
							IDC_SCULPTBAKE_MAPPING_OFF, IDS_SCULPTBAKE_MAPPING_OFF;
							IDC_SCULPTBAKE_MAPPING_CUBIC, IDS_SCULPTBAKE_MAPPING_CUBIC;
							IDC_SCULPTBAKE_MAPPING_ANGLE, IDS_SCULPTBAKE_MAPPING_ANGLE;
						}
					}
					//STATICTEXT { NAME IDS_SCULPTBAKE_RELAXCOUNT; CENTER_V; ALIGN_LEFT; }
					//EDITNUMBERARROWS IDC_SCULPTBAKE_RELAXCOUNT { CENTER_V; ALIGN_LEFT; SIZE 70, 0; }

					STATICTEXT { NAME IDS_SCULPTBAKE_TARGETLEVEL_INCLUDETOP; CENTER_V; ALIGN_LEFT; }
					CHECKBOX  IDC_SCULPTBAKE_TARGETLEVEL_INCLUDETOP { CENTER_V; ALIGN_LEFT; SIZE 70, 0; }
				}

				GROUP
				{
					BORDERSTYLE BORDER_GROUP_IN;
					BORDERSIZE 4, 4, 4, 4; 
					SPACE 4, 4;
					SCALE_H; SCALE_V; 

					GROUP 
					{
						NAME IDS_SCULPTBAKE_SOURCELIST;
						BORDERSTYLE BORDER_GROUP_IN;
						BORDERSIZE 4, 4, 4, 4; 
						SPACE 4, 4;
						SCALE_H; SCALE_V;
						//SIZE 250, 200;
						COLUMNS 1;
						TREEVIEW IDC_SCULPTBAKE_SOURCELIST
						{
							SCALE_V; SCALE_H; 
							BORDER; 
							//HIDE_LINES;
							NO_MULTISELECT; 
							HAS_HEADER;
							//MOVE_COLUMN;
							FIXED_LAYOUT;
							NO_BACK_DELETE;
							ALTERNATE_BG;      
						}
					}
					GROUP 
					{
						NAME IDS_SCULPTBAKE_TARGETLIST;
						//SIZE 250, 200;
						BORDERSTYLE BORDER_GROUP_IN;
						BORDERSIZE 4, 4, 4, 4; 
						SPACE 4, 4;
						SCALE_H; SCALE_V;
						COLUMNS 1;
						TREEVIEW IDC_SCULPTBAKE_TARGETLIST
						{
							SCALE_V; SCALE_H; 
							BORDER; 
							//HIDE_LINES;
							NO_MULTISELECT; 
							HAS_HEADER;
							//MOVE_COLUMN;
							FIXED_LAYOUT;
							NO_BACK_DELETE;
							ALTERNATE_BG;      
						}
					}
				}
			}

			GROUP IDC_SCULPTBAKE_SETTINGS
			{
				NAME IDS_SCULPTBAKE_SETTINGS;
				BORDERSIZE 4, 4, 4, 4; 
				SPACE 4, 4;
				SCALE_H; FIT_V;

				COLUMNS 1;

				GROUP IDC_SCULPTBAKE_DISPLACEMENT_SETTINGS
				{  
					NAME IDS_SCULPTBAKE_DISPLACEMENT_SETTINGS;
					BORDERSTYLE BORDER_GROUP_IN;
					BORDERSIZE 4, 4, 4, 4; 
					SPACE 4, 4;

					SCALE_H;

					COLUMNS 2;

					STATICTEXT { NAME IDS_SCULPTBAKE_DISPLACEMENT_METHOD; CENTER_V; ALIGN_LEFT; }
					COMBOBOX IDC_SCULPTBAKE_DISPLACEMENT_METHOD
					{
						ALIGN_TOP; SCALE_H; SIZE 150, 0; 
						CHILDS
						{
							IDC_SCULPTBAKE_DISPLACEMENT_METHOD_INTENSITY, IDS_SCULPTBAKE_DISPLACEMENT_METHOD_INTENSITY;
							IDC_SCULPTBAKE_DISPLACEMENT_METHOD_INTENSITYCENTERED, IDS_SCULPTBAKE_DISPLACEMENT_METHOD_INTENSITYCENTERED;
							IDC_SCULPTBAKE_DISPLACEMENT_METHOD_REDGREEN, IDS_SCULPTBAKE_DISPLACEMENT_METHOD_REDGREEN;
							IDC_SCULPTBAKE_DISPLACEMENT_METHOD_TANGET, IDS_SCULPTBAKE_DISPLACEMENT_METHOD_TANGET;
							IDC_SCULPTBAKE_DISPLACEMENT_METHOD_OBJECT, IDS_SCULPTBAKE_DISPLACEMENT_METHOD_OBJECT;
							IDC_SCULPTBAKE_DISPLACEMENT_METHOD_WORLD, IDS_SCULPTBAKE_DISPLACEMENT_METHOD_WORLD;
						}
					}

					STATICTEXT { NAME IDS_SCULPTBAKE_DISPLACEMENT_ROUNDGEOMETRY; CENTER_V; ALIGN_LEFT; }
					CHECKBOX  IDC_SCULPTBAKE_DISPLACEMENT_ROUNDGEOMETRY { CENTER_V; ALIGN_LEFT; SIZE 70, 0; }					
				}

				GROUP IDC_SCULPTBAKE_NORMAL_SETTINGS
				{
					NAME IDS_SCULPTBAKE_NORMAL_SETTINGS;
					BORDERSTYLE BORDER_GROUP_IN;
					BORDERSIZE 4, 4, 4, 4; 
					SPACE 4, 4;
					SCALE_H;    
					COLUMNS 2;

					STATICTEXT { NAME IDS_SCULPTBAKE_NORMAL_METHOD; CENTER_V; ALIGN_LEFT; }
					COMBOBOX IDC_SCULPTBAKE_NORMAL_METHOD
					{
						ALIGN_TOP; SCALE_H; SIZE 150, 0; 
						CHILDS
						{
							IDC_SCULPTBAKE_NORMAL_METHOD_TANGET, IDS_SCULPTBAKE_NORMAL_METHOD_TANGET;
							IDC_SCULPTBAKE_NORMAL_METHOD_OBJECT, IDS_SCULPTBAKE_NORMAL_METHOD_OBJECT;
							IDC_SCULPTBAKE_NORMAL_METHOD_WORLD, IDS_SCULPTBAKE_NORMAL_METHOD_WORLD;
						}
					}

					STATICTEXT { NAME IDS_SCULPTBAKE_NORMAL_OPTIONS; CENTER_V; ALIGN_LEFT; }
					GROUP
					{
						SCALE_H;    
						COLUMNS 8;

						STATICTEXT { NAME IDS_SCULPTBAKE_NORMAL_FLIP_X; CENTER_V; ALIGN_LEFT; }
						CHECKBOX  IDC_SCULPTBAKE_NORMAL_FLIP_X { CENTER_V; CENTER_H; SIZE 70, 0; }

						STATICTEXT { NAME IDS_SCULPTBAKE_NORMAL_FLIP_Y; CENTER_V; ALIGN_LEFT; }
						CHECKBOX  IDC_SCULPTBAKE_NORMAL_FLIP_Y { CENTER_V; CENTER_H; SIZE 70, 0;  }
						
						STATICTEXT { NAME IDS_SCULPTBAKE_NORMAL_FLIP_Z; CENTER_V; ALIGN_LEFT; }
						CHECKBOX  IDC_SCULPTBAKE_NORMAL_FLIP_Z { CENTER_V; CENTER_H; SIZE 70, 0; }
						
						STATICTEXT { NAME IDS_SCULPTBAKE_NORMAL_SWAP_YZ; CENTER_V; ALIGN_LEFT; }
						CHECKBOX  IDC_SCULPTBAKE_NORMAL_SWAP_YZ { CENTER_V; CENTER_H; SIZE 70, 0; }
					}

					STATICTEXT { NAME IDS_SCULPTBAKE_NORMAL_CONTINUEUVS; CENTER_V; ALIGN_LEFT; }
					CHECKBOX IDC_SCULPTBAKE_NORMAL_CONTINUEUVS { CENTER_V; ALIGN_LEFT; SIZE 70, 0; }
				}

				GROUP IDC_SCULPTBAKE_AO_SETTINGS
				{
					NAME IDS_SCULPTBAKE_AO_SETTINGS;
					BORDERSTYLE BORDER_GROUP_IN;
					BORDERSIZE 4, 4, 4, 4; 
					SPACE 4, 4;
					SCALE_H;    
					COLUMNS 2;

					STATICTEXT { NAME IDS_SCULPTBAKE_AO_ANTIALIASING; CENTER_V; ALIGN_LEFT; }
					EDITNUMBERARROWS IDC_SCULPTBAKE_AO_ANTIALIASING { CENTER_V; ALIGN_LEFT; SIZE 70, 0; }

					STATICTEXT { NAME IDS_SCULPTBAKE_AO_CONTINUEUVS; CENTER_V; ALIGN_LEFT; }
					CHECKBOX IDC_SCULPTBAKE_AO_CONTINUEUVS { CENTER_V; ALIGN_LEFT; SIZE 70, 0; }
				}

				GROUP IDC_SCULPTBAKE_RAYCAST_SETTINGS
				{
					NAME IDS_SCULPTBAKE_RAYCAST_SETTINGS;
					BORDERSTYLE BORDER_GROUP_IN;
					BORDERSIZE 4, 4, 4, 4; 
					SPACE 4, 4;
					SCALE_H;    
					COLUMNS 2;

					STATICTEXT { NAME IDS_SCULPTBAKE_RAYCAST_USE_MAX_DISTANCE; CENTER_V; ALIGN_LEFT; }
					CHECKBOX IDC_SCULPTBAKE_RAYCAST_USE_MAX_DISTANCE { CENTER_V; ALIGN_LEFT; SIZE 70,0; }

					STATICTEXT { NAME IDS_SCULPTBAKE_RAYCAST_CUSTOM_MAX_DISTANCE; CENTER_V; ALIGN_LEFT; }
					EDITNUMBERARROWS IDC_SCULPTBAKE_RAYCAST_CUSTOM_MAX_DISTANCE { CENTER_V; ALIGN_LEFT; SIZE 175,0; }

					STATICTEXT { NAME IDS_SCULPTBAKE_RAYCAST_USE_AUTO_SPIKE_FILTER_THRESHOLD; CENTER_V; ALIGN_LEFT; }
					CHECKBOX IDC_SCULPTBAKE_RAYCAST_USE_AUTO_SPIKE_FILTER_THRESHOLD { CENTER_V; ALIGN_LEFT; SIZE 70,0; }

					STATICTEXT { NAME IDS_SCULPTBAKE_RAYCAST_CUSTOM_SPIKE_FILTER_THRESHOLD; CENTER_V; ALIGN_LEFT; }
					EDITNUMBERARROWS IDC_SCULPTBAKE_RAYCAST_CUSTOM_SPIKE_FILTER_THRESHOLD { CENTER_V; ALIGN_LEFT; SIZE 70,0; }
				}
			}
		} //TABS
	}
}