// C4D-DialogResource
DIALOG IDD_SCALEDOCUMENT
{
  NAME IDS_DIALOG; CENTER_V; CENTER_H; 
  
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC; ALIGN_TOP; ALIGN_LEFT; 
    BORDERSTYLE BORDER_NONE; BORDERSIZE 4, 4, 4, 4; 
    COLUMNS 1;
    
    GROUP IDC_STATIC
    {
      NAME IDS_STATIC3; ALIGN_TOP; ALIGN_LEFT; 
      BORDERSTYLE BORDER_NONE; BORDERSIZE 0, 0, 0, 0; 
      COLUMNS 2;
      
      STATICTEXT IDC_STATIC { NAME IDS_STATIC1; CENTER_V; ALIGN_LEFT; }
      UNITSCALE IDC_SCALEDOCUMENT_CURRENT
      {
        ALIGN_TOP; ALIGN_LEFT; 
      }
      STATICTEXT IDC_STATIC { NAME IDS_STATIC2; CENTER_V; ALIGN_LEFT; }
      UNITSCALE IDC_SCALEDOCUMENT_TARGET
      {
        ALIGN_TOP; ALIGN_LEFT; 
      }
      STATICTEXT IDC_STATIC { NAME IDS_STATIC4; CENTER_V; ALIGN_LEFT; }
      STATICTEXT IDC_SCALEDOCUMENT_EFFECTIVE { FIT_H; CENTER_V; }
    }
  }
  DLGGROUP { OK; CANCEL; }
}