// C4D-DialogResource
DIALOG IDD_SEARCH_DIALOG
{
  NAME T1; FIT_V; SCALE_V; FIT_H; SCALE_H;

  GROUP IDC_STATIC
  {
    NAME IDS_STATIC8; ALIGN_TOP; FIT_H; SCALE_H;
    BORDERSIZE 0, 0, 0, 0;
    ROWS 1;
    SPACE 2, 4;

		WINDOWPIN { ALIGN_LEFT; CENTER_V; };
    ARROWBUTTON IDC_SEARCH_TYPE_ARROW { CENTER_V; CENTER_H; ARROW_RIGHT;  }
    EDITTEXT IDC_SEARCH_NAME_EDIT
    { CENTER_V; FIT_H; SCALE_H; SIZE 70, 0; }
  }
}