// C4D-DialogResource
DIALOG DLG_QUICKLIGHT_MANAGER
{
  NAME IDS_DIALOG; FIT_V; SCALE_V; FIT_H; SCALE_H; 
  
  GROUP IDC_STATIC
  {
    FIT_V; SCALE_V; FIT_H; SCALE_H; 
    BORDERSTYLE BORDER_NONE; BORDERSIZE 0, 0, 0, 0; 
    COLUMNS 1;
    
    USERAREA IDC_QUICKLIGHT { FIT_V; SCALE_V; FIT_H; SCALE_H; SIZE 50, 50; }
  }
}