// C4D-DialogResource
DIALOG DLG_ADDUSERDATA
{
  NAME IDS_DIALOG; SCALE_V; SCALE_H; 
  
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC1; SCALE_V; SCALE_H; 
    BORDERSIZE 0, 0, 0, 0; 
    COLUMNS 2;
    SPACE 4, 4;
    
    STATICTEXT IDC_STATIC { NAME IDS_STATIC7; CENTER_V; ALIGN_LEFT; }
    EDITTEXT IDC_NAME
    { CENTER_V; SCALE_H; SIZE 70, 0; }
    STATICTEXT IDC_STATIC { NAME IDS_STATIC; CENTER_V; ALIGN_LEFT; }
    COMBOBOX IDC_DATATYPE
    {
      ALIGN_TOP; FIT_H; SIZE 150, 0; 
      CHILDS
      {
      }
    }
    STATICTEXT IDC_STATIC { NAME IDS_STATIC2; CENTER_V; ALIGN_LEFT; }
    COMBOBOX IDC_CUSTOMGUI
    {
      ALIGN_TOP; FIT_H; SIZE 150, 0; 
      CHILDS
      {
      }
    }
    STATICTEXT IDC_STATIC { NAME IDS_STATIC3; CENTER_V; ALIGN_LEFT; }
    COMBOBOX IDC_UNIT
    {
      ALIGN_TOP; FIT_H; SIZE 150, 0; 
      CHILDS
      {
      }
    }
    CHECKBOX IDC_MINENABLED { NAME IDS_CHECK; CENTER_V; ALIGN_LEFT;  }
    GROUP IDC_STATIC
    {
      NAME IDS_STATIC10; ALIGN_TOP; ALIGN_LEFT; 
      BORDERSTYLE BORDER_NONE; BORDERSIZE 0, 0, 0, 0; 
      ROWS 1;
      
      EDITNUMBERARROWS IDC_MIN
      { CENTER_V; ALIGN_LEFT; SIZE 70, 0; }
      CHECKBOX IDC_MIN_SLIDERCHECK { NAME IDS_CHECK3; CENTER_V; ALIGN_LEFT;  }
      EDITNUMBERARROWS IDC_MIN_SLIDER
      { CENTER_V; CENTER_H; SIZE 70, 0; }
    }
    CHECKBOX IDC_MAXENABLED { NAME IDS_CHECK1; CENTER_V; ALIGN_LEFT;  }
    GROUP IDC_STATIC
    {
      NAME IDS_STATIC12; CENTER_V; ALIGN_LEFT; 
      BORDERSTYLE BORDER_NONE; BORDERSIZE 0, 0, 0, 0; 
      ROWS 1;
      
      EDITNUMBERARROWS IDC_MAX
      { CENTER_V; ALIGN_LEFT; SIZE 70, 0; }
      CHECKBOX IDC_MAX_SLIDERCHECK { NAME IDS_CHECK4; CENTER_V; ALIGN_LEFT;  }
      EDITNUMBERARROWS IDC_MAX_SLIDER
      { CENTER_V; CENTER_H; SIZE 70, 0; }
    }
    STATICTEXT IDC_STATIC { NAME IDS_STATIC8; CENTER_V; ALIGN_LEFT; }
    EDITNUMBERARROWS IDC_STEP
    { CENTER_V; ALIGN_LEFT; SIZE 70, 0; }
    STATICTEXT  { NAME IDS_STATIC9; CENTER_V; ALIGN_LEFT; }
    MULTILINEEDIT IDC_CYCLE
    { SCALE_V; SCALE_H; }
  }
}