// C4D-DialogResource
DIALOG IDD_INFOMANAGER
{
  NAME IDS_DIALOG; CENTER_V; SCALE_H; 
  
  SCROLLGROUP IDC_STATIC
  {
    NAME IDS_STATIC25; SCALE_V; SCALE_H; 
    NAME IDS_STATIC25; SCALE_V; SCALE_H; SCROLL_V; SCROLL_H; SCROLL_AUTO_H; SCROLL_AUTO_V; 
    
    GROUP IDC_STATIC
    {
      NAME IDS_STATIC26; SCALE_V; SCALE_H; 
      BORDERSIZE 0, 0, 0, 0; 
      COLUMNS 1;
      SPACE 4, 4;
      
      GROUP IDC_TEXTUREINFO
      {
        NAME IDS_STATIC90; SCALE_V; SCALE_H; 
        BORDERSIZE 4, 4, 4, 4; 
        COLUMNS 1;
        SPACE 4, 4;
        
        QUICKTAB IDC_CUSTOM4
        {
          ALIGN_TOP; SCALE_H; 
          BAR; 
          BARTITLE IDS_TEXTURES; 
          ALTERNATIVECOLOR 0; 
        }
        GROUP IDC_STATIC
        {
          NAME IDS_STATIC91; SCALE_V; SCALE_H; 
          BORDERSIZE 0, 0, 0, 0; 
          COLUMNS 1;
          SPACE 4, 4;
          
          GROUP IDC_STATIC
          {
            NAME IDS_STATIC99; ALIGN_TOP; SCALE_H; 
            BORDERSIZE 0, 0, 0, 0; 
            ROWS 1;
            SPACE 4, 4;
            
            STATICTEXT IDC_STATIC { NAME IDS_STATIC97; CENTER_V; ALIGN_LEFT; }
            COMBOBOX IDC_TEXTURES_ACTIVEMATERIALS
            {
              CENTER_V; ALIGN_LEFT; SIZE 150, 0; 
              CHILDS
              {
                0, IDS_TEX_DOCUMENT; 
                1, IDS_TEX_ACTIVE_MATERIALS; 
              }
            }
            STATICTEXT IDC_STATIC { NAME IDS_STATIC100; CENTER_V; SCALE_H; }
          }
          TREEVIEW IDC_TEXTURETREE
          {
            SCALE_V; SCALE_H; 
            BORDER; 
            HIDE_LINES; 
            NO_MULTISELECT; 
            HAS_HEADER; 
            RESIZE_HEADER; 
            MOVE_COLUMN; 
            NO_BACK_DELETE; 
          }
        }
        TEXTURENAME IDC_TEXTURENAME
        {
          ALIGN_TOP; SCALE_H; 
          OPEN; 
        }
        GROUP IDC_STATIC
        {
          NAME IDS_STATIC94; ALIGN_TOP; SCALE_H; 
          BORDERSIZE 0, 0, 0, 0; 
          COLUMNS 2;
          SPACE 4, 4;
          
          STATICTEXT IDC_STATIC { NAME IDS_STATIC101; CENTER_V; SCALE_H; }
          GROUP IDC_STATIC
          {
            NAME IDS_STATIC106; ALIGN_TOP; FIT_H; 
            BORDERSIZE 0, 0, 0, 0; 
            COLUMNS 2;
            EQUAL_COLS; 
            SPACE 4, 4;
            
            BUTTON IDC_TEXTURE_OPEN { NAME IDS_BUTTON29; ALIGN_TOP; SCALE_H; }
            BUTTON IDC_TEXTURE_RELOAD { NAME IDS_BUTTON30; ALIGN_TOP; SCALE_H; }
            BUTTON IDC_TEXTURE_RELOAD_ALL { NAME IDS_BUTTON30b; ALIGN_TOP; SCALE_H; }
            BUTTON IDC_TEXTURE_CHECKALLTEX { NAME IDS_BUTTON31; ALIGN_TOP; SCALE_H; }
          }
        }
      }
      GROUP IDC_OBJECTINFO
      {
        NAME IDS_STATIC2; ALIGN_TOP; SCALE_H; 
        BORDERSIZE 4, 4, 4, 4; 
        COLUMNS 1;
        SPACE 4, 4;
        
        QUICKTAB IDC_CUSTOM1
        {
          ALIGN_TOP; SCALE_H; 
          BAR; 
          BARTITLE IDS_STATIC2; 
          ALTERNATIVECOLOR 0; 
        }
        CHECKBOX IDC_CHILDREN { NAME IDS_CHECK; ALIGN_TOP; ALIGN_LEFT;  }
        SEPARATOR { SCALE_H; }
        GROUP IDC_STATIC
        {
          NAME IDS_STATIC16; ALIGN_TOP; SCALE_H; 
          BORDERSIZE 0, 0, 0, 0; 
          COLUMNS 3;
          SPACE 4, 0;
          
          STATICTEXT IDC_STATIC { NAME IDS_STATIC8; CENTER_V; ALIGN_LEFT; }
          STATICTEXT IDC_STATIC { NAME IDS_STATIC9; CENTER_V; ALIGN_LEFT; }
          STATICTEXT IDC_STATIC { NAME IDS_STATIC10; CENTER_V; ALIGN_LEFT; }
          STATICTEXT IDC_STATIC { NAME IDS_STATIC14; CENTER_V; ALIGN_LEFT; }
          STATICTEXT IDC_OBJECTS1 { NAME IDS_STATIC13; CENTER_V; FIT_H; SIZE 120, 10; BORDERSTYLE BORDER_THIN_IN; }
          STATICTEXT IDC_OBJECTS2 { NAME IDS_STATIC15; CENTER_V; FIT_H; SIZE 120, 10; BORDERSTYLE BORDER_THIN_IN; }
          STATICTEXT IDC_STATIC { NAME IDS_STATIC3; CENTER_V; ALIGN_LEFT; }
          STATICTEXT IDC_POINTS1 { NAME IDS_STATIC6; CENTER_V; FIT_H; SIZE 0, 10; BORDERSTYLE BORDER_THIN_IN; }
          STATICTEXT IDC_POINTS2 { NAME IDS_STATIC7; CENTER_V; FIT_H; SIZE 0, 10; BORDERSTYLE BORDER_THIN_IN; }
          STATICTEXT IDC_STATIC { NAME IDS_STATIC4; CENTER_V; ALIGN_LEFT; }
          STATICTEXT IDC_POLYGONS1 { NAME IDS_STATIC11; CENTER_V; FIT_H; SIZE 0, 10; BORDERSTYLE BORDER_THIN_IN; }
          STATICTEXT IDC_POLYGONS2 { NAME IDS_STATIC12; CENTER_V; FIT_H; SIZE 0, 10; BORDERSTYLE BORDER_THIN_IN; }
          STATICTEXT IDC_STATIC1 { NAME IDS_STATIC; CENTER_V; ALIGN_LEFT; }
          STATICTEXT IDC_MEMORY1 { NAME IDS_STATIC1; CENTER_V; FIT_H; SIZE 0, 10; BORDERSTYLE BORDER_THIN_IN; }
          STATICTEXT IDC_MEMORY2 { NAME IDS_STATIC5; CENTER_V; FIT_H; SIZE 0, 10; }
        }
      }
      GROUP IDC_SELECTIONINFO
      {
        NAME IDS_STATIC22; ALIGN_TOP; SCALE_H; 
        BORDERSIZE 4, 4, 4, 4; 
        COLUMNS 1;
        SPACE 4, 4;
        
        QUICKTAB IDC_CUSTOM3
        {
          ALIGN_TOP; SCALE_H; 
          BAR; 
          BARTITLE IDS_STATIC22; 
          ALTERNATIVECOLOR 0; 
        }
        GROUP IDC_SELECTION_INFO
        {
          NAME IDS_STATIC23; ALIGN_TOP; ALIGN_LEFT; 
          BORDERSIZE 0, 0, 0, 0; 
          COLUMNS 4;
          SPACE 4, 0;
          
          STATICTEXT IDC_STATIC { NAME IDS_STATIC24; CENTER_V; ALIGN_LEFT; }
          STATICTEXT IDC_STATIC { NAME IDS_STATIC27; CENTER_V; ALIGN_LEFT; }
          STATICTEXT IDC_STATIC { NAME IDS_STATIC28; CENTER_V; ALIGN_LEFT; }
          STATICTEXT IDC_STATIC { NAME IDS_STATIC29; CENTER_V; ALIGN_LEFT; }
          STATICTEXT IDC_STATIC { NAME IDS_STATIC30; CENTER_V; ALIGN_LEFT; }
          STATICTEXT IDC_VSEL { NAME IDS_STATIC31; CENTER_V; FIT_H; SIZE 80, 10; BORDERSTYLE BORDER_THIN_IN; }
          STATICTEXT IDC_VTOT { NAME IDS_STATIC32; CENTER_V; FIT_H; SIZE 80, 10; BORDERSTYLE BORDER_THIN_IN; }
          STATICTEXT IDC_VHID { NAME IDS_STATIC33; CENTER_V; FIT_H; SIZE 80, 10; BORDERSTYLE BORDER_THIN_IN; }
          STATICTEXT IDC_STATIC { NAME IDS_STATIC42; CENTER_V; ALIGN_LEFT; }
          STATICTEXT IDC_ESEL { NAME IDS_STATIC43; CENTER_V; FIT_H; SIZE 0, 10; BORDERSTYLE BORDER_THIN_IN; }
          STATICTEXT IDC_ETOT { NAME IDS_STATIC44; CENTER_V; FIT_H; SIZE 0, 10; BORDERSTYLE BORDER_THIN_IN; }
          STATICTEXT IDC_EHID { NAME IDS_STATIC46; CENTER_V; FIT_H; SIZE 0, 10; BORDERSTYLE BORDER_THIN_IN; }
          STATICTEXT IDC_STATIC { NAME IDS_STATIC34; CENTER_V; ALIGN_LEFT; }
          STATICTEXT IDC_PSEL { NAME IDS_STATIC35; CENTER_V; FIT_H; SIZE 0, 10; BORDERSTYLE BORDER_THIN_IN; }
          STATICTEXT IDC_PTOT { NAME IDS_STATIC36; CENTER_V; FIT_H; SIZE 0, 10; BORDERSTYLE BORDER_THIN_IN; }
          STATICTEXT IDC_PHID { NAME IDS_STATIC37; CENTER_V; FIT_H; SIZE 0, 10; BORDERSTYLE BORDER_THIN_IN; }
          STATICTEXT IDC_STATIC { NAME IDS_STATIC47; CENTER_V; ALIGN_LEFT; }
          STATICTEXT IDC_NSEL { NAME IDS_STATIC48; CENTER_V; FIT_H; SIZE 0, 10; BORDERSTYLE BORDER_THIN_IN; }
          STATICTEXT IDC_NTOT { NAME IDS_STATIC49; CENTER_V; FIT_H; SIZE 0, 10; BORDERSTYLE BORDER_THIN_IN; }
          STATICTEXT IDC_NHID { NAME IDS_STATIC50; CENTER_V; FIT_H; SIZE 0, 10; BORDERSTYLE BORDER_THIN_IN; }
          STATICTEXT IDC_STATIC { NAME IDS_STATIC38; CENTER_V; ALIGN_LEFT; }
          STATICTEXT IDC_SEGMENTS { NAME IDS_STATIC39; CENTER_V; FIT_H; SIZE 0, 10; BORDERSTYLE BORDER_THIN_IN; }
          STATICTEXT IDC_STATIC { NAME IDS_STATIC40; CENTER_V; FIT_H; }
          STATICTEXT IDC_STATIC { NAME IDS_STATIC41; CENTER_V; FIT_H; }
        }
      }
      GROUP IDC_STRUCTUREINFO
      {
        NAME IDS_STATIC17; ALIGN_TOP; SCALE_H; 
        BORDERSIZE 4, 4, 4, 4; 
        COLUMNS 1;
        SPACE 4, 4;
        
        QUICKTAB IDC_CUSTOM2
        {
          ALIGN_TOP; SCALE_H; 
          BAR; 
          BARTITLE IDS_STATIC17; 
          ALTERNATIVECOLOR 0; 
        }
        TAB IDC_STRUCTURE_TAB
        {
          NAME IDS_STATIC64; ALIGN_TOP; ALIGN_LEFT; 
          SELECTION_NONE; 
          
          GROUP IDC_POLYOBJECT_POINT_MODE_STRUCTURE
          {
            NAME IDS_STATIC18; ALIGN_TOP; ALIGN_LEFT; 
            BORDERSIZE 0, 0, 0, 0; 
            COLUMNS 4;
            SPACE 4, 0;
            
            STATICTEXT IDC_STATIC { NAME IDS_STATIC51; CENTER_V; ALIGN_LEFT; }
            STATICTEXT IDC_0_POLY { NAME IDS_STATIC52; CENTER_V; FIT_H; SIZE 80, 10; BORDERSTYLE BORDER_THIN_IN; }
            BUTTON IDC_0_POLY_ADD { NAME IDS_BUTTON; ALIGN_TOP; FIT_H; SIZE 20, 10; }
            BUTTON IDC_0_POLY_SUB { NAME IDS_BUTTON1; ALIGN_TOP; FIT_H; SIZE 20, 10; }
            STATICTEXT IDC_STATIC { NAME IDS_STATIC53; CENTER_V; ALIGN_LEFT; }
            STATICTEXT IDC_1_POLY { NAME IDS_STATIC54; CENTER_V; FIT_H; SIZE 0, 10; BORDERSTYLE BORDER_THIN_IN; }
            BUTTON IDC_1_POLY_ADD { NAME IDS_BUTTON2; ALIGN_TOP; FIT_H; SIZE 0, 10; }
            BUTTON IDC_1_POLY_SUB { NAME IDS_BUTTON3; ALIGN_TOP; FIT_H; SIZE 0, 10; }
            STATICTEXT IDC_STATIC { NAME IDS_STATIC59; CENTER_V; ALIGN_LEFT; }
            STATICTEXT IDC_2_POLY { NAME IDS_STATIC55; CENTER_V; FIT_H; SIZE 0, 10; BORDERSTYLE BORDER_THIN_IN; }
            BUTTON IDC_2_POLY_ADD { NAME IDS_BUTTON4; ALIGN_TOP; FIT_H; SIZE 0, 10; }
            BUTTON IDC_2_POLY_SUB { NAME IDS_BUTTON5; ALIGN_TOP; FIT_H; SIZE 0, 10; }
            STATICTEXT IDC_STATIC { NAME IDS_STATIC60; CENTER_V; ALIGN_LEFT; }
            STATICTEXT IDC_3_POLY { NAME IDS_STATIC56; CENTER_V; FIT_H; SIZE 0, 10; BORDERSTYLE BORDER_THIN_IN; }
            BUTTON IDC_3_POLY_ADD { NAME IDS_BUTTON6; ALIGN_TOP; FIT_H; SIZE 0, 10; }
            BUTTON IDC_3_POLY_SUB { NAME IDS_BUTTON7; ALIGN_TOP; FIT_H; SIZE 0, 10; }
            STATICTEXT IDC_STATIC { NAME IDS_STATIC61; CENTER_V; ALIGN_LEFT; }
            STATICTEXT IDC_4_POLY { NAME IDS_STATIC57; CENTER_V; FIT_H; SIZE 0, 10; BORDERSTYLE BORDER_THIN_IN; }
            BUTTON IDC_4_POLY_ADD { NAME IDS_BUTTON12; ALIGN_TOP; FIT_H; SIZE 0, 10; }
            BUTTON IDC_4_POLY_SUB { NAME IDS_BUTTON13; ALIGN_TOP; FIT_H; SIZE 0, 10; }
            STATICTEXT IDC_STATIC { NAME IDS_STATIC62; CENTER_V; ALIGN_LEFT; }
            STATICTEXT IDC_5_POLY { NAME IDS_STATIC58; CENTER_V; FIT_H; SIZE 0, 10; BORDERSTYLE BORDER_THIN_IN; }
            BUTTON IDC_5_POLY_ADD { NAME IDS_BUTTON8; ALIGN_TOP; FIT_H; SIZE 0, 10; }
            BUTTON IDC_5_POLY_SUB { NAME IDS_BUTTON9; ALIGN_TOP; FIT_H; SIZE 0, 10; }
          }
          GROUP IDC_SPLINEOBJECT_STRUCTURE
          {
            NAME IDS_STATIC65; ALIGN_TOP; ALIGN_LEFT; 
            BORDERSIZE 0, 0, 0, 0; 
            COLUMNS 4;
            SPACE 4, 0;
            
            STATICTEXT IDC_STATIC { NAME IDS_STATIC66; CENTER_V; ALIGN_LEFT; }
            STATICTEXT IDC_SPLINE_STRUCT_LENGTH { NAME IDS_STATIC67; CENTER_V; FIT_H; SIZE 80, 10; BORDERSTYLE BORDER_THIN_IN; }
            STATICTEXT IDC_STATIC { NAME IDS_STATIC68; CENTER_V; ALIGN_LEFT; }
            STATICTEXT IDC_STATIC { NAME IDS_STATIC71; CENTER_V; ALIGN_LEFT; }
            STATICTEXT IDC_STATIC { NAME IDS_STATIC69; CENTER_V; ALIGN_LEFT; }
            STATICTEXT IDC_SPLINE_STRUCT_SPLIT { NAME IDS_STATIC70; CENTER_V; FIT_H; SIZE 0, 10; BORDERSTYLE BORDER_THIN_IN; }
            BUTTON IDC_SPLINE_STRUCT_SPLIT_ADD { NAME IDS_BUTTON14; ALIGN_TOP; FIT_H; SIZE 20, 10; }
            BUTTON IDC_SPLINE_STRUCT_SPLIT_SUB { NAME IDS_BUTTON15; ALIGN_TOP; FIT_H; SIZE 20, 10; }
            STATICTEXT IDC_STATIC { NAME IDS_STATIC72; CENTER_V; ALIGN_LEFT; }
            STATICTEXT IDC_SPLINE_STRUCT_SOFT { NAME IDS_STATIC73; CENTER_V; FIT_H; SIZE 0, 10; BORDERSTYLE BORDER_THIN_IN; }
            BUTTON IDC_SPLINE_STRUCT_SOFT_ADD { NAME IDS_BUTTON16; ALIGN_TOP; FIT_H; SIZE 0, 10; }
            BUTTON IDC_SPLINE_STRUCT_SOFT_SUB { NAME IDS_BUTTON17; ALIGN_TOP; FIT_H; SIZE 0, 10; }
            STATICTEXT IDC_STATIC { NAME IDS_STATIC74; CENTER_V; ALIGN_LEFT; }
            STATICTEXT IDC_SPLINE_STRUCT_HARD { NAME IDS_STATIC75; CENTER_V; FIT_H; SIZE 0, 10; BORDERSTYLE BORDER_THIN_IN; }
            BUTTON IDC_SPLINE_STRUCT_HARD_ADD { NAME IDS_BUTTON18; ALIGN_TOP; FIT_H; SIZE 0, 10; }
            BUTTON IDC_SPLINE_STRUCT_HARD_SUB { NAME IDS_BUTTON19; ALIGN_TOP; FIT_H; SIZE 0, 10; }
          }
          GROUP IDC_POLYOBJECT_POLYGON_MODE_STRUCTURE
          {
            NAME IDS_STATIC81; ALIGN_TOP; ALIGN_LEFT; 
            BORDERSIZE 0, 0, 0, 0; 
            COLUMNS 4;
            SPACE 4, 0;
            
            STATICTEXT IDC_STATIC { NAME IDS_STATIC82; CENTER_V; ALIGN_LEFT; }
            STATICTEXT IDC_STRUCT_TRIANG { NAME IDS_STATIC83; CENTER_V; FIT_H; SIZE 80, 10; BORDERSTYLE BORDER_THIN_IN; }
            BUTTON IDC_STRUCT_TRIANG_ADD { NAME IDS_BUTTON20; ALIGN_TOP; ALIGN_LEFT; SIZE 20, 10; }
            BUTTON IDC_STRUCT_TRIANG_SUB { NAME IDS_BUTTON21; ALIGN_TOP; ALIGN_LEFT; SIZE 20, 10; }
            STATICTEXT IDC_STATIC { NAME IDS_STATIC84; CENTER_V; ALIGN_LEFT; }
            STATICTEXT IDC_STRUCT_QUAD { NAME IDS_STATIC85; CENTER_V; FIT_H; SIZE 0, 10; BORDERSTYLE BORDER_THIN_IN; }
            BUTTON IDC_STRUCT_QUAD_ADD { NAME IDS_BUTTON22; ALIGN_TOP; FIT_H; SIZE 0, 10; }
            BUTTON IDC_STRUCT_QUAD_SUB { NAME IDS_BUTTON23; ALIGN_TOP; FIT_H; SIZE 0, 10; }
            STATICTEXT IDC_STATIC { NAME IDS_STATIC108; CENTER_V; ALIGN_LEFT; }
            STATICTEXT IDC_STRUCT_NGONS { NAME IDS_STATIC109; CENTER_V; FIT_H; SIZE 0, 10; BORDERSTYLE BORDER_THIN_IN; }
            BUTTON IDC_STRUCT_NGON_ADD { NAME IDS_BUTTON32; ALIGN_TOP; FIT_H; SIZE 0, 10; }
            BUTTON IDC_STRUCT_NGON_SUB { NAME IDS_BUTTON33; ALIGN_TOP; FIT_H; SIZE 0, 10; }
            STATICTEXT IDC_STATIC { NAME IDS_STATIC86; CENTER_V; ALIGN_LEFT; }
            STATICTEXT IDC_STRUCT_NONPLANAR { NAME IDS_STATIC87; CENTER_V; FIT_H; SIZE 0, 10; BORDERSTYLE BORDER_THIN_IN; }
            BUTTON IDC_STRUCT_NONPLANAR_ADD { NAME IDS_BUTTON24; ALIGN_TOP; FIT_H; SIZE 0, 10; }
            BUTTON IDC_STRUCT_NONPLANAR_SUB { NAME IDS_BUTTON25; ALIGN_TOP; FIT_H; SIZE 0, 10; }
            STATICTEXT IDC_STATIC { NAME IDS_STATIC88; CENTER_V; ALIGN_LEFT; }
            STATICTEXT IDC_STRUCT_DEGEN { NAME IDS_STATIC89; CENTER_V; FIT_H; SIZE 0, 10; BORDERSTYLE BORDER_THIN_IN; }
            BUTTON IDC_STRUCT_DEGEN_ADD { NAME IDS_BUTTON26; ALIGN_TOP; FIT_H; SIZE 0, 10; }
            BUTTON IDC_STRUCT_DEGEN_SUB { NAME IDS_BUTTON27; ALIGN_TOP; FIT_H; SIZE 0, 10; }
          }
          GROUP IDC_MIXED_STRUCTURE
          {
            NAME IDS_STATIC76; ALIGN_TOP; ALIGN_LEFT; 
            BORDERSIZE 0, 0, 0, 0; 
            COLUMNS 1;
            SPACE 4, 4;
            
            STATICTEXT IDC_STATIC { NAME IDS_STATIC78; CENTER_V; ALIGN_LEFT; }
          }
          GROUP IDC_NOTHING_SELECTED_STRUCTURE
          {
            NAME IDS_STATIC79; ALIGN_TOP; ALIGN_LEFT; 
            BORDERSIZE 0, 0, 0, 0; 
            COLUMNS 1;
            SPACE 4, 4;
            
            STATICTEXT IDC_STATIC { NAME IDS_STATIC80; CENTER_V; ALIGN_LEFT; }
          }
        }
      }
    }
  }
}