// C4D-DialogResource
DIALOG IDD_PREVIEW_SETUP_DLG
{
  NAME IDS_DIALOG; CENTER_V; CENTER_H; 
  
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC1; ALIGN_TOP; ALIGN_LEFT; 
    BORDERSIZE 0, 0, 0, 0; 
    COLUMNS 2;
    SPACE 4, 4;
    
    STATICTEXT IDC_STATIC { NAME IDS_STATIC; CENTER_V; ALIGN_LEFT; }
    EDITNUMBER IDC_PREVIEW_ORIG_EDIT
    { CENTER_V; SCALE_H; SIZE 90, 0; }
    STATICTEXT IDC_STATIC { NAME IDS_STATIC3; CENTER_V; ALIGN_LEFT; }
    EDITNUMBERARROWS IDC_PREVIEW_NEW_EDIT
    { CENTER_V; SCALE_H; SIZE 90, 0; }
    STATICTEXT IDC_STATIC { NAME IDS_STATIC4; CENTER_V; ALIGN_LEFT; }
    EDITNUMBERARROWS IDC_PREVIEW_RATIO_EDIT
    { CENTER_V; SCALE_H; SIZE 90, 0; }
    STATICTEXT IDC_STATIC { NAME IDS_STATIC5; CENTER_V; ALIGN_LEFT; }
    EDITNUMBERARROWS IDC_PREVIEW_START_EDIT
    { CENTER_V; SCALE_H; SIZE 90, 0; }
    STATICTEXT IDC_ENV_COLOR_STATIC { NAME IDS_STATIC7; CENTER_V; ALIGN_LEFT; }
    COLORFIELD IDC_PREVIEW_ENV_COLOR { SCALE_V; SCALE_H; NOBRIGHTNESS; NOCOLOR; }
    STATICTEXT IDC_ENV_STRENGTH_STATIC { NAME IDS_STATIC8; CENTER_V; SCALE_H; }
    EDITNUMBERARROWS IDC_PREVIEW_ENV_STRENGTH_EDIT
    { CENTER_V; SCALE_H; SIZE 70, 0; }
  }
  DLGGROUP { OK; CANCEL; }
}