DIALOG IDD_COFFEESCRIPT_DIALOG
{
	NAME T1;
	SCALE_H;
	SCALE_V;

	GROUP
	{
	  SCALE_H;
	  SCALE_V;
		COLUMNS 1;
		BORDERSIZE 4,4,4,4;

		GROUP IDD_COFFEESCRIPT_VARIABLEGROUP
		{
			SCALE_H;
			SCALE_V;
			
			GROUP IDD_COFFEESCRIPT_PYTHONMODE
			{
				SCALE_H;
				SCALE_V;
				COLUMNS 1;

				GROUP
				{
					COLUMNS 2;
					SCALE_H;

					GROUP
					{
						ROWS 1;
						FIT_H;
						BITMAPBUTTON IDC_PYTHONSCRIPT_IMAGE { SIZE -32,-32; BORDER; }
						STATICTEXT { NAME TA; }
					}

					COMBOBOX IDC_PYTHONSCRIPT_SCRIPT { SCALE_H; SIZE 300,0; }
				}
				
				GROUP
				{
					COLUMNS 1;
					SCALE_H;
					SCALE_V;

					MULTILINEEDIT IDC_PYTHONSCRIPT_TEXT
					{
						MONOSPACED;
						PYTHON;
						HIGHLIGHTLINE;
						SYNTAXCOLOR;
						WORDWRAP;
						STATUSBAR;
						SCALE_H;SCALE_V; SIZE 600,100;
					}
				}

				GROUP
				{
					SCALE_H;
					ROWS 1;
					BORDERSIZE 0, 0, 3, 0;

					STATICTEXT { SCALE_H; }

					BUTTON IDC_PYTHONSCRIPT_ASSIGNSHORTCUT { ALIGN_RIGHT; SCALE_V; NAME T13; }
					BUTTON IDC_PYTHONSCRIPT_EXECUTE { ALIGN_RIGHT; SCALE_V; NAME T10; }
				}
			}
		}
	}
}