CONTAINER ToolUntriangulate
{
  NAME ToolUntriangulate;
	INCLUDE ToolBase;

  GROUP MDATA_MAINGROUP
  {
		BOOL MDATA_UNTRIANGULATE_NGONS_DESC {}
		BOOL MDATA_UNTRIANGULATE_ANGLE_DESC {}
	 	REAL MDATA_UNTRIANGULATE_ANGLE_RAD_DESC { UNIT DEGREE; MIN 0.0; MINSLIDER 0.0; MAX 180.0; MAXSLIDER 180.0; CUSTOMGUI REALSLIDER;}
		BOOL MDATA_UNTRIANGULATE_USE_ANGLE_DERIVATION {}
		REAL MDATA_UNTRIANGULATE_ANGLE_DERIVATION { UNIT DEGREE; MIN 0.0; MINSLIDER 0.0; MAX 90.0; MAXSLIDER 90.0; CUSTOMGUI REALSLIDER;}
		BOOL MDATA_UNTRIANGULATE_USE_ALIGNMENT_DERIVATION {}
		REAL MDATA_UNTRIANGULATE_ALIGNMENT_DERIVATION { UNIT DEGREE; MIN 0.0; MINSLIDER 0.0; MAX 90.0; MAXSLIDER 90.0; CUSTOMGUI REALSLIDER;}
		BOOL MDATA_UNTRIANGULATE_RESPECTUVBOUNDARY {}
		BOOL MDATA_UNTRIANGULATE_RESPECTSHADINGBREAKS {}
		BOOL MDATA_UNTRIANGULATE_RESPECTPOLYATTRIBUTES {}
	}
}
