
CONTAINER DistanceBlur
{
	NAME DB_NAME;
	INCLUDE VPbase;

	GROUP ID_VIDEOPOSTPROPERTIES
	{
		DEFAULT 1;

		GROUP
		{
			COLUMNS 2;

			SEPARATOR { }
			REAL DB_FBLUR			{ UNIT PERCENT; MIN 0.0; MAX 100.0; }

			BOOL DB_DBLURON		{}
			REAL DB_DBLUR			{ UNIT PERCENT; MIN 0.0; MAX 100.0; }
			BOOL DB_BBLURON		{}
			REAL DB_BBLUR			{ UNIT PERCENT; MIN 0.0; MAX 100.0; }
			BOOL DB_DOFON			{}
			REAL DB_DOF				{ UNIT PERCENT; MIN 0.0; MAX 100.0; }
			BOOL DB_AFOCUSON	{}
			REAL DB_AFOCUS		{ UNIT PERCENT; MIN 0.0; MAX 100.0; }
		}

		BOOL DB_RANGE_USE		{}
		GRADIENT DB_RANGE_FGRAD	{ PARENTID DB_RANGE_USE; ALPHA; ICC_BASEDOCUMENT; }
		GRADIENT DB_RANGE_BGRAD	{ PARENTID DB_RANGE_USE; ALPHA; ICC_BASEDOCUMENT; }
	}

	GROUP DB_LENS_GROUP
	{
		REAL DB_SHARP		{ UNIT PERCENT; MIN 0.0; MAX 100.0; }
		REAL DB_MINT		{ UNIT PERCENT; MIN 0.0; }
		LONG DB_REFTYPE		{ CYCLE { CIRCULAR; TRIANGLE; RHOMBIC; PENTAGON; HEXAGON; HEPTAGON; OCTAGON; NANOGON; } }
		REAL DB_ROT			{ UNIT DEGREE; }
	}

	GROUP DB_TINT_GROUP
	{
		BOOL DB_TINT_USE		{}
		GRADIENT DB_TINT_FGRAD	{ PARENTID DB_TINT_USE; COLOR; ALPHA; ICC_BASEDOCUMENT; }
		GRADIENT DB_TINT_BGRAD	{ PARENTID DB_TINT_USE; COLOR; ALPHA; ICC_BASEDOCUMENT; }
		BOOL DB_TINT_USERANGE	{}
		SEPARATOR { }
		BOOL DB_TINT_USECAM		{}
		GROUP
		{
			COLUMNS 2;
			REAL DB_TINT_FSTART		{ PARENTID DB_TINT_USECAM; MIN 0.0; UNIT METER; }
			REAL DB_TINT_BSTART		{ PARENTID DB_TINT_USECAM; MIN 0.0; UNIT METER; }
			REAL DB_TINT_FEND		{ PARENTID DB_TINT_USECAM; MIN 0.0; UNIT METER; }
			REAL DB_TINT_BEND		{ PARENTID DB_TINT_USECAM; MIN 0.0; UNIT METER; }
		}
	}
}
