
CONTAINER Glow
{
	NAME GW_NAME;
	INCLUDE VPbase;

	GROUP GW_GLOBALS_GROUP
	{
		DEFAULT 1;
		COLUMNS 2;

		BOOL  GW_CH_OBJON	{ ANIM OFF; }
		LONG  GW_CH_OBJ		{ ANIM OFF; MIN 0; MAX 1000; }
		SEPARATOR { }
		SEPARATOR { }
		SEPARATOR { }
		REAL  GW_MAXSIZE	{ MIN 0.0; MAX 100.0; UNIT PERCENT; }
		SEPARATOR { }
		REAL  GW_DENS		{ MIN 0.0; UNIT PERCENT; }
		SEPARATOR { }
		REAL  GW_BDENS		{ MIN 0.0; UNIT PERCENT; }

		SEPARATOR { }
		REAL  GW_LUM		{ MIN 0.0; MAX 100.0; UNIT PERCENT; }

		BOOL  GW_BLUMON		{}
		REAL  GW_BLUM		{ MIN 0.0; MAX 100.0; UNIT PERCENT; }

		BOOL  GW_GCOL		{}
		COLOR GW_COL		{ SCALE_H; }

		GROUP
		{
			BOOL  GW_GEDGES		{}
			BOOL  GW_ZSCALE		{}
			BOOL  GW_DSCALE		{}
		}
		GROUP
		{
			REAL  GW_BAL		{ MIN 0.0; MAX 100.0; UNIT PERCENT; }
		}
	}

	GROUP GW_NC_GROUP
	{
		GROUP
		{
			BOOL     GW_NC_USE		{}
			REAL     GW_NC_MIN		{ PARENTID GW_NC_USE; MIN 0.0; UNIT PERCENT; }
			REAL     GW_NC_MAX		{ PARENTID GW_NC_USE; MIN 0.0; UNIT PERCENT; }
		}

		SEPARATOR { }
		BOOL     GW_NC_COLON	{}
		COLOR    GW_NC_COL		{ PARENTID GW_NC_COLON; SCALE_H; }
		REAL     GW_NC_COLVAR	{ PARENTID GW_NC_COLON; MIN 0.0; MAX 100.0; UNIT PERCENT; }

		SEPARATOR { }

		GROUP
		{
			COLUMNS 2;
			BOOL     GW_NC_SIZEON	{}
			GRADIENT GW_NC_GSIZE	{ SCALE_H; ALPHA; ICC_BASEDOCUMENT; }
			BOOL     GW_NC_DENSON	{}
			GRADIENT GW_NC_GDENS	{ SCALE_H; ALPHA; ICC_BASEDOCUMENT; }
			BOOL     GW_NC_LUMON	{}
			GRADIENT GW_NC_GLUM		{ SCALE_H; ALPHA; ICC_BASEDOCUMENT; }
			BOOL     GW_NC_GCOL		{}
			GRADIENT GW_NC_GRAD		{ SCALE_H; COLOR; ALPHA; ICC_BASEDOCUMENT; }
		}
	}

	GROUP GW_ATT_GROUP
	{
		BOOL     GW_AT_USE		{}
		REAL     GW_AT_START	{ PARENTID GW_AT_USE; MIN 0.0; UNIT METER; }
		REAL     GW_AT_END		{ PARENTID GW_AT_USE; MIN 0.0; UNIT METER; }
		LONG     GW_AT_POS		{ PARENTID GW_AT_USE; CYCLE { GW_AT_ZBUFFER; GW_AT_3DPOS; } }
		SEPARATOR { }
		GROUP
		{
			COLUMNS 2;
			BOOL     GW_AT_SIZEON	{}
			GRADIENT GW_AT_GSIZE	{ SCALE_H; ALPHA; ICC_BASEDOCUMENT; }
			BOOL     GW_AT_DENSON	{}
			GRADIENT GW_AT_GDENS	{ SCALE_H; ALPHA; ICC_BASEDOCUMENT; }
			BOOL     GW_AT_LUMON	{}
			GRADIENT GW_AT_GLUM		{ SCALE_H; ALPHA; ICC_BASEDOCUMENT; }
			BOOL     GW_AT_GCOL		{}
			GRADIENT GW_AT_GRAD		{ SCALE_H; COLOR; ALPHA; ICC_BASEDOCUMENT; }
		}
	}

	GROUP GW_SN_GROUP
	{
		BOOL     GW_SN_USE		{}
		REAL     GW_SN_SH		{ PARENTID GW_SN_USE; MIN 0.0; MAX 100.0; UNIT PERCENT; }

		GROUP
		{
			COLUMNS 2;
			BOOL     GW_SN_SIZEON	{}
			GRADIENT GW_SN_GSIZE	{ SCALE_H; ALPHA; ICC_BASEDOCUMENT; }
			BOOL     GW_SN_DENSON	{}
			GRADIENT GW_SN_GDENS	{ SCALE_H; ALPHA; ICC_BASEDOCUMENT; }
			BOOL     GW_SN_LUMON	{}
			GRADIENT GW_SN_GLUM		{ SCALE_H; ALPHA; ICC_BASEDOCUMENT; }
			BOOL     GW_SN_GCOL		{}
			GRADIENT GW_SN_GRAD		{ SCALE_H; COLOR; ALPHA; ICC_BASEDOCUMENT; }
		}
	}

	GROUP GW_FF_GROUP
	{
		BOOL  GW_FF_USE		{}
		LONG  GW_FF_TYPE	{ CYCLE { GW_FF_TYPE_GAS; GW_FF_TYPE_FIRE; GW_FF_TYPE_ELEC; } }
		REAL  GW_FF_INT		{ MIN 0.0; UNIT PERCENT; }
		REAL  GW_FF_DENS	{ MIN 0.0; UNIT PERCENT; }
		REAL  GW_FF_BRIGHT	{ UNIT PERCENT; }
		REAL  GW_FF_LUM		{ MIN 0.0; MAX 100.0; UNIT PERCENT; }
		BOOL  GW_FF_COLORON	{}
		COLOR GW_FF_COLOR	{ PARENTID GW_FF_COLORON; }
		REAL  GW_FF_SCALE	{ MIN 0.0; STEP 0.01; }
		REAL  GW_FF_EXP		{ STEP 0.01; }
		REAL  GW_FF_LEVEL	{ MIN 1.0; STEP 0.01; }
		REAL  GW_FF_PHASE	{ UNIT PERCENT; }
		REAL  GW_FF_ANGLE	{ UNIT DEGREE; }
		REAL  GW_FF_SPEED	{ STEP 0.01; }
		BOOL  GW_FF_PSTATIC	{}
		BOOL  GW_FF_ADD		{}
		REAL  GW_FF_STR		{ UNIT PERCENT; MIN 0.0; }
	}
}