CONTAINER HighLights
{
	NAME HLIGHT_NAME;
	INCLUDE VPbase;

	GROUP HLIGHT_GLOBALS_GROUP
	{
		DEFAULT 1;
		REAL HLIGHT_FACEINTENS	{ UNIT PERCENT; MIN 0.0; }
		REAL HLIGHT_MININTENS	{ UNIT PERCENT; MIN 0.0; }
		REAL HLIGHT_MAXINTENS	{ UNIT PERCENT; MIN 0.0; }
		REAL HLIGHT_SIZE { UNIT PERCENT; MIN 0.0; MAX 1000.0; }
		SEPARATOR { }
		LONG HLIGHT_PRESET { CYCLE { HLIGHT_PRESET_CUSTOM; HLIGHT_PRESET_1; HLIGHT_PRESET_2; HLIGHT_PRESET_3; HLIGHT_PRESET_4; HLIGHT_PRESET_5; HLIGHT_PRESET_6; HLIGHT_PRESET_7; HLIGHT_PRESET_8; HLIGHT_PRESET_9; HLIGHT_PRESET_10; HLIGHT_PRESET_11; HLIGHT_PRESET_12; HLIGHT_PRESET_13; HLIGHT_PRESET_14; HLIGHT_PRESET_15; HLIGHT_PRESET_16; HLIGHT_PRESET_17; } }
		LENSGLOW HLIGHT_LENSGLOW { PREVIEW; }
		SEPARATOR { }
		BOOL HLIGHT_USE_OBJID	{}
		LONG HLIGHT_OBJID		{ PARENTID HLIGHT_USE_OBJID; MIN 1; }
	}
}
