CONTAINER Mgirealsky
{
	NAME Mgirealsky;

 	INCLUDE Mpreview;
	INCLUDE Mbase;

	GROUP Obaselist
	{
		BOOL GI_REAL_SKY_PAGE_LOCATION		{ HIDDEN; PAGE; PARENTMSG GI_REAL_SKY_GROUP_LOCATION; }
		BOOL GI_REAL_SKY_PAGE_GLOBAL		{ HIDDEN; PAGE; PARENTMSG GI_REAL_SKY_GROUP_GLOBAL; }
		BOOL GI_REAL_SKY_PAGE_SKY		{ HIDDEN; PAGE; PARENTMSG GI_REAL_SKY_GROUP_SKY; }
		BOOL GI_REAL_SKY_PAGE_SUN		{ HIDDEN; PAGE; PARENTMSG GI_REAL_SKY_GROUP_SUN; }
		BOOL GI_REAL_SKY_PAGE_ATM		{ HIDDEN; PAGE; PARENTMSG GI_REAL_SKY_GROUP_ATM; }
	}

	// ---
	GROUP GI_REAL_SKY_GROUP_LOCATION
	{
		DEFAULT 1;

		REAL GI_REAL_SKY_LATITUDE 		{ UNIT DEGREE; CUSTOMGUI LONG_LAT; MIN -90; MAX 90; }
		REAL GI_REAL_SKY_LONGITUDE 		{ UNIT DEGREE; CUSTOMGUI LONG_LAT; MIN -180; MAX 180; LONGITUDE; }

		SEPARATOR { LINE; }

		DATETIME GI_REAL_SKY_DATETIME 		{ TIME_CONTROL; DATE_CONTROL; TIME_NOW; ANIM MIX;}
		LONG GI_REAL_SKY_TIME_ZONE		{ MIN -12; MAX 12; MINSLIDER -12; MAXSLIDER 12;	STEP 1; FIT_H; }
		
		SEPARATOR { LINE; }

		BOOL GI_REAL_SKY_HUD			{ ANIM OFF; }
	}

	GROUP GI_REAL_SKY_GROUP_GLOBAL
	{
		DEFAULT 1;

		REAL GI_REAL_SKY_TURBIDITY		{ UNIT REAL; MIN 2.0; MAX 16.0; MINSLIDER 2.0; MAXSLIDER 16.0; STEP 0.1; CUSTOMGUI REALSLIDER; }
		REAL GI_REAL_SKY_OZONE			{ UNIT REAL; MIN 0.0; MAX 8.0; MINSLIDER 0.0; MAXSLIDER 8.0; STEP 0.1; CUSTOMGUI REALSLIDER; }
	}

	GROUP GI_REAL_SKY_GROUP_SKY
	{
		DEFAULT 1;

		BOOL GI_REAL_SKY_SKY_ENABLED		{ }
		BOOL GI_REAL_SKY_SKY_HORIZON		{ }
		BOOL GI_REAL_SKY_SKY_WARM_COLORS	{ }
		BOOL GI_REAL_SKY_SKY_CHROMA		{ }
		REAL GI_REAL_SKY_SKY_INTENSITY		{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 10000.0; CUSTOMGUI REALSLIDER; }
		REAL GI_REAL_SKY_SKY_INTENSITY_NIGHT	{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 10000.0; CUSTOMGUI REALSLIDER; }
		REAL GI_REAL_SKY_SKY_SATURATION		{ UNIT PERCENT; MIN 0.0; MAX 200.0; MAXSLIDER 200.0; CUSTOMGUI REALSLIDER; }
		REAL GI_REAL_SKY_SKY_HUE		{ UNIT REAL; MIN 0.0; MAX 1.0; MINSLIDER 0.0; MAXSLIDER 1.0; STEP 0.01; CUSTOMGUI REALSLIDER; } 
		REAL GI_REAL_SKY_SKY_GAMMA		{ UNIT REAL; MIN 0.1; MAX 10.0; MINSLIDER 0.1; MAXSLIDER 10.0; STEP 0.1; CUSTOMGUI REALSLIDER; }
		REAL GI_REAL_SKY_SKY_SEEN_RATIO		{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 10000.0; CUSTOMGUI REALSLIDER; }
	}

	GROUP GI_REAL_SKY_GROUP_SUN
	{
		DEFAULT 1;

		COLOR GI_REAL_SKY_SUN_COLOR		{ ANIM OFF; }

		SEPARATOR { LINE; }

		BOOL GI_REAL_SKY_SUN_ENABLED		{ }
		BOOL GI_REAL_SKY_SUN_WARM_COLORS	{ }
		COLOR GI_REAL_SKY_SUN_SHADOW_COLOR	{ }
		REAL GI_REAL_SKY_SUN_INTENSITY		{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 10000.0; CUSTOMGUI REALSLIDER; }
		REAL GI_REAL_SKY_SUN_SATURATION		{ UNIT PERCENT; MIN 0.0; MAX 200.0; MAXSLIDER 200.0; CUSTOMGUI REALSLIDER; }
		REAL GI_REAL_SKY_SUN_HUE		{ UNIT REAL; MIN 0.0; MAX 1.0; MINSLIDER 0.0; MAXSLIDER 1.0; STEP 0.01; CUSTOMGUI REALSLIDER; } 
		REAL GI_REAL_SKY_SUN_GAMMA		{ UNIT REAL; MIN 0.1; MAX 10.0; MINSLIDER 0.1; MAXSLIDER 10.0; STEP 0.1; CUSTOMGUI REALSLIDER; }
		REAL GI_REAL_SKY_SUN_SIZE_RATIO		{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 10000.0; CUSTOMGUI REALSLIDER; }
		REAL GI_REAL_SKY_SUN_SEEN_RATIO		{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 10000.0; CUSTOMGUI REALSLIDER; }

		SEPARATOR { LINE; }

		LONG GI_REAL_SKY_SUN_SAMPLING_SAMPLES	{ ANIM OFF; MIN 16; MAX 16384; MINSLIDER 16; MAXSLIDER 4096; STEP 16; CUSTOMGUI LONGSLIDER; FIT_H; SCALE_H; }
		REAL GI_REAL_SKY_SUN_SAMPLING_QUALITY	{ ANIM OFF; MIN 0.0; MAX 100.0; MINSLIDER 0.0; MAXSLIDER 100.0; STEP 1.0; UNIT PERCENT; CUSTOMGUI REALSLIDER; FIT_H; SCALE_H; }
	}

	GROUP GI_REAL_SKY_GROUP_ATM
	{
		DEFAULT 1;

		BOOL GI_REAL_SKY_ATM_ENABLED		{ }
		REAL GI_REAL_SKY_ATM_INTENSITY		{ UNIT PERCENT; MIN 0.0; MAX 1000.0; MAXSLIDER 1000.0; CUSTOMGUI REALSLIDER; }
		REAL GI_REAL_SKY_ATM_SATURATION		{ UNIT PERCENT; MIN 0.0; MAX 200.0; MAXSLIDER 200.0; CUSTOMGUI REALSLIDER; }
		REAL GI_REAL_SKY_ATM_HUE		{ UNIT REAL; MIN 0.0; MAX 1.0; MINSLIDER 0.0; MAXSLIDER 1.0; STEP 0.01; CUSTOMGUI REALSLIDER; } 
		REAL GI_REAL_SKY_ATM_GAMMA		{ UNIT REAL; MIN 0.1; MAX 10.0; MINSLIDER 0.1; MAXSLIDER 10.0; STEP 0.1; CUSTOMGUI REALSLIDER; }
		REAL GI_REAL_SKY_ATM_SCALE_RATIO	{ UNIT PERCENT; MIN 0.0; MAX 10000.0; MAXSLIDER 10000.0; CUSTOMGUI REALSLIDER; }
	}


	//GROUP GI_REAL_SKY_GROUP_TEMP
	//{
	//	BUTTON GI_REAL_SKY_BITMAP		{ }
	//	BUTTON GI_REAL_SKY_SEQ			{ }
	//}

	INCLUDE Massign;
}
