CONTAINER MotionBlur
{
	NAME MBLUR_NAME;
	INCLUDE VPbase;

	GROUP MBLUR_GLOBALS_GROUP
	{
		DEFAULT 1;

		REAL  MBLUR_PHASE		{ MIN -100.0; MAX 100.0; UNIT PERCENT; }
		REAL  MBLUR_DENSITY		{ MIN 0.0; MAX 10000.0; UNIT PERCENT; }

		SEPARATOR { }

		LONG  MBLUR_SAMPLES		{ MIN 2; MAX 1000; }
		REAL  MBLUR_BLUR		{ MIN 0.0; MAX 10.0; STEP 0.1; }

		SEPARATOR { }

		BOOL  MBLUR_TRAILS      { }
		BOOL  MBLUR_MESHTRACK   { }
	}
}
