CONTAINER PyroCluster
{
	NAME PSIMF_NAME;
	INCLUDE Mpreview;
	INCLUDE Mbase;

	GROUP Obaselist
	{
		BOOL MATERIAL_PAGE_PROPERTIES { HIDDEN; PAGE; PARENTMSG PSIMF_GLOBALS_GROUP; }
	}

	GROUP PSIMF_GLOBALS_GROUP
	{
		DEFAULT 1;
		GROUP
		{
			BOOL PSIMF_RENDOBJ		{}
			BOOL PSIMF_RENDHOBJ		{}
		}
		LONG PSIMF_RENDMODE		{ CYCLE { REND_MODE_HIGH; REND_MODE_MEDIUM; REND_MODE_LOW; REND_MODE_USER; } }
		SEPARATOR				{ LINE; }
		REAL PSIMF_STEP			{ MIN 0.01; STEP 0.01; }
		REAL PSIMF_LIMIT		{ UNIT PERCENT; MIN 0.0; MAX 100.0; STEP 0.1; }
		SEPARATOR				{ LINE; }
		REAL PSIMF_MAPSTEP		{ MIN 0.01; STEP 0.01; }
		REAL PSIMF_MAPLIMIT		{ UNIT PERCENT; MIN 0.0; MAX 100.0; STEP 0.1; }
		SEPARATOR				{ LINE; }
		REAL PSIMF_SHADSTEP		{ MIN 0.01; STEP 0.01; }
		REAL PSIMF_SHADLIMIT	{ UNIT PERCENT; MIN 0.0; MAX 100.0; STEP 0.1; }
		SEPARATOR				{ LINE; }
		REAL PSIMF_RTCORRECT	{ UNIT PERCENT; MIN 0.0; MAX 100.0; STEP 0.1; }
		BOOL PSIMF_VOLFILTER	{}
	}
}
