CONTAINER VPcaustics
{
	NAME VPcaustics;

	INCLUDE VPbase;

	GROUP ID_VIDEOPOSTPROPERTIES
	{
		BOOL VPCAUSTICS_ENABLEDIFFUSE { ANIM OFF; }
		BOOL VPCAUSTICS_ENABLEVOLUME { ANIM OFF; }
	
		REAL VPCAUSTICS_STRENGTH { ANIM OFF; UNIT PERCENT; MIN 0.0; MAX 100000; }
		REAL VPCAUSTICS_STEPSIZE { ANIM OFF; UNIT METER; MIN 0.001; STEP 0.01; }
		REAL VPCAUSTICS_SAMPLERADIUS { ANIM OFF; UNIT METER; MIN 0.001; STEP 0.01; }
		LONG VPCAUSTICS_SAMPLES { ANIM OFF; MIN 1; MAX 10000; }

		LONG VPCAUSTICS_RECOMPUTE { ANIM OFF; CYCLE { VPCAUSTICS_RECOMPUTE_FIRSTTIME; VPCAUSTICS_RECOMPUTE_ALWAYS; VPCAUSTICS_RECOMPUTE_NEVER; } }

		BOOL VPCAUSTICS_SAVESOLUTION { ANIM OFF; }
		BOOL VPCAUSTICS_CAMERASOLUTION { ANIM OFF; }
	}
}