CONTAINER VPcolormapping
{
	NAME VPcolormapping;
	INCLUDE VPbase;

	GROUP ID_VIDEOPOSTPROPERTIES
	{
		DEFAULT 1;

		GROUP
		{
			COLUMNS 1;

			BOOL COLORMAPPING_EXPONENTIAL {}
			BOOL COLORMAPPING_HSV {}
			BOOL COLORMAPPING_BACKGROUND { }
			REAL COLORMAPPING_DARKMULTIPLIER	 { MIN 0.0; MAX 1000.0; STEP 0.01; }
			REAL COLORMAPPING_BRIGHTMULTIPLIER	 { MIN 0.0; MAX 1000.0; STEP 0.01; }
		}
	}
}
