CONTAINER VPcylinderlens
{
	NAME VPcylinderlens;
	INCLUDE VPbase;

	GROUP ID_VIDEOPOSTPROPERTIES
	{
		DEFAULT 1;

		GROUP
		{
			COLUMNS 1;

			REAL CYLINDERLENS_HORIZONTALFOV	{ MIN 1.0; MAX 360.0; STEP 1.0; UNIT DEGREE; }
			REAL CYLINDERLENS_VERTICALSIZE { MIN 0.01; MAX 1000000.0; STEP 0.01; UNIT METER; }
		}
	}
}
