CONTAINER Xambientocclusion
{
	NAME Xambientocclusion;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		GRADIENT AMBIENTOCCLUSIONSHADER_GRADIENT { ICC_BASEDOCUMENT; }

		REAL AMBIENTOCCLUSIONSHADER_MINLENGTH { UNIT METER; MIN 0.0; STEP 0.1; }
		REAL AMBIENTOCCLUSIONSHADER_MAXLENGTH { UNIT METER; MIN 0.0; STEP 0.1; }

		REAL AMBIENTOCCLUSIONSHADER_DISPERSION { UNIT PERCENT; MIN 0.0; MAX 100.0; }
		REAL AMBIENTOCCLUSIONSHADER_ACCURACY { UNIT PERCENT; MIN 0.0; MAX 100.0; }

		LONG AMBIENTOCCLUSIONSHADER_MINSAMPLES { MIN 1; MAX 10000; }
		LONG AMBIENTOCCLUSIONSHADER_MAXSAMPLES { MIN 1; MAX 10000; }

		REAL AMBIENTOCCLUSIONSHADER_CONTRAST { UNIT PERCENT; MIN -100.0; MAX 100.0; }

		BOOL AMBIENTOCCLUSIONSHADER_ENVIRONMENT {}

		BOOL AMBIENTOCCLUSIONSHADER_TRANSPARENCY {}

		BOOL AMBIENTOCCLUSIONSHADER_SELFTEST {}

		BOOL AMBIENTOCCLUSIONSHADER_REVERSE {}
	}
}