CONTAINER Xsss
{
	NAME Xsss;

	INCLUDE Mpreview;
	INCLUDE Xbase;

	GROUP ID_SHADERPROPERTIES
	{
		GRADIENT SSSSHADER_GRADIENT { ICC_BASEDOCUMENT; }
		REAL SSSSHADER_STRENGTH { UNIT PERCENT; MIN 0.0; MAX 10000.0; }
		REAL SSSSHADER_COLORDENSITY { UNIT METER; MIN 0.0; STEP 0.1; }
		REAL SSSSHADER_DENSITY { UNIT METER; MIN 0.0; STEP 0.1; }
		LONG SSSSHADER_SAMPLES { MIN 1; MAX 1000000; }
		REAL SSSSHADER_MINTHICKNESS { UNIT METER; MIN 0.0; STEP 0.01; }
		REAL SSSSHADER_SCATTERINGLENGTH { UNIT METER; MIN 0.0; STEP 0.01; }
		BOOL SSSSHADER_USE_NORMALS { }
	}
}