// C4D-DialogResource
DIALOG IDD_DISCLAIMER
{
  NAME IDS_DIALOG; SCALE_V; SCALE_H; 
  
  GROUP IDC_STATIC
  {
    SCALE_V; SCALE_H; 
    BORDERSIZE 4, 4, 4, 4; 
    COLUMNS 1;
    SPACE 4, 4;
    
    HTMLVIEWER IDC_DISCLAIMER
    {
      SCALE_V; SCALE_H; SIZE 1200, 400; 
    }
    GROUP IDC_STATIC
    {
      NAME IDS_STATIC1; ALIGN_TOP; CENTER_H; 
      BORDERSIZE 0, 0, 0, 0; 
      ROWS 1;
      EQUAL_COLS; 
      SPACE 4, 4;
      
      BUTTON IDC_ACCEPT { NAME IDS_BUTTON; ALIGN_TOP; ALIGN_LEFT; SIZE 0, 16; }
      BUTTON IDC_DECLINE { NAME IDS_BUTTON1; ALIGN_TOP; ALIGN_LEFT; SIZE 0, 16; }
    }
  }
}