1000474, //Preferences
465001620, // Preferences / Interface 
PREFSINTERFACE-PREFSINTERFACE-PREF_INTERFACE_MAIN_GROUP-PREF_INTERFACE_MACMENU, // Show Mac Menu Bar
PREFSINTERFACE-PREFSINTERFACE-PREF_INTERFACE_MAIN_GROUP-PREF_INTERFACE_ONLINEHELP, // Online Help
PREFSINTERFACE-PREFSINTERFACE-PREF_INTERFACE_MAIN_GROUP-PREF_INTERFACE_EXTERNALHELP, // External Browser
465001626, // PREFS_FILES
PREFSFILES-PREFSFILES-PREF_FILE_MAIN_GROUP-PREF_FILE_ASSETS_LINK, // Link Assets to Project
465001635, // PREFS_MATERIAL
PREFSMATERIAL-PREFSMATERIAL-PREF_MM_MATMANAGERGROUP-PREF_MM_DEFAULT_MATERIAL, // Default Material
465001640, // PREFS_SCHEMECOLORS
465001622, // PREFS_EDITORCOLORS
465001641, // PREFS_HAIR_COLOR
465001621, // PREFS_THEMECOLORS
PREFSHAIRCOLOR-PREFSHAIRCOLOR-PREF_HAIRCOLOR_MAIN_GROUP-PREF_HAIRCOLOR_RESET, // Hair Color
PREFSTHEME-PREFSTHEME-PREF_THEME_MAIN_GROUP-PREF_THEME_RESET, // Reset Color
PREFSCOLOR-PREFSCOLOR-PREF_COLOR_MAIN_GROUP-PREF_COLOR_RESET, // Editor Color
465001638, // PREFS_IMPORTEXPORT
PREFSIMEXPORT-PREFSIMEXPORT-PREF_IMEXPORT_MAIN_GROUP-PREF_IMEXPORT_SHOW_IMPORT_DLG, // Show Import Dialog,	// Show Import Dialog
PREFSIMEXPORT-PREFSIMEXPORT-PREF_IMEXPORT_MAIN_GROUP-PREF_IMEXPORT_SHOW_EXPORT_DLG, // Show Export Dialog,	// Show Export Dialog
PREFSIMEXPORT-PREFSIMEXPORT-PREF_IMEXPORT_MAIN_GROUP-PREF_IMEXPORT_MERGE_ON_DD, // Merge on Drag & Drop,	// Merge on Drag and Drop
465001629 | STUDIO LITE ~ISTRIAL_ENTITLEMENT ~ISNFR_ENTITLEMENT ~ISEDU_ENTITLEMENT ~ISEDUFLOATING_ENTITLEMENT ~ISLITE_ENTITLEMENT, // Preferences / Communication
PREFSCOMMUNICATION-PREFSCOMMUNICATION-PREF_COMMUNICATION_MAINGROUP-PREF_COMMUNICATION_QUICKSTART_DIALOG, // Quick Start Dialog Enabled at Startup

1041349, // Null Tag
100004842, // Show Custom Icons


// R21 Weight Improvement project

1025028, // Wm
OWEIGHTMGR-OWEIGHTMGR-ID_CA_WEIGHT_MGR_AUTOWEIGHT_GROUP-ID_CA_WEIGHT_MGR_AUTOWEIGHT_MODE,
1019881, // Bind
-NET_MAXON_ANIMATION_AUTOWEIGHT_BASE_SMOOTHSTRENGTH,
-NET_MAXON_ANIMATION_AUTOWEIGHT_BASE-NET_MAXON_ANIMATION_AUTOWEIGHT_BASE_SMOOTHGROUP-NET_MAXON_ANIMATION_AUTOWEIGHT_BASE_SMOOTHSTRENGTH,
-NET_MAXON_ANIMATION_AUTOWEIGHT_BASE-NET_MAXON_ANIMATION_AUTOWEIGHT_BASE_SMOOTHGROUP-NET_MAXON_ANIMATION_AUTOWEIGHT_BASE_SMOOTHITERATION,
-NET_MAXON_ANIMATION_AUTOWEIGHT_BONEGLOW-NET_MAXON_ANIMATION_AUTOWEIGHT_BONEGLOW_GROUP-NET_MAXON_ANIMATION_AUTOWEIGHT_BONEGLOW_USEVISIBILITY,
-NET_MAXON_ANIMATION_AUTOWEIGHT_BONEGLOW-NET_MAXON_ANIMATION_AUTOWEIGHT_BONEGLOW_GROUP-NET_MAXON_ANIMATION_AUTOWEIGHT_BONEGLOW_IGNOREINNERPOLY,
-NET_MAXON_ANIMATION_AUTOWEIGHT_BONEGLOW-NET_MAXON_ANIMATION_AUTOWEIGHT_BONEGLOW_GROUP-NET_MAXON_ANIMATION_AUTOWEIGHT_BONEGLOW_VISIBILITYRATIO,
-NET_MAXON_ANIMATION_AUTOWEIGHT_VOXELBONEGLOW-NET_MAXON_ANIMATION_AUTOWEIGHT_VOXELBONEGLOW_GROUP-NET_MAXON_ANIMATION_AUTOWEIGHT_VOXELBONEGLOW_USEVISIBILITY,
-NET_MAXON_ANIMATION_AUTOWEIGHT_VOXELBONEGLOW-NET_MAXON_ANIMATION_AUTOWEIGHT_VOXELBONEGLOW_GROUP-NET_MAXON_ANIMATION_AUTOWEIGHT_VOXELBONEGLOW_IGNOREINNERPOLY,
-NET_MAXON_ANIMATION_AUTOWEIGHT_VOXELBONEGLOW-NET_MAXON_ANIMATION_AUTOWEIGHT_VOXELBONEGLOW_GROUP-NET_MAXON_ANIMATION_AUTOWEIGHT_VOXELBONEGLOW_VISIBILITYRATIO,
-NET_MAXON_ANIMATION_AUTOWEIGHT_VOXELBONEGLOW-NET_MAXON_ANIMATION_AUTOWEIGHT_VOXELBONEGLOW_GROUP-NET_MAXON_ANIMATION_AUTOWEIGHT_VOXELBONEGLOW_USEAUTOVOXELSIZE,
-NET_MAXON_ANIMATION_AUTOWEIGHT_VOXELBONEGLOW-NET_MAXON_ANIMATION_AUTOWEIGHT_VOXELBONEGLOW_GROUP-NET_MAXON_ANIMATION_AUTOWEIGHT_VOXELBONEGLOW_SIZE,

// Quickstart
1050249,

// CX

13680, // License Manager
200000264, // Legal information
200000204, // Quit and Sign out
300002005; // Export License Overview


// Project Asset Inspector

1029486, // Project Asset Inspector
1050522, // Consolidate Assets
1050500, // Image
1050501, // Video
1050502, // Audio
1050503, // External Cache
1050504, // Referenced 3D
1050505, // Other
1050557, // Take
1050848, // Asset Type
1050586, // Element Type
1050849, // Format
1050850, // Resolution
1050882, // File Size
1029823, // Filter Bar
1051186, // Node Space


// UV

170103, // New Texture View...
1038963, // UV Transform
170755, // HUD
170756, // Canvas Axis
170757, // Editor Axis
170758, // UV Units
170759, // UV component highlighting
PREFSOPENGL-PREFSOPENGL-PREF_OPENGL_MAIN_GROUP-PREF_OPENGL_UVEDITOR_ANTIALIAS, // Anti-aliasing
465001624, // OpenGL


// Modeling

5117, // Lathe
OLATHE-ONURBSCAPSLEGACY-ID_CAPSANDROUNDING-CAP_MIGRATE_BUTTON, // Migrate
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_CAP_ENABLE_START, // Start Cap
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_CAP_ENABLE_END, // End Cap
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_BEVEL_SEPARATE, // Separate Bevel Controls
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_TYPE, // Bevel Shape
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_OFFSET, // Size
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_MODE, // Extended Shape
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_HEIGHT, // Height
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_CURVE, // Curve
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_DEPTH, // Shape Depth
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_ABSOLUTE, // Use Absolute Value
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_ABSOLUTEDEPTH, // Max Shape Height
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_SEGMENTS, // Segments
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_LOADPRESET,
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_SAVEPRESET,
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_TYPE, // Bevel Shape
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_OFFSET, // Size
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_MODE, // Extended Shape
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_HEIGHT, // Height
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_CURVE, // Curve
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_DEPTH, // Shape Depth
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_ABSOLUTE, // Use Absolute Value
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_ABSOLUTEDEPTH, // Max Shape Height
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_SEGMENTS, // Segments
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_LOADPRESET,
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_SAVEPRESET,
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_CAP_TYPE, // Caps Type
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_BEVEL_OUTSIDE, // Bevel Outside
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_PHONGBREAKROUNDING, // Break Phong Rounding
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_AVOIDINTERSECTION, // Avoid Self Intersections
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_CAP_DELAUNAY_GRAD, // Density
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_CAP_DELAUNAY_QUAD, // Quad Dominant
OLATHE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_CAP_REGULAR_SIZE,  // Regular
OLATHE-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS, // Polygon Selections
OLATHE-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_POLYGON_SHELL, // Shell
OLATHE-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_POLYGON_CAP_START, // Start Cap
OLATHE-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_POLYGON_CAP_END, // End Cap
OLATHE-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_POLYGON_BEVEL_START, // Start Bevel
OLATHE-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_POLYGON_BEVEL_END, // End Bevel
OLATHE-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_EDGE_SHELL_START, // Start Shell
OLATHE-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_EDGE_SHELL_END, // End Shell
OLATHE-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_EDGE_CAP_START, // Start Cap
OLATHE-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_EDGE_CAP_END, // End Cap
OLATHE-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_EDGE_STEP_START, // Start Step
OLATHE-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_EDGE_STEP_END, // End Step

5118, // Sweep
OSWEEP-ONURBSCAPSLEGACY-ID_CAPSANDROUNDING-CAP_MIGRATE_BUTTON, // Migrate
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_CAP_ENABLE_START, // Start Cap
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_CAP_ENABLE_END, // End Cap
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_BEVEL_SEPARATE, // Separate Bevel Controls
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_TYPE, // Bevel Shape
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_OFFSET, // Size
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_MODE, // Extended Shape
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_HEIGHT, // Height
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_CURVE, // Curve
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_DEPTH, // Shape Depth
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_ABSOLUTE, // Use Absolute Value
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_ABSOLUTEDEPTH, // Max Shape Height
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_SEGMENTS, // Segments
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_LOADPRESET,
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_SAVEPRESET,
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_TYPE, // Bevel Shape
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_OFFSET, // Size
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_MODE, // Extended Shape
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_HEIGHT, // Height
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_CURVE, // Curve
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_DEPTH, // Shape Depth
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_ABSOLUTE, // Use Absolute Value
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_ABSOLUTEDEPTH, // Max Shape Height
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_SEGMENTS, // Segments
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_LOADPRESET,
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_SAVEPRESET,
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_CAP_TYPE, // Caps Type
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_BEVEL_OUTSIDE, // Bevel Outside
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_PHONGBREAKROUNDING, // Break Phong Rounding
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_AVOIDINTERSECTION, // Avoid Self Intersections
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_CAP_DELAUNAY_GRAD, // Density
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_CAP_DELAUNAY_QUAD, // Quad Dominant
OSWEEP-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_CAP_REGULAR_SIZE,  // Regular
OSWEEP-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS, // Polygon Selections
OSWEEP-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_POLYGON_SHELL, // Shell
OSWEEP-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_POLYGON_CAP_START, // Start Cap
OSWEEP-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_POLYGON_CAP_END, // End Cap
OSWEEP-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_POLYGON_BEVEL_START, // Start Bevel
OSWEEP-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_POLYGON_BEVEL_END, // End Bevel
OSWEEP-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_EDGE_SHELL_START, // Start Shell
OSWEEP-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_EDGE_SHELL_END, // End Shell
OSWEEP-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_EDGE_CAP_START, // Start Cap
OSWEEP-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_EDGE_CAP_END, // End Cap
OSWEEP-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_EDGE_STEP_START, // Start Step
OSWEEP-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_EDGE_STEP_END, // End Step

5116, // Extrude
OEXTRUDE-ONURBSCAPSLEGACY-ID_CAPSANDROUNDING-CAP_MIGRATE_BUTTON, // Migrate
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_CAP_ENABLE_START, // Start Cap
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_CAP_ENABLE_END, // End Cap
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_BEVEL_SEPARATE, // Separate Bevel Controls
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_TYPE, // Bevel Shape
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_OFFSET, // Size
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_MODE, // Extended Shape
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_HEIGHT, // Height
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_CURVE, // Curve
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_DEPTH, // Shape Depth
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_ABSOLUTE, // Use Absolute Value
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_ABSOLUTEDEPTH, // Max Shape Height
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_SEGMENTS, // Segments
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_LOADPRESET,
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_SAVEPRESET,
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_TYPE, // Bevel Shape
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_OFFSET, // Size
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_MODE, // Extended Shape
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_HEIGHT, // Height
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_CURVE, // Curve
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_DEPTH, // Shape Depth
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_ABSOLUTE, // Use Absolute Value
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_ABSOLUTEDEPTH, // Max Shape Height
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_SEGMENTS, // Segments
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_LOADPRESET,
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_SAVEPRESET,
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_CAP_TYPE, // Caps Type
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_BEVEL_OUTSIDE, // Bevel Outside
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_PHONGBREAKROUNDING, // Break Phong Rounding
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_AVOIDINTERSECTION, // Avoid Self Intersections
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_CAP_DELAUNAY_GRAD, // Density
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_CAP_DELAUNAY_QUAD, // Quad Dominant
OEXTRUDE-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_CAP_REGULAR_SIZE,  // Regular
OEXTRUDE-ONURBSSELECTION--ID_GENERATOR_SELECTION_POLYGONS, // Polygon Selections
OEXTRUDE-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_POLYGON_SHELL, // Shell
OEXTRUDE-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_POLYGON_CAP_START, // Start Cap
OEXTRUDE-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_POLYGON_CAP_END, // End Cap
OEXTRUDE-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_POLYGON_BEVEL_START, // Start Bevel
OEXTRUDE-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_POLYGON_BEVEL_END, // End Bevel
OEXTRUDE-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_EDGE_SHELL_START, // Start Shell
OEXTRUDE-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_EDGE_SHELL_END, // End Shell
OEXTRUDE-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_EDGE_CAP_START, // Start Cap
OEXTRUDE-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_EDGE_CAP_END, // End Cap
OEXTRUDE-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_EDGE_STEP_START, // Start Step
OEXTRUDE-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_EDGE_STEP_END, // End Step

5107, // Loft
OLOFT-ONURBSCAPSLEGACY-ID_CAPSANDROUNDING-CAP_MIGRATE_BUTTON, // Migrate
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_CAP_ENABLE_START, // Start Cap
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_CAP_ENABLE_END, // End Cap
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_BEVEL_SEPARATE, // Separate Bevel Controls
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_TYPE, // Bevel Shape
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_OFFSET, // Size
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_MODE, // Extended Shape
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_HEIGHT, // Height
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_CURVE, // Curve
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_DEPTH, // Shape Depth
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_ABSOLUTE, // Use Absolute Value
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_ABSOLUTEDEPTH, // Max Shape Height
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_SEGMENTS, // Segments
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_LOADPRESET, 
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_SAVEPRESET, 
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_TYPE, // Bevel Shape
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_OFFSET, // Size
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_MODE, // Extended Shape
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_HEIGHT, // Height
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_CURVE, // Curve
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_DEPTH, // Shape Depth
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_ABSOLUTE, // Use Absolute Value
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_ABSOLUTEDEPTH, // Max Shape Height
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_SEGMENTS, // Segments
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_LOADPRESET, 
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_SAVEPRESET, 
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_CAP_TYPE, // Caps Type
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_BEVEL_OUTSIDE, // Bevel Outside
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_PHONGBREAKROUNDING, // Break Phong Rounding
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_AVOIDINTERSECTION, // Avoid Self Intersections
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_CAP_DELAUNAY_GRAD, // Density
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_CAP_DELAUNAY_QUAD, // Quad Dominant
OLOFT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_CAP_REGULAR_SIZE,  // Regular
OLOFT-ONURBSSELECTION--ID_GENERATOR_SELECTION_POLYGONS, // Polygon Selections
OLOFT-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_POLYGON_SHELL, // Shell
OLOFT-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_POLYGON_CAP_START, // Start Cap
OLOFT-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_POLYGON_CAP_END, // End Cap
OLOFT-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_POLYGON_BEVEL_START, // Start Bevel
OLOFT-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_POLYGON_BEVEL_END, // End Bevel
OLOFT-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_EDGE_SHELL_START, // Start Shell
OLOFT-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_EDGE_SHELL_END, // End Shell
OLOFT-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_EDGE_CAP_START, // Start Cap
OLOFT-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_EDGE_CAP_END, // End Cap
OLOFT-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_EDGE_STEP_START, // Start Step
OLOFT-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_EDGE_STEP_END, // End Step

1019268, // MoText
OMOGRAPH_TEXT-ONURBSCAPSLEGACY-ID_CAPSANDROUNDING-CAP_MIGRATE_BUTTON, // Migrate
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_CAP_ENABLE_START, // Start Cap
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_CAP_ENABLE_END, // End Cap
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_BEVEL_SEPARATE, // Separate Bevel Controls
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_TYPE, // Bevel Shape
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_OFFSET, // Size
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_MODE, // Extended Shape
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_HEIGHT, // Height
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_CURVE, // Curve
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_DEPTH, // Shape Depth
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_ABSOLUTE, // Use Absolute Value
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_ABSOLUTEDEPTH, // Max Shape Height
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_SEGMENTS, // Segments
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_LOADPRESET,
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_STARTBEVEL_SAVEPRESET,
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_TYPE, // Bevel Shape
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_OFFSET, // Size
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_MODE, // Extended Shape
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_HEIGHT, // Height
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_CURVE, // Curve
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_DEPTH, // Shape Depth
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_ABSOLUTE, // Use Absolute Value
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_ABSOLUTEDEPTH, // Max Shape Height
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_SEGMENTS, // Segments
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_LOADPRESET,
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_ENDBEVEL_SAVEPRESET,
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_CAP_TYPE, // Caps Type
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_BEVEL_OUTSIDE, // Bevel Outside
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_PHONGBREAKROUNDING, // Break Phong Rounding
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_AVOIDINTERSECTION, // Avoid Self Intersections
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_CAP_DELAUNAY_GRAD, // Density
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_CAP_DELAUNAY_QUAD, // Quad Dominant
OMOGRAPH_TEXT-ONURBSCAPS-ID_CAPSANDBEVELS-CAPSANDBEVELS_CAP_REGULAR_SIZE,  // Regular
OMOGRAPH_TEXT-ONURBSSELECTION--ID_GENERATOR_SELECTION_POLYGONS, // Polygon Selections
OMOGRAPH_TEXT-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_POLYGON_SHELL, // Shell
OMOGRAPH_TEXT-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_POLYGON_CAP_START, // Start Cap
OMOGRAPH_TEXT-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_POLYGON_CAP_END, // End Cap
OMOGRAPH_TEXT-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_POLYGON_BEVEL_START, // Start Bevel
OMOGRAPH_TEXT-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_POLYGON_BEVEL_END, // End Bevel
OMOGRAPH_TEXT-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_EDGE_SHELL_START, // Start Shell
OMOGRAPH_TEXT-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_EDGE_SHELL_END, // End Shell
OMOGRAPH_TEXT-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_EDGE_CAP_START, // Start Cap
OMOGRAPH_TEXT-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_EDGE_CAP_END, // End Cap
OMOGRAPH_TEXT-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_EDGE_STEP_START, // Start Step
OMOGRAPH_TEXT-ONURBSSELECTION-ID_GENERATOR_SELECTION_POLYGONS-GENERATOR_SELECTION_EDGE_STEP_END, // End Step

// Materials

202586, // New Default Material
72000, // Node Spaces
202541, // New Node Material
465002211, // Node Editor
465002336, // New Input Node
465002337, // New Output Node
[NodeAsset] net.maxon.pattern.node.twod.areaaverage, // Area Average
NET_MAXON_PATTERN_NODE_TWOD_AREAAVERAGE-NET_MAXON_PATTERN_NODE_TWOD_AREAAVERAGE-NET_MAXON_NODE_BASE_GROUP_INPUTS-COLOR, // Color
NET_MAXON_PATTERN_NODE_TWOD_AREAAVERAGE-NET_MAXON_PATTERN_NODE_TWOD_AREAAVERAGE-NET_MAXON_NODE_BASE_GROUP_INPUTS-WIDTH, // Width
NET_MAXON_PATTERN_NODE_TWOD_AREAAVERAGE-NET_MAXON_PATTERN_NODE_TWOD_AREAAVERAGE-NET_MAXON_NODE_BASE_GROUP_INPUTS-HEIGHT, // Height
NET_MAXON_PATTERN_NODE_TWOD_AREAAVERAGE-NET_MAXON_PATTERN_NODE_TWOD_AREAAVERAGE-NET_MAXON_NODE_BASE_GROUP_INPUTS-MASK, // Mask Area

[NodeAsset] net.maxon.pattern.node.twod.blur, // Blur
NET_MAXON_PATTERN_NODE_TWOD_BLUR-NET_MAXON_PATTERN_NODE_TWOD_BLUR-NET_MAXON_NODE_BASE_GROUP_INPUTS-COLOR, // Color
NET_MAXON_PATTERN_NODE_TWOD_BLUR-NET_MAXON_PATTERN_NODE_TWOD_BLUR-NET_MAXON_NODE_BASE_GROUP_INPUTS-RADIUS, // Radius
NET_MAXON_PATTERN_NODE_TWOD_BLUR-NET_MAXON_PATTERN_NODE_TWOD_BLUR-NET_MAXON_NODE_BASE_GROUP_INPUTS-MODE, // Mode
NET_MAXON_PATTERN_NODE_TWOD_BLUR-NET_MAXON_PATTERN_NODE_TWOD_BLUR-NET_MAXON_NODE_BASE_GROUP_INPUTS-RESOLUTION, // Resolution
NET_MAXON_PATTERN_NODE_TWOD_BLUR-NET_MAXON_PATTERN_NODE_TWOD_BLUR-NET_MAXON_NODE_BASE_GROUP_INPUTS-INTERPOLATION, // Interpolation
NET_MAXON_PATTERN_NODE_TWOD_BLUR-NET_MAXON_PATTERN_NODE_TWOD_BLUR-NET_MAXON_NODE_BASE_GROUP_INPUTS-SAMPLES, // Samples
NET_MAXON_PATTERN_NODE_TWOD_BLUR-NET_MAXON_PATTERN_NODE_TWOD_BLUR-NET_MAXON_NODE_BASE_GROUP_INPUTS-SEED, // Seed
NET_MAXON_PATTERN_NODE_TWOD_BLUR-NET_MAXON_PATTERN_NODE_TWOD_BLUR-NET_MAXON_NODE_BASE_GROUP_INPUTS-STATICNOISE, // Static Noise
NET_MAXON_PATTERN_NODE_TWOD_BLUR-NET_MAXON_NODE_GROUPPORTS-NET_MAXON_NODE_BASE_GROUP_INPUTS-RENDERMODE, // Input
NET_MAXON_PATTERN_NODE_TWOD_BLUR-NET_MAXON_RENDER_INCLUDE_CONTEXT-NET_MAXON_RENDER_NODE_BASE_GROUP_CONTEXT-CONTEXT, // Context
NET_MAXON_PATTERN_NODE_TWOD_BLUR-NET_MAXON_PATTERN_INCLUDE_COLORMASK-NET_MAXON_PATTERN_INCLUDE_WITHMASK_GROUP-MASKBLEND, // Blend
NET_MAXON_PATTERN_NODE_TWOD_BLUR-NET_MAXON_PATTERN_INCLUDE_COLORMASK-MASKCOMPONENTS-MASKRED, // Red
NET_MAXON_PATTERN_NODE_TWOD_BLUR-NET_MAXON_PATTERN_INCLUDE_COLORMASK-MASKCOMPONENTS-MASKGREEN, // Green
NET_MAXON_PATTERN_NODE_TWOD_BLUR-NET_MAXON_PATTERN_INCLUDE_COLORMASK-MASKCOMPONENTS-MASKBLUE, // Blue
NET_MAXON_PATTERN_NODE_TWOD_BLUR-NET_MAXON_PATTERN_INCLUDE_COLORMASK-MASKCOMPONENTS-MASKALPHA, // Alpha

[NodeAsset] net.maxon.pattern.node.twod.cache, // Cache
NET_MAXON_PATTERN_NODE_TWOD_CACHE-NET_MAXON_PATTERN_NODE_TWOD_CACHE-NET_MAXON_NODE_BASE_GROUP_INPUTS-COLOR, // Color
NET_MAXON_PATTERN_NODE_TWOD_CACHE-NET_MAXON_PATTERN_NODE_TWOD_CACHE-NET_MAXON_NODE_BASE_GROUP_INPUTS-WIDTH, // Width
NET_MAXON_PATTERN_NODE_TWOD_CACHE-NET_MAXON_PATTERN_NODE_TWOD_CACHE-NET_MAXON_NODE_BASE_GROUP_INPUTS-HEIGHT, // Height
NET_MAXON_PATTERN_NODE_TWOD_CACHE-NET_MAXON_PATTERN_NODE_TWOD_CACHE-NET_MAXON_NODE_BASE_GROUP_INPUTS-INTERPOLATION, // Interpolation

[NodeAsset] net.maxon.pattern.node.generator.ray, // Trace Ray
[NodeAsset] net.maxon.pattern.node.utility.shadingcontext, // Get Context

[NodeAsset] net.maxon.pattern.node.twod.kernel, // Kernel
NET_MAXON_PATTERN_NODE_TWOD_KERNEL-NET_MAXON_PATTERN_NODE_TWOD_KERNEL-NET_MAXON_NODE_BASE_GROUP_INPUTS-COLOR, // Color
NET_MAXON_PATTERN_NODE_TWOD_KERNEL-NET_MAXON_PATTERN_NODE_TWOD_KERNEL-NET_MAXON_NODE_BASE_GROUP_INPUTS-RESOLUTION, // Resolution
NET_MAXON_PATTERN_NODE_TWOD_KERNEL--NET_MAXON_NODE_BASE_GROUP_INPUTS-NET_MAXON_PATTERN_NODE_TWOD_KERNEL_UHXDO4NQBVATSQQ4VQZ5CJ, // Preset
NET_MAXON_PATTERN_NODE_TWOD_KERNEL-NET_MAXON_PATTERN_NODE_TWOD_KERNEL-NET_MAXON_NODE_BASE_GROUP_INPUTS-NORMALIZE, // Normalize Kernel
NET_MAXON_PATTERN_NODE_TWOD_KERNEL-NET_MAXON_PATTERN_NODE_TWOD_KERNEL-NET_MAXON_PATTERN_NODE_TWOD_KERNEL_B2T0TRDTJRPV_RJXJ6IMZD-KERNEL00, // 1
NET_MAXON_PATTERN_NODE_TWOD_KERNEL-NET_MAXON_PATTERN_NODE_TWOD_KERNEL-NET_MAXON_PATTERN_NODE_TWOD_KERNEL_B2T0TRDTJRPV_RJXJ6IMZD-KERNEL01, // 2
NET_MAXON_PATTERN_NODE_TWOD_KERNEL-NET_MAXON_PATTERN_NODE_TWOD_KERNEL-NET_MAXON_PATTERN_NODE_TWOD_KERNEL_B2T0TRDTJRPV_RJXJ6IMZD-KERNEL02, // 3
NET_MAXON_PATTERN_NODE_TWOD_KERNEL-NET_MAXON_PATTERN_NODE_TWOD_KERNEL-NET_MAXON_PATTERN_NODE_TWOD_KERNEL_B2T0TRDTJRPV_RJXJ6IMZD-KERNEL10, // 4
NET_MAXON_PATTERN_NODE_TWOD_KERNEL-NET_MAXON_PATTERN_NODE_TWOD_KERNEL-NET_MAXON_PATTERN_NODE_TWOD_KERNEL_B2T0TRDTJRPV_RJXJ6IMZD-KERNEL11, // 5
NET_MAXON_PATTERN_NODE_TWOD_KERNEL-NET_MAXON_PATTERN_NODE_TWOD_KERNEL-NET_MAXON_PATTERN_NODE_TWOD_KERNEL_B2T0TRDTJRPV_RJXJ6IMZD-KERNEL12, // 6
NET_MAXON_PATTERN_NODE_TWOD_KERNEL-NET_MAXON_PATTERN_NODE_TWOD_KERNEL-NET_MAXON_PATTERN_NODE_TWOD_KERNEL_B2T0TRDTJRPV_RJXJ6IMZD-KERNEL20, // 7
NET_MAXON_PATTERN_NODE_TWOD_KERNEL-NET_MAXON_PATTERN_NODE_TWOD_KERNEL-NET_MAXON_PATTERN_NODE_TWOD_KERNEL_B2T0TRDTJRPV_RJXJ6IMZD-KERNEL21, // 8
NET_MAXON_PATTERN_NODE_TWOD_KERNEL-NET_MAXON_PATTERN_NODE_TWOD_KERNEL-NET_MAXON_PATTERN_NODE_TWOD_KERNEL_B2T0TRDTJRPV_RJXJ6IMZD-KERNEL22, // 9
NET_MAXON_PATTERN_NODE_TWOD_KERNEL-NET_MAXON_RENDER_INCLUDE_CONTEXT-NET_MAXON_RENDER_NODE_BASE_GROUP_CONTEXT-CONTEXT, // Context
NET_MAXON_PATTERN_NODE_TWOD_KERNEL-NET_MAXON_PATTERN_INCLUDE_COLORMASK-NET_MAXON_PATTERN_INCLUDE_WITHMASK_GROUP-MASKBLEND, // Blend
NET_MAXON_PATTERN_NODE_TWOD_KERNEL-NET_MAXON_PATTERN_INCLUDE_COLORMASK-MASKCOMPONENTS-MASKRED, // Red
NET_MAXON_PATTERN_NODE_TWOD_KERNEL-NET_MAXON_PATTERN_INCLUDE_COLORMASK-MASKCOMPONENTS-MASKGREEN, // Green
NET_MAXON_PATTERN_NODE_TWOD_KERNEL-NET_MAXON_PATTERN_INCLUDE_COLORMASK-MASKCOMPONENTS-MASKBLUE, // Blue
NET_MAXON_PATTERN_NODE_TWOD_KERNEL-NET_MAXON_PATTERN_INCLUDE_COLORMASK-MASKCOMPONENTS-MASKALPHA, // Alpha

[NodeAsset] net.maxon.pattern.node.generator.multiray, // Trace Multi-Ray
NET_MAXON_PATTERN_NODE_GENERATOR_MULTIRAY-NET_MAXON_PATTERN_NODE_GENERATOR_MULTIRAY-NET_MAXON_NODE_BASE_GROUP_INPUTS-ORIGIN, // Origin
NET_MAXON_PATTERN_NODE_GENERATOR_MULTIRAY-NET_MAXON_PATTERN_NODE_GENERATOR_MULTIRAY-NET_MAXON_NODE_BASE_GROUP_INPUTS-DIRECTION, // Direction
NET_MAXON_PATTERN_NODE_GENERATOR_MULTIRAY-NET_MAXON_PATTERN_NODE_GENERATOR_MULTIRAY-NET_MAXON_NODE_BASE_GROUP_INPUTS-DISPERSION, // Spread
NET_MAXON_PATTERN_NODE_GENERATOR_MULTIRAY-NET_MAXON_PATTERN_NODE_GENERATOR_MULTIRAY-NET_MAXON_NODE_BASE_GROUP_INPUTS-MINLENGTH, // Min Ray Length
NET_MAXON_PATTERN_NODE_GENERATOR_MULTIRAY-NET_MAXON_PATTERN_NODE_GENERATOR_MULTIRAY-NET_MAXON_NODE_BASE_GROUP_INPUTS-MAXLENGTH, // Max Ray Length
NET_MAXON_PATTERN_NODE_GENERATOR_MULTIRAY-NET_MAXON_PATTERN_NODE_GENERATOR_MULTIRAY-NET_MAXON_NODE_BASE_GROUP_INPUTS-IGNORE, // Ignore
NET_MAXON_PATTERN_NODE_GENERATOR_MULTIRAY-NET_MAXON_PATTERN_NODE_GENERATOR_MULTIRAY-QUALITY-MINSAMPLES, // Min Samples
NET_MAXON_PATTERN_NODE_GENERATOR_MULTIRAY-NET_MAXON_PATTERN_NODE_GENERATOR_MULTIRAY-QUALITY-MAXSAMPLES, // Max Samples
NET_MAXON_PATTERN_NODE_GENERATOR_MULTIRAY-NET_MAXON_PATTERN_NODE_GENERATOR_MULTIRAY-QUALITY-ACCURACY, // Accuracy

[NodeAsset] net.maxon.pattern.node.shape.line, // Line
NET_MAXON_PATTERN_NODE_SHAPE_LINE-NET_MAXON_PATTERN_NODE_SHAPE_LINE-NET_MAXON_NODE_BASE_GROUP_INPUTS-EXTERIOR, // Exterior
NET_MAXON_PATTERN_NODE_SHAPE_LINE-NET_MAXON_PATTERN_NODE_SHAPE_LINE-NET_MAXON_NODE_BASE_GROUP_INPUTS-FILL, // Fill
NET_MAXON_PATTERN_NODE_SHAPE_LINE-NET_MAXON_PATTERN_NODE_SHAPE_LINE-NET_MAXON_NODE_BASE_GROUP_INPUTS-SOURCE, // Source
NET_MAXON_PATTERN_NODE_SHAPE_LINE-NET_MAXON_PATTERN_NODE_SHAPE_LINE-NET_MAXON_NODE_BASE_GROUP_INPUTS-DESTINATION, // Destination
NET_MAXON_PATTERN_NODE_SHAPE_LINE-NET_MAXON_PATTERN_NODE_SHAPE_LINE-NET_MAXON_NODE_BASE_GROUP_INPUTS-SOFTNESS, // Softness
NET_MAXON_PATTERN_NODE_SHAPE_LINE-NET_MAXON_PATTERN_NODE_SHAPE_LINE-NET_MAXON_NODE_BASE_GROUP_INPUTS-WIDTH, // Width

[NodeAsset] net.maxon.pattern.node.generator.scratches, // Scratches
NET_MAXON_PATTERN_NODE_GENERATOR_SCRATCHES-NET_MAXON_PATTERN_NODE_GENERATOR_SCRATCHES-NET_MAXON_NODE_BASE_GROUP_INPUTS-SEED, // Seed

[NodeAsset] net.maxon.node.average, // Average
NET_MAXON_NODE_AVERAGE-NET_MAXON_NODE_AVERAGE-NET_MAXON_NODE_BASE_GROUP_INPUTS-OPERATION, // Operation

[NodeAsset] net.maxon.node.exp, // Exp
NET_MAXON_NODE_EXP-NET_MAXON_NODE_EXP-NET_MAXON_NODE_BASE_GROUP_INPUTS-DATATYPE, // Data Type
NET_MAXON_NODE_EXP-NET_MAXON_NODE_EXP-NET_MAXON_NODE_BASE_GROUP_INPUTS-IN, // Value

[NodeAsset] net.maxon.node.exp2, // Exp2
NET_MAXON_NODE_EXP2-NET_MAXON_NODE_EXP2-NET_MAXON_NODE_BASE_GROUP_INPUTS-DATATYPE, // Data Type
NET_MAXON_NODE_EXP2-NET_MAXON_NODE_EXP2-NET_MAXON_NODE_BASE_GROUP_INPUTS-IN, // Value

[NodeAsset] net.maxon.node.log, // Log
NET_MAXON_NODE_LOG-NET_MAXON_NODE_LOG-NET_MAXON_NODE_BASE_GROUP_INPUTS-DATATYPE, // Data Type
NET_MAXON_NODE_LOG-NET_MAXON_NODE_LOG-NET_MAXON_NODE_BASE_GROUP_INPUTS-IN, // Value

[NodeAsset] net.maxon.node.log2, // Log2
NET_MAXON_NODE_LOG2-NET_MAXON_NODE_LOG2-NET_MAXON_NODE_BASE_GROUP_INPUTS-DATATYPE, // Data Type
NET_MAXON_NODE_LOG2-NET_MAXON_NODE_LOG2-NET_MAXON_NODE_BASE_GROUP_INPUTS-IN, // Value

[NodeAsset] net.maxon.node.round, // Round
NET_MAXON_NODE_ROUND-NET_MAXON_NODE_ROUND-NET_MAXON_NODE_BASE_GROUP_INPUTS-OPERATION, // Mode


// Volumes

12681, // Volume Vector - Length
12682, // Volume Vector - Direction
12287, // Configure...
17138, // Configure All...
DBASEDRAW-DBASEDRAW-BASEDRAW_GROUP_ACTIVEOBJECT-BASEDRAW_DATA_VDISPLAYACTIVE, // Volume Vector
DBASEDRAW-DBASEDRAW-BASEDRAW_GROUP_INACTIVEOBJECT-BASEDRAW_DATA_VDISPLAYINACTIVE, // Volume Vector
5613, // DisplayTag
TDISPLAY-TDISPLAY-ID_TAGPROPERTIES-DISPLAYTAG_VDISPLAYMODE, // Volume Vector
1041451, // Field Force
OFIELDFORCE-OFIELDFORCE-ID_OBJECTPROPERTIES-ID_FIELDFORCE_MODE, // Velocity Type
OFIELDFORCE-OFIELDFORCE-ID_OBJECTPROPERTIES-ID_FIELDFORCE_STRENGTH, // Strength
OFIELDFORCE-OFIELDFORCE-ID_OBJECTPROPERTIES-ID_FIELDFORCE_CONSIDER_MASS, // Consider Mass
OFIELDFORCE-OFIELDFORCE-ID_OBJECTPROPERTIES-ID_FIELDFORCE_FIELDLIST, // Field
OFIELDFORCE-OFIELDFORCE-ID_FIELDFORCE_DISPLAY_TAB-ID_FIELDFORCE_DISPLAY, // Display Box
OFIELDFORCE-OFIELDFORCE-ID_FIELDFORCE_DISPLAY_TAB-ID_FIELDFORCE_BOX_SIZE, // Box Size
OFIELDFORCE-OFIELDFORCE-ID_FIELDFORCE_DISPLAY_TAB-ID_FIELDFORCE_DENSITY, // Line Density
OFIELDFORCE-OFIELDFORCE-ID_FIELDFORCE_DISPLAY_TAB-ID_FIELDFORCE_DISPLAY_LENGTH, // Display Speed
OFIELDFORCE-OFIELDFORCE-ID_FIELDFORCE_DISPLAY_TAB-ID_FIELDFORCE_VECTOR_MODE, // Speed Mode
OFIELDFORCE-OFIELDFORCE-ID_FIELDFORCE_DISPLAY_TAB-ID_FIELDFORCE_SCALE_LENGTH_DISPLAY, // Scale Displayed Speed

OVOLUMEBUILDER-OVOLUMEBUILDER-ID_OBJECTPROPERTIES-ID_VOLUMEBUILDER_VOLUMETYPE, // Volume Type
TVOLUMEBUILDER-TVOLUMEBUILDER-ID_VOLUMEBUILDER_TAG_BB-ID_VOLUMEBUILDER_TAG_BBPOSITION, // P
TVOLUMEBUILDER-TVOLUMEBUILDER-ID_VOLUMEBUILDER_TAG_BB-ID_VOLUMEBUILDER_TAG_BBROTATION, // R
TVOLUMEBUILDER-TVOLUMEBUILDER-ID_VOLUMEBUILDER_TAG_CREATE_CONTROLLER, // Create Controller
1050456, // VolumeCacheLayer
OVOLUMECACHELAYER-OVOLUMECACHELAYER--ID_VOLUMECACHELAYER_ANIMATION, // Animation
OVOLUMECACHELAYER-OVOLUMECACHELAYER--ID_VOLUMECACHELAYER_FROM, // From
OVOLUMECACHELAYER-OVOLUMECACHELAYER--ID_VOLUMECACHELAYER_TO, // To
OVOLUMECACHELAYER-OVOLUMECACHELAYER-ID_VOLUMECACHELAYER_BUTTON_CACHE,
OVOLUMECACHELAYER-OVOLUMECACHELAYER-ID_VOLUMECACHELAYER_BUTTON_REFRESH,
OVOLUMECACHELAYER-OVOLUMECACHELAYER-ID_VOLUMECACHELAYER_BUTTON_CLEAR,
OVOLUMEFILTER-OVOLUMEFILTER-ID_VOLUMEFILTER_FILTERTAB-ID_VOLUMEFILTER_VECTOR_FILTER_TYPE, // Filter Type
OVOLUMEFILTER-OVOLUMEFILTER-ID_VOLUMEFILTER_FILTERTAB-ID_VOLUMEFILTER_RESHAPE_ROTATE_AXIS_MODE, // Rotation Axis
OVOLUMEFILTER-OVOLUMEFILTER-ID_VOLUMEFILTER_FILTERTAB-ID_VOLUMEFILTER_RESHAPE_ROTATE_ANGLE, // Angle
OVOLUMEFILTER-OVOLUMEFILTER-ID_VOLUMEFILTER_FILTERTAB-ID_VOLUMEFILTER_RESHAPE_SCALE, // Scale
OVOLUMEFILTER-OVOLUMEFILTER-ID_VOLUMEFILTER_FILTERTAB-ID_VOLUMEFILTER_FOG_RESHAPE_MULTIPLY, // Multiply
TVOLUMEBUILDER-TVOLUMEBUILDER-ID_VOLUMEBUILDER_TAG_MAINTAB-ID_VOLUMEBUILDER_TAG_SPLINERADIUS_SCALESPLINE, // Scale Along
TVOLUMEBUILDER-TVOLUMEBUILDER-ID_VOLUMEBUILDER_TAG_MAINTAB-ID_VOLUMEBUILDER_TAG_SPLINERADIUS_PERSEGMENT, // Scale per Segment
OVOLUMETOMESH-OVOLUMETOMESH-ID_OBJECTPROPERTIES-ID_VOLUMETOMESH_CREATE_CURVATURE_MAP, // Create Curvature Map
OVOLUMETOMESH-OVOLUMETOMESH-ID_OBJECTPROPERTIES-ID_VOLUMETOMESH_CURVATURE_DIRECTION, // Curvature Direction
1050000, //PForceObject
OP_FORCEOBJECT-OP_FORCEOBJECT-ID_GVPORTS-FORCEOBJECT_OBJECT, // Object
1040113, // VOLUMEFILTER_SDF_SMOOTH_CMD_ID 
1040114, // VOLUMEFILTER_SDF_DILATE_ERODE_CMD_ID
465002103, // VOLUMEFILTER_SDF_CLOSE_OPEN_CMD_ID
1040737, // VOLUMEFILTER_FOG_SMOOTH_CMD_ID
465002105, // VOLUMEFILTER_FOG_MULTIPLY_CMD_ID
465002107, // VOLUMEFILTER_FOG_INVERT_CMD_ID
1040738, // VOLUMEFILTER_FOG_ADD_CMD_ID
465002109, // VOLUMEFILTER_FOG_RANGEMAP_CMD_ID
465002111, // VOLUMEFILTER_FOG_CURVE_CMD_ID
465002113, // VOLUMEFILTER_VECTOR_SMOOTH_CMD_ID
465002115, // VOLUMEFILTER_VECTOR_SCALE_CMD_ID
465002117, // VOLUMEFILTER_VECTOR_ROTATE_CMD_ID
465002119, // VOLUMEFILTER_VECTOR_INVERT_CMD_ID
465002121, // VOLUMEFILTER_VECTOR_NORMALIZE_CMD_ID
465002123, // VOLUMEFILTER_VECTOR_CURL_CMD_ID
1050995, // Volume Tag
1039859, // Volume Builder
1039861, // Volume Mesher
1050981, // ResetCachesCommand
TVOLUME-TVOLUME-ID_TAGPROPERTIES-ID_VOLUME_MATERIAL, // Material
TVOLUME-TVOLUME-ID_TAGPROPERTIES-ID_VOLUME_DENSITY_SELECTION, // Density
TVOLUME-TVOLUME-ID_TAGPROPERTIES-ID_VOLUME_DENSITY_RANGEMAP_MIN, // Input Min
TVOLUME-TVOLUME-ID_TAGPROPERTIES-ID_VOLUME_DENSITY_RANGEMAP_MAX, // Input Max
TVOLUME-TVOLUME-ID_TAGPROPERTIES-ID_VOLUME_DENSITY_RANGEMAP_DETECT, // Detect Value Range
TVOLUME-TVOLUME-ID_TAGPROPERTIES-ID_VOLUME_ALBEDO_SELECTION, // Color
TVOLUME-TVOLUME-ID_TAGPROPERTIES-ID_VOLUME_ALBEDO_RANGEMAP_MIN, // Input Min
TVOLUME-TVOLUME-ID_TAGPROPERTIES-ID_VOLUME_ALBEDO_RANGEMAP_MAX, // Input Max
TVOLUME-TVOLUME-ID_TAGPROPERTIES-ID_VOLUME_ALBEDO_RANGEMAP_DETECT, // Detect Value Range
TVOLUME-TVOLUME-ID_TAGPROPERTIES-ID_VOLUME_EMISSION_SELECTION, // Emission
TVOLUME-TVOLUME-ID_TAGPROPERTIES-ID_VOLUME_EMISSION_RANGEMAP_MIN, // Input Min
TVOLUME-TVOLUME-ID_TAGPROPERTIES-ID_VOLUME_EMISSION_RANGEMAP_MAX, // Input Max
TVOLUME-TVOLUME-ID_TAGPROPERTIES-ID_VOLUME_EMISSION_RANGEMAP_DETECT, // Detect Value Range

// ProRender
12161, // Edit Render Settings...
DRENDERSETTINGS-DRENDERSETTINGS-Obaselist-RDATA_RENDERENGINE, // Renderer
1037639, // VPGPURenderer
VPGPURENDERER-VPGPURENDERER-VP_GPURENDERER_MULTIPASS_GROUP-VP_GPURENDERER_MULTIPASS_DIRECT_DIFFUSE, // Direct Diffuse
VPGPURENDERER-VPGPURENDERER-VP_GPURENDERER_MULTIPASS_GROUP-VP_GPURENDERER_MULTIPASS_DIRECT_REFLECT, // Direct Reflect
VPGPURENDERER-VPGPURENDERER-VP_GPURENDERER_MULTIPASS_GROUP-VP_GPURENDERER_MULTIPASS_EMISSION, // Emission
VPGPURENDERER-VPGPURENDERER-VP_GPURENDERER_MULTIPASS_GROUP-VP_GPURENDERER_MULTIPASS_INDIRECT_DIFFUSE, // Indirect Diffuse
VPGPURENDERER-VPGPURENDERER-VP_GPURENDERER_MULTIPASS_GROUP-VP_GPURENDERER_MULTIPASS_INDIRECT_REFLECT, // Indirect Reflect
VPGPURENDERER-VPGPURENDERER-VP_GPURENDERER_MULTIPASS_GROUP-VP_GPURENDERER_MULTIPASS_REFRACT, // Refract
VPGPURENDERER-VPGPURENDERER-VP_GPURENDERER_MULTIPASS_GROUP-VP_GPURENDERER_MULTIPASS_VOLUME, // Volume
VPGPURENDERER-VPGPURENDERER-VP_GPURENDERER_MULTIPASS_GROUP-VP_GPURENDERER_MULTIPASS_AO, // Ambient Occlusion
VPGPURENDERER-VPGPURENDERER-VP_GPURENDERER_MULTIPASS_GROUP-VP_GPURENDERER_MULTIPASS_ALBEDO, // Albedo
VPGPURENDERER-VPGPURENDERER-VP_GPURENDERER_PAGE_OFFLINE-VP_GPURENDERER_RENDERMODE_OFFLINE, // Render Mode
VPGPURENDERER-VPGPURENDERER-VP_GPURENDERER_PAGE_PREVIEW-VP_GPURENDERER_RENDERMODE_PREVIEW, // Render Mode
VPGPURENDERER-VPGPURENDERER-VP_GPURENDERER_PAGE_OFFLINE-VP_GPURENDERER_MOTION_BLUR_TYPE_OFFLINE, // Motion Blur
1000474, // Preferences
465001630, // Preferences/Renderer
1038496,  // Preferences / Renderer / GPU REnderer
PREFSGPURENDERER-PREFSGPURENDERER-PREFS_GPURENDERER_BUTTON_GROUP-PREFS_GPURENDERER_COMPILE_SHADERS, 
PREFSGPURENDERER-PREFSGPURENDERER-PREFS_GPURENDERER_BUTTON_GROUP-PREFS_GPURENDERER_CLEAR_SHADER_CACHE,


// ProRender Nodes
[NodeAsset] net.maxon.gpurenderer.node.ambientocclusion,
[NodeAsset] net.maxon.gpurenderer.node.anyall,
[NodeAsset] net.maxon.gpurenderer.node.angle,
[NodeAsset] net.maxon.gpurenderer.node.checkerboard,
[NodeAsset] net.maxon.gpurenderer.node.average,
[NodeAsset] net.maxon.gpurenderer.node.blend,
[NodeAsset] net.maxon.gpurenderer.node.projection,
[NodeAsset] net.maxon.gpurenderer.node.cache2d,
[NodeAsset] net.maxon.gpurenderer.node.displacement,
[NodeAsset] net.maxon.gpurenderer.node.fresnelconductor,
[NodeAsset] net.maxon.gpurenderer.node.splitvector3d,
[NodeAsset] net.maxon.gpurenderer.node.fresneldielectric,
[NodeAsset] net.maxon.gpurenderer.node.getcontext,
[NodeAsset] net.maxon.gpurenderer.node.image,
[NodeAsset] net.maxon.gpurenderer.node.gradient,
[NodeAsset] net.maxon.gpurenderer.node.material.add,
[NodeAsset] net.maxon.gpurenderer.node.material.mix,
[NodeAsset] net.maxon.gpurenderer.node.materialend,
[NodeAsset] net.maxon.gpurenderer.node.minmax,
[NodeAsset] net.maxon.gpurenderer.node.mograph,
[NodeAsset] net.maxon.gpurenderer.node.noise,
[NodeAsset] net.maxon.gpurenderer.node.splitcolor,
[NodeAsset] net.maxon.gpurenderer.node.splitvector2d,
[NodeAsset] net.maxon.gpurenderer.node.uber,
[NodeAsset] net.maxon.gpurenderer.node.volume.heterogenous,
[NodeAsset] net.maxon.gpurenderer.node.uvdistort,
[NodeAsset] net.maxon.gpurenderer.node.uvreprojection,
[NodeAsset] net.maxon.gpurenderer.node.uvtransform,
[NodeAsset] net.maxon.gpurenderer.node.volume.absorption,
[NodeAsset] net.maxon.gpurenderer.node.volume.homogenous,
[NodeAsset] net.maxon.gpurenderer.node.volume.scattering,
[NodeAsset] 3627604be83e4982b3f13f3f0cafeaf1, // VDB Volume Asset

// Denoiser
1050980, // Denoiser VP Plugin
VPDENOISER-VPDENOISER-VP_DENOISER_TYPE_GROUP-VP_DENOISER_TYPE, // Type
VPDENOISER-VPDENOISER-VP_DENOISER_TYPE_GROUP-VP_DENOISER_USE_PASSES, // Use Multi-Passes
VPDENOISER-VPDENOISER--VP_DENOISER_ADDRAWLAYER, // Save the Raw Image on a separate layer
VPDENOISER-VPDENOISER--VP_DENOISER_COLORSIGMA, // Strength
VPDENOISER-VPDENOISER--VP_DENOISER_NORMALSSIGMA, // Highlights and Shadows
VPDENOISER-VPDENOISER--VP_DENOISER_DEPTHSIGMA, // Affect Depth
VPDENOISER-VPDENOISER--VP_DENOISER_TRANSSIGMA, // Affect Texture Detail

// CAD exchange
1039778, // catia
FCATIAIMPORT-FCADIMPORT-CADIMPORT_GRP_GENERAL-CADIMPORT_INSTANCES, // Instances
1039779, // iges
FIGESIMPORT-FCADIMPORT-CADIMPORT_GRP_GENERAL-CADIMPORT_INSTANCES, // Instances
1039780, // jt
FJTIMPORT-FCADIMPORT-CADIMPORT_GRP_GENERAL-CADIMPORT_INSTANCES, // Instances
1039781, // solidworks
FSOLIDWORKSIMPORT-FCADIMPORT-CADIMPORT_GRP_GENERAL-CADIMPORT_INSTANCES, // Instances
1039777, // step
FSTEPIMPORT-FCADIMPORT-CADIMPORT_GRP_GENERAL-CADIMPORT_INSTANCES, // Instances
