// UV
17038, // UV Mode
1053301, // UV Unwrap
1053373, // UV Weld
1053312, // UV Weld and Relax
1053110, // Pack UV (Geometric)
1053659, // Pack UV (Rasterized)
1053624, // Create Automatic UV
170769, // UV Pins
170760, // UV Overlapping Polygons
170775, // UV No Boundaries
170766, // UV Seams
170767, // UV Connectivity
170774, // Lines
170768, // Filled Polygons
170762, // Distortion
170763, // Multi-Color Islands
170765, // Configure All
170764, // Configure
1054138, // UV editor colors prefs
1054357, // Add to Pin Selection
1054358, // Remove from Pin Selection
465002126, // Clear Pin Selection
1011168, // UV Manager
-UV_SETTINGS-UV_SETTINGS_GROUP_OVERLAYS-UV_SETTINGS_DISPLAY_PINS, // Pins
-UV_SETTINGS-UV_SETTINGS_GROUP_OVERLAYS-UV_SETTINGS_DISPLAY_BOUNDARIES, // Boundaries
-UV_SETTINGS-UV_SETTINGS_GROUP_DISPLAY-UV_SETTINGS_DISPLAY_UVDISPLAY, // UV Display
-UV_SETTINGS-UV_SETTINGS_GROUP_OVERLAYS-UV_SETTINGS_DISPLAY_UVMESH, // UV Mesh
-UV_SETTINGS-UV_SETTINGS_GROUP_OVERLAYS-UV_SETTINGS_DISPLAY_SHADING, // Shading
-UV_SETTINGS-UV_SETTINGS_GROUP_OVERLAYS-UV_SETTINGS_DISPLAY_OPACITY, // Opacity
-UV_SETTINGS-UV_SETTINGS_GROUP_FILTER-UV_SETTINGS_FILTER_UV_HUD, // HUD
-UV_SETTINGS-UV_SETTINGS_GROUP_FILTER-UV_SETTINGS_FILTER_UV_RULERS, // Canvas Axis
-UV_SETTINGS-UV_SETTINGS_GROUP_FILTER-UV_SETTINGS_FILTER_UV_AXIS, // Editor Axis
-UV_SETTINGS-UV_SETTINGS_GROUP_FILTER-UV_SETTINGS_FILTER_UV_UNITS, // UV Units
-UV_SETTINGS-UV_SETTINGS_GROUP_FILTER-UV_SETTINGS_FILTER_UV_COMPONENTS, // UV Component Highlighting
-UV_SETTINGS-UV_SETTINGS_GROUP_BACK-UV_SETTINGS_BACK_TEXTURE, // Texture
-UV_SETTINGS-UV_SETTINGS_GROUP_BACK-UV_SETTINGS_BACK_OPACITY, // Opacity
170009, // Show UV Mesh
170773, // Show UV Display




// Modeling
450000008, // Bridge
TOOLBRIDGE-TOOLBRIDGE-MDATA_MAINGROUP-MDATA_BRIDGE_SUBDIVISION, // Subdivision
TOOLBRIDGE-TOOLBRIDGE-MDATA_MAINGROUP-MDATA_BRIDGE_SPIN_STEPS, // Spin Steps

1016202, // Brush
TOOLBRUSH-TOOLBRUSH-MDATA_MAINGROUP-MDATA_BRUSH_VISIBLEONLY, // Visible Only
TOOLBRUSH-TOOLBRUSH-MDATA_BRUSH_RESTRICTION_GROUP-MDATA_BRUSH_RESTRICTION_SPACE, // Space
TOOLBRUSH-TOOLBRUSH-MDATA_BRUSH_RESTRICTION_GROUP-MDATA_BRUSH_RESTRICTION_X, // X
TOOLBRUSH-TOOLBRUSH-MDATA_BRUSH_RESTRICTION_GROUP-MDATA_BRUSH_RESTRICTION_Y, // Y
TOOLBRUSH-TOOLBRUSH-MDATA_BRUSH_RESTRICTION_GROUP-MDATA_BRUSH_RESTRICTION_Z, // Z

450000007, // Create Point
TOOLADDPOINT-TOOLADDPOINT-MDATA_MAINGROUP-MDATA_ADDPOINT_POLYTYPE, // Polygon Type

450000010, // Close Polygon hole
TOOLCLOSEHOLE-TOOLCLOSEHOLE-MDATA_MAINGROUP-MDATA_CLOSEHOLE_POLYTYPE, // Polygon Type
TOOLCLOSEHOLE-TOOLCLOSEHOLE-MDATA_MAINGROUP-MDATA_CLOSEHOLE_SELECTNEWPOLY, // Select New Polygons
TOOLCLOSEHOLE-TOOLCLOSEHOLE-MDATA_MAINGROUP-MDATA_CLOSEHOLE_SELECTOUTLINE, // Select Outline
TOOLCLOSEHOLE-TOOLCLOSEHOLE-MDATA_MAINGROUP-MDATA_CLOSEHOLE_BREAKOUTLINE, // Phong Break Outline

1009661, // Edge Cut
TOOLEDGECUT-TOOLEDGECUT-MDATA_MAINGROUP-MDATA_EDGECUT_NGONMODE, // N-gons

1016185, // Magnet
TOOLMAGNET-TOOLMAGNET-MDATA_MAINGROUP-MDATA_MAGNET_EFFECTMODE, // Mode
TOOLMAGNET-TOOLMAGNET-MDATA_MAINGROUP-MDATA_MAGNET_MOVEONLYVISIBLE, // Visible Only

450000014, // Iron
TOOLIRON-TOOLIRON-MDATA_MAINGROUP-MDATA_IRON_PRESERVEBOUNDARY, // Preserve Boundaries

222, // Untriangulate
TOOLUNTRIANGULATE-TOOLUNTRIANGULATE-MDATA_MAINGROUP-MDATA_UNTRIANGULATE_USE_ANGLE_DERIVATION, // Internal Angle
TOOLUNTRIANGULATE-TOOLUNTRIANGULATE-MDATA_MAINGROUP-MDATA_UNTRIANGULATE_ANGLE_DERIVATION, // Angle
TOOLUNTRIANGULATE-TOOLUNTRIANGULATE-MDATA_MAINGROUP-MDATA_UNTRIANGULATE_USE_ALIGNMENT_DERIVATION, // Alignment Angle
TOOLUNTRIANGULATE-TOOLUNTRIANGULATE-MDATA_MAINGROUP-MDATA_UNTRIANGULATE_ALIGNMENT_DERIVATION, // Angle
TOOLUNTRIANGULATE-TOOLUNTRIANGULATE-MDATA_MAINGROUP-MDATA_UNTRIANGULATE_RESPECTUVBOUNDARY, // Keep UV Boundary
TOOLUNTRIANGULATE-TOOLUNTRIANGULATE-MDATA_MAINGROUP-MDATA_UNTRIANGULATE_RESPECTSHADINGBREAKS, // Keep Phong Edge Breaks
TOOLUNTRIANGULATE-TOOLUNTRIANGULATE-MDATA_MAINGROUP-MDATA_UNTRIANGULATE_RESPECTPOLYATTRIBUTES, // Keep Mesh Attributes

14047, // Subdivide

450000003, // Smooth Shift
TOOLSMOOTHSHIFT-TOOLSMOOTHSHIFT-MDATA_MAINGROUP-MDATA_SMOOTHSHIFT_PRESERVEGROUPS, // Preserve Groups

1053469, // Mirror Selection

1011192, // Loop Selection
TOOLLOOPSELECTION-TOOLLOOPSELECTION-MDATA_MAINGROUP-MDATA_LOOP_SEL_STOP_AT_SELECTIONS, // Stop at Selections
TOOLLOOPSELECTION-TOOLLOOPSELECTION-MDATA_MAINGROUP-MDATA_LOOP_SEL_STOP_AT_NON_QUADS, // Stop at Non-Quads
TOOLLOOPSELECTION-TOOLLOOPSELECTION-MDATA_MAINGROUP-MDATA_LOOP_SEL_STOP_AT_POLES, // Stop at Poles

1011180, // Ring Selection
TOOLRINGSELECTION-TOOLRINGSELECTION-MDATA_MAINGROUP-MDATA_RING_SEL_STOP_AT_SELECTIONS, // Stop at Selections
TOOLRINGSELECTION-TOOLRINGSELECTION-MDATA_MAINGROUP-MDATA_RING_SEL_STOP_AT_NON_QUADS, // Stop at Non-Quads
TOOLRINGSELECTION-TOOLRINGSELECTION-MDATA_MAINGROUP-MDATA_RING_SEL_STOP_AT_POLES, // Stop at Poles

431000202, // Remove Non-Manifold

5116, // Extrude Object
OEXTRUDE-OEXTRUDE-ID_OBJECTPROPERTIES-EXTRUDEOBJECT_EXTRUSIONOFFSET, // Offset
OEXTRUDE-OEXTRUDE-ID_OBJECTPROPERTIES-EXTRUDEOBJECT_DIRECTION, // Direction
OEXTRUDE-OEXTRUDE-ID_OBJECTPROPERTIES-EXTRUDEOBJECT_MOVE, // Movement

1051315, // Normal
5612, // Phong Tag
TPHONG-TPHONG-ID_TAGPROPERTIES-PHONGTAG_CREATE_NORMAL_TAG, // Create Normal Tag Button






// Exchange
1000474, // Preferences...
1041129, // Preferences/ ImportExport / glTF Export
FGLTFEXPORTER-FGLTFEXPORTER-GLTFEXPORTER_GROUP-GLTFEXPORTER_NORMALS, // Export Normals
FGLTFEXPORTER-FGLTFEXPORTER-GLTFEXPORTER_GROUP-GLTFEXPORTER_UVS, // Export UV Coordinates
FGLTFEXPORTER-FGLTFEXPORTER-GLTFEXPORTER_GROUP-GLTFEXPORTER_UNITSCALE, // Scale
FGLTFEXPORTER-FGLTFEXPORTER-GLTFEXPORTER_GROUP-GLTFEXPORTER_TEXTURES, // Export Textures
FGLTFEXPORTER-FGLTFEXPORTER-GLTFEXPORTER_GROUP-GLTFEXPORTER_DOUBLESIDED, // Double Sided
FGLTFEXPORTER-FGLTFEXPORTER-GLTFEXPORTER_GROUP-GLTFEXPORTER_PSRANIMATIONS, // Export PSR Animations
FGLTFEXPORTER-FGLTFEXPORTER-GLTFEXPORTER_GROUP-GLTFEXPORTER_MORPHANIMATIONS, // Export Morph Animations
FGLTFEXPORTER-FGLTFEXPORTER-GLTFEXPORTER_GROUP-GLTFEXPORTER_SKINANIMATIONS, // Export Skin Animations
FGLTFEXPORTER-FGLTFEXPORTER-GLTFEXPORTER_GROUP-GLTFEXPORTER_BAKEANIMATIONS, // Bake Animations
FGLTFEXPORTER-FGLTFEXPORTER-GLTFEXPORTER_GROUP-GLTFEXPORTER_CURRENTFRAME, // Current Frame
FGLTFEXPORTER-FGLTFEXPORTER-GLTFEXPORTER_GROUP-GLTFEXPORTER_CUSTOMFRAME, // Custom Frame
FGLTFEXPORTER-FGLTFEXPORTER-GLTFEXPORTER_GROUP-GLTFEXPORTER_CAMERAS, // Export Cameras
FGLTFEXPORTER-FGLTFEXPORTER-GLTFEXPORTER_GROUP-GLTFEXPORTER_FLIPZ, // Flip Z
FGLTFEXPORTER-FGLTFEXPORTER-GLTFEXPORTER_GROUP-GLTFEXPORTER_FILEFORMAT, // File Format



1028081,  // Preferences / Import/Export / Alembic Import
465001638, // Preferences / Import/Export
FALEMBICIMPORT-FALEMBICIMPORT-ABCIMPORT_GROUP-ABCIMPORT_INSTANCES, // Instances
GL
OALEMBICGENERATOR-OALEMBICGENERATOR-ID_OBJECTPROPERTIES-ALEMBIC_INSTANCE, // Instance

1054226, // Preferences/ Go Zbrush
PREFSGOZ-PREFSGOZ-PREFS_GOZ_GROUP-GOZ_SCALE_FACTOR_IMPORT, // Scale vector for import
PREFSGOZ-PREFSGOZ-PREFS_GOZ_GROUP-GOZ_IMPORT_COLOR_MAP, // Import Color Map
PREFSGOZ-PREFSGOZ-PREFS_GOZ_GROUP-GOZ_IMPORT_NORMAL_MAP, // Import Normal Map
PREFSGOZ-PREFSGOZ-PREFS_GOZ_GROUP-GOZ_IMPORT_DISPLACEMENT_MAP, // Import Displacement map
PREFSGOZ-PREFSGOZ-PREFS_GOZ_GROUP-GOZ_IMPORT_UVW, // Import Uvw
PREFSGOZ-PREFSGOZ-PREFS_GOZ_GROUP-GOZ_IMPORT_POLYPAINT, // Import Polypaint
PREFSGOZ-PREFSGOZ-PREFS_GOZ_GROUP-GOZ_IMPORT_POLYGROUP, // Import Polygroup
PREFSGOZ-PREFSGOZ-PREFS_GOZ_GROUP-GOZ_SCALE_FACTOR_EXPORT, // Export Scale Vector
PREFSGOZ-PREFSGOZ-PREFS_GOZ_GROUP-GOZ_EXPORT_UVW, // Export Uvw
PREFSGOZ-PREFSGOZ-PREFS_GOZ_GROUP-GOZ_EXPORT_POLYPAINT, // Export Polypaint
PREFSGOZ-PREFSGOZ-PREFS_GOZ_GROUP-GOZ_EXPORT_POLYGROUP, // Export Polygroup
1053946, // Go Zbrush Import Command
1054167, // Go Zbrush Export Command
1054230, // Go Zbrush Install Command
1054392, // Go Zbrush Assign Polygroup Command
1054295, // Go Zbrush Polygroup tag
TGOZPOLYGROUP-TGOZPOLYGROUP-ID_GOZ_POLYGROUP-ID_ADDPOLYGROUP, // Add selected polygon to polygroup

12373, //Project Settings
DDOC-DDOC-DOCUMENT_GROUP_CINEWARE-DOCUMENT_CINEWARE_POLYGON_CACHE, // Save Polygon Cache
DDOC-DDOC-DOCUMENT_GROUP_CINEWARE-DOCUMENT_CINEWARE_ANIMATION_CACHE, // Save Animation Cache
DDOC-DDOC-DOCUMENT_GROUP_CINEWARE-DOCUMENT_CINEWARE_MATERIAL_CACHE, // Save Material Cache
DDOC-DDOC-DOCUMENT_GROUP_CINEWARE-DOCUMENT_CINEWARE_MATERIAL_WIDTH, // Width
DDOC-DDOC-DOCUMENT_GROUP_CINEWARE-DOCUMENT_CINEWARE_MATERIAL_HEIGHT, // Height
DDOC-DDOC-DOCUMENT_GROUP_CINEWARE-DOCUMENT_CINEWARE_MATERIAL_FORMAT, // Format
DDOC-DDOC-DOCUMENT_GROUP_CINEWARE-DOCUMENT_CINEWARE_MATERIAL_DEPTH, // Depth

1026370,  // Preferences / Import/Export / FBX Export
FFBXEXPORT-FFBXEXPORT-FBXEXPORT_GROUP-FBXEXPORT_MATERIALS, // Material
FFBXEXPORT-FFBXEXPORT--FBXEXPORT_GROUP, // 
FFBXEXPORT-FFBXEXPORT-FBXEXPORT_GROUP-FBXEXPORT_BAKE_MATERIALS, // Bake Materials
FFBXEXPORT-FFBXEXPORT--FBXEXPORT_GROUP, // 
FFBXEXPORT-FFBXEXPORT-FBXEXPORT_GROUP-FBXEXPORT_BAKEDTEXTURE_WIDTH, // Width
FFBXEXPORT-FFBXEXPORT--FBXEXPORT_GROUP, // 
FFBXEXPORT-FFBXEXPORT-FBXEXPORT_GROUP-FBXEXPORT_BAKEDTEXTURE_HEIGHT, // Height
FFBXEXPORT-FFBXEXPORT--FBXEXPORT_GROUP, // 
FFBXEXPORT-FFBXEXPORT-FBXEXPORT_GROUP-FBXEXPORT_BAKEDTEXTURE_FORMAT, // Format
FFBXEXPORT-FFBXEXPORT--FBXEXPORT_GROUP, // 
FFBXEXPORT-FFBXEXPORT-FBXEXPORT_GROUP-FBXEXPORT_BAKEDTEXTURE_DEPTH, // Depth

1026369,  // Preferences / Import/Export / FBX Import
FFBXIMPORT-FFBXIMPORT-FBXIMPORT_GROUP-FBXIMPORT_MATERIALMODE, // Material
FFBXIMPORT-FFBXIMPORT-FBXIMPORT_GROUP-FBXIMPORT_NODESPACE, // Node Space


465001623, // PREFS_MOUSE
PREFSMOUSE-PREFSMOUSE-PREF_MOUSE_MAIN_GROUP-PREF_MOUSE_TOUCHSUPPORT, // Touch Support


465001625, // Preferences / View
PREFSVIEW-PREFSVIEW-PREFS_VIEW_GROUP-PREF_VIEW_SPLINE_WIDTH, // Spline Size
PREFSVIEW-PREFSVIEW-PREFS_VIEW_GROUP-PREF_VIEW_EDGE_UNSELECTED_SIZE, // Edge Size
// View Settings
18159, // Configure Similar
DBASEDRAW-DBASEDRAW-BASEDRAW_GROUP_FILTER-BASEDRAW_DATA_ONLY_GEOMETRY, // Geometry Only
DBASEDRAW-DBASEDRAW-BASEDRAW_GROUP_FILTER-BASEDRAW_DISPLAYFILTER_HAIR, // Hair
DBASEDRAW-DBASEDRAW-BASEDRAW_GROUP_FILTER-BASEDRAW_DISPLAYFILTER_FIELD, // Field
DBASEDRAW-DBASEDRAW-BASEDRAW_GROUP_EFFECTS-BASEDRAW_DATA_SHADOW_SOFTSHADOW_ATTENUATION, // Soft Shadow Attenuation
DBASEDRAW-DBASEDRAW-BASEDRAW_GROUP_EFFECTS-BASEDRAW_DATA_SHADOW_TYPE, // Shadow Type
DBASEDRAW-DBASEDRAW-BASEDRAW_GROUP_EFFECTS-BASEDRAW_DATA_SHADOW_PCF, // Alternative Shadow Filtering
DBASEDRAW-DBASEDRAW-BASEDRAW_GROUP_EFFECTS-BASEDRAW_DATA_SHADOW_MAP_SIZE, // Shadowmap Size
DBASEDRAW-DBASEDRAW-BASEDRAW_GROUP_EFFECTS-BASEDRAW_DATA_COMPLETE_MATERIAL_TRANSPARENCY, // Complete Material Transparency
DBASEDRAW-DBASEDRAW-BASEDRAW_GROUP_EFFECTS-BASEDRAW_DATA_SUPERSAMPLING, // Supersampling
DBASEDRAW-DBASEDRAW-BASEDRAW_GROUP_EFFECTS-BASEDRAW_DATA_VIEWPORT_CONTENT_SCALE, // Resolution

DBASEDRAW-DBASEDRAW-BASEDRAW_GROUP_FILTER-BASEDRAW_COMMAND_DISPLAYFILTER_PRESET_LOAD, // Load Preset...
DBASEDRAW-DBASEDRAW-BASEDRAW_GROUP_FILTER-BASEDRAW_COMMAND_DISPLAYFILTER_PRESET_SAVE, // Save Preset...

//Viewport Attributes - Effects tab
DBASEDRAW-DBASEDRAW-BASEDRAW_GROUP_EFFECTS-BASEDRAW_DATA_SSAO_MODE, // SSAO Mode
DBASEDRAW-DBASEDRAW-BASEDRAW_GROUP_EFFECTS-BASEDRAW_DATA_DEPTHOFFIELD_ANTIALIASED, // Depth Of Field-Anti-Aliased DOF

//Viewport Attributes - Filter Tab
DBASEDRAW-DBASEDRAW-BASEDRAW_GROUP_FILTER-BASEDRAW_DISPLAYFILTER_FIELD, // Field

12161, // Edit Render Settings...
DRENDERSETTINGS-DRENDERSETTINGS-Obaselist-RDATA_RENDERENGINE, // Renderer
300001061, // Hardware OpenGL
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-ID_VIDEOPOSTPROPERTIES-VP_PREVIEWHARDWARE_SHADOW_MAP_SIZE, // Shadowmap Size
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-ID_VIDEOPOSTPROPERTIES-VP_PREVIEWHARDWARE_ALTERNATIVESHADOWMAPPING, // Alternative Shadow Filtering
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-ID_VIDEOPOSTPROPERTIES-VP_PREVIEWHARDWARE_IGNORE_HIDDEN_SELECTION, // Ignore Hidden Selections
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-ID_VIDEOPOSTPROPERTIES-VP_PREVIEWHARDWARE_32BIT_DEPTH, // 32-bit Framebuffer
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-ID_VIDEOPOSTPROPERTIES-VP_PREVIEWHARDWARE_COPY_VP_EFFECTS, // Copy Effects from Viewport

VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP-VP_PREVIEWHARDWARE_ONLY_GEOMETRY, // Geometry Only
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP-VP_PREVIEWHARDWARE_DISPLAYFILTER_NULL, // Null
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP-VP_PREVIEWHARDWARE_DISPLAYFILTER_FIELD, // Field
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP-VP_PREVIEWHARDWARE_DISPLAYFILTER_POLYGON, // Polygon
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP-VP_PREVIEWHARDWARE_DISPLAYFILTER_CAMERA, // Camera
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP-VP_PREVIEWHARDWARE_DISPLAYFILTER_SPLINE, // Spline
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP-VP_PREVIEWHARDWARE_DISPLAYFILTER_LIGHT, // Light
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP-VP_PREVIEWHARDWARE_DISPLAYFILTER_GENERATOR, // Generator
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP-VP_PREVIEWHARDWARE_DISPLAYFILTER_HYPERNURBS, // Subdivision Surface
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP-VP_PREVIEWHARDWARE_DISPLAYFILTER_JOINT, // Joint
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP-VP_PREVIEWHARDWARE_DISPLAYFILTER_PARTICLE, // Particle
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP-VP_PREVIEWHARDWARE_DISPLAYFILTER_DEFORMER, // Deformer
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP-VP_PREVIEWHARDWARE_DISPLAYFILTER_HAIR, // Hair
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP-VP_PREVIEWHARDWARE_DISPLAYFILTER_SCENE, // Environment
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP-VP_PREVIEWHARDWARE_DISPLAYFILTER_OTHER, // Other
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE--VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP, // 
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP-VP_PREVIEWHARDWARE_DISPLAYFILTER_GRID, // Workplane
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP-VP_PREVIEWHARDWARE_DISPLAYFILTER_BASEGRID, // Base Grid
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP-VP_PREVIEWHARDWARE_DISPLAYFILTER_OBJECTHANDLES, // Axis
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP-VP_PREVIEWHARDWARE_DISPLAYFILTER_MULTIAXIS, // Multi-Select Axes
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP-VP_PREVIEWHARDWARE_DISPLAYFILTER_WORLDAXIS, // World Axis
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP-VP_PREVIEWHARDWARE_DISPLAYFILTER_HANDLES, // Handles
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP-VP_PREVIEWHARDWARE_DISPLAYFILTER_SDS, // SDS Mesh
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP-VP_PREVIEWHARDWARE_DISPLAYFILTER_SDSCAGE, // SDS Cage
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP-VP_PREVIEWHARDWARE_DISPLAYFILTER_NGONLINES, // N-gon Lines
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP-VP_PREVIEWHARDWARE_DISPLAYFILTER_GUIDELINES, // Guides
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP-VP_PREVIEWHARDWARE_DATA_SHOWPATH, // Animation Path
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP-VP_PREVIEWHARDWARE_DISPLAYFILTER_ONION, // Ghosting
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP-VP_PREVIEWHARDWARE_DISPLAYFILTER_HUD, // HUD
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP-VP_PREVIEWHARDWARE_DISPLAYFILTER_HORIZON, // Horizon
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP-VP_PREVIEWHARDWARE_DISPLAYFILTER_PRESET_LOAD, // Load Preset...
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-VP_PREVIEWHARDWARE_DISPLAYFILTER_GROUP-VP_PREVIEWHARDWARE_DISPLAYFILTER_PRESET_SAVE, // Save Preset...
 
// Basic Tab
VPPREVIEWHARDWARE-VPPREVIEWHARDWARE-ID_VIDEOPOSTPROPERTIES-VP_PREVIEWHARDWARE_DEPTHOFFIELD_ANTIALIASED, // Anti-Aliased DOF

 
 
18162, // Display Filter Presets
18163, // Save Preset...
18160, // All
18195, // Default
18161, // None
18194, // Geometry Only
18164, // Null
18165, // Polygon
18166, // Spline
18167, // Generator
18168, // Subdivision Surface
18169, // Deformer
18170, // Camera
18171, // Light
18185, // Joint
18173, // Particle
18192, // Field
18191, // Hair
18172, // Environment
18174, // Other
18175, // Grid
18189, // Base Grid
// 18182, // Axis
18177, // World Axis
18181, // Multi-Select Axes
18190, // Handles
18188, // Object Highlighting
18180, // Component Highlighting
18179, // SDS Mesh
18183, // SDS Cage
18184, // N-gon Lines
18187, // Guides
18193, // Animation Path
18186, // Ghosting
18178, // HUD
18176, // Horizon






// misc
13680, // License Manager...
56000, // Switch Layout
