DIALOG DLG_TRIGGER
{
  NAME TITLE;

	GROUP
	{

		ROWS 1;
		BORDERSIZE 4,4,4,4;
		SCALE_H; SCALE_V;

		CHECKBOX  IDC_TRI_REDRAW { NAME TREDRAW; }
		STATICTEXT { NAME TTIME; };
		EDITNUMBERARROWS IDC_TRI_TIME { ALIGN_LEFT; SIZE 60,0; }
		STATICTEXT { NAME TUNIT; };

	}
}
