// C4D-DialogResource

DIALOG DLG_ACTOR_RECORD
{
  NAME TITLE;

	GROUP
	{
		COLUMNS 1;
		BORDERSIZE 4,4,4,4;
		SCALE_H; SCALE_V;

		GROUP
		{
			NAME THOW;
			BORDERSTYLE BORDER_GROUP_IN;

			COLUMNS 1;
			BORDERSIZE 4,4,4,4;
			SCALE_H; SCALE_V;

			GROUP
			{
				COLUMNS 2;

				BUTTON IDC_ACTOR_RECORD_SINGLE { NAME TSINGLE; } STATICTEXT {};

				BUTTON IDC_ACTOR_RECORD_START { NAME TSTART; }  BUTTON IDC_ACTOR_RECORD_STOP  { NAME TSTOP; }
			}
		}

		GROUP
		{
			NAME TWHEN;
			BORDERSTYLE BORDER_GROUP_IN;

			COLUMNS 1;
			BORDERSIZE 4,4,4,4;
			SCALE_H; SCALE_V;


			GROUP
			{
				STATICTEXT { NAME TRANGE; }
				COMBOBOX IDC_ACTOR_RECORD_RANGE
				{
					ALIGN_LEFT;
					SIZE 160,0;
					CHILDS
					{
						0, TDOCUMENT;
						1, TPREVIEW;
						2, TRENDER;
						3, TUSER;
					}
				}
			}

			GROUP
			{
				COLUMNS 4;
				STATICTEXT { NAME T6; } EDITNUMBERARROWS IDC_ACTOR_RECORD_FROM { ALIGN_LEFT; SIZE 60,0; }
				STATICTEXT { NAME T7; } EDITNUMBERARROWS IDC_ACTOR_RECORD_TO   { ALIGN_LEFT; SIZE 60,0; }
			}

			CHECKBOX IDC_ACTOR_RECORD_ATIME  { NAME TATIME; }
			CHECKBOX IDC_ACTOR_RECORD_REWIND { NAME TREWIND; }
		}

		GROUP
		{
			NAME TWHAT;
			BORDERSTYLE BORDER_GROUP_IN;

			SCALE_H; SCALE_V;
			COLUMNS 1;

			GROUP
			{
				COLUMNS 3;
				BORDERSIZE 4,4,4,4;
				SCALE_H; SCALE_V;

				CHECKBOX IDC_ACTOR_RECORD_POSITION   { NAME TRECORD_TYPE_POSITION ; }
				CHECKBOX IDC_ACTOR_RECORD_SCALE      { NAME TRECORD_TYPE_SCALE    ; }
				CHECKBOX IDC_ACTOR_RECORD_ROTATION   { NAME TRECORD_TYPE_ROTATION ; }
				CHECKBOX IDC_ACTOR_RECORD_PLA        { NAME TRECORD_TYPE_MORPH    ; }
				CHECKBOX IDC_ACTOR_RECORD_HIERARCHY  { NAME TRECORD_TYPE_HIERARCHY; }
			}
		}
	}
}
